src/components/Quiz/QuizzesModal.tsx
Atm the bg color of the Quiz modal is hardcoded to `white`, which generates the following result in dark mode
This PR uses the semantic token `neutral` to display the correct color between light and dark mode.
=> Fix quiz modal bg color

src/@chakra-ui/gatsby-plugin/components/Button.ts, src/@chakra-ui/gatsby-plugin/semanticTokens.ts, src/components/Button/Button.stories.tsx
Adds the correct disabled styles to the button's solid variant as defined in the DS. It also shows the disabled state in the button's stories.
=> Button - Fix disabled styles in solid variant

src/components/ButtonLink.tsx, src/components/TableOfContents/index.tsx
Simplify and use the new DS styles on the buttons with icons.
Changes the color of the Edit button's icon to the primary color.
~~This PR also sets `hideArrow` as always true in the `ButtonLink` as we never want to display the arrow for any link wrapped by this component.~~
=> Fix icon of the edit button

gatsby-ssr.tsx
Currently, we are preloading [3 fonts](https://github.com/ethereum/ethereum-org-website/blob/dev/gatsby-ssr.tsx). The problem is that the browser is always going to fetch them, even if it doesn't need all of them. Also, the font `Inter-Regular`, is preloaded in 2 different types, woff and woff2 (only one is going to be used).
Another problem it arises is the 
To optimize this, this PR only preloads the `Inter-Regular.woff2` font since
1. It is the most used font in the website
2. The woff2 format has a [pretty good adoption (~96% global)](https://caniuse.com/woff2) and its lighter than the others.
3. It doesn't mean that we are not going to load the rest of the fonts, they are going to be loaded but normally, not preloaded.
=> [Performance] Preload fonts

gatsby-browser.tsx, package.json, yarn.lock
Remove `Intl` polyfills from `formatjs` since there is good browsers coverage for them at this moment.
- https://caniuse.com/mdn-javascript_builtins_intl_numberformat
- https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat
=> [Performance optimizations] Remove intl polyfills

src/components/icons/Icons.stories.tsx
Per the [Storybook directory structure proposal](https://www.figma.com/file/Ne3iAassyfAcJ0AlgqioAP/DS-to-storybook-structure?node-id=47%3A74&mode=dev) the story for the icons should be placed in `Atoms / Media & Icons / Icons`
Also updates naming of the story to match the directory name, as it is only one story and does not need to be in an additional level.
This PR overall is promoting consistency of the story file usage.
N/A
=> chore(Icons.stories): update storybook directory placement

src/content/defi/index.md
In #10928 we used [the GlossaryTooltip React component on the DeFi markdown page](https://github.com/ethereum/ethereum-org-website/pull/10928/files#r1308431628) to showcase the new feature.
In #11021 we introduce a simpler implementation, that doesn't require us to add unnecessary React components to our markdown files. 
This PR reverts the addition of the GlossaryTooltip to the Defi page in #10928 and uses the original markdown syntax.
#10928
#11021
=> Revert glossary tooltip link in DeFi page

src/content/roadmap/statelessness/index.md
"Verkle Tree" URL is broken, this PR updates with correct URL.
Old broken link: https://ethereum.org/en../verkle-trees/
New link: https://ethereum.org/en/roadmap/verkle-trees/
=> Fixed broken URL for "Verkle Trees"

src/content/translations/it/roadmap/statelessness/index.md
Fixes a typo causing a broken link on the Italian statelessness page
#11038
=> Fix broken link on statelessness roadmap page (Italian)

src/content/community/get-involved/index.md
The URL link to EIP-1 had a typo. 
Changed https://eip.ethereum.org/EIPS/eip-1 to https://eips.ethereum.org/EIPS/eip-1
=> EIP-1 URL link change because of a typo that breaks the connection

src/content/security/index.md
Remove broken link in reading-web-security
The video in this link has expired, users cannot see the demo video in the article.
https://www.theverge.com/2017/9/18/16328172/sms-two-factor-authentication-hack-password-bitcoin
=> Remove broken link in reading-web-security

src/content/developers/docs/networks/index.md
Updates out of date content [Resolves #10921]
Replaced dead Sepolia faucet from Faucet list because it's down:
https://faucet.sepolia.dev/
with
Alternative PoW faucet:
https://sepolia-faucet.com/
=> Replaced dead Sepolia faucet.

src/content/developers/docs/apis/json-rpc/index.md
`data` may be empty, indicating no non-indexed arguments are in the log.
Example:
- https://etherscan.io/tx/0xa3b805acacb25da412a44bd9612a73464292fc684a400ab54f0a9626f7d9c3f2#eventlog
=> Receipt logs may contain no non-indexed arguments

src/data/community-events.json
[ETH Riyadh](https://ethriyadh.com/) unites developers and builders from Saudi Arabia and the other Middle East regions, nurturing their roles and connections in the Ethereum ecosystem.
We will hold Events from September 20 to October 15, 2023, and hope to join ETH Events.
=> Add ETH Riyadh 2023 to ETH events

src/content/developers/docs/consensus-mechanisms/pos/block-proposal/index.md
Two links on the [block proposal](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/block-proposal/) are broken. (PREREQUISITES section)
before
```
[proof-of-stake](src/content/developers/docs/consensus-mechanisms/pos/) and [block architecture](src/content/developers/docs/blocks/).
```
After
```
[proof-of-stake](/developers/docs/consensus-mechanisms/pos/) and [block architecture](/developers/docs/blocks/).
```
Updated both links 
https://github.com/ethereum/ethereum-org-website/issues/10972
fixed #10972
=> fixed two broken links issue  [Fixes #10972]

src/content/staking/pools/index.md
Line 63: changed "that represents" to "and represent"
Line 63 of the content/staking/pools page contains the sentence "Typically ERC-20 staking tokens are issued to stakers that represents the value of their staked ETH plus rewards". Replacing "that represents" with "and represent" improves comprehensibility.
None.
=>  content: improved comprehensibility in the staking/pools page

src/data/community-events.json
adding Ethereum Rio 2024 info into community-events.json (events page)
=> adding Ethereum Rio 2024 info into community-events.json (events page)

src/components/ButtonTwoLines/ButtonTwoLines.stories.tsx, src/components/ButtonTwoLines/index.tsx
Creates a button component with the following features:
- dedicated two distinct lines of text content with a main label and a helper label
- required icon
- ability to show the text in reverse stacking order
- ability to have the content left- or right-aligned (i.e. for pagination)
- renders the custom `Button` or `ButtonLink` component.
Note: part of the new DS as an intermediary step to creating a pagination button or the interactive simulator button that uses the design.
N/A
=> feat(components): add `ButtonTwoLines` component

src/content/developers/docs/networking-layer/portal-network/index.md
Discord made it so servers not in "community mode" couldn't have non-expiring invite links. So the Portal Network invite link on the Portal Network page expired. We just changed the server to "community mode" and this PR is adding a new non-expiring invite link
Replaced expired discord invite link with new non-expiry invite link for the Portal Network server
=> Update Portal Network discord invite link

src/pages/get-eth.tsx
- /get-eth had a bug where it was using the old Link component. Updated to InlineLink usage.
=> fix Link -> InlineLink on /get-eth

src/pages-conditional/wallets.tsx
- Add conditional for displaying CTA button on wallets page
=> add conditional for buttons in hero based on language

src/components/Simulator/NotificationPopover.tsx, src/components/Simulator/WalletHome/AddressPill.tsx, src/components/Simulator/WalletHome/WalletBalance.tsx, src/components/Simulator/screens/ConnectWeb3/Web3App.tsx, src/components/Simulator/screens/SendReceive/ReceiveEther.tsx, src/components/Simulator/screens/SendReceive/SendEther.tsx, src/components/Simulator/screens/SendReceive/SendFromContacts.tsx, src/components/Simulator/screens/SendReceive/Success.tsx, src/data/WalletSimulatorData.tsx
- Updates some copy around ether/ETH
- Updates `NotificationPopover` (previously named DemoOnlyPopover) and further rolls out its usage with more helper text
- Switched final "get wallet" link to use relative path, and thus keep it as an "internal" link that will not open in a new tab
- https://ethereumorgwebsitedev01-simpatches.gatsbyjs.io/en/wallets/
=> Interactive simulator patches

src/content/developers/docs/bridges/index.md
Changed link from `https://blog.li.fi/what-are-blockchain-bridges-and-how-can-we-classify-them-560dc6ec05fa`  to `https://li.fi/knowledge-hub/blockchain-bridges-and-classification/`
#11162
=> Fixed broken link

src/data/community-events.json
Add ETHDubai 2024 conference and hackathon dates (the page already has a few speakers and link to our call for paper).
=> Add ETHDubai 2024 conference and hackathon dates

src/components/Roadmap/RoadmapActionCard.tsx, src/templates/roadmap.tsx
Current styles:
This PR fixes the styles in the roadmap cards.
- Uses the `Heading` component with the desired size
- Fixes the spacing within the cards
=> Fix heading and spacing in roadmap cards

src/@chakra-ui/gatsby-plugin/styles.ts
- Switches kebab casing to camel case for styling property names
- Use direction-agnostic property names
Fixes kebab case warnings:
```log
Using kebab-case for css properties in objects is not supported. Did you mean marginBottom?
Using kebab-case for css properties in objects is not supported. Did you mean paddingLeft?
Using kebab-case for css properties in objects is not supported. Did you mean marginLeft?
Using kebab-case for css properties in objects is not supported. Did you mean marginTop?
```
=> Patch casing for styles

src/content/developers/docs/nodes-and-clients/index.md
=> Fixed spelling mistake in nodes and clients

src/components/Staking/StakingProductsCardGrid.tsx
- Switches to the `Heading` component for the product names on the staking product cards
- This fixes the alignment issue between the name and the icon (no more bottom margin)
Serves as a patch until full design system can be implemented
=> Fix alignment of staking product name and icon

src/components/Buttons/index.ts
Updates the entry point to the `Buttons` directory by using direct exports from the main `index` file.
This improves DX experience by only auto-completing imports of the components and type signatures from `./components/Buttons`
N/A
=> refactor(Buttons): use direct exports from index

src/components/Link.tsx
Currently the following React warning throws in development:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```
This points to the `BaseLink` component in the warning stack.
This PR wraps the component in Chakra's `forwardRef`.
In addition, a minor refactor with the `commonProps` object as the `ref` prop is used in all render conditions.
N/A
=> fix: add forward ref to `BaseLink`

.storybook/preview.ts
The `Inter` font-face set in the local was not exposed in the Storybook server.
Here, importing the css file `inter-font-face.css` from the `static` folder to `preview.ts` should provide the necessary exposure.
(Not quite sure how that was missed 🤔 )
N/A
=> fix(.storybook): import inter font css to preview

src/content/community/grants/index.md
=> fix: remove and replace outdated links from `/community/grants`

src/content/developers/docs/apis/json-rpc/index.md
- Updates the `data` input to `input` for `eth_call` on the `/json-rpc` page
Posted in Discord, request to update the param to match the [spec](https://github.com/ethereum/execution-apis/blob/584905270d8ad665718058060267061ecfd79ca5/src/schemas/transaction.yaml#L301-L303)
=> patch eth_call spec param

src/@chakra-ui/gatsby-plugin/components/Breadcrumb.ts, src/@chakra-ui/gatsby-plugin/components/index.ts, src/components/Breadcrumbs/Breadcrumbs.stories.tsx, src/components/Breadcrumbs/index.tsx, src/pages/bug-bounty.tsx, src/pages/roadmap/vision.tsx, src/templates/roadmap.tsx, src/templates/staking.tsx, src/templates/static.tsx, src/templates/upgrade.tsx
This PR updates the styling of the `Breadcrumbs` component.
- Moves styling to a component theme file.
- Gives control to the parent of the bottom margin spacing of the component container
N/A
=> refactor(Breadcrumbs): update style usage

src/components/Buttons/ButtonTwoLines/index.tsx
- Primary: use `body.medium` color for helper text with `outline` variant or `isSecondary` (per DS)
- Secondary: use `size` theme prop instead of `fontSize` to include `lineHeight` for both `Text` components
N/A
=> style(ButtonTwoLines): alter `size` and `color` prop usage for text

src/content/developers/docs/programming-languages/rust/index.md
Link for "An Introduction to Smart Contracts with Parity Ethereum Client" no longer exits. I just removed this. 
https://openethereum.github.io/wiki/Smart-Contracts
https://github.com/ethereum/ethereum-org-website/issues/11244
=> Remove link to missing webpage

src/content/developers/docs/frameworks/index.md
- Deprecate Truffle, Brownie, OpenZeppelin SDK as they are currently unmaintained
- Update links and description of Foundry, as Foundry has now new home
- Move unmaintained frameworks to the bottom of the list, as developers likely do not want to use something that no longer works
As above.
-
=> Update smart contract development frameworks

src/data/community-meetups.json
I added the needed json data for my meetup group to show on the ethereum.org meetup page, so more people can find us and connect!
=> Add Web3.NE group to Eth.org 'Meetups' Page 

src/components/Simulator/PulseAnimation.tsx, src/components/Simulator/constants.ts, src/components/Simulator/screens/ConnectWeb3/Browser.tsx, src/components/Simulator/screens/ConnectWeb3/Slider.tsx, src/components/Simulator/screens/ConnectWeb3/Web3App.tsx, src/components/Simulator/screens/ConnectWeb3/constants.ts, src/components/Simulator/screens/ConnectWeb3/index.tsx, src/components/Simulator/screens/SendReceive/SendFromContacts.tsx, src/data/WalletSimulatorData.tsx
- Adds a new starting screen/step to the Connect to Web3 sim
- Introduced a new `Browser` component for that step that starts with the user needing to go to the website for the dapp, after receiving an NFT as part of the story line
- Adjusts some copy to fit the new screen flow
- Typo correction, and added "Mint new NFT" to dapp account screen
https://ethereumorgwebsitedev01-simupdates.gatsbyjs.io/en/wallets/?sim=connect-web3#sim
None filed
=> Connect to Web3 sim updates

src/data/community-events.json
Updated the dates of ETH HK event to 22-24 Oct 2023.
Updated the dates of ETH HK event to 22-24 Oct 2023.
More details at https://twitter.com/EthereumHK.
=> Update ETH Hong Kong dates

src/components/FindWallet/WalletFilterSidebar/index.tsx, src/intl/en/page-wallets-find-wallet.json
- Setup reset filter label for translation
Fixes https://github.com/ethereum/ethereum-org-website/issues/11369
=> 'Reset Filters' button on find wallet page is always in English 

src/content/glossary/index.md
The "numerical" (`#`) section of the glossary is missing the Divider at the end. PR places one there, and removes the one currently underneeth the "Glossary" h1.
https://ethereum.org/en/glossary
See Divider usage at top of page:
vs Divider usage everywhere else on that page:
With this PR:
cc: @nloureiro
=> Move divider to end of numerical h2 (/glossary)

docs/ds-implementation.md
Linter has repeatedly been removing the leading whitespace used in this markdown document. This PR restores the spacing using bullets so they won't be removed by the linter in the future.
None filed
=> DS docs patch

src/components/Modal.tsx
- Extend interface for Modal component to accept `ModalContentProps` and `size` property picked off of `ModalProps`.
- `size` is passed to parent `ChakraModal` element, with `"xl"` fallback
- `ModalContentProps` are spread as `...restProps` onto the `ModalContent` element to allow for styling props to be passed when component is instantiated
- None filed, result of Discord discussion
=> Update Modal interface to accept styling props

src/content/history/index.md
- Updates the Constantinople entry to include mention of ETH issuance reduction via EIP-1234
In the `/history` page, the [Byztantium](https://ethereum.org/en/history/#byzantium) upgrade makes notes of the issuance reduction from 5 -> 3 ETH, but the [Constantinople](https://ethereum.org/en/history/#constantinople) upgrade does not mention the drop from 3 -> 2.
=> Add detail to history page

src/@chakra-ui/gatsby-plugin/components/Heading.ts
This PR addresses the `lineHeight`s not being applied correctly for the `Heading` component. Based on breakpoint, the sizes either needed to be flipped or replaced to match the DS
N/A
=> fix(theme/Heading): flip `lineHeight`s rendered to match DS

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
Changed "is" to "in" in the sentence "To get an average price you read the cumulative price **is** two points in time".
=> Fix bad grammar/improve understandability on Uniswap V2 tutorial

gatsby-node.ts
- add .replace(/\\./g, "/") to `const dirname = path.resolve('./)`
=> Add .replace(/\\./g, "/") to gatsby.node 

src/content/bridges/index.md, src/content/community/get-involved/index.md, src/content/community/grants/index.md, src/content/community/research/index.md, src/content/contributing/translation-program/content-buckets/index.md, src/content/contributing/translation-program/faq/index.md, src/content/contributing/translation-program/playbook/index.md
This Pull Request addresses multiple typographical and grammatical errors across different sections of the documentation. The changes aim to improve readability and clarity for users.
**Detailed Changes:**
1. Corrected the word "phrases" to "phases" in the translation workflow hyperlink text.
2. Corrected "non-monteary" to "non-monetary" in the translation compensation section.
3. Removed extra closing brackets in the "5) Use case pages" section.
4. Fixed a typo from "FGPAs" to "FPGAs" (Field-Programmable Gate Arrays) in the context of "ecdsa on FPGAs".
5. Added a missing underscore to correctly format text in italic using markdown.
6. Corrected "directons" to "directions".
7. Corrected "blockchains protocols" to "blockchain protocols".
- No specific related issue, this PR focuses on …
=> Documentation Cleanup: Typos and Grammar Fixes

src/content/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/de/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/es/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/fr/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/id/developers/docs/scaling/layer-2-rollups/index.md, src/content/translations/it/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/ja/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/pl/developers/docs/scaling/layer-2-rollups/index.md, src/content/translations/pt-br/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/ro/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/sl/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/tr/developers/docs/scaling/optimistic-rollups/index.md, src/content/translations/zh/developers/docs/scaling/optimistic-rollups/index.md
Replaced link for [https://research.paradigm.xyz/optimism](https://research.paradigm.xyz/optimism) with [https://www.paradigm.xyz/2021/01/how-does-optimisms-rollup-really-work](https://www.paradigm.xyz/2021/01/how-does-optimisms-rollup-really-work)
#11444
=> Fix url for Optimism Rollup's

src/pages/gas.tsx
Make "Use Layer 2" button go to layer 2 page instead of the get eth page on the gas learning page
=> Fix layer 2 button on gas page

src/content/community/support/index.md
I have fixed the broken Discord link for CryptoDevs by replacing it with a new one.
Previous link : https://discord.com/invite/Z9TA39m8Yu
New link : https://discord.com/invite/5W5tVb3
=> fix: CryptoDevs broken discord link

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Erigon has provided pre-built binaries on their [GitHub releases page](https://github.com/ledgerwatch/erigon/releases) since release [v2.39.0](https://github.com/ledgerwatch/erigon/releases/tag/v2.39.0) (released February 19, 2023), so the note is no longer accurate.
=> Remove note about Erigon binaries

src/content/developers/docs/evm/index.md
Small change, add revm to the list: https://github.com/bluealloy/revm
=> oneliner, add revm to list of standalone EVMs

src/components/Hero/HubHero/index.tsx
- Adds `wordBreak="break-word"` to HubHero to avoid overflow of header and paragraph
=> Add wordBreak style to avoid overflow bug in HubHero

src/@chakra-ui/gatsby-plugin/styles.ts
Uses the defined background semantic token for the body bg color. This will fix the flashing color issue.
More context about this fix in [this comment](https://github.com/ethereum/ethereum-org-fork/pull/105#issuecomment-1793285311) from @TylerAPfledderer.
Fixes #7727
=> Fix flashing color mode issue

src/content/developers/docs/apis/json-rpc/index.md
Update `eth_sendTransaction` at index.md according to https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.yaml#L385
The method `eth_sendtransaction` at https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction is not according to the execution layer api specs as in https://ethereum.github.io/execution-apis/api-documentation/
=> Update eth_sendTransaction according to ethereum execution-apis documentation

src/content/desci/index.md
**Description:**
This pull request addresses an issue where the "Bio.xyz: get funded for your biotech DAO or desci project" link in the ['Get involved'](https://ethereum.org/en/desci/#get-involved) section incorrectly directed users to the Molecule website. The link has been updated to point to the intended destination, https://www.bio.xyz, ensuring users are correctly guided to Bio.xyz resources.
closes #11579
=> Fix Incorrect URL for Bio.xyz Link in 'Get Involved' Section

src/intl/en/common.json, src/pages-conditional/wallets.tsx
- Change "Guides hub" -> "How-to guides"
- Change "Interactive tutorial" -> "How to use a wallet"
Fixes https://github.com/ethereum/ethereum-org-website/issues/11362
=> Improve copywriting: rename guides hub and change wallet simulator CTA

src/content/developers/docs/apis/backend/index.md
This pull request addresses typographical errors in the Backend API libraries documentation that affect the accessibility of external resources.
Changes included:
1. Fixed the Tokenview documentation link text from "tokeniew" to "tokenview" and updated the hyperlink to the correct URL. Previously, navigating to https://ethereum.org/sl/developers/docs/apis/backend/#available-libraries and clicking on the Tokenview [Documentation](https://services.tokeniew/docs?type=api) link would result in a 404 error. 
2. Corrected the service description title for GetBlock from "developement" to "development".
These corrections will enhance the user experience by providing accurate information and functioning links, facilitating a seamless navigation experience in the API documentation.
=> Fix documentation typos for GetBlock and Tokenview link 404

src/components/Search/index.tsx
In prod when loading a page on a desktop screen size, the `SearchIconButton` icon would render first, then `SearchButton`. This is due to the `useMediaQuery` check not running immediately upon painting of the content.
This Pr switches to the style prop strategy by using Chakra's `hide*` props to change the display of the components rather than their DOM rendering.
N/A
=> fix(Search): render button components with the `hide*` props

src/content/developers/docs/scaling/zk-rollups/index.md
Using `Merkle tree` is not clear, so replace it with  `Merkle tree root`
=> Use Merkle tree root be scpecific

src/content/developers/docs/programming-languages/rust/index.md
The link to "An Intro to Secret Contracts" was broken as per issue #11643 therefore I added the updated link.
Fixes #11643 
Just updating the link since the current link to https://blog.enigma.co/getting-started-with-enigma-an-intro-to-secret-contracts-cdba4fe501c2 is outdated, so I updated it to https://docs.scrt.network/secret-network-documentation/development/secret-contract-fundamentals/secret-contracts-introduction
=> Fixed links as per issue #11643

src/content/developers/docs/networks/index.md, src/content/translations/es/developers/docs/networks/index.md, src/content/translations/fr/developers/docs/networks/index.md, src/content/translations/it/developers/docs/networks/index.md, src/content/translations/ja/developers/docs/networks/index.md, src/content/translations/pt-br/developers/docs/networks/index.md, src/content/translations/ru/developers/docs/networks/index.md, src/content/translations/tr/developers/docs/networks/index.md, src/content/translations/zh-tw/developers/docs/networks/index.md, src/content/translations/zh/developers/docs/networks/index.md
1. https://faucet.sepolia.dev/ was down for long time as in issue #11012 
2. Also https://fauceth.komputing.org was down.
3. Remove and add some faucets in Japanese section.
=> Remove dead Sepolia faucet

src/components/LeftNavBar/index.tsx
resolved the problem of "menu list" **hidden** under "title card". 
**changes:** add `zIndex` to `LeftNavBar as "dropdown", which is 100, while `TitileCard` has set as `docker`, which is 10. Now, zindex value 100>10, menu can be set at front. 
Fixes: https://github.com/ethereum/ethereum-org-website/issues/11410
Fixes: https://github.com/ethereum/ethereum-org-website/issues/11304
=> fix: hidden menu list item

src/content/developers/docs/smart-contracts/deploying/index.md
Truffle is [being sunset](https://consensys.io/blog/consensys-announces-the-sunset-of-truffle-and-ganache-and-new-hardhat?utm_source=github&utm_medium=referral&utm_campaign=2023_Sep_truffle-sunset-2023_announcement_) and developers are encouraged to transition to other tools to avoid disruptions to development workflows. To avoid confusion, we'll have to remove the tool from the listing of contract deployment tools (which I've done in this PR). 
- Removed links to documentation for deploying smart contracts with Truffle
- Replaced external link to Truffle deployment workflow with link to Forge's contract deployment guide 
- Added an internal link to source code verification (ie. to show developers they'll need to verify contracts after deploying)
=> Remove Truffle from deployment tools

src/content/developers/docs/smart-contracts/testing/index.md
Removed Truffle/Ganache from the documentation on testing smart contracts as both tools are [being sunset](https://consensys.io/blog/consensys-announces-the-sunset-of-truffle-and-ganache-and-new-hardhat?utm_source=github&utm_medium=referral&utm_campaign=2023_Sep_truffle-sunset-2023_announcement_). 
- Removed mentions of Truffle/Ganache in the page 
- Replaced Ganache with Forge for fork testing 
- Added a new tutorial for running unit tests in Solidity with Foundry
=> Remove Truffle/Ganache from smart contract testing tools

src/components/Buttons/Button.tsx, src/components/FindWallet/WalletTable/index.tsx, src/utils/matomo.ts
Implement updates to Matomo tracking for wallet pages
- Removes event when collapsing wallet details; only logs when item is expanded
- Differentiate external links to website vs Twitter vs Discord for wallets
- "Check out ___" button logging patched -- This required updating the `Button` component which was not utilizing the MatomoEventOptions being passed.
- Small refactor to use guard clauses instead of nesting primary logic inside `if` statements inside `matomo.ts`
- Partially resolves #11521 [(Notion Card)](https://www.notion.so/efdn/Event-tracking-issues-fix-14550da4fa0b4a5a895e7910848d8f36?pvs=4)
cc: @konopkja Left a note for you about remaining item in that Notion card
=> Matomo updates

src/pages/get-eth.tsx
Patches a broken i18n string on the `/get-eth` page.
There are two cards in this section that link to the wallets page... we should probably try and avoid this redundancy, but would like to address that separately to just patch the i18n key being displayed at the moment
https://ethereum.org/en/get-eth/
=> Patch i18n string key

src/content/developers/tutorials/run-node-raspberry-pi/index.md, src/content/developers/tutorials/set-up-web3js-to-use-ethereum-in-javascript/index.md, src/content/developers/tutorials/smart-contract-security-guidelines/index.md, src/content/developers/tutorials/testing-erc-20-tokens-with-waffle/index.md, src/content/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md, src/content/developers/tutorials/waffle-say-hello-world-with-hardhat-and-ethers/index.md
This pull request introduces a series of grammar and typo corrections across different tutorials related to Ethereum development. The changes focus on enhancing the clarity, accuracy, and readability of the documentation. No functional code changes are included.
1. **Update Grammar in Project Setup Instructions**: Corrected a grammatical error in the Waffle tutorial to improve clarity in the project setup instructions.
2. **Fix Typo in .gitattributes Filename**: Corrected the filename from `.gitattributs` to `.gitattributes` in the same tutorial, ensuring accurate file naming conventions.
3. **Fix Typos in Test Description of 'AmIRichAlready' Tutorial**: Addressed two typographical errors in the testing section of the 'AmIRichAlready' contract tutorial. Changes include clarifying a …
=> Fix various grammatical errors and typos in Ethereum tutorials

src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/ethash/index.md
The link to the discussion of "ETHASH: The use of 'SHA3'"was broken as per issue [#11715](https://github.com/ethereum/ethereum-org-website/issues/11715) therefore I added the updated link.
Fixes [#11715](https://github.com/ethereum/ethereum-org-website/issues/11715)
Just updating the link since the current link to https://eips.ethereum.org/EIPS-1803 is broken, so I updated it to https://eips.ethereum.org/EIPS/eip-1803
=> Fixed links as per issue #11715

src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
Just a tiny typo fix:
`s/concentenation/concatenation/`
=> Small typo fix

src/content/developers/tutorials/using-websockets/index.md
typo fix
There is no issue. I found the `eth_subscription` typo because someone using *web3.py* was looking at the documentation here for examples on `eth_subscribe` types.
Also the Alchemy documentation linked seems to be behind a permissions wall and was inaccessible when I tried to navigate there.
=> Minor updates to websockets tutorial page

src/components/MeetupList.tsx
Fixes #11902
Added the `isExternal` prop to the `LinkOverlay` component.
This pull request addresses the issue described in Issue #11902 
Related issue link: https://github.com/ethereum/ethereum-org-website/issues/11902
=> Update MeetupList.tsx to open links in new tabs [Fixes #11902]

src/components/PageMetadata.tsx
- Removes `NEXT_PUBLIC_SITE_URL` env var now that Next.js migration is complete.
- Replaces usage with `SITE_URL` constant which is set to `https://ethereum.org`
https://www.notion.so/efdn/Remove-NEXT_PUBLIC_SITE_URL-46c6bc7923de425ea50dcafe53b4e0cf?pvs=4
=> chore: remove deprecated env var usage

src/components/PageMetadata.tsx
- Removes the "en" path prefix from the canonical URL being generated inside `PageMetadata` component
With the Next.js migration, English pages no longer use the `/en/` path prefix, and going to these routes will redirect to `/**`. As such this, this is causing cyclical logic within our Algolia search crawler:
- Crawling https://ethereum.org/ is skipped, in favor of "canonical" https://ethereum.org/en/
- And https://ethereum.org/en/ is skipped by redirecting back to https://ethereum.org/
=> Fix canonical English URLs to fix Algolia search crawling

src/hooks/useClientSideGitHubContributors.ts, src/hooks/useClientSideGitHubLastEdit.ts, src/lib/constants.ts
=> [HOTFIX] Deprecate OLD_CONTENT_DIR

src/layouts/Docs.tsx, src/layouts/Static.tsx, src/layouts/Tutorial.tsx, src/layouts/UseCases.tsx, src/lib/utils/editPath.ts
- Adds a util helper function to get the edit path for markdown files
- Implement in layouts: Static, UseCases, Docs, Tutorial
=> Fix: Edit path for markdown files

src/components/PageMetadata.tsx
- fix: remove trailing slash from canonical url
- fixes Algolia search crawler issues related to canonical URL
=> fix: remove trailing slash from canonical url

src/components/CalloutBanner.tsx, src/pages/get-eth.tsx, src/pages/stablecoins.tsx
- Switches to using `imageWidth` prop instead of `maxImageWidth` prop in both `get-eth` and `stablecoins` page components, fixing sizing and overflow issues (especially seen on tablet sizes)
- `maxImageWidth` prop no longer being used by any components; removed from usage within `CalloutBanner` to prevent confusion in the future over which to use
- Replaced `alignSelf="center"` with `mx="auto"` which fixes mobile alignment issue
https://www.notion.so/efdn/BUG-small-visual-issue-in-Callout-banner-c6e1b5a94ec14a90bf3f8934d5a7b171?pvs=4
- **https://deploy-preview-11958--ethereumorg.netlify.app/get-eth**
- **https://deploy-preview-11958--ethereumorg.netlify.app/staking**
- **https://deploy-preview-11958--ethereumorg.netlify.app/stablecoins**
Gatsby archive link for comparisons (goal):
- …
=> Fix CalloutBanner imge sizing/layout bugs

public/content/community/get-involved/index.md
I've fixed the broken Discord link for EthCatHerders and replaced it with the new working link.
Previous link: https://discord.io/EthCatHerders
New link: https://discord.com/invite/Nz6rtfJ8Cu
=> fix: EthCatHerders broken discord link

public/content/glossary/index.md
I've fixed the issue that was making the definition and term for internal transactions not show up in the glossary list. Look at the screenshots for a clearer understanding.
=> fix: Internal transaction term visibility in glossary list

.gitignore
Since we don't utilize a committed/shared set of vscode settings, this adds the `.vscode` folder back to the `.gitignore` file so users can save their own settings without potentially committing them. 
This was previously present in the Gatsby repo and we accidentally regressed during the Next.js migration.
=> build: add .vscode folder to .gitignore

src/components/Search/index.tsx
- Adds hover color and rotation styling to "tablet" search icon
- Desktop (>xl) screens left unchanged given "outline button" styling with a label
- Mobile menu left unchanged
Note: Other nav icons using a 10deg rotation. Went with 5deg here since the magnifying glass looked a little strange when rotating too much. Open to feedback/changing
Related to navigation updates
=> style: hover color and rotation for search icon

src/lib/api/calendarEvents.ts, src/lib/interfaces.ts
The `pastEventLink` property was resulting `undefined` in some cases causing the build to fail when attempting to serialize. This value is not being consumed by the frontend and is not needed. PR removes this variable which resolved build errors. 
Current `dev` branch build failures:
```
Error serializing `.communityEvents.pastEventData[2].pastEventLink` returned from `getStaticProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```
=> fix: remove unused property causing build breaks

README.md
Change yarn start to yarn dev and localhost:8000 to localhost:3000 in README file  [Fixes #12039]
- Change command `$ yarn start` to `$ yarn dev`
- Change port `localhost:8000` to localhost:3000`
- Change description for running Next.js locallly
#12039
=> Change yarn start to yarn dev and localhost:8000 to localhost:3000 in README file

src/lib/types.ts, src/pages/contributing/translation-program/contributors.tsx
Currently in the `Contributors` page,  there is a flatmap using the `allTimeData` json to create a simplified array of translator info `translatorData`. 
A type error currently throws: `Property 'data' does not exist on type '{}'`
This is because a type is not being inferred for the json file and is only providing an empty object.
This PR creates the shape for this data structure so there is type safety in the flatmap.
The shape was generated using [Transform Web Converter App](https://transform.tools/json-to-typescript) and double-checked for any undefined fields with the data used.
According to the shape generated, there should be no fields in the JSON structure that would be undefined or null.
N/A
=> fix(contributors): create shape for allTimeData json type

src/intl/en/page-bug-bounty.json
Making it even more clear that one should not report a vulnerability to multiple parties without prior agreement.
=> Bug Bounty text clarification

docs/api-keys.md, src/lib/api/ghRepoData.ts
This PR simplifies the GH tokens we currently use for the site. Instead of having 2 tokens, it uses just one for all the GH calls we need to make.
- Removes the `GITHUB_TOKEN_READ_ONLY` env var
- Refactor the code to use `NEXT_PUBLIC_GITHUB_TOKEN_READ_ONLY` instead.
Both tokens were of the same type, Github read-only tokens. These were used to fetch commits for a given file and to fetch metadata from repos (star count, programming langs, etc).
=> Unify GH tokens

package.json, src/components/Link.tsx, src/components/Staking/StakingHowSoloWorks.tsx, src/components/Staking/StakingLaunchpadWidget.tsx, src/lib/utils/cx.ts, yarn.lock
Currently, when the user loads a page, all the internal navigation links display the `href` without the locale that the user is using.
For example, when you load https://ethereum.org/de/layer-2, all the internal links ignore the `de` locale and build the href from the root level.
The problem seems to come from the `Link` component imported from [`@chakra-ui/next-js`](https://github.com/chakra-ui/chakra-ui/tree/main/packages/next-js). I'll try to reproduce this bug on a codesandbox later and open an issue in that repo.
For the scope of this PR, it:
- Removes the dependency
- Implements a custom integration between Chakra & Next Link component
=> Fix i18n links not having the locale in hrefs

docs/best-practices.md
Delete React.FC in sample code because of code-conventions change
Delete React.FC in sample code because of code-conventions change 
https://github.com/ethereum/ethereum-org-website/blob/dev/docs/code-conventions.md#directly-annotate-the-props-object
Related PR
https://github.com/ethereum/ethereum-org-website/pull/12014
=> Delete React.FC in sample code because of code-conventions change

README.md
The POAP logo path was wrong, upon going through the files, I figured out the right path and changed it.
Changed the poap-logo.svg path from "src/assets/poap-logo.svg" to "public/poap-logo.svg"
Issue - "Missing Images in README.md File #12068"
Link - https://github.com/ethereum/ethereum-org-website/issues/12068
=> fixed POAP logo render

src/lib/utils/editPath.ts
Updates construction of the "edit path" url to use `new URL()` when adding the base path. Current production uses `join` which collapses the repeated slashes in `https://` and causes broken paths. 
- Fixes #11994
=> hot-fix: update page edit path logic [Fixes #11994]

README.md
- Adds `public/assets/` to the src path for the logo in repo README
=> fix: README logo image src path

src/components/Search/SearchModal.tsx, src/components/Search/utils.ts
- Maintain scroll position when closing search modal
- Fix modal overlay (`.DocSearch.DocSearch-Container`) to screen
Bug: Modal overlay stays at top, and scroll position returns to the top after closing search modal:
https://github.com/ethereum/ethereum-org-website/assets/54227730/d96f9c10-8ac9-4500-8ae8-674db4b216d8
=> fix: search modal scroll position and overlay

src/components/History/NetworkUpgradeSummary.tsx
Hello,
Since there was no space before the **block/epoch/slot** values for each entry on the _/history_ page, I add a span tag for the corresponding value with **marginLeft** style property, having value of 4px.
With these code changes in place, there has been decent space added before the values on the history page.
I hope these code changes meet the requirements asked.
If at all there are any changes required, then do let me know about the same.
Issue: #12101
=> Fix #12101: Bug: missing space in history entries

src/pages/dapps.tsx
Skiff is defunct and shutting down in 6 months, this PR removes it.
https://skiff.com/data-migration
=> fix: removed skiff (defunct and shutting down in 6 months)

src/data/community-events.ts
Hi guys!
Am a Core-contributor for ETHSafari. I added the dates and description to the event that we are planning in Kenya for this year from 9 -  15 September.
Tested locally, and all looks good, see image below:
Let me know if you have any questions.
Thanks for your service!
=> Added ETHSaafri event info for 2024

public/content/developers/docs/consensus-mechanisms/pos/attestations/index.md
When you go to the book's current link, it says this version is old and provides a newer version link so it is updated to the newer version.
When you go to the current link, it has a warning at the top of the page:
Fixes #12144
=> Update eth2book link

src/components/Table/index.tsx, src/layouts/Static.tsx
Adds relative position to the table container to avoid overflows.
- Fixes #12119
- Fixes #7163
=> Fix table overflow

src/components/LanguagePicker/useLanguagePicker.tsx, src/intl/ar/page-languages.json, src/intl/fa/page-languages.json, src/intl/fil/page-languages.json, src/intl/sl/common.json, src/intl/uk/page-languages.json
- Removes all empty strings from the `intl` folder (will fallback to English string)
- Improve check inside `useLanguagePicker` to check if we have an internal translation available or not
If the output of `t()` matches the English name _or_ the i18n key, then this string isn't available internally and Intl.DisplayNames used as fallback to display the locale name.
=> Fix fallback for locale display names

src/components/Nav/Menu/LvlContent.tsx, src/components/Nav/Menu/SubMenu.tsx, src/components/Nav/Menu/index.tsx, src/components/Nav/Menu/useNavMenu.ts, src/components/Nav/Menu/useSubMenu.ts
- Adds animations for navigation menu using framer-motion
- Opacity fade-in and unfolding for entire menu on opening
- Opacity fade-in and slight horizontal scaling effect for sub-menus on opening
- #12125
=> feat: add desktop nav menu animations

src/components/Footer.tsx
To fix the weird social button outline, the margin has been removed from `Icon` component and added to the `BaseLink` component
[Fixes #12213]
=> fix: footer social buttons strange outline [Fixes #12213]

public/content/developers/docs/development-networks/index.md, public/content/translations/pt-br/developers/docs/consensus-mechanisms/pow/mining/index.md
Fix a couple spelling and whitespace bugs spotted with `yarn markdown-checker` during intl review
=> fix: spelling and whitespace bugs

src/components/Hero/HubHero/index.tsx
If a `title` is not passed in props, use the `header` as H1 instead.
cc: @nloureiro this probably has design system considerations
Small fix to error syntax
Fixes #12253
Related #12252
=> Use `header` as H1 if `title` is missing in HubHero

src/pages/bug-bounty.tsx
Adds H1 in place of the current paragraph tag to the bug bounty page
_Note: The styling is close but not perfect because of the different line heights on paragraphs/H1s, but given that this is non-standard styling, it didn't seem worth the time to make it perfect :)_
Fixes #12255
Related #12252
=> Add H1 to bug bounty page

src/components/StablecoinBoxGrid.tsx, src/intl/en/page-stablecoins.json, src/pages/stablecoins.tsx
Added a disclaimer banner stating the potential risk involved with Algorithmic coins,
Added the key for dynamic rendering and translation- ' page-stablecoins-algorithmic-disclaimer'
=> added disclaimer (for Algorithimic stablecoins) to stablecoin page

src/components/FindWallet/WalletTable/WalletEmptyState.tsx, src/components/FindWallet/WalletTable/index.tsx, src/intl/en/page-wallets-find-wallet.json, src/pages/wallets/find-wallet.tsx
This PR adds the WalletTable empty state as defined in the [design](https://www.figma.com/file/rv850lIICwOwRnyqSdtZED/Redesign-find-wallet?type=design&node-id=1842-22283&mode=design&t=28QQPGqW3a5BGm31-0). This PR branches off https://github.com/ethereum/ethereum-org-website/pull/12191 as it builds on top of the new wallet table layout, so should be merged first.
- adds `WalletEmptyState` component
- adds `WalletEmptyState` i18n strings
- displays `WalletEmptyState` if filtered results throw no results
This PR needs to be merged BEFORE https://github.com/ethereum/ethereum-org-website/pull/12191
https://deploy-preview-12232--ethereumorg.netlify.app/wallets/find-wallet
Update the filters/`wallet-data.ts` to have 0 results or just pass an empty array as `walletData` to `WalletTable` in …
=> Wallettable empty state

src/components/FileContributors.tsx
Hides the contributor's profile link if the url doesn't exist.
Fixes #12269
=> Hide contributor's profile link if the url doesn't exist

src/components/LanguagePicker/index.tsx, src/components/LanguagePicker/useLanguagePicker.tsx, src/components/PageMetadata.tsx
- Add matomo event when user focuses in language picker filter input
- De-duped to only send one event per session, per language (resets if user follows a language result and switches languages)
cc: @konopkja
=> feat: add matomo event to lang picker input

src/components/TranslationBanner.tsx
Temporarily removes 'View in English' button from the translation banner, as it is currently causing thousands of 404s due to a logic bug.
#12292
=> Remove View in English button from Translation Banner

src/components/AssetDownload/index.tsx
Disables the SVG download functionality, whilst we sort the bug in #12267
#12267
=> Disable SVG URLs in AssetDownload

public/content/translations/fr/security/index.md, src/intl/fr/page-learn.json
In this pull request, I have corrected the French spelling errors on the web page.
"Qu'est-ce qu'Ethereum&nbsp;?" by "Qu'est-ce qu'Ethereum ?"
I have reviewed the text and made necessary adjustments to ensure proper spelling and grammar in French.
No specific issue was opened for this task.
=> fix  Ethereum&nbsp spelling in french learn page

public/content/glossary/index.md, src/intl/en/glossary.json
- Adds glossary term for proto-danksharding
- Adds GlossaryDefinition component using proto-danksharding to /glossary page
Fixes: https://github.com/ethereum/ethereum-org-website/issues/9026
=> Add glossary definition for proto-danksharding

src/intl/en/glossary.json
Fixed the hyperlink in the glossary on the definition of "consensus client" -- it should work well now
Fixes issue #12318
=> fix: fix hyperlink in glossary on consensus client (fixes #12318)

src/middleware.ts
Adds a trailing slash to redirects coming from the middleware.
=> hot-fix: add trailing slash to redirects

public/content/developers/docs/data-and-analytics/block-explorers/index.md, public/content/enterprise/index.md, public/content/translations/de/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/de/enterprise/index.md, public/content/translations/es/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/es/enterprise/index.md, public/content/translations/fr/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/fr/enterprise/index.md, public/content/translations/hu/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/hu/enterprise/index.md, public/content/translations/it/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/it/enterprise/index.md, public/content/translations/ja/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/ja/enterprise/index.md, public/content/translations/pt-br/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/pt-br/enterprise/index.md, public/content/translations/tr/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/tr/enterprise/index.md, public/content/translations/zh/developers/docs/data-and-analytics/block-explorers/index.md, public/content/translations/zh/enterprise/index.md
The block explorers list is not in alphabetical order, this PR updates it so it is with the exception of Etherscan remaining at the top.
I've also updated references to Sirato block explorer to be Chainlens as its been rebranded.
This pull request fixes issue #12306
=> Clean up block explorers list (fixes #12306)

public/_redirects
- Remove a 301 redirect from `/developers/docs/scaling` to itself
A previous commit that removed a deprecated redirect introduced an issue where the subpage `/developers/docs/scaling` redirects back to itself, causing an infinite redirect loop.
Issue #12330 describes that this only happens when trying to visit the page, doesn't happen when routing through the navigation. This is probably because during the visit, Netlify triggers the redirect, while navigation uses Next.js to push a new path without triggering a reload/redirect.
To fix this issue, we simply remove the redirect in `_redirects` for Netlify.
[Issue #12330 - Navigating directly to the scaling docs enters a redirect loop](https://github.com/ethereum/ethereum-org-website/issues/12330)
=> fix: infinite redirect loop at developers/docs/scaling [FIXES #12330]

src/components/CardList.tsx
Fixed this by passing the `isExternal` prop to the `LinkOverlay` component.
=> Fix CardList external links not opening in new tabs

src/components/Nav/Menu/index.tsx, src/components/Nav/index.tsx, src/lib/constants.ts
- Removes delay duration when hovering over a nav menu item (menu now opens immediately upon hovering)
- Extends the click/hover zone for each button to the bottom of the nav bar, eliminating dead-space between the buttons and the menu that opens which could close the menu if cursor is paused in this space
Bug surfaced from #12125 review
cc: @konopkja
=> fix: nav item hover zone, opening delay duration

src/pages/quizzes.tsx
This PR adds the missing `common` namespace prefix for quizzes title
=> fix: adds missing namespace prefix for quizzes title

public/content/history/index.md, src/data/NetworkUpgradeSummaryData.ts
- Updates /history page with details from Dencun upgrade
Dencun updates
=> feat: update history page for dencun

src/intl/en/glossary.json, src/intl/fr/glossary.json, src/intl/hu/glossary.json, src/intl/it/glossary.json
Glossary entry for "assert" is incorrectly titled "asset".
Typo was found in 4 translations. Fixed for all.
=> typo: change "asset" to "assert" in glossary

public/content/developers/docs/programming-languages/dart/index.md
I've added some new video tutorials and a video playlist for Dart language, which I think will be helpful for everyone.
I've just added:
- [Flutter Dapp Simple Wallet](https://youtu.be/JMfIBpuAhKA?si=LdhvRORRZKfMD0Cn) and [First Flutter DApp - Solidity, Truffle, Ganache](https://youtu.be/bHw2gQZxJ_s?si=8EyLJqOI-AYRYt7r) - these videos show how to make simple dapps in Flutter using Truffle and Ganache.
- [Mobile Blockchain Developer Bootcamp Course With Solidity & Flutter](https://youtube.com/playlist?list=PL4V4Unlk5luhQ26ERO6hWEbcUwHDSSmVH&si=qBtm5lqsB6ePAZn6) - full stack mobile blockchain developer course playlist
=> Add new tutorial videos for Dart language

src/components/Nav/Mobile/HamburgerButton.tsx
Warning seen in the console
```
Warning: React does not recognize the isSecondary prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase issecondary instead. If you accidentally passed it from a parent component, remove it from the DOM element. at button
```
Fixes this warning by using our custom `IconButton` component instead of chakra native one that knows how to implement the `isSecondary` prop.
=> IconButton `isSecondary` warning

public/content/developers/docs/programming-languages/golang/index.md
This PR adds Covalent's Golang SDK apart of `GO PROJECTS AND TOOLS` under programming languages, Golang
Covalent's Golang SDK -> https://github.com/covalenthq/covalent-api-sdk-go
=> docs: Add docs for covalent's Golang SDK

src/components/LanguagePicker/useLanguagePicker.tsx
- Update `useLanguagePicker.tsx` to remove error throwing when a source or target locale display name is not found
- Adds `console.warn` instead, and adds an empty string fallback to ensure values are never `undefined`
- https://github.com/ethereum/ethereum-org-website/pull/12204#pullrequestreview-1885619513
=> refactor: useLanguagePicker warning and fallback

public/content/developers/docs/standards/tokens/erc-4626/index.md
In the ERC4526 the Withdraw event parameter is described as `shares` not `share`
Changing documentation to align with the [EIP for ERC4626 ](https://eips.ethereum.org/EIPS/eip-4626#events).
This also aligns with how it is implemented in e.g. sDAI.
=> ERC4526 withdraw event documentation wrong field name for shares

src/components/FindWallet/WalletTable/index.tsx, src/pages/wallets/find-wallet.tsx
This PR makes the "Filters" label clickable to allow opening filters menu on mobile
=> chore: make Filters clickable on mobile to open filters menu

.github/workflows/import-community-events.yml
- Updates `import-community-events.yml` workflow to commit results to a branch and post as a PR
- Adds "name" fields to steps for readability
- (Templated from `get-crowdin-contirbutors.yml`)
=> Update workflow to commit to branch and post as PR

public/content/developers/docs/apis/json-rpc/index.md
Add missing info about `safe` and `finalized` blocks to `json-rpc` docs.
=> Add missing info about `safe` and `finalized` blocks

src/components/Glossary/GlossaryTooltip/index.tsx, src/components/Tooltip/index.tsx
Avoids the overwriting of the prop `onOpen` and calls it after it is handled internally.
Fixes #12592
=> Fix Tooltip overwritten prop

src/components/Staking/StakingProductsCardGrid/utils.ts
- Fixes a bug introduced in #11477 with the logic for the "battle tested" indicator on staking products.
- That PR switches this logic to use guard statements, but returning after the first check was causing the "Caution" flag (6-12 months live) to take precedent even if the product had been around over 1 year ("Valid" flag). This flips the ordering so it will return the best possible flag, falling back to the "warning" flag.
Surfaced with PR #11477
Can see bug here (before merging): https://dev--ethereumorg.netlify.app/en/staking/saas/#saas-providers (Notice all products are listed with a yellow caution icon for "battle tested")
=> fix: battle tested logic

public/content/developers/docs/programming-languages/python/index.md
Brownie is officially no longer maintained.
`py-devp2p` and `py-wasm` have had no updates for 6 and 5 years, respectively.
While in there, I noticed that the link for the list of Vyper resources needed to be updated too.
I moved the links for Brownie, `py-devp2p` and `py-wasm` to the "Archived / No longer maintained" section and updated the Vyper resources link.
- Fixes #12628
=> move Brownie, pydevp2p, and py-wasm to Archived tools, update link to list of Vyper resources

public/content/contributing/adding-wallets/index.md, public/content/contributing/design/index.md
Corrected Ethereum.org -> ethereum.org on Design contribution page
Corrected Ethereum.org -> ethereum.org on Design contribution page
None
=> Typo: Corrected Ethereum.org -> ethereum.org on Design contribution page

public/content/developers/docs/data-and-analytics/index.md
=> Update SubQuery entry

src/pages/stablecoins.tsx
Added the padding between the warning and the text [Fixes #12649 ]
https://deploy-preview-12659--ethereumorg.netlify.app/en/stablecoins
- Fixes #12649
=> Fix: component padding on /stablecoins

public/content/contributing/translation-program/index.md, public/content/translations/tr/contributing/page-contributing-translation-program-acknowledgements.json, public/content/translations/zh/contributing/page-contributing-translation-program-acknowledgements.json, src/intl/de/page-contributing-translation-program-acknowledgements.json, src/intl/en/page-contributing-translation-program-acknowledgements.json, src/intl/en/page-contributing-translation-program-contributors.json, src/intl/es/page-contributing-translation-program-acknowledgements.json, src/intl/fr/page-contributing-translation-program-acknowledgements.json, src/intl/id/page-contributing-translation-program-acknowledgements.json, src/intl/it/page-contributing-translation-program-acknowledgements.json, src/intl/pt-br/page-contributing-translation-program-acknowledgements.json, src/intl/tr/page-contributing-translation-program-acknowledgements.json, src/intl/zh/page-contributing-translation-program-acknowledgements.json, src/pages/contributing/translation-program/acknowledgements.tsx
Update the Translation Program and translation acknowledgement pages to replace the mentions of POAPs with OATs and update the process to claim them
=> Update translator acknowledgements

public/content/developers/docs/apis/json-rpc/index.md
Adds a link and a short description for [ethereum-json-rpc.com](https://ethereum-json-rpc.com).
Adds a paragraph to the "Execution client spec" section on the "JSON-RPC" page, highlighting "Ethereum JSON RPC" tool — the interactive API playground for Ethereum JSON-RPC spec. One distinctive feature of the tool is that it allows the user to execute methods right from the browser.
The playground is [open-source](https://github.com/Destiner/ethereum-json-rpc).
> Disclaimer: I am the creator of the tool.
Recreating the PR to fix the file path.
=> Add ethereum-json-rpc.com

public/content/developers/docs/apis/json-rpc/index.md
Fixed a typo, a residual double quatation.
Fixed a typo, a residual double quatation.
none
=> Typo: Fixed a typo, a residual double quatation.

src/components/FindWallet/WalletTable/index.tsx
This PR adds some requested Matomo tracking for `/find-wallet` page
Fixes https://github.com/ethereum/ethereum-org-website/issues/12642
=> feat: add tracking for cta buttons in /find-wallet

src/components/FindWallet/WalletTable/index.tsx
When the Visit website is clicked on the wallet, the event is compared with the associated class and allows to show the detailed view accordingly. [Fixes #12644 ]
=> Fix the unintended behaviour of clicking visit website on find wallet #12644

public/content/community/get-involved/index.md, public/content/translations/ca/community/get-involved/index.md, public/content/translations/de/community/get-involved/index.md, public/content/translations/el/community/get-involved/index.md, public/content/translations/es/community/get-involved/index.md, public/content/translations/fa/community/get-involved/index.md, public/content/translations/fr/community/get-involved/index.md, public/content/translations/hu/community/get-involved/index.md, public/content/translations/id/community/get-involved/index.md, public/content/translations/it/community/get-involved/index.md, public/content/translations/ja/community/get-involved/index.md, public/content/translations/nl/community/get-involved/index.md, public/content/translations/pl/community/get-involved/index.md, public/content/translations/pt-br/community/get-involved/index.md, public/content/translations/ro/community/get-involved/index.md, public/content/translations/ru/community/get-involved/index.md, public/content/translations/sw/community/get-involved/index.md, public/content/translations/tr/community/get-involved/index.md, public/content/translations/uk/community/get-involved/index.md, public/content/translations/zh-tw/community/get-involved/index.md, public/content/translations/zh/community/get-involved/index.md
I removed all the links to Gitcoin on the get-involved page, I also added a link to ETHGlobal on the italian translation  of "Attend an [ETHGlobal(opens in a new tab)](http://ethglobal.co/) hackathon near you!".
https://github.com/ethereum/ethereum-org-website/issues/12725
=> feat: Remove Gitcoin bounties from get involved page

public/content/developers/docs/evm/index.md
typo: Typo a residual parenthesis in EVM page
typo: Typo a residual parenthesis in EVM page
none
=> typo: Typo a residual parenthesis in EVM page

src/components/Nav/Mobile/MenuFooter.tsx, src/components/Nav/index.tsx
Since our Search API Key for Algolia has been fixed, we can display the search modal again.
Reverts the hidden search modal in desktop & mobile.
Prev hotfix #12692
=> Hotfix: revert hidden search modal

public/content/contributing/translation-program/translatathon/index.md
I've added the missing year after the dates under the page https://ethereum.org/en/contributing/translation-program/
=> Added 2023 to Translatathon page

.storybook/preview-head.html, .storybook/preview.ts
Somehow in a past build (probably during the project migration to NextJS), the `Inter` font lost exposure in Storybook; It is no longer available in the existing configuration to being available to the Chakra theme in the SB environment.
And with the Inter font now being served locally via PR #12501, there needed to be  different approach to applying it back into the environment
- Creates `preview-head.html` to redefine the CSS variable `--font-inter` to it is available to the Chakra theme in the SB environment
- This variable in prod is currently declared in `_app.tsx` so it is unavailable to the SB environment from that location
- Exposes the `global.css` to make the inter font faces available
This PR does not consider the mono font, which is also not exposed to Storybook. Because of …
=> fix(storybook): expose `Inter` local fonts to storybook

src/intl/zh/page-developers-docs.json
`权益正明` should be `权益证明` in navbar
=> Fix a typo "权益正明" in Chinese doc

public/content/developers/docs/consensus-mechanisms/pos/attestations/index.md
Correct information about number of aggregators per attestation subnet
confirm to the spec as outlined here: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#misc
=> Correct information about number of aggregators per attestation subnet

public/content/developers/docs/networks/index.md
Move links to Blockscout explorer from "Faucets" section to "Resources" section.
=> Move Blockscout away from faucets section

src/layouts/Docs.tsx, src/layouts/Static.tsx, src/layouts/Tutorial.tsx, src/layouts/Upgrade.tsx, src/layouts/UseCases.tsx
Currently we have this
a different color than `body.base` in our list items.
This PR fixes the color by removing the custom `ListItem` components used in the layouts to default to the used in the `mdComponents` list.
#9548
=> Fix list item color in layouts

public/content/contributing/translation-program/translatathon/index.md
- add InfoBanner with link to twitter page
- add year to the translatathon dates
Contrary to the expected emoji 🗓️, I added 📆 emoji instead as it looks better and more visible on the info banner background. _See images_
[#12756 - Update content (add year + call-out) on Translatathon page](https://github.com/ethereum/ethereum-org-website/issues/12756)
=> feat: add year and banner to translathathon page [FIXES #12756]

public/content/developers/docs/oracles/index.md
Oracles are applications that provide data feeds, not data feeds themselves.
Fix: From "Oracles are data feeds" to "Oracles are *applications that produce* data feeds"
I could be wrong. I didn't find an explicit distinction anywhere online, but I came to this conclusion from what I've gathered below. 
Sources that support this distinction:
["Data feeds are data “produced” by oracles"](https://leancommunity.org/essential-data-feeds-in-blockchain-contracts/)
["decentralized data feeds (dAPIs) delivered by first-party oracle nodes"](https://blockchain.news/news/api3-unveils-enhanced-data-feed-service-to-bolster-tvl-on-polygon-zkevm)
["API3, the first-party blockchain oracle, is releasing beacon data feeds"](https://www.zdnet.com/finance/blockchain/api3-the-first-party-blockchain-oracle-is-rel …
=> Update definition of "Oracle" in "Oracles" Page

src/components/Stat/index.tsx
This is a follow-up to an issue noticed in the [Stat component creation PR](https://github.com/ethereum/ethereum-org-website/pull/11574#pullrequestreview-2015599608)
Fixes placement of the tooltip popover for the `Stat` component, by wrapping the child content in a button.
Per [Chakra docs for the Popover](https://v2.chakra-ui.com/docs/components/popover/usage#basic-usage) the child element should be able to take have a forwarded ref and be focusable (the later currently not considered). This means that at the very least the element should be a `button` or an `a`.
Wrapping in a button also allows for keyboard focus which triggers the popover.
N/A
=> fix(Stat): wrap `Tooltip` child in button

src/components/Nav/Mobile/MenuFooter.tsx
Fixes mobile menu layout to have 3 columns instead of 2.
Fixes #12856
=> Fix mobile menu layout

.github/workflows/build-crowdin.yml, src/scripts/crowdin/getTranslationProgress.ts, src/scripts/crowdin/translations/triggerBuild.ts
- `build-crowdin.yml` - New GitHub action workflow, which runs a new `triggerBuild.ts` script on the 1st of every month.
- `triggerBuild.ts` - Simple script to call `crowdin.translationsApi.buildProject()`, triggering Crowdin to build our project
Crowdin CI/CD efforts
cc: @lukassim
=> feat: Crowdin build automation

src/hooks/useClientSideGitHubContributors.ts
- The array on commits/contributions is ordered most recent to oldest. The order of `...oldCommits` and `...newCommits` was reversed causing the last commit from the old repo to be highlighted. 
- Flips the order of this concatenation to have the most recent commit in [0] position.
https://ethereum.org/en/developers/docs/scaling/zk-rollups/
https://github.com/ethereum/ethereum-org-website/commits/dev/public/content/developers/docs/scaling/zk-rollups/index.md
=> fix: latest contributor for dev docs

src/lib/utils/matomo.ts
- Customizes the page URL logged for Matomo events using the `setCustomUrl` function
- Query params and hash links are removed from the current URL before being logged
See:
- https://developer.matomo.org/guides/tracking-javascript-guide#manually-trigger-a-page-view
- https://matomo.org/faq/how-to/how-do-i-set-a-custom-url-using-the-matomo-javascript-tracker/
cc: @konopkja
=> fix: strip query params/hashes form matomo events

src/components/FileContributors.tsx, src/components/SideNav.tsx, src/components/SideNavMobile.tsx, src/layouts/Docs.tsx
Immediately display the contributors modal button to reduce LCP.
Other changes:
- Used the MdChevronRight icon to match the initial close state and avoid the initial animation causing the LCP to be higher sometimes
- Removed the Skeletons and add one inside the modal
====
Webpagetest https://www.webpagetest.org/result/240430_BiDc8E_92E/
All the LCPs are the same now, ~2/3s.
=> Performance - contributors component refactor

public/content/developers/docs/apis/json-rpc/index.md
Removed unnecessary backslash in `0x004200 (size 3, "\0B\0")`
`0x004200` has `0x` prefix and remaining 6 characters for 3 bytes where 2 characters represent 1 byte.
| HEX | Decimal | Ascii |
|--------|------------|--------|
|00|0|0|
|42|66|B|
|00|0|0|
[Learn More](https://www.ascii-code.com/66)
fix #12838
=> Remove unnecessary backslash

src/scripts/crowdin-import.ts, src/scripts/crowdin/import/utils.ts
- removes svg and xlsx files from crowdin import scripts as images are handled through a separate import process
=> remove svg and xlsx files from crowdin import

i18n.config.json
[Bug report: Region-specific browser language preferences are being ignored #12027] is caused by only Brave browser specific i18 redirection.
Only changing of the JSON array order can suppress the bug.
#12027
=> Workdround for brave i18 redirection [Fixes #12027]

public/content/desci/index.md
Add ValleyDAO to desci page
User @SeaBlue22 requested for their page [ValleyDAO](https://www.valleydao.bio) to be added to the [Ethereum.org Desci page](https://ethereum.org/en/desci). As per there request I have added the link to the page in case their request is to be approved. Disregard this PR if not, just wanted to provide a quick fix in case it was needed.
This PR closes #12105
=> add ValleyDAO to desci page

netlify.toml
Enables `NEXT_FORCE_EDGE_IMAGES` env var to serve images from the edge env and avoid the extra redirect we currently have to the `ipx` endpoint.
https://github.com/netlify/next-runtime/tree/main?tab=readme-ov-file#enabling-edge-images
prod
preview deploy
=> Performance - enable NEXT_FORCE_EDGE_IMAGES

docs/applying-storybook.md
As essentially task #0 in rolling out new initiatives in including more component stories, this PR updates and adds clarification to the `Applying Storybook` documentation for contributors.
This also updates existing stories to ensure they are inline with this updated documentation.
=> docs(applying-storybook): update documentation and usage

src/data/externalTutorials.json
Updated the externalTutorials.json file to add 7 new tutorials from SpeedRunEthereum.com.  
Along with [PR#12834](https://github.com/ethereum/ethereum-org-website/pull/12834) which removes the outdated SRE challenge, Closes #12834
=> add updated tutorials from speedrunethereum.com

src/pages/stablecoins.tsx
This changeset updates the `Swap ETH for Dai` and `Swap ETH for USDC` button destination URLS on the stablecoin page to a valid token page where ETH is set as the sell token, and either DAI or USDC as the buy token as the button text suggests.
[PR Walkthrough of changes and issues seen in production](https://www.youtube.com/watch?v=6-nCSj9uRq0)
Update the links used on this page to lead to a valid token page which has Ethereum as the sell token and `USDC` or `DAI` as the buy token. 
Add `target="_blank"` to ensure these pages open in a separate tab allowing users to explore the external content without losing their place on the Stablecoin page..
FIXES #12873
=> Update Swap ETH for USDC/DAI link on stablecoin page [FIXES #12873]

.storybook/ChakraDecorator.tsx, .storybook/i18next.ts, .storybook/main.ts, .storybook/preview.ts, .storybook/types.ts, package.json, src/components/Buttons/Button.stories.tsx, yarn.lock
In response to attempting to add a RTL language as a locale option for Storybook, this PR removes `@chakra-ui/storybook-addon` in favor of a local decorator setup.
It is expected that the addon will not be updated due to ongoing building of Chakra v3 (which will deprecate the addon). In it's current state, the addon is not set up to properly sync with the changing of locale direction via `i18next`, affecting DX.
Creation of a local decorator similar to the addon expects a resolution to this, along with other modifications.
The `.storybook/types` brings in the `getThemingArgTypes` from the addon to generate SB controls based on the given component theme. (Currently in use in `Button.stories`)
The Farsi language is added to SB as a locale option to generate RTL snapshots in Chromatic.
=> refactor: replace `@chakra-ui/addon` with local setup

.storybook/main.ts, package.json, src/components/Hero/ContentHero/ContentHero.stories.tsx, src/components/Hero/HomeHero/HomeHero.stories.tsx, src/components/Hero/HubHero/HubHero.stories.tsx, yarn.lock
Adds and configures the [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin#tsconfig-paths-webpack-plugin) for webpack to consistently resolve path aliases in TypeScript modules.
See [Storybook Docs](https://storybook.js.org/docs/builders/webpack#typescript-modules-are-not-resolved-within-storybook) regarding this webpack recommendation.
Also updates import paths in existing story files that use imports from the `public` folder.
Errors would throw specifically for the path alias to the `public` folder (`@/public`) saying it could not resolve the aliased path. But the alias `@` for the `src` directory would always resolve successfully.
For example, attempt to render a story involving an image being import from `@/public/**`, either in the component or …
=> fix(storybook): fix alias paths with tsconfig plugin

.github/ISSUE_TEMPLATE/suggest_wallet.yaml, public/content/contributing/adding-wallets/index.md
- Update description for EIP-1559 (type 2) transactions for wallet listing. This is required for Ethereum Mainnet, but for wallets that don't support mainnet and are layer 2 first wallets, they may not have this.
=> Update EIP-1559 transaction type information for wallets

src/components/Buttons/ButtonLink.tsx, src/components/FindWallet/WalletTable/index.tsx
This PR updates the `ButtonLink` component to handle custom `onClick` events and override its behavior when needed. Fixes the issue of `/wallets/find-wallet/` `Visit website` CTA not being tracking the event when clicked.
- Go to `/wallets/find-wallet/` now the `Visit website` button should be triggering the custom `handleWalletWebsiteClick` event handler
- Go to any other page like `/community/` to check that the `ButtonLink` component is still working as expected for other cases
https://deploy-preview-12935--ethereumorg.netlify.app/wallets/find-wallet
=> fix: ButtonLink onClick handler

public/content/community/get-involved/index.md
- Adds information on AllWalletDevs to get-involved page
Fixes https://github.com/ethereum/ethereum-org-website/issues/9244
=> add AllWalletDev to get-involved page

public/content/community/events/index.md
Fixes #12961 
Replaced "add a community event" URL .ts on /community/events/ page.
=> fix: replaced `add a community event` url on /community/events/

public/content/developers/docs/data-and-analytics/block-explorers/index.md
Add [`lazy-etherscan`](https://github.com/woxjro/lazy-etherscan) to the list of block explorers.
#12115
=> Add lazy-etherscan to the list of block explorers [Issue #12115]

src/@chakra-ui/components/Popover.ts
fix: override box-shadow to none to avoid tooltip border [#12597](https://github.com/ethereum/ethereum-org-website/issues/12597)
This pull request addresses the issue where a colored border appears around tooltips on mobile devices due to the focus-visible state. The changes ensure that the box-shadow is set to none when elements are focused, effectively removing the unwanted visual effect and maintaining a consistent appearance across devices.
=> fix: override box-shadow to none to avoid tooltip border #12597

src/middleware.ts
Adds missing root route to the middleware matcher.
=> Fix: add explicit matcher for the root path to work on dev mode

.github/labeler.yml
- Removes "needs review" as this is implied with all PRs
- Adds /docs to "documentation"
- Adds storybook to tooling 
- Removes all-contributors from being labeled
- Fixes "translations" vs "content"
- `public/content/translations` path fixed
- Added `!` to remove english updates from "translations", and non-English updates from "content"
- Renames "internal" to "config"
Ongoing GitHub management initiatives
=> feat: update labeler

public/content/translations/es/contributing/translation-program/how-to-translate/index.md, public/content/translations/es/contributing/translation-program/index.md, public/content/translations/fr/contributing/translation-program/how-to-translate/index.md, public/content/translations/fr/contributing/translation-program/index.md, public/content/translations/it/contributing/translation-program/how-to-translate/index.md, public/content/translations/it/contributing/translation-program/index.md, public/content/translations/pt-br/contributing/translation-program/how-to-translate/index.md, public/content/translations/pt-br/contributing/translation-program/index.md
Update link to the ethereum.org Crowdin project on translated versions of the Translation program page, as the old link (https://crowdin.com/project/ethereum-org/invite) does not work
=> Update broken Crowdin link on translated Translation program page

.github/labeler.yml, .github/workflows/label.yml
- `- !src/intl/en/**` syntax invalid for `actions/labeler@v2` config `yml`
- Removes these conditions, and added a follow-up task that updates the labels that match those conditions
- This helps keep English content updates/additions labeled separately from non-English translation updates
- Fixes labeler action failures
=> fix: labeler yml syntax, add labeler refining step

src/intl/en/glossary.json
Fixing glossary typos
Fixing glossary typos (missing closing tag)
None.
=> fix: glossary typos

public/content/enterprise/index.md
Fix typo on Ethereum mainnet for enterprise page
Change _electroinc_ to _electronic_
No related issue, typo was highlighted in Crowdin
=> Fix typo on Ethereum mainnet for enterprise page

src/components/LanguagePicker/MobileCloseBar.tsx, src/components/LanguagePicker/index.tsx, src/components/Nav/Menu/index.tsx, src/components/Nav/index.tsx
This PR avoids unnecesary nav menus renderings on desktop/mobile
- avoids rendering desktop Menu version on mobile
- avoids rendering desktop LanguagePicker version on mobile
- extracts `MobileCloseBar` component and renders on mobile only
- moves `LanguagePicker` handlers to external functions to avoid re-creating them on each render
=> performance: avoid desktop/mobile menus unnecesary renderings

src/components/Hero/ContentHero/index.tsx, src/components/Hero/HubHero/index.tsx, src/components/PageHero.tsx, src/layouts/Roadmap.tsx, src/layouts/UseCases.tsx, src/pages/eth.tsx, src/pages/wallets/find-wallet.tsx, src/pages/what-is-ethereum.tsx
Implements the `sizes` prop where it is missing to get a more optimized image especially in smaller resolutions.
=> Performance: optimize hero images

src/intl/ja/page-developers-docs.json
In the side menu, where it should have been Development Network(開発用ネットワーク), it was Development Framework(開発フレームワーク), which has been corrected.
https://ethereum.org/en/developers/docs/development-networks/
https://ethereum.org/ja/developers/docs/development-networks/
=> chore: update Japanese translation for developers docs navigation

src/pages/wallets/find-wallet.tsx
Created from [this comment](https://github.com/ethereum/ethereum-org-website/pull/13066#pullrequestreview-2108854241) because we forgot to add `revalidate` to this page.
=> Revalidate find-wallet page daily

.github/ISSUE_TEMPLATE/suggest_dapp.yaml
- Add required "url" input for `suggest_dapp.yaml` issue template
- Discovered during issue reviews; dapp listing requests lacking this information
=> fix: add url to dapp listing template

public/content/developers/docs/networks/index.md
This PR introduces a link to Ethereum Ecosystem' sepolia faucet: https://www.ethereum-ecosystem.com/faucets/ethereum-sepolia
People struggle to find faucets that have plenty of ETH to distribute AND do not get depleted by malicous actors with bots. This faucet is bot/spam-resistant and provides generous drips to users.
=> Add Ethereum Ecosystem Sepolia faucet to dev docs /networks

public/content/developers/docs/networking-layer/portal-network/index.md
Updated content on the doc about the Portal Network to include the client [Shisui](https://github.com/GrapeBaBa/shisui). 
N/A
=> content: add Shisui to list of Portal clients

public/content/community/online/index.md, public/content/translations/de/community/online/index.md, public/content/translations/el/community/online/index.md, public/content/translations/es/community/online/index.md, public/content/translations/fa/community/online/index.md, public/content/translations/fr/community/online/index.md, public/content/translations/hu/community/online/index.md, public/content/translations/it/community/online/index.md, public/content/translations/ja/community/online/index.md, public/content/translations/nl/community/online/index.md, public/content/translations/pl/community/online/index.md, public/content/translations/pt-br/community/online/index.md, public/content/translations/ru/community/online/index.md, public/content/translations/sw/community/online/index.md, public/content/translations/tr/community/online/index.md, public/content/translations/uk/community/online/index.md, public/content/translations/zh-tw/community/online/index.md, public/content/translations/zh/community/online/index.md
- Update ETHGobal Discord link to use `.com` instead of `.co`
From UX Research sync
=> fix: ETHGlobal Discord link

netlify.toml, package.json, yarn.lock
Running `yarn dev` crashes because it expects `sharp` which is not installed since we only installed it on Netlify contexts for reasons explained in #12957.
This fix reverts the changes made in #12957 to install sharp. It now forces the installation of `sharp@v0.32.6` as this version does not cause problems with local and netlify envs. `sharp` is currently installed by `@storybook/nextjs`.
Consider this a temporary solution until we find a better way to install the latest version and avoid problems with different envs.
#12957
=> Force to use sharp v0.32

package.json, src/components/Codeblock.tsx, src/pages/what-is-ethereum.tsx, yarn.lock
=> Upgrade TS to v5.5

public/content/developers/docs/smart-contracts/testing/index.md
=> indefinite article placed properly

public/content/developers/docs/evm/index.md, public/content/translations/de/developers/docs/evm/index.md, public/content/translations/es/developers/docs/evm/index.md, public/content/translations/fa/developers/docs/evm/index.md, public/content/translations/fr/developers/docs/evm/index.md, public/content/translations/hu/developers/docs/evm/index.md, public/content/translations/id/developers/docs/evm/index.md, public/content/translations/it/developers/docs/evm/index.md, public/content/translations/ja/developers/docs/evm/index.md, public/content/translations/pl/developers/docs/evm/index.md, public/content/translations/pt-br/developers/docs/evm/index.md, public/content/translations/ro/developers/docs/evm/index.md, public/content/translations/ru/developers/docs/evm/index.md, public/content/translations/tr/developers/docs/evm/index.md, public/content/translations/zh-tw/developers/docs/evm/index.md, public/content/translations/zh/developers/docs/evm/index.md
[eEVM](https://github.com/microsoft/eEVM) is archived and hasn't been updated in a year. I did not find any link to a new code location, so I think this project is not maintained in any more.
This PR removes the link from this page: https://ethereum.org/en/developers/docs/evm/
=> remove reference to unmaintained eEVM

.storybook/i18next.ts, src/components/EnergyConsumptionChart/EnergyConsumptionChart.stories.tsx, src/components/EnergyConsumptionChart/index.tsx, src/components/StatsBoxGrid/GridItem.tsx, src/components/StatsBoxGrid/StatsBoxGrid.stories.tsx, yarn.lock
Tackles issues detected while testing the chart.js migration.
Home page charts
- app crashing on production build when user changes the range period
- disabled labels because for some reason, some times, they were displayed even though we are not using labels in this case
Energy consumption chart
- better responsive styles ([docs](https://www.chartjs.org/docs/latest/configuration/responsive.html)) - left the `aspectRatio` unset given that we want the chart to adapt to its parent size
- adjust chart height for different resolutions
- rtl support
- fixed a few typing issues
Added stories for both.
#12952
=> Fix charts using chart.js

src/pages/layer-2.tsx
The Layer 2 Hero image does not appear when sharing the page link to social media.
Fix relative path string for the hero image passed to `PageMetadata`.
=> fix(pages/layer-2): update image path for meta

src/components/Simulator/WalletHome/TokenBalanceItem.tsx
In the `Create account` and `Send/receive` tokens flows of the wallet simulator, the spacing of the tokens list (UNI token in this case) is quite close to the border. Without scrolling for more tokens in this list, the spacing looks a bit awkward.
for now I've decreased the font size of token list so that it gives some extra margin bottom.
- https://deploy-preview-13202--ethereumorg.netlify.app/en/wallets/#sim
- Closes #11465
=> fix: spacing on token list in wallet simulator

public/content/developers/docs/intro-to-ethereum/index.md, public/content/translations/it/developers/docs/intro-to-ethereum/index.md
-  Removed unaccessible link from the intro to Ethereum page and replaced it with the working one.
-  The previous link used a domain that was expired, so replaced it with a link of the medium article directly.
https://github.com/ethereum/ethereum-org-website/issues/13209
=> replaced unaccesible link from intro to ethereum page

src/components/LanguagePicker/index.tsx
Fixed the overlapping keyboard shortcut `[\]` in the `LanguagePicker` component for right-to-left (RTL) languages.
Closes #12965
=> fix: overlapping elements in LanguagePicker for RTL langs

src/components/FindWallet/WalletFilterFeature.tsx
- Fixes reversal of true/false for "Toggle Desktop/Browser/Mobile" Matomo events
- Adds the word "to" to differentiate between old logs (where T/F have flipped meanings) and the new corrected entries.
Example of new usage: If "Mobile" is switched from off to on, it will log `Toggle Mobile to true`.
None filed; from UX research sync
=> fix: wallet filter device boolean tracking

public/content/developers/docs/apis/javascript/index.md
Fixed ether command on Ethereum Client APIs
Changed
ethers.providers.Web3Provider(window.ethereum) --> ethers.BrowserProvider(window.ethereum)  & 
Wallet.fromMnemonic(mnemonics) --> Wallet.fromPhrase(mnemonics)
=> Fixed ether command on Ethereum Client APIs

public/content/developers/docs/nodes-and-clients/node-architecture/index.md
- Remove irrelevant image subtext
- Applied change to English only as it's low-priority, and this let's the Crowdin process handle the non-English version updates.
The subtext ^ here was in reference to an older image:
=> fix: remove outdated subtext

src/components/Nav/index.tsx, src/lib/utils/isDesktop.ts
The desktop menu was still rendered on ssr because `isMobile` is always `false` on the server. Changed the logic to only render the menu on the client side as originally intended.
Fixes #12749
=> Fix hydration issue on mobile

public/content/developers/docs/nodes-and-clients/index.md
Execution client summary table did not link users to sync types
Sync types were poorly identified and incomplete
Small proofs including:
- proof-of-stake > Proof of Stake (PoS) acronym then applied
- mainnet > Mainnet for Ethereum
Fixes #12003
=> Update node syncing content [Fixes #12003]

src/components/Glossary/GlossaryDefinition/index.tsx
- Removes unused component import
Resolves:
```
12:41:48 AM: ./src/components/Glossary/GlossaryDefinition/index.tsx
12:41:48 AM: 2:10  Warning: 'Box' is defined but never used.  unused-imports/no-unused-imports-ts
```
=> chore: remove unused import, fix console warning

public/content/developers/tutorials/short-abi/index.md
As suggested in the issue, I have removed the examples section containing links to the deprecated Kovan explorer and other broken links as well.
Closes #10383
=> Remove deprecated Kovan links from tutorial [Fixes #10383]

src/components/Nav/Desktop/index.tsx
[Old PR](https://github.com/ethereum/ethereum-org-website/pull/13229)
- remove hover animation from `IconButton`
- add hover animation to `IconButton`'s child svg (the icon)
- add same animation to `:focus` state
[Bug: Click zone on color toggle rotating with icon effect](https://github.com/ethereum/ethereum-org-website/issues/11591)
=> style(Nav): shift hover transition to button children icon and add focus state

src/scripts/crowdin-import.ts
- Removes entry from `USER_OVERRIDE` object in `crowdin-import.ts` (used ephemerally; entries should not be commited)
=> fix: remove `hu` entry from crowdin-import

src/components/EthVideo.tsx
It fixes `ethereum-hero-light.mp4` inappropriate path at `What is ETH?` page. Resolves [#13349]
=> fix: eth page video graphic path

public/content/security/index.md
- Removes use of `{" "}` for spaces and places `div` children on one line to fix spacing issue shown below.
- Ran linter
Existing:
https://ethereum.org/en/security/
With fix:
=> fix: spacing on /security InfoBanner

src/layouts/UseCases.tsx
- Removes the scroll to button under the hero on the UseCases template. Was the only template with this and served nor real purpose. 
- Closes: https://github.com/ethereum/ethereum-org-website/issues/11466#issuecomment-2164204176
=> Remove scroll button from UseCases template

src/components/StablecoinsTable.tsx, src/intl/en/page-layer-2.json, src/intl/en/page-stablecoins.json, src/pages/layer-2.tsx
- Setup missing translations on /layer-2 and /stablecoins
- Closes: https://github.com/ethereum/ethereum-org-website/issues/12044
=> Setup missing translations on /layer-2 and /stablecoins pages

public/content/roadmap/verkle-trees/index.md
There is an error on the Verkle trees page, the paragraph below ends with a closing bracket with no corresponding opening bracket
https://ethereum.org/en/roadmap/verkle-trees/#why-do-verkle-trees-enable-smaller-witnesses
=> Fix error on the Verkle trees page

.env.example, src/components/StatsBoxGrid/useStatsBoxGrid.tsx, src/lib/api/fetchTotalEthStaked.ts, src/lib/constants.ts, src/lib/types.ts
The current implementation fetches ~20 times to get all the data needed for the total eth staked chart on the home page.
This causes a few problems:
- bad DX because you have to wait a long time for these fetches to run
- the granularity of the chart is not very good since we are omitting days to avoid calling more times the API
- (most importantly) hitting rate limits and causing the build to fail
This PR uses a different API (Dune API) to do just one fetch call and simplify the whole process.
We shouldn't have any issues with rate limits now since the Dune API free plan supports [40 req per min](https://docs.dune.com/api-reference/overview/rate-limits) for this type of operation.
It uses the following [query](https://dune.com/queries/3915587) forked and customized for our case (limited …
=> Dune API to fetch total eth staked

src/hooks/useWalletTable.tsx, src/pages/wallets/find-wallet.tsx
- Pass `supportedLanguage` to `useWalletTable` instead of relying on `useContext` provider.
Forces the table to update when language filter changes
- Fixes #13385
=> fix: wallet language filtering [Fixes #13385]

public/content/developers/docs/nodes-and-clients/run-a-node/index.md
Typo fix to use Holesky over Goerli when setting up a node in testnet
=> fix: Recommend Holesky over Goerli on "run a node"

tailwind/ui/buttons/Button.tsx
- Simple addition of tailwind class `pointer` to `button` component
- Fixes current arrow cursor bug
=> fix: add pointer cursor to button component

public/content/about/index.md
Replaced Product Roadmap URL on /about page from [View our 2024 Q1 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/12005) to [View our 2024 Q3 product roadmap](https://github.com/ethereum/ethereum-org-website/issues/13399).
Issue Fixes: #13401
=> replaced product roadmap url on about page #13401

public/content/developers/docs/transactions/index.md
=> Fix typo in "transactions" page, missing full stop

public/content/developers/docs/accounts/index.md
* Updated the account creation section to include details on Externally Owned Account (EOA) address format. 
* Added clarification that an EOA address consists of a 42-character string (40 hexadecimal characters plus `0x` prefix). 
* Also fixed minor formatting issues in the section.
Closes #11877
=> Update EOA address info [Fixes #11877]

src/components/LazyLoadComponent.tsx
Fixes the following warnings:
```
9:47:07 AM: 34:15  Warning: The ref value 'ref.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a node rendered by React, copy 'ref.current' to a variable inside the effect, and use that variable in the cleanup function.  react-hooks/exhaustive-deps
9:47:07 AM: 38:6  Warning: React Hook useEffect has a missing dependency: 'intersectionOptions'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```
=> Fix `ref` warning

public/content/developers/docs/oracles/index.md
Added Chronicle Oracles to the oracles list
- added Chronicle Oracles description
- added a link to a tutorial example using Chronicle Oracles
- replaced Maker Oracles with Chronicle in the price feed section, as Chronicle spun off from Maker in Autumn 2023 and is currently powering Maker in terms of price feeds.
https://github.com/ethereum/ethereum-org-website/issues/13220
=> Add Chronicle to Oracles list

public/content/roadmap/future-proofing/index.md
Retained `SELFDESTRUCT` keyword rather than SELF-DESTRUCT
=> term correction

public/content/developers/docs/apis/backend/index.md
Add Etherscan to the APIs list
Include Etherscan as a beginner friendly Ethereum API development option
=> Add Etherscan to dev docs /apis/backend/

public/content/community/get-involved/index.md
Update link to make it easier to find the Consensus and Execution Layer calls (formerly known as Core Devs calls)
=> Update naming and link to core dev calls

public/content/community/support/index.md
Truffle invite is invalid and it has also been sunset https://consensys.io/blog/consensys-announces-the-sunset-of-truffle-and-ganache-and-new-hardhat
=> Delete Invalid Invite

src/data/developer-docs-links.yaml
Reorder doc links to have proof-of-stake first in consensus mechanisms as this is what Ethereum uses today.
=> Reorder consensus mechanisms to have proof-of-stake first

src/components/Nav/useNav.ts
Warning stack thrown in the console from `useNav` during development:
```bash
Warning: React does not recognize the `fromPageParameter` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `frompageparameter` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
at button
at /home/tylerapfledderer/sites/ethereum-org/ethereum-org-website/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
at ChakraComponent (file:///home/tylerapfledderer/sites/ethereum-org/ethereum-org-website/node_modules/@chakra-ui/system/dist/chunk-5PL47M24.mjs:43:35)
at file:///home/tylerapfledderer/sites/ethereum-org/ethereum-org-website/node_modules/@chakra-ui/button/dist/chunk-UVUR7MCU.mjs …
```
=> fix(useNav): remove unused `fromPageParameter`

public/content/developers/docs/programming-languages/rust/index.md, public/content/translations/de/developers/docs/programming-languages/rust/index.md, public/content/translations/es/developers/docs/programming-languages/rust/index.md, public/content/translations/fr/developers/docs/programming-languages/rust/index.md, public/content/translations/hu/developers/docs/programming-languages/rust/index.md, public/content/translations/it/developers/docs/programming-languages/rust/index.md, public/content/translations/ja/developers/docs/programming-languages/rust/index.md, public/content/translations/pt-br/developers/docs/programming-languages/rust/index.md, public/content/translations/ro/developers/docs/programming-languages/rust/index.md, public/content/translations/tr/developers/docs/programming-languages/rust/index.md, public/content/translations/zh/developers/docs/programming-languages/rust/index.md
[`ethers-rs`](https://github.com/gakonst/ethers-rs) is on the verge of deprecation. **Alloy** is a high-performance rewrite of `ethers-rs` from the ground up with exciting new features.
- Add **Alloy** reference to Rust documentation.
- Fix the link for **Foundry**.
- Kept `ethers-rs` reference for old projects.
=> Add Alloy, successor to ethers-rs

public/content/developers/docs/nodes-and-clients/index.md
- Removes dead link for [Ethereum Node Crawler](https://crawler.ethereum.org/) `https://crawler.ethereum.org/`
=> chore: remove dead link

src/components/CommunityEvents/index.tsx
- Adds an `id` to the CommunityEvents component to allow a `https://ethereum.org/{lang}/#community-event` link that goes directly to this section of the homepage.
cc: @isabelladebrito
=> feat: add hash link for homepage events

.storybook/main.ts, next.config.js, src/assets.d.ts, src/components/FeedbackWidget/index.tsx
Adds the svgr loader in SB to handle svg files as with Nextjs and updates the configs and types.
=> Fix svg imports in SB

public/content/developers/docs/apis/json-rpc/index.md
Interestingly, on the JSON RPC spec page which is describing execution APIs have a link to Beacon API docs page(in Consensus section) but not the Execution API page.
Execution API docs page consist of the Inspector which can assist like Postman (GUI tool) for trying out various APIs.
I didn't open an issue first because that increases the duration of action, especially for such a small change. If PR is found to be inappropriate, can be just closed directly.
=> Add link to the Execution API Inspector page.

src/pages/get-eth.tsx
This PR addresses issue #13498 by adding missing padding around the button on the Ethereum.org page. 
- Added required spacing around the button on the "What are DEXs?" section of the page.
=> Fix: button spacing

src/components/Search/index.tsx
Fixes the docsearch `transformItems` function with the correct item properties.
Fixes #13603
=> HOTFIX docsearch transform

README.md
As local builds are set to include `en` only now by default, this PR adds the instruction on how to include more locales
=> readme: add tip about how to build in other languages

src/components/MergeInfographic/MergeInfographic.stories.tsx
Removes the `MdComponents` import since it creates a circular dependency problem with `TooltipLink`.
=> Fix stories in SB

public/_redirects
=> remove language redirects

src/components/Image.tsx
Exports the default image component to be used in the UI transition.
=> Shadcn migration - image

src/components/Quiz/QuizWidget/useQuizWidget.tsx
Fixes issue where the Chromatic Snapshot for the quiz modal kept updating because the first question rendered was always random. Uses the `isChromatic()` check to determine if `shuffle()` is triggered. The `layer-2` quiz key is used, therefore the first question to appear should always be `Layer 2 blockchain networks are for:`
The shuffle will still run when viewing the story in the daskboard.
The question set should not be shuffled when rendered in the Chromatic snapshot. Snapshots should at least be stable if they are not rendering pure functions with static prop data.
=> [Storybook] fix(useQuizWidget): run chromatic check for shuffling question set

public/content/contributing/translation-program/translatathon/details/index.md
Add a link to the Solidity Language Docs Crowdin project to the list of Translatathon ecosystem content
No related issues
=> Add Solidity docs to Translatathon ecosystem content

src/hooks/useRtlFlip.ts
- Updates the `useRtlFlip` custom hook to return `txFlipForRtl` with tailwind class `-scale-x-1` to horizontally flip elements
- Marked as the preferred method over using the transform value, and mark existing as deprecated
- Keeps existing `flipForRtl` export unchanged for temporary backward compatibility
Tailwindcss migration
@pettinarip Would this be useful or do you see another approach here?
=> feat: adds twFlipForRtl cn export to useRtlFlip

src/components/AdoptionChart.tsx, src/components/Nav/useNav.ts, src/hooks/useColorModeValue.ts, src/hooks/useNavMenuColorsTw.ts
Uses `resolvedTheme` instead of `theme` to avoid `system` value.
=> Hotfix color theme

src/components/AdoptionChart.tsx
Migrate AdoptionChart to tailwind.
=> Shadcn migration - AdoptionChart

.eslintrc.json, src/pages/_app.tsx, src/styles/global.css
- Consolidates all css imports into the `global.css` file
- Moves other global `css` imports as an `@import` statement within `global.css`
cc: @pettinarip Not sure if we would also like to revert the recent updates to the ESLint rule changes with this PR. Happy to, just drop a note if you'd prefer one way or the other.
=> refactor: consolidate css imports into global.css

public/content/contributing/translation-program/content-buckets/index.md, public/content/developers/docs/programming-languages/elixir/index.md, public/content/developers/docs/programming-languages/index.md, src/data/developer-docs-links.yaml, src/intl/en/page-developers-docs.json, src/lib/utils/md.ts
This PR adds a new page "Ethereum for Elixir developers".
Similar to other languages, Elixir also can benefit from having a dedicated page in ethereum.org documentations to ease onboarding of Elixir devs to Ethereum.
Fixes #13614
=> Add Ethereum for Elixir developers page

src/lib/api/fetchTotalEthStaked.ts
Updates the endpoint of the `ethstaked` data to point to the public query instead of the specific endpoint of the user. This will allow us to query it using api keys generated by others and not just this user.
=> Update ethstaked data endpoint

src/intl/en/glossary-tooltip.json, src/intl/en/glossary.json
- Removes term from definition intro for NFT glossary entry
- Corrects casing to sentence case
- Fixes the `(NFT )` typo via removal
none filed
=> fix: term typo/casing, rm term from defn

package.json, src/components/ui/dialog.tsx, yarn.lock
Removes the `lucide-reacts` icon dependency that was added by mistake when adding components from ShadCN.
=> chore: remove lucide-react dep

src/components/ui/buttons/Button.tsx, src/pages/what-is-ethereum.tsx
- Improves on #13706 to accept `size` and `variant` directly as props
None filed
=> refactor: accept size and variant as direct props

src/components/PageHero.tsx
Reduced Padding Between Navbar and Ethereum-Powered Tools and Services Banner In [Dapps Page](https://ethereum.org/en/dapps/)
before reducing padding top
after reducing padding top
- Fixes #11730
=> fix: padding between navbar and dapps page hero

public/content/community/support/index.md, public/content/contributing/adding-staking-products/index.md, public/content/developers/docs/nodes-and-clients/client-diversity/index.md, public/content/developers/docs/nodes-and-clients/index.md, public/content/governance/index.md
I updated the following pages by adding Grandine to any mention of CL clients.
- Nodes and clients (https://ethereum.org/en/developers/docs/nodes-and-clients)
- Client diversity (https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/#consensus-clients)
- Ethereum Support (https://ethereum.org/en/community/support/#consensus-clients)
- Adding staking products or services (https://ethereum.org/en/contributing/adding-staking-products/#node-or-client-tooling)
- Ethereum Governance (https://ethereum.org/en/governance/#who-is-involved)
=> Adding Grandine to various pages

src/components/EnergyConsumptionChart/index.tsx
- Rotates the labels to 45 degrees on energy consumption chart for longer labels
Fixes https://github.com/ethereum/ethereum-org-website/issues/12099
=> rotate energy consumption labels

src/data/CreateWallet.ts, src/pages/index.tsx
- rm comments at top, which were being rendered in code example on homepage
- Export as string literal instead of importing `.js` as raw.
oops =)
=> fix: convert js example to ts string export

src/components/Nav/Desktop/index.tsx
- Adds transition to default state to enable animation when leaving hover state for color toggle nav button
https://github.com/user-attachments/assets/041bb2ad-b2e9-4a77-aafb-677d8871e8de
None filed
=> fix: hover-off transition on color toggle

src/data/wallets/wallet-data.ts
- Removes the `new_to_crypto` flag from the Infinity Wallet entry which was added inadvertently in #13665
=> Remove new_to_crypto flag

public/content/developers/docs/networking-layer/portal-network/index.md
- Converts an image of a table to a table on the [portal-networks](https://ethereum.org/en/developers/docs/networking-layer/portal-network) page
Fixes: https://github.com/ethereum/ethereum-org-website/issues/13360
=> Change portal network image to table

src/lib/api/fetchRSS.ts, src/lib/constants.ts, src/lib/types.ts
- #13528 
- Add support for atom feeds
- Activate PSE and Josh Stark feeds which were pending this upgrade
Homepage epic
=> Homepage: enable atom feeds

src/components/Translation.tsx
Moves htmr transformers inside the function component to avoid circular dep problems.
=> Fix circular dep issue with `Translation` component

src/components/ui/buttons/Button.tsx
- `button` does not require declaring a pointer cursor
- tw class should've been `cursor-pointer`
=> chore: rm incorrect and redundant class

src/components/ui/progress.tsx
- Updates base `ui/progress` component with `rounded-full` on the inner progress bar element
^ Maintains this appearance from previous Chakra-UI `Progress`
cc: @nloureiro I didn't see this component in the DS, but noticed we previously had the rounded approach on the inside bar. Came across it when updating colors on the Quizzes page, so if we don't want to change the base component here, I can just close it out and apply to that usage only.
=> ui: round inner meter in ui/progress

src/components/Homepage/useHome.ts, src/components/ui/Link.tsx, src/pages/index.tsx
- Few homepage related RTL-responsiveness patches
- #13528
=> Homepage RTL patches

src/@chakra-ui/components/Button.ts, src/@chakra-ui/foundations/shadows.ts, src/components/FeedbackCard.tsx, src/components/Homepage/BentoCard.tsx, src/components/ui/buttons/Button.tsx, src/pages/index.tsx, tailwind.config.ts
- #13821 
(Can be merged in any order)
- Updates `buttonVariants` in new `ui/buttons/Button.tsx` component.
- Variants updated in detail to match current Figma Design System
- For readability and understanding, styling has been broken into functional sections with comments added
- Updates _Chakra_ Button component as well, syncing theming and applying same readability comments to improve ability to cross-verify these are correct until this component is fully deprecated.
[Figma](https://www.figma.com/design/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=545-16075&t=BxcGhRGzwsxhuaVj-1):
Design system
=> Design system: button theming

src/components/Nav/Desktop/index.tsx, src/components/Nav/index.tsx, src/components/Search/SearchButton.tsx, src/components/Search/index.tsx, src/styles/docsearch.css
- #13821 
(Can be merged in any order)
- Touches up nav bar buttons patching color inconsistencies, and updating with latest design system.
- Patches transition animations (consistent 12deg rotation on hover, and 500ms duration on/off.
- Adds `border-b-disabled` for nav bar per Figma 
Design system
=> Design system: nav bar/button theming

src/components/Homepage/useBentoBox.ts
- Refactors/simplifies the useBentoBox hook logic for readability
- Re-positions copy and images for bento boxes
cc: @konopkja 
https://www.figma.com/design/ocV0PiMMzklN6iVtJePxUv/homepage-redesign?node-id=8730-74947&t=6T2tquBliQ58ThwV-1
=> Update homepage bento arrangement

src/hooks/useBreakpointValue.ts, src/lib/types.ts, src/lib/utils/screen.ts, src/styles/config.ts, tailwind.config.ts, tailwind/screens.ts
Refactor to reuse the `screens` config file instead of importing the tw config file, which adds unnecessary stuff to the final bundle.
=> Refactor: reuse `screens` config file

src/components/FindWallet/WalletFilterPersona.tsx
fixed ui on find-wallet Fixes #13421 
1) Made changes in scroll-bar css to show it by default.
2) Increased the width of cards for overflowing on right size
We can also provide arrows like this indicating more items in the grid, clicking on arrow will scroll the cards
=> fixed ui on find-wallet [Fixes #13421]

src/components/ThemeProvider.tsx
- Fonts imported in `global.css`
- Duplicate font import in `ThemeProvider` removed
=> chore: remove duplicate font import

src/data/wallets/wallet-data.ts
rabby wallet was mistakenly assigned "new to crypto" tag, so just removing it.
=> removing new to crypto tag

src/components/Nav/Desktop/index.tsx, src/components/Search/SearchButton.tsx
- Remove outline from tablet nav-bar search button
- Remove transition for `color` property on nav buttons; transition only `transform` property
None filed, fixes outline seen here:
=> Patch search button

Adding that improves clarity README.md
Adding "that" improves clarity, and using "and" instead of the ampersand (&) makes it more formal.
=> Adding that improves clarity in README.md

src/components/BigNumber/index.tsx, src/lib/utils/rss.ts, src/pages/index.tsx
Few patches from homepage review
- #13528
=> Homepage patches

src/components/Homepage/ValuesMarquee.tsx, src/components/Tooltip/index.tsx
Sets custom container to tooltips inside marquee to keep animation paused while hovering the tooltip content.
=> Marquee tooltips

src/@chakra-ui/theme.ts, src/components/Nav/useNav.ts, src/components/ThemeProvider.tsx, src/styles/docsearch.css, src/styles/global.css, src/styles/semantic-tokens.css
1. Drops support for `system` color mode since we have edge cases where the theme providers run out of sync. I would suggest keeping this until we remove chakra from the codebase.
2. Use `data-theme` attr to detect dark mode instead of `class`. This aligns with Chakra's color mode detection method.
=> Hotfix color mode

src/components/ui/Select/innerComponents.tsx
- Replaces use of low-contrast with high-contrast primary color variant for `Select` component hover border color
Poor contrast ratio, giving a "disappearing" experience on select hovering
=> fix: Select hover border color contrast ratio

src/styles/docsearch.css, src/styles/global.css, tailwind.config.ts
- deprecate: primary-light/dark color tokens
Design system; theming updates and color token purging
=> deprecate: primary-light/dark color tokens

src/components/BigNumber/index.tsx
small css touch on the erros on the homepage
=> small css touch on the errors on the homepage

src/components/Nav/Menu/MenuContent.tsx, src/components/Nav/Mobile/LvlAccordion.tsx, src/components/Nav/Mobile/MenuBody.tsx, src/styles/semantic-tokens.css, tailwind.config.ts
**Proposal**: Migrate our "menu" tokens to tokens that are more generalizable.
Instead of declaring a whole array of specific "menu" tokens, with different level numbers, this PR suggests adding the additional shades of gray that are needed as additional `background` token shades.
We currently only have `background` and `background-highlight` for background tokens. This would add `low`, `medium` and `high` background variants to be used as layers to any stack (ie. nested menus, nested accordions, or any other nested elements).
These tokens were then used directly at the component level, updating and removing the existing usage of "menu-x-(active-)background" with the new corresponding background token.
Similar approach with text, but unsure of potential naming convention here. Went with a …
=> refactor: menu color tokens

src/data/consensus-bounty-hunters.json
The link to my github profile is broken on the consensus bounty page.
=> Fix nerolation link

src/styles/global.css
Testing the font size more prominent on mobile for accessibility
=> desktop and mobile 16 px font

src/components/LanguagePicker/index.tsx
- Moves the max-height property to the `Command` parent for the Language Picker component
- Adjusts height to use `calc` allowing menu to drop to just above the feedback widget, regardless of screen height
Fixes bug where the "Learn more" section at the bottom of the LanguagePicker was falling off the bottom edge of the screen on shorter displays/windows.
With fix:
https://deploy-preview-13942--ethereumorg.netlify.app/en/
=> fix: LanguagePicker max height

src/styles/semantic-tokens.css, tailwind.config.ts
- Token `accent-a-low-constrast` was added in development of the `ValuesMarquee` component, but was ultimately not used. PR removes all traces
- Removed `TODO` about color clash: `primary-action`/`primary-action-hover` applied specifically to `solid` buttons and should not clash with text link `primary`, `primary-hover`, and `primary-visited`
Ongoing theming cleanup
=> chore: remove unused token

src/components/Homepage/BentoCard.tsx, src/components/Homepage/ValuesMarquee.tsx, src/components/Homepage/useHome.ts, src/components/Homepage/useValuesMarquee.ts, src/pages/index.tsx
- Adds matomo events to "popular topics" buttons on Homepage
- Include locale code in `eventCategory` for all Homepage events, breaking into individual per-locale dashboards
cc: @konopkja
=> fix(matomo): Add missing homepage events; parse events by locale

src/components/MatomoOptOut.tsx
Migrates `MatomoOptOut` component to ShadCN from Chakra
As far as I can tell, the current border color for the box in Chakra theme (#e5e5e5) does not exist in DS/Tailwind theme. I've used `body-light` as the closest, but defer to @nloureiro here :) 
Per @pettinarip's [comment here](https://github.com/ethereum/ethereum-org-website/pull/13961#discussion_r1775316271), I've also stopped using the `OldText` component. This means the red color is slightly, though unrecognisably, different (now using `error` from tailwind config instead of the `fail` color in Chakra theme), and the margin bottom (was 1.45rem) is now 1.25rem per our scale.
#13946
=> Migrate MatomoOptOut to ShadCN

src/components/UpcomingEventsList.tsx
Migrates `UpcomingEventList` to Shadcn.
Note, before the H3 had a line-height of 1.4 (not really sure why). This isn't in our system, so I just left it as default line height.
#13946 #13966
=> Migrate UpcomingEventsList to Shadcn

src/components/EventCard.tsx
- Updates EventCard to shadcn
1. Hardcoded 1.6rem line height for the description text (per OldText) as the defaults we have varied too much from the current design. Our designers should pull this component in line with current DS.
2. Slight differences in spacing compared to the original design (which had kind of unusual spacing). IMO, these are improvements but defer to @nloureiro
3. I've hardcoded the background colors (`bg-[#FCFCFC] dark:bg-[#272627]`) in the CardHeader. Our default theme values didn't provide a good match for this use case. another area where we might want to consult with design
#13946
=> Migrate EventCard to Shadcn

src/components/UpgradeTableOfContents.tsx
- Updates `UpgradeTableOfContents` to Shadcn
#13946
=> Migrate UpgradeTableOfContents to Shadcn

src/components/Glossary/GlossaryDefinition/index.tsx, src/components/IdAnchor.tsx, src/components/MdComponents/index.tsx
=> refactor: migrate IdAnchor to tw

src/components/Banners/ContributorsQuizBanner.tsx
Migrate `ContributorsQuizBanner` to tailwind
=> Shadcn migration - ContributorsQuizBanner 

src/components/ui/alert.tsx
Proposal: Use 16px font size as default for `ui/alert` component
https://deploy-preview-13953--ethereumorg.netlify.app/en/get-eth
https://ethereum.org/en/get-eth
=> theme: use 16px font for alert descriptions

src/components/Trilemma/Triangle.tsx, src/styles/semantic-tokens.css, tailwind.config.ts
- Migrated Trilemma Triangle to Shadcn
- Add default border color from DS 
@nloureiro I took some liberties with picking colors: the current production Trilemma Triangle still uses blue for lightmode and orange for darkmode. This PR now uses purple instead, let me know if you have any suggestions/tweaks you'd like and I'll update.
#13946
=> Migrate Trilemma Triangle to Shadcn

.storybook/modes.ts, src/components/CallToContribute/CallToContribute.stories.tsx, src/components/Quiz/stories/QuizSummary.stories.tsx, src/components/Quiz/stories/QuizzesList.stories.tsx
Reduces the number of locales we currently test in Chromatic to just two (`en` and `fa` to test rtl). It also removes full testing on all components except the hero and layout components.
=> Chromatic reduce snapshot tests

src/styles/semantic-tokens.css, tailwind.config.ts
Adds all the new border colors from the DS. cc @nloureiro
=> Theme - add border colors

src/components/Hero/ContentHero/index.tsx, src/components/Hero/MdxHero/index.tsx, src/lib/types.ts
Migrates the ContentHero and MdxHero component to TW.
=> Shadcn migration - heros

src/components/BeaconChainActions.tsx
Migrate `BeaconChainActions` component to tailwind.
#13946
=> Shadcn Migration -  BeaconChainActions

src/components/Homepage/useHome.ts
- apply RTL flip to parent of svg to avoid conflicting transitions on the `svg` element
- Fixes issue where hovering on RTL pages would flip the icon back to "LTR" orientation
None filed
=> fix: apply flip to parent of svg

public/content/developers/docs/ides/index.md
Removed the Atom editor, as it is no longer supported or maintained.
- Fixes #13711
=> Removed Atom Editor from IDE List page

src/hooks/useStakingConsiderations.ts, src/intl/en/page-staking.json, src/layouts/md/Roadmap.tsx
- Fixes dropdown strings for Roadmap layout, passing key through `t()` first
- Fixes dropdown menu title/aria-label for mobile StakingConsiderations menu
https://deploy-preview-14022--ethereumorg.netlify.app/en/roadmap/
- #13971
=> fix: dropdown intl bugs

src/pages/get-eth.tsx
- Removes `leading-6` class (`line-height: 1.5rem;`) to fix the line height issue on `/get-eth` h1
Reported in QA
=> fix: h1 line height

.eslintrc.json, .storybook/i18next.ts, .storybook/utils.ts
Adds a custom eslint warning when `react-i18next` is used and suggest to use `next-i18next` to avoid hydration issues.
=> Import warning

src/layouts/Docs.tsx
Updated docs layout component to address content overflow across pages. Improved text wrapping for better readability on all devices, especially mobile.
Pages where this issue was most noticeable:
- [Ethereum Accounts](https://ethereum.org/en/developers/docs/accounts/)
- [Transactions](https://ethereum.org/en/developers/docs/transactions/)
- [Proof of Work](https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/)
- [JSON-RPC API](https://ethereum.org/en/developers/docs/apis/json-rpc/)
- [Network Addresses](https://ethereum.org/en/developers/docs/networking-layer/network-addresses/)
- [Web3 Secret Storage Definition](https://ethereum.org/en/developers/docs/data-structures-and-encoding/web3-secret-storage/)
- [Merkle Patricia …
=> fix: Docs layout component to resolve content overflow on mobile

src/components/EthPriceCard.tsx, src/pages/get-eth.tsx
- mx causing overflow; stack supportive text to avoid individual text-wrap
None filed, reported during release candidate QA session. Lower priority
=> fix: price card arrangement

src/components/ExpandableCard.tsx, tailwind/ui/accordion.tsx
Migrates `ExpandableCard` component to ShadCN from Chakra
This PR updates the ExpandableCard to use ShadcnUI's accordion component instead of Chakra component. Styles have been updated for both light and dark version.
@pettinarip I've used the `accordion` from `/tailwind` directory and did not directly overwrite the classes in the primitives, instead added classes in the `ExpandableCard` component to keep the UI similar to how it was with Chakra.
Lemme know if this approach doesn't look good, happy to update it. 
Also the default behaviour on shadcn accordion doesn't allow the accordion it to be closed if clicked on content, I can add this using mouse events, thoughts?
#13946
=> feat: migrate ExpandableCard component to shadcn

public/content/developers/docs/apis/json-rpc/index.md
As discussed in [ethereum/go-ethereum#29747](https://github.com/ethereum/go-ethereum/issues/29747), eth_coinbase no longer returns an address in v1.14.0+ and has been deprecated.
This PR removes the deprecated eth_coinbase RPC method from the JSON-RPC API list.
- Fixes #13996
=> Removed deprecated eth_coinbase from json-rpc docs[#13996]

src/components/StatsBoxGrid/useStatsBoxGrid.tsx
This PR enhances the homepage metrics section by updating the links to direct users to the relevant dashboards, facilitating easier verification of the data. The following updates have been made:
- **Value Locked in DeFi**: Linked to the DeFi Llama dashboard.
- **Value Protecting Ethereum**: Linked to Dune Analytics for total ETH staked 
- **Average Transaction Cost & Transactions in the Last 24h**: Linked to the GrowThePie dashboard.
Fixes: #13916
Please feel free to suggest any changes if needed.
=> Fix: Update Links to Source Dashboards in Metrics Section

public/content/developers/docs/nodes-and-clients/index.md
This pull request adds armiarma developed by Migalabs to the Ethereum documentation:
Armiarma: A tool designed to identify participants in the Ethereum network, listed under the [Nodes and Clients](https://ethereum.org/en/developers/docs/nodes-and-clients/#network-overview) section.
This tool is open-source and contribute to better understanding the network and its participants.
There is no related issue for this pull request, as this addition introduces new tools to the existing documentation and does not resolve an open issue.
=> Added Armiarma to the nodes and clients section under the tracking nodes in the network segment.

src/components/GhostCard.tsx, src/pages/dapps.tsx, src/pages/gas.tsx, src/pages/stablecoins.tsx
Migrates `GhostCard` component to tailwind ShadCN from Chakra
This PR updates the `GhostCard` to use ShadcnUI's card component instead of Chakra component. Styles have been updated for both light and dark version.
#13946
=> feat: migrate GhostCard to tailwind

src/components/StablecoinsTable.tsx
- Migrate `StablecoinsTable` to tailwind
- Replaced existing table implementation with the Shadcn table component.
#13946
=> feat: migrate StablecoinsTable to shadcn

src/components/StablecoinsTable.tsx, src/components/Translatathon/ApplyNow.tsx
=>  Migrate ApplyNow Components to shadcn/Tailwind 

src/lib/constants.ts
Disables the ethstaker feed until we have a solution to skip the security checkpoint.
=> Disable ethstaker feed

src/lib/constants.ts
- Re-adds the EthStaker blog as a _link only_ feed, without fetching latest posts
- Temporary solution while investigating issue noted in #14171
- #14171
=> chore: list EthStaker blog link only, without fetching latest

public/content/developers/docs/intro-to-ether/index.md
- fixes issues with translations that do not have specific translations for each linked word
- removes broken links; removes unnecessary hash link from link that remains
=> fix: rm broken links, simplify to single callout

next-i18next.config.js
After upgrading `@netlify/plugin-nextjs` #14175, the translations stop working on pages that we revalidate, as it seems that next-i18next couldn't find the correct location for our translations.
This PR fixes the problem by using `path.resolve` to resolve the locale path as described in https://github.com/i18next/next-i18next/issues/1552#issuecomment-1538452722
=> Fix i18n in revalidated paths in Netlify

src/components/EventCard.tsx
- Update `mr` (`margin-right`) to `me` (`margin-inline-end`) to fix `dir`-responsive margin on calendar icon for `EventCard`
=> fix: dir-responsive margin

src/pages/index.tsx, src/pages/stablecoins.tsx, src/pages/staking/index.tsx, src/pages/wallets/find-wallet.tsx
Currently, our revalidate process is always failing due to this bug, which is currently fixed in `dev` #14175. This issue causes the revalidate to never be done and always be triggered on every request, resulting in a lot of unnecessary API calls.
This PR temporarily stops revalidation until we have #14179 (which will allow us to re-enable it).
=> Hotfix disable `revalidate`

src/components/FindWalletProductTable/WalletSubComponent.tsx
- Prevent Info tooltip icon from wrapping on its own by forcing nowrap connection to last word in label
- Fine adjustments to positioning of icons to improve alignment
- #13807
(surfaced during review of product table refactor)
Fixes issues seen here:
=> Fix: wallet attributes icon alignments

netlify.toml
Currently our page revalidation does not work in preview deploy contexts (or envs using `USE_MOCK_DATA`) because the mocks are not found.
This PR includes the mock files.
=> Patch: include mocks in Netlify deploys

netlify.toml, src/pages/api/revalidate.ts, src/pages/index.tsx, src/pages/stablecoins.tsx, src/pages/staking/index.tsx, src/pages/wallets/find-wallet.tsx
Adds a `/api/revalidate` endpoint and remove automatic revalidation from root path.
=> Revalidate on demand

src/components/BugBountyCards.tsx
- Migrate `BugBountyCards` to tailwind
- Remove unused `Divider`
#13946
=> Shadcn migrate - BugBountyCards

src/components/Roadmap/RoadmapImageContent.tsx
Migrate Roadmap/RoadmapImageContent component to shadcn/tailwind
=> Migrate roadmap/roadmapimagecontent to shadcn/tailwind

src/components/Translatathon/TranslatathonCalendar.tsx
Migrate Translatathon/TranslatathonCalendar.tsx to Shadcn UI and Tailwind CSS
- This PR migrates TranslatathonCalendar.tsx to Shadcn UI and Tailwind CSS, replacing Chakra UI imports with native tags and Shadcn components.
=> Migrate  Translatathon/TranslatathonCalendar.tsx to Shadcn/Tailwind

src/layouts/Tutorial.tsx
Fixes the address overflow issue on the "Reverse Engineering a Contract" tutorial page, ensuring long addresses wrap on mobile devices.
Resolves #14092
=> feat: address overflow resolved [Fixes #14092]

src/components/Staking/StakingCommunityCallout.tsx
Migrate StakingCommunityCallout Component to tailwind/shadcn
=> Migrate StakingCommunityCallout Component to tailwind/shadcn

src/components/Translatathon/TranslatathonInANutshell.tsx
Migrate Translatathon/TranslatathonInANutshell.tsx to shadcs/tailwind
=> Migrate Translatathon/TranslatathonInANutshell.tsx to shadcs/tailwind

src/components/RollupProductDevDoc.tsx
migration-RollupProductDevDoc.tsx-to-tailwind
i migrationed  `RollupProductDevDoc.tsx` to tailwind
**### Snapshot**
localhost:
ethereum.org:
=> migration-RollupProductDevDoc.tsx-to-tailwind

src/data/community-events.json
ETHCluj date shifted by one week. Updated according to the official website: [ethcluj.org](https://www.ethcluj.org) 
Updated ETHCluj start and end dates in `community-events.json`. Also changed the country code (ROU) to country full name (Romania) just as Eth Bucharest. 
#14484
=> Updated ETHCluj event date

src/pages/what-is-ethereum.tsx
Replacing broken link on Kernel button.
old link: https://www.kernel.community/en/learn/module-1/dreamers
new link: https://read.kernel.community/en/learn/module-1/dreamers
#14493
=> Update what-is-ethereum.tsx - Broken link fix

public/content/developers/docs/smart-contracts/testing/index.md
The following content seems to be partially correct and could use some clarification. The path to the content is:
public/content/developers/docs/smart-contracts/testing
The content is:
"Tests should have good code coverage, otherwise you may get "false negatives" which happen a contract passes all tests, but vulnerabilities still exist in the code."
The rewrite for the above text should go like:
"Tests should have good code coverage to minimize the risk of untested vulnerabilities. Without sufficient coverage, you might falsely assume your contract is secure because all tests pass, while vulnerabilities still exist in untested code paths."
Explanation:
Code Coverage and "False Negatives":
Code coverage measures how much of your code is executed during testing. High code coverage ensures …
=> changes in content

public/manifest.json
The manifest.json file contains a trailing comma after the last property ("description"), which is not allowed in JSON.
=> Remove trailing comma after the last property in manifest.json

src/lib/api/fetchGrowThePie.ts
Switch to weekly active addresses and smaller growthepie API endpoint
- switching to "fundamentals" endpoint instead of "fundamentals_full" - it's a smaller endpoint but still has all required data.
- using "aa_last7d" (Active Addresses last 7 days) instead of "daa" (Daily Active Addresses) since you are referring to this datapoint as weekly active addresses on your page
- small naming fix "growthepie" is how we ideally refer to our platform :)
=> Switch to weekly active addresses and smaller growthepie API endpoint

src/hooks/useCentralizedExchanges.ts
Updated the `usaExceptions` list for `binanceus` to reflect the most current list of unsupported states and territories, including:
- Alaska (AK)
- American Samoa (AS)
- Connecticut (CT)
- Georgia (GA)
- Guam (GU)
- Maine (ME)
- Northern Mariana Islands (MP)
- New York (NY)
- North Carolina (NC)
- North Dakota (ND)
- Ohio (OH)
- Oregon (OR)
- Texas (TX)
- U.S. Virgin Islands (VI)
- Vermont (VT)
- Washington (WA)
None
=> Update Binance US exchange availability by state

.github/workflows/generate-review-report.yml
- Updates to using `actions/upload-artifact@v4`
- `actions/upload-artifact@v2` deprecated
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Fixes:
=> workflow: updates to actions/upload-artifact@v4

public/content/defi/index.md
Bug: The link to 'More on flash loans' on the Ethereum website leads to a 404 error page instead of the intended Aave documentation. This broken link prevents users from accessing detailed information about flash loans.
This PR replace the following links:
old link: https://aave.com/flash-loans
new link: https://aave.com/docs/concepts/flash-loans
#14481
=> Fix Broken Link on Decentralized finance (DeFi).

public/content/smart-contracts/index.md
The link to the article 'Smart Contracts: The Blockchain Technology That Will Replace Lawyers' on the Ethereum website points to the Blockgeeks website, but the destination website is offline, making the content inaccessible.
The original article can be found on the webarchive but there is no other site that has published it. 
That's why I suggest removing it from the page.
#14482
=> Removing Broken Link on Introduction to smart contracts page

public/content/community/research/index.md, public/content/contributing/index.md, public/content/developers/docs/networking-layer/network-addresses/index.md, public/content/developers/docs/nodes-and-clients/run-a-node/index.md, public/content/developers/docs/standards/tokens/erc-223/index.md, public/content/developers/docs/standards/tokens/erc-4626/index.md, public/content/developers/docs/transactions/index.md, public/content/guides/how-to-use-a-bridge/index.md, public/content/roadmap/statelessness/index.md, src/intl/en/page-contributing-translation-program-acknowledgements.json, src/intl/en/page-learn.json
Changed the name of tutorial as the tutorial is now not named like that
=> Update tutorial name and add some missing punctuation

src/components/TutorialMetadata.tsx
Migrated tutorialmetadata component from chakra ui to shadcn and tailwind css
#13946
=> migrated `TutorialMetadata.tsx` to shadcn/tailwind

src/components/TranslationBannerLegal.tsx
=> 🦄 refactor: Migrated `TranslationBannerLegal.tsx` to shadcn

src/components/Translatathon/TranslatathonBanner.tsx
Changes:
- Replaced Chakra UI components (Flex, Text, Button) with Shadcn/Tailwind equivalents.
- Used Tailwind CSS for layout and styling.
=> Migrate TranslatathonBanner to Shadcn/Tailwins

src/intl/en/page-learn.json
Ethereum was misspelt in https://ethereum.org/en/learn/#smart-contracts -> "how do i use ethereum?" ->Card #3
The typo has been rectified. Now Ethereume is replaced with Ethereum.
=> issue #14561 issue fixed, spelling corrected

public/content/developers/docs/smart-contracts/security/index.md
Original solidity code:
pragma solidity ^0.7.0;
contract MutexPattern {
bool locked = false;
mapping(address => uint256) public balances;
modifier noReentrancy() {
require(!locked, "Blocked from reentrancy.");
locked = true;
_;
locked = false;
}
// This function is protected by a mutex, so reentrant calls from within `msg.sender.call` cannot call `withdraw` again.
//  The `return` statement evaluates to `true` but still evaluates the `locked = false` statement in the modifier
function withdraw(uint _amount) public payable noReentrancy returns(bool) {
require(balances[msg.sender] >= _amount, "No balance to withdraw.");
balances[msg.sender] -= _amount;
bool (success, ) = msg.sender.call{value: _amount}("");
require(success);
return true;
}
}
Error in the above code:
bool (success, ) = …
=> error in solidity code

public/content/community/language-resources/index.md, public/content/developers/docs/networking-layer/portal-network/index.md
Corrected `Tutoriales` to `Tutorials`
Corrected `futher` to `further`
=> fix: typos in documentation files

src/data/wallets/wallet-data.ts
* Updates the supported chains for the ShapeShift wallet, based on chains effectively supported in the app/wallet and limited to the ones supported currently by ethereum.org
* Updates the Twitter link to use `x.com` instead of `twitter.com`
* Updates the `last_updated` date.
#14617
=> chore: update shapeshift supported chains

src/lib/api/fetchGrowThePie.ts
- Had an issue where the average txCosts was using all networks from growthepie, but we only show some of the networks. Filtering this down now so that the average costs reflects the networks we show on ethereum.org
=> txCosts using layer2Data

src/components/Staking/StakingGuides.tsx
Changed original Stack with CardList attributes into a CardList with Stack attributes, i.e., from
```<Stack as={CardList} direction="column" gap={4} items={guides}>``` 
to 
```<CardList className="flex flex-col gap-4" items={guides} />```
#13946
=> Migrate Staking Guides to shadcn

src/components/Banners/BugBountyBanner/index.tsx, src/pages/bug-bounty.tsx
Adds info about bug bouty Attackathon
=> Adds info about bug bouty Attackathon

src/intl/en/page-eth.json
Fix typo:
goverened  ->  governed
https://github.com/ethereum/ethereum-org-website/issues/14632
=> fix typo on eth page

public/content/contributing/translation-program/content-buckets/index.md
I noticed that the entry "How The Merge Impacted ETH Supply" was listed twice under the Upgrades section.
This seemed like a small oversight, so I've cleaned it up by removing the duplicate.
=> docs: Fixed Duplicate

src/data/community-meetups.json
- Updated the title and link for the Jeju Blockchain Meetup in the community-meetups.json file to reflect the new name and URL.
- The title was changed from "Jeju Blockchain Meetup" to "Ethereum Jeju".
- The link was updated from "https://www.meetup.com/Jeju-Blockchain-Meetup" to "https://www.meetup.com/Ethereum-Jeju".
=> update community meetup title and url

public/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
Refactored the variable name `node` to `node_hash` to remove ambiguity. This change improves code clarity by explicitly indicating that the variable holds the hash of a node, not the node itself.
- Replaced `node` with `node_hash` throughout the `update` and `delete` functions.
=> Update index.md of Merkle-Patricia Trie doc

src/pages/layer-2/learn.tsx, src/pages/layer-2/networks.tsx
- Updates the ButtonLink component usage to shadcn version
=> fix: use migrated ButtonLink on layer-2 pages

src/lib/api/fetchRSS.ts
Fixed the RSS parsing image logic for medium feeds
Before:
After:
=> fix rss parsing logic

src/pages/developers/tutorials.tsx
Migrate developers/tutorials.tsx to Shadcn
=> Shadcn Migrate: developers/tutorials.tsx

src/components/Simulator/ClickAnimation.tsx, src/components/Simulator/Explanation.tsx, src/components/Simulator/MoreInfoPopover.tsx, src/components/Simulator/NotificationPopover.tsx, src/components/Simulator/PathButton.tsx, src/components/Simulator/Phone.tsx, src/components/Simulator/ProgressCta.tsx, src/components/Simulator/PulseAnimation.tsx, src/components/Simulator/Template.tsx, src/components/Simulator/__stories__/ClickAnimation.stories.tsx, src/components/Simulator/__stories__/Explanation.stories.tsx, src/components/Simulator/__stories__/MoreInfoPopover.stories.tsx, src/components/Simulator/__stories__/PathButton.stories.tsx, src/components/Simulator/__stories__/Phone.stories.tsx, src/components/Simulator/index.tsx, src/components/Simulator/screens/ConnectWeb3/index.tsx, src/components/Simulator/screens/CreateAccount/GeneratingKeys.tsx, src/components/Simulator/screens/CreateAccount/index.tsx, src/components/Simulator/screens/SendReceive/ReceiveEther.tsx, src/components/Simulator/screens/SendReceive/SendEther.tsx, src/components/Simulator/screens/SendReceive/index.tsx, src/components/ui/popover.tsx
Migrates base components for the main `Simulator` component to Tailwind/ShadCN
=> [ShadCN]: Migrate Base Simulator Content 

src/pages/get-eth.tsx, src/pages/stablecoins.tsx
- stablecoins page bank apr data severely outdated with paywalled link—removed.
- 1inch link geo/vpn-blocked—removed.
(Third link in screenshot from old event; already removed)
=> patch: rm old/geoblocked links

src/components/BoxGrid.tsx
Migrate `BoxGrid.tsx` to Shadcn
=> Shadcn Migrate: BoxGrid.tsx

src/components/FileContributors.tsx, src/components/IssuesList/index.tsx, src/components/Leaderboard.tsx, src/components/ui/avatar.tsx
Applies the newest Avatar component to all current instances: `IssuesList.tsx`, `FileContributors.tsx`, and `Leaderboard.tsx`
Two points of note related to the Design System:
- It is intentional in `Leaderboard.tsx` to adhere to the DS, where it is required to supply a value to the `href` prop. It is believed that it is better to address this requirement in the short term with a comment and using `#` as the value in the component instance, instead of making the prop an optional type. This should not be noticeable to the user.
- There are multiple instance where the height and width are set to the token value `10`. This value is not being used in any of the `size` variants in the DS, and therefore explicitly set in the given instances.
Minor impact approaching migrations done for the above …
=> [ShadCN]: Implement ShadCN Avatar to Production

src/components/InfoBanner.tsx, src/pages/dapps.tsx, src/pages/gas.tsx, src/pages/stablecoins.tsx
Migrate `InfoBanner.tsx` to Shadcn
=> Shadcn Migrate: InfoBanner.tsx

src/components/Leaderboard.tsx
Migrate  `Leaderboard.tsx` to Shadcn
=> Shadcn Migrate: Leaderboard.tsx

public/content/developers/docs/gas/index.md
When learning this session, I found that if one transaction has a gas limit of 20000 < 21000, it will fail in the transaction validation phase, and not even enter the EVM execution phase. thus this PR fixes this and adds another case without removing the original meaning.
=> fix: OOG cases

public/content/developers/docs/oracles/index.md, public/content/developers/docs/scaling/state-channels/index.md
Except a dispute arises, the intermediary only has to be contacted when opening or terminating the channel.
This above statement is grammatically incorrect
The correct statement should be:
Unless a dispute arises, the intermediary only has to be contacted when opening or terminating the channel.
=> Fixing typo

public/content/developers/docs/oracles/index.md
Changes made in the file public/content/developers/docs/oracles/index.md
=> fixed typo on the oracles files

public/content/history/index.md
I noticed a small typo in the 2024 section under the Execution upgrade naming table.
For the Cancun upgrade, the Devcon year was listed as 2018, but it should be **2019**. 
Corrected.
P.S. Thanks for Ethereum!
=> docs: Fix incorrect Devcon year Update index.md

public/content/terms-of-use/index.md
A small typo in the **Terms of Use** section. The sentence:  
> "We do not guarantee that our Websites or any content on them will always be available or be interrupted."  
is missing the word **"not"** before "be interrupted." This change ensures the sentence is logically consistent and correctly conveys that interruptions may occur.  
The corrected version should read:  
> "We do not guarantee that our Websites or any content on them will always be available or **not** be interrupted."
=> docs: Fix typo in Terms of Use Update index.md

public/content/translations/pt-br/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
Corrected minor typos and formatting inconsistencies.
- Fix: Corrected Web3. y to Web3.py 
- Fix: Corrected Sãp to São
=> Fix typos and grammar in README.md

public/content/zero-knowledge-proofs/index.md
I noticed a small typo in the first sentence of the description. The article "An" was incorrectly used before "non-technical." Since "non-technical" starts with a consonant sound (/n/), it should be "A non-technical introduction."
This has been corrected.
=> docs: Fix incorrect article Update index.md

public/content/history/index.md
Fixed a typo in the Deneb summary section on the "The History of Ethereum" page by correcting `withdrawal` to `withdraw` for proper grammar.
Resolves #14680
=> fix: typo in Deneb summary section on `The history of Ethereum` page

public/content/developers/docs/data-availability/index.md
- Updated a resource in the further reading section to reflect content moving from [Ethereum 2077](https://ethereum2077.substack.com/) to [2077 Research](https://research.2077.xyz/). 
- Added an explainer on [EIP-7623](https://eips.ethereum.org/EIPS/eip-7623)--a proposal to increase cost of calldata and push rollups towards using blobs (as well as bound maximum block sizes)
=> Updated further reading section of DA page

src/components/ui/badge.tsx
Switch layer-2 networks' tagging color
https://github.com/ethereum/ethereum-org-website/issues/14759
=> Switch layer-2 networks' tagging color

public/content/zero-knowledge-proofs/index.md
- Added [EIP-7503](https://eips.ethereum.org/EIPS/eip-7503) as an example of a proposed design for Ethereum that will enable anonymous ETH transfers with zero-knowledge proofs
- Added an article explaining the mechanics of EIP-7503
=> Add EIP-7503 resources to ZKPs page

public/content/roadmap/account-abstraction/index.md
- Added a research report that discusses EIP-3074, EIP-5806, and EIP-7702 (proposals to give EOAs programmable functionality)
- Added the [Bundlebear dashboard](https://www.bundlebear.com/overview/all) for visitors to track ERC-4337 adoption
- Added an article on [modular account abstraction](https://blog.rhinestone.wtf/part-1-modular-account-abstraction-for-everyone-else-84567422bc46)
=> Add resources to account abstraction page

public/content/developers/docs/nodes-and-clients/index.md
The [consensus clients table](https://ethereum.org/en/developers/docs/nodes-and-clients/#consensus-clients) was not rendering correctly due to misplaced `|` character at the end.
The table prior to the fix looks like this:
=> fix: consensus clients table formatting

src/data/mocks/l2beatData.json, src/pages/layer-2/networks.tsx
https://l2beat.com/api/scaling/summary Endpoint returning `tvs.breakdown.total` but code currently looking for `tvl.breakdown.total` causing `master` branch to break during build.
https://app.netlify.com/sites/ethereumorg/deploys/679ce6c2afa5dc0008ef3c4a
=> [HOT FIX] property name containing total breakdown

src/intl/en/glossary.json
There's an issue with the `re-entrancy attack` glossary definition where the hyperlink is not properly formatted. I have corrected the `<a>` tag, ensuring the link to further information on re-entrancy is displayed correctly. See the screenshot below for reference.
None
=> fix: re-entrancy attack definition link formatting in glossary

src/components/Layer2NetworksTable/NetworksSubComponent.tsx
Add the missing link for the grow the pie on the L2 networks page
https://github.com/ethereum/ethereum-org-website/issues/14840
=> Fix: Add the missing link for the grow the pie on the L2 networks page

src/pages/developers/tutorials.tsx
Removes the remaining Chakra import and applies React's `forwardRef` to `FilterTag`
=> refactor(pages/tutorials): update forwardRef import for `FilterTag`

public/content/developers/docs/scaling/index.md
- Updated a resource in the further reading section to reflect content moving from [Ethereum 2077](https://ethereum2077.substack.com/) to [2077 Research](https://research.2077.xyz/).
- Added a comprehensive article analyzing the different types of rollups (including newer designs like sovereign rollups)
=> Update further reading section on scaling page

next.config.js
- Adds `X-Frame-Options` to response header for all pages with `DENY` value
- Fixes https://github.com/ethereum/devops/issues/1593
=> feat: add X-Frame-Options to header

src/pages/assets.tsx
SVG Download links are broken on this page: https://ethereum.org/en/assets/ 
This is caused by internalization prepending the locale in the URL
https://github.com/ethereum/ethereum-org-website/issues/14600
=> Fix broken SVG assets icons path by using absolute URL from origin

src/components/AssetDownload/index.tsx
gm 🌞
Within the [assets page](https://ethereum.org/en/assets/), images with an accompanying SVG download route to a 404 page when clicked. For example:
The `locale` in the URL appears to be the issue. Assets are rendering fine when I disable the `locale` in the corresponding `ButtonLink` component.
---
Looks like this may close #14600. The linked PR in that issue might be overkill?
=> fix: asset page svg download url

public/content/roadmap/index.md, public/content/roadmap/pectra/index.md, src/lib/utils/md.ts
This PR creates initial documentation of upcoming Pectra upgrade. I followed some format of docs on previous forks but I decided to document each included change with some general info and resources. I think there could still be some more information, maybe images, let me know how I can improve it further
=> Add docs on Pectra

src/pages/roadmap/vision.tsx
Migrate the Roadmap Vision page to use Tailwind
#13946
=> [ShadCN]: Migrate Roadmap Vision page

src/pages/quizzes.tsx
Migrates the quizzes page to ShadCN/Tailwind
#13946
=> [ShadCN]: Migrate quizzes page

src/components/Quiz/QuizWidget/QuizRadioGroup.tsx
Replaces Chakra radio hooks with `RadioGroup` from Radix for the Quiz Widget question choices.
Uses direct import of `RadioGroup` to maintain custom styling.
=> [ShadCN]: Replace Chakra radio hooks with RadioGroup Radix

src/pages/layer-2/index.tsx
Added functionality to highlight robust and maturing networks on Page: https://ethereum.org/en/layer-2/
Added a function to to filter the L2LayerData, if it is "Robust". If the length is 0, then it checks for network that have reached "Maturing" and return max 3 of them at random.
#14910
=> issue:14910 added functionality to highlight robust and maturing networks

public/content/translations/cs/staking/solo/index.md, public/content/translations/zh/staking/solo/index.md
Fixes bug seen in https://ethereum.org/cs/staking/solo/
The current quiz key used in the `cs` and `zh` versions is incorrect.
=> Hotfix incorrect quizkey

src/components/Banners/BugBountyBanner/index.tsx, src/pages/bug-bounty.tsx
Add Pectra info to bug bounty page
=> Add Pectra info to bug bounty page

src/lib/constants.ts, src/lib/utils/md.ts
=> Deprecate allow list

src/styles/global.css
- apply default `border-border` class to all elements
Fixes recent border-color regressions with Chakra theming deprecation
=> fix: apply default border color to all

public/content/developers/docs/data-and-analytics/index.md
- Added an article that discusses retrieval, decoding, and transformation, and utilization of raw on-chain data to build blockchain applications
- Added a blog post on [EQL](https://eql.sh/)--a new tool for efficiently extracting data from EVM blockchains
=> Add resources + info to data/analytics page

public/content/developers/docs/consensus-mechanisms/pos/keys/index.md
- Added information about [EIP-7002](https://eips.ethereum.org/EIPS/eip-7002) (a proposal that will allow validators sign exit messages with their withdrawal keys)
- Added an article on validator key management
=> Update validator keys page

public/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
- Add an explainer on [EIP-7251](https://eips.ethereum.org/EIPS/eip-7251)--a proposal to increase maximum effective balance for validators (with implications for validator rewards and penalties) 
- Added an analysis of changes to slashing/penalty mechanisms under EIP-7251
=> Update further reading section on PoS rewards/penalties page

public/content/developers/docs/nodes-and-clients/index.md
- remove beta from Grandine, v1.0.0 launched
- Remove deprecated networks: goerli and ropsten
- Add Holesky to consensus clients
=> Update consensus client listings

src/components/Banners/BannerNotification.tsx
Makes banner notification full width
Fixes:
=> fix: full width BannerNotification

src/pages/[locale]/index.tsx
=> fix: fix centered labels in code examples section on homepage

src/components/CentralizedExchanges/index.tsx
Fixes zindex issue in country picker select for CentralizedExchanges component
=> fix: Adjust z-index for CentralizedExchanges Select component

docs/review-process.md
I noticed a grammatical issue in the "Adding products" section. The sentence:
"...ensure we not sending our users to any dubious or unsafe products."
has been corrected to:
"...ensure we **are** not sending our users to any dubious or unsafe products."
This small adjustment improves clarity and correctness.
=> docs: fix minor stylistic issue in "Adding products" section

src/pages/[locale]/gas.tsx
This PR fixes an issue where an unexpected translation key was appearing on the Gas page.
[#15021](https://github.com/ethereum/ethereum-org-website/issues/15021)
Prod:
Preview:
=> fix: Fix unexpected translation keys on gas page [Fixes #15021]

public/content/developers/docs/smart-contracts/testing/index.md
Hi! While reviewing the documentation, I noticed that a link to Foundry's testing framework (forge) was broken. The original link pointed to an outdated path (https://github.com/foundry-rs/foundry/tree/master/forge), which no longer exists. I’ve updated it to the correct path: https://github.com/foundry-rs/foundry/tree/master/crates/forge.
=> fix: dead link in doc

public/content/roadmap/pectra/index.md
Adds additional context to EIP7691 within the Pectra roadmap section
https://github.com/ethereum/ethereum-org-website/issues/14893
=> docs(roadmap): add PeerDAS context to EIP-7691 description

public/content/community/online/index.md
I noticed a wording issue in the "YouTube and X formerly (Twitter)" heading.
The phrase "formerly (Twitter)" sounded a bit unnatural, so I adjusted it to "YouTube and X (formerly Twitter)" for better readability.
=> docs: fix wording in "YouTube and X" section

public/content/defi/index.md
A grammatical error in the text: "time zone" was missing the article "a." This caused the sentence to be incorrect.
Added the article "a" to make the sentence grammatically correct.
=> docs: fix grammar issue with article usage before "time zone"

public/content/developers/tutorials/erc20-with-safety-rails/index.md
"miught" → "might" in the section about smart contract events.
=> docs: fix typo in documentation

src/pages/_document.tsx
Hotfix https://github.com/ethereum/ethereum-org-website/pull/15058
=> Correctly set HTML lang attribute (hotfix from https://github.com/ethereum/ethereum-org-website/pull/15058)

src/pages/_document.tsx
The `lang` html attribute was always defaulting to "en" regardless of the actual page locale. My understanding is we use the `lang` to split our search indexes, so this bug is causing all languages to be [searchable in English](https://discord.com/channels/420394352083337236/426091468403376128/1349122790258770013), and none of the non-English languages have any search hits at all.
Solution is... maybe hacky? I modified _document.tsx to extract the locale from query parameters in getInitialProps. This ensures the `lang` is properly set for the crawler to see.
After testing/merging this PR, we need to run a [recrawl on Docsearch to fix the bug](https://crawler.algolia.com/admin/crawlers/d9cd038f-c91f-471d-99bc-f9a3f370beb3/overview)
=> Correctly set HTML lang attribute

src/pages/[locale]/resources.tsx
- Fix banner notifcation mobile text alignment
- Fix z-index for sub nav
none filed
=> fix: banner/subnav layout on resource dashboard

public/content/roadmap/account-abstraction/index.md
removing irrelevant EIPs and updating text based on shipped 4337 and adding info about 7702 being included in Pectra and other improvements in fusaka upgrades.
=> Updating AA page

src/components/icons/EthHomeIcon.tsx
Fixes
```
Warning: Invalid DOM property `stroke-linejoin`. Did you mean `strokeLinejoin`?
at path
at svg
at IconBase
at Comp (webpack-internal:///./src/components/icons/icon-base.tsx:23:21)
at a
at LinkComponent (/Users/corwinsmith/Documents/work/ethereum-org-website/node_modules/next/dist/client/link.js:121:19)
at BaseLink (/Users/corwinsmith/Documents/work/ethereum-org-website/node_modules/next-intl/dist/development/navigation/shared/BaseLink.js:20:5)
at Link (/Users/corwinsmith/Documents/work/ethereum-org-website/node_modules/next-intl/dist/development/navigation/shared/createSharedNavigationFns.js:36:7)
at Link (webpack-internal:///./src/components/ui/Link.tsx:48:102)
at div
at nav
at div
at Nav (webpack-internal:///./src/components/Nav/index.tsx:60:94)
at div
at BaseLayout …
```
=> stroke-linejoin -> strokeLinejoin

public/content/translations/fr/developers/docs/smart-contracts/upgrading/index.md, public/content/translations/zh-tw/history/index.md
Fixes html syntax nested within markdown
Currently breaking dev builds
=> fix: markdown syntax

public/content/desci/index.md
- Fixes link with stray hidden character; was causing issues on each translated version and showing up in markdown checker
None filed
=> fix: hidden character in link

src/components/ListenToPlayer/index.tsx
- Hides the listen to player on non english pages since this content is only in english at the moment
=> Hide listen to player on non-english pages

src/pages/[locale]/stablecoins.tsx
Replaced outdated link (https://www.trusttoken.com/) with the current official TUSD site (https://tusd.io/). The old link was broken.
=> update broken TrustToken link to new TUSD website

public/content/developers/docs/networking-layer/portal-network/index.md
When browsing the portal network page in the developer docs I found that the link to the Fluffy portal network client is broken. This change updates the link to point to our Fluffy book/documentation site.
=> Update link to Fluffy on the Portal Network page

public/content/bridges/index.md
I’ve corrected a grammatical mistake in the blockchain description—changed "develop" to "**are developed**" for better accuracy and clarity.
=> docs: fix grammatical error

public/content/bridges/index.md
I noticed a few grammatical errors and awkward phrases in the documentation. Specifically:
1. Changed **"Types of bridge"** to **"Types of bridges"** for proper plural usage.
2. Updated **"Use bridge"** to **"Using bridges"** to correct the phrasing.
3. Corrected **"Risk using bridges"** to **"Risks of using bridges"** for clarity and accuracy.
These changes should improve the readability and correctness of the text.
=> docs: fixed grammatical issues in "Blockchain Bridges" section

docs/applying-storybook.md, docs/best-practices.md, docs/header-ids.md, docs/translation-program.md
"notated" → "noted" (correct meaning in context)
Fix article usage (File: relevant doc)
"place index markdown file" → "place an index markdown file" (missing article)
"for header on every" → "for headers in every" (plural & correct preposition)
"translating the website to your language" → "translating the website into your language" (correct usage)
=> Grammar & Wording Fixes in Docs

src/components/TutorialMetadata.tsx
This PR fixes the issue where the time-to-read label was being duplicated in the UI. 
The problem was in the TutorialMetadata component where both the translated string from `comp-tutorial-metadata-minute-read` AND a hardcoded "minute read" text were being displayed together, causing strings like:
- "28 minute read minute read" in English
- "28 minute de citit minute read" in Romanian
The fix simply removes the hardcoded "minute read" text since it's already included in the translation string.
Fixes #15174
=> Fix: Remove duplicate 'minute read' text in tutorial metadata

src/data/listen-to-feature/playlist.ts
- Normalize slugs for comparison function used by listen to feature
Fixes redirect bug for /eth /what-is-ethereum /wallets pages
=> Listen to feature slug normalizing

src/lib/utils/data/cacheAsyncFn.ts
- skip "Cache hit gfissues" log output
- removes potentially >30k logs during build.
None filed; 34,360 logs of "Cache hit gfissues" in build logs:
https://app.netlify.com/sites/ethereumorg/deploys/67e5fa6c532a270008eaf31f
=> build: skip "Cache hit gfissues" log output

app/[locale]/[...slug]/page.tsx, src/lib/md/data.ts
Removes hardcoded read time for tutorials and calculate it using `reading-time` lib.
=> Hotfix reading time for tutorials

public/content/developers/docs/data-structures-and-encoding/ssz/index.md
This PR adds a link to the RLP serialization documentation from the SSZ documentation page. This improves navigation between related documentation pages and helps users understand the relationship between these two serialization methods.
The changes include:
- Added a link to the RLP documentation in the SSZ documentation page
- The link text is "Recursive-length prefix (RLP)"
- The link points to `/developers/docs/data-structures-and-encoding/rlp/`
This PR fixes [#15161](https://github.com/ethereum/ethereum-org-website/issues/15161), which requested adding a redirect link from the SSZ documentation to the RLP documentation page.
=> docs: add RLP link to SSZ documentation

app/[locale]/get-eth/page.tsx
Builds `/get-eth` page statically because it needs to run `git log` command and that is not possible on runtime.
Page: https://deploy-preview-15295--ethereumorg.netlify.app/en/get-eth/
=> Hotfix get eth page

src/data/community-events.json
- Removes 2025 staking summit event given reports of unethical behavior https://www.patreon.com/posts/scam-alert-dubai-126772229 and absence of Ethereum-related staking topics ([Website](https://www.stakingsummit.com/) has only mentions of bitcoin staking)
- Event previously with EthStaker involvement, but no associated for this event
=> revert: staking summit listing

public/content/roadmap/pectra/index.md
A few minor changes to the Pectra page in advance of the mainnet announcement.
=> Pectra Upgrade Modifications

src/components/DocLink/index.tsx
Currently when clicking on internal link in Learn page ( https://ethereum.org/en/learn/ ), it ended up in 404 redirect, because of the missing i18n (links are pointed to `https://ethereum.org/quizzes/` and not to `https://ethereum.org/[locale]/quizzes/`m which resulted in 404 page not found. 
I mean links in these sections:
I've fixed it by using the `InlineLink` component in `DocLink` component, which handles the addition of i18n locale to links automatically.
=> fix: DocLink routing; use internal link component

src/lib/utils/metadata.ts
Fixes broken og image paths for share links
Uses SITE_URL as the metadataBase URL... realtively image paths will then build on that.
Other URLs utilize `getFullUrl`
Image paths were inappropriately being taken from the current path, resulting in `ethereum.org/en/images/...` or `ethereum.org/en/staking/images...`  instead of `ethereum.org/images/...` breaking share link images
=> fix: metadataBase to use SITE_URL

src/lib/constants.ts
- Adds [Geodework Blog](https://geodework.com/blog) to homepage rss feeds
https://deploy-preview-15404--ethereumorg.netlify.app/en/#recent
=> feat: add geodework blog to homepage feeds

docs/stack.md
We do not have ALGOLIA_DOCSEARCH.md already so we need to remoce this ded 'text' not to mislead the user.
=> docs (`stack.md`): remove part about Algolia

public/content/history/index.md
=> patch: pectra complete, update language

src/data/roadmap/releases.tsx
Replaced the url of the 'Learn more' button of the Fusaka upgrade slide into PeerDAS EIP URL
Closes: #15410
=> Replace URL on the roadmap page 

src/intl/es/common.json
This PR fixes the incorrect translation in the Spanish version footer where "UX/IU" is used instead of the globally recognized standard "UX/UI". While "IU" (Interfaz de Usuario) is technically the correct Spanish abbreviation for User Interface, the standard order "UX/UI" is widely recognized in technical and design contexts, including in Spanish-speaking environments.
* Changed "Lo esencial del diseño de la UX/IU" to "Lo esencial del diseño de la UX/UI" in `src/intl/es/common.json`
As pointed out by native Spanish speakers in the original issue, although "IU" is technically correct in Spanish, "UX/UI" has become the internationally recognized standard even in Spanish technical documentation and design fields. This change improves consistency with industry standards and professional …
=> fix: correct Spanish translation of UX/UI in footer [FIXES #15173]

app/[locale]/layer-2/_components/layer-2.tsx, src/components/Layer2NetworksTable/NetworksSubComponent.tsx, src/components/Layer2NetworksTable/hooks/useNetworkColumns.tsx, src/lib/types.ts
handles falsy values and adds type definitions to missing parts
=> hotfix layer 2

src/components/Footer.tsx, src/components/ui/buttons/Button.tsx, src/layouts/BaseLayout.tsx, src/lib/utils/scrollIntoView.ts
The "Go to top" button was not functioning due to a missing anchor target.
This PR:
- Adds an `id="top"` to the `main` container in `BaseLayout.tsx`
- Updates the `href` used by the "Go to top" button in `Footer.tsx` to point to `#top`
Fixes [#15412](https://github.com/ethereum/ethereum-org-website/issues/15412)
=> Fix go to top [Fixes #15412]

public/content/developers/docs/data-structures-and-encoding/rlp/index.md
The spacing on the line that `raises` was invalid python.  It produces the error 
```
File "/home/dave/tmp/dev/python/main.py", line 18
raise Exception("input too long")
^
IndentationError: unindent does not match any outer indentation level
```
This update fixes the indentation so that a reader can copy and paste the code.
None, just fixes a type in some docs.
=> Fix typo in python example code

public/content/roadmap/pectra/maxeb/index.md
Adding in third-party consolidation tooling, added in a question for FAQ
There's currently nowhere to get an overview of third-party tooling that provide features that the Launchpad doesn't provide (e.g. using a SAFE as a withdrawal address, batching consolidations, etc). while they're third-party and not endorsed by ethereum.org, it's still good to have community-consensus "legit" tooling listed to minimize scam opportunities
n/a
=> Adding in third-party consolidation tooling, augmented FAQ

src/intl/de/page-gas.json
Fixed quote escaping in the German translation file (`src/intl/de/page-gas.json`) where link quotes were not properly escaped.
Modified line 56 to change the link format from `href="/developers/docs/gas/"` to the correct format `href=\"/developers/docs/gas/\"` to ensure proper JSON formatting. Also fixed the quote escaping in the `translate="no"` attribute.
Before:
```json
"page-gas-faq-question-1-a-2": "Eine detaillierte Beschreibung des Prozesses finden Sie in den <a href="/developers/docs/gas/" translate="no">Sprit-Entwicklerdokumenten</a>.",
```
After:
```json
"page-gas-faq-question-1-a-2": "Eine detaillierte Beschreibung des Prozesses finden Sie in den <a href=\"/developers/docs/gas/\" translate=\"no\">Sprit-Entwicklerdokumenten</a>.",
```
#15349
=> fix: quotes escaping in German gas page link [FIXES #15349]

src/components/ActionCard.tsx
Image in ActionCard not fitting properly on mobile
When viewed in the mobile screen the alignment and size of the image was wrong fixed the alignment 
- Before 
- After 
[
](url)
Link to issue - https://github.com/ethereum/ethereum-org-website/issues/14920
=> cosmetic:Fixed mobile view for action card

public/content/developers/docs/programming-languages/javascript/index.md
Hi, Holger from the JavaScript team here, this PR updates some outdates EthereumJS related packages links and name references, so from [”Ethereum for JavaScript developers"](https://ethereum.org/en/developers/docs/programming-languages/javascript/) page.
I think we can generally look over this page a bit, could use some updates, also EthereumJS is a bit too much in focus, should likely go more broadly, so much happening in dev ecosystem. We'll keep a bit an eye on this and eventually submit a few subsequent PRs! 🙂 
Here just this small separate update though!
=> Update some EthereumJS related links

app/[locale]/wallets/find-wallet/_components/find-wallet.tsx
- Fixes regression for find wallet hero for new design
=> fix hero regression on find wallet

src/components/Footer.tsx, src/layouts/Docs.tsx
=> fix: intl strings for go/back to top

app/[locale]/dapps/_components/dapps.tsx, public/content/developers/docs/programming-languages/python/index.md, public/content/guides/how-to-swap-tokens/index.md
- Fix curve.finance links
([announcement tweet](https://x.com/CurveFinance/status/1922664429646184482))
- Fix category selection button layout on desktop (adjusts grid to only 4 categories)
https://deploy-preview-15502--ethereumorg.netlify.app/en/dapps
=> fix: /dapps page patches

app/[locale]/page.tsx, src/lib/utils/metadata.ts
- updates the home page to display correct metadata
- filters the `alternates` paths by valid `ISO639_1` locales (missing part in #15200 implementation)
=> fix: home page metadata

public/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
Description
This pull request fixes a small typo in the content. The phrase "really dummy" was changed to "real dummy", improving grammar and readability.
Related Issue
N/A – This is a minor typo fix and doesn't correspond to a previously opened issue.
Type of Change
Bug fix (non-breaking change which fixes a typo)
=> Fixed typo: "really dummy" → "real dummy"

src/lib/api/fetchRSS.ts
The existing logic isn't parsing image properly.
This PR:
1. Use the first url in the matching array, instead of the whole array
2. Use this logic as default
Before: 
After: 
n/a
=> Fix: rss image parsing logic

public/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
Fixes md table on https://ethereum.org/en/developers/docs/data-structures-and-encoding/patricia-merkle-trie/
prod: 
deploy preview:
n/a
=> fix: markdown table format in developers docs

app/[locale]/roadmap/_components/ReleaseCarousel.tsx, src/data/roadmap/releases.tsx
- refactor: use releaseDate and plannedReleaseYear
- fixes start index bug
- removed 2 month window for upcoming; defines production as releaseDate in past, upcoming as releaseDate in the future, and in development as no releaseDate but optional plannedReleaseYear.
=> fix: start index for Roadmap carousel

src/layouts/Docs.tsx
Fixes a bug where nav items failed to open due to incorrect `path` props
prod:
https://github.com/user-attachments/assets/4e1afd4c-c44c-4816-8187-643c5266ed98
localhost:
https://github.com/user-attachments/assets/6a87a1a8-bc1e-4858-ad5b-7271086d69db
n/a
=> fix: correct path passed to SideNav

public/content/staking/withdrawals/index.md
there was a banner on top about withdrawal being live which has been 2 years ago at this point
=> remove old info from withdrawal page

app/[locale]/roadmap/_components/ReleaseCarousel.tsx
- Tiny left-over refactor from ReleaseCarousel changes
=> refactor: hasUpcomingRelease using .some

src/hooks/useRefWidth.ts
Fixes: `React Hook useEffect has a missing dependency: 'updateWidth'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps`
=> fix: react-hooks/exhaustive-deps

app/[locale]/page.tsx, src/lib/constants.ts
- Adds array of xml fetches to skip, ie non-xml html parsing
- Adds Attestant to this array
Fixes: `Error parsing XML, invalid RSSResult or AtomResult type: https://www.attestant.io/posts/`
This was expected with existing setup since we were fetching this in a custom manner _and_ also keeping it in the list to attempt an XML fetch, when we know that will fail.
=> fix: skip attestant xml attempt

src/components/MarkdownImage.tsx, src/components/ui/Link.tsx
- Adds `referrer` to external links currently missing it
- Intent to block third-party cookies from links we load in various places
Inappropriate third-party cookies being loaded:
=> fix: noreferrer for all links; block cookies

app/[locale]/10years/page.tsx
```sh
$ curl -I https://ethereum.org/en/10years/
HTTP/2 500
...
```
Page loading, but returning 500; blocking opengraph share sheet generation
=> hot-fix: 10years page 500; use ssr false for globe

app/[locale]/10years/_components/TenYearHomeBanner.tsx
- Use next/image component for 10y homepage callout background image
=> fix: use next/image

src/lib/utils/rss.ts
fixes `Invalid date found: 2024年8月22日 2024年9月13日` error pattern
=> fix: sorting using pre-translated dates

src/data/staking-products.json
The GitHub repository https://github.com/eth-educators has been migrated to https://github.com/ethstaker / https://github.com/ethstaker/eth-docker. 
I searched through the repository for eth-educator related items and only found one :)
=> change "eth-educators" url path to ethstaker

public/content/developers/docs/apis/json-rpc/index.md
This pull request fixes a small typo in the content. The word "of" was changed to "if", improving readability.
N/A – This is a minor typo fix and doesn't correspond to a previously opened issue.
Bug fix (non-breaking change which fixes a typo)
=> Typo fix: "returns `true` of the client is mining" → "returns `true` if the client is mining"

.github/workflows/claude.yml
=> Add Claude GitHub action

app/[locale]/page.tsx, src/intl/en/page-index.json
- Adds `/enterprise` CTA button link to the #activity section of the homepage as primary action
https://deploy-preview-15707--ethereumorg.netlify.app/en/#activity
=> feat: add enterprise cta to home activity

docs/ds-implementation.md
The previous link (/docs/styled-system/theme) was broken and led to a 404 Page Not Found error on the Chakra UI documentation site.
The updated link (/docs/components/theme) correctly redirects to the Theme component documentation, which provides relevant usage and examples. Ensuring correct documentation links improves developer experience and prevents confusion during design system implementation.
=> updates a broken link in the docs/ds-implementation.md

src/components/ui/avatar.tsx
ui/avatar has been using radix component for image rendering, foregoing next image optimization
- Uses internal Image component to render github contributor avatars; domain allow-listed in next config
Resolves:
=> perf: use Next image for avatars

src/components/Morpher.tsx
- Fix memory management by using useRef for timeout variables
- Add accessibility support with usePrefersReducedMotion hook
- Reduce animation frame rate from 30 to 24 FPS for better performance
- Implement deferred animation start (2s delay) to improve initial page load
- Prevent multiple simultaneous animations with proper state tracking
- Optimize React re-renders by only updating state when text changes
- Add proper cleanup to prevent memory leaks and runaway animations
Note: part of the efforts to reduce INP and TBT.
=> Optimize Morpher performance for mobile devices

.claude/commands/update-llms-txt.md
Claude slash command to keep `llms.txt` updated.
=> Slash command to keep llms.txt file updated

app/[locale]/assets/page.tsx
=> fix: /assets metadata string key

app/[locale]/stablecoins/page.tsx
=> fix: handle missing CoinGecko stablecoin data gracefully

public/content/roadmap/pectra/7702/index.md
=> add addresses and Calibur (Uniswap)

src/components/Morpher/index.tsx
after initial load (words[0]), start iterating list from words[1]
fixes duplication of first word after initial load
=> fix: initial morpher transition

public/content/developers/docs/standards/tokens/erc-20/index.md
I've updated the description of the **ERC-20 token reception issue block** on the **ERC-20 TOKEN STANDARD** page. 
Closes https://github.com/ethereum/ethereum-org-website/issues/13218
=> Update: ERC-20 Token Standard description [Fixes #13218]

public/content/developers/docs/nodes-and-clients/node-architecture/index.md
Add detailed explanation for RANDAO in the Node Architecture documentation to improve first-time reader experience.
Fixes #12059 
The Node Architecture page mentioned RANDAO in the node comparison table without providing any context or explanation, making it difficult for newcomers to understand what RANDAO is and its purpose in Ethereum's consensus mechanism. This was identified as a user experience issue in the GitHub issue.
- Enhanced RANDAO description in the node comparison table from:
```
Keeps track of accumulated randomness in RANDAO
```
to:
```
Keeps track of accumulated randomness in RANDAO (an algorithm that provides verifiable randomness for validator selection and other consensus operations)
```
=> Add RANDAO explanation to Node Architecture page

public/content/developers/docs/apis/json-rpc/index.md
Use [Execution APIs](https://ethereum.github.io/execution-apis/) as the Execution APIs' link
=> [R4R] typo: Update index.md to fix Execution API webpage URL

public/content/developers/docs/apis/json-rpc/index.md
The current JSON-RPC page has a section about the _"extra default block parameter"_. The words "extra" and "default" are ambiguous and confusing because the spec actually requires this parameter.
N/A
=> feat: update ambiguous wording about RPC block parameter

src/components/DataTable/index.tsx
My update resolves an issue where the non-standard value `duration-25` was used in a TailwindCSS class. TailwindCSS only supports predefined duration values such as `duration-75`, `duration-100`, `duration-200`, etc.  
The incorrect `duration-25` value has been replaced with a valid option to ensure compatibility with the framework. This adjustment aligns the code with TailwindCSS conventions and avoids potential styling inconsistencies.  
Thanks!
=> fix: Correct invalid duration-25 value in TailwindCSS classes

public/content/developers/docs/nodes-and-clients/index.md
The ProbeLab team (https://probelab.io) is crawling the CL of Ethereum, using the Nebula crawler (https://github.com/dennis-tra/nebula) and creating weekly reports that include several metrics for the P2P network. We believe the metrics would be of interest to the community and the developers.
The latest report can be found here: https://probelab.io/ethereum/discv5/2024-50/ and the methodology here: https://probelab.io/ethereum/discv5/methodology/.
There is no issue related to this PR, as the work to deploy and run the crawler has already been done and reports are live (published every Monday).
=> Adding ProbeLab's Weekly Reports

public/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
- #14486 accidentally reverted `node_hash` changes; reinstates changes from #13758
=> patch: node_hash reversion

app/[locale]/10years/_components/CurrentTorchHolderCard.tsx, app/[locale]/10years/_components/TorchHistoryCard.tsx, app/[locale]/10years/_components/TorchHistorySwiper/index.tsx, app/[locale]/10years/page.tsx, next.config.js, src/components/ui/avatar.tsx, src/lib/torch/etherscan.ts, src/lib/torch/index.ts
- Integrate Etherscan API to fetch live Torch transfer events and holder data
- Implement current torch holder display with Twitter avatar integration
- Link to tx instead of address
=> Hotfix torch

src/components/ui/avatar.tsx, src/lib/torch/index.ts
Current url hits a redirect that might be causing issues with Netlify's image service and making it use the fallback image.
=> Hotfix twitter avatar

app/[locale]/10years/_components/TorchHistoryCard.tsx, app/[locale]/10years/_components/TorchHistorySwiper/index.tsx
=> [Test] - Fix to form

app/[locale]/10years/_components/TorchHistorySwiper/index.tsx
Problem: All future torchbearer placeholders show the same generic "Coming soon!" message, providing no indication of when each person will receive the torch.
Solution: Replace generic messaging with specific dates showing when each torchbearer will receive the torch:
Torchbearer 1: "Coming July 20th!"
Torchbearer 2: "Coming July 21st!"
Torchbearer 3: "Coming July 22nd!"
And so on...
Supersedes #15886
=> Improve torch card placeholder copy 

public/content/staking/solo/index.md
- Updates copy inside FAQ on solo staking page about depositing more than 32 ETH
=> fix: outdated max-eb copy in solo staking faq

app/[locale]/resources/page.tsx
- Add z-index to subnav bar, `z-docked` (`z-index: 10;`)
- Fixes #15712
- Closes #15717
=> fix: subnav z-index [Fixes #15712]

public/content/developers/docs/networks/index.md
The Ephemery network is currently missing from the list of public testnets. It's a special one and mostly operated by community so it could be described in more detail. 
The PR is adding the basic description highlighting use cases and all relevant resources.
=> Add ephemery testnet to networks

public/content/developers/docs/data-and-analytics/index.md, public/content/developers/docs/gas/index.md, public/content/developers/docs/intro-to-ether/index.md, public/content/developers/docs/mev/index.md, public/content/developers/docs/scaling/optimistic-rollups/index.md, public/content/developers/docs/smart-contracts/verifying/index.md, public/content/developers/tutorials/erc20-annotated-code/index.md, public/content/developers/tutorials/erc20-with-safety-rails/index.md, public/content/developers/tutorials/how-to-mint-an-nft/index.md, public/content/developers/tutorials/learn-foundational-ethereum-topics-with-sql/index.md, public/content/developers/tutorials/optimism-std-bridge-annotated-code/index.md, public/content/developers/tutorials/uniswap-v2-annotated-code/index.md, public/content/guides/how-to-id-scam-tokens/index.md, src/components/History/NetworkUpgradeSummary.tsx
let's update some of these links and add new links to blockscout on some popular pages to drive more traffic to blockscout because they are open source and etherscan is not!
(also blockscout is supporting Speedrun Ethereum and we want to get them more support!)
=> let's update some of these links and add new links to blockscout (open source!) 

public/content/developers/docs/networks/index.md
Fixes build-breaking MDX error
```
12:23:06 PM: [Error: [next-mdx-remote] error compiling MDX:
12:23:06 PM: Unexpected character `5` (U+0035) before name, expected a character that can start a name, such as a letter, `$`, or `_`
12:23:06 PM: More information: https://mdxjs.com/docs/troubleshooting-mdx] {
12:23:06 PM:   digest: '3504767675'
12:23:06 PM: }
```
=> fix: mdx syntax

src/data/community-meetups.json
Summary
This PR updates the Ethereum Jakarta (ETHJKT) community link on the ethereum.org website. Previously, the link pointed to our Meetup page. We are now directing users to our official website at https://ethjkt.com for up-to-date events, community resources, and initiatives.
Changes Made
Updated the ETHJKT community link in the respective JSON/YAML or markdown content file.
Ensured the new link points to: https://ethjkt.com
Why this change?
The official website provides a more comprehensive and updated representation of Ethereum Jakarta, including upcoming events, past activities, media, and partnership opportunities.
Checklist
Updated URL points to https://ethjkt.com
Verified link works
Additional Notes
ETHJKT is growing rapidly, and this change ensures visitors are directed to the …
=> 🔧 Change ETHJKT Link from Meetup to Official Website

public/content/developers/tutorials/ethereum-for-web2-auth/index.md
Just a small text correction.
#15940
=> Fix typo from 'Using Ethereum for web2 authentication'

src/data/staking-products.json
_tl;dr: Update of Rocket Pool entry price 10.4 ETH -> 8 ETH._
On Ethereum.org website, [the Node tools section](https://ethereum.org/en/staking/solo/#node-and-client-tools) is saying that entry price for stacking on Rocket Pool is 10.4 ETH.
It used to be true since RP was asking for 8 ETH + equivalent of 2.4 ETH converted in RPL (Rocket Pool token) but since recent update ("[Saturn 0](https://docs.rocketpool.net/guides/saturn-0/whats-new)") that's not the case anymore.
People can create 8 ETH ([source](https://rocketpool.net/node-staking/rocket-pool-vs-solo-staking)) node only (without RPL) on Rocket Pool, so correct entry price is only 8 ETH now.
=> fix: Change Rocket Pool entry price

src/components/FeedbackWidget/FixedDot.tsx
The current animation causes the icon to jump outside its container, briefly triggering a horizontal scrollbar.
Matching the animation timings seems to fix this and have a smooth transition.
https://github.com/user-attachments/assets/cdb812d9-a0c0-44df-b4b0-9d9bd615c344
=> Fix feedback button animation

public/content/developers/docs/apis/backend/index.md
the docs link was going to Chainbase by accident.
switched it over to the right one: [https://docs.chainstack.com/](https://docs.chainstack.com/).
=> docs: fix broken documentation link to Chainstack

public/_redirects, src/components/Translatathon/TranslatathonCalendar.tsx
Current redirect structure is redirection /developers/docs/dapps to /developers/docs/apps
This PR adds condition to maintain /developers/docs/dapps as a valid path
https://deploy-preview-16097--ethereumorg.netlify.app/en/developers/docs/dapps
=> hotfix /apps redirect making /developers/docs/dapps unreachable

src/intl/en/page-index.json
- Applies descriptive label to `/stablecoins/` link on homepage
https://developer.chrome.com/docs/lighthouse/seo/link-text
=> seo: use descriptive link label

app/[locale]/stablecoins/page.tsx, src/intl/en/page-stablecoins.json
=> chore: conclude test; use original

app/[locale]/developers/page.tsx, src/components/BigNumber/index.tsx
- Updates BigNumbers with `light` variant
- Adds three-variant A/B test `2025-08-why-dev` to /developers page
- `Original`: Empty component
- `Variation1`: "Why" section without metrics
- `Variation2`: "Why" section with metrics
https://deploy-preview-16117--ethereumorg.netlify.app/en/developers
=> init: A/B test 2025-08-why-dev

src/components/LanguagePicker/useLanguagePicker.tsx
- Restores functionality that surfaced full list of browser language preferences to the top of the language picker.
https://deploy-preview-16000--ethereumorg.netlify.app/es
cc: @konopkja
=> fix: highlight all browser language preferences

app/[locale]/contributing/translation-program/translatathon/leaderboard/_components/Leaderboard.tsx, app/[locale]/contributing/translation-program/translatathon/leaderboard/page.tsx, public/content/contributing/translation-program/translatathon/details/index.md, src/components/Translatathon/ApplyNow.tsx, src/data/mocks/translatathonTranslators.json, src/layouts/md/Translatathon.tsx, src/lib/api/fetchTranslatathonTranslators.ts
Adds translatathon leaderboard page on /contributing/translation-program/translatathon/leaderboard
https://deploy-preview-16136--ethereumorg.netlify.app/en/contributing/translation-program/translatathon/leaderboard
=> Translatathon leaderboard

src/components/AB/TestWrapper.tsx
- Within `ABTestWrapper` component, check locale—if non-English, return fallback/original variant
- Adds `enableAllLocales` boolean prop to override and allow test component to render for all locales
A/B test cases to use English by default—should avoid rendering English test cases on non-English locales
=> patch: use fallback/original variant for non-EN A/B tests

public/content/wrapped-eth/index.md, src/layouts/Static.tsx
- Adds `Alert` component to static template component options
- Adds top-level notice on /wrapped-eth to wrapeth.com for quick access
=> feat: add wrapeth.com link to /wrapped-eth

instrumentation-client.ts, sentry.edge.config.ts, sentry.server.config.ts
Reduces it to `0.01` and ignores `middleware` transactions.
=> Sentry traces sample rate

public/_redirects
Updates `_redirects` file by removing the `/en` path (not needed anymore).
=> Remove /en from Netlify redirects

public/content/dao/index.md
Hi, David from DeGov.AI here.
Here's the reason for this pull request:
1. Add DeGov.AI list of DAOs 
2. Add DeGov.AI Launcher for new DAOs looking to launch a DAO platform for free.
DeGov.AI is an AI-powered governance platform designed for DAOs that use the OpenZeppelin Governor framework. What sets DeGov.AI apart is its [agent governance](https://docs.degov.ai/governance/agent/overview/) feature, which allows AI agents to participate in the governance process, enhancing decision-making and community engagement.
This update introduces a list of DAOs currently supported by DeGov.AI, with plans for exponential growth in the coming months (development began approximately five months ago). 
It also includes the DeGov.AI Launcher instance, which is free to use, with details provided in the …
=> Add DeGov.Ai DAOs and Launcher to Ethereum website

public/content/developers/docs/smart-contracts/anatomy/index.md
I went through the docs and replaced broken/outdated `readthedocs.io` links with the current `docs.vyperlang.org` and `docs.soliditylang.org` equivalents.
=> docs: fix outdated links

public/content/developers/docs/smart-contracts/composability/index.md
Fixed the link to the composability article so it points to the right page.
=> docs: fix broken link to composability article

src/styles/semantic-tokens.css, tailwind.config.ts
Remove unused vars from theme and format `semantic-tokens.css` file
=> Clean up theme

public/content/community/grants/index.md
Added Karma funding map to grant directories section
Karma maintains a directory of various funding opportunities in the web3 ecosystem. Added the link to the Karma's funding map in the section that lists all the directories.
=> add Karma Funding Map to grants list

public/content/developers/docs/standards/tokens/erc-1155/index.md
the old link to the NFT API docs was no longer valid.
updated it to the current reference page to avoid broken redirects and ensure developers can find the right documentation quickly.
=> docs: update outdated Alchemy NFT API docs link

src/components/StablecoinAccordion/AccordionCustomItem.tsx, src/intl/en/page-stablecoins.json
- Updates StablecoinAccordion to use default chevron icon from design system instead of more/less
- Fixes bug where opening two or more items in succession was not switching "Less" back to "More"
- Removes now-unused "More"/"Less" intl strings
- Fixes #15398
=> fix: stablecoin accordion indicator

src/components/Hero/HomeHero/HomeHero.stories.tsx
Disables the home hero story due to the lack of RSC support in SB.
=> Patch home hero story

public/content/zero-knowledge-proofs/index.md
The old link was outdated, so I swapped it for the current wiki page:
[https://www.radicalxchange.org/wiki/plural-funding/](https://www.radicalxchange.org/wiki/plural-funding/)
=> docs: Update Plural Funding link

public/content/developers/docs/web2-vs-web3/index.md
Hello, team! I noticed a couple of Medium links were pointing to old URLs.
Updated them to the new ones so everything points correctly now.
**Links updated:**
* `https://medium.com/s/story/why-decentralization-matters-5e3f79f7638e` → `https://onezero.medium.com/why-decentralization-matters-5e3f79f7638e`
* `https://medium.com/@gavofyork/why-we-need-web-3-0-5da4f2bf95ab` → `https://gavofyork.medium.com/why-we-need-web-3-0-5da4f2bf95ab`
Thanks!
=> docs: fix outdated Medium links

public/content/developers/tutorials/eip-1271-smart-contract-signatures/index.md
updated to the correct URL so readers can access the message signature verification guide without issues.
=> docs: fix outdated Alchemy docs link

public/content/roadmap/fusaka/index.md, public/content/roadmap/fusaka/peerdas/index.md
- Adds missing h1 to peerdas page
- Refactors to using `<sup>` tags for numbers for rendering consistency
- Auto-formatter made a couple adjustments as well
=> patch: h1 and superscript

public/content/developers/tutorials/erc20-annotated-code/index.md
fixed a typo in the documentation where "complied" was used instead of "compiled".
also updated the outdated GeeksforGeeks link to the current one.
=> docs: fix typo and update outdated reference

public/content/community/get-involved/index.md
I updated the Web3Bridge link to the new official site and removed the MetaGame link since the project has been discontinued.
N/A
=> docs: fix broken and outdated links

public/content/what-are-apps/index.md
Adds missing header ids to /what-are-apps page
=> add headers ids for what-are-apps page

public/content/roadmap/fusaka/index.md, public/content/roadmap/fusaka/peerdas/index.md
very non-urgent. just adding a good tweet by vitalik as a resource on the peerdas page
none
=> add resource

public/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
a few outdated Alchemy links that were still pointing to `alchemyapi.io`.
updated them to the current `alchemy.com` domain so everything works smoothly:
* `https://auth.alchemyapi.io/signup` → `https://auth.alchemy.com/`
* `https://docs.alchemyapi.io/` → `https://www.alchemy.com/docs/`
* `http://dashboard.alchemyapi.io/` → `https://dashboard.alchemy.com/`
* `https://docs.alchemyapi.io/tutorials/hello-world-smart-contract` → `https://www.alchemy.com/docs/hello-world-smart-contract`
=> docs: update outdated Alchemy links

public/content/contributing/style-guide/content-standardization/index.md
Patch bold markdown syntax
https://ethereum.org/contributing/style-guide/content-standardization#smart-contract
=> patch: markdown syntax

public/content/developers/tutorials/guide-to-smart-contract-security-tools/index.md
found that the old draft link was no longer valid. updated it to the current page:
`https://csrc.nist.gov/publications/detail/sp/800-154/draft` to `https://csrc.nist.gov/pubs/sp/800/154/ipd`
=> docs: fix outdated NIST SP 800-154 link

public/content/developers/tutorials/learn-foundational-ethereum-topics-with-sql/index.md
several Dune references were outdated and pointing to old domains.
updated them so they resolve correctly:
* `dune.xyz/home` → `dune.com/`
* `duneanalytics.com/` → `dune.com/`
* `duneanalytics.com/paulapivat/Learn-Ethereum` → `dune.com/paulapivat/Learn-Ethereum`
* `duneanalytics.com/queries/44856/88292` → `dune.com/queries/44856/88292`
=> docs: fix broken Dune links

public/content/developers/tutorials/uniswap-v2-annotated-code/index.md
noticed the Uniswap whitepaper links were pointing to the old domain.
updated them to the current location:
* `uniswap.org/whitepaper.pdf` → `app.uniswap.org/whitepaper.pdf`
* `uniswap.org/whitepaper-v3.pdf` → `app.uniswap.org/whitepaper-v3.pdf`
=> docs: fix Uniswap whitepaper links

public/content/eips/index.md
noticed the Ethereum2077 Substack project no longer exists and all posts were deleted.
removed the outdated link to avoid pointing to a dead resource.
=> docs: removed dead Ethereum2077 blog link

README.md
Added a short note at the end of README.md for Ubuntu and Debian users who may need to install nodejs and npm before using yarn install
=> Update package manager instructions in README.md

public/content/refi/index.md
a couple of outdated URLs in the content and updated them to the correct ones:
* `https://www.klimadao.finance/blog/the-vision-of-a-carbon-currency` → `https://www.klimadao.finance/resources/the-vision-of-a-carbon-currency`
* `https://coinmarketcap.com/alexandria/glossary/regenerative-finance-refi` → `https://coinmarketcap.com/academy/glossary/regenerative-finance-refi`
the links now point to the right pages.
=> docs: fixed outdated links

public/content/roadmap/account-abstraction/index.md
spotted a couple of links that were leading to the wrong places, so I fixed them:
* `https://www.bundlebear.com/overview/all` → `https://www.bundlebear.com/erc4337-overview/all`
* `https://www.erc4337.io/` → `https://docs.erc4337.io/`
=> docs: updated some outdated links

.github/workflows/playwright.yml
Reorders steps for playwright E2E Testing workflow to install dependencies prior to Netlify involvement
https://github.com/ethereum/ethereum-org-website/actions/runs/18140948786/job/51631376977#step:3:44
=> fix: order of workflow actions—install deps before netlify step
