ethereum/ethereum-org-website

docs/build/index.md

Congrats on the re-launch, I love the philosophy behind it. 
This PR adds these security focused docs which have been actively maintained dating back to about 2 weeks after the TheDAO hack. :)

Add Best Practices Guide

---

docs/build/index.md

Update build/index.md: 2081 -> 2018

---

docs/use/index.md

Includes:
* Fixing Veil link to go to Veil's app instead of splash page

Update Veil link

---

docs/build/index.md

Added Kauri Fullstack DAPP Tutorial

Added Kauri Fullstack DAPP Tutorial to Build - Getting started section

---

docs/build/index.md

as opposed to linking just to the first article

changed link to the greater ETH 101 collection

---

docs/build/index.md

Spell check

---

docs/build/index.md

Adds a link in the build section to the "Deconstructing a Solidity Contract" series: https://blog.zeppelin.solutions/deconstructing-a-solidity-contract-part-i-introduction-832efd2d7737
This series uses Remix to help developers better understand how Solidity is compiled into bytecode, and how this bytecode is executed by the EVM. The goal of the series is to demystify EVM bytecode, and to make newcomers feel comfortable with it.

Add link to the Deconstructing a Solidity Contract article series.

---

README.md

ref: https://github.com/ethereum/ethereum-org-website/issues/63

Clarify dapp submission criteria

---

docs/build/index.md

Adds ethernaut.zeppelin.solutions to the list of developer training resources under Build.
> The Ethernaut is a Web3/Solidity based wargame inspired on overthewire.org, played in the Ethereum Virtual Machine. Each level is a smart contract that needs to be 'hacked'. The game is 100% open source and all levels are contributions made by other players.

Add ethernaut to dev training section

---

docs/build/index.md

broken link fixed

---

docs/learn/index.md

Add kauri.io in the "Learn" section

Add Kauri under "Learn about Ethereum"

---

docs/learn/index.md

added News to anchor text of link to weekinethereumnews.com

Added News to anchor text of link to weekinethereumnews.com

---

docs/developers/index.md

Part of fix for https://github.com/ethereum/ethereum-org-website/issues/73

Updated to remove "non-technical"

---

docs/developers/index.md

Crazyrabbit ltc patch 1

---

docs/developers/index.md

Add Pantheon to list of Ethereum Clients

Add Pantheon to list of Ethereum Clients

---

README.md

Update README.md to include information about team

---

docs/developers/index.md

Add link to the full list of Python tools

Add Python tooling link

---

docs/use/index.md

as @jjmstark  suggested now it's a stand-alone page for [Ethereum products only](https://defiprime.com/ethereum)

Ethereum DeFi Ecosystem

---

docs/use/index.md

Change to directly link to major wallets

---

docs/developers/index.md

As the title suggests, added Tenderly as a development tool.

Added Tenderly to the list of development tools

---

docs/learn/index.md

- Added video to the "Ethereum basics" section, which previously lacked any video content
- First noticed the video here: https://twitter.com/ameensol/status/1148453238754045952
- Added as the second bullet point (rather than at bottom of list) because it's valuable, especially for beginner content, to give the reader of a video option, rather than long articles. The fact that this is the only video in this section warranted including it higher-up.

Added "What is Ether and Ethereum?" video

---

docs/developers/index.md

Added our Universal Faucet to both Rinkeby and Gorli Faucet section.

added universal faucet

---

docs/developers/index.md

Full disclosure, I work at Nodesmith, but I think it's important to have some listed optionality when it comes to infrastructure providers.

added Nodesmith to the backend APIs section

---

docs/developers/index.md

Related to: https://github.com/ethereum/ethereum-org-website/pull/111

Add mythril to the list of Security tools

---

docs/developers/index.md

Add rimble

---

docs/developers/index.md

Updating Brownie PR #25 to new `dev` branch (cc: @nymd)

Adding python-based dev environment "Brownie"

---

docs/learn/index.md

Added a link to Andreas Antonopolous open source book section on "What is a Smart Contract" Slightly technical in nature, but will add a more beginner-friendly source in future. I'm currently working on adding some content over at EthHub to achieve this.

Add link to Smart Contract definition

---

docs/learn/index.md

That renders incorrectly as HTML

Fix miss-formatted markdown link

---

docs/learn/index.md

As mentioned previously, I've started beginners definition of Smart Contracts/DApps on EthHub. Planning to continue to build on it, but thought the link would belong here.

What is a smart contract - EthHub Link

---

docs/.vuepress/config.js
docs/.vuepress/theme/components/Footer.vue

The Matomo scripts were causing issues with Netlify's preview deploys. This change injects the scripts into the head element via config.js.
See https://github.com/vuejs/vuepress/issues/790

Matomo fix

---

docs/.vuepress/config.js

Twitter does not support relative paths, see [here](https://stackoverflow.com/questions/45915720/relative-image-paths-for-twitter-cards-in-blogdown)

Update meta images to full URL

---

docs/.vuepress/enhanceApp.js

https://github.com/ethereum/ethereum-org-website/issues/236
Locally

Add redirects for legacy pages [Fixes #236]

---

docs/.vuepress/config.js
docs/.vuepress/theme/components/DropdownLink.vue
docs/.vuepress/theme/utils/translations.js
docs/index.md
docs/ko/index.md
docs/ko/learn/index.md
docs/zh/beginners/index.md
docs/zh/developers/index.md
docs/zh/index.md
docs/zh/learn/index.md
docs/zh/use/index.md

Add Chinese (Simplified) translations at ethereum.org/zh/
https://github.com/ethereum/ethereum-org-website/issues/210

Add Chinese (Simplified) translations [Resolves #210]

---

docs/.vuepress/theme/components/Sidebar.vue
docs/developers/index.md

Reorganization of the Developers page on Ethereum.org
It should be further reviewed/discussed.

Reorganization of the developers page index.md

---

README.md

Updates the "principles" for the website in the README, following discussion & comment from the website team. Some changes directly in response to feedback in #77.
#77 
N/A
N/A

Updated "core principles" of the README.

---

.gitignore
docs/.vuepress/components/HomePage.vue
docs/.vuepress/config.js
docs/.vuepress/theme/components/DropdownLink.vue
docs/.vuepress/theme/components/Header.vue
docs/python/index.md

Updated internal links with trailing backslashes

---

docs/.vuepress/theme/styles/theme.styl

Hi! I fixed header overlap.
[#292](https://github.com/ethereum/ethereum-org-website/issues/292)

Fix header overlaps in-page anchors [Resolves #292]

---

docs/developers/index.md

Adding a link to B9lab Academy. We've been around from the very early days of the ecosystem and have been training people since 2015.

Add reference to B9lab Academy

---

docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/styles/dark.styl
docs/.vuepress/theme/styles/responsive.styl
docs/.vuepress/theme/styles/theme.styl

Remove button element from the announcement link for accessability
https://github.com/ethereum/ethereum-org-website/issues/184
No UI changes

Update <button> to <a> tag [Fixes #184]

---

docs/developers/index.md
docs/fr/developers/index.md
docs/ja/developers/index.md
docs/java/index.md
docs/javascript/index.md
docs/ko/developers/index.md
docs/python/index.md
docs/zh/developers/index.md

Dedicated page for ethereum.org/javascript - see more info in the related issue.
https://github.com/ethereum/ethereum-org-website/issues/224
Locally

WIP Javascript page

---

.github/labeler.yml
.github/workflows/label.yml

https://github.com/actions/labeler
https://github.com/ethereum/ethereum-org-website/issues/296

Add Github Action: Labeler

---

.github/workflows/label.yml

Disabling for now until this issue with Github labeler actions is resolved https://github.com/actions/labeler/issues/12
https://github.com/ethereum/ethereum-org-website/issues/344

Disable Labeler action for forks [Fixes #344]

---

docs/.vuepress/config.js
docs/.vuepress/public/robots.txt
package.json
yarn.lock

Add robots.txt & sitemap.xml to improve site crawlability
https://github.com/ethereum/ethereum-org-website/issues/347

Add robots.txt & sitemap.xml

---

docs/developers/index.md

- Adding Nethermind to Clients
- N/a

Add Nethermind to Clients

---

docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/NotFound.vue
docs/.vuepress/theme/components/Header.vue
docs/.vuepress/theme/utils/translations.js

Some tweaks to respect dark mode toggle & remove translations since this.$lang is always `en-US`

Clean up NotFound component

---

docs/java/index.md

Signed-off-by: Felipe Faraggi <felipefaraggi@gmail.com>
small updates to pantheon/besu renaming and removed unused gitter link.
also, booooo!
- [x ] I have read the contributing guidelines in the project README.
- [ x] My code follows the code style of this project.

updated besu references and outdated gitter

---

docs/developers/index.md

added studio.ethereum.org and the Azure Ethereum Developer Kit

---

docs/learn/index.md

Remove (newly) paywalled bloomberg article
N/A

Remove (newly) paywalled bloomberg article

---

docs/use/index.md

Updated title and last updated date of article.
N/A

Updated title and "last updated" date for "90+ Ethereum apps..."

---

docs/.vuepress/theme/utils/__mocks__/util.js

Fixes #387 
One util function `resolveHeaderTitle` introduced in #369 should be mocked in SidebarLink's unit test.
#387

Fixes #387: mock util to fix unit test failure

---

docs/developers/index.md

Updated the reference from Superblocks Lab to the new official Ethereum Studio IDE instead.

Updated reference from Superblocks Lab to Ethereum Studio

---

docs/learn/index.md

Fix broken link to Zubin Koticha article
N/A
N/A

Fix broken link to Zubin Koticha article

---

docs/.vuepress/components/BuildPage.vue

Minor copy change to reflect the copy of studio.ethereum.org

Update ERC-20 template to Coin Contract

---

README.md

Add [All Contributors](https://allcontributors.org/docs/en/overview) to the project.
#362

Add @all-contributors bot & update README [Fixes #362]

---

docs/rust/index.md

Added language-specific page for Rust following https://ethereum.org/python/ page as a template
Resolves #266

Add Rust Developer Docs

---

docs/.vuepress/theme/components/Hero.vue

Clear intervals when the Hero component is destroyed to prevent console errors when navigating to new pages.
#200

Clear hero intervals on destroy [Fixes #200]

---

docs/dot-net/index.md

Fresh pull request - @samajammin sorry for the earlier mistakes!
Fingers crossed this is good, if not, happy to do any additional changes as required.
Thanks again for your patience!

.NET materials addition and merged

---

docs/enterprise/index.md

Remove deprecated Gitter [Fixes #395]

---

docs/.vuepress/theme/components/SearchBox.vue
docs/.vuepress/theme/utils/util.js

Trim off explicit header IDs from search result titles
#546

Trim header IDs off search results [Fixes #546]

---

docs/.vuepress/config.js
docs/.vuepress/theme/utils/translations.js
docs/sl/beginners/index.md
docs/sl/developers/index.md
docs/sl/index.md
docs/sl/learn/index.md
docs/sl/use/index.md

Added Slovenian translation. All files changed with respect to the guidelines specified in PR #282 
Solves Issue #544 
None

Added Slovenian Translation [fixes #544]

---

docs/.vuepress/components/HomePage.vue
docs/sl/beginners/index.md
docs/sl/developers/index.md
docs/sl/learn/index.md
docs/sl/use/index.md

Fix Slovenian formatting & relative links

---

package.json
yarn.lock

Run build commands sequentially [Fixes #535]

---

docs/languages/index.md

Add blurb on community translations [Fixes #576]
#576

Add blurb on community translations [Fixes #576]

---

docs/enterprise/index.md

Add explicit heading IDs for enterprise translations
None

Add explicit heading IDs for enterprise translations

---

docs/developers/index.md
docs/enterprise/index.md
docs/fr/learn/index.md
docs/sk/developers/index.md

I changed the broken links with correct ones

Fix of multiple broken links

---

docs/cookie-policy/index.md
docs/dot-net/index.md
docs/golang/index.md
docs/java/index.md
docs/javascript/index.md
docs/languages/index.md
docs/privacy-policy/index.md
docs/python/index.md
docs/rust/index.md
docs/terms-of-use/index.md

Added Heading IDs to English pages in the docs directory.
Issue #592

Heading IDs added to pages. Fixes #592

---

docs/.vuepress/theme/components/DropdownLink.vue
docs/.vuepress/theme/components/NavLink.vue

Navbar closes on link selection 
Issue #545

Close nav dropdown on link select

---

docs/.vuepress/theme/utils/translations.js
docs/ig/learn/index.md

Fix Igbo markdown

---

docs/ig/beginners/index.md
docs/ig/developers/index.md
docs/ig/learn/index.md
docs/ig/use/index.md
docs/use/index.md

Fixed the formatting issues from #580
#542

Fix Igbo markup issues

---

docs/.vuepress/theme/components/NavLink.vue

Fixes console errors introduces in #596
#545

Prevent NavLink closeMenu errors

---

docs/developers/index.md

…es #547]
Adds Alchemy API to the list of Backend APIs. To address a few of the criteria listed in the docs for evaluating additions to this page:
**_Is it meaningfully differentiated from tools already listed?_**
Alchemy supports the core-Ethereum JSON RPC API but does so with a significantly different architecture - we also support some enhanced APIs, and have built a suite of developer tools to compliment the underlying infra.
**_Is the tool well documented? Does documentation exist? Is it sufficient to use the tool? Has it been recently updated?_**
Please see [our docs](https://docs.alchemyapi.io) - we update our docs regularly!
**_Is the tool widely used?_**
Yes - tons of top Ethereum projects use Alchemy as their infrastructure provider. You can see a few on our [customers …

Add Alchemy to the 'Backend APIs' section of the developers page

---

docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/components/Sidebar.vue

Reverts ethereum/ethereum-org-website#624

Revert "Add XL-friendly layout."

---

docs/ar/developers/index.md
docs/developers/index.md
docs/fa/developers/index.md

Update references to Hyperledger Besu.
#630

Updated Patheon references [Fixes #630]

---

LICENSE

Add MIT open source license to the project
https://opensource.guide
https://github.com/ethereum/ethereum-org-website/issues/226

Create LICENSE [Resolves #226]

---

docs/developers/index.md

Adding 3Box [Fixes #620]
Added 3Box, 3Box.js and our series of react plugins to developer tools. These are fully working and useful for the Ethereum community
NA
NA

Adding 3Box  - [Fixes #620]

---

docs/developers/index.md

Added the step by step tutorial  [Running an Ethereum Full Node on a RaspberryPi 4 (kauri.io )](https://kauri.io/article/9695fcca217f46feb355245275835fc0/)  to the *Ethereum Node Resources* section.
I received some traction on this article so I thought it would be a good addition for the site.
N/A
N/A

add kauri article 'Running an Ethereum Full Node on a RaspberryPi 4' to the *Ethereum Node Resources* section

---

docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/components/Sidebar.vue
docs/.vuepress/theme/styles/config.styl

Slight tweaks, focusing on XL screens as > 1440px
#207

Clean up XL layout [Fixes #207]

---

docs/enterprise/index.md

Added Tenderly to the list of Enterprise tooling. Position picked in alphabetical order.

Added Tenderly to the list of enterprise tools

---

docs/wallets/index.md

Creates a new "Wallets" page, by separating out the "Wallets" content on the existing "Use" page. This is a quick and simple draft, which we intend to iterate on.

Rough draft of separate "Wallets" page

---

docs/eth/index.md

Creates a new "What is ETH?"  page, by separating out the "ETH" content on the existing "Use" page. This is a quick and simple draft, which we intend to iterate on.

Rough draft of separate "What is ETH?" page

---

docs/cookie-policy/index.md
docs/privacy-policy/index.md

Remove page timestamps [Fixes #650]

---

docs/.vuepress/components/HomePage.vue
docs/.vuepress/theme/components/Header.vue
docs/.vuepress/theme/components/NavLinks.vue
docs/ar/developers/index.md
docs/cs/developers/index.md
docs/de/developers/index.md
docs/developers/index.md
docs/el/developers/index.md
docs/es/developers/index.md
docs/fa/developers/index.md
docs/fr/developers/index.md
docs/ig/developers/index.md
docs/it/developers/index.md
docs/ja/developers/index.md
docs/ko/developers/index.md
docs/learn/index.md
docs/nl/developers/index.md
docs/pl/developers/index.md
docs/pt-br/developers/index.md
docs/ru/developers/index.md
docs/sk/developers/index.md
docs/sl/developers/index.md
docs/zh/developers/index.md

Add backslash to internal links [Fixes #648]

---

docs/.vuepress/components/AssetItem.vue
docs/.vuepress/components/BuildPage.vue
docs/.vuepress/components/DefaultList.vue
docs/.vuepress/components/LanguagesPage.vue
docs/.vuepress/theme/components/Footer.vue
docs/.vuepress/theme/components/Header.vue

Add ESP link to footer [Resolves #670]

---

docs/languages/index.md

Updating the Slack invite link, which expires every 30 days 😕 
#673

Update Slack link [Fixes #673]

---

docs/zh/developers/index.md

Fix misspelling:  
The tools is called "Securify". Misspell to "Secutiry "

Fix misspelling

---

docs/pt-br/what-is-ethereum/index.md

corrigindo erros de ortografia na tradução pt-BR na idex.md

erros de ortografia

---

README.md

First swing at updating the README to reflect the new site content structure
#515

Update README content guidelines [Fixes #515]

---

docs/pt-br/use/index.md

Corrigindo erros gramaticais no arquivo doc/pt-br/user/index.md

Corrigindo erros gramaticais

---

docs/java/index.md

Added a link to the web3j cheat sheet which contains a list of constantly growing useful java code snippets to achieve common ethereum tasks.
N/A

Added web3j cheat sheet link

---

docs/developers/index.md

A pull request to add Status to the Developer Resources page(https://ethereum.org/developers/#other-tools)
Status is a multi-purpose communication tool that combines a peer-to-peer messenger, decentralized crypto-wallet, and Web3 browser using the Ethereum tech stacks.
The Dapp Integration Center is a step by step guide to optimize dapps for use in Status. This includes mobile first best practice, security and privacy requirements, leveraging the Status API, and how to submit to [dap.ps](https://dap.ps/).
A PR applying the feedback from https://github.com/ethereum/ethereum-org-website/pull/594

add Status to the Developer Resources page

---

docs/developers/index.md

Re-making the PR for this reference: https://github.com/ethereum/ethereum-org-website/pull/168

add Ethercluster

---

docs/developers/index.md

Added [Best Practices for Smart Contract Development](https://yos.io/2019/11/10/smart-contract-development-best-practices/) to the ['Best Practices, Patterns, and Anti-Patterns'](https://ethereum.org/developers/#best-practices-patterns-and-anti-patterns) section of Developer Resources.
N/A
N/A

Add 'Best Practices for Smart Contract Development' article to Best Practices section

---

docs/enterprise/index.md

Hyperledeger ~~Foundation~~
Pegasys -> PegaSys
Wrong twitter link
formatting issue
Just some small errors that were caught on a recent scan.

Update enterprise landing age with some uncaught errors

---

design-principles.md

Add markdown file of ethereum.org's proposed design principles.
#667

Add design principles [Fixes #667]

---

docs/.vuepress/config.js
docs/community/index.md
docs/strings.json

Add Community page [Resolves #269]

---

docs/.vuepress/components/HomePage.vue
docs/.vuepress/config.js
docs/community/index.md
docs/strings.json
package.json

Deploy v0.3.1

---

docs/community/index.md
package.json

- Minor updates to Community page

Deploy v0.3.2

---

docs/community/index.md
package.json

Deploy v0.3.3

---

docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/components/Sidebar.vue

Small styling fixes to the sidebar
#710 
#711 
See issues

Sidebar fixes

---

.all-contributorsrc
README.md
docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/components/Sidebar.vue
docs/community/index.md
package.json

Deploy v0.3.4

---

docs/.vuepress/config.js

Making the page search engine friendly with structured data

SEO with structured data

---

docs/community/index.md

Fixed links at community page

---

docs/community/index.md

Update index.md with ETHTurin Hackathon

---

docs/community/index.md

Added the a Jeju meetup group in the community page

Add Jeju Meetup

---

docs/community/index.md

Added a local event

---

docs/community/index.md

Smart contract workshop on #defi. 
We've had regular monthly events on Ethereum dev since 2018

Add community event

---

docs/community/index.md

Add Meetups mentioned in community call

Add Meetups mentioned in community call

---

docs/community/index.md

Just added the a Barcelona meetup group in the community page

Added Barcelona meetup group

---

.all-contributorsrc
README.md
docs/community/index.md
package.json

- Add meetup groups to Community page

Deploy v0.3.6

---

docs/what-is-ethereum/index.md

linked video has been taken down by creator
ben horowitz video has no longer online, embed broken

remove broken video embed

---

.all-contributorsrc
README.md
docs/community/index.md
docs/what-is-ethereum/index.md
package.json

- Add more meetups to Community page
- Remove broken video

Deploy v0.3.7

---

netlify.toml

Add  `X-Frame-Options` & `X-XSS-Protection` HTTP response headers to prevent malicious attacks.
N/A

Add response headers

---

docs/community/index.md

Add ETHLagos to upcoming events

---

docs/community/index.md
docs/what-is-ethereum/index.md
netlify.toml
package.json

- Add ETHLagos
- Add HTTP response headers

Deploy v0.3.9

---

docs/community/index.md

ETHDenver has happened, and now needs to be removed from the list

Remove ETHDenver

---

docs/community/index.md

ETHParis 2020 has been cancelled https://twitter.com/ETHParis/status/1229820364324208642?s=20

Remove ETHParis

---

docs/ar/what-is-ethereum/index.md
docs/cs/what-is-ethereum/index.md
docs/de/what-is-ethereum/index.md
docs/el/what-is-ethereum/index.md
docs/es/what-is-ethereum/index.md
docs/fa/what-is-ethereum/index.md
docs/fr/what-is-ethereum/index.md
docs/id/what-is-ethereum/index.md
docs/ig/what-is-ethereum/index.md
docs/it/what-is-ethereum/index.md
docs/ja/what-is-ethereum/index.md
docs/ko/what-is-ethereum/index.md
docs/nl/what-is-ethereum/index.md
docs/pl/what-is-ethereum/index.md
docs/pt-br/what-is-ethereum/index.md
docs/ru/what-is-ethereum/index.md
docs/se/what-is-ethereum/index.md
docs/sk/what-is-ethereum/index.md
docs/sl/what-is-ethereum/index.md
docs/zh/what-is-ethereum/index.md

Remove broken YouTube links
#781

Remove broken YouTube links [Fixes #781]

---

docs/languages/index.md

This link will never expire! Slack finally launched the ability to share the link without expiration 🎉 - thanks @sorumfactory 
#673

Fix Translation Program Slack link [Fixes #673]

---

docs/developers/index.md

Swap Developer Tools & IDEs sections
#789

Swap Developer Tools & IDEs sections [Fixes #789]

---

docs/community/index.md

Remove ETHLondonUK & EthCC

---

docs/community/index.md

Add ESP's wishlist as a way to get involved
#802

Add ESP's wishlist as a way to get involved [Fixes #802]

---

docs/community/index.md

Adding San Diego meetup.

---

docs/.vuepress/theme/Layout.vue

This `home` class is no longer used
N/A

Remove unused classes

---

docs/.vuepress/components/HomePage.vue
docs/.vuepress/theme/styles/theme.styl

Fix homepage content logic for translations - a few bugs introduced in #801
#763

Fix homepage content logic for translations

---

docs/.vuepress/theme/Layout.vue

Remove smooth scroll behavior
#795

Remove smooth scroll behavior [Fixes #795]

---

docs/community/index.md

Update community events [Fixes #828]

---

docs/.vuepress/theme/components/Navigation.vue

Fix handleNavToggle console errors
#837

Fix handleNavToggle [Fixes #837]

---

docs/.vuepress/theme/components/NavLink.vue

Remove native modifier on `NavLink` `a` tag
#835

Remove native modifier [Fixes #835]

---

docs/.vuepress/config.js
docs/.vuepress/theme/utils/markdown.js
docs/dot-net/index.md
docs/translations/id/dot-net/index.md
docs/translations/se/dot-net/index.md
docs/translations/sk/dot-net/index.md

Updates `renderHeaderWithExplicitAnchor` to play nice with `markdown-it-attrs`. This simplifies the logic as `markdown-it-attrs` already strips out the bracket text from the final output.
#585

Fix header ids

---

docs/.vuepress/components/CardList.vue
docs/style-guide/cards/index.md
docs/style-guide/index.md

Added card documentation
This documents how to leverage cards, and card lists

Add card documentation

---

docs/developers/index.md

Add article on Protocol Development Governance
None

Add article on Protocol Development Governance

---

docs/dapps/index.md

Update consensys link to new URL

Update consensys link

---

docs/.vuepress/components/RandomAppList.vue

- Remove Cryptokitties for now, as it's a relatively old app
- Add Gods Unchained
- Add Decentraland
- Add Dharma
- Add Augur

Update /dapps in response to individuals content audit

---

docs/eth/index.md

Changes in response to feedback from individuals content audit:
- Remove cryptokitties link
- Reorder links, so that the mycrypto guide (which is very long & intimidating compared to the ethhub link) is at bottom
- Add ethhub link about buying ETH
- Added CTAs for user to check out the wallets & dapps pages
Note: these are quick fixes for current version, majority of the audit feedback will be reflected in a new version of this page that will replace the current content

Various copy changes

---

docs/wallets/index.md

Various changes in response to individuals content audit:
- Remove ledger blog post, as hardware wallets are already covered by other links here
- Remove Opera, since it is not strictly a wallet but a browser with wallet functionality. May be re-added in future when page is expanded to include a larger suite of options.
- Added Argent, Coinbase wallet, and Gnosis safe

Wallets page copy changes

---

docs/learn/index.md

Various changes in response to individuals content audit:
- Add whitepaper
- Update Year in Ethereum to most recent version
- Remove "Ethereum Basics" section since this really belongs on the beginner page, and creates confusion about what this page is about

Learn page copy changes

---

docs/community/index.md

- Added links to popular crypto job boards
- Recommendation from individuals content audit

Add job page links to Community page

---

docs/what-is-ethereum/index.md

Various changes in response to feedback from Individuals content audit:
- Expand list of community members examples to include more "regular" or "non technical" examples
- Replace "trustworthy" with "reliable and predictable"
- Add links to list of application category examples
- removed videos, which are outdated and too long for an intro page

"What is Ethereum" page copy changes

---

docs/.vuepress/components/BuildPage.vue
docs/.vuepress/config.js
docs/.vuepress/theme/components/Hero.vue
package.json
yarn.lock

Add ability to upload ethereum.org to IPFS
#300

Support IPFS

---

docs/developers/index.md

Tutorial was updated to use the latest libraries
The code in the tutorial was updated to use the latest version of libraries (Truffle and Web3JS).

Updated last updated date

---

docs/developers/index.md

Add link to the Solidity blog at solidity.ethereum.org
None

Add Solidity blog

---

README.md
docs/.vuepress/components/TranslationsAvailable.vue
docs/.vuepress/components/TranslationsInProgress.vue
docs/languages/index.md

Explain translation version management for volunteers of our Translation Program. Encourage folks to translate the latest version of the website.
#921

Explain translation version management [Fixes #921]

---

docs/community/index.md

Place link to Ethereum Hackers Discord and link to HackMoney hackathon

Link & Event Updates

---

docs/community/index.md

This PR adds an invite link to the CryptoDevs community discord to the community page.

Add CryptoDevs Discord invite to Community page

---

docs/translations/tr/build/index.md
docs/translations/tr/dot-net/index.md
docs/translations/tr/enterprise/index.md
docs/translations/tr/index.md
docs/translations/tr/learn/index.md

Fix Turkish translations

---

docs/.vuepress/theme/components/Footer.vue
docs/strings.json

Translate Footer component & conditionally display links depending on translation content version
#865

Translate Footer component [Fixes #865]

---

docs/translations/de/dot-net/index.md
docs/translations/de/what-is-ethereum/index.md
docs/translations/fr/dot-net/index.md
docs/translations/id/what-is-ethereum/index.md
docs/translations/tr/what-is-ethereum/index.md
netlify.toml

Fix translation links & redirects
Nonte

Fix translation links & redirects

---

docs/learn/index.md

Follow up on #912 to remove old resources & re-organize so new additions are added at the bottom
None

Update ETH 2.0 resources

---

docs/dapps/index.md
docs/translations/cs/use/index.md
docs/translations/de/use/index.md
docs/translations/el/use/index.md
docs/translations/es/use/index.md
docs/translations/fa/use/index.md
docs/translations/fr/use/index.md
docs/translations/id/use/index.md
docs/translations/ig/use/index.md
docs/translations/it/use/index.md
docs/translations/ja/use/index.md
docs/translations/ko/use/index.md
docs/translations/nl/use/index.md
docs/translations/pl/use/index.md
docs/translations/pt-br/use/index.md
docs/translations/ru/use/index.md
docs/translations/se/dapps/index.md
docs/translations/sk/dapps/index.md
docs/translations/sl/use/index.md
docs/translations/zh/use/index.md

Add a brief "What is a dapp?" intro on the /dapps page explaining what dapps are & how they're different.
#853
Adds citation to OpenZeppelin's doc where most of the content is from. See relevant discussion here: https://github.com/OpenZeppelin/docs.openzeppelin.com/issues/155#issuecomment-597881924

Add dapp explanation

---

docs/.vuepress/config.js
netlify.toml
package.json
yarn.lock

Updates for issues surfaced from Google Search Console
- Add canonical HTML tags
- Update schema
- Add /search redirect
None

Add canonical HTML tags

---

docs/dapps/index.md
docs/eth/index.md
docs/what-is-ethereum/index.md

Minor updates to internal link anchor text, primarily for SEO.
None

Update internal link anchor text

---

docs/terms-of-use/index.md

Update terms of use to reflect MIT & CC licenses.
None

Update terms of use

---

docs/.vuepress/theme/components/Footer.vue
docs/developers/index.md
docs/eips/index.md

Add intro to EIPS page [Fixes #831]

---

docs/community/index.md

Add Solidity Summit to events
None

Add Solidity Summit

---

docs/.vuepress/theme/components/AlgoliaSearchBox.vue

Update site search styles
#804

Site search styles

---

docs/developers/index.md

Vyper update from Jan 8 2020 and update links

Vyper update from Jan 8 2020

---

docs/developers/index.md

Fix date on 2018 article that is not updated often

Remove 2018 article that is not updated often

---

docs/enterprise/index.md

Added Baseline, Provide, and a new section for enterprise apps live on mainnet.

Add content to ethereum.org/enterprise [Fixes #971]

---

docs/.vuepress/components/ListCard.vue
docs/.vuepress/theme/styles/theme.styl
docs/.vuepress/theme/utils/inline-md.js
docs/community/index.md

This updates the meetup list:
- now using the list component with flags
- in alphabetical order by country
- listed in an object rather than markdown
This also resolves two previously unknown issues:
- mixed elements (e.g. image, text) in list columns would not be displayed inline. They now are.
- twemoji previously was using a `v1.0` collection of SVG assets, which doesn't include flags. This has been updated to `latest`

Update meetups, update twemoji to latest, add parsing to lists

---

docs/golang/index.md

A little more developer centric benefits and an example for #985

A little more developer centric benefits

---

docs/enterprise/index.md

update old links to new links and add new links to quorum documentation and articles
- added a new link for Official Quorum Documentation under For more in depth information
- added a new link to Projects Building on J.P. Morgan’s Quorum Blockchain For more in depth information
- added Quorum GitHub link under Protocol and Infrastructure
- updated quorum permissioning link under Enterprise Features
- Added Quorum Security Framework under security
- Updated Quorum Tessera link under Privacy
https://github.com/ethereum/ethereum-org-website/issues/1008
None

Quorum updates - update old links and add new links

---

docs/.vuepress/theme/components/Footer.vue
docs/.vuepress/theme/components/__tests__/__snapshots__/Footer.spec.js.snap
docs/community/index.md
docs/foundation/index.md

Update ESP links to new domain
None

Update ESP links to new domain

---

docs/.vuepress/theme/NotFound.vue

Add base tag for 404 pages
#1024

Add base tag for 404 pages

---

docs/whitepaper/index.md

Update reference URLs to links 
#1042

Update reference URLs to links [Fixes #1042]

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Add release drafter GH action
#336

Add release drafter GH action

---

.github/workflows/release-drafter.yml

Fix workflow [Fixes #336]

---

docs/.vuepress/theme/styles/theme.styl
docs/whitepaper/index.md

Limit img width styles to whitepaper
#1048

Limit img width styles to whitepaper [Fixes #1048]

---

docs/community/index.md

- Add Madrid meetups
- Add ETH events
None

Community updates

---

docs/.vuepress/components/DefaultList.vue
docs/.vuepress/components/RandomList.vue

Test this solution to #1040 
https://github.com/ethereum/ethereum-org-website/pull/1050#issuecomment-635236164
#1050

Add sync to DefaultList

---

docs/developers/index.md

This PR adds a mention to [Create Eth App](https://github.com/PaulRBerg/create-eth-app) under "Other Tools" in the Developer page.

Add "Create Eth App" to the Developer page

---

docs/translations/fr/build/index.md
docs/translations/no/build/index.md
docs/translations/zh-tw/build/index.md
docs/translations/zh-tw/developers/index.md
docs/translations/zh-tw/dot-net/index.md
docs/translations/zh-tw/enterprise/index.md
docs/translations/zh-tw/golang/index.md
docs/translations/zh-tw/java/index.md
docs/translations/zh-tw/javascript/index.md
docs/translations/zh-tw/learn/index.md
docs/translations/zh-tw/python/index.md
docs/translations/zh-tw/rust/index.md

Fix frontmatter values - they weren't intended to be translated.
#1060 #1061 #1062

Fix frontmatter values

---

docs/community/index.md

Added a line [here](https://github.com/Solexplorer/ethereum-org-website/blob/0ded42eb173da179594cc1cfa4dc02e8cd332dfc/docs/community/index.md#upcoming-events-upcoming-events) to have the Gitcoin hackathon show up in the community website
#1071

Add Gitcoin hackathon - GitxChange [Fixes #1071]

---

.github/workflows/docsearch-crawl.yml
.github/workflows/docsearchConfig.json
docs/.vuepress/config.js
docs/.vuepress/theme/components/AlgoliaSearchBox.vue

Add docsearch workflow

---

docs/enterprise/index.md

Enterprise supply chain addition

---

docs/about/index.md
docs/assets/index.md
docs/delphi/index.md
docs/dot-net/index.md
docs/eips/index.md
docs/enterprise/index.md
docs/foundation/index.md
docs/whitepaper/index.md

Generate missing heading IDs
#592

Generate missing heading IDs [Fixes #592]

---

.github/labeler.yml
.github/workflows/labeler.yml

Due to GH action limitations on forks (https://github.com/actions/labeler/issues/12), we can't run this action on PRs.
This is a test to run a cron job every hour. Once working, let's update to daily (e.g. `0 2 * * *`).
#296

Add labeler action [#296]

---

.github/workflows/stale.yml

Add stale action [#296]

---

design-principles.md

Changed to "We're a stepping stone for anyone looking for answers" to avoid the grammatical error.
#1102

Corrected typo in design principles [Fixes #1102]

---

docs/developers/index.md

@samajammin Here's the related PR
Adds torus as a developer tool and links to github + documentation

Add torus as a developer tool

---

docs/.vuepress/components/TranslationsAvailable.vue

Sort languages by English name (vs. ISO code).
#1121

Sort available languages [Fixes #1121]

---

docs/community/index.md

Added SFBW hackathon that is upcoming
Is issue needed? It's just a 1-line change.

Add sfbw hackathon from gitcoin

---

docs/community/index.md

Removed events from event list whose active dates (as listed here) have passed

Removed events whose active dates have passed

---

src/components/Search/index.js

Closes & clears search when result is clicked.
#1143
https://share.getcloudapp.com/YEupPvgk

Strip URL on search [Fixes #1143]

---

src/pages/build.js
src/pages/index.js

Adds eager loading to hero images to improve load speed ([gatsby-image defaults to lazy](https://www.gatsbyjs.org/packages/gatsby-image/#gatsby-image-props)).
@sorumfactory received feedback that hero image is taking some time to load.
> some ppl told me that the main image isn't loading or taking quite a while to have full image.

Add eager loading to hero images

---

src/content/community/index.md

add DAOSquare in DAOs list
add DAOSquare in DAOs list
NA

Add DAOSquare in DAOs list

---

src/content/community/index.md

Added a hackathon and changed end date of another one

Changed date for protect privacy and added open web incubator

---

src/components/MeetupList.js

- Added Tegucigalpa, Honduras Meetup to the Meetup List

added Tegucigalpa to Meetup List

---

src/content/developers/index.md

Add ethplorer to block explorers
Fixes merge conflicts of #1128

Add ethplorer to block explorers

---

README.md

Update README for Gatsby
#1157

Update README for Gatsby [Fixes #1157]

---

.github/workflows/docsearch-crawl.yml
.github/workflows/docsearchConfig.json
src/components/Search/index.js

Update to use our production index.
#1153

Update to prod search index

---

.github/workflows/docsearch-crawl.yml
.github/workflows/docsearchConfig.json
README.md
package.json
src/components/Search/index.js
src/content/developers/index.md

***
- Update to prod search index (#1174) @samajammin
- Exclude empty search queries from analytics [Fixes #1153] (#1173) @samajammin
- Update README for Gatsby [Fixes #1157] (#1172) @samajammin
- Deploy v2.0.3 (#1170) @samajammin
***
***

Deploy v2.0.4

---

.github/workflows/docsearchConfig.json

Revert description selector
#1176

Revert description selector [Fixes #1176]

---

src/content/whitepaper/index.md

Fix typo (it's -> its)

---

src/components/Morpher.js
src/pages/index.js

Add "Ethereum" text Morpher to homepage
#1151
See deploy previews (check multiple translated content versions)

Add Morpher [Fixes #1151]

---

package.json
src/pages/what-is-ethereum.js

***
- docs: add dschlabach as a contributor (#1189) @allcontributors
- Fix typo (it's -> its) (#1186) @dschlabach
- Add Morpher [Fixes #1151] (#1179) @samajammin
***
Thank you @dschlabach and @samajammin for the contributions! :trophy:
***

Deploy v2.0.7

---

src/pages/what-is-ethereum.js

Add page metadata for What is Ethereum
#1183

Add page metadata for What is Ethereum

---

src/components/Callout.js
src/pages/what-is-ethereum.js

Fix mobile image cutoff on Callout component
#1183
Before:
After:

Fix callout cutoff

---

package.json
src/components/Callout.js
src/pages/what-is-ethereum.js

***
- Fix callout cutoff (#1194) @samajammin
- Add page metadata for What is Ethereum (#1192) @samajammin
***
***

Deploy v2.0.8

---

src/components/ActionCard.js
src/components/Callout.js
src/pages/what-is-ethereum.js

Image alt text on the new page wasn't as accessible as it could be. Have given each image a more detailed description.
none

Added more accessible image alt text

---

package.json
src/components/Theme.js
yarn.lock

1st step towards cleaning up our color variables & applying uniform colors across the app.
None

Add color variables from design system

---

src/content/developers/index.md

- adding soliditydeveloper.com blog

Add soliditydeveloper.com blog

---

src/content/golang/index.md

This article covers many topics that others do, but in a more condensed and updated form.
It should act as a quick reference that can be used in hackathon, etc. to look up usage of the backend.
Link: https://medium.com/coinmonks/web3-go-part-1-31c68c68e20e

Added article about usage of geth as a library

---

src/utils/moment.js

add: RFC2822 Date on moment 

---

src/utils/moment.js

import locales on moment.js #1231

---

README.md
src/content/contributing/adding-products/index.md
src/content/contributing/index.md
src/templates/static.js

Add listing policy [Fixes #743]

---

package.json
src/components/Footer.js
src/templates/static.js
src/utils/luxon.js
src/utils/moment.js
yarn.lock

Proposal
as i added another lib of momentum intl i was wondering how long it takes to load and how bad it is, i saw a new lib that moment's own support team.
is Luxon has a [total of 20.4kb](https://bundlephobia.com/result?p=luxon@1.24.1)
and it's great for those who will enter the site by cell phone, and how it flows much better with gatsby

change: moment.js to luxon

---

src/components/Footer.js
src/templates/static.js
src/utils/luxon.js
src/utils/time.js

Update getLocaleTimestamp display format
Builds off #1237

Update getLocaleTimestamp display format

---

src/components/Link.js
src/components/SharedStyledComponents.js
src/templates/static.js

Prevent external link arrow from being wrapped around.
Fixes #980.

Prevent external link arrow from being wrapped around

---

src/content/developers/index.md
src/content/translations/cs/developers/index.md
src/content/translations/tr/developers/index.md

Fix Geth typo
Issue mentioned in Discord: https://discordapp.com/channels/714888181740339261/727898649006309377/731483307170201640

Fix Geth typo

---

src/components/ActionCard.js
src/components/Button.js
src/components/CardList.js
src/components/Footer.js
src/components/MeetupList.js
src/components/Nav/Dropdown.js
src/components/Nav/Mobile.js
src/components/Nav/index.js
src/components/Roadmap.js
src/components/Search/index.js
src/components/Sidebar.js
src/components/Theme.js
src/pages/build.js
src/pages/languages.js

Underline in-content links
#1187

Update link styles [Fixes #1187]

---

src/content/contributing/adding-products/index.md

Added terms of use to products policy and made some content tweaks.

Products policy update

---

package.json
src/components/Contributors.js
src/content/about/index.md
src/content/community/index.md
src/content/contributing/index.md

***
- Fix internal links
- Sort contributors alphabetically
***
***

Deploy v2.3.1

---

src/components/EthExchanges.js
src/pages/build.js

Update Dharma for USA only
None, user report on Discord:
> Hmmm look like dharma is wyre but only US for some reason

Fix dharma

---

src/content/developers/index.md

Add Trinity client
Issue mentioned in Discord: https://discordapp.com/channels/714888181740339261/727898649006309377/731483307170201640

Add Trinity client

---

src/components/EthExchanges.js

Add event to country select.
None

Track country input

---

package.json
src/components/EthExchanges.js

***
- Track country input (#1276) @samajammin
***
***

Deploy v2.3.6

---

src/components/EthExchanges.js

Sort the country list alphabetically
#1278

Sort country list [Fixes #1278]

---

src/components/Contributors.js

feat: Randomise contributor list 

---

src/components/Contributors.js

Randomize list [Fixes #1269]

---

src/components/Roadmap.js

chore: add logic for filter close issues on planned

---

src/content/wallets/index.md

Added imToken to wallets list.
Fixes #1275

Added imtoken to wallets list [Fixes #1275]

---

src/components/RandomAppList.js

Added ENS to list of dapps.
Fixes #1271

Added ENS to dapp list [Fixes #1271]

---

src/content/contributing/adding-articles/index.md
src/content/contributing/adding-developer-tools/index.md
src/content/contributing/adding-products/index.md
src/content/contributing/design-principles/index.md

Added meta descriptions to "adding products" "adding developer tools" "adding articles" and "design principles"
Fixes #1290

Added meta descriptions to contributing pages [Fixes #1290]

---

src/components/RandomAppList.js
src/intl/en.json

Clean up #1285 to use translations.
#1271

Update ENS listing [Fixes #1271]

---

src/utils/time.js

Update timestamp parsing
#1309

Update timestamp parsing [Fixes #1309]

---

.github/PULL_REQUEST_TEMPLATE.md
package.json

***
- Update ENS listing [Fixes #1271] (#1316) @samajammin
- Update timestamp parsing [Fixes #1309] (#1318) @samajammin
***
***

Deploy v2.3.9

---

netlify.toml

Add language redirects [Fixes #1297]

---

.github/labeler.yml
.github/workflows/label.yml

Add labeler action [Fixes #1327]

---

src/content/community/index.md

Update upcoming events

---

src/content/translations/fi/dapps/index.md
src/content/translations/fi/developers/index.md
src/content/translations/fi/dot-net/index.md
src/content/translations/fi/enterprise/index.md
src/content/translations/fi/eth/index.md
src/content/translations/fi/golang/index.md
src/content/translations/fi/java/index.md
src/content/translations/fi/javascript/index.md
src/content/translations/fi/learn/index.md
src/content/translations/fi/python/index.md
src/content/translations/fi/rust/index.md
src/content/translations/fi/wallets/index.md
src/content/translations/fi/what-is-ethereum/index.md

Fix frontmatter issues from #1336
#1332

Fix frontmatter of fi translations

---

src/components/Eth2Clients.js
src/content/eth2/get-involved/index.md
src/content/eth2/index.md
src/content/translations/it/enterprise/index.md
src/content/translations/it/java/index.md
src/templates/static.js

Randomize order of Eth2 client list.
#878

Randomize clients

---

.github/ISSUE_TEMPLATE/new_exchange.md
src/content/contributing/adding-exchanges/index.md
src/content/contributing/adding-products/index.md
src/content/contributing/index.md
src/pages/get-eth.js

A series of small changes to help streamline the process for getting the information we need to successfully list exchanges with confidence.
#1346

Exchange listing changes

---

.github/ISSUE_TEMPLATE/suggest_exchange.md
.github/ISSUE_TEMPLATE/suggest_wallet.md
src/components/WalletCompare.js
src/pages-conditional/wallets/find-wallet.js
src/pages-conditional/wallets/index.js
src/pages/get-eth.js

Meta cleanup

---

.github/ISSUE_TEMPLATE/suggest_exchange.md
.github/ISSUE_TEMPLATE/suggest_wallet.md
package.json
src/components/WalletCompare.js
src/pages-conditional/wallets/find-wallet.js
src/pages-conditional/wallets/index.js
src/pages/get-eth.js

***
- Meta cleanup (#1355) @samajammin
***
***

Deploy v2.6.1

---

src/components/Eth2Articles.js
src/content/eth2/index.md

- Removed latest status tags following feedback
- Updated latest articles from Ben and Danny 
- Fixed bug that was displaying Ben and Danny's articles in the wrong lists.

Eth2 page updates

---

src/pages-conditional/what-is-ethereum.js

Fixes issue #1381
Adding a single new word, 'from', to improve readability.

Minor grammatical issue. Adding word 'from'

---

src/components/Breadcrumbs.js
src/components/Tag.js
src/components/WalletCompare.js
src/pages-conditional/wallets/find-wallet.js

Always show wallet filter tags
#1205

Always show wallet filter tags

---

src/components/TranslationsLeaderboard.js
src/content/contributing/index.md
src/content/contributing/translation-program/acknowledgements/index.md
src/content/contributing/translation-program/index.md
src/content/contributing/translation-program/leaderboard/index.md
src/templates/static.js

New structural changes to the contributing section that add new content explaining and celebrating the ethereum.org translations program.
#1368

Create content for translations program

---

src/components/Breadcrumbs.js

wrapped breadcrumbs for mobile

---

src/content/translations/ml/python/index.md

Fix typo in brownie repo

---

src/content/eth2/get-involved/medalla-data-challenge/index.md

Converted How to submit section to h2 tag so it appears in toc

---

src/pages/get-eth.js

Typo Fix: Update get-eth.js

---

src/content/community/index.md

Remove past events

---

src/content/eth2/get-involved/medalla-data-challenge/index.md

Added contest form

---

src/content/eth2/get-involved/medalla-data-challenge/index.md

Added discord support channel name

---

src/content/eth2/get-involved/index.md
src/content/eth2/get-involved/medalla-data-challenge/index.md

- Added page that explains the Medalla data challenge
- Added link to Medalla data challenge from `/get-involved` page
Still to-do:
n/a

Medalla data challenge

---

src/components/Eth2Articles.js

Added latest Danny Ryan and Ben Edginton articles to community articles section of Eth2.

Added latest Ben and Danny articles

---

src/pages-conditional/assets.js

Removed the gif artwork while we figure out open-source licence.

Assets page update

---

src/content/eth2/get-involved/medalla-data-challenge/index.md

Updated support email to an alias

---

src/data/wallets.csv

Added status wallet to wallet finder component
#1425

Added status wallet [fixes #1425]

---

src/pages-conditional/assets.js

Removed EF logo and removed copy while awaiting images Ts&Cs

Updated assets page

---

src/content/developers/docs/evm/index.md
src/content/developers/docs/intro-to-ethereum/index.md

Fixes merge conflict in #1436 (I don't have permission to push to that PR)
#1395

edn-mvp EVM article

---

src/content/developers/docs/security/index.md

First draft of security page

---

netlify.toml

Add redirects for the pages we moved.
#1470

Add programming language redirects [Fixes #1470]

---

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md

Adding line break, caught by Marc:
> 1 wei should be the start of another line
None

Update "A developer's guide to Ethereum, part 1"

---

src/content/developers/docs/standards/tokens/erc-20/index.md

Minor fixes in text and links.
@samajammin can we land the links in `Related Topics` like I did before they exist, just to keep a pattern?
I'm planing to deliver all of them during this week.

[ERC-20] Minor fixes.

---

src/pages-conditional/developers/index.js

Couldn't resist the opportunty to fix a typo in the sentence telling readers to fix typos ;)

Fix typo: s/opportunties/opportunities/

---

src/components/SideNav.js
src/pages-conditional/developers/index.js

Remove duplicate framework links
#1476

Remove duplicate framework links [Fixes #1476]

---

src/components/CalloutBanner.js
src/pages-conditional/developers/index.js

Fix Callout displays on mobile
#1487

Fix Callout displays on mobile [Fixes #1487]

---

src/components/SharedStyledComponents.js
src/components/SideNav.js
src/components/SideNavMobile.js
src/components/TableOfContents.js
src/content/developers/docs/nodes-and-clients/index.md
src/content/developers/docs/programming-languages/javascript/index.md

- Fix typos
- Fix dropdown icon alignment when open
None

Misc edn fixes

---

src/content/developers/docs/index.md
src/content/developers/docs/programming-languages/javascript/index.md
src/content/developers/docs/smart-contracts/anatomy/index.md
src/content/developers/docs/smart-contracts/index.md
src/content/developers/docs/smart-contracts/languages/index.md
src/content/developers/docs/web2-vs-web3/index.md
src/templates/docs.js
src/templates/tutorial.js

- Fix docs & tutorials header overlap
- Fix typo [Fixes #1491]
- Minor doc content updates
#1491

Edn content updates

---

src/components/EthPriceCard.js
src/pages-conditional/wallets/index.js

Fix issue created in #1486
#1486

Fix EthPriceCard error state

---

src/components/SideNavMobile.js

Make the expandable mobile nav scrollable.
#1468

Fix SideNavMobile scroll [Fixes #1468]

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

fixed spelling of transaction

---

src/content/eth2/get-involved/medalla-data-challenge/index.md

Edited medalla data challenge flyer text
* Added tooling for building public datasets addendum 
* and clarified award amounts

Added tooling for building public datasets addendum and clarified award amounts

---

src/content/developers/docs/standards/tokens/erc-20/index.md
src/content/developers/docs/standards/tokens/erc-721/index.md

Adding the documentation for `ERC-721`.
@samajammin let me know if the section title `Popular NFTs` is ok for your suggestion.

[ERC-721] Non-Fungible Token Standard Documentation

---

.github/ISSUE_TEMPLATE/suggest_wallet.md

Added mention of audit to wallet issue template.

Added audit question to issue template

---

src/content/eth2/index.md

ETH withdrawal from phase 1 to phase 1.5
none

ETH withdrawal from phase 1 to phase 1.5

---

src/components/Theme.js
src/components/TutorialMetadata.js
src/components/TutorialTags.js
src/pages-conditional/developers/tutorials.js

**WIP** Add colored tutorial tags
None

Add colored tutorial tags

---

src/components/Nav/index.js

#1263  bugfix ESLINT error
adding the button rol
adding onKeyDown
adding outline ( otherwise there is border if you click) fix can maybe done global css 
none

#1263 fix navigation ESlint error

---

src/intl/en.json
src/pages-conditional/developers/index.js

Replace "EDN" branding

---

.github/ISSUE_TEMPLATE/suggest_wallet.md
src/content/contributing/adding-products/index.md

Add additional listing criteria for products & wallets.
None

Add global access & non-custodial criteria to products

---

src/content/developers/docs/smart-contracts/libraries/index.md
src/data/developer-docs-links.yaml

Smart contracts libraries page

---

src/content/developers/docs/dapps/index.md
src/content/developers/docs/ethereum-stack/index.md
src/content/developers/docs/intro-to-ethereum/index.md
src/content/developers/docs/smart-contracts/deploying/index.md
src/content/developers/docs/smart-contracts/index.md
src/content/developers/docs/transactions/index.md

**WIP, do not merge**
Misc content updates within Developer Docs
#1441

WIP add misc /docs/ content updates

---

src/content/developers/docs/nodes-and-clients/index.md

Added paragraphs about each implementation after talking to client implementer teams. I think this should be part of the page, feel free to edit.
#969

Added info about each client

---

src/components/SharedStyledComponents.js
src/content/developers/docs/nodes-and-clients/index.md
src/templates/docs.js
src/templates/static.js
src/templates/tutorial.js

Fix template styles for `h4` elements
- Only display anchor link on hover
- Avoid nav overlap when navigating to anchor
None

Template h4s

---

src/components/Eth2Articles.js

Updated eth2 with latest articles from Danny and Ben.

Updated eth2 with latest articles

---

src/content/contributing/adding-developer-tools/index.md

Added open source as a criteria in our listing policy for dev tools. We ideally want to prioritise open source software.
#1552

Added mention of open source to dev tool policy [Fixes #1552]

---

src/data/wallets.csv

Monolith introduce the ability to buy crypto with card in-app.
Can't add it to /get-eth page as we don't have information on what geographical restrictions apply. Awaiting email response from monolith
#1432

Added monolith to "buy crypto with card" feature

---

src/content/developers/docs/programming-languages/dot-net/index.md

Fix broken link on tech-mint website.

Update index.md to fix broken link

---

src/content/developers/docs/smart-contracts/testing/index.md

OpenZeppelin Test Environment Links
OpenZeppelin Test Helpers (Assertion Library) Links
Tutorial on how to migrate from Truffle Tests to OpenZeppelin Test Environment

Add OpenZeppelin Test Environment + Test Helpers + Tutorial

---

src/content/developers/docs/ethereum-stack/index.md

Fix Typos in interact
Change from "permissionaly intract" to "permissively interact"

Fix Typos in interact

---

src/content/translations/zh-tw/developers/index.md
src/utils/translations.js

I edited the word choice of the zh-tw developers page.

Fix zh-tw translation

---

src/content/developers/docs/smart-contracts/languages/index.md

- Adding Yul and Yul+ to smart contract languages
- Adding material and descriptions for Yul and Yul+
- Adjusting intro text accordingly
Example smart contract in Yul is missing, I'll reach out to the team and add it later.

Adding Yul and Yul+ to smart contract languages

---

src/content/developers/docs/apis/backend/index.md

Add Rivet to Backend APIs
#1419

Add Rivet [Fixes #1419]

---

src/pages-conditional/what-is-ethereum.js

Update /build/ link [Fixes #1585]

---

netlify.toml

Remove fallback redirects
#1609

Remove fallback redirects [Fixes #1609]

---

.all-contributorsrc
README.md
netlify.toml
package.json
src/content/whitepaper/index.md
src/pages-conditional/what-is-ethereum.js

***
- fixed typo? (#1608) @mustafawm
- Remove fallback redirects [Fixes #1609] (#1610) @samajammin
- Remove fallback redirects [Fixes #1609] (#1610) @samajammin
***
Thank you @mustafawm and @samajammin for the contributions! :trophy:
***

Deploy 2.7.9

---

src/content/developers/docs/development-networks/index.md
src/content/developers/docs/intro-to-ethereum/index.md
src/content/developers/docs/networks/index.md
src/content/developers/docs/nodes-and-clients/index.md
src/data/developer-docs-links.yaml

Add "development networks" documentation page
#1582

Add "development networks" documentation page

---

src/content/developers/docs/accounts/index.md

Just a couple quick typo fixes

Small Typos on Accounts

---

src/content/community/index.md

I just added all the gitcoin events, the ongoing ones and also the upcoming ones related to the ethereum ecosystem

Add gitcoin hackathon events

---

src/pages-conditional/developers/learning-tools.js

This content was outdated, leftover from the previous /build page:
None

Update /learning-tools metadata

---

src/pages-conditional/developers/local-environment.js

Add Waffle to "Set up local environment" section.
Mentions Buidler and scaffold-eth as a way to use Waffle.

Add Waffle to list of local envs

---

src/content/developers/docs/evm/index.md

Adds a missing comma to the EVM doc.

Add missing comma

---

src/content/developers/docs/standards/tokens/index.md

Fix broken link to 'Understand the ERC20 token smart contract'

---

src/pages-conditional/developers/local-environment.js

Update Epirus description fixing target platform
Javascript Virtual Machine should be Java Virtual Machine.

Fix Epirus description

---

src/components/Icon.js
src/components/Nav/Mobile.js
src/components/Tag.js

Minor cleanup of #1674 to stick with one primary icon set: [Material Design](https://react-icons.github.io/react-icons/icons?name=md).
#1651

Update Icons to Material Design

---

src/content/about/index.md
src/content/developers/docs/ethereum-stack/index.md
src/content/developers/docs/evm/index.md
src/content/developers/docs/index.md
src/content/developers/docs/smart-contracts/deploying/index.md
src/content/developers/docs/smart-contracts/index.md
src/content/developers/docs/smart-contracts/testing/index.md
src/content/developers/docs/standards/tokens/erc-721/index.md
src/content/developers/tutorials/run-node-raspberry-pi/index.md
src/content/eth2/get-involved/index.md
src/content/eth2/index.md
src/pages-conditional/assets.js
src/pages-conditional/developers/local-environment.js
src/pages-conditional/wallets/find-wallet.js
src/pages/get-eth.js

Add trailing slashes & removes capitalization of links to ensure they don't result in 301 redirects (which triggers a page refresh - bad UX).
None

Fix internal 301 redirects

---

src/content/developers/tutorials/testing-smart-contract-with-waffle/index.md

Add new tutorial for Waffle about using matchers.

Add new Waffle tutorial

---

README.md

It's not clear that there is a link to the Discord in our repo readme. This PR aims to make our Discord server more discoverable from our readme. 
cc @wackerow

Added more links to Discord from readme

---

src/data/wallets.csv

Dharma, like most wallets in this current "gas climate" no longer subsidise gas fees. So this PR removes this claim from their description.
#1729

removed "no gas fees" from description of dharma

---

gatsby-node.js
src/components/Layout.js
src/data/addresses.js
src/pages/eth2/deposit-contract.js

Builds of work from #1554 to create /eth2/deposit-contract/ page
#1553

Eth2 Deposit Contract Page

---

package.json
src/pages/eth2/deposit-contract.js

- Add EthHub deposit contract link
- Tweak checkbox alignment
#1553

Add EthHub deposit contract link

---

netlify.toml

Add 301 redirect for old URL
#878

Add beacon chain page redirect

---

src/components/Layout.js

- Ensure parent element is `relative`
- Change element name (to change classname, to bust browser caches)
#1768

Fix Eth2 banner display [Fixes #1768]

---

src/content/developers/docs/smart-contracts/index.md
src/pages/eth2/index.js

Simple correction of two instances of `Etheruem`

Type correction [Fixes #1790]

---

package.json
src/components/SideNav.js

Add SideNav padding-bottom
#1797

Sidenav padding

---

src/content/developers/docs/apis/backend/index.md

1. update Alchemy description
2. add link to Alchemy discord
Change **Alchemy -** **_Ethereum API and developer tools._**
Updated **Alchemy -** **_Ethereum Development Platform._**
Add - [Discord](https://discord.gg/kwqVnrA)

Update Alchemy Description and add community discord for support/questions

---

src/content/developers/docs/frameworks/index.md

- [alchemyapi.io](https://alchemyapi.io/)
- [GitHub](https://github.com/alchemyplatform)
- [Discord](https://discord.gg/kwqVnrA)

Add Alchemy

---

README.md

Add Netlify status badge

---

netlify.toml
src/content/developers/docs/consensus-mechanisms/index.md
src/content/developers/docs/consensus-mechanisms/pow/index.md

- Fix mechanism typo
- Add mining redirect
None

Mechanism typo

---

src/content/enterprise/index.md

Addressing comment from @tasdienes 
None

Add link to private Ethereum page

---

src/content/community/index.md

removed past events and a dead projects

---

src/components/Eth2Articles.js

Correct the spelling of my name 😀

Spelling correction

---

src/content/developers/docs/gas/index.md

added link with an in-depth explainer on ethereum gas

Further reading about gas 

---

src/components/Nav/Dropdown.js
src/components/Nav/index.js
src/intl/en.json

Prevent nav item text wrapping. See movie:
https://share.getcloudapp.com/z8uYKO7r
#1813

Prevent nav item text wrapping [Fixes #1813]

---

gatsby-node.js
src/content/eth2/beacon-chain/index.md
src/content/eth2/docking/index.md
src/content/eth2/shard-chains/index.md
src/templates/eth2.js

Refactor field to array for greater flexibility
None

Create flexible summaryPoints frontmatter field

---

src/components/Eth2TableOfContents.js
src/pages/eth2/vision.js
src/templates/eth2.js

Fix InfoColumn mobile styles
#1722

Fix InfoColumn mobile styles [Fixes #1772]

---

src/components/DismissibleCard.js
src/templates/eth2.js

- Refactor AnnouncementCard to DismissibleCard
- Stores key in local storage to track dismiss history
#1837

Add DismissibleCard [Fixes #1837]

---

src/components/TutorialMetadata.js
src/templates/tutorial.js

Update tutorial template styles
Fixes #1842

Update tutorial template styles [Fixes #1842]

---

src/components/DocLink.js
src/content/developers/docs/consensus-mechanisms/pow/index.md
src/content/developers/docs/layer-2-scaling/index.md
src/content/enterprise/index.md
src/content/glossary/index.md

- Used Tas' work on layer 2 to update `/docs/layer-2-scaling`
- Added links to relevant teams/products for each layer 2 solution
- Added relevant glossary entries
_NOTE:_ We may want to split out this layer-2-scaling section into separate pages soon. Especially if more content gets added.
#774 – I think we can probably close that one out. It's largely covered and I can't see anyone finding it at the bottom of page 2 of our Issues. We have pretty good coverage of Optimistic and Zero knowledge, and we could maybe create issues that are more targeted, e.g. "We need help with state channels content" or "We need help with Plasma content".

Updates to layer 2 across site

---

src/components/Trilemma.js
src/pages/eth2/vision.js

Add Trilemma component to /eth2/vision page (for screens > `theme.breakpoints.m`)
None

Display Trilemma except on mobile

---

src/content/developers/docs/nodes-and-clients/index.md

Add link to Eth2 clients
None, just noticed there's no mention of Eth2 on this page.

Add link to Eth2 clients

---

src/content/community/index.md

We're a well established DAO with a growing community of web3 builders and collaborators. Looking forward to help!
https://dorg.tech
added link to dOrg DAO
#1722

Adding dOrg DAO to the list of DAOs

---

src/content/eth2/get-involved/medalla-data-challenge/index.md

Re-add Medalla data challenge
None

Re-add Medalla data challenge

---

.github/ISSUE_TEMPLATE/suggest_wallet.md

Please provide details of your last audit -> Please describe the measures taken to ensure the wallet's security and provide documentation wherever possible

Update suggest_wallet.md with new security language

---

src/components/FileContributors.js

Fix de-duping of contributors
#1878

Fix de-duping of contributors [Fixes #1878]

---

src/content/contributing/adding-products/index.md

Audited - > security-tested, with some examples. *Please* change language as you see fit!

Updated language around security/audit on product listing policy

---

src/components/WalletCard.js
src/components/WalletCompare.js

Finally learning how rad & simple CSS grid is 🎉 
#1883

Refactor card sections to css grid [Fixes #1883]

---

src/content/eth2/get-involved/medalla-data-challenge/index.md

Add link to Medalla data challenge results
None

Add link to Medalla data challenge results

---

gatsby-browser.js
gatsby-ssr.js
src/components/Layout.js

Refactor Layout from class to function component
Hoping this may address layout issues in #1866 & #1867

Refactor Layout to function component

---

src/content/developers/docs/consensus-mechanisms/index.md
src/content/developers/docs/development-networks/index.md
src/content/developers/docs/networks/index.md
src/content/developers/docs/smart-contracts/languages/index.md
src/content/developers/docs/transactions/index.md
src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
src/content/developers/tutorials/how-to-use-slither-to-find-smart-contract-bugs/index.md
src/content/developers/tutorials/secure-development-workflow/index.md
src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
src/content/developers/tutorials/testing-smart-contract-with-waffle/index.md
src/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
src/content/enterprise/private-ethereum/index.md
src/content/eth2/get-involved/medalla-data-challenge/index.md

Previously I had gone through content md files adding header tags that had been missed, but did not go through dev docs or tutorials at that time. This updates all the headers I found in (english) dev docs and tutorials to have unique header tags, fixing the console warnings and broken ToC links this was causing.
Note: Also found a typo in the numbering on the "sending transactions with web3/alchemy" tutorial and fixed this.

More header tag fixes

---

src/content/developers/docs/consensus-mechanisms/pow/mining/index.md

typo in index.md

---

src/content/developers/docs/apis/backend/index.md

Add reference to the .NET API library for Ethereum

Add Ethereum API library for .NET

---

src/content/developers/docs/layer-2-scaling/index.md
src/content/enterprise/index.md
src/content/enterprise/private-ethereum/index.md
src/content/translations/de/developers/index.md

Decapitalised mainnet and fixed "transation" typo
https://github.com/ethereum/ethereum-org-website/issues/1882

Decapitalised mainnet and fixed "transation" typo

---

src/pages-conditional/dapps.js
src/pages/eth2/staking.js

Gaming copy was using the collectibles copy in error. This fix adds an intro to decentralized gaming.
Also, made the options inactive/active states clearer.

Adds gaming definition

---

README.md

Add Twitter button to README
None

Add Twitter button

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

Added Blockchair's Ethereum explorer.
Added Blockchair to the list of block explorers.

Add Blockchair’s Ethereum explorer to list of explorers

---

src/pages-conditional/dapps.js

Removed duplicate trailing slash on Oasis link

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

Added Blockchair to the list of block explorers + description

Add Blockchair to list of block explorers + description

---

src/content/eth2/get-involved/staking-community-grants/index.md

Added a word on staking community grants flyer page

Fixed grammar on staking community grants flyer page

---

src/components/FileContributors.js

Add check for GH API return objects
#1972

Add check for user object [Fixes #1972]

---

package.json
src/components/Eth2BeaconChainActions.js

Add images to Eth2BeaconChainActions
#1982

Add useStaticQuery in Eth2BeaconChainActions [Fixes #1982]

---

src/content/developers/docs/consensus-mechanisms/pos/index.md

There was an extra bullet point for no reason which was not needed. I removed it.

removed dangling bullet point

---

src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md

Add a new Hello World tutorial for Waffle.

Add a new Waffle tutorial

---

src/components/Eth2Articles.js

Added Danny's latest Eth2article

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

fixed typo in received

---

src/components/BugBountyCards.js
src/pages/eth2/get-involved/bug-bounty.js

This PR updates the google form on the Eth2 bug bounty site to the Eth2-specific google form. It's currently pointing to the general, Eth1 bug bounty submission form.

Fix Eth2 bug bounty submission form

---

src/components/TableOfContents.js
src/intl/en.json

Add translation support to TOC component
#2006

Translate TOC component [Fixes #2006]

---

src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
src/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md

All tutorial tags should be added as lowercase to prevent duplicates in the tag list.

Made all tutorial tags lowercase

---

src/content/community/index.md

Removes two events that took place last month.

Removes community events that have passed as of 12/1

---

src/pages/studio.js

My additions aren't the prettiest, feel free to spiff it up a bit 😄 
None

Update Studio page copy

---

src/content/developers/docs/oracles/index.md

Improved the oracles page:
- What are they
- Why are they needed
- The architecture of oracles/oracle networks
- Example contract and oracles-as-a-service
Feedback and extra content welcome!
Should oracles live under stack/data and analytics ?
#1881

Added oracle content [#1881]

---

.github/CODEOWNERS

Add bounty code owners to review changes to the Eth2 bounty data file
None

Add bounty code owners

---

src/content/community/index.md

Update cat herders link to new Discord server
cc @poojaranjan
None

Update cat herders link

---

.github/CODEOWNERS

Add Josh to CODEOWNERS

---

.github/ISSUE_TEMPLATE/suggest_dev_tool.md
src/content/contributing/adding-developer-tools/index.md

Added dev tool issue template
#2055

Added dev tool issue template [#2055]

---

src/intl/en.json
src/pages-conditional/developers/local-environment.js

Adds solidity template repo to local environment
#2054

Adds solidity template repo to local environment [#2054]

---

src/content/developers/docs/smart-contracts/anatomy/index.md

Made example data variables clearer

Made example data variables clearer

---

README.md

Makes it clearer that this is repo for ethereum.org and provides a link to the different clients if users want to inspect the blockchain code.
#2059

Updated readme [#2059]

---

src/data/translations.json

Changes Finnish label to `Suomi`
#2079

Updates Suomalainen to Suomi

---

src/pages/languages.js

Updated styling on styled component LangItem. [Fixes #2076]
- Implemented styling change suggested by @ryancreatescopy to revamp old styled component on Language page.

added new styled component for language page per request. [Fixes #2076]

---

package.json
src/components/Footer.js
src/components/Nav/index.js
src/content/community/index.md
src/content/developers/docs/security/index.md
src/content/eth2/get-involved/medalla-data-challenge/index.md
src/content/history/index.md
src/content/translations/cs/use/index.md
src/content/translations/fa/use/index.md
src/content/translations/ig/use/index.md
src/content/translations/nl/use/index.md
src/content/translations/pl/use/index.md
src/content/whitepaper/index.md
src/intl/en.json
src/templates/static.js
yarn.lock

Creating a first iteration of the history/forks timelines page. 
#923

Ethereum history/forks page

---

src/components/SharedStyledComponents.js
src/content/history/index.md
src/templates/static.js

Finished forks page and made some style changes to headers as it was very hard to scan long pages.
#2078 
#923

Finished forks history [#2078,  #923]

---

src/intl/en/page-dapps.json

Fixes small grammatical error in `page-dapps-get-started-subtitle` string
(none filed)

Small grammar correction

---

src/components/TranslationBanner.js
src/intl/en/common.json
src/pages/index.js

Adds translation banner component for our upcoming translations improvements.
Example banner is present on the homepage on the local build.

Adds translation banner

---

src/content/developers/tutorials/deploying-your-first-smart-contract/index.md

I fixed a grammatically incorrect sentence for the 'deploy first contract' tutorial.

Edited an grammatically incorrect sentence for the 'deploy first contract' tutorial

---

src/content/developers/docs/gas/index.md

Adding Blocknative's Gas Platform

---

src/pages/assets.js

Fix broken string
Reported in Discord:

Fix broken translation ID

---

README.md

Remove URL redirections in README.md.

docs: Remove URL redirections

---

src/pages-conditional/dapps.js

Translate the IDs vs. merely displaying them
#2210

Translate dapp descriptions [Fixes #2210]

---

README.md

update Bob Jiang's website
Only update Bob Jiang website from c4at.cn to bobjiang.com

update Bob Jiang's website

---

src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md

Fixed typos in `waffle hello world with buidler tutorial`

Fix typos in tutorial

---

src/content/eth2/shard-chains/index.md

Fix ethresear.ch link

---

src/content/eth2/get-involved/staking-community-grants/index.md

Removed submission form and added banner that the wave is over

Removed submission form and added banner that the wave is over

---

src/intl/en/page-developers-local-environment.json

Fix minor typo
https://discord.com/channels/714888181740339261/727898649006309377/797055073225408523

Fix scaffold-eth typo

---

src/content/developers/docs/dapps/index.md

This PR fixes a typo in the docs. The description of being able to express any action very closely resembles the concept of Turing completeness. Turing compatibility is nothing I, or Google, have heard of before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethereum/ethereum-org-website/2239)

Intro to dapps docs: Fix Turing completeness

---

.env.example
gatsby-config.js
netlify.toml

Tune configs for Github API

---

src/content/developers/docs/spin-up-your-node/index.md

This page is general intro to running own Ethereum node. I believe it still needs proofreading and maybe some edits, happy to change, remove, add something, let me know if I can help somehow

Adding page Spin up your own node

---

src/components/Codeblock.js

Added the possibility to write simple code as plain text  inside Codeblock component
For example:
https://github.com/ethereum/ethereum-org-website/issues/2158

Refactoring Codeblock component [Issue#2158]

---

src/data/eth2-bounty-hunters.csv

Add Quan (cryptosubtlety) to leaderboard

---

src/components/FileContributors.js
src/components/Modal.js
src/pages/developers/tutorials.js

Adds overflow-y scroll and max-heights to modal body
Fixes #2224

Modal overflow issue [Fixes #2224]

---

src/content/developers/docs/smart-contracts/anatomy/index.md

The layout of the code for ExampleDapp was all over the place. This PR fixes the indentation and aligns the style of the comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ethereum/ethereum-org-website/2243)

Fix layout of ExampleDapp

---

src/content/developers/docs/consensus-mechanisms/pow/index.md
src/content/developers/docs/consensus-mechanisms/pow/mining/index.md

Adds a link to staking from the mining page and explains that staking will eventually replace it. 
Fixes #2274

Adds staking banner on mining [fixes #2274]

---

src/components/Roadmap.js
src/pages/languages.js

updates roadmap cards and language cards
- consistent styling
- ensures consistent height of cards in same row
fixes #2195

Roadmap card fix [fixes #2195]

---

src/intl/en/common.json

Removed the mention of "expert knowledge" to try and reduce the barriers to contribution.
fixes #2205

Updated docs banner copy [Fixes #2205]

---

src/content/community/index.md

Adds MarketMake event and removes outdated events.
Fixes #2208

Adds MarketMake and removes old events [Fixes #2208]

---

src/data/eth2-bounty-hunters.csv

Increase Quan's bounty hunting score

---

src/components/DismissibleCard.js
src/components/Eth2TableOfContents.js
src/templates/eth2.js

This PR also reintroduces table of contents and breadccrumbs to smaller devices
Fixes #2231

Fixes broken scrolling [#2231]

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md
src/content/developers/docs/programming-languages/java/index.md
src/content/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
src/content/developers/tutorials/logging-events-smart-contracts/index.md
src/content/developers/tutorials/run-node-raspberry-pi/index.md
src/content/glossary/index.md
src/intl/en/page-dapps.json
src/intl/en/page-eth2-index.json
src/intl/en/page-eth2-vision.json

Translators highlighted some typos in our content. This PR addresses them prior to re-uploading files to crowdin.

Content bug fixes (for translations)

---

src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md

Here is the tutorial I wrote about creating and deploying a DeFi app. It is a proposal to be published in the Tutorials section.
In this tutorial we will build a DeFi Application with solidity where users can deposit an ERC20 token to the smart contract and it will mint and transfer Farm Tokens to them. The users can later withdraw their ERC20 tokens by burning their Farm Token on smart contract and the ERC20 tokens will be transferred back to them.

Tutorial proposal called "Create and deploy a DeFi App"

---

src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md

Defi tutorial fixes

---

src/components/EthExchanges.js
src/data/wallets.csv
src/pages-conditional/wallets/index.js

Adds mycrypto to get-eth list and removes ambo
Fixes #2269

MyCrypto and Ambo fixes [fixes #2269]

---

src/content/community/index.md

Added EtherPunk hackathon to the list. 
**Relevant links** -
https://etherpunk.devfolio.co/
https://twitter.com/ETHIndiaco

hackathon: Add EtherPunk hackathon.

---

src/content/developers/tutorials/run-node-raspberry-pi/index.md

1 quick translation fix

---

src/content/developers/docs/apis/backend/index.md

Update a paragraph that didn't make much sense 🧐 
None

Fix grammatical error

---

src/styles/layout.css

Removes hsla value

---

src/content/developers/docs/web2-vs-web3/index.md

"These examples are illustrative to show the main differences between web2 and web3 services."
to
"These examples are illustrative of the main differences between web2 and web3 services."

Minor content change

---

src/content/developers/docs/accounts/index.md

Fix typo in index.md

---

src/content/eth2/beacon-chain/index.md

Upgade --> upgrade [Fixes #2354]

---

src/content/developers/docs/programming-languages/python/index.md

Adding python and brownie tutorial
https://github.com/ethereum/ethereum-org-website/issues/2257

Added a simple brownie tutorial

---

.github/CODEOWNERS

Pending action in https://github.com/ethereum/devops/issues/619

Add JustinDrake as Eth2 bounty CODEOWNER

---

src/content/developers/docs/frameworks/index.md

Update index.md -- scaffold-eth components

---

src/intl/en/page-developers-local-environment.json

Update page-developers-local-environment.json -- update scaffold-eth components

---

src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md

Added more info + resources based off user feedback

---

src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md

Make guide more agnostic

---

src/content/developers/docs/layer-2-scaling/index.md

Cartesi has recently unveiled upgrading Descartes to Optimistic Rollups, the article and spec can be found here: https://medium.com/cartesi/scalable-smart-contracts-on-ethereum-built-with-mainstream-software-stacks-8ad6f8f17997
Addition

Add Cartesi to Optimistic Rollups

---

src/data/SimpleDomainRegistry.sol
src/data/SimpleToken.sol
src/data/SimpleWallet.sol
src/pages/index.js

Modified solidity version from `^0.7.0` to `^0.8.1` on homepage.
#2357

Modify solidity version to ^0.8.1 [Fixes #2357]

---

src/content/developers/docs/ethereum-stack/index.md

Changed:
`As a dapp developer, you don't need to know much about the EVM other than it exists and that reliably powers all applications on Ethereum without downtime.`
To:
`As a dapp developer, you don't need to know much about the EVM other than it exists and that it reliably powers all applications on Ethereum without downtime.`

Update index.md - added the word "it" to fix the typo.

---

CONTRIBUTING.md

Adds CONTRIBUTING.md file to root directyly. This causes GitHub to prompt new users when they visit the PR page. 
Linking to README initially to prevent split/contradicting information over time.

Adds CONTRIBUTING.md file to root directly

---

src/pages/get-eth.js

Link was the DEX v1, which is deprecated.
Updated to Loopring zkRollup DEX v2

Update Loopring link

---

src/content/developers/docs/frameworks/index.md

Replaced Epirus reference with Web3j reference and updated relevant links

Replaced epirus with web3j

---

src/components/Layout.js

Removes todo

---

src/components/WalletCompare.js
src/content/contributing/design-principles/index.md
src/content/contributing/translation-program/index.md
src/pages/developers/tutorials.js
src/pages/index.js
src/pages/languages.js

Explicitly set language path for Contributing page links as they only exist in English
#2359

Update contributing links to English paths

---

src/content/developers/docs/layer-2-scaling/index.md
src/content/enterprise/index.md

Add [Kchannels](https://www.kchannels.io/) to list of state channel projects

Add Kchannels to list of state channel projects

---

src/content/developers/docs/web2-vs-web3/index.md

Correction of typos
applicacations to applications

Correction of typos

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

- Adds **GetBlock** to nodes-as-a-service documentation page
#2373

Adds GetBlock to nodes-as-a-service list [Fixes #2373]

---

src/components/Nav/Mobile.js
src/components/Nav/index.js
src/components/TitleCardList.js
src/intl/en/common.json

Fixed a few accessibility issues showing up on the browser devtools
Footer.js has `socialLinks` array with four links using icons and lacking alt text. I tried passing in `alt` text to these links, as well as directly to the icon, but wasn't able to get it to work, so that's the only one left.
ethereum.org:
this PR localhost:
...btw @samajammin @ryancreatescopy , SEO and Best Practices rank 100%

Accessibility improvements

---

src/content/community/index.md

Added mention about miners in the community section.

Add miners to the Ethereum Community section

---

src/content/developers/docs/data-and-analytics/index.md
src/content/glossary/index.md
src/data/developer-docs-links.yaml

Content doc for "Data and Analytics" developer section. 
Updated content topics and details surrounding "Data and Analytics".
https://github.com/ethereum/ethereum-org-website/issues/1564

Content doc for "Data and Analytics" developer section.

---

src/content/community/index.md

fixes broken link for MGD DAO and adds HausDAO. Couple minor copy edits

---

src/content/developers/docs/oracles/index.md

1. Added architecture information of a simple oracle using logs to request data
2. Added Chainlink VRF for random number generation example
3. Added API calls for getting any data
Added an explainer article with more information on oracles
Addresses https://github.com/ethereum/ethereum-org-website/issues/2499

updated oracle information

---

src/content/developers/docs/dapps/index.md

small grammar fix 

---

src/content/developers/docs/accounts/index.md

Small quality of life improvement here as I'm reading through these.

backlink to ECDSA

---

src/content/developers/docs/smart-contracts/index.md

most newcomers won't know who nick is so it might be right to send the traffic back his way.

add Nick's site

---

src/content/developers/docs/intro-to-ethereum/index.md
src/content/developers/docs/storage/index.md

Added information on Arweave, Filecoin, Skynet, 0Chain, and Storg
Added components talking about contract-based data retention, decentrally and more information on current solutions. 
addresses https://github.com/ethereum/ethereum-org-website/issues/2520

added more dStorage information

---

package.json
src/components/Contributors.js
src/components/RandomAppList.js
src/components/WalletCompare.js
src/data/contributors.json
src/pages-conditional/wallets/index.js
src/pages/developers/local-environment.js
yarn.lock

Replaced all the shuffling algorithms with _.shuffle (lodash shuffle)
Fixes #2407

Used lodash for shuffling arrays [Fixes #2407]

---

src/content/about/web-developer/index.md
src/content/contributing/index.md
src/content/defi/index.md
src/content/developers/docs/ides/index.md
src/content/developers/docs/programming-languages/java/index.md
src/content/developers/docs/smart-contracts/deploying/index.md
src/content/developers/docs/smart-contracts/index.md
src/content/developers/docs/storage/index.md
src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
src/content/nft/index.md

- More custom header IDs missing from recent changes

Adds missing custom headers

---

src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md

Replaces expired link to Alchemy Discord with a link that does not expire
Thanks @YussufElarif for surfacing!

Update Alchemy Discord link [Fixes #2485]

---

src/content/nft/index.md

removed content that should have been commented out

NFT content fix

---

src/pages/index.js

Orders the dev section properly, which also fixes the margin issue:
#2566

Fix dev section mobile display [Fixes #2566]

---

src/components/Eth2Articles.js

Fixes a broken component caused by #2497
#2595

Fix Eth2Articles [Fixes #2595]

---

src/content/developers/docs/programming-languages/index.md

Typo in Programming Languages section

---

src/components/Layout.js
src/intl/en/common.json

- Retires banner directly linking to deposit contract from any Eth2 page.
#2569

Removes Eth2 staking banner [Closes #2569]

---

src/content/community/index.md

- adds Gitcoin grants funding round
- Removes passed events

Adds Gitcoin grants funding round to community events

---

src/content/developers/docs/layer-2-scaling/index.md

Prior description was based on zkrollups. (Some of the deleted parts can be moved into the zkrollups section in another PR.) 
Sidechains will be mentioned later.

Improve general description of rollups

---

src/content/nft/index.md

"Non-fungible tokens (NFT)" contained some typos
Fixed typos

fix: typos on "Non-fungible tokens (NFT)" page

---

src/content/developers/tutorials/erc20-annotated-code/index.md

1. Added publication date
2. Added a few words on associative arrays in case people need them.
3. Changed the description of calldata
4. Explained why if you transfer tokens and then `revert` nothing happens.
5. Changed "Alice things" to "Alice thinks"
6. Changed "Note: every" to "Note: Every"

Fixed some typos, added a tiny bit of content

---

src/templates/use-cases.js

Scales down and trims margins for use-cases hero images on mobile screen sizes
Extends #2554

Use-cases mobile hero image adjustments

---

src/content/developers/docs/programming-languages/index.md

When there is no library you just use the JSON-RPC interface directly (or write a library)
A user asked how to use Swift. We figured more than one person could use the answer.
This is based on #2222

Added using unsupported languages

---

src/content/developers/docs/apis/json-rpc/index.md

Update JSON RPC intro

---

src/content/nft/index.md

NFT page: `/staking/` fixed to `/eth2/staking/`
@ryancreatescopy

Broken link fix

---

src/content/developers/docs/accounts/index.md

- misspelled words
- output should not be plural

Minor typo clean-up in the Accounts doc

---

src/content/community/index.md

Updating ETHGlobal events, NFTHacks closed applications and applications recently opened for Scaling Ethereum.

[Community Events] Remove NFTHack and add Scaling Ethereum

---

src/content/learn/index.md

The two broken links on the learn page are updated.
Fixes ethereum/ethereum-org-website#2677

Fix broken links on the learn page 

---

src/content/developers/tutorials/waffle-hello-world-with-buidler-tutorial/index.md

Lowercase directory name - slugs should be lowercase.
Fixes #2672

Lowercase directory name

---

src/content/developers/docs/intro-to-ethereum/index.md

Small grammar fixes for [Intro to Ethereum page](https://ethereum.org/en/developers/docs/intro-to-ethereum/) ([Respective Mardown file](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/intro-to-ethereum/index.md)).
Fixes #2689

Small Grammar Fix

---

src/content/developers/docs/storage/index.md

fix: storage doc - grammar

---

.all-contributorsrc

Updated dTilen's profile url as the previous website url was broken.

Updated out of date content (profile url)

---

src/content/developers/docs/accounts/index.md

Add visual demo to Accounts section

---

src/content/developers/docs/programming-languages/rust/index.md

Update this link: [Sending Transaction to Ethereum Using Rust](https://kauri.io/#collections/A%20Hackathon%20Survival%20Guide/sending-ethereum-transactions-with-rust/)
This problem was identified by @rabbitXIII at #2682. I just submitted the PR to save time, he gets all the credit.
#2682

Update a link

---

src/content/developers/tutorials/erc20-annotated-code/index.md

fixed link to safemath.sol

---

README.md

Updates `README.md` reflecting the 2021 POAPs being live

Update README with POAP updates [skip ci]

---

src/content/community/index.md

- Removes past events
- Adds custom header id to new support section.

Update community/index.md [skip ci]

---

src/content/community/grants/index.md
src/content/community/index.md
src/templates/docs.js
src/templates/eth2.js
src/templates/job.js
src/templates/static.js
src/templates/tutorial.js
src/templates/use-cases.js

- Update static templates to show GH edit button
- Link to Grants page from Community page
None

Grants updates

---

src/content/developers/docs/ides/index.md

- Add JetBrains IDEs section to `ides/index.md`
- 
resolves ethereum/ethereum-org-website#2743

Add JetBrains to IDEs [Fixes #2743]

---

src/content/contributing/translation-program/index.md

Add note on the Translation Program page re: the Eth2 Launchpad translation program
None

Add reference to Eth2 Launchpad translation program

---

src/content/learn/index.md

Most of the Layer 2 resources we link to on the Learn page are quite outdated. Updated that page to just refer to our documentation page on Layer 2.
None

Refer to Layer 2 page for info

---

src/content/developers/docs/accounts/index.md

Specify HTTPS on YT embeds [Fixes #2787]

---

src/content/developers/docs/web2-vs-web3/index.md

Change `refer` to `refers`.
Minor grammar correction -> "refers to decentralized apps" instead of "refer to decentralized apps".

minor grammar correction

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add call to contribute to bottom of issue templates
None

Add call to contribute to bottom of issue templates

---

src/content/developers/docs/nodes-and-clients/index.md

Simplify Node/Client explanation

---

src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Small fix to correct the link to Grafana
None

fixed link to Grafana

---

src/content/developers/docs/consensus-mechanisms/pos/index.md

Various content edits in **PROOF-OF-STAKE (POS)** webpage (spelling, grammar, flow)
None

Various edits in "Proof-of-Stake" webpage

---

src/content/developers/docs/standards/tokens/erc-20/index.md

Same links but for ERC20 page.

Deleting ERC-777 and ERC-1555

---

src/content/history/index.md

Adds Berlin upgrade to history page.

Adds Berlin upgrade to history page

---

src/pages/studio.js

Update content to no longer reference project URLs & instead point to Github repos.
#2851

Update Studio page content [Fixes #2851]

---

src/content/community/index.md

Slightly more relevant link
None

Update jobs link to Ethereum section

---

src/content/developers/tutorials/erc20-annotated-code/index.md

Fixed minor typo

---

src/content/developers/docs/standards/tokens/index.md

Fixing a typo in the Related tutorials section

Fixing a typo

---

src/content/developers/docs/consensus-mechanisms/pos/index.md

In /src/content/developers/docs/consensus-mechanisum/pos/index.md line 26, add a page reference to "Shard" page.
#2865

Quick contents update  [Contents update #2865]

---

src/content/developers/docs/oracles/index.md

Fixed typo.
```
recieve -> receive
```

Fix typo in  oracles/index.md

---

src/content/developers/tutorials/deploying-your-first-smart-contract/index.md

typo line 17: "fist" -> "first"

---

src/content/community/index.md

Remove passed event on Community page

Update community events

---

src/content/developers/docs/layer-2-scaling/index.md

Add L2Beat & a few articles they mention
Discord discussion: https://discord.com/channels/714888181740339261/714888881824333894/833022329717129278

Add L2Beat & other L2 resources

---

src/content/developers/docs/layer-2-scaling/index.md

Added more complete description of zero-knowledge rollups' pros and cons
Closes #2797

More complete description of zkRollups

---

README.md

GitHub format

---

src/content/developers/docs/intro-to-ethereum/index.md

This sections explains smart contracts. dapps are explained on the following page: https://ethereum.org/en/developers/docs/dapps/#definition-of-a-dapp

Rename section to "What are smart contracts"

---

src/content/developers/docs/intro-to-ethereum/index.md

...hopefully making it more clear...

Update blockchain section

---

src/intl/en/page-dapps.json

Updates grammar for `src/intl/en/page-dapp.json` > `page-dapps-features-6-description`
Fixes #2892

Fixing grammar for page-dapps [Fixes #2892]

---

src/content/developers/docs/smart-contracts/anatomy/index.md

I think `exceeded` is the desired word here, not `succeeded`.

Change error message in example Token contract

---

src/content/history/index.md

Fixes https://github.com/ethereum/ethereum-org-website/issues/2918

Add London and Altair info

---

src/content/developers/docs/consensus-mechanisms/pow/index.md

There was a missing full stop in line 85(compared to proof of stake topic's first point).

Added missing full stop

---

src/content/developers/docs/smart-contracts/languages/index.md

- Updates the Solidity section - more context on Solidity's language influences can be found [here](https://docs.soliditylang.org/en/latest/language-influences.html) if necessary.
- Adds "Fe" as a new and emerging smart contract language. I know they are still early but it might make sense to show the variety of different languages and innovation available. 
cc @cburgdorf I hope the stuff I wrote on Fe is ok for you guys, please feel free to have a look and adjust. :)

[Smart contract lang page] Updating Solidity section and adding Fe section

---

src/content/history/index.md

Based on feedback: https://discord.com/channels/420394352083337236/801131433510830091/841208169162080266
None

Add forks to history title

---

src/content/learn/index.md

Lists _Understanding Ethereum_ article link under "How Ethereum works" section of "Community guides and resources" page at `/learn`.
[Closes #2947]

Adds Understanding Ethereum article link

---

src/content/community/index.md

Add Eth R&D Discord

---

src/content/developers/docs/apis/backend/index.md
src/content/developers/docs/scaling/index.md
src/content/translations/ro/developers/docs/apis/backend/index.md

Fix dev doc links [Fixes #3031]

---

src/content/developers/docs/scaling/index.md

Adding "An Incomplete Guide to Rollups" from Vitalik to recommended readings

Adding to Scaling page Further Readings

---

src/intl/en/page-eth2-get-involved-bug-bounty.json

- Fixes a string that leaves Nimbus out
- (reorders clients to match rest of page)
[Fixes #2943]

Adds nimbus to client list string [Fixes #2943]

---

src/content/about/community-lead/index.md
src/content/about/index.md

Adds Community & Ecosystem Lead job description

---

src/content/developers/docs/gas/index.md

I have answered all of the following:
Explain why gas fees get high (i.e. high demand for the network)
Explain initiatives in progress (e.g. Eth2, L2) that are working to reduce gas costs
Explain strategies users can use to reduce gas costs (e.g. tools to monitor gas prices)
Explain approaches as a dapp developer you can do to reduce gas usage of smart contracts (e.g. assembly code optimization)
I have added information about the above and also added a YouTube video link and 3 website links.
I have added a "Why are gas fees so high?" part then written this "High Gas fees are due to the popularity of Ethereum. As every operation on the Etheruem blockcahin uses gas, including computation, checking the balance of an account and transaction fees, these all contribute to the high gas levels we …

Adds content to Gas developer docs

---

.all-contributorsrc
README.md
package.json
src/components/StablecoinAccordion.js
src/content/about/community-lead/index.md
src/content/developers/docs/scaling/layer-2-rollups/index.md
src/data/eth2-bounty-hunters.csv

***
- Update community lead job description (#3077) @GeorgeTrotter
- stablecoins: set the correct URLs for all DEXs (#3074) @skylenet
- Add zkTube to layer 2 solutions (#2997) @Dave2022
***
Thank you @Dave2022, @GeorgeTrotter, @JustinDrake, @samajammin, @skylenet and @wackerow for the contributions! :trophy:
***

Deploy v2.28.1

---

src/content/developers/docs/smart-contracts/anatomy/index.md

Simple misspelling

---

src/content/developers/docs/evm/index.md

**Product name:**
hevm
**Product description:**
Testing oriented EVM implementation. Debug, fuzz, or symbolically execute code against local or mainnet state.
**How long has it been around?**
~2 years (initial release 2019-08-06)
**Where do you think it should go?**
https://ethereum.org/en/developers/docs/evm/
**GitHub URL**
https://github.com/dapphub/dapptools/tree/master/src/hevm
**Docs URL**
https://github.com/dapphub/dapptools/tree/master/src/hevm
**Is the product open source?**
yes
**Additional context**
used in the development and testing of several well known contracts, including Multi-Collateral Dai and Uniswap

add hevm to list of EVM implementations

---

src/content/developers/docs/scaling/layer-2-rollups/index.md

Update to add OMGX

---

src/content/developers/docs/gas/index.md

Added an example for more clarity how the transaction fee is calculated.
I added an example which shows how the transaction fee is calculated based on the Gas units and price.
I think adding this example gives more clarity to the reader as the reader will be able to relate to a real life situation as mentioned in the example.

Added example of Gas Fees

---

src/intl/en/page-languages.json
src/pages/languages.js

Added a search input to the languages page so the languages can be dynamically filtered and rendered onto the page.
[Fixes #3036]

Added a search input to the languages page

---

src/content/defi/index.md

Implemented suggestions made by @rhechler, thanks!
Affects: https://ethereum.org/en/defi/#bitcoin

Grammatical correction [Fixes #3075]

---

src/content/developers/docs/gas/index.md

Fixes a markup issue that is causing titles to render incorrectly. 
Screenshot before change:

Fix markup in gas/index.md

---

src/content/developers/docs/standards/tokens/index.md

Fixes broken link (thanks @jcpickett1 for surfacing!)
#3073

Link fix [Fixes #3073]

---

src/content/translations/es/python/index.md

Changed 'Etherium' to correct spelling 😀

Fix Spelling Mistake

---

src/content/developers/docs/scaling/index.md

I believe there was a simple mistake in the text of the _Scaling_ page, in the chapter of _State Channels_.
I think the author meant to use "thus" instead of "this".

Fix possible grammatical mistake

---

src/content/learn/index.md

Any reason not to have this on here?

Add Link to developer learning tools to pull request

---

src/content/developers/docs/gas/index.md

Name fix for the example

---

src/content/translations/ml/javascript/index.md

docs update => proper capitalisation would be better. 👍: Github
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>

DOC: Fix camelCase (or capitalization)

---

src/content/about/community-lead/index.md

Make it clear this role is for ethereum.org not the EF broadly
None

Update community role

---

src/content/about/community-lead/index.md

Update community lead JD for compensation range, requesting cover letter in application

---

src/content/eips/index.md

Add editors

---

src/content/developers/tutorials/erc-721-vyper-annotated-code/index.md

Fixed typo.
```
inheritence -> inheritance
```

Fix typo in  erc-721-vyper-annotated-code/index.md

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

Simple grammatical fix to the sentence.

Fixes grammar in doc: including -> include

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

French and Turkish languages added for Ethplorer
#3189

More supported languages added for Ethplorer

---

src/content/developers/docs/programming-languages/python/index.md

Added a few more python tutorials. Some ranging to more advanced. The DeFi one shows users how to interact with Aave in an advanced manner.
https://github.com/ethereum/ethereum-org-website/issues/3187

added more python tutorials!

---

src/content/developers/docs/gas/index.md

Correcting the formula for transaction fee to gasLimit times gasPrice

Transaction fee calculation

---

src/content/developers/docs/nodes-and-clients/index.md

Add snap (which is now default sync) to Geth

---

src/content/eth2/merge/index.md

eth2 page: fixing minor typo

---

src/content/developers/docs/nodes-and-clients/index.md
src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Add Erigon to node list(s)
None

Add Erigon

---

src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md

I was studying the Transfers and approval of ERC-20 tokens from a solidity smart contract and I came across three typos highlighted in issue #3233. So I have fixed them. Thank you for the amazing tutorial
Open issue #3233 
Fixed are highlighted in bold below. 
> For this tutorial we’ll use the code we wrote in the previous tutorial as a base. Our DEX will instantiate an instance of the contract in **its** constructor and **perform** the operations of:
> So we **now** have our DEX and it has all the token reserve available. The contract has two functions:
Thanks and Regards
Elio

fixed three typos in the ERC-20 tutorial highlighted in #3233

---

src/components/Eth2ShardChainsList.js

Adds sharding article #3239

---

src/content/developers/docs/nodes-and-clients/index.md

PR to correct a typographical error in the docs

correct typo

---

src/content/glossary/index.md

elliptic curve digital signature algorithm (ECDSA) [Fixes #3229]
supplemented the definition by adding additional content.
New definition: A cryptographic algorithm used by Ethereum to create public and private keys. Relevant for account address generation and transaction verification.
Related Issue
https://github.com/ethereum/ethereum-org-website/issues/3229

Supplemented glossary definition for elliptic curve digital signature algorithm (ECDSA)

---

src/content/developers/tutorials/waffle-say-hello-world-with-hardhat-and-ethers/index.md

Fixed a broken example test on the Waffles say "hello world!" tutorial page.

Fixed broken sample test on tutorial page

---

README.md

Just a minimal and quick change to the README File to enhance the view.
I Added a hand waiving GIF in place of a Sticker.

Added a hand waiving gif in place of Sticker.

---

src/content/developers/docs/dapps/index.md

fix a grammatical error in the Dapps Introduction documentation.

fix(Dapps Documentation): grammatical error

---

src/content/community/index.md
src/data/community-events.json

Added ETHOdyssey Hackathon
- https://ethodyssey.devfolio.co
- https://twitter.com/ethindiaco

hackathon: Add ETHOdyssey Hackathon

---

.github/CODEOWNERS

Update our CODEOWNERS file
None

Replace Ryan w/ Pablo & Corwin

---

src/content/developers/docs/programming-languages/python/index.md

correct dead link

---

src/content/translations/ar/python/index.md
src/content/translations/bn/python/index.md
src/content/translations/cs/python/index.md
src/content/translations/de/python/index.md
src/content/translations/es/python/index.md
src/content/translations/fi/python/index.md
src/content/translations/fr/python/index.md
src/content/translations/hu/python/index.md
src/content/translations/id/python/index.md
src/content/translations/it/python/index.md
src/content/translations/ja/python/index.md
src/content/translations/ko/python/index.md
src/content/translations/lt/python/index.md
src/content/translations/ml/python/index.md
src/content/translations/nb/python/index.md
src/content/translations/pt-br/python/index.md
src/content/translations/ro/developers/docs/programming-languages/python/index.md
src/content/translations/ro/python/index.md
src/content/translations/se/python/index.md
src/content/translations/sk/python/index.md
src/content/translations/tr/python/index.md
src/content/translations/uk/python/index.md
src/content/translations/vi/python/index.md
src/content/translations/zh/python/index.md

Dead link update for intl pages

---

src/content/developers/docs/gas/index.md

Embeds YouTube video [Fixes #3315]

---

src/data/community-events.json

- Lists Women Spotlight event under community events (Update community-events.json)
#3297

Lists Women Spotlight event under community events [Closes #3297]

---

src/content/developers/docs/scaling/layer-2-rollups/index.md

Fix typo in docs - Layer 2 Rollups

---

src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Fixed a small typo.

---

src/data/community-events.json

- Adds EthCC4, and EthCC week to community events page
- Removed past event
#3362

Adds EthCC to community events

---

src/content/whitepaper/index.md

- Adds markdown syntax to make table render appropriately
#3338

Adds markdown syntax for table within whitepaper [Fixes #3338]

---

src/content/developers/docs/programming-languages/python/index.md
src/content/translations/ar/python/index.md
src/content/translations/bn/python/index.md
src/content/translations/cs/python/index.md
src/content/translations/de/python/index.md
src/content/translations/es/python/index.md
src/content/translations/fi/python/index.md
src/content/translations/fr/python/index.md
src/content/translations/hu/python/index.md
src/content/translations/id/python/index.md
src/content/translations/it/python/index.md
src/content/translations/ja/python/index.md
src/content/translations/ko/python/index.md
src/content/translations/lt/python/index.md
src/content/translations/ml/python/index.md
src/content/translations/nb/python/index.md
src/content/translations/pt-br/python/index.md
src/content/translations/ro/developers/docs/programming-languages/python/index.md
src/content/translations/ro/python/index.md
src/content/translations/se/python/index.md
src/content/translations/sk/python/index.md
src/content/translations/tr/python/index.md
src/content/translations/uk/python/index.md
src/content/translations/vi/python/index.md
src/content/translations/zh-tw/python/index.md
src/content/translations/zh/python/index.md

Reported by a user on discord: https://discord.com/channels/714888181740339261/714888881824333894/861289747438370826

Fix Broken Links in Ethereum for Python Devs docs

---

README.md

- Adds closing parenthesis to link text.

Typo correction README.md

---

src/data/community-events.json

Peep the new `.com` 👀
Adding the latest ETHGlobal event

[Community Events] Add HackFS

---

src/content/developers/docs/ides/index.md
src/content/translations/ro/developers/docs/ides/index.md

Added Remix desktop IDE

---

src/content/contributing/translation-program/index.md

Fix word stat

---

src/data/eth2-bounty-hunters.csv

Add 9000 point bounty to GRandine team for finding a fork choice implementation bu

add Saulius 9000 point bounty

---

src/intl/en/page-eth2-staking.json

"miner" to "minor"
`"page-eth2-staking-upgrades-li-5": "A minor upgrade will follow to enable withdraw of staked funds.",`
#3498
Thanks @esale for posting =)

Typo correction [Fixes #3498]

---

src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md

Tutorial for getting set up with the Tellor oracle.
Submission for 'How to Set Up the Tellor Oracle' to be added to the developer tutorials page.

Tellor Oracle Tutorial

---

src/content/developers/docs/oracles/index.md

I have added an additional open-source oracle (Paralink Network) under the Oracle Services section.
[Closes #3433]

Add Paralink Network to Oracles page

---

src/data/wallets.csv

Addresses [comment](https://github.com/ethereum/ethereum-org-website/issues/3186#issuecomment-882404112) on #3186

Updates bitcoin.com wallet listing with token swaps

---

src/content/foundation/index.md

Add Fellowship Program section on the Ethereum Foundation page
None

Add blurb on EF fellowship program

---

src/components/TranslationsInProgress.js
src/content/contributing/translation-program/index.md
src/lambda/translation-build.js
src/lambda/translations.js
src/utils/translations.js

https://crowdin.com/project/ethereum-org/
(ethereumfoundation -> ethereum-org)
cc: @lukassim

Updates with new Crowdin link

---

README.md

Add Crowdin badge to display localization progress
None

Add Crowdin badge to display localization progress

---

package.json
src/components/Layout.js
src/components/ReleaseBanner.js
src/intl/en/common.json
src/lambda/etherscanBlock.js
src/utils/cache.js
yarn.lock

Adds a BannerNotfication for the London Upgrade. This banner will have a countdown until launch (which estimated time is fetched from etherscan.io), and will say the upgrade has been released when the block has been mined (again, fetched from etherscan.io).
https://github.com/ethereum/ethereum-org-website/issues/3522

London Banner

---

src/components/Layout.js
src/components/ReleaseBanner.js

Switch to using Link component instead of using a href.

Link for Release Banner instead of a href

---

src/content/history/index.md

Updates London History with exact time, price and wayback machine link.

Update London History

---

src/content/community/index.md

I changed the wrong link in the index.md file and wrote the correct link both of which are clearly mentioned in the issue description.

Fixed issue #3564

---

src/content/community/grants/index.md

Also removed the expired rollup grants (which were a subcomponent of ESP)

add Ethereum RFPs

---

src/content/developers/docs/smart-contracts/index.md

The best explanation of smart contracts should include something about immutability, but that word is kind of jargon so it should say transactions on them are irreversible and the deployed contracts cant be deleted.

Add some stronger language to why smart contracts are cool + immutable 

---

src/content/developers/docs/standards/tokens/index.md

Added ERC-777 to token Standards, with a short description.

Update index.md to include ERC-777

---

src/content/community/index.md

- Added more job search resources

Updated job page links

---

src/content/contributing/index.md

Added a header for devs new to open source and linking to first issues label
#3587

Point to good first issues labels [Feature #3587]

---

src/components/SharedStyledComponents.js

CSS fix for H4 [Closes #3600]

---

src/data/community-events.json

Add upcoming events to community page

---

src/content/community/index.md

Reorders the list of job boards as per #3594

Reorder Job Boards Chronologically

---

src/components/FeedbackCard.js

Added a discord invitation link on feedback card
Resolves #3581

Adding invitation to discord on feedback card

---

src/content/developers/docs/gas/index.md

Update Issue #3611

---

src/data/wallets.csv

The Argent logo disappeared following the last update. This fixes the issue by changing the background colour to white.

[UPDATE] Colour for Argent to ensure logo is visible.

---

src/content/contributing/index.md

We give POAPS for contributions this year as well 😄 
None

Remove mention of 2020

---

README.md
src/content/contributing/translation-program/index.md

Removes remaining references to claiming 2020 POAPs

Remove 2020 POAP ref from translations-program

---

src/components/Eth2Articles.js
src/data/eth2-articles.js

Updates the outdated ETH2 articles were displaying as pointed out by Trent in #3627
Closes #3627

Update ETH2 article section

---

src/content/developers/docs/dapps/index.md

Changed ABI to API on the intro to dapps section of the docs.

Fix typo in docs

---

src/content/developers/docs/smart-contracts/composability/index.md

Add Composability is Innovation to Further reading in `src/content/developers/docs/smart-contracts/composability/index.md.` The article is by: Linda Xie and published by: future.a16z.com
none

Add Composability is Innovation to Further reading in src/content/developers/docs/smart-contracts/composability/index.md

---

src/content/developers/tutorials/calling-a-smart-contract-from-javascript/index.md

"it's" = "it is" / "its" = possessive

Fixed grammar errors

---

src/content/developers/docs/scaling/plasma/index.md

An excellent resource for all things Plasma!
Adding a Link to the Learn Plasma Resource
#3655

Add Learn Plasma

---

src/content/nft/index.md

Added a bit more information on how NFTs work. Fixes [#2839]

---

src/content/developers/docs/scaling/plasma/index.md

fix typo: Merkel Tree -> Merkle Tree

---

src/content/developers/docs/nodes-and-clients/index.md

I was reading the `Nodes and client` docs and noticed there were two similar entries for Erigon. I kept the one with a bit more information.

Remove duplicate entry for Erigon

---

src/content/developers/docs/gas/index.md

Fix typo in `src/content/developers/docs/gas/index.md`.
This closes: #3687

Fix typo in src/content/developers/docs/gas/index.md

---

src/content/developers/tutorials/how-to-mint-an-nft/index.md
src/content/developers/tutorials/how-to-view-nft-in-metamask/index.md
src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md

Adds missing sidebars to the NFT tutorial series
**Pages Changed**
- https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/
- https://ethereum.org/en/developers/tutorials/how-to-mint-an-nft/
- https://ethereum.org/en/developers/tutorials/how-to-view-nft-in-metamask/

Add sidebar to NFT tutorial series

---

src/content/developers/docs/apis/json-rpc/index.md

Changes query param in JSON RPC Spec link to display the playground by default

Display JSON RPC playground

---

src/data/community-events.json

Added LisCon in [Upcoming Events](https://ethereum.org/en/community/#upcoming-events)
Fixes #3728

feat: LisCon added in Upcoming Events

---

src/content/developers/docs/oracles/index.md

Add to DOSNetwork to Oracle docs

---

src/content/developers/docs/intro-to-ethereum/index.md

The original page links to the demo website by Anders but it doesn't mention the video that he has on Youtube where he explains it wonderfully.
He goes through the entire demo step by step and explains the core concepts of blockchain in very simple terms.
I added an embedding to his video on this page.

Add blockchain hashes video to 'Intro to Ethereum' developer doc

---

src/data/eth2-articles.js

Add latest articles on eth2 from Danny Ryan and Ben Edgington
#3632

Update eth2 articles

---

src/content/nft/index.md

Aligned energy calculations with Carl's article
1: Added link on NFT page to Carl's energy article: https://blog.ethereum.org/2021/05/18/country-power-no-more/
2: Aligned energy calculations with Carl's article.
3072
https://github.com/ethereum/ethereum-org-website/issues/3072

Align energy calculations with Carl´s article [Fixes #3072]

---

src/content/glossary/index.md

Just fixing this small typo :) 
Beacon Chainin the -> Beacon Chain in the
Fixes: https://github.com/ethereum/ethereum-org-website/issues/3775

Fix crosslink typo in glossary [Fixes #3375]

---

src/data/tutorials.json
src/intl/en/page-developers-tutorials.json
src/pages/developers/tutorials.js

Adding tutorials from 3rd party on tutorials page
Added extra sources on turorials page via JSON file.
Resolves #3620

adding tutorials from external sources

---

README.md

Add a section about the Translation Program to the readme, including a brief overview and the relevant links.
#3800

Add Translation Program section to the readme

---

README.md

After a while, the animated wave can get quite annoying. It was a nice idea at the time but I think using a regular emoji is better and is one less network request for our users 🙏😬

Remove animated wave gif in README

---

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md

Typos and grammar fixes
Fixed a few typos, removed/added missing words, did some light grammar checks.

Fix grammar and typos in NFT tutorial

---

src/content/developers/docs/transactions/index.md

Add information on transaction types. Sorry if I missed a type or made some complete nonsense I just now learned about the different transaction types.
This closes: #3547

Add transaction types to transactions page

---

src/content/developers/docs/intro-to-ether/index.md

Line 52,
Changed "Wei the smallest possible amount of ether, ..." to "Wei is the smallest possible amount of ether, ..."

Grammar fix

---

src/content/whitepaper/index.md

Reword the Agility section under Ethereum Philosophy in the whitepaper to make it less confusing [Fixes #3397]
The current wording of the whitepaper's Ethereum > Philosopy > Agility section is hard to understand due to some grammar issues, and also the inclusion of some technical terms (i.e. abstracting execution, data availability enshrined in consensus) that increase the complexity of the explanation. I think these terms can be removed from the explanation, as it seems that the main goal is to communicate that extensive deliberation must occur when changes to core aspects of the protocol are proposed.
> Agility: details of the Ethereum protocol are not set in stone. Although we will be extremely judicious about making modifications to high-level constructs, for instance with the …

Reword Agility section for clarity in Ethereum Philosophy (WP) [Fixes #3397]

---

src/content/contributing/index.md

changing some lines ; ,making it more understandable and eligible to read for users.
- Grammatical errors and paraphrasing some lines to make it more readable for users.

Reword section of contributing readme

---

src/content/developers/docs/gas/index.md

My prior suggestion included a small typo I just realized 🤦

Fix typo on gas page

---

.github/ISSUE_TEMPLATE/suggest_wallet.md

Added 4 additional questions to reduce the amount of back-and-forth required to make a decision on wallets. 
- Is your wallet security tested? Please explain security measures i.e. security audit, internal security team or some other method.
- When did your wallet go live to users?
- Does your wallet have an active development team?
- Is your wallet open-source?

Update wallet issue template

---

.github/ISSUE_TEMPLATE/suggest_tutorial.md

This PR updates the tutorial submission template to receive externally hosted tutorial submissions.
None

Update tutorial submission template

---

src/content/developers/docs/gas/index.md

Added BlockNative's new gas estimation Chrome extension which supports both Type 0 legacy transactions and Type 2 EIP-1559 transactions.
None

Add BlockNative's chrome extension to gas page

---

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
src/content/translations/es/glossary/index.md

Fix typo in Part 1 of NFT tutorial series

---

src/data/tutorials.json
src/pages/developers/tutorials.js

Add external tutorials data and refactor tutorials

---

.github/workflows/on-pr-close.yml

Fix Close PR workflow

---

.github/workflows/on-pr-close.yml

Fix workflow

---

src/data/eth2-bounty-hunters.csv

Add 1,500 points to Guido Vranken.

Update eth2-bounty-hunters.csv (+1,500 points to Guido)

---

.github/ISSUE_TEMPLATE/suggest_tutorial.md

Hey, I have noticed a small grammatical error on the tutorial issue template while creating an issue. So I thought of fixing it.
Want to start contributing to this organization, so started with the smallest of the fixes.
#3856

Fixed grammatical error in tutorial issue template

---

src/data/eth2-bounty-hunters.csv

Update eth2-bounty-hunters.csv (+100 points to Jim McDonald)

---

src/content/developers/tutorials/how-to-mint-an-nft/index.md

Updated pinata.cloud link
Current link is broken

Fix broken signup link on NFT tutorial

---

README.md

We forgot to change the CrowdIn badge on the README when we changed the CrowdIn URL :) This PR fixes that

Update CrowdInLink on README badge

---

src/content/dao/index.md

Add “What is a DAO?” to DAO Articles by: Coinmarketcap
none

Add “What is a DAO?” to articles on DAO page

---

src/content/governance/index.md

Fixes a mistake pointed out by David on Discord - ETH is not a token.
https://discord.com/channels/714888181740339261/870313128242602004/885979955324919848

Fix Governance page error

---

src/content/developers/docs/smart-contracts/index.md

Updated solidity version from 0.6.11 to 0.8.7.
From what I could tell there have been no breaking changes and therefore, the code is still valid.
Fixes #3891

Updated solidity version in smart contract developer docs

---

src/content/developers/docs/nodes-and-clients/index.md

Elaborating content about synchronization strategies. 
Sync modes section remade, updated, added more info explaining high level benefits and tradeoffs. 
Solves #3219

Add info on sync modes to nodes-and-clients docs

---

src/content/glossary/index.md

Add API to Glossary

---

src/content/developers/docs/smart-contracts/composability/index.md

This small change just points the docs to the latest Uniswap contracts.

Add URL to Uniswap v3 contracts to smart contracts

---

src/content/governance/index.md

Trims down the opening definition of governance.
Related to https://twitter.com/technocrypto/status/1436877444410232833?s=20
Purely subjective opinions here but I tend to agree that we can mostly assume people understand the concept of governance. We should cut to the chase: governance in the context of Ethereum.

Consolidate definition of governance

---

src/content/translations/zh/developers/docs/apis/javascript/index.md

fix: web3 usage typo

---

src/pages/eth2/get-involved/index.js

Updates Prsym's staking link to the new official getting started documentation
#3921

Update Prysmatic Labs documentation link

---

src/content/dao/index.md

This PR fixes a typo in the DAO documentation. The word "want" was omitted.
None

Fix typo in DAO docs

---

src/content/contributing/style-guide/index.md

Fix typo on Ethereum.org Style Guide

---

src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Fix broken link to layer-2 rollups page

---

src/content/community/index.md

Made two lines italic for consistency and added Developer DAO to list of DAOs.
#3932

Consistent Formatting/Added DAO [Fixes #3932]

---

src/content/developers/docs/consensus-mechanisms/pow/index.md

Add “What is Proof of Work” by: Whiteboard Crypto
none

Add “What is Proof of Work” video 

---

src/content/developers/docs/smart-contracts/index.md

Add information on smart contact size limitations and a link to the diamond pattern eip.
#3943

Add info smart contact size limitations and diamond pattern

---

src/content/developers/docs/scaling/layer-2-rollups/index.md
src/content/translations/pl/developers/docs/scaling/layer-2-rollups/index.md

OMGX has recently undergone a name change to Boba Network.
N/A

Update the name of OMGX to Boba

---

src/content/developers/docs/frameworks/index.md

Corrected Discord Link For Alchemy Platform

Fix Discord Link For Alchemy Platform

---

src/content/developers/docs/apis/backend/index.md

Fix Discord Link For Alchemy Platform

Fix Discord Link For Alchemy Platform on backend API page

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

Fix Alchemy link on nodes and services doc

---

src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md

Fix Alchemy link on web3 and alchemy tutorial

---

src/content/enterprise/index.md

Update Alchemy Link on Enterprise page

---

src/content/developers/docs/mev/index.md

Fixed Link IvanBogatyy Twitter Status for 7$million

Add explicit https to twitter link

---

src/content/developers/docs/frameworks/index.md
src/content/translations/es/developers/docs/frameworks/index.md
src/content/translations/fr/developers/docs/frameworks/index.md
src/content/translations/hu/developers/docs/frameworks/index.md
src/content/translations/it/developers/docs/frameworks/index.md
src/content/translations/pl/developers/docs/frameworks/index.md
src/content/translations/ro/developers/docs/frameworks/index.md
src/content/translations/zh/developers/docs/frameworks/index.md

Edited Etherlime Docs Page Link To An Appropriate Link

Remove all occurrences of Etherlime (deprecated) from docs

---

src/content/community/index.md

Add Bankless jobs board

---

src/data/community-events.json

Add ETH Portland to community events
#4002

Add ETH Portland to community events [Fixes #4002]

---

src/content/contributing/translation-program/index.md

Update the number of translators and number of words translated in 2021.
#4029

Update Translation Program stats #2

---

src/data/community-events.json

- Updates recently added EthPortland event listing with modified dates, now planned to take place 10/28-10/29.
(none filed)

Update EthPortland dates

---

src/content/nft/index.md

99.98% -> 99.95% Energy Reduction in ETH2 in NFT Page.
#3950

99.98% -> 99.95% Energy Reduction in ETH2 in NFT Page

---

yarn.lock

- Ran `npx browserslist@latest --update-db` to update caniuse browser db list
[Fixes #4004]

Updates caniuse db to latest [Fixes #4004]

---

src/content/glossary/index.md

Fix broken wallet link in Glossary

---

src/content/glossary/index.md

Fix proof-of-stake link in glossary

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

InfStones provides Ethereum Public API service and Dedicated Node service on InfStones platform. We hope to be listed in the node service provider list, so as to provide convenience to more developers in the Ethereum community. Thanks.

Add InfStones to nodes-as-a-service

---

src/intl/en/page-eth2-get-involved-bug-bounty.json

Adding 2x rewards for vulnerabilities related to Altair.

Adding 2x rewards for vulnerabilities related to Altair

---

src/content/developers/docs/programming-languages/python/index.md

New developers can look some of DeFi blue-chip projects for example code.

Update Python developer docs - add notable Ethereum projects using Brownie and Vyper

---

src/intl/en/common.json

Add missing breadcrumbs for Governance page

---

src/content/developers/docs/intro-to-ethereum/index.md

This PR is part of a series to audit the developer docs in preparation for upgrades to our translation program.
Changes are:
- Improve readability
Todo: 
[I've posted on Ethereum Python Community Discord](https://discord.com/channels/809793915578089484/844687746911567892/887687158301872179) to see if someone familiar with Python web3 can have a quick look at the tutorial we're linking out to.

Update Intro to Ethereum developer doc

---

src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
src/content/translations/zh/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
src/content/translations/zh/developers/tutorials/calling-a-smart-contract-from-javascript/index.md
src/content/translations/zh/developers/tutorials/deploying-your-first-smart-contract/index.md
src/content/translations/zh/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
src/content/translations/zh/developers/tutorials/how-to-implement-an-erc721-market/index.md
src/content/translations/zh/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
src/content/translations/zh/developers/tutorials/how-to-use-slither-to-find-smart-contract-bugs/index.md
src/content/translations/zh/developers/tutorials/interact-with-other-contracts-from-solidity/index.md
src/content/translations/zh/developers/tutorials/logging-events-smart-contracts/index.md
src/content/translations/zh/developers/tutorials/run-light-node-geth/index.md
src/content/translations/zh/developers/tutorials/run-node-raspberry-pi/index.md
src/content/translations/zh/developers/tutorials/smart-contract-security-guidelines/index.md
src/content/translations/zh/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
src/content/translations/zh/developers/tutorials/token-integration-checklist/index.md
src/content/translations/zh/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
src/content/translations/zh/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
src/content/translations/zh/developers/tutorials/using-websockets/index.md
src/content/translations/zh/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md

- Adds available `zh` (Chinese Simplified) v2.2 developer tutorials
🎉 And of course, a special thanks to the Crowdin community for making this happen! 🙏🏻 
[Fixes #4040]

Adds available Chinese tutorials [Fixes #4040]

---

src/content/security/index.md

`one is going to give you free or discounted ETH!` -> `no one is going to give you free or discounted ETH!`
none filed

Patch to security copy

---

src/content/whitepaper/index.md

Fixed Wiki Links Yellow Paper Appendix, Yellow Papaer and YP

Fixed Wiki Links Yellow Paper Appendix, Yellow Papaer and YP

---

src/content/developers/docs/mev/index.md

Twitter is a huge part of why miner extractable value is such a big part of the Ethereum conversation nowadays, so including a link to @bertcmiller's MEV threads on the ethereum.org MEV page will hopefully allow people to discover MEV Twitter earlier in their MEV journey and learn more about the topic faster.

Add link to bertcmiller's MEV threads

---

src/content/history/index.md

Updated DAO Attack 2016 Redirected Link

---

src/content/whitepaper/index.md

Have Updated The Direct Link For DAO. It will result in faster redirect.
Although this is not necessary.
@minimalsm @wackerow  .
Just Ping Me If this don't seems necessary. I will close The PR

Updated DAO Direct Redirect Https Link

---

src/content/community/grants/index.md

MakerDAO have Closed there Open Grants .
Check This Link : https://blog.makerdao.com/maker-development-grants-program-sunsets/
@samajammin @minimalsm @wackerow 
Please Review This

Removed MakerDAO Open Grants

---

src/content/contributing/style-guide/index.md

Adds a few missing custom header ids on the `style-guide` page
none filed

Adds missing custom header ids on style-guide

---

src/content/whitepaper/index.md

Removed Existing Solutions Broken URL

Remove Broken URL on Whitepaper

---

src/content/developers/docs/dapps/index.md

Deploy preview - https://deploy-preview-4065--ethereumorg.netlify.app/en/developers/docs/dapps/

Update intro to dapps developer doc

---

src/content/developers/docs/smart-contracts/deploying/index.md

Deploy preview - https://deploy-preview-4064--ethereumorg.netlify.app/en/developers/docs/smart-contracts/deploying/

Update deploying smart contracts developer doc

---

src/content/contributing/translation-program/index.md

Added a section detailing the Translation Program mission and vision.
Added a section linking to the blog posts on the EF blog.
Preview deploy: https://deploy-preview-4046--ethereumorg.netlify.app/en/contributing/translation-program/#mission-and-vision
#4036

Add Translation Program mission and vision section

---

src/content/community/index.md

No Longer In to The Business :  VeriLedger
Last Post was in 2019
@samajammin Can Check Please

Removed  VeriLedger

---

src/content/developers/docs/oracles/index.md

- added oracle problem
- added high level overview of oracle video
- added further readings
- improvements to readability
Deploy preview - https://deploy-preview-3998--ethereumorg.netlify.app/en/developers/docs/oracles

Update Oracles developer doc 

---

src/intl/en/page-eth2-index.json

Update merge estimate to reflect merge page
None

Update merge estimate to reflect merge page

---

src/pages/eth2/get-involved/index.js

Changes Lodestar back to `isProductionReady: false`

Patch to update Lodestar status

---

src/content/developers/docs/ethereum-stack/index.md

Minor updates to (hopefully) improve legibility.
None

Update Ethereum stack developer doc

---

src/content/translations/es/developers/docs/storage/index.md
src/content/translations/fr/developers/docs/storage/index.md
src/content/translations/hu/developers/docs/storage/index.md
src/content/translations/it/developers/docs/storage/index.md
src/content/translations/pl/developers/docs/storage/index.md
src/content/translations/ro/developers/docs/storage/index.md
src/content/translations/zh/developers/docs/storage/index.md

Removes 3box from storage just to bring the translated storage pages in line with the English page.

Remove 3box from storage page

---

src/content/developers/docs/apis/backend/index.md

Add Tatum platform to backend API developer docs

---

src/content/community/grants/index.md

Have Added mStable In The List of Grants.
I recently get to know that mStable is also having their grants Program.
The Grant Program is Active. I Confirmed.
@wackerow @minimalsm  Please take a Look.

Add mStable to list of grant providers

---

src/content/developers/docs/oracles/index.md

Adds samczsun's 'so you want to use a price oracle' article
None

Add article to Oracle developer docs

---

src/components/RandomAppList.js
src/intl/en/page-dapps.json

Changed tags that are not available for any language to the available english language
https://github.com/ethereum/ethereum-org-website/issues/3976

Updated description tags for the dapps to available english tags

---

src/content/community/grants/index.md

Small Imrovement By Removing Comma

Fix grammar on grants page

---

src/content/community/index.md

Changed github typo to GitHub
@wackerow Take a look Please

Fix typo (github>GitHub)

---

src/content/developers/tutorials/interact-with-other-contracts-from-solidity/index.md

Reported by a user in discord https://discord.com/channels/714888181740339261/885883808392572963/893173724075933776

Fix typo on interacting with other smart contracts tutorial

---

src/content/developers/docs/consensus-mechanisms/pow/index.md

Deploy preview - https://deploy-preview-3999--ethereumorg.netlify.app/en/developers/docs/consensus-mechanisms/pow/

Update proof-of-work developer doc 

---

src/content/contributing/translation-program/content-versions/index.md

Update content versions page in accordance with our new content buckets system

Update content versions page

---

src/content/privacy-policy/index.md

Fix punctuation (space)
Added required spaces for words on line number 63 and 64

Fix punctuation in privacy policy

---

src/content/contributing/translation-program/index.md

Update Translation Program stats to reflect the current status.
Specifically, the number of translators and number of translated words have been updated.
#4359

Update Translation Program stats

---

src/content/developers/docs/smart-contracts/anatomy/index.md

Typo in comment
Fix typo on line number 179

Fix typo in smart contract anatomy developer doc

---

src/content/developers/tutorials/monitoring-geth-with-influxdb-and-grafana/index.md

Previously directed here: 
https://ethereum.org/en/404/
https://ethereum.org/grafana.com/

Add missing "www." in grafana link in tutorial

---

src/content/foundation/index.md

Reframed a sentence
Sentence correction done on line number 14 to match the context, perhaps this could be even more re-framed

Reword a complex sentence on EF page

---

src/content/defi/index.md

Add DefiLlama to DeFi page

---

src/content/developers/tutorials/erc20-annotated-code/index.md

Fix typo in ERC20 annotated code tutorial

---

src/content/nft/index.md

Fix typos and punctuations in nft doc
Corrections for typos and punctuations on line number 347, 351, 371 and 411

Fix typos and punctuations on NFT learn page

---

src/content/defi/index.md

Fix typos in defi doc
Corrected words on line number 318, 325 and 327

Fix typos in DeFi learn page

---

src/content/developers/tutorials/how-to-use-echidna-to-test-smart-contracts/index.md

Fix typos in tutorials doc
Corrected spellings for few words

Fix typos in using echidna tutorial

---

src/content/cookie-policy/index.md

Fix punctuation in cookie-policy doc
Removed a space for a word on line number 40

Fix typo in cookie policy

---

src/content/deprecated-software/index.md

Typo in deprecated software document
Corrected a word on line number 149

Fix typo in deprecated software doc

---

src/content/developers/docs/gas/index.md
src/content/developers/docs/nodes-and-clients/index.md
src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Minor updates where the sentences were incomplete or grammar needed updating.

Minor grammar corrections to developer docs

---

src/content/deprecated-software/index.md

Word replacement
Replaced a word that matches context on line number 268, this must be possessive pronoun isn't it ?

Word replacement in deprecated software doc

---

src/content/governance/index.md

Fix typo
Typo in line number 18, this could be some sort of 'selector' so changes may affect somewhere !

Fix typo in governance learn page

---

src/content/learn/index.md

Fix typo
fix typo on line number 140, hopefully this change doesn't impact anywhere else

Fix typo in learn doc

---

src/content/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md

Changed "there is no floats" to "there are no floats in Solidity"

[Bugfix] ERC20 Grammar Fix

---

src/content/developers/docs/programming-languages/dart/index.md

Quick video on the basics of integrating MetaMask into Flutter applications. Not a lot of support out there so this is a good start for those who want to start with wallet integration.
Little to no support in the Flutter/Dart x Blockchain space.

Ethereum for Dart Developers: MetaMask integration in Flutter applications
