- src/content/developers/docs/networks/index.md
> Fix typo in networks developer docs

- src/content/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
> Grammar fixes for erc20 tutorial

- src/content/developers/docs/storage/index.md
Fixed typo
Correction done on line number 51
> Fix typo in storage developer docs

- src/content/deprecated-software/index.md
Mention this is a community curated list that may not be up to date (similar to grants page: https://ethereum.org/en/community/grants/)
None
> Add mention of community curation

- src/content/community/index.md
Removes an event added to wrong place on community page 
#4291
> Remove metamask weekend event from community page

- src/content/community/index.md
Adding 2 links to the community page
- Main website https://www.useweb3.xyz/
- Jobs https://www.useweb3.xyz/jobs
> Add useWeb3 to community page

- src/content/developers/docs/scaling/layer-2-rollups/index.md
Just adding:
Polynya's posts on Rollups and Volitions
Canti's post on Rollups
> Adding Polynya and Canti's posts

- src/components/StatsBoxGrid.js
Light contribution to increase accessibility
I took a look at the differents colors from `theme.js`
I choosed `homeBoxPurple`, to have the option to switch from darkmode to lightmode too.
->_`/src/components/StatsBoxGrid.js`_
```js 
const ButtonToggle = styled(Button)`
${({ active, theme }) =>
active &&
`
background-color: ${theme.colors.homeBoxPurple};
opacity: 1;
`}
`
```
[![Image from Gyazo](https://i.gyazo.com/e80b5b36f22e9b8a1d1918569529f136.gif)](https://gyazo.com/e80b5b36f22e9b8a1d1918569529f136)
Contrast 10.45 in lightmode
Contrast 14.13 in darkmode
#4426
> Color update to increase accessibility [Fix #4426]

- src/content/developers/tutorials/how-to-mint-an-nft/index.md
Updated the text and the gif to reflect the new Pinata UI.
> Update NFT tutorial to reflect new Pinata UI

- src/content/nft/index.md
Adds a title attribute to the iframe element with the video title. Allows screen readers to identify that the iframe content is a video.
```
title="YouTube video titled What Are NFTs and How Can They Be Used in Decentralized Finance? DEFI Explained"
```
> Add title attribute to iframe (a11y)

- src/content/developers/docs/data-and-analytics/index.md
Fixed punctuation
Removed a space for word on line number 12
> Fix punctuation in data-and-analytics page

- gatsby-node.js
- src/content/about/index.md
- src/content/about/product-designer/index.md
- src/templates/job.js
> Product designer

- src/components/StablecoinAccordion.js
Fix external link to MakerDAO in Stablecoins section.
[Resolves #4453 ]
> Fix external link to MakerDAO in Stablecoins section

- src/data/eth2-bounty-hunters.csv
Add 2850 bounty to ItsUnixIKnowThis for vulnerability report.
> Add 2850 bounty to ItsUnixIKnowThis

- src/content/whitepaper/index.md
Added missing verb in the white paper.
> Fix grammar in Whitepaper

- src/data/community-events.json
Added the ZK Hack event details to the community events json file in src/data
> Add ZK Hack to events #4497

- src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
> Uniswap V2 tutorial: fix an error (16*16 = 256, not 1024)

- src/content/developers/docs/nodes-and-clients/index.md
Add info on OE being deprecated
> Nodes and clients developer doc: adds note about OpenEthereum being deprecated 

- src/content/developers/docs/intro-to-ethereum/index.md
Now I think it make sense that Ether and ETH are same
https://github.com/ethereum/ethereum-org-website/issues/4509
> Intro to Ethereum developer docs: explicitly state ether === ETH

- src/content/developers/tutorials/how-to-mint-an-nft/index.md
Corrected the wordings in the developer tutorials
https://github.com/ethereum/ethereum-org-website/issues/4176
> Improve wording in how to mint an NFT tutorial

- src/pages-conditional/eth.js
This PR adds links to More on Tokens and their uses.
Fixes #4544
> Add links to "More on Tokens and their uses"

- src/data/eth2-articles.js
Add latest ETH2  articles from Ben Edgington and Danny Ryan
#3632
> Update ETH2 articles 

- src/content/developers/docs/nodes-and-clients/index.md
> Fix typo in nodes and clients docs

- src/components/Layout.js
- src/components/UpgradeBannerNotification.js
- src/content/history/index.md
- Adds Arrow Glacier upgrade to `history` page
- Updates `UpgradeBannerNotification` and adds banner to homepage for all languages
Note, this will not be translated in time for the upgrade, but chose to add to all languages to at least allow all users to be notified in some way, even if it's only in English. Can change if others disagree with this approach. 
none filed
> Add Arrow Glacier to history with banner notification

- src/data/externalTutorials.json
Added a tutorial involving events in solidity, and a video too!
> added events blog and video

- src/content/developers/tutorials/erc-721-vyper-annotated-code/index.md
Rectified typos and duplication in sentences
> Fix typos in erc-721-vyper-annotated-code tutorial

- src/content/community/index.md
Added https://web3.career to the community page (Ethereum jobs)
> Add Web3.Career job board to community page

- src/content/deprecated-software/index.md
- src/content/developers/docs/development-networks/index.md
- src/content/developers/docs/nodes-and-clients/index.md
- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
- src/content/developers/docs/programming-languages/rust/index.md
- src/content/developers/tutorials/run-node-raspberry-pi/index.md
This PR adds OpenEthereum to the deprecated software page.
#4530
> Add OpenEthereum to /deprecated-software [Fixes #4530]

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Added details about Ankr services.
> Add Ankr to nodes as a service

- src/styles/layout.css
- src/templates/eth2.js
- src/templates/use-cases.js
- Update h2 and h3 style for eth2 and use-cases pages to add a top margin when scroll into them
- Update layout style to allow smooth scroll across the application when using anchors
- #4548 
- #4547
> Update header anchors top margin on scroll [Fixes #4548 and #4547]

- src/content/developers/docs/standards/tokens/erc-721/index.md
Added two NFT projects, CryptoPunks and Bored Ape Yacht Club.
**The first could not be missing!**
> Add Bored Ape Yacht Club to ERC-721 developer docs

- src/content/contributing/translation-program/index.md
Update the number of words the community has translated in 2021 in the stats section.
> Update number of translated words 2021

- src/components/MeetupList.js
We have setup Web3 Together about a month ago. Our vision is to bring people to be involved in blockchain technology development.
Facebook: https://www.facebook.com/Web3Together
Discussions: https://github.com/web3together/web3together/discussions
Twitter: https://twitter.com/web3together
> Add Web3 Together in Meetup list

- src/content/cookie-policy/index.md
> Fix typo in cookie-policy doc

- src/content/deprecated-software/index.md
> Fix typos in deprecated-software doc

- docs/contributing/EDITING_MARKDOWN.md
> Update editing_markdown documentation

- src/pages/developers/tutorials.js
Switch from lodash some to array.some for tutorials
> Switch from lodash some to array.some for tutorials

- src/content/translations/zh/developers/docs/accounts/index.md
- src/content/translations/zh/developers/docs/blocks/index.md
- src/content/translations/zh/developers/docs/evm/index.md
- src/content/translations/zh/developers/docs/gas/index.md
- src/content/translations/zh/developers/docs/nodes-and-clients/index.md
- src/content/translations/zh/developers/docs/transactions/index.md
- src/content/translations/zh/developers/tutorials/deploying-your-first-smart-contract/index.md
- src/content/translations/zh/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/zh/developers/tutorials/how-to-use-slither-to-find-smart-contract-bugs/index.md
- src/content/translations/zh/developers/tutorials/logging-events-smart-contracts/index.md
- src/content/translations/zh/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
- src/content/translations/zh/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
- src/content/translations/zh/developers/tutorials/using-websockets/index.md
- src/content/translations/zh/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
Fixes: All of the images on the Chinese language version of developer docs and tutorials were brokenly due to fetching from the wrong path.
#2585
> Fix broken image paths (Chinese developer docs and tutorials)

- src/content/developers/docs/consensus-mechanisms/pos/index.md
i have included history of proof of stake on btc talk.com and bitcoin magazine article written by vitalik.
> Add bitcoin magazine article to proof-of-stake developer doc

- src/content/developers/docs/intro-to-ethereum/index.md
> Changed the word summarise to summarize.

- src/components/MeetupList.js
- src/data/community-events.json
Small fix to ETHDubai conference date. Also add link to meetup.
> fix: ethdubai new dates, add meetup too

- gatsby-node.js
Remove force on redirects
None
> Remove force on redirects

- gatsby-config.js
Remove redirect from gatsby-plugin-intl
None
> Remove redirect from gatsby-plugin-intl

- gatsby-config.js
Reverts ethereum/ethereum-org-website#4701
> Revert "Remove redirect from gatsby-plugin-intl"

- gatsby-node.js
Reverts ethereum/ethereum-org-website#4700
> Revert "Remove force on redirects"

- redirects.json
> Add /eth2 redirect

- src/content/developers/docs/dapps/index.md
- src/content/developers/docs/ethereum-stack/index.md
- src/content/developers/docs/web2-vs-web3/index.md
> Add Architecture of a Web 3.0 application article

- src/components/Callout.js
- src/content/community/online/index.md
- src/templates/static.js
Added DAO callout for /community/online page
Fixes: https://github.com/ethereum/ethereum-org-website/issues/4713
> Add DAO card information in community/online.md 

- src/components/DeveloperDocsLinks.js
Add keys to list renders
None but should fix some console errors.
> Add keys to list renders

- src/content/community/get-involved/index.md
Received feedback on Discord to add this - seems like a reasonable idea!
None
> Add EF job listings

- src/content/community/get-involved/index.md
This PR was approved before https://github.com/ethereum/ethereum-org-website/pull/4602#event-5698742769 but I assume it disappeared due changes on community page
> Add Web3.Career job board to get-involved page

- src/content/developers/docs/apis/backend/index.md
Add Figment to the list of Ethereum APIs following alphabetical order.
> Add Figment to the list of Ethereum APIs

- src/content/developers/docs/scaling/index.md
This PR adds a link to A rollup-centric ethereum roadmap, which is mentioned at the end of the video from the `More of a visual learner` section
> update further reading to include A rollup-centric ethereum roadmap

- src/data/community-meetups.json
Added Calgary meetup ground to meetups list
> Add Calgary meetup to meetups list

- src/content/contributing/translation-program/translation-guide/index.md
Add a section about adding content in other languages than English to the website.
Update the Discord invite link and add the translation program email address to the 'Get in touch' section.
> Update translation guide

- src/content/developers/tutorials/calling-a-smart-contract-from-javascript/index.md
> Fix grammar in calling-a-smart-contract-from-javascript tutorial

- package.json
Replace two instances of https://github.com/diglos/pi-gen with https://github.com/diglos/ethereumonarm
> Updating Ethereum-on-ARM Repo URL

- src/pages/index.js
temporary measure to prevent homepage bug on dev builds
> Remove StatsBoxGrid

- package.json
- src/data/translations.json
- yarn.lock
***
- Remove `useLegacyHomepage` flag from new languages (#4794) @wackerow
***
Thank you @corwintines and @wackerow for the contributions! :trophy:
***
> Deploy v3.2.1

- src/content/community/support/index.md
Adds MyEtherWallet's support link
N/A
> Add myetherwallet support on supported wallets

- src/content/community/online/index.md
- fix dublicate link in `community/online/`
> doc:fix duplicate link on online community page

- src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
> Fix punctuation in getting-started-with-ethereum tutorial

- src/content/contributing/translation-program/index.md
Update the number of translators that have contributed to the Translation Program.
> Update number of translators

- src/content/governance/index.md
Add Vitalik's governance articles as recommended reading to the governance page
> Add Vitalik's governance articles to Further Reading

- src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/pl/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
Removes usage of a foreign asterisk causing issues with markdown when uploaded to/exported from crowdin. Some other light polishes. 
- Updates English, Polish, and Romanian instances
- Chinese simplified updates in PR #4852 already include these adjustments
> Syntax clean-up on tutorial

- src/content/translations/id/community/grants/index.md
- src/content/translations/id/contributing/translation-program/index.md
- src/content/translations/id/contributing/translation-program/translation-guide/index.md
- src/content/translations/id/dao/index.md
- src/content/translations/id/defi/index.md
- src/content/translations/id/governance/index.md
- src/content/translations/id/nft/index.md
- src/intl/id/template-usecase.json
Updates Indonesian (`id`) "Use Cases" content bucket with latest from Crowdin.
> Indonesian: Use Cases

- src/content/translations/id/contributing/translation-program/index.md
- src/content/translations/id/contributing/translation-program/translation-guide/index.md
- src/content/translations/id/nft/index.md
Fixes broken images on translation-program and translation-guide
None
> Fix indonesian broken images

- src/content/translations/sl/community/grants/index.md
- src/content/translations/sl/contributing/translation-program/index.md
- src/content/translations/sl/contributing/translation-program/translation-guide/index.md
- src/content/translations/sl/dao/index.md
- src/content/translations/sl/defi/index.md
- src/content/translations/sl/governance/index.md
- src/content/translations/sl/nft/index.md
Updates Slovenian (`sl`) Use Cases content with latest from Crowdin.
> Slovenian: Use Cases

- src/content/developers/docs/consensus-mechanisms/pos/index.md
> Add PoS reading links

- src/components/ActionCard.js
- src/components/StablecoinAccordion.js
- src/components/StatsBoxGrid.js
- src/hooks/useActiveHash.js
- src/pages/community.js
- src/pages/eth2/get-involved/index.js
- src/pages/get-eth.js
- src/pages/stablecoins.js
- src/templates/static.js
- src/templates/tutorial.js
- src/templates/use-cases.js
Fixed different React warnings we get while running in develop mode.
```
/eth/ethereum-org-website/src/components/ActionCard.js
3:23  warning  'getImage' is defined but never used  no-unused-vars
/eth/ethereum-org-website/src/components/Morpher.js
152:6  warning  React Hook useEffect has missing dependencies: 'morphTimeout', 'morpher', 'state.text', and 'state.words'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
/eth/ethereum-org-website/src/components/StablecoinAccordion.js
144:7  warning  'InfoTitle' is assigned a value but never used  no-unused-vars
/eth/ethereum-org-website/src/components/StatsBoxGrid.js
200:11  warning  No duplicate props allowed
react/jsx-no-duplicate-props
424:6   warning  React Hook useEffect has missing dependencies: …
```
> Fix warnings in dev mode

- src/data/community-events.json
- Add new events from **ethglobal.medium.com** article
#4859
> Add new events from ethglobal [Fixes #4859]

- docs/contributing/EDITING_MARKDOWN.md
> docs: fix a typo in EDITING_MARKDOWN.md

- src/intl/tr/common.json
typo should be Norveççe instead of Norveçce
> fix(typo): Norveçce

- src/content/developers/docs/consensus-mechanisms/index.md
Slight edit to avoid explaining consensus as a voting, which leads to incorrect intuition.
> Update consensus mechanisms developer doc intro

- src/content/developers/docs/ides/index.md
> Add replit to IDEs

- src/components/Modal.js
- src/pages/developers/tutorials.js
Centers modal, and prevents background scrolling
Fixes: https://github.com/ethereum/ethereum-org-website/issues/3790
> Add tutorial modal unwanted scrolling

- src/content/developers/docs/scaling/sidechains/index.md
> xDai is Now Gnosis Chain.md

- src/content/developers/docs/ides/index.md
Attempt to clarify the description of IDEs & how they are the same w/ Ethereum development.
#4883
> Clarify IDE intro

- src/content/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md
Remove extraneous word & fix links
Good reminder to check out our style guide for how to create internal links 😄 
https://ethereum.org/en/contributing/style-guide/#internal-links
None
> Fix typos in merkle proof tutorial

- src/components/Nav/index.js
- src/content/community/language-resources/index.md
- src/intl/en/common.json
- src/intl/en/page-languages.json
- src/pages/languages.js
Creates a page for non-English community suggested resources
None
https://ethereumorgwebsitedev01-addlangresourcespage.gtsb.io/en/community/language-resources
> Create lang-resources page

- src/intl/en/page-contributing-translation-program-acknowledgements.json
Add option of using alias to claim the translator certificate, for translators who would prefer to stay anonymous.
> Add option of using alias for certificate

- src/components/ButtonLink.js
- Allow text to wrap in ButtonLink to avoid overflow and horizontal scroll in mobile 
None
> Fix UI bugs on some versions of new homepage

- src/data/community-meetups.json
Add https://ethereum-jkt.github.io/ (Eth Jakarta) to the list.
n/a
> Add Ethereum Jakarta

- src/intl/en/page-eth2-get-involved-bug-bounty.json
Removed Altair multiplier for "eth2 bug bounty" page
> Removed Altair multiplier for "eth2 bug bounty" page

- src/content/contributing/translation-program/index.md
Add a section and some details about office hours for translators to the translation program page.
> Add section about office hours to TP page

- src/content/translations/id/developers/docs/mev/index.md
- src/content/translations/id/developers/docs/oracles/index.md
- src/content/translations/id/developers/docs/scaling/index.md
- src/content/translations/id/developers/docs/scaling/layer-2-rollups/index.md
- src/content/translations/id/developers/docs/scaling/plasma/index.md
- src/content/translations/id/developers/docs/scaling/sidechains/index.md
- src/content/translations/id/developers/docs/scaling/state-channels/index.md
- src/content/translations/id/developers/docs/scaling/validium/index.md
- src/content/translations/id/developers/docs/standards/index.md
- src/content/translations/id/developers/docs/standards/tokens/erc-20/index.md
- src/content/translations/id/developers/docs/standards/tokens/erc-721/index.md
- src/content/translations/id/developers/docs/standards/tokens/erc-777/index.md
- src/content/translations/id/developers/docs/standards/tokens/index.md
Updates Indonesian (id) "Docs - Advanced" content with latest from Crowdin
> Indonesian: Docs - Advanced

- src/content/translations/id/developers/docs/apis/backend/index.md
- src/content/translations/id/developers/docs/apis/javascript/index.md
- src/content/translations/id/developers/docs/apis/json-rpc/index.md
- src/content/translations/id/developers/docs/data-and-analytics/block-explorers/index.md
- src/content/translations/id/developers/docs/data-and-analytics/index.md
- src/content/translations/id/developers/docs/development-networks/index.md
- src/content/translations/id/developers/docs/ethereum-stack/index.md
- src/content/translations/id/developers/docs/frameworks/index.md
- src/content/translations/id/developers/docs/ides/index.md
- src/content/translations/id/developers/docs/programming-languages/delphi/index.md
- src/content/translations/id/developers/docs/programming-languages/dot-net/index.md
- src/content/translations/id/developers/docs/programming-languages/golang/index.md
- src/content/translations/id/developers/docs/programming-languages/index.md
- src/content/translations/id/developers/docs/programming-languages/java/index.md
- src/content/translations/id/developers/docs/programming-languages/javascript/index.md
- src/content/translations/id/developers/docs/programming-languages/python/index.md
- src/content/translations/id/developers/docs/programming-languages/rust/index.md
- src/content/translations/id/developers/docs/smart-contracts/anatomy/index.md
- src/content/translations/id/developers/docs/smart-contracts/compiling/index.md
- src/content/translations/id/developers/docs/smart-contracts/composability/index.md
- src/content/translations/id/developers/docs/smart-contracts/deploying/index.md
- src/content/translations/id/developers/docs/smart-contracts/index.md
- src/content/translations/id/developers/docs/smart-contracts/languages/index.md
- src/content/translations/id/developers/docs/smart-contracts/libraries/index.md
- src/content/translations/id/developers/docs/smart-contracts/security/index.md
- src/content/translations/id/developers/docs/smart-contracts/testing/index.md
- src/content/translations/id/developers/docs/storage/index.md
Updates Indonesian (id) "Docs - Tech Stack" content with latest from Crowdin
> Indonesian: Docs - Tech Stack

- src/components/Layout.js
- src/styles/layout.css
- src/templates/docs.js
- src/templates/eth2.js
- src/templates/tutorial.js
- src/templates/use-cases.js
- src/theme.js
- Added scroll-margin-top to headers
- Added a hook in for when a page is loaded with a anchor tag and scroll to that anchor
fixes: https://github.com/ethereum/ethereum-org-website/issues/4793
> Bug: H3 ::before pseudo-element is preventing click interation with the elements above

- src/content/developers/tutorials/learn-foundational-ethereum-topics-with-sql/index.md
Adding word to improve readability.
> Tutorial copy adjustment

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
SettleMint is a popular node as a service platform. Check it out! -> https://console.settlemint.com/ 
This PR proposes to add it to the popular node services list. 
Added SettleMint (link to platform, link to docs) along with its various features in the list of popular node services.
> Add SettleMint to popular node services list

- src/content/developers/docs/mev/index.md
Grammar issue in the [MEV article](https://ethereum.org/en/developers/docs/mev/) 
I made a change in line 36 in the Flashbots section:
Flashbots is **a** independent project -> Flashbots is **an** independent project
> Fix grammar in MEV developer doc

- src/content/developers/docs/networks/index.md
Add Chainlist to Networks resources.
None
> Add Chainlist

- src/content/community/get-involved/index.md
- src/content/community/online/index.md
Fixes dead links to the Ethereum Cat Herders discord
None, private DM
> Fix broken ECH link

- src/content/developers/docs/dapps/index.md
Was moved from https://github.com/One-Click-Dapp/one-click-dApp to https://github.com/oneclickdapp/oneclickdapp-v1
> Updated URL to Oneclickdapp github

- redirects.json
`eth2-rebrand <- redirects`
Updates `redirects.json` with new paths for eth2 rebrand
> Update eth2 redirects

- src/content/security/index.md
Added section about Eth2 token scams to scams page
> Add content on “Eth2 scams”

- src/content/history/index.md
- src/content/translations/id/history/index.md
- src/content/translations/pl/history/index.md
- src/content/translations/zh/history/index.md
- src/pages/upgrades/get-involved/bug-bounty.js
Update consensus spec GitHub links
> Update consensus spec GitHub links

- src/content/developers/docs/networks/index.md
some of the faucets below (sometimes) do not work & this one also supports L2s
> Add FaucETH

- src/components/ExpandableCard.js
- Update mobile display for expandable cards to break on small screens
- Update style for More/Less link to not break the word regardless of the width
#5083
> Update style for expandable cards [Fixes #5083]

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
> Improve word choice on run a node developer doc

- src/content/developers/docs/networks/index.md
Added  more testnet faucets
Fixes : #5090 
Added 3 more test faucets in network docs
> Added testnet faucets

- src/content/security/index.md
- Add information around Airdrop scams to the security and scams page
> Add "Airdrop Scams" to security and scams page

- src/content/contributing/translation-program/content-versions/index.md
Updates our content versions with our new content buckets
None
> Update content versions 

- src/content/community/events/index.md
- src/templates/static.js
- Add sidebar to events page
- Hide edit page button
[Discord discussion](https://discord.com/channels/714888181740339261/784460943966863380/930599964919361687)
> Add sidebar to Ethereum events page

- src/components/TranslationBanner.js
- src/components/WalletCompare.js
- src/content/contributing/translation-program/index.md
- src/content/translations/id/about/index.md
- src/content/translations/id/enterprise/index.md
- src/content/translations/id/glossary/index.md
- src/content/translations/id/nft/index.md
- src/content/translations/ja/contributing/translation-program/index.md
- src/content/translations/sl/contributing/translation-program/index.md
- src/content/translations/sl/nft/index.md
- src/content/translations/zh/contributing/translation-program/index.md
- src/content/translations/zh/nft/index.md
- src/pages/contributing/translation-program/contributors.js
- src/pages/index.js
- src/pages/languages.js
- Removes explicit English path from links to ethereum.org/contributing
> Remove instances of /en/ path from links to /contributing/

- src/content/translations/es/developers/docs/dapps/index.md
- src/content/translations/fr/developers/docs/dapps/index.md
- src/content/translations/hu/developers/docs/dapps/index.md
- src/content/translations/id/developers/docs/dapps/index.md
- src/content/translations/it/developers/docs/dapps/index.md
- src/content/translations/pl/developers/docs/dapps/index.md
- src/content/translations/ro/developers/docs/dapps/index.md
- src/content/translations/zh/developers/docs/dapps/index.md
- Fixes oneclickdapp link in non-English languages
Same as #5076
> Update oneclickdapp link in non-English languages

- src/components/EthExchanges.js
- src/intl/en/page-get-eth.json
- src/pages/get-eth.js
- Adds articles on get-eth to be translated
- Translate the EthExchanges placeholder string - "Type where you live" - that was previously missed
> Setup useEthereum bucket for translations

- src/content/contributing/index.md
Adds a section to contributing explaining that we only accept original work or work that users have explicit permission to use.
None
> Add plagiarism blurb to contributing page

- src/components/Contributors.js
- src/content/contributing/index.md
Add contributor count to thank you message:
None, just found myself wanting to check the total number of contributors 😄
> Display contributor count

- src/content/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
- src/content/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md
- src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/pl/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
- src/content/translations/ro/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
- src/content/translations/zh/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
- src/content/translations/zh/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md
- src/content/translations/zh/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
Fixing some more broken links
None
> Fix broken external links

- src/content/glossary/index.md
- Added "Base fee" in the glossary section
- Provided term's definition and link for better-detailed understanding
> Add base fee to glossary

- src/content/contributing/index.md
https://ethereum.org/en/contributing/style-guide/#american-english
None
> Fix typo: artefact -> artifact

- src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
Tellor recently upgraded its contracts which required updates to testnet addresses as well as functionality pertaining to the example posted in the tutorial. Changes were made to reflect these updates.
> Update Tellor oracle tutorial

- src/content/community/grants/index.md
- src/content/translations/id/community/grants/index.md
- src/content/translations/ja/community/grants/index.md
- src/content/translations/sl/community/grants/index.md
- src/content/translations/zh/community/grants/index.md
> Fix Uniswap grants link

- redirects.json
Add eth2 homepage redirect. We handled it for when no lang path was specified, but not if there was a lang path.
#5181
> Add eth2 homepage redirect [Fixes #5181]

- redirects.json
Whoops, incorrect addition in #5182 - should be /upgrades, not /eth2 🤦‍♂️ 
#5181
> Update homepage eth2 redirect [Fixes #5181]

- src/content/glossary/index.md
- src/content/translations/es/developers/docs/smart-contracts/languages/index.md
- src/content/translations/fr/developers/docs/smart-contracts/languages/index.md
- src/content/translations/hu/developers/docs/smart-contracts/languages/index.md
- src/content/translations/id/developers/docs/programming-languages/javascript/index.md
- src/content/translations/id/upgrades/shard-chains/index.md
- src/content/translations/pl/developers/docs/smart-contracts/languages/index.md
- src/content/translations/pt-br/upgrades/shard-chains/index.md
- src/content/translations/ro/developers/docs/smart-contracts/languages/index.md
- src/content/translations/zh/developers/docs/programming-languages/javascript/index.md
- src/content/translations/zh/developers/tutorials/secure-development-workflow/index.md
Fixes several links that are causing 404s 
None
> Fix 404 links

- src/intl/en/page-upgrades-index.json
- src/pages/upgrades/index.js
Add link to Eth2 renaming blog post:
https://blog.ethereum.org/2022/01/24/the-great-eth2-renaming/
#4915
> Add link to Eth2 renaming blog post

- src/content/translations/es/developers/docs/smart-contracts/index.md
- src/content/translations/es/developers/docs/smart-contracts/languages/index.md
- src/content/translations/es/developers/docs/standards/tokens/erc-20/index.md
- src/content/translations/es/developers/docs/standards/tokens/erc-721/index.md
this PR fixes #4972 following the recommendation
> Fix incorrectly translated code blocks in Spanish [Fixes #4972]

- src/content/translations/zh/developers/docs/apis/json-rpc/index.md
Fixed typo.
```
Github -> GitHub
```
> Fix typo in json-rpc/index.md

- src/content/security/index.md
Update content in "Eth2" scam section on security page to talk about staked ETH derivative tokens.
> Update scam content on security page

- src/content/learn/index.md
Add new article from @jjmstark 
https://stark.mirror.xyz/q3OnsK7mvfGtTQ72nfoxLyEV5lfYOqUfJIoKBx7BG1I
Should we remove the 2020 link? Or add more previous years?
- 2020: https://stark.mirror.xyz/ywsx9-AsGR83LOyRUdDx2NpfaLEQdS0lKxHpHYwvzTI
- 2019: https://stark.mirror.xyz/32hW-yLR6riSmzQuuDDMX6XZhSh-k-RB7w5mvW0Vy9U
- 2018: https://stark.mirror.xyz/w5DBtrkxEl2lI3P1RxmkVhqIhrp19g5zqU-RcZMR3ZQ
None
> Add new Year in Ethereum

- src/content/developers/docs/smart-contracts/deploying/index.md
Changed desc and added the link to Tenderly docs page.
> Changed Tenderly description in smart-contracts deploying docs

- src/intl/en/page-run-a-node.json
Fixes smaller grammar error on run-a-node page
https://twitter.com/cobmin/status/1486547255452651522
> Grammar patch

- redirects.json
- src/components/Layout.js
When going to a page without a lang the site gets in a redirect loop and never loads. Added back in redirects removed in https://github.com/ethereum/ethereum-org-website/pull/5097/files to resolve
> Fix redirect bug on page loads without lang

- src/content/governance/index.md
Add end punctuation to Ethereum Governance sentence
[#5248](https://github.com/ethereum/ethereum-org-website/issues/5248)
> Add punctuation [Fixes #5248]

- src/content/security/index.md
Fix plural form of sentence and used semicolon instead of comma
> Fix punctuation on security page

- src/data/externalTutorials.json
Hi! I didn't make an issue on this... but I can if you'd like... This is a dapptools video and article, and a "how to become a blockchain engineer video".
I was wondering a few things:'
1. Do you prefer the written content? Or video and written? Most of my videos come with written content, and vise versa. Let me know what you'd like to see.
2. I have another video on events and logging with brownie, should I add that one too? 
3. Should I make issues for content adds? 
Love the site, let me know!
> added dapptools and career focused tutorials

- src/content/community/grants/index.md
- src/content/translations/id/community/grants/index.md
- src/content/translations/ja/community/grants/index.md
- src/content/translations/sl/community/grants/index.md
- src/content/translations/zh/community/grants/index.md
Changed 'TheGraph' to 'The Graph'. Issue was on src/content/community/grants/index.md.
> Changed 'TheGraph' to 'The Graph' [Fixes #5246]

- src/content/glossary/index.md
Adding missing glossary terms as previously approved (linked related issues).
1. [Zero-knowledge proof #5121](https://github.com/ethereum/ethereum-org-website/issues/5121)
2. [STARK #5120](https://github.com/ethereum/ethereum-org-website/issues/5120)
3. [SNARK #5119](https://github.com/ethereum/ethereum-org-website/issues/5119)
> Glossary: Add Zero-knowledge proof, STARK and SNARK

- src/content/developers/docs/networks/index.md
- src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
- src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
I made an update to rinkeby faucet documentation to include links to rinkebyfaucet.com, I edited the NFT tutorial to include the most up to date links (.com instead of .io), and updated a broken link in the send transaction document. Please let me know if you have any questions!
> Updating Faucet, NFT Tutorial, and Sending Transaction Document

- src/content/enterprise/index.md
> Updates to #enterprise-live-on-mainnet

- src/content/developers/docs/programming-languages/python/index.md
A newly released Python package makes dealing with DeFi testing easier
This is a new Python project providing repeatable deployments and testing for ERC-20, Uniswap-like DEXes in a highly documented package.
> Adding smart-contracts-for-testing Python package

- src/components/UpgradeBannerNotification.js
- Update the message link from `Link More.` to `Read the full announcement.`
- Vertical centre banner content
#5260 #5261
> Update notification link message and vertical align content banner [Fixes #5261 & #5260]

- src/content/developers/docs/nodes-and-clients/client-diversity/index.md
Fixed Broken header-ID on client diversity developer docs
[#5276 ](https://github.com/ethereum/ethereum-org-website/issues/5276)
> fix header id [Fixes #5276]

- src/content/developers/docs/apis/backend/index.md
- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Add watchdata to apis and nodes-as-a-service
> Add watchdata to apis and nodes-as-a-service

- src/content/upgrades/shard-chains/index.md
Didn't have permissions to make changes to #5037 and had to rebase conflicts caused by Eth2 rebrand.
Closes #5037
> Adding sharding account balance clarification

- src/content/glossary/index.md
> Fix glossary typos

- src/content/developers/docs/programming-languages/python/index.md
Updated Smart contracts for testing description to match with the overall aesthetic.
Smart contracts for testing is a new python project providing repeatable deployments and testing for ERC-20, 
Uniswap-like DEXes in a highly documented package.
Its description needs to be italicize to match with the overall aesthetic.
Issue Fix : Smart contracts for testing description should be italicize to match with the overall aesthetic #5295
> Update Smart contracts for testing description to match with the overall aesthetic

- src/content/developers/docs/ethereum-stack/index.md
> Fix typo in Ethereum stack developer docs

- src/content/developers/tutorials/how-to-mint-an-nft/index.md
Correct typo in the "How to Mint an NFT" article
> Correct typo in the "How to Mint an NFT" article

- src/content/developers/tutorials/logging-events-smart-contracts/index.md
Fixed typo in Logging events smart contracts tutorial
> Fix typo in Logging events smart contracts tutorial

- src/content/developers/docs/programming-languages/python/index.md
New Python OSS project: Sign in with Ethereum (siwe)
> Add Sign in with Ethereum to Python developer docs

- src/data/consensus-bounty-hunters.csv
> updating Guido's score

- src/intl/en/common.json
Remove london banner strings from common.js that arent used anymore
> Remove london banner strings from common.js

- src/content/developers/docs/frameworks/index.md
Adds Foundry to list of developer frameworks
Closes #5263
> Add Foundry to dev frameworks [Closes #5263]

- src/content/developers/docs/nodes-and-clients/client-diversity/index.md
I wrote a much more detailed version of our introductory page on client diversity, published on mirror.xyz. This PR adds the link to the list of Further Reading.
if anyone here fancies giving feedback on the article itself that would be most welcome!
> add link to new diversity article

- src/content/contributing/index.md
A couple of minor updates I noticed in #5381
#5381
> Fix contributing page

- src/content/developers/docs/networks/index.md
Add a working Alchemy rinkeby testnet faucet to the networks page on ethereum.org
> add alchemy rinkeby faucet link

- src/components/Footer.js
- src/components/Nav/index.js
- src/content/bridges/index.md
- src/intl/en/common.json
Adds blockchain bridges learn page
None
> Add blockchain bridges

- src/content/community/language-resources/index.md
This change added just one line with a new resource to the Education in Portuguese language.
web3dev is now the largest community here in Brazil focused on web 3 development and we are growing fast. We are doing translations of a lot of content and bringing together Brazilian developers from all over the blockchains.
> ptbr community and content hub added for web 3 developers

- src/content/bridges/index.md
- src/intl/en/common.json
Add more descriptive meta title
None
> Add more descriptive meta title

- src/content/whitepaper/index.md
This PR fixes the whitepaper link to download the pdf.
#5385
> Fix whitepaper link

- src/content/community/language-resources/index.md
Inclusion of Livecoins news website.
> News website BR

- src/content/bridges/index.md
- Add https://blog.li.finance/what-are-blockchain-bridges-and-how-can-we-classify-them-560dc6ec05fa to further reading section on bridges page
> Add li.finance article to further readings for bridges

- src/content/developers/tutorials/hello-world-smart-contract/index.md
This PR adds a new line, to match the output of generated `package.json`
> Fix typo in hello-world-smart-contract tutorial

- src/content/developers/docs/programming-languages/javascript/index.md
> Solidity is not "heavily inspired by JavaScript"

- src/content/translations/es/developers/docs/intro-to-ethereum/index.md
corrección en la traducción de "Cualquiera que pueda solicitar que el código del contrato inteligente se ejecute..." a "Cualquiera puede solicitar que el código del contrato inteligente se ejecute al hacer una solicitud de transacción"
> Fix typo (Spanish intro to Ethereum developer docs)

- src/content/developers/tutorials/hello-world-smart-contract/index.md
- src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
- src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
This PR adds an important security warning message for the `.env` file creation steps. Accidentally committing `.env` file  to a git repo is a mistake. Adding some warning messages, so devs don't forget.
> Add warning to not commit env files

- src/content/translations/es/developers/docs/oracles/index.md
Updated the "Oracles" title to "Oráculos" which is a better Spanish title
> Update oracle title to spanish

- redirects.json
Add redirect from old product designer page
https://github.com/ethereum/ethereum-org-website/pull/5358/
> Add product designer redirect

- src/content/contributing/adding-products/index.md
Update contributing details for Adding Ethereum products
> Fix typo in Adding Ethereum products

- src/content/bridges/index.md
Minor typo fix.
Fix a minor typo.
> Fix grammar in bridges page

- src/content/translations/fr/dao/index.md
- src/content/translations/fr/defi/index.md
- src/content/translations/fr/energy-consumption/index.md
- src/content/translations/fr/governance/index.md
- src/content/translations/fr/nft/index.md
- src/content/translations/fr/security/index.md
- src/intl/fr/template-usecase.json
Updates French (`fr`) **use cases** with latest from Crowdin
> French: Use cases

- src/content/translations/pt-br/dao/index.md
- src/content/translations/pt-br/defi/index.md
- src/content/translations/pt-br/energy-consumption/index.md
- src/content/translations/pt-br/governance/index.md
- src/content/translations/pt-br/nft/index.md
- src/content/translations/pt-br/security/index.md
- src/intl/pt-br/template-usecase.json
Updates Portuguese Brazilian (`pt-br`) **use cases** with latest from Crowdin
> Portuguese Brazilian: Use cases

- src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Deploying to Ropsten can take awhile. Have added text to reflect that.
> Added text to elaborate more on deploying address

- src/content/community/grants/academics-grants-round/index.md
- src/content/community/grants/index.md
- src/intl/en/common.json
Draft grants page
Preview deploy:
https://ethereumorgwebsitedev01-academicsgrantsround.gtsb.io/en/community/grants/academics-grants-round
**Note: we need this page to be live first:** 
https://esp.ethereum.foundation/academics-grants
None
> Create academics-grants-round page

- src/content/eips/index.md
Update Ethereum Improvement Proposals (EIPs) page
> Fix typo on EIPs page

- src/content/developers/tutorials/how-to-use-echidna-to-test-smart-contracts/index.md
> Fix typos in echidna tutorial

- src/content/security/index.md
Update Ethereum security and scam prevention page
> Fix typo on security learn page

- src/content/translations/zh/developers/docs/evm/index.md
modify  page title "以太机" => "以太坊"
> Update title of EVM page (Chinese developer docs)

- src/content/community/grants/academic-grants-round/index.md
- src/content/community/grants/index.md
- src/intl/en/common.json
Updates content: academics to academic.
Preview: https://ethereumorgwebsitedev01-updateacademiccontent.gtsb.io/en/community/grants/academic-grants-round/
> Update academics content

- src/content/community/grants/academic-grants-round/index.md
> Fix academic grant link

- src/components/Footer.js
- Add run-a-node link to footer Use Ethereum section
> add run-a-node page to footer

- src/data/translation-reports/month-data.json
- Update month-data and alltime-data files for translation leaderboard to mark end of February.
> update translation leaderboard data 2022/03/01

- src/content/translations/it/dao/index.md
- src/content/translations/it/defi/index.md
- src/content/translations/it/energy-consumption/index.md
- src/content/translations/it/governance/index.md
- src/content/translations/it/nft/index.md
- src/content/translations/it/security/index.md
- src/intl/it/template-usecase.json
Updates Italian (`it`) **use cases** content with latest from Crowdin
> Italian: Use cases

- src/content/developers/docs/scaling/sidechains/index.md
- Replace POA with Polygon PoS in sidechains page
> Polygon PoS in sidechains

- src/content/translations/ro/dao/index.md
- src/content/translations/ro/defi/index.md
- src/content/translations/ro/energy-consumption/index.md
- src/content/translations/ro/governance/index.md
- src/content/translations/ro/nft/index.md
- src/content/translations/ro/security/index.md
- src/intl/ro/template-usecase.json
Updates Romanian (`ro`) **use cases** content with latest from Crowdin
> Romanian: Use cases

- src/content/translations/id/about/index.md
- src/content/translations/id/enterprise/index.md
- src/content/translations/id/glossary/index.md
- src/content/translations/id/history/index.md
Updates Indonesian (`id`) **learn pages** content with latest from Crowdin
> Indonesian: Learn pages

- src/content/developers/tutorials/how-to-mint-an-nft/index.md
Fix the title of the step to match the actual script filename
> Fix step title to match the actual script filename

- src/content/community/grants/index.md
- Add google doc to grants resources for organizations offering grants
https://github.com/ethereum/ethereum-org-website/issues/5581
> Add google doc to organizations offering grants

- src/components/Layout.js
- Remove banner for altair upgrade
> cleanup altair banner logic

- src/content/translations/fr/developers/docs/web2-vs-web3/index.md
Fix WEB2 ET WEB3 french prevention page
> docs: update french translation for web2-vs-web3

- src/content/glossary/index.md
Added a new glossary term: Mint
> Added Mint glossary term

- src/pages/stablecoins.js
Added more Ethereum-based stablecoins from the top 10 on https://www.coingecko.com/en/categories/stablecoins
I have added 5 stablecoins that are currently in the top 10 on coingecko to stablecoins.js as the list was out of date. 
The issue related to this pull request is 'Update list of stablecoins #5558'
https://github.com/ethereum/ethereum-org-website/issues/5558
> Added updated stablecoins from the current top 10

- src/content/developers/docs/storage/index.md
Adding Filebase to the list of 'Additional Considerations'
> Adding Filebase to 'Additional Considerations'

- src/content/developers/docs/programming-languages/ruby/index.md
- src/data/developer-docs-links.yaml
- src/intl/en/page-developers-docs.json
Creates the page "Ethereum for Ruby Developers."
fix #1116 #1300
> dev/lang: create a ruby page

- src/content/contributing/translation-program/translators-guide/index.md
Fix a couple of typos in the translators guide.
> Fix typos in translators guide

- src/content/developers/docs/mev/index.md
Just some English improvements.
> Fix a grammatical issue and some word choice (MEV developer doc)

- src/content/developers/docs/apis/backend/index.md
Just updating QuickNode links in the Backend API section.
No open issue, just updating links.
> Update quicknode links

- src/content/developers/docs/transactions/index.md
> Update transactions developer doc

- src/content/contributing/translation-program/index.md
- src/content/contributing/translation-program/playbook/index.md
Create a subpage on the Translation Program page with a 'playbook' for starting and managing a translation program.
> Add translation program playbook

- src/content/developers/docs/frameworks/index.md
- src/content/developers/docs/programming-languages/python/index.md
This PR adds the `ape` smart contract development framework to the relevant pages discussed in #5657
fixes: #5657
> Add ape python framework for smart contract dev

- src/data/community-events.json
> Update ETHMiami description

- src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Correction of a misspelled parameter of the mintNFT function
> [Fix] typo in NFT tutorial

- src/components/ButtonLink.js
- src/components/Layout.js
- src/pages/run-a-node.js
- src/utils/scrollIntoView.js
Scroll to the anchor's start position by default, not the end.
Bonus:
- Created a utils function to reuse the code.
Example:
https://ethereumorgwebsitedev01-fixscrollintoview.gtsb.io/en/whitepaper/
> Fix header ids scrolling

- src/components/Link.js
Fixes warnings and improve security on pdf anchor links.
> Fix link warning

- src/pages/upgrades/get-involved/bug-bounty.js
- Created new button styled component to deal with the secondary one (based on other components)
- Main button style add margin-right 
#5616
> Update margin-right for CTA button bug-bounty page [Fixes #5616]

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Updates changes made in #5736 to order products based on date added vs. alphabetically.
None, see policy here: https://ethereum.org/en/contributing/adding-developer-tools/#product-ordering
> Node service order

- src/content/security/index.md
Fixed grammatical errors 
- removed end punctuations in 'common scams' 2nd point 
- rephrased false sense of urgency in 'Giveaway scam'
- added period at the end of social media hack 
https://github.com/ethereum/ethereum-org-website/issues/5759
https://github.com/ethereum/ethereum-org-website/issues/5759
> Fixed grammatical errors (Security learn page)

- src/content/developers/docs/consensus-mechanisms/pow/index.md
changed a sentence in ###proof of work economics 
added the changes regarding miner rewards according to EIP-1559 
https://github.com/ethereum/ethereum-org-website/issues/5760
> Update proof of work transaction fee explanation

- src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
> Fix typo on Uniswap v2 walkthrough

- src/data/community-events.json
Added the HODLerCon event: hodlercon.com
> Add HODlerCon to community events

- src/content/contributing/index.md
Made some changes to contributing page on the website.
issue #5763
> Fix typo on contributing page

- src/content/glossary/index.md
> Fix typo on Glossary page

- src/content/developers/docs/nodes-and-clients/client-diversity/index.md
Since this page was published several new client diversity dashboards have become available, and Dankrad from the EF posted a detailed description of the risks of going through the merge with the majority client.
I have added links to these resources in this PR.
> add links to dashboards and dankrad's article to client diversity page

- src/content/developers/docs/dapps/index.md
Fix incorrect "deployed and on the blockchain" syntax.
> Simplify language on dapps developer doc

- src/content/developers/docs/standards/index.md
Update Ethereum Development Standards page
> Update Ethereum Development Standards page

- src/content/developers/docs/networks/index.md
Adding Alchemy Goerli Faucet. Please let me know if you have any questions!
> Adding Alchemy Goerli Faucet

- src/pages/layer-2.js
A few proposed changes, based largely off feedback here: https://twitter.com/ryancreatescopy/status/1506893580065026051?s=20&t=st3EwiUqCDhF8yYzVCh9qg
- Define L2 right off the bat in a new section at the top
- Re-word existing sections to "How layer 2 works" & "Use layer 2"
- Misc copy updates
#5656
> L2 page tweaks

- src/content/community/grants/index.md
Add grant programs for dYdX and Lido.
#5581
> Add grant programs for dYdX and Lido

- src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
Update Minerstat calculator on the Mining page
Fixes #5801
> Update Minerstat calculator on the Mining page 

- src/content/contributing/translation-program/index.md
Adds a video guide to using Crowdin to the translation program page
None
> Add video guide to using Crowdin

- src/content/community/language-resources/index.md
> Added resources for Japanese language

- .env.example
- src/api/tvl.js
- src/components/StatsBoxGrid.js
- src/lambda/tvl.js
Pulls TVL data from Defi Llama API. https://defillama.com/docs/api
Fixes #3972
> Fix TVL chart

- src/components/OrderedList.js
Create and OrderedList component to be used around the site
> OrderedList compnonent

- src/content/about/index.md
- src/content/translations/id/about/index.md
- src/content/translations/it/about/index.md
- src/content/translations/zh/about/index.md
These links references our old jobs link. Updated to reference the new page.
Link updates were made in #4521
> Fix jobs links

- src/pages/layer-2.js
remove hardcoded values to use l2beat lambda function since it has been deployed
> remove hardcoded values and using l2beat api

- src/content/developers/tutorials/reverse-engineering-a-contract/index.md
- src/content/developers/tutorials/short-abi/index.md
- src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/content/translations/it/developers/tutorials/uniswap-v2-annotated-code/index.md
Adds some missing header ids
#2304
> Add missing header ids

- src/content/contributing/adding-products/index.md
- Adds the find-wallets page explicitly to the adding-products listing criteria
None
> Add find-wallets to adding-products listing criteria

- src/content/developers/docs/development-networks/index.md
Added a punctuation mark at the end of the sentence on line 44 (src/content/developers/docs/development-networks/index.md).
> Punctuation mark added to sentence [dev docs]

- src/content/translations/ca/dao/index.md
- src/content/translations/ca/defi/index.md
- src/content/translations/ca/energy-consumption/index.md
- src/content/translations/ca/governance/index.md
- src/content/translations/ca/nft/index.md
- src/content/translations/ca/security/index.md
- src/intl/ca/template-usecase.json
- Update `Use cases` content bucket translation files for Catalan
> Catalan (ca): update "Use Cases" content bucket translation files 

- src/content/translations/tr/dao/index.md
- src/content/translations/tr/defi/index.md
- src/content/translations/tr/energy-consumption/index.md
- src/content/translations/tr/governance/index.md
- src/content/translations/tr/nft/index.md
- src/content/translations/tr/security/index.md
- src/intl/tr/template-usecase.json
- Update `Use cases` content bucket translation files for Turkish
> Turkish (tr): update "Use Cases" content bucket translation files

- src/content/translations/es/dao/index.md
- src/content/translations/es/defi/index.md
- src/content/translations/es/energy-consumption/index.md
- src/content/translations/es/governance/index.md
- src/content/translations/es/nft/index.md
- src/content/translations/es/security/index.md
- src/intl/es/template-usecase.json
- Update `Use cases` content bucket translation files for Spanish
> Spanish (es): update "Use Cases" content bucket translation files

- src/content/translations/id/dao/index.md
- src/content/translations/id/defi/index.md
- src/content/translations/id/energy-consumption/index.md
- src/content/translations/id/governance/index.md
- src/content/translations/id/nft/index.md
- src/content/translations/id/security/index.md
- src/intl/id/template-usecase.json
- Update `Use cases` content bucket translation files for Indonesian
> Indonesian (id): update "Use Cases" content bucket translation files

- src/content/translations/de/dao/index.md
- src/content/translations/de/defi/index.md
- src/content/translations/de/energy-consumption/index.md
- src/content/translations/de/governance/index.md
- src/content/translations/de/nft/index.md
- src/content/translations/de/security/index.md
- src/intl/de/template-usecase.json
- Update `Use cases` content bucket translation files for German
> German (de): update "Use Cases" content bucket translation files

- src/content/translations/nl/dao/index.md
- src/content/translations/nl/defi/index.md
- src/content/translations/nl/energy-consumption/index.md
- src/content/translations/nl/governance/index.md
- src/content/translations/nl/nft/index.md
- src/content/translations/nl/security/index.md
- src/intl/nl/template-usecase.json
- Update `Use cases content` bucket translation files for Dutch
> Dutch (nl): update "Use Cases" content bucket translation files

- src/components/WalletCompare.js
- Translate message id for wallet tags in WalletCompare component
> Translate title in tags for WalletCompare component

- src/content/dao/index.md
Minor copy improvements to index.md
Improvements on the language of the page:
Members can exit at **_any time_** with their proportionate share of the treasury.
replaces
Members can exit at **_anytime_** with their proportionate share of the treasury.
Any prospective members can submit a proposal to join the DAO, usually **_offering a tribute_** of some value in the form of tokens or work.
replaces
Any prospective members can submit a proposal to join the DAO, usually **_offering tribute_** of some value in the form of tokens or work.
**_Instead, the group_** makes decisions collectively and payments are authorized automatically when votes pass.
replaces
**_Instead the group_** makes decisions collectively and payments are authorized automatically when votes pass.
> Minor copy improvements to DAOs page

- src/data/community-events.json
Add a community event
Add Devcon 2022 into community-events.json
#5982
> Added community event 

- src/content/developers/docs/scaling/validium/index.md
> Removed Loopring from Validium list

- src/components/SharedStyledComponents.js
- src/templates/upgrade.js
- src/templates/use-cases.js
- src/theme.js
Problem: when a heading is focused, the anchor links remain hidden.
This PR addresses fixing how we hide/show them + a small refactor to avoid repeating the styles.
> Fix hidden anchor links on focus

- src/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
EASY FIX
Another typo fix + improving consistency
> Update Tuto The Graph index.md

- src/content/community/get-involved/index.md
Add new job portal link:
https://jobs.lever.co/ethereumfoundation
Keeping old one as there are still some jobs listed there
None
> Update EF jobs link

- src/content/governance/index.md
Add period to intro paragraph
None
> Add period to intro paragraph

- src/content/developers/docs/web2-vs-web3/index.md
> Add link to web3 page

- src/content/developers/docs/scaling/zk-rollups/index.md
> Add link to L2 page

- src/intl/vi/common.json
- src/intl/vi/page-developers-index.json
Updates Vietnamese (vi) translation
> Vietnamese (vi): Update translation

- src/components/ExpandableCard.js
Make expandable links as buttons.
> Expandable cards a11y improvements

- src/pages/layer-2.js
Remove the 3 'the's before the word Ethereum
> Remove the 3 'the's before the word Ethereum

- src/content/web3/index.md
Update reference to earlier tweet.
None but a few folks pointed out this tweet that's earlier than the current one we reference:
https://twitter.com/himgajria/status/1266415636789334016
> Update Twitter reference

- src/content/community/grants/academic-grants-round/index.md
Updates deadline for academic grants to May 8.
> Update academic grants dates

- src/content/contributing/adding-staking-product/index.md
link on live page doesn't work, and I've also included the specific LOC for the algorithm that weights the scores.
> Fix broken link

- src/content/developers/docs/index.md
The previous link gives a 404 so I just updated the link.
> Update link for "Follow these instructions"

- src/intl/en/page-index.json
- Rephrased the description of the 'Level up your upgrade knowledge' card (on the homepage). 
- PR related to [#6030]
> Rephrased the description of Ethereum upgrades on the homepage [Fixes #6030]

- src/content/developers/docs/mev/index.md
closes: https://github.com/ethereum/ethereum-org-website/issues/6032
> Change position of quotation marks on MEV page

- src/content/contributing/index.md
> Update contribution year

- src/pages/layer-2.js
Fix a broken link to share chains page
> Fix broken shard chains link on layer-2 page

- src/content/contributing/design-principles/index.md
> Remove typo on design principles

- src/data/community-events.json
Fixes: 
- A couple events listed are not real ETHGlobal events and never have been, removing as there's been a lot of confusion due to this.
- Updated URLs for ETHGlobal events as well to point to homepages instead of signup pages
- Updated descriptions for ETHGlobal hackathons
Chore:
- Improve overall consistency with country names. Country codes are pretty non-ideal for human consumption, switched all to human-readible country names.
> Update community events list to be more accurate

- src/content/community/support/index.md
Thought this was more descriptive
None
> Update copy on community support page

- src/content/developers/tutorials/how-to-mint-an-nft/index.md
**EASY FIX**
Few typos, improvements and consistency fixes FTW! 😉
> Update on part 2 - Tuto 'How to mint an NFT'

- src/content/translations/zh/developers/tutorials/create-and-deploy-a-defi-app/index.md
- src/content/translations/zh/developers/tutorials/deploying-your-first-smart-contract/index.md
- src/content/translations/zh/developers/tutorials/erc20-annotated-code/index.md
- src/content/translations/zh/developers/tutorials/how-to-implement-an-erc721-market/index.md
- src/content/translations/zh/developers/tutorials/interact-with-other-contracts-from-solidity/index.md
- src/content/translations/zh/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md
- src/content/translations/zh/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md
- src/content/translations/zh/developers/tutorials/run-light-node-geth/index.md
- src/content/translations/zh/developers/tutorials/send-token-etherjs/index.md
- src/content/translations/zh/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/zh/developers/tutorials/uniswap-v2-annotated-code/index.md
- Update Chinese Tutorials 2 content bucket files
> Update: Chinese translation files Tutorials 2

- src/content/translations/zh/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
- src/content/translations/zh/developers/tutorials/calling-a-smart-contract-from-javascript/index.md
- src/content/translations/zh/developers/tutorials/hello-world-smart-contract/index.md
- src/content/translations/zh/developers/tutorials/how-to-mint-an-nft/index.md
- src/content/translations/zh/developers/tutorials/how-to-view-nft-in-metamask/index.md
- src/content/translations/zh/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
- src/content/translations/zh/developers/tutorials/run-node-raspberry-pi/index.md
- src/content/translations/zh/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
- src/content/translations/zh/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
- src/intl/zh/page-developers-tutorials.json
- Update Chinese Tutorials 1 content bucket files
> Update: Chinese translation files Tutorials 1

- src/content/translations/id/developers/tutorials/create-and-deploy-a-defi-app/index.md
- src/content/translations/id/developers/tutorials/deploying-your-first-smart-contract/index.md
- src/content/translations/id/developers/tutorials/erc20-annotated-code/index.md
- src/content/translations/id/developers/tutorials/how-to-implement-an-erc721-market/index.md
- src/content/translations/id/developers/tutorials/interact-with-other-contracts-from-solidity/index.md
- src/content/translations/id/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md
- src/content/translations/id/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md
- src/content/translations/id/developers/tutorials/run-light-node-geth/index.md
- src/content/translations/id/developers/tutorials/send-token-etherjs/index.md
- src/content/translations/id/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/id/developers/tutorials/uniswap-v2-annotated-code/index.md
- Update Indonesian Tutorials 2 content bucket files
> Update: Indonesian translation files Tutorials 2 

- src/content/translations/id/glossary/index.md
> id: Fix typo in glossary/index.md

- src/data/community-events.json
Fixed some dates of upcoming events 📅
As reported by the official events sites, some dates have been changed.
I attach the links here.
Spaghett.ETH : https://spaghett-eth.com/
HackMoney : https://defi.ethglobal.com/
BlockSplit : https://blocksplit.net/
DeFiCon : https://deficon.nyc/
> Fix upcoming events date

- src/components/Nav/index.js
Fixed theme toggle icon mentioned in the issue #6078.
> fix: theme-toggler icon

- src/content/translations/fr/developers/docs/apis/backend/index.md
- src/content/translations/fr/developers/docs/apis/javascript/index.md
- src/content/translations/fr/developers/docs/apis/json-rpc/index.md
- src/content/translations/fr/developers/docs/data-and-analytics/block-explorers/index.md
- src/content/translations/fr/developers/docs/data-and-analytics/index.md
- src/content/translations/fr/developers/docs/development-networks/index.md
- src/content/translations/fr/developers/docs/ethereum-stack/index.md
- src/content/translations/fr/developers/docs/frameworks/index.md
- src/content/translations/fr/developers/docs/ides/index.md
- src/content/translations/fr/developers/docs/programming-languages/dart/index.md
- src/content/translations/fr/developers/docs/programming-languages/delphi/index.md
- src/content/translations/fr/developers/docs/programming-languages/dot-net/index.md
- src/content/translations/fr/developers/docs/programming-languages/golang/index.md
- src/content/translations/fr/developers/docs/programming-languages/index.md
- src/content/translations/fr/developers/docs/programming-languages/java/index.md
- src/content/translations/fr/developers/docs/programming-languages/javascript/index.md
- src/content/translations/fr/developers/docs/programming-languages/python/index.md
- src/content/translations/fr/developers/docs/programming-languages/ruby/index.md
- src/content/translations/fr/developers/docs/programming-languages/rust/index.md
- src/content/translations/fr/developers/docs/smart-contracts/anatomy/index.md
- src/content/translations/fr/developers/docs/smart-contracts/composability/index.md
- src/content/translations/fr/developers/docs/smart-contracts/deploying/index.md
- src/content/translations/fr/developers/docs/smart-contracts/index.md
- src/content/translations/fr/developers/docs/smart-contracts/languages/index.md
- src/content/translations/fr/developers/docs/smart-contracts/security/index.md
- src/content/translations/fr/developers/docs/smart-contracts/testing/index.md
- src/content/translations/fr/developers/docs/storage/index.md
- Update French Tech Stack content bucket files
> Update: French translation files Tech Stack 

- src/content/translations/pt-br/developers/docs/apis/backend/index.md
- src/content/translations/pt-br/developers/docs/apis/javascript/index.md
- src/content/translations/pt-br/developers/docs/apis/json-rpc/index.md
- src/content/translations/pt-br/developers/docs/data-and-analytics/block-explorers/index.md
- src/content/translations/pt-br/developers/docs/data-and-analytics/index.md
- src/content/translations/pt-br/developers/docs/development-networks/index.md
- src/content/translations/pt-br/developers/docs/ethereum-stack/index.md
- src/content/translations/pt-br/developers/docs/frameworks/index.md
- src/content/translations/pt-br/developers/docs/ides/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/dart/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/delphi/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/dot-net/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/golang/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/java/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/javascript/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/python/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/ruby/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/rust/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/anatomy/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/compiling/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/composability/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/deploying/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/languages/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/libraries/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/security/index.md
- src/content/translations/pt-br/developers/docs/smart-contracts/testing/index.md
- src/content/translations/pt-br/developers/docs/storage/index.md
- Update Portuguese Brazilian Tech Stack content bucket files
> Update: Portuguese Brazilian translation files Tech Stack

- src/intl/en/page-wallets-find-wallet.json
Updating "over 1 million" to "over 21 million"
> fix typo under "MetaMask" description

- src/pages/layer-2.js
- Fix template string for negative percent change for L2 stats
> fix template string bug for l2 stats

- redirects.json
- Add redirect for `/grants/` -> `/community/grants/`
> Add redirect for /grants/

- src/content/eips/index.md
I have updated the list of old EIP editors with the new one.
> Updated the list of EIP Editors

- src/pages/layer-2.js
Fix a small typo. Lighting Network -> Lightning Network
> Fix typo on layer 2 page

- src/content/developers/docs/programming-languages/rust/index.md
A very good tutorial to help understand rust development
@ samajammin
> docs: add a tutorial 

- src/components/Staking/StakingProductsCardGrid.js
- Add id key for product card components for render IDs
> Add ID for staking product card map 

- src/content/community/language-resources/index.md
The original link of EthFans is no longer available.
> Fixed EthFans' link

- src/content/developers/docs/scaling/zk-rollups/index.md
- Added a missing quotation mark in the pros/cons table.
- Not related to an issue.
> Updated index.md [Dev/Docs/Scaling/Zk-Rollups] 

- src/content/developers/docs/scaling/state-channels/index.md
- Added some missing quotation marks in the pros/cons table.
- Not related to an issue.
> Updated index.md [Dev/Docs/Scaling/State Channels]

- src/content/translations/id/enterprise/index.md
- src/content/translations/id/glossary/index.md
- src/content/translations/id/history/index.md
- src/intl/id/page-assets.json
- Update Indonesian Learn Page content bucket files
> Update: Indonesian translation files Learn Pages 

- src/content/translations/ro/developers/docs/mev/index.md
- src/content/translations/ro/developers/docs/oracles/index.md
- src/content/translations/ro/developers/docs/scaling/index.md
- src/content/translations/ro/developers/docs/scaling/optimistic-rollups/index.md
- src/content/translations/ro/developers/docs/scaling/plasma/index.md
- src/content/translations/ro/developers/docs/scaling/sidechains/index.md
- src/content/translations/ro/developers/docs/scaling/state-channels/index.md
- src/content/translations/ro/developers/docs/scaling/validium/index.md
- src/content/translations/ro/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/ro/developers/docs/standards/index.md
- src/content/translations/ro/developers/docs/standards/tokens/erc-1155/index.md
- src/content/translations/ro/developers/docs/standards/tokens/erc-20/index.md
- src/content/translations/ro/developers/docs/standards/tokens/erc-721/index.md
- src/content/translations/ro/developers/docs/standards/tokens/erc-777/index.md
- src/content/translations/ro/developers/docs/standards/tokens/index.md
- Update Romanian Advanced Pages content bucket files
> Update: Romanian translation files Advanced Pages

- src/content/translations/pt-br/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
- src/content/translations/pt-br/developers/tutorials/calling-a-smart-contract-from-javascript/index.md
- src/content/translations/pt-br/developers/tutorials/hello-world-smart-contract/index.md
- src/content/translations/pt-br/developers/tutorials/how-to-mint-an-nft/index.md
- src/content/translations/pt-br/developers/tutorials/how-to-view-nft-in-metamask/index.md
- src/content/translations/pt-br/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
- src/content/translations/pt-br/developers/tutorials/run-node-raspberry-pi/index.md
- src/content/translations/pt-br/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
- src/content/translations/pt-br/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
- src/intl/pt-br/page-developers-tutorials.json
- Update Portuguese Brazilian Tutorials 1 content bucket files
> Update: Portuguese Brazilian translation files Tutorials 1

- src/data/staking-products.json
Updates audit info for StakeWise staking products
Audits: https://github.com/stakewise/contracts/tree/master/audits
[Fixes #6213]
> Update StakeWise audit info

- src/content/translations/zh/developers/docs/nodes-and-clients/index.md
> Fix Chinese translation error (nodes and clients)

- src/content/developers/docs/standards/tokens/erc-721/index.md
> Added POAP to popular NFTs

- src/intl/en/page-upgrades-index.json
Changed "the merge" to "The Merge" for consistency
> Fixed typo to 'The Merge' spelling

- src/content/developers/docs/scaling/zk-rollups/index.md
Fix typo, noticed in Romanian translated files.
None
> Fix broken link on zk-rollups developer doc

- src/pages/layer-2.js
- Add a "how to get onto layer 2" button in the layer 2 page hero that takes the user to the onboard section
> Add "how to get onto layer 2" button in layer 2 page hero

- src/content/developers/docs/programming-languages/python/index.md
The package was renamed due to a common request
I updated link, name and description.
> Update smart-contracts-for-testing project name and link

- src/content/developers/docs/programming-languages/dart/index.md
Deleted redundant punctuation marks:
- [Building a Mobile dApp with Flutter](https://medium.com/dash-community/building-a-mobile-dapp-with-flutter-be945c80315a) is a lot shorter, which might be better if you already know the basics`.`
- [Integrating MetaMask in Flutter application](https://youtu.be/8qzVDje3IWk) - this short video takes you through the steps of integrating MetaMask into your Flutter applications`.`
> Removed redundant punctuation marks [dev docs]

- src/content/translations/ca/community/language-resources/index.md
- src/content/translations/de/community/language-resources/index.md
- src/content/translations/es/community/language-resources/index.md
- src/content/translations/fa/community/language-resources/index.md
- src/content/translations/fr/community/language-resources/index.md
- src/content/translations/id/community/index.md
- src/content/translations/id/community/language-resources/index.md
- src/content/translations/it/community/language-resources/index.md
- src/content/translations/nl/community/language-resources/index.md
- src/content/translations/pt-br/community/language-resources/index.md
- src/content/translations/ro/community/language-resources/index.md
- src/content/translations/ru/community/language-resources/index.md
- src/content/translations/tr/community/language-resources/index.md
- src/content/translations/zh/community/language-resources/index.md
> Update ethfans.org link

- src/content/translations/it/developers/docs/standards/tokens/erc-777/index.md
- src/content/translations/zh/developers/docs/standards/tokens/erc-777/index.md
Change code snippets back to English
None
> Fix translated code snippets

- src/components/UpcomingEventsList.js
Override RTL styling on UpcomingEventsList
Fixes #6221
> Override RTL styling on UpcomingEventsList

- src/content/translations/id/history/index.md
- src/content/translations/it/history/index.md
Fixes broken syntax for Emojis which were causing the emojis to not render correctly.
None, [context here on Discord](https://discord.com/channels/714888181740339261/971697031586402305/971697191414550548).
> Fix broken emojis on History page

- src/content/contributing/translation-program/content-buckets/index.md
Updates content buckets page in line with what we have on Crowdin
None
> Update content buckets page

- src/content/dao/index.md
Added information on reputation-based systems and holographic consensus, in light of Vitalik's recent post discussing soulbound governance rights. https://vitalik.eth.limo/general/2022/01/26/soulbound.html
> Add reputation based DAOs to DAO page

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Adding ZMOK to nodes/API providers. Describing its key benefits.
> Adding ZMOK

- src/content/developers/docs/consensus-mechanisms/index.md
Additions to the consensus mechanism docs
- Adds notes around Byzantine fault and Byzantine Generals Problem as it provides more context on consensus and consensus mechanisms
- Adds another an analogy/story to support the Byzantine Generals Problem explanation
- Adds a note on the difference between protocols and algorithms
#5711
> Update consensus mechanisms docs

- src/content/community/online/index.md
- Typo fixed, changed `upto date` to `up to date`.
> Typo fixed [Community Page]

- src/data/community-events.json
Updates ETHBarcelona dates to the correct ones
None
> Update ETHBarcelona dates

- .github/ISSUE_TEMPLATE/suggest_layer2.md
- src/content/contributing/adding-layer-2/index.md
- Update layer 2 listing policy to make requirements of data availability and security more apparent.
> Update layer 2 listing policy

- src/content/developers/docs/networks/index.md
added the recently launched sepolia faucet.
> dev/networks: add sepolia faucet

- src/content/developers/docs/scaling/zk-rollups/index.md
Fix an incorrect path to optimistic-rollups on the zk-rollups page.
> Fix incorrect path to optimistic rollups

- src/content/translations/tr/developers/docs/mev/index.md
- src/content/translations/tr/developers/docs/oracles/index.md
- src/content/translations/tr/developers/docs/scaling/index.md
- src/content/translations/tr/developers/docs/scaling/optimistic-rollups/index.md
- src/content/translations/tr/developers/docs/scaling/plasma/index.md
- src/content/translations/tr/developers/docs/scaling/sidechains/index.md
- src/content/translations/tr/developers/docs/scaling/state-channels/index.md
- src/content/translations/tr/developers/docs/scaling/validium/index.md
- src/content/translations/tr/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/tr/developers/docs/standards/index.md
- src/content/translations/tr/developers/docs/standards/tokens/erc-1155/index.md
- src/content/translations/tr/developers/docs/standards/tokens/erc-20/index.md
- src/content/translations/tr/developers/docs/standards/tokens/erc-721/index.md
- src/content/translations/tr/developers/docs/standards/tokens/erc-777/index.md
- src/content/translations/tr/developers/docs/standards/tokens/index.md
Updates Turkish (`tr`) "advanced docs" content bucket with latest from Crowdin.
> Turkish: Advanced docs

- src/content/translations/fr/developers/docs/mev/index.md
- src/content/translations/fr/developers/docs/oracles/index.md
- src/content/translations/fr/developers/docs/scaling/index.md
- src/content/translations/fr/developers/docs/scaling/optimistic-rollups/index.md
- src/content/translations/fr/developers/docs/scaling/plasma/index.md
- src/content/translations/fr/developers/docs/scaling/sidechains/index.md
- src/content/translations/fr/developers/docs/scaling/state-channels/index.md
- src/content/translations/fr/developers/docs/scaling/validium/index.md
- src/content/translations/fr/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/fr/developers/docs/standards/index.md
- src/content/translations/fr/developers/docs/standards/tokens/erc-1155/index.md
- src/content/translations/fr/developers/docs/standards/tokens/erc-20/index.md
- src/content/translations/fr/developers/docs/standards/tokens/erc-721/index.md
- src/content/translations/fr/developers/docs/standards/tokens/erc-777/index.md
- src/content/translations/fr/developers/docs/standards/tokens/index.md
Updates French (`fr`) "advanced docs" content bucket with latest from Crowdin.
> French: Advanced docs

- src/content/translations/nl/energy-consumption/index.md
- src/content/translations/nl/governance/index.md
- src/content/translations/nl/nft/index.md
- src/content/translations/nl/security/index.md
Updates Dutch (`nl`) "use cases" content bucket with latest from Crowdin.
> Dutch: Use cases content

- src/content/developers/docs/consensus-mechanisms/index.md
> Fix wording in consensus mechanisms developer docs

- src/content/community/get-involved/open-research/index.md
- Added suggestions and rationale behind proposed content structure
- Provided sample of content structure from ESP (Ecosystem Support Program)
- Proposed metadata schema and key fields for entries
> suggestions for content presentation structure

- src/content/staking/solo/index.md
> Fix minor typos in staking documentation.

- src/intl/en/page-developers-index.json
Language JSON file missing comma separator
> Syntax bug patch

- src/content/community/language-resources/index.md
Edit: Typo
Edited a typo in language-resources.md
Removed accidental repetition in the sentence (see issue).
https://github.com/ethereum/ethereum-org-website/issues/6363
> Typo correction

- src/components/ButtonLink.js
- src/components/FileContributors.js
- src/components/Layer2ProductCard.js
- src/components/ProductCard.js
- src/components/TableOfContents.js
- src/components/WalletCard.js
- Add optional hideArrow prop to ButtonLink, and remove these props from product cards and other buttons where applicable.
> Fix ButtonLink arrow logic

- src/content/contributing/adding-products/index.md
Update link to GH issue user can approve the most appropriate option (e.g. wallet or dapp). Currently it takes them to a generic issue.
None
> Update GH issue link

- .env.example
- gatsby-config.js
Use custom env value to determine if we are in preview deploy env.
> Fix Matomo not loading

- src/data/consensus-bounty-hunters.csv
> update Guido's score

- src/content/web3/index.md
Adds a short section about DAOs to the web3 page
None
> Add DAO section to Web3 page

- src/content/developers/docs/consensus-mechanisms/pos/gasper/index.md
> fix typo: close parenthesis

- src/data/community-events.json
I added ETH Warsaw conference and hackathon date to the second community events list.
> 🇵🇱 Add ETH Warsaw to the second list

- src/data/staking-products.json
> Update StakeWise info

- src/data/eth-upgrade-articles.js
Adds most recent "Finalized" and "What's new in Eth2?" blog entries to eth-upgrade-articles.js
> Update upgrade articles

- src/content/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md
The current version of this article has the hash function `hash(a^b)`.
That is a **bad** idea because it means that if you know the legitimate values of `a` and `b` you could use `b' = a^b^a'` to prove any desired `a'` value.
With this function you'd have to calculate `b'` such that `hash(a') ^ hash(b')` is equal to a known value (the next branch on the way to root), which is a lot harder.
> Urgent: Fix security in Merkle Tree article

- src/data/community-events.json
I added ETHLatam @ Buenos Aires to the list of upcoming events 📅
https://twitter.com/ethlatam
> Add ETHLatam @ Buenos Aires to upcoming events

- docs/typescript.md
Adding some initial TS docs.
Note: the build is not failing, I canceled it because it was not necessary here.
> Typescript docs

- src/content/community/get-involved/index.md
- Removed punctuation mark from list. 
- Changed `... help people create value through DAO.` to `... help people create value through DAO`.
> Fix punctuation on community get involved page

- src/content/developers/docs/standards/tokens/erc-4626/index.md
addres -> address
Github -> GitHub
> Fix typo in erc-4626/index.md

- src/content/developers/docs/smart-contracts/composability/index.md
The smart contract composability lacked detailed information, so I included new details that may be helpful to readers.
The addition includes a more in-depth explanation of smart contract composability and why it matters for developers. The update also contains a new section on examples of composability in Ethereum, asides from the Uniswap example mentioned at the beginning. I also included additional resources for those who want deeper knowledge of how composability works.
> Update page on smart contract composability

- src/content/developers/docs/apis/json-rpc/index.md
minor updates to smooth following along the example
* added links to `solc` installation docs, and to relevant release
* corrected an output and a command
(pls, indicate if an issue really needed for such a small fix)
> `solc` links and couple corrections (Update index.md)

- src/data/community-events.json
Fixed date of HackFS event and added ETHVenice event 🎆
I attach the links here of the official events sites.
HackFS : https://hackfs.ethglobal.com/
ETHVenice : https://ethvenice.com/
> Fix a date and add ETHVenice

- src/data/community-meetups.json
Adding Chicago Ethereum Meetup to the meetups list
n/a
> Add Chicago to the meetups list

- src/data/externalTutorials.json
Small format issue in json file is breaking builds.
> Fix json file

- src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/content/translations/id/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/content/translations/it/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/content/translations/ro/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/content/translations/tr/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/content/translations/zh/developers/tutorials/uniswap-v2-annotated-code/index.md
Fixes a broken link from uniswap docs
Catches links from translated folders missed in #6449
> Fix uniswap docs link

- src/data/staking-products.json
StakeWise has added a bug bounty to Immunefi: https://immunefi.com/bounty/stakewise/
> StakeWise added Bug Bounty [Fixes #6516]

- src/data/consensus-bounty-hunters.csv
> Updated Jonny's score

- src/content/developers/docs/networks/index.md
Adding the links to the new Sepolia Etherscan explorer as well as to an additional Sepolia faucet provider.
> ♻️ Add further Sepolia links

- src/content/developers/docs/consensus-mechanisms/pos/gasper/index.md
> Fix typo in Gasper developer docs

- src/content/contributing/style-guide/index.md
- Add The Merge to the style guide
#6520
> Add The Merge to the style guide

- src/data/translation-reports/month/month-data.json
- Monthly update of translation leaderboard data
> update month and alltime data for translation leaderboard

- src/content/developers/docs/scaling/sidechains/index.md
Reworked the content to add more structure to the page. Also updated pros/cons and described the architecture of sidechains in detail.
I felt the page needed some structure, so I reworked it and added a few things to provide readers with more information. Here's a brief overview of the changes:
- Rewrote the introduction (the original was too long imo and could be more concise)
- Included new details about sidechains' relationship with Mainnet and contrasted them with Layer 2 scaling solutions 
- Created a section to describe how sidechains work, with new details on how assets are transferred
- Updated the "Use Sidechains" section; replaced the Gnosis chain link (the other was a dead link) and added Loom Network
- Updated pros and cons; added some points and fleshed out others
> Add new information to sidechains page

- src/content/developers/docs/intro-to-ethereum/index.md
> Fix inaccuracy in intro to ethereum developer doc

- src/content/developers/docs/networking-layer/index.md
> Fix broken link in developer docs

- src/intl/en/page-developers-index.json
> Fix typo in developer docs navigation

- src/content/developers/docs/smart-contracts/index.md
Although technically correct already, I've edited this statement to be more fluent in English as it's used by native speakers to enhance readability.
> Rephrase section of smart contracts developers docs

- src/content/community/language-resources/index.md
This change adds Cryptoversidad's channel to the spanish language resources.
> Add Cryptoversidad to the Spanish resources

- src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/index.md
This PR fixes two non-existing links.
>  mining-algorithms/index.md: fix pow and mining links

- src/data/community-events.json
Including the infos about EthereumSP.
Including information about EthereumSP, an event held in September 2022, in Brazil.
> Add EthereumSP to events

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Updating Alchemy's entry in Node Services on behalf of Alchemy.
> Updating Alchemy's entry in Node Services.

- src/data/community-events.json
Updating our calendar, unfortunately, we were forced to cancel ETHTaiwan :( 
Updated descriptions to be a bit more clear and be sure to point out that it's an ETHGlobal event as there's been some confusion in the community!
-- 
PS: Sorry for two commits, I can pre-squash if preferred.
_This PR opened at FL320 ✈️_
> Update 2022 ETHGlobal community events list

- src/data/layer-2/cex-layer-2-support.json
- Add optimism to L2's that Binance supports
https://www.binance.com/en/support/announcement/3ee5a24e46754c278eaf769fcd4b7edf
> Add optimism support in binance.

- src/content/upgrades/merge/index.md
@wackerow 
/developers/docs/scaling/ updated as /layer-2/ 
#6588
> Update non-dev links to L2 resources

- src/content/glossary/index.md
> Update EOA definition

- src/content/developers/docs/development-networks/index.md
Includes some basic info/links about local/public BC testnets
> Update testnet page with Beacon Chain testnets

- src/data/externalTutorials.json
Adding "How to develop an NFT Smart Contract (ERC721) with Alchemy" tutorial in external developer articles.
> Adding NFT Smart Contract External Tutorial.

- src/data/community-events.json
99% of projects presenting at MetaFest are based on Ethereum or EVM chains like Gnosis & Polygon so it probably makes sense to ahve it here
> adding MetaFest to the schedule

- src/content/developers/docs/nodes-and-clients/client-diversity/index.md
adds short paragraph about execution layer diversity
> add execution-layer info to client diversity page

- src/data/community-events.json
Fixes missing comma from `community-events.json`
> Json syntax bug patch

- src/content/foundation/index.md
This PR updates the description of the Fellowship Program for 2022, in line with the changes going in to the fellowship program website. 
It remains rather generic, so there's no problem merging this immediately (before the new fellowship website is deployed, which will happen later this week).
> Update Fellowship Program copy.

- src/pages/layer-2.js
- Add a note about EOA and smart contract wallets on layer 2
> add note about wallet addresses to layer 2 page

- src/content/developers/docs/networking-layer/index.md
adds a warning about changes to the p2p networking layer coming with The Merge.
Page will need more substantial revisions for post-merge version.
> additional warning about merge changes to p2p networking page

- src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
Don't see major changes required on this page, but have updated the position and content of the merge warning banner to be more explicit about mining being switched off and adding links to more information.
> update banner on mining page

- src/components/PreMergeBanner.tsx
- src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/index.md
- src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
- src/content/developers/docs/development-networks/index.md
- src/content/developers/docs/intro-to-ether/index.md
- src/content/developers/docs/mev/index.md
- src/content/developers/docs/networking-layer/index.md
- src/content/developers/docs/networks/index.md
- src/content/developers/docs/nodes-and-clients/client-diversity/index.md
- src/content/developers/docs/nodes-and-clients/index.md
- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
- src/content/developers/tutorials/run-light-node-geth/index.md
- src/content/developers/tutorials/run-node-raspberry-pi/index.md
- src/content/governance/index.md
- src/content/nft/index.md
- src/content/security/index.md
- src/pages/developers/tutorials.js
- src/schema/sdls/Frontmatter.ts
- src/templates/docs.tsx
- src/templates/tutorial.tsx
- src/templates/use-cases.tsx
Adds a pre-merge banner notification for pages flagged during site audit for containing any content requiring updating as we approach The Merge. Updating these pages will come in separate PRs, but this at least makes users aware that the content isn't fully accurate until these fixes are ready.
- #6281
> Adds PreMergeBanner

- src/content/contributing/adding-wallet/index.md
- src/content/contributing/index.md
- Create new wallet listing page
- https://github.com/ethereum/ethereum-org-website/issues/6434
> Wallet listing policy

- src/data/community-events.json
- yarn.lock
Hi guys, organizer of ethsafari in Kenya here. Would like to add the community event to the community events page. Lemme know if you have questions!
> added ethsafari to community events page

- src/content/contributing/index.md
Update the emoji of the poaps channel
> Update channel emoji

- src/intl/en/page-upgrades-index.json
Returns string to intl json needed on Upgrades pages
> Revert string removal

- src/data/community-events.json
> Added ETHBerlin³

- src/content/translations/zh/developers/docs/nodes-and-clients/index.md
Correct a translation mistake
Don't need to translate 'Go' to Chinese
> fix: correct translation mistake

- src/content/developers/docs/transactions/index.md
changed "wallet" to "account" in the "types of transactions" section
> Clarity/accuracy: transactions developer doc

- src/content/translations/zh/developers/docs/nodes-and-clients/index.md
> Fix typo in nodes and clients developer doc (Chinese)

- src/data/execution-bounty-hunters.csv
Adding Sergio Demian Lerner to EL bounty list
> Adding Sergio Demian Lerner to EL bounty list

- src/content/community/language-resources/index.md
Hi, I added a Czech section to the "Language resources" page, maybe it will be useful for someone. 🇨🇿 
It includes links to our content that we create within @gweicz and a czech translation of the book Mastering Ethereum.
Thank you so much for the PR merge!
> Adding a Czech section to the Language Resources page

- src/content/community/grants/index.md
Add Chainlink's grants program to the grants list.
> add Chainlink to grants list

- src/data/community-meetups.json
Add Web3Dubai and DeFi Dubai meetups.
> Add community meetups in the UAE

- src/data/community-events.json
Update ethlatam event website.
> Update Ethlatam website

- src/content/developers/docs/intro-to-ether/index.md
Adding this Gwei calculator to help Ethereum developers and Users easily convert different denominations of Ether.
> Adding Gwei Calculator to Page

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
name update
"QuikNode" rebranded to "QuickNode" in 2021
> update to QuickNode

- src/data/community-meetups.json
Adds the Brighton Blockchain meetup group to the list of community meetups.
resolves #6757 
Issue:
https://github.com/ethereum/ethereum-org-website/issues/6757
> Adds Brighton Blockchain to community meetups (#6757)

- src/content/nft/index.md
> Added in use cases for NFTs for consideration on page

- src/content/translations/es/developers/docs/intro-to-ether/index.md
Traducción de frase no traducida en ¿Qué es el ether?
> Translate missing string on /intro-to-ether

- src/components/ImageCard.tsx
- src/components/InfoBanner.tsx
- src/components/Layer2/Layer2Onboard.tsx
- src/components/Layer2ProductCard.tsx
- src/components/Layout.tsx
- src/components/Leaderboard.tsx
- src/components/Logo.tsx
- src/pages/layer-2.js
- src/types.ts
Moving files starting with letter "I" and "L" to TS
Conversion to TS according to #6392
> Convert i & l files ts

- src/components/Card.tsx
- src/components/TranslationBanner.tsx
- src/components/TranslationBannerLegal.tsx
- src/components/TranslationLeaderboard.tsx
- src/components/TranslationsInProgress.tsx
- src/components/Trilemma.tsx
- src/components/TutorialMetadata.tsx
- src/components/TutorialTags.tsx
- src/components/UpcomingEventsList.tsx
- src/pages/contributing/translation-program/acknowledgements.tsx
- src/pages/contributing/translation-program/contributors.tsx
- src/pages/staking/deposit-contract.tsx
Converted Javascript files to Typescript
#6392
> Javascript -> Typescript

- src/intl/en/page-upgrades-get-involved-bug-bounty.json
Making it more clear who are excluded from monetary rewards.
> Updating bug bounty text for clarity

- src/content/developers/docs/nodes-and-clients/index.md
removes embedded link that was linking out to the same page it was displayed on.
#6861
> removes recursive link

- src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
> fix broken header ID in merkle trie page

- src/components/VisuallyHidden.tsx
Refactor component VisuallyHidden to typescript
Refs: #6392
> refactor(VisuallyHidden): migrate component to typescript

- src/components/UpgradeStatus.tsx
Refactor component UpgradeStatus to typescript
Refs: #6392
> refactor(upgrade-status): migrate component to typescript

- src/components/VisuallyHidden.tsx
> Fix visually hidden component

- src/components/Tag.tsx
Migrate [Tag](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/Tag.js) to typescript
Refs: #6392
> refactor: migrate Tag to typescript

- src/content/translations/tr/developers/docs/apis/backend/index.md
- src/content/translations/tr/developers/docs/apis/javascript/index.md
- src/content/translations/tr/developers/docs/data-and-analytics/block-explorers/index.md
- src/content/translations/tr/developers/docs/development-networks/index.md
- src/content/translations/tr/developers/docs/ethereum-stack/index.md
- src/content/translations/tr/developers/docs/frameworks/index.md
- src/content/translations/tr/developers/docs/programming-languages/dart/index.md
- src/content/translations/tr/developers/docs/programming-languages/delphi/index.md
- src/content/translations/tr/developers/docs/programming-languages/dot-net/index.md
- src/content/translations/tr/developers/docs/programming-languages/golang/index.md
- src/content/translations/tr/developers/docs/programming-languages/index.md
- src/content/translations/tr/developers/docs/programming-languages/java/index.md
- src/content/translations/tr/developers/docs/programming-languages/javascript/index.md
- src/content/translations/tr/developers/docs/programming-languages/python/index.md
- src/content/translations/tr/developers/docs/programming-languages/ruby/index.md
- src/content/translations/tr/developers/docs/programming-languages/rust/index.md
- src/content/translations/tr/developers/docs/smart-contracts/anatomy/index.md
- src/content/translations/tr/developers/docs/smart-contracts/compiling/index.md
- src/content/translations/tr/developers/docs/smart-contracts/deploying/index.md
- src/content/translations/tr/developers/docs/smart-contracts/index.md
- src/content/translations/tr/developers/docs/smart-contracts/libraries/index.md
- src/content/translations/tr/developers/docs/smart-contracts/security/index.md
- Updates Turkish `tr` content with latest from Crowdin for Tech Stack Docs content bucket
> Turkish update 'tech stack' latest from Crowdin

- src/content/translations/tr/developers/docs/scaling/optimistic-rollups/index.md
- src/content/translations/tr/developers/tutorials/deploying-your-first-smart-contract/index.md
- src/content/translations/tr/developers/tutorials/how-to-implement-an-erc721-market/index.md
- src/content/translations/tr/developers/tutorials/interact-with-other-contracts-from-solidity/index.md
- src/content/translations/tr/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md
- src/content/translations/tr/developers/tutorials/run-light-node-geth/index.md
- src/content/translations/tr/developers/tutorials/send-token-etherjs/index.md
- src/content/translations/tr/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/tr/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/content/translations/tr/glossary/index.md
- Imports Turkish `tr` with latest from Crowdin for **Tutorials II** content bucket
> Turkish tutorials import from Crowdin

- src/content/translations/fr/enterprise/index.md
- src/content/translations/fr/enterprise/private-ethereum/index.md
- src/content/translations/fr/foundation/index.md
- src/content/translations/fr/glossary/index.md
- src/content/translations/fr/history/index.md
- src/intl/fr/page-about.json
- Imports French `fr` with latest from Crowdin for **Learn** content bucket
> French import 'learn' from Crowdin

- src/content/translations/tr/contributing/adding-exchanges/index.md
- src/content/translations/tr/contributing/adding-layer-2/index.md
- src/content/translations/tr/contributing/adding-products/index.md
- src/content/translations/tr/contributing/adding-staking-product/index.md
- src/content/translations/tr/contributing/content-resources/index.md
- src/content/translations/tr/contributing/index.md
- src/content/translations/tr/contributing/translation-program/translators-guide/index.md
- Imports Turkish `tr` with latest from Crowdin for **Contributing** content bucket
> Turkish import 'contributing' from Crowdin

- src/content/translations/fr/developers/docs/blocks/index.md
- src/content/translations/fr/developers/docs/consensus-mechanisms/index.md
- src/content/translations/fr/developers/docs/consensus-mechanisms/pos/index.md
- src/content/translations/fr/developers/docs/consensus-mechanisms/pow/mining/index.md
- src/content/translations/fr/developers/docs/evm/index.md
- src/content/translations/fr/developers/docs/gas/index.md
- src/content/translations/fr/developers/docs/index.md
- src/content/translations/fr/developers/docs/intro-to-ether/index.md
- src/content/translations/fr/developers/docs/intro-to-ethereum/index.md
- src/content/translations/fr/developers/docs/layer-2-scaling/index.md
- src/content/translations/fr/developers/docs/networks/index.md
- src/content/translations/fr/developers/docs/nodes-and-clients/index.md
- src/content/translations/fr/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
- src/content/translations/fr/developers/docs/nodes-and-clients/run-a-node/index.md
- src/content/translations/fr/developers/docs/scaling/optimistic-rollups/index.md
- src/content/translations/fr/developers/docs/transactions/index.md
- src/content/translations/fr/developers/docs/web2-vs-web3/index.md
- src/content/translations/fr/glossary/index.md
- src/intl/fr/page-developers-docs.json
- Updates French `fr` content with latest from Crowdin for Foundational Docs content bucket
> French import 'foundational docs' from Crowdin

- src/components/Breadcrumbs.tsx
- src/components/PageMetadata.tsx
- src/utils/languages.ts
- src/utils/translations.ts
Migrating the components in the title to TypeScript.
Also add some type guards to enhance control flow on identifying different types between translationKey and language.
#6392
> refactor: migrate Breadcrumbs and PageMetadata to ts

- src/components/CodeModal.tsx
- src/components/CopyToClipboard.tsx
- src/components/MarkdownTable.tsx
- src/components/MatomoOptOut.tsx
- src/components/MeetupList.tsx
- src/components/MergeArticleList.tsx
- src/components/Modal.tsx
Moving files starting with letter "M" to TS
Conversion to TS according to #6392
> Convert m files

- src/content/developers/docs/frameworks/index.md
Updated the link to the foundry documentation
This resolves #6945
> Update Foundry documentation's Link 

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Fixed typo in link, so that it will be parsed as a link
> Fix client diversity link

- src/pages/learn/index.tsx
Add a handful of minor copy changes.
#6708
> Learn revamp page suggestions

- src/pages-conditional/what-is-ethereum.tsx
Small suggested copy updates.
#6797
> What is eth revamp suggestions

- src/content/translations/sl/developers/docs/mev/index.md
- src/content/translations/sl/developers/docs/oracles/index.md
- src/content/translations/sl/developers/docs/scaling/index.md
- src/content/translations/sl/developers/docs/scaling/optimistic-rollups/index.md
- src/content/translations/sl/developers/docs/scaling/plasma/index.md
- src/content/translations/sl/developers/docs/scaling/sidechains/index.md
- src/content/translations/sl/developers/docs/scaling/state-channels/index.md
- src/content/translations/sl/developers/docs/scaling/validium/index.md
- src/content/translations/sl/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/sl/developers/docs/standards/index.md
- src/content/translations/sl/developers/docs/standards/tokens/erc-1155/index.md
- src/content/translations/sl/developers/docs/standards/tokens/erc-20/index.md
- src/content/translations/sl/developers/docs/standards/tokens/erc-721/index.md
- src/content/translations/sl/developers/docs/standards/tokens/erc-777/index.md
- src/content/translations/sl/developers/docs/standards/tokens/index.md
- Adds Slovenian `sl` content from Crowdin for Advanced Docs content bucket
> Slovenian add 'advanced docs' from Crowdin

- src/content/staking/pools/index.md
* Changed `keep in mine` to `keep in mind`.
* Not related to an issue, spotted this while translating in Crowdin.
> Small Typo Fix [Staking/Pools]

- src/data/community-events.json
Add a couple of dev conferences to community events
ETHDubai is a dev conference centered around Ethereum and Web3Dubai around Web3.
> add conferences ETHDubai 2023 and Web3Dubai 2022

- src/content/translations/fr/developers/docs/frameworks/index.md
- src/content/translations/pt-br/developers/docs/frameworks/index.md
- src/content/translations/ro/developers/docs/frameworks/index.md
- src/content/translations/tr/developers/docs/frameworks/index.md
- src/content/translations/zh/developers/docs/frameworks/index.md
Update outdated Foundry links
#6946 #6945
> Update Foundry documentation link (fr, pt-br, ro, tr, zh)

- src/content/history/index.md
- Updates details of Gray Glacier history page entry 
- Removes note to node operators
> Update Gray Glacier details

- src/content/developers/docs/data-structures-and-encoding/index.md
> Fix grammar on data structures and encoding developer doc

- src/intl/ar/page-upgrades-vision.json
- src/intl/bg/page-upgrades-vision.json
- src/intl/ca/page-upgrades-vision.json
- src/intl/el/page-upgrades-vision.json
- src/intl/es/page-upgrades-vision.json
- src/intl/fa/page-upgrades-vision.json
- src/intl/fr/page-upgrades-vision.json
- src/intl/hi/page-upgrades-vision.json
- src/intl/hr/page-upgrades-vision.json
- src/intl/hu/page-upgrades-vision.json
- src/intl/id/page-upgrades-vision.json
- src/intl/ml/page-upgrades-vision.json
- src/intl/pl/page-upgrades-vision.json
- src/intl/pt-br/page-upgrades-vision.json
- src/intl/ro/page-upgrades-vision.json
- src/intl/sl/page-upgrades-vision.json
- src/intl/uk/page-upgrades-vision.json
- src/intl/zh/page-upgrades-vision.json
Annoyingly, this keeps reverting despite me resetting it in Crowdin... will look into this again but a quick patch for now.
None
> Fix sharding date in non-English languages

- src/content/translations/id/developers/tutorials/calling-a-smart-contract-from-javascript/index.md
- src/content/translations/ro/developers/tutorials/create-and-deploy-a-defi-app/index.md
- src/content/translations/ro/developers/tutorials/guide-to-smart-contract-security-tools/index.md
Using some regex magic courtesy of @wackerow to squash invalid datetime bugs 🐞
> Fix broken tutorial dates

- src/content/translations/de/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/fr/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/it/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/tr/developers/docs/scaling/zk-rollups/index.md
- src/content/translations/zh/developers/docs/scaling/zk-rollups/index.md
Fixing a few broken links in non-English pages
None
> Fix broken starks vs snarks link in non-English pages

- src/components/PageMetadata.tsx
- src/templates/docs.tsx
- src/templates/staking.tsx
- src/templates/static.tsx
- src/templates/tutorial.tsx
- src/templates/upgrade.tsx
- src/templates/use-cases.tsx
@pettinarip Just a thought on one way to handle this. This makes the "title" field required and will throw an error without one (we want to catch these). It keeps the description optional, and logs a warning for pages that don't have one so we can spot and correct these when bandwidth allows. Let me know what you think
example log output snippet:
```log
warn Missing PageMetadata description: Cookie Policy
warn Missing PageMetadata description: Programming languages
warn Missing custom ID on header:  Data availability committee (DAC)
warn Missing custom ID on header:  Bonded data availability
warn Missing custom ID on header:  Volitions and validium
warn Missing custom ID on header:  Data availability committee (DAC)
warn Missing custom ID on header:  Bonded data availability
warn Missing …
```
> PageMetadata: enforce title, warn description

- src/content/glossary/index.md
Changes corresponding to issue #4916
Add the term Soft Fork to the Ethereum Glossary, which wasn't present originally.
#4916
> Added term to glossary: Soft Fork

- src/content/desci/index.md
- src/intl/en/common.json
Updated the whole text of this page collaboratively with a group of people from the space, still works in progress, but would love to do the collaborative part directly in here on github through pull requests
Thank you to the contributors of this document: Jon Starr, Erik Van Winkle, Carla Ostmann, Omar El Naggar, Vincent Weisser, Philipp Koellinger, Christopher Hill, Niklas Rindtorff, Joseph Cook, Sam Richards,
> DeSci page collaborative update with much more content

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Infrastructure provider Sensei Node added - https://senseinode.com
> Sensei Node Infrastructure Provider

- src/components/Nav/index.js
- src/content/desci/index.md
- src/intl/en/common.json
Add new Ethereum use case page: DeSci
**Preview deploy:**
https://ethereumorgwebsitedev01-desci.gtsb.io/en/desci
#6432 
1. If you're comfortable with GitHub workflows, feel free to branch off this branch (`desci`) & open a PR into back into this branch.
2. If you'd prefer to just work on a draft in markdown file, feel free to edit this directly: https://notes.ethereum.org/@sam/desci
> Create DeSci page

- src/components/Nav/index.tsx
- src/intl/en/common.json
> Add desci to nav

- src/content/translations/tr/developers/docs/dapps/index.md
Dapp deliştirmenin faydaları , geliştirmenin olarak düzeltilmiştir.
> Update Turkish translation on dapps docs page

- src/content/desci/index.md
Link to desci.world was incorrect
> Link to desci.world

- src/content/developers/docs/smart-contracts/index.md
Some grammatical fixes.
Grammatical fixes in some sentences.
grammatical changes.
> Grammar fixes in smart contracts developer doc

- src/content/glossary/index.md
Add link to Ethereum networks under Mainnet for more info.
None
> Add link to Ethereum networks

- src/content/developers/docs/data-availability.md
- src/data/developer-docs-links.yaml
- src/intl/en/page-developers-docs.json
This page discusses the concept of data availability, why it matters, and solutions to the data availability problem.
@samajammin suggested a page on data availability, so I decided to start things off with this contribution. The page breaks down the concept of data availability and how the data availability relates to security and scalability. It also has a brief description of different solutions to the data availability problem.
> Add page on data availability

- src/components/MergeArticleList.tsx
Updated the list with relevant files about the merge, particularly around faucet changes and technical details that include definitions, timing, and merge steps. I organized the list to be in alphabetical order based on contributor.
https://ethereumorgwebsitedev01-shelleyoliviaethereumorgw95126.gtsb.io/en/upgrades/merge/#further-reading
> Updated MergeArticle List

- src/content/developers/docs/programming-languages/golang/index.md
A simple Ethereum wallet implementation and utilities in Golang.
A simple ethereum golang sdk
> Add Ethereum golang sdk

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Senseinode is a node operator located in Latin America, we are currently validating on rocketpool, verified on SSV and running our own validators in Brasil,Chile, Mexico and Argentina.
> Update: inclusion of SenseiNode

- src/data/developer-docs-links.yaml
Add missing description on data availability nav.
> Fix developers docs links yaml file

- src/components/FindWallet/WalletFilterSidebar.tsx
- Add matomo events on device toggle
> add matomo events on device toggles

- src/pages/wallets/find-wallet.tsx
- Adds a matomo event to track when the `RESET FILTERS` button is pressed.
> add matomo event to reset button

- src/content/zero-knowledge-proofs.md
Provides a high-level overview of zero-knowledge proofs and their applications.
This page provides a beginner-level introduction to the concept of zero-knowledge proofs. It also explains the differences between interactive and non-interactive proofs and ZK-SNARKs and ZK-STARKs. There are also sections explaining the applications of zk-proofs in various areas (including blockchains) and drawbacks of zk-proofs. 
https://github.com/ethereum/ethereum-org-website/issues/6451
> Add Learn page on zero-knowledge proofs

- src/content/developers/docs/programming-languages/delphi/index.md
This PR adds a new article to the "[Ethereum for Delphi developers](https://ethereum.org/en/developers/docs/programming-languages/delphi/)" page.
There is [a new article on how to do token swaps in the Delphi programming language](https://svanas.medium.com/swap-one-token-for-another-in-delphi-bcb999c47f7). This PR includes this article with the "Ethereum for Delphi developers" page.
> new article on how to do token swaps in Delphi

- src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> Remove stray paren

- src/content/desci/index.md
> Update #get-involved and #further-reading in index.md

- src/content/desci/index.md
Add link of article that introduces IP-NFT as hyperlink
> Add link to IP-NFT

- src/components/Footer.tsx
- src/components/Nav/index.tsx
- src/content/zero-knowledge-proofs.md
- src/intl/en/common.json
- Add dropdown and footer nav items for zero-knowledge proof page
- Add YouTube resource in further reading section
- Add reference to CRS beside Common Reference String to tie acronym to it.
> add nav links for zkp page, add a youtube resource, and acronym

- src/content/developers/docs/evm/opcodes/index.md
Add mention to evm.codes, which looks to be a well-maintained, open-source, interactive resource:
https://github.com/comitylabs/evm.codes
None 😄
> Add link to evm.codes

- src/content/developers/docs/scaling/plasma/index.md
Edited the page to add a detailed description of plasma and how it works. I also added new information on the mass exit problem and how it threatens plasma's security model.
- Expanded upon the current docs to more thoroughly describe Plasma
- Explained [the mass exit problem](https://www.google.com/search?q=plasma+mass+exit+problem)
- Explained why plasma fell out of favour and how the Ethereum community has gathered around other Layer 2 solutions.
#3655
> Expand Plasma developer docs

- src/content/developers/docs/data-availability.md
- Looks like linter ran, but main fix is on line 150 adding in # for header tag.
> fix header tag

- src/content/developers/docs/scaling/optimistic-rollups/index.md
I noticed the sharding link wasn't working so I added a thorough sharding doc. Also I included a full guide on optimistic roll-ups that was recently updated. Thank you!
> Updated broken link + included a guide

- src/content/translations/it/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
- src/content/translations/it/developers/tutorials/calling-a-smart-contract-from-javascript/index.md
- src/content/translations/it/developers/tutorials/hello-world-smart-contract/index.md
- src/content/translations/it/developers/tutorials/how-to-mint-an-nft/index.md
- src/content/translations/it/developers/tutorials/how-to-view-nft-in-metamask/index.md
- src/content/translations/it/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
- src/content/translations/it/developers/tutorials/run-node-raspberry-pi/index.md
- src/content/translations/it/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
- src/content/translations/it/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
Update tutorials I bucket from Crowdin
None
> Italian: update "Tutorials I" bucket from Crowdin

- src/data/community-events.json
We need to add pull request for our event ETH-Vietnam into community-events.json
We need to add pull request for our event ETH-Vietnam into community-events.json, please check it out
> Add ETH-Vietnam to community-events.json

- src/content/developers/tutorials/how-to-mock-solidity-contracts-for-testing/index.md
> Fix typo in how-to-mock-solidity-contracts-for-testing/index.md

- src/content/contributing/index.md
Make it clearer that content resources aren't just "articles".
#4439
> Update anchor text to match page

- README.md
- src/content/translations/de/contributing/index.md
- src/content/translations/it/contributing/index.md
- src/content/translations/tr/contributing/index.md
- src/content/translations/tr/contributing/page-contributing-translation-program-acknowledgements.json
- src/content/translations/zh/contributing/index.md
- src/intl/de/page-contributing-translation-program-acknowledgements.json
- src/intl/en/page-contributing-translation-program-acknowledgements.json
- src/intl/id/page-contributing-translation-program-acknowledgements.json
- src/intl/pt-br/page-contributing-translation-program-acknowledgements.json
- src/intl/tr/page-contributing-translation-program-acknowledgements.json
- src/intl/zh/page-contributing-translation-program-acknowledgements.json
Changes of the POAPs content
Changes of the emoji and the year of contribution for POAPs
None
> Changes on emoji and year of contribution for POAPs

- docs/typescript.md
Added a few more TS resources.
> TS more learning resources

- src/components/EthExchanges.tsx
`EthExchanges.js` to ts.
#6392
> Migrate EthExchanges to TS

- .eslintignore
- overrides.d.ts
- src/data/CreateWallet.js
- src/data/SimpleDomainRegistry.sol
- src/data/SimpleToken.sol
- src/data/SimpleWallet.sol
- src/pages/index.tsx
- webpack.config.ts
Source homepage code examples from data files
Load the content of the code examples (on homepage) from the corresponding files in `/src/data`
#7150
> Load content from data files

- src/components/Nav/Menu.tsx
- src/components/Nav/Mobile.tsx
Added missing `key` props in the `Menu` component.
> Add missing `key` props

- src/content/contributing/index.md
Add the link to the discord channel
Directly add the discord channel link.
None
> Add discord channel link

- src/intl/tr/common.json
- src/intl/tr/page-about.json
- src/intl/tr/page-developers-index.json
- src/intl/tr/page-developers-local-environment.json
> fix(typos): remove leading spaces

- .github/CODEOWNERS
Add @jmcook1186 as code owner
Due to branch rules @jmcook1186 was unable to merge #7151 - he should be a code owner 😄
> Add jmcook1186 as code owner

- src/content/bridges/index.md
* Added punctuation mark sentence.
* Not related to an issue.
> Update index.md [bridges]

- src/content/enterprise/private-ethereum/index.md
* Small typo fix. 
* Not related to an issue.
> Update index.md [private-ethereum]

- src/content/community/research/index.md
> Fixed Indentation of "Coinbase: Intro to Web3 Stack"

- src/content/developers/docs/web2-vs-web3/index.md
updates web2 vs web3 page for post-merge. AFAICT just requires single word update.
#7075
> update web2vweb3 page

- src/content/developers/docs/gas/index.md
Updates content on /gas page for post-merge
#7075
> update gas page content for post-merge

- src/data/execution-bounty-hunters.csv
Increasing Guido's score based on a finding of his.
> Increasing Guido Vranken's EL Bounty score

- src/content/developers/docs/ides/index.md
The Blockchain Development Kit for Ethereum in the Visual Studio marketplace does not exist anymore. Removed its broken link.
> Remove broken link to Visual Studio dev kit

- src/content/decentralized-identity/index.md
Hi Ethereum team, I added a community for those interested in contributing to an Open Source Project building a framework for verifiable data to the ethereum.org/en/decentralized-identity page
> Add Veramo Labs to decentralized identity page

- src/intl/ro/common.json
I've added some translations for the romanian language. 
Most of the translations are for links in the footer
> Added romanian translations for footer links

- src/content/developers/docs/networks/index.md
updates info on testnets to be relevant post-merge
#7075
> post-merge update: networks page

- src/content/developers/docs/scaling/index.md
- Add validium to off-chain scaling section.
> Add validium to off-chain scaling section.

- src/content/desci/index.md
> Adding an amazing talk by Juan Benet about DeSci

- src/content/community/grants/index.md
* Removed punctuation mark from list. 
* Not related to an issue.
> Update index.md [Grants]

- src/content/developers/docs/scaling/state-channels/index.md
> Reword section of state channels developer doc

- src/data/community-events.json
For some reason, we changed the event date to Nov 25, 2022 - Nov 27, 2022.
We have updated this on our website.
We changed the event date to Nov 25, 2022 - Nov 27, 2022.
We have updated this on our website.
> Change ETHVietnam Event Date

- src/content/developers/docs/evm/opcodes/index.md
Add headers to the EVM opcodes page
Fix #7072
> Add headers to opcodes file

- src/content/developers/docs/smart-contracts/index.md
- src/content/developers/docs/web2-vs-web3/index.md
- Added an article about " [Why We Need Web 3.0](https://medium.com/@gavofyork/why-we-need-web-3-0-5da4f2bf95ab) " by  Gavin Wood Ethereum co-founder in web2 vs web3 Doc.
- And added some text in the smart contract Doc. 
PS: This is my first PR in Ethereum org looking forward to making some quality code contributions and adding some features.
If any suggestions, please let me know.
> Article added in web2 vs web3 and did some minor changes

- src/content/upgrades/merge/index.md
adds a short notice about the expected merge date
> add merge date notice

- src/content/translations/ca/community/grants/index.md
- src/content/translations/de/community/grants/index.md
- src/content/translations/es/community/grants/index.md
- src/content/translations/fa/community/grants/index.md
- src/content/translations/fr/community/grants/index.md
- src/content/translations/id/community/grants/index.md
- src/content/translations/it/community/grants/index.md
- src/content/translations/ja/community/grants/index.md
- src/content/translations/nl/community/grants/index.md
- src/content/translations/pt-br/community/grants/index.md
- src/content/translations/ro/community/grants/index.md
- src/content/translations/ru/community/grants/index.md
- src/content/translations/sl/community/grants/index.md
- src/content/translations/sw/community/grants/index.md
- src/content/translations/tr/community/grants/index.md
- src/content/translations/zh/community/grants/index.md
Fixes non-English links (#7245)
#7245
> Fix non-English balancer community grants links

- i18n/config.json
Adds `ph` and `kk` to i18n config.json
#6990
> Add PH and KK to config.json

- src/content/enterprise/index.md
Adding QuickNode with a short description in the Enterprise section
No related issues.
> Adding QuickNode to Enterprise Section

- src/content/developers/docs/standards/tokens/erc-4626/index.md
> Fix ERC-4626 interface

- src/content/upgrades/beacon-chain/index.md
updates beacon chain page ready for post-merge
#7075
> post-merge updates: beacon chain page

- src/content/developers/docs/accounts/index.md
updates accounts page for post-merge. Adds note on validator keys (links to page created in PR #7215).
#7075
> post-merge update: accounts page

- src/content/desci/index.md
> DeSci page: add a new article to further reading

- src/content/developers/docs/smart-contracts/languages/index.md
> Adding VyperExamples.com do docs

- src/content/community/get-involved/index.md
> Add CryptoValley jobs 

- src/data/translation-reports/month/month-data.json
Update translation leaderboard files for:
- Month (July 1, 2022 - July 31, 2022)
- All time (Genesis-July 31, 2022)
> Update translation leaderboard data files

- src/content/translations/id/developers/tutorials/optimism-std-bridge-annotated-code/index.md
> Fix typo in optimism-std-bridge-annotated-code/index.md

- src/content/translations/fa/developers/docs/intro-to-ether/index.md
translate to persian
Translation of some of the remaining English texts into Persian in the topics what-is-ether and burning-ether
> Update Farsi intro to Ether

- src/content/translations/it/contributing/adding-layer-2s/index.md
- src/content/translations/it/contributing/adding-products/index.md
- src/content/translations/it/contributing/adding-staking-products/index.md
- src/content/translations/it/contributing/index.md
- src/content/translations/it/contributing/translation-program/index.md
- src/content/translations/it/contributing/translation-program/translators-guide/index.md
Update Contributing bucket for Italian (`it`) lang
> Update Italian contributing bucket

- src/content/translations/fa/community/online/index.md
Updates Community bucket for Farsi (`fa`) lang
> Update Farsi Community bucket

- src/content/community/online/index.md
removes link to mining forum
#7075
> post-merge updates: community/online page

- src/content/developers/docs/apis/javascript/index.md
adds a note explaining that consensus client is required.
#7075
> post-merge updates: javascript api page

- src/content/bridges/index.md
Hi there, two changes:
1) Added a concrete bridging use case - under the "why do we need bridging" section, I added in a concrete example to solidify the point of what bridging looks like in company that helps bridges Ethereum to other chains. The thinking is that the additional detail adds value to understanding why multi chain support and bridging is important
2) Added an in-depth article that has been recently updated - the other docs were all from 2021
Pls lmk if there are any questions, thanks!
> Added a bridging use case + an in-depth article

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Hi Ethereum Team!
Please, add NOWNodes in providers list. Thank you!
NOWNodes is a blockchain-as-a-service solution that lets users get access to full Nodes and blockbook Explorers via API. Instant access to 56 blockchain networks, including BTC, ETH, and BSC, which amount has over 1000 coins and tokens.
> add NOWNodes in provider list

- src/content/developers/docs/apis/json-rpc/index.md
> Fix typo in json-rpc/index.md file

- src/content/developers/docs/standards/index.md
Updated the Types of Standard tab to elucidate the different types of EIPs(Standard, Meta & Informational) , and list down the sub-categories of Standard Track EIP.
> Update types of standards

- src/content/developers/docs/smart-contracts/languages/index.md
Addeed
- Vyper Hub for development
- Vyper greatest hits smart contract examples
- Awesome Vyper curated resources
Remove a link to 2020 blog post (no longer topical)
> Even more Vyper links for smart contract programming language documentation

- src/pages/stablecoins.tsx
Fixing the broken link of the `Learn about Dai` button.
None
> Fix broken link on stablecoins page

- src/content/developers/docs/networking-layer/index.md
updates networking layer information ready for post-merge
#7075
> post merge updates: networking layer

- src/data/community-events.json
> Updating EthereumSP 2022 Dates.

- src/content/translations/tr/nft/index.md
- src/intl/tr/page-stablecoins.json
- src/intl/tr/template-usecase.json
Update Turkish (tr) 
- Exploring bucket
> Update Turkish (tr) Exploring bucket

- src/content/translations/id/nft/index.md
- src/intl/id/page-stablecoins.json
- src/intl/id/template-usecase.json
Update Indonesian (id) 
- Exploring bucket
> Update Indonesian (id) Exploring bucket

- src/content/translations/es/nft/index.md
- src/intl/es/page-stablecoins.json
- src/intl/es/template-usecase.json
Update Spanish (es) 
- Exploring bucket
> Update Spanish (es) Exploring bucket

- src/components/UpgradeTableOfContents.tsx
> Found explicit type declarations - anti pattern

- src/components/AssetDownload.tsx
Found unnecessary boolean casts - which could lead to a potential bug risk.
> Found unnecessary boolean casts - bug risk

- src/content/smart-contracts/index.md
Changed 
*Smart contracts can also protect our privacy.*
to 
*Smart contracts can also protect privacy.*
> Smart contract can also protect privacy, not our privacy

- docs/typescript.md
- Adds documentation to typescript.md for typing variables
> Add documentation to typescript.md

- src/content/deprecated-software/index.md
* Added Hyperledger Burrow to deprecated software
* Related to #7413
> Added Hyperledger Burrow to deprecated software page [Fixes #7413]

- src/content/contributing/design-principles/index.md
- src/content/translations/de/contributing/design-principles/index.md
- src/content/translations/it/contributing/design-principles/index.md
- src/content/translations/zh/contributing/design-principles/index.md
Fix broken link on design principles page
#7313
> Fix design principles broken link

- src/content/translations/tr/enterprise/index.md
- src/content/translations/tr/foundation/index.md
- src/content/translations/tr/glossary/index.md
- src/content/translations/tr/history/index.md
Update Learn 2 bucket for Turkish (`tr`) lang
> Update Turkish learn 2 bucket

- src/components/FindWallet/WalletFilterSidebar.tsx
- src/components/FindWallet/WalletPersonasSidebar.tsx
- src/components/FindWallet/WalletTable.tsx
- src/content/contributing/adding-wallets/index.md
- src/data/wallets/wallet-filters.ts
- Change `Buy crypto` and `Withdraw crypto` to `On ramp crypto` and `Off ramp crypto` based on user testing feedback
> Change buy/withdraw crypto labels to on ramp and off ramp

- src/content/glossary/index.md
* Linked the glossary item to the attestations page
* PR related to #7421
> Linked attestation glossary item to attestations page [Fixes #7421]

- src/components/MergeArticleList.tsx
- src/components/ShardChainsList.tsx
- src/content/developers/docs/mev/index.md
- src/intl/en/page-upgrades-index.json
Added "The Hitchhikers Guide To Ethereum" to the following three pages: 
* [Sharding](https://ethereum.org/en/upgrades/sharding/#read-more)
*  [The Merge](https://ethereum.org/en/upgrades/merge/#read-more)
* [MEV](https://ethereum.org/en/developers/docs/mev/)
Also added a new entry in [page-upgrades-index.json](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en/page-upgrades-index.json).
* Related to #6523 (Stale issue)
> Added "The Hitchhikers Guide To Ethereum" (Sharding/The Merge/MEV) [Fixes #6523]

- src/content/translations/de/governance/index.md
Spelling Mistakes
Fixed one spelling mistake in line 34 and corrected the headline in line 58 from IEO to EIP because IEO was wrong.
none
> Fix governance learn page spelling mistakes (German)

- src/content/eips/index.md
See https://eips.ethereum.org/EIPS/eip-1#eip-editors
Updates the EIP Editor list, adds a link to EIP-5069.
N.A.
> Update EIP Editor list

- src/content/security/index.md
I added a great Twitter thread by (ex)-MyCrypto CEO Taylor Monahan showing examples of common phishing messages and emails targeted at crypto users.
> Added new resource for scam prevention

- src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/developers/tutorials/using-websockets/index.md
- src/content/translations/id/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/id/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/id/developers/tutorials/using-websockets/index.md
- src/content/translations/it/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/it/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/it/developers/tutorials/using-websockets/index.md
- src/content/translations/pl/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/pl/developers/tutorials/using-websockets/index.md
- src/content/translations/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/ro/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/ro/developers/tutorials/using-websockets/index.md
- src/content/translations/tr/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/zh/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/zh/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/zh/developers/tutorials/using-websockets/index.md
Alchemy link was redirecting to a general auth page, changed these links to point to to the actual sign-up page.
#7479
> Update redirecting Alchemy sign-up URL

- src/content/developers/docs/apis/javascript/index.md
- src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/developers/tutorials/using-websockets/index.md
- src/content/translations/de/developers/docs/apis/javascript/index.md
- src/content/translations/es/developers/docs/apis/javascript/index.md
- src/content/translations/fr/developers/docs/apis/javascript/index.md
- src/content/translations/hu/developers/docs/apis/javascript/index.md
- src/content/translations/id/developers/docs/apis/javascript/index.md
- src/content/translations/id/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/id/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/id/developers/tutorials/using-websockets/index.md
- src/content/translations/it/developers/docs/apis/javascript/index.md
- src/content/translations/it/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/it/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/it/developers/tutorials/using-websockets/index.md
- src/content/translations/pl/developers/docs/apis/javascript/index.md
- src/content/translations/pl/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/pl/developers/tutorials/using-websockets/index.md
- src/content/translations/pt-br/developers/docs/apis/javascript/index.md
- src/content/translations/ro/developers/docs/apis/javascript/index.md
- src/content/translations/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/ro/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/ro/developers/tutorials/using-websockets/index.md
- src/content/translations/tr/developers/docs/apis/javascript/index.md
- src/content/translations/tr/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/zh/developers/docs/apis/javascript/index.md
- src/content/translations/zh/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
- src/content/translations/zh/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
- src/content/translations/zh/developers/tutorials/using-websockets/index.md
Fixes broken Alchemy documentation links
#7479
> Fix broken Alchemy docs links

- src/content/developers/docs/nodes-and-clients/index.md
> Fix: minor typo

- src/content/developers/docs/smart-contracts/languages/index.md
> EasyFix - Typo fix

- src/content/developers/docs/nodes-and-clients/index.md
Grammatical update.
Grammatical update.
> Update index.md - Grammatical update

- src/content/developers/docs/networks/index.md
Added an extensive research report on the evolution of the Ethereum Testnets from genesis till The Merge upgrade by Yash Kamal Chaturvedi.
He shared it on the ETHGlobal server and I immediately took it to heart ❤️
Furthermore, he said it's also reviewed by Ethereum Developers.
I think it's worth sharing this, it could be helpful for many 🙌
> Add community resource on Networks page

- .gitignore
Added .vscode in .gitignore to prevent commiting local workplace configuration for devs using vscode.
> Added .vscode in .gitignore

- src/content/developers/docs/evm/index.md
> Update index.md  - General grammatical updates

- src/content/developers/docs/blocks/index.md
Updated the grammar in the documentation.
> Update index.md - General grammatical updates

- src/data/community-events.json
I would love to add the Arab blockchain week details to the list. It's a one-stop shop for all web3 events happening in the Arab world from Oct 1st to 8th 2022.
> Add the Arab blockchain week

- src/content/developers/tutorials/learn-foundational-ethereum-topics-with-sql/index.md
updates sql tutorial as part of post-merge updates. Most changes not really merge-specific but actually reflect changes due to eip1559.
#7075
> post-merge updates: sql tutorial

- src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
updates tutorial ready for post-merge
#7075
> post-merge update: guide to ethereum tutorial

- src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
minor updates to uniswap tutorial for post merge. Not actually much that needs changing afaict.
#7075
> post-merge updates: uniswap tutorial

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
updates Nodes as a service page with warning for stakers. @wackerow please sanity check!
#7075
> post merge updates: naas page

- src/content/community/support/index.md
updates "mining" section on community support page ready for post-merge
#7075
> post-merge updates: community support page

- docs/chakra-migration-guide.md
Adds a new section about wrappers & layouts components.
> UI migration guide - wrappers & layout divs

- src/content/translations/de/developers/docs/nodes-and-clients/index.md
Fixed typo/mistranslation in German translation
> Fixed programming language of Erigon Client

- src/content/developers/docs/smart-contracts/index.md
Git blame suggests this has been incorrect since the beginning, so I made up some new words to correct it.
N/A
> Correction about smart contracts not being able to be the source of transactions.

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
> Add guides by Somer Esat

- src/content/translations/tr/whitepaper/index.md
Fixed Ethereum whitepaper link for Turkish page.
Ethereum whitepaper pdf link was broken in Turkish page.
> Fix broken PDF link to whitepaper PDF (Turkish)

- src/content/community/grants/index.md
- Add merge data challenge to grants page
> Add merge data challenge

- src/data/execution-bounty-hunters.csv
> Adding Alex Beregszaszi to the EL bounty hunters

- src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/dagger-hashamoto/index.md
Change "Hashamoto" to "Hashimoto"
> Fix typo: Hashamoto -> Hashimoto

- src/components/Banners/BugBountyBanner.tsx
- src/pages/bug-bounty.tsx
- Add banner on bug bounty page for multiplier
- https://github.com/ethereum/ethereum-org-website/issues/7547
> Add multiplier banner on bug bounty page

- src/pages/layer-2.tsx
- Updates the response code from the change in the l2beat api
> update response from l2beat api

- src/data/community-events.json
We are organizing 2 hackathons around web3 privacy (Zurich and Istanbul) as well as a privacy-focused conference in Bogota. Please let me know if anything is unclear or needs to be changed. Many thanks in advanced!
> Updating upcoming Ethereum events in Switzerland, Columbia and Turkey

- src/content/upgrades/merge/index.md
adds finematics merge video to merge page
> add finematics merge video to merge page

- src/content/desci/index.md
> Added amazing talk on desci and for the funding

- src/content/developers/docs/gas/index.md
The reference site no longer exists:
https://stat.bloxy.info/
Removed the link to the missing resource
> Removed missing resource

- src/data/wallets/wallet-data.ts
Status is a desktop and mobile application that has built-in hot wallet and cold wallet support. It is **NOT** a hardware wallet.
Status.im and [Keycard](https://keycard.tech/) appear to be related, but since they are two very different products, they should likewise be distinct entries.
N.A.
> Unmark status.im as a hardware wallet

- src/content/developers/tutorials/erc20-with-safety-rails/index.md
Fixes a typo. Not much else to say. 
None.
> Fix small typo in erc20 safety rails article

- src/content/translations/zh/foundation/index.md
> fix: minor typo on foundation page (Chinese simplified)

- src/data/community-meetups.json
> Added ETHAnglia Community in Norwich, UK

- src/content/enterprise/index.md
Update Layer 2 section, list of enterprise apps, etc.
> Freshen up Enterprise content

- src/content/translations/zh/eips/index.md
Description
Fixed content discrepancies between Chinese and English versions
> Fix EIP editors list (Chinese)

- src/data/execution-bounty-hunters.csv
For a vulnerability he located in another client.
> +1000 points for Martin Holst Swende

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Reference: https://lighthouse-book.sigmaprime.io/merge-migration.html#connecting-to-an-execution-engine
> Fix lighthouse beacon node command

- src/data/execution-bounty-hunters.csv
+1000 for last reported bug, +500 for EL-2020-10 (https://github.com/ethereum/public-disclosures/blob/master/disclosures/EL.md) which appears to have been previously missed.
> Adding Hwanjo Heo to bounty list

- src/content/eips/index.md
Grammar updates on the `Introduction to Ethereum Improvement Proposals (EIPs)` page
> Fix grammar on EIPs learn page

- src/content/desci/index.md
> Fixed typos in links and added links

- src/content/upgrades/merge/index.md
- src/intl/ca/page-upgrades.json
- src/intl/de/page-upgrades.json
- src/intl/en/page-upgrades.json
- src/intl/es/page-upgrades.json
- src/intl/fa/page-upgrades.json
- src/intl/fr/page-upgrades.json
- src/intl/id/page-upgrades.json
- src/intl/it/page-upgrades.json
- src/intl/ja/page-upgrades.json
- src/intl/nl/page-upgrades.json
- src/intl/pt-br/page-upgrades.json
- src/intl/ru/page-upgrades.json
- src/intl/sw/page-upgrades.json
- src/intl/tr/page-upgrades.json
- src/intl/zh/page-upgrades.json
Update info in callout on `/upgrades/merge` with the right date, and link out to the merge announcement blog post.
> update merge date and info in callout

- src/content/developers/docs/standards/index.md
There are quite a few token standards that build on other token standards. All the standards listed here are final.
N.A.
> Add placeholders for token extensions

- src/content/developers/docs/transactions/index.md
Helping the newcomer to quick understanding total gas fee from bob account.
> Add more explanation for total gas fee

- src/content/enterprise/index.md
- src/content/translations/de/enterprise/index.md
Added Zero Services GmbH to "enterprise services". With reference to our discussions in #7608 
#7607 
#7608
> added zeroservices to enterprise services

- src/content/dao/index.md
Add or improve sections for:
- DAO governance
- DAO laws
- DAO examples
> Improve page on DAOs

- src/content/community/online/index.md
Added Matos Discord to /community/online/index.md
Added the following `SocialListItem` to `src/content/community/online/index.md`
```html
<SocialListItem socialIcon="discord">
<Link to="https://discord.gg/G4vVhQu3">Matos Discord</Link>
- web3 creators community where builders, industrial figureheads, and Ethereum enthusiasts hang out. we're passioned about web3 development, design, and culture. come build with us.
</SocialListItem>
> Updated online communities to include Matos

- src/content/developers/docs/nodes-and-clients/index.md
Update merge testnet list on nodes and clients developer docs page
> Update merged testnets list

- src/content/developers/docs/accounts/index.md
Added an important distinction between Externally Owned Accounts (EOA) and Contract accounts regarding the presence of private keys.
> Update content in accounts/index.md

- src/content/developers/docs/standards/tokens/erc-4626/index.md
Changed 'Widthdraw' to 'Withdraw'
> typo at line #189

- src/content/upgrades/merge/index.md
updates merge estimate post-goerli including link to bordel.wtf
> update merge timing estimate

- src/content/glossary/index.md
Updates more glossary terms for post-merge changes
Extension of #7190
> Post merge glossary updates

- src/content/developers/docs/smart-contracts/verifying/index.md
> Fix typo in verifying smart contracts page

- src/content/desci/index.md
Context: https://discord.com/channels/714888181740339261/727898649006309377/1018969307344031845
Use `YouTube` component instead of the fixed width iframe.
> Fix embed YouTube width

- src/data/community-meetups.json
> Ethereum nyc meetup added

- src/data/translation-reports/month/month-data.json
- Update alltime-data.json and month-data.json to reflect translations in August
> update translation leaderboard data for August

- src/content/developers/docs/accounts/index.md
Just added the EOA definition since it's used a lot across technical documentation
> Add EOA definition

- src/components/EnergyConsumptionChart.tsx
- src/content/energy-consumption/index.md
- src/intl/en/page-what-is-ethereum.json
- src/pages-conditional/what-is-ethereum.tsx
- src/templates/static.tsx
Preview: https://postmerge-energyconsumptionchart.gtsb.io/en/energy-consumption
- Refactors EnergyConsumptionChart to be mobile responsive
- Replaces use of `.png` on `/energy-consumption` page with this component instead
> Energy consumption chart update

- src/hooks/useConsoleEasterEgg.ts
- src/pages/index.tsx
- Adds post-merge console log easter egg
> Console easter egg

- src/data/community-meetups.json
> Added CryptoSD meetup

- src/data/community-events.json
> Added details for Web3SD conference

- docs/chakra-migration-guide.md
> Chakra migration guide - add breakpoints guidance

- src/components/EthVideo.tsx
Migrate `EthVideo.tsx` component to Chakra.
Includes refactor of `div` component.
#6374
> refactor `EthVideo.tsx` component with chakra UI

- src/components/Layout.tsx
- src/pages/index.tsx
Patch confetti easter egg for mobile homepage
> Patch: confetti

- package.json
- src/components/Layout.tsx
- src/pages/index.tsx
***
- Patch: remove confetti from homepage (#7858) @wackerow
- v6.4.2 (#7859) @samajammin
***
Thank you @samajammin and @wackerow for the contributions! :trophy:
***
> Deploy v6.4.2

- src/content/upgrades/merge/index.md
There was a small typo on the Merge upgrade released today!!
I deleted the extra 'the' in the paragraph! :)
Typo issue!!
> Fix typo on The Merge

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Fixed typo.
```
accross -> across
```
> Fix typo in nodes-as-a-service/index.md

- src/components/DocsNav.tsx
- Migrates `DocsNav` component from `emotion` to Chakra-UI per [Chakra Migration Guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md)
#6374
> Migrate DocsNav to Chakra

- src/components/Logo.tsx
- Migrates `Logo` component from `emotion` to `chakra-ui`
#6374
> Migrate Logo to Chakra

- src/components/Checkbox.tsx
Migrate Checkbox from styled component to ChakraUI
https://github.com/ethereum/ethereum-org-website/issues/6374
> Migrate Checkbox from styled component to ChakraUI

- src/content/upgrades/merge/index.md
> fix typo on merge page

- src/content/social-networks/index.md
* Noticed while translating. 
* Not related to an open issue.
> Fixed small typo in index.md [social-networks]

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Update the links to the "client diversity" page. 
[Fixes #7896]
> update links to client diversity [Fixes #7896]

- src/content/staking/pools/index.md
Add "d" to the end of "encourage"
> Fix typo on staking pools page

- src/scripts/crowdin-import.ts
- Remove zh lang buckets accidentally added to crowdin-import 
None
> Remove zh lang buckets accidentally added to crowdin-import 

- src/content/developers/docs/ides/index.md
Per @samajammin's suggestion, I added Tenderly Sandbox to the web-based IDEs section. Also tweaked the link styles a bit to make them cleaner.
> Add Tenderly Sandbox to IDEs

- src/content/developers/docs/web2-vs-web3/index.md
Slight tweak, but "you can pretty much program anything" < "you can program pretty much anything"
> Slight sentence tweak on web2 vs web3 developer docs

- static/.well-known/matrix/server
That's needed for setting up the federation of the matrix server.
> Matrix federation delegation

- src/content/developers/docs/blocks/index.md
Fixed spelling of containign to containing.
N/A
> Fix developer docs typo.

- src/data/staking-products.json
[Kiln.fi has been audited by Prescient Assurance](https://drive.google.com/file/d/1K-Q0r2lXqnOePsV3e7c9sErl6iz8EKHX/view?usp=sharing). Added this to Kiln's audit section.
#7628
> Add Kiln audit

- src/content/desci/index.md
> Added an amazing article on science funding + desci

- src/components/Morpher.tsx
- Migrates `Morpher` component from `emotion` to `chakra-ui`
#6374
> Migrate Morpher to Chakra

- src/components/InfoBanner.tsx
- Migrates `InfoBanner` component from `emotion` to `chakra-ui`
#6374
> Migrate InfoBanner to Chakra

- src/content/developers/docs/scaling/optimistic-rollups/index.md
Added link for the Data Availability page.
Removed a repeated link in the 'Further reading' section
> Minor changes to the OR page

- src/components/ImageCard.tsx
Migrates `ImageCard `component from `emotion `to `chakra-ui`
#6374
> Migrate ImageCard to Chakra

- src/content/developers/docs/scaling/zk-rollups/index.md
Remove the claim in the zk rollups page that STARKs don't support recursion. This is not true.
Source: https://medium.com/@starkware/recursive-starks-78f8dd401025
> Remove incorrect zk-stark information

- src/content/developers/docs/programming-languages/dot-net/index.md
- src/content/developers/docs/programming-languages/javascript/index.md
> Fix: typos

- src/components/Nav/index.tsx
Fixes #8018
Added aria-label to boost accessibility
> Aria-label for homepage link

- src/intl/ar/page-run-a-node.json
- src/intl/en/page-run-a-node.json
- Removes mentions of mining from run-a-node page
#7075
> Update run-a-node copy for post-merge

- src/content/translations/id/nft/index.md
- src/intl/id/page-dapps.json
- src/intl/id/page-stablecoins.json
Update Indonesian (id) Exploring buckets
> Update Indonesian (id) Exploring buckets

- src/intl/en/page-upgrades-get-involved-bug-bounty.json
Removed reference to "POW" in bug bounty program
> Removed reference to "POW" in bug bounty program

- src/content/developers/docs/smart-contracts/upgrading/index.md
> Fix typo on upgrading smart contracts page

- src/data/execution-bounty-hunters.csv
@holiman found a vulnerability, upping his score
> Increasing Martin's score on the bounty board

- src/data/community-events.json
> ETHLisbon Hackaton is missing and should be added to upcoming events on the website

- src/components/SectionNav.tsx
Converted SectionNav.tsx from styled-components to ChakraUI
#6374
> SectionNav refactor to ChakraUI

- src/components/MarkdownTable.tsx
Migrates `MarkdownTable` component from `emotion` to `chakra-ui`
#6374
> Migrate MarkdownTable to Chakra

- src/content/dao/index.md
> Adding a great read by Vitalik on DAOs

- src/content/bridges/index.md
There weren't any resources from 2022. Good to keep up to date on how bridges / cross-chain has evolved.
> Added more relevant links in #further-reading

- src/content/developers/docs/smart-contracts/upgrading/index.md
Updated relative to absolute link 
see #8134
> Updated relative to absolute link 

- src/content/developers/docs/smart-contracts/upgrading/index.md
Fix broken OpenZeppelin url for proxy patterns
https://github.com/ethereum/ethereum-org-website/issues/8134
> Fix broken OpenZeppelin url for proxy patterns

- src/content/translations/es/web3/index.md
- Delete angle bracket in text
> :pencil2: [REMOVE] Angle bracket in text

- src/@chakra-ui/gatsby-plugin/styles.ts
Added global styles to temporarily fix list formatting issue.
Fixes #8031
> Fix list styles

- src/content/history/index.md
Fix missing # for paris summary header tag
> Fix header tag for paris summary

- src/content/translations/de/decentralized-identity/index.md
- src/content/translations/de/defi/index.md
- src/content/translations/de/smart-contracts/index.md
- src/content/translations/de/social-networks/index.md
Update German (de) Use cases bucket
> Update German (de) Use cases bucket

- src/content/translations/fr/developers/tutorials/how-to-mint-an-nft/index.md
- src/content/translations/fr/developers/tutorials/how-to-view-nft-in-metamask/index.md
- src/content/translations/fr/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
- src/content/translations/fr/developers/tutorials/uniswap-v2-annotated-code/index.md
- src/intl/fr/page-developers-tutorials.json
Update French (fr) Tutorials 1 bucket
> Update French (fr) Tutorials 1 bucket

- src/content/community/research/index.md
fix: #8127 
I am not sure if this link is correct, but I found the link on the official blog and replaced it.
https://blog.ethereum.org/2022/03/23/finalized-no-34
I have confirmed that the link works.
> Fix: Eth R&D Discord channel link

- src/content/translations/es/decentralized-identity/index.md
- src/content/translations/es/social-networks/index.md
Update Spanish (es) Use Case bucket
> Update Spanish (es) Use Case bucket

- src/data/community-meetups.json
Add EthPDX to Ethereum meetups list
None
> Add EthPDX to Ethereum meetups list

- src/content/translations/fr/developers/docs/accounts/index.md
Small grammar fix
No related open issue.
> Update french translation for accounts (small grammar fix)

- src/content/developers/tutorials/yellow-paper-evm/index.md
some updates to the yellow paper page to make it a bit easier to understand and clarify for post-merge.
> some clarifications on the yellow paper page

- src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/ethash/index.md
> Fix link to Dagger-Hashimoto

- src/content/community/grants/index.md
> added an extensive list of web3 grants

- src/content/developers/tutorials/erc20-with-safety-rails/index.md
> updated index.html

- src/components/MatomoOptOut.tsx
Migrates `MatomoOptOut` component from `emotion` to `chakra-ui`
#6374
> Migrate MatomoOptOut to Chakra

- src/data/community-events.json
Added a new event.
The  PyChain 2022 is the first virtual blockchain developer conference targeting the Python ecosystem and Python devs. The topics cover quantitative finance and AI, APIs, trading automation, web3, smart contract development, blockchain core development, security and testing. The goals of the event include introducing blockchain development to new developers and sharing the best practices across different blockchain community boundaries.
> Added PyChain 2022 to events

- src/content/enterprise/index.md
On line 151 the url was duplicated, I have removed the duplicated text and now the page displays correctly.
On line 163 the url was no longer available, so I have added the url from waybackmachine and it can now be viewed
Correcting external urls which are no longer viewable.
> Corrected external broken links

- src/content/community/grants/index.md
I removed the extra bullet point from "grants" page!
None filed
> Remove extra bullet point from "grants" page

- src/content/developers/docs/transactions/index.md
> small edit in index.md

- gatsby-browser.tsx
- gatsby-ssr.tsx
Fix rendering different output on pages that do not have a lang specified in the url (only affects dev mode).
> Fix hydration issue on DEV

- src/content/developers/docs/data-structures-and-encoding/rlp/index.md
This PR updates the broken patricia merkle trie link in the RLP developer docs
> Update patricia merkle trie broken link in RLP docs

- src/content/developers/docs/nodes-and-clients/index.md
Updates the lighthouse description in the docs 
Fixes #8227
> update the lighthouse description in the docs [Fixes #8227]

- src/data/community-events.json
> ETH Miami was moved to 2023 and the exact date is TBA

- src/content/developers/docs/networking-layer/index.md
Minor fix to improve sentence flow
s/Similarly/Similar
> Fix grammatical error in consensus discovery

- src/content/staking/solo/index.md
* Fixed small typo in string, noticed while translating on Crowdin. 
* Not related to an open issue.
> Small typo fix [staking/solo]

- src/data/community-events.json
Unfortunately noticed his only after the merge. 
Probably messed up the text when copy-pasting it to events JSON.
> Fixd type in PyChain 2022 description in events

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
> feat: fixed broken link

- src/data/community-events.json
https://www.ethdenver.com has the 2023 dates
> Update ETHDenver 2023

- src/content/translations/zh/developers/docs/transactions/index.md
> Improve a sentence in transactions developer docs (Chinese)

- src/content/developers/docs/consensus-mechanisms/pos/index.md
The current link with a trailing slash is broken (404).
> Fix link to ethos.dev

- src/components/CopyToClipboard.tsx
Refactor `CopyToClipboard` using chakra-ui
#6374
> refactor(copyToClipboard): add chakra ui Box component

- src/content/desci/index.md
> Adding blockchain for science telegram

- src/content/dao/index.md
Hello! 
I've added Tally.xyz as a resource for Governor DAOs (Compound, Uniswap, Gitcoin, ENS, NounsDAO, etc...) in the ecosystem. Thank you!
> Update index.md to add Tally.xyz

- README.md
> Grammar enhancement

- src/components/RollupProductDevDoc.tsx
Migrates component to Chakra UI
#6374
> Migrate `RollupProductDevDoc` to Chakra

- src/components/UpgradeBannerNotification.tsx
> Migrate UpgradeBannerNotification.tsx to chakra

- src/content/developers/docs/data-structures-and-encoding/web3-secret-storage/index.md
> doc: fix missing variable identifier letter

- src/content/governance/index.md
Changed phrasing of trade-offs for improved clarity
> _"some EIPs are straightforward..., some are more complex **and inherently tradeoffs** which will affect different stakeholders in different ways..."_
The phrase 'inherently tradeoffs' does not really identify a subject in the sentence. This PR solves the issue by replacing 'inherently' with 'come with' to imply that 'EIPs come with trade-offs'.
> updates governance page

- src/intl/de/page-developers-local-environment.json
Fixed a small grammar error in the documentation.
@minimalsm you missed this one during PR #8108. 😅
> Fixed a typo in docs

- src/content/developers/docs/networks/index.md
Hi, I'm a blockchain infrastructure & software engineer from All That Node.
We are also providing Ethereum Goerli faucet.
So I added our web page link.
Happy Building :)
> Add a new faucet

- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
> Fix typo on run a node developer docs page

- src/content/developers/docs/frameworks/index.md
- src/content/developers/docs/ides/index.md
Added Docs & forums links of respective IDEs in IDEs section page. Also added some helpful article links in the further reading section of the frameworks page & IDE page.
Added some articles in the further reading sections that are well written and can help the reader.
> Added docs links for IDEs & added furthur readings for frameworks & tools

- src/components/Emoji.tsx
- src/components/TranslationBanner.tsx
Migrates TransitionBanner component from emotion to chakra-ui
#8052
> Migrate TransitionBanner to Chakra [Fixes #8052]

- src/content/developers/docs/nodes-and-clients/client-diversity/index.md
Solved issue https://github.com/ethereum/ethereum-org-website/issues/8393
Changed YouTube to YouTube
> Updated Youtube to YouTube

- src/content/community/online/index.md
Capitalize letters at the beginning of new sentences!
> Fixed typos in online communities

- src/data/wallets/wallet-data.ts
Updated with the twitter account they list on https://www.enkrypt.com/
> Change enkrypt wallet's twitter account

- src/content/community/language-resources/index.md
Hi, I added a Russian section to the "Language resources" page, maybe it will be useful for someone.
It includes link to our educational platform for web3 builders that we create within @cyberacademydev team.
Thank you so much for the PR merge!
> Adding a Russian section to the Language Resources page

- src/content/developers/docs/apis/json-rpc/index.md
Add the effective gas price and the type to the transaction receipt documentation and replace the example for something functioning on mainnet.
Related issue: #7549
> Add effective gas price, type, replace the example

- src/content/nft/index.md
Adds a new use case to the NFT page: tokengating and corresponding anchor link. Solves #8253.
#8253
> Adds tokengating use case to NFT page

- src/intl/en/page-upgrades-vision.json
Make vision clearer / less confusing: neutrality is a clearer benefit of decentralization than data privacy.
> Decentralization leads to neutrality

- src/content/community/grants/index.md
> Update index - add UMA Developer Support grants.md

- src/data/quizzes/questionBank.ts
Fixes the correct answer choice for a quiz question
None filed, reported via Discord
> Patch: quiz answer

- src/data/quizzes/questionBank.ts
IMHO the sentence before made no sense - fixed it
> Fix fee explanation

- src/content/energy-consumption/index.md
Merged #8376 before [this change](https://github.com/ethereum/ethereum-org-website/pull/8376#discussion_r1012715027) could be implemented. This PR implements the change.
> Wording improvement on energy consumption page 

- src/content/translations/fr/developers/docs/standards/tokens/erc-777/index.md
Some sentences did not the right translation due to automatic translation and was confusing.
> Update erc-777 developer docs (French)

- src/content/community/online/index.md
> Fix typo in online/index.md

- src/data/community-meetups.json
Update UAE flag emoji name, to properly display on Meetup listings
- Fixes https://github.com/ethereum/ethereum-org-website/issues/8478
- reported on Discord:
> Patch: UAE flag emoji name

- src/content/developers/tutorials/yellow-paper-evm/index.md
adds a more clear description of the EVM memory types 
#8307
> update yellow paper -> clarify memory types

- src/content/translations/zh/developers/docs/oracles/index.md
> Update oracles developer docs (Chinese)

- src/content/developers/docs/mev/index.md
Add "-" to a link description for consistency
> Add "-" to a link description for consistency

- src/content/developers/docs/evm/index.md
"All Ethereum clients" seems to suggest that consensus clients might also include an EVM implementation. This change is to add more clarity to the reader.
> enhance(docs): specify execution clients

- src/content/translations/fr/developers/docs/standards/tokens/erc-20/index.md
Added caps to the second list of item for more consistency.
Slightly 
Updated the example definition to be more friendly instead of being directly translated by a machine to ease the comprehension.
> Update erc-20 developer docs (French)

- src/data/quizzes/questionBank.ts
Tweaks answer explanations to the 'ETH is valuable' to make more sense. 
Context: https://github.com/ethereum/ethereum-org-website/issues/7555#issuecomment-1301979631
#7555
> Update quiz question: 'ETH is valuable because' answer explanations

- src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Add All That Node on list of Node-as-a-service
I updated another Node-as-a-service on the list.
> Add All That Node on list of Node-as-a-service

- src/content/developers/docs/programming-languages/rust/index.md
- src/content/translations/de/developers/docs/programming-languages/rust/index.md
- src/content/translations/es/developers/docs/programming-languages/rust/index.md
- src/content/translations/fr/developers/docs/programming-languages/rust/index.md
- src/content/translations/hu/developers/docs/programming-languages/rust/index.md
- src/content/translations/id/developers/docs/programming-languages/rust/index.md
- src/content/translations/it/developers/docs/programming-languages/rust/index.md
- src/content/translations/pl/developers/docs/programming-languages/rust/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/rust/index.md
- src/content/translations/ro/developers/docs/programming-languages/rust/index.md
- src/content/translations/tr/developers/docs/programming-languages/rust/index.md
- src/content/translations/zh/developers/docs/programming-languages/rust/index.md
Remove broken Oasis links (they have no replacement link)
#8503
> Remove broken Oasis links

- src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
Highlighted by @samajammin [on Discord](https://discord.com/channels/714888181740339261/727898649006309377/1039182241630257203)
> Fix formatting on rewards and penalties page

- src/content/developers/docs/oracles/index.md
> Removed duplicate 'can'

- src/components/Pill.tsx
Convert the `Pill.tsx` component to Chakra
Epic: #6374
> convert the Pill component to Chakra

- src/components/UpgradeStatus.tsx
A quick refactor, applying the use of Chakra's `useColorModeValue` hook to tidy up the logic of the border styling. :)
N/A
> refactor(upgrade-status): implement `useColorModeValue`

- src/data/translation-reports/month/month-data.json
- update month-data.json and alltime-data.json
> update translation stats

- src/components/Pill.tsx
Fix bg color used in the Pill component.
#8550
> Fix `Pill` bg color

- src/content/upgrades/merge/issuance/index.md
- Expands some of the math explanations
- Update gwei value for deflation used in tldr to match the math beneath
- Remove unused comment
None filed
> Merge-related ETH issuance page adjustments

- src/content/community/grants/index.md
Replace the outdated Merge Data Challenge grants link with the Layer 2 grants one.
> Remove old Merge Data Challenge grants link

- src/data/community-events.json
> Add ETHMiami to community events

- src/content/developers/docs/nodes-and-clients/index.md
> Fix typo on nodes and clients developer doc

- src/content/developers/docs/programming-languages/rust/index.md
Removed invalid link pointing to invalid dns. Not alternate blog exist for the same topic
- [Getting Started with Enigma - In Rust Programming Language](https://blog.enigma.co/getting-started-with-discovery-the-rust-programming-language-4d1e0b06de15)
> Remove broken link

- src/content/translations/it/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
- src/content/translations/it/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit/index.md
- src/content/translations/it/developers/tutorials/erc20-annotated-code/index.md
- src/content/translations/it/developers/tutorials/hello-world-smart-contract/index.md
- src/content/translations/it/developers/tutorials/interact-with-other-contracts-from-solidity/index.md
- src/content/translations/it/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md
- src/content/translations/it/developers/tutorials/nft-minter/index.md
- src/content/translations/it/developers/tutorials/reverse-engineering-a-contract/index.md
- src/content/translations/it/developers/tutorials/run-node-raspberry-pi/index.md
- src/content/translations/it/developers/tutorials/send-token-etherjs/index.md
- src/content/translations/it/developers/tutorials/testing-smart-contract-with-waffle/index.md
- src/content/translations/it/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
- src/content/translations/it/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
Update Italian (it) Tutorials II bucket
> Update Italian (it) Tutorials II bucket

- src/content/nft/index.md
update nft page so that it links out to the energy consumption page
> nft page: link out to energy consumption page

- src/content/community/grants/index.md
- src/content/translations/ca/community/grants/index.md
- src/content/translations/it/community/grants/index.md
- src/content/translations/nl/community/grants/index.md
- src/content/translations/ro/community/grants/index.md
I went through all the content and replaced all locations with Consensys Grants with MetaMask Grants.
fixes #8522
> Added MetaMask grants and removed Consensys grants

- src/scripts/markdown-checker.js
Updates the markdown checker script:
- ensure skill level matching either 'beginner', 'intermediate', or 'advanced'
- ensure sidebar props are not present
> Update markdown checker script

- src/data/execution-bounty-hunters.csv
> Upped score for Chainsecurity

- src/content/developers/docs/bridges/index.md
The right word is systemic
- systematic = methodical  (= there is a plan/structure in place) 
- systemic = affects every part of an entire system
> Use systemic rather than systematic

- src/content/developers/docs/apis/backend/index.md
> Add NFTPort to backend APIs

- src/content/developers/docs/apis/json-rpc/index.md
- src/content/developers/docs/consensus-mechanisms/pos/weak-subjectivity/index.md
- src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/dagger-hashimoto/index.md
- src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
- src/content/developers/docs/data-and-analytics/block-explorers/index.md
- src/content/developers/docs/intro-to-ethereum/index.md
- src/content/developers/docs/nodes-and-clients/client-diversity/index.md
- src/content/developers/docs/nodes-and-clients/index.md
- src/content/developers/docs/nodes-and-clients/run-a-node/index.md
- src/content/developers/docs/transactions/index.md
Various small changes that fix minor issues encountered while auditing external content. Mostly removing or updating  outdated links/content and typo fixes.
#8285
> various post-merge cleanup items

- src/content/translations/de/developers/docs/programming-languages/python/index.md
- src/content/translations/es/developers/docs/programming-languages/python/index.md
- src/content/translations/fr/developers/docs/programming-languages/python/index.md
- src/content/translations/hu/developers/docs/programming-languages/python/index.md
- src/content/translations/id/developers/docs/programming-languages/python/index.md
- src/content/translations/it/developers/docs/programming-languages/python/index.md
- src/content/translations/pl/developers/docs/programming-languages/python/index.md
- src/content/translations/pt-br/developers/docs/programming-languages/python/index.md
- src/content/translations/ro/developers/docs/programming-languages/python/index.md
- src/content/translations/tr/developers/docs/programming-languages/python/index.md
- src/content/translations/zh/developers/docs/programming-languages/python/index.md
Updates broken 'mamba.black' links to use the GitHub repo link instead.
#8681
> Update broken Mamba links

- src/content/translations/it/developers/docs/nodes-and-clients/run-a-node/index.md
- src/content/translations/zh/developers/docs/nodes-and-clients/run-a-node/index.md
Fix broken Ethdocker links in non-English langs
#8743
> Fix broken Ethdocker link (Italian and Chinese)

- src/content/translations/zh/developers/tutorials/send-token-etherjs/index.md
Updates error content [Fixes #8571]
> Fix error on send ether tokens tutorial (Chinese simplified) [Fixes #8571]

- src/components/SkipLink.tsx
Refactored `SkipLink.tsx` component with Chakra UI
#6374
> Refactor `SkipLink.tsx` component to use ChakraUI

- docs/best-practices.md
> Update i18n docs

- src/intl/en/page-what-is-ethereum.json
replaces missing "h" in TWh/yr in chart title
#8769
> fix unit in energy chart
