ethereum/ethereum-org-website

src/content/developers/tutorials/send-token-etherjs/index.md
Not working:
window.provider = new InfuraProvider("ropsten")
Fixed: 
window.ethersProvider = new ethers.providers.InfuraProvider("ropsten")
=> Update InfuraProvider on send-token-ethersjs tutorial

src/content/developers/tutorials/run-light-node-geth/index.md
/ is missing in the URL, which leads to an error when clicked.
=> Missing / in URL

src/content/developers/docs/standards/tokens/erc-1155/index.md, src/content/developers/docs/standards/tokens/erc-721/index.md
- add alchemy nft api docs to further reading for erc-721 and erc-1155 pages. This api supports these standards.
=> add alchemy nft api to nft standards

src/content/developers/tutorials/erc20-annotated-code/index.md
Fixed typo.
```
inheritence -> inheritance
```
=> Fix typo in erc20-annotated-code/index.md

src/content/developers/tutorials/nft-minter/index.md
- Adds missing header IDs that were causing errors during Gatsby builds
None
=> Add missing header IDs in NFT minter tutorial

src/content/contributing/translation-program/translators-guide/index.md
The two-letter language code for Chinese Simplified in the translators guide is incorrect, it should be 'zh'.
=> Fix Chinese Simplified language code

src/components/Contributors.js
passed alt to contributor images
passed alt to contributor images
passed alt as `{contributor.name}`props in contributor card 
https://github.com/ethereum/ethereum-org-website/issues/5816
=> Update Contributors.js to pass alt text [a11y]

src/content/community/get-involved/index.md
DXdao has been live on Ethereum for almost 3 years, and it is still growing.
I added it to the list of DAOs people interested in the Ethereum ecosystem should consider joining.
=> Add DXDao to list of DAOs

src/content/contributing/translation-program/faq/index.md
Remove mention of 'Eth2' and change punctuation of Beacon Chain in the terminology section of the translator FAQs.
=> Remove mention of Eth2 and change punctuation of Beacon Chain

src/content/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
Fixed typo in 'src/content/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md'. Changed 'cosntraint' to 'constraint'.
Related issue: [#5853]
=> Fixed spelling of 'constraint' [Fixes #5853]

src/content/developers/tutorials/run-node-raspberry-pi/index.md
Fixed typo in 'src/content/developers/tutorials/run-node-raspberry-pi/index.md'. Changed 'execution later' to 'execution layer'. 
Related issue: [#5852]
=> Fixed spelling of 'execution layer' [Fixes #5852]

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
Fixed typos in 'src/content/developers/tutorials/uniswap-v2-annotated-code/index.md'. Changed 'defintion' to 'definition' & changed 'Skip' to 'Skim'.
Related issue: [#5855]
=> Fixed errors on the Uniswap-v2 contract walkthrough page [Fixes #5855]

src/content/developers/tutorials/using-websockets/index.md
Typo
Simple Typo
`address` instead of `adddress`
=> Fix typo in using web-sockets tutorial

src/components/Checkbox.js, src/components/SelectableCard.js, src/components/WalletCompare.js
- 'Checkbox' in Checkbox.js has a new ariaContent property (line 56, Checkbox.js).
- 'HiddenCheckbox' has a new attribute 'aria-label' with the ariaContent value in it (line 67, Checkbox.js).
- 'StyledCheckbox' in SelectableCard.js has the title.id value (translated with the translateMessageId function) passed for 
'ariaContent' (line 58, SelectableCard.js).
- Related to issue: [#5788]
1. Add a new property to Checkbox. E.g: 'ariaContent' (line 56, Checkbox.js).
2. Add an aria-label attribute to HiddenCheckbox (line 67, Checkbox.js).
3. Put the ariaContent (created in step 1) in the aria-label (line 67, Checkbox.js).
4. In StyledCheckbox add the ariaContent property (line 58, SelectableCard.js).
5. Now take 'title.props.id' and use the translateMessageId-method as value for ariaContent …
=> Aria-labels added the wallets checkboxes [Solves #5788]

src/content/developers/docs/nodes-and-clients/index.md
"Nodes as a service" was written as "Nodes as a services" (in src/content/developers/docs/nodes-and-clients/index.md, line 106). 
Not related to an open issue.
=> Fixed spelling of 'service' in dev docs

src/content/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
Changed: allowed[owner][msg.sender] = allowed[owner][msg.sender]+numTokens;
To: allowed[owner][msg.sender] = allowed[owner][msg.sender]-numTokens;
In the example script of a basic ERC20 Token:
The allowance is increased instead of decreased by the number of tokens transfered via the transferFrom function.
=> Fix bug in ERC-20 tutorial

src/content/contributing/adding-products/index.md
As discussed at PR grooming: adds a note about us not actively adding wallets until we refine the current listing criteria.
#5105
=> Add a note on adding wallets to ethereum.org

src/content/developers/docs/smart-contracts/anatomy/index.md
Issue #5862 suggested a potential bug in a tutorial smart contract relating to assignment of addresses in a mapping. 
There is no bug, the issue is that `address(0)` is the zero-address. The contract asserts that the current mapping between ID and address is the zero address before allowing the mapping to update (essentially confirming that a particular ID is "available" before allowing a transfer).
This isn't necessarily obvious and is not currently documented in the in-line comments, so I added a short comment.
#5862
=> add comment explaining zero address to tutorial

src/content/developers/docs/frameworks/index.md
Added three punctuation marks (because all other sentences had them except those three):
- Ethereum development environment for professionals**.** (line 39)
- A platform for developing blockchain applications on the JVM**.** (line 59)
- The Graph for querying blockchain data efficiently**.** (line 80)
=> Missing punctuation marks added to sentences [dev docs]

src/content/developers/docs/intro-to-ether/index.md
Fixed a typo in order to provide more clarity to the sentence
A particular sentence in intro to ether page was not well formed. it was talking about ether but it referred to The merge as the one needed to validate blocks on the Mainnet, therefore, i added a comma and the word 'it'.
[#5717]
=> Fix typo in intro to ether doc [Fixes #5717]

src/content/developers/tutorials/erc20-annotated-code/index.md
Fix typo on ERC-20 Contract Walkthrough page [Fixes #5892]
I have changed buf to but
changed a minor typo.
=> Fix typo on ERC-20 Contract Walkthrough page [Fixes #5892]

src/content/developers/tutorials/erc20-annotated-code/index.md
fixed typo at line 905
changed `buf` to `but`
https://github.com/ethereum/ethereum-org-website/issues/5892
=> Fix typo in ERC-20 annotated code tutorial

src/data/community-meetups.json
This PR adds the [Ethereum Vancouver](https://www.meetup.com/ethvancouver-meetup-group/) meetup group to the list of meetups. Here are some social links:
- http://ethvancouver.org/ 
- http://discord.ethvancouver.org/
- http://meetup.ethvancouver.org/
Note that this is a different group than the previous "Vancouver Ethereum Meetup". That group has since rebranded to the Vancouver Blockchain Meetup. In contrast, this new meetup aims to be Ethereum and EVM-focused and will focus on more technical matters as well.
I would recommend removing the other Vancouver meetup from the list since they are no longer Ethereum-focused and it is a meetup group run by a staunch BSV supporter. I have nothing against that meetup, but it may cause confusion for those looking for a local meetup. They also …
=> Add Ethereum Vancouver to list of meetups

src/data/community-meetups.json
As I mentioned briefly in #5826, the old Vancouver Ethereum meetup group is now a BSV maxi group.
If you click the link: https://www.meetup.com/Vancouver-Ethereum-Meetup
You will be greeted by a "Bitcoin is BSV" meetup:
My understanding is that the Ethereum Foundation would not want to confuse users and demonstrate supporting a BSV maxi group that has nothing to do with Ethereum on their website. Therefore, I propose removing this meetup from the list of Ethereum meetups.
=> Remove legacy meetup (they are now BSV maxis)

src/content/developers/tutorials/nft-minter/index.md
Hey, following up on [this](https://github.com/ethereum/ethereum-org-website/pull/2653). My job while interning at Alchemy was just to put up the existing NFT Minter tutorial from our website on the Ethereum Foundation. After looking at the thread of comments a few months later on the linked PR, @smudgil is absolutely right — she is the rightful owner of this tutorial, and I had no clue!
I've gone ahead and taken down the Twitter post that Sumi linked, and in addition, this is a PR with a request to change the top level name to Sumi's GitHub. Please see that this PR is merged, and Sumi becomes the official rightful owner here.
Thank you!! @samajammin @wackerow @minimalsm @pettinarip
=> Change author

src/content/developers/docs/apis/backend/index.md
Added punctuation marks:
- BlockCypher - Ethereum Web APIs`.`
- Zmok - Speed-oriented Ethereum nodes as JSON-RPC/WebSockets API`.`
=> Missing punctuation marks added [dev docs]

src/content/deprecated-software/index.md
Adds some deprecated clients and related software to ethereum.org deprecated software page as part of content migration from ethdocs.org and eth.wiki.
Adds:
Ethereum-H
Minimal
Mana
ruby-ethereum
note that Aleth was also known as cpp-ethereum
#5731 #5921 #5690
=> Add deprecated software to "deprecated software" page

src/content/developers/docs/programming-languages/ruby/index.md
Removed redundant punctuation marks from list.
Changes in: `src/content/developers/docs/programming-languages/ruby/index.md`
=> Removed redundant punctuation marks [dev docs]

README.md, src/components/ReleaseBanner.js, src/components/Roadmap.js, src/components/StatsBoxGrid.js, src/components/TranslationsInProgress.js, src/constants.js, src/pages/layer-2.js
Currently to develop locally with our lambda functions, we are using `netlify-lambda` to build and then create a server to serve them. There is no need to do this anymore since we now have them built and hosted by Gatsby running `gatsby develop`.
This PR uses the functions hosted by Gatsby for local development. It improves the DX since you don't need to have two separate processes running in parallel.
=> Use Gatsby functions for local development

src/components/SkipLink.js
Problem: when the user clicks on the "Skip to main content" link, it is scrolling too much and the content is behind the nav bar.
In this PR: adds more space to the anchor target div to avoid being behind the nav bar.
=> Anchor div space

src/content/developers/docs/smart-contracts/index.md
Add link to smart contract intro.
We may want to add a similar notification & link on other smart contract documentation page? Main user journey I'm looking to solve for here is non-technical folks who land directly on these pages (which rank very well in search, e.g. for "smart contracts").
None
=> Add link to smart contract intro

src/content/developers/docs/smart-contracts/composability/index.md
One of the links under Related Tutorials section in Smart contract composability docs was broken. 
Before:
[Contract Composability: The Building Blocks of Ethereum Smart Contract Development](https://blog.decentlabs.io/contract-composability-the-building-blocks-of-ethereum-smart-contract-development/)
=> Fixing broken link in Smart contract composability docs

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Add very simple sentence in /developers/docs/nodes-and-clients/run-a-node/index.md explaining the utility of client version strings. This is useful information for people running their own node, but this PR is primarily motivated by generating a target for redirecting the `version-strings` page from eth.wiki.
#5690
=> Add client version string info to /run-a-node/

src/components/Staking/StakingHierarchy.js, src/components/Staking/StakingStatsBox.js, src/content/staking/solo/index.md, src/pages/staking/index.js
Fixes a few initial bugs noted on recently merged staking epic PR.
- Centers hierarchy pills on mobile
- Removes unused components
- FAQ update with latest copy
- Denote APR estimation as approximate
- Bug: "StakingLaunchpadWidget" component name fixed
Preview: <a href="https://ethereumorgwebsitedev01-stakingpatches.gtsb.io/en/staking" target="_blank">https://ethereumorgwebsitedev01-stakingpatches.gtsb.io/en/staking</a>
=> Staking epic patches

src/components/StatsBoxGrid.js, src/pages/layer-2.js, src/utils/formatLocaleNumbers.js, src/utils/translations.js
Context: As noted in #5490, we were mixing Persian and Hindu-Arabic numerals. After consulting Farsi speakers, we realised this was undesirable.
**This PR overwrites the number formatting of the Farsi language on our StatsBox components to use Hindu-Arabic formatting.**
- Updates homepage StatsBox
- Updates layer-2 page StatsBox
- We should do the same for our staking pages
- https://ethereumorgwebsitedev01-overwritepersiannumbers.gtsb.io/fa/
- https://ethereumorgwebsitedev01-overwritepersiannumbers.gtsb.io/fa/layer-2
#5490 #5748
=> Overwrite Persian numbering for StatsBoxes

redirects.json
Found myself forgetting if the hyphen was required or not. Added simply redirect to allow users to just type ethereum.org/layer2 and not have to worry about the hyphen.
=> Add redirect for non-hyphenated layer2 path

src/content/developers/tutorials/optimism-std-bridge-annotated-code/index.md
Fixed typo.
```
recieve -> receive
```
=> Fix typo in optimism-std-bridge-annotated-code/index.md

src/components/Staking/StakingStatsBox.js
In #5911, we decided to overwrite Persian number formatting with Hindu-Arabic number formatting. This PR implements the same change on our `StakingStatsBox` component used on [the staking homepage](https://ethereum.org/en/staking/)
#5911
=> Update staking page to override Persian number formatting

src/content/developers/tutorials/nft-minter/index.md
typo : smart contract was misspell smart con**tact**
=> Fixed a couple of typos 'smart  contact' > 'smart contract'

gatsby-config.js
The theme color is set to #1c1ce1 and on safari mobile fills the top of the screen. this color does not work on das theme
changed from #1c1ce1 to #222222 to work good on light and dark theme
Open the ethereum.org on safari mobile or even in the desktop when scrolling
=> New color for the theme (mostly seen on safari)

src/content/developers/tutorials/optimism-std-bridge-annotated-code/index.md
EASY FIX
Just typo fix in Tuto article: optimism-std-bridge-annotated-code 😉
=> Typo fix in optimism-std-bridge-annotated-code

src/content/developers/docs/mev/index.md
Link to "The Merge" page was referring to a faulty url.
I updated the link to the correct page.
=> fix link to The Merge

src/pages/developers/learning-tools.js
crypto zombies changed the url of their tutorial
=> Update learning-tools.js to use correct crypto zombies url

src/components/ExpandableCard.js
- Make it so that users can click the ExpandableCard question box.
- New function:
- Users can click the question area to open and close for ExpandableCard
- click event will be ignored if the user is selecting text
=> Make ExpandableCard question box clickable

src/content/enterprise/index.md, src/content/history/index.md
Link to "Are you a dApp developer? Be sure to upgrade your libraries and tooling." on https://ethereum.org/en/history/ was referring to 404/faulty url
I updated the link to the correct page.
=> Fix link to history page/broken link

src/content/translations/ro/developers/tutorials/create-and-deploy-a-defi-app/index.md, src/content/translations/ro/developers/tutorials/deploying-your-first-smart-contract/index.md, src/content/translations/ro/developers/tutorials/erc20-annotated-code/index.md, src/content/translations/ro/developers/tutorials/how-to-implement-an-erc721-market/index.md, src/content/translations/ro/developers/tutorials/interact-with-other-contracts-from-solidity/index.md, src/content/translations/ro/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/ro/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md, src/content/translations/ro/developers/tutorials/run-light-node-geth/index.md, src/content/translations/ro/developers/tutorials/send-token-etherjs/index.md, src/content/translations/ro/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md, src/content/translations/ro/developers/tutorials/uniswap-v2-annotated-code/index.md
- Update Romanian Tutorials 2 content bucket files
=> Update: Romanian translation files Tutorials 2

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md, src/content/translations/id/developers/tutorials/uniswap-v2-annotated-code/index.md, src/content/translations/it/developers/tutorials/uniswap-v2-annotated-code/index.md, src/content/translations/ro/developers/tutorials/uniswap-v2-annotated-code/index.md, src/content/translations/zh/developers/tutorials/uniswap-v2-annotated-code/index.md
The links for UniswapV2Router docs were outdated and redirected into 404 pages
This PR is to ddd the updated links for UniswapV2Router docs
=> docs: Fix outdated links for UniswapV2Router documentation

src/content/developers/docs/networks/index.md
Adds some clarifications to public Ethereum networks.
- creates a section for L2 testnets to avoid confusion
- adds a deprecation notice for Kovan, Rinkeby, and Ropsten
- adds [Sepolia](https://github.com/goerli/sepolia) testnet
- removes some broken links
- https://github.com/ethereum/pm/issues/460
=> dev/networks: update public testnets

src/content/developers/docs/transactions/index.md
The URL pointing to the glossary entry of ABI, has a trailing slash which makes the anchor tag not work. The fix is too remove the trailing slash.
=> docs: Fixes the anchor tag for ABI link

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
DataHub provides access to the RPC and REST APIs of our supported protocols including Ethereum for both the latest mainnets and testnets. In this PR I've updated the "Popular node services" section on the "Nodes and clients" page to add the DataHub as one of the node providers in this list.
=> Added DataHub under the "Popular node services" section on "Nodes and clients" page.

src/content/developers/docs/consensus-mechanisms/pos/index.md
Period should be outside of quote
Period should be outside of quote
https://github.com/ethereum/ethereum-org-website/issues/6072
=> Fix period typo

src/content/contributing/translation-program/translators-guide/index.md
An alt attribute ends up containing ".png" in Crowdin Warning section, which is displayed to readers when hovering the image.
Changed the alt content : 
"Example of a Crowdin warning.png" > "Example of a Crowdin warning"
=> unnecessary file extension in img alt text

src/content/contributing/translation-program/translators-guide/index.md
A sentence was long and object was at the end, making the sentence slightly difficult to understand. There's room for simplification.
To simplify I reverted to position object first and finished by examples.
_Note_ : I followed the following guideline regarding punctuation of _'etc.'_ : https://klmoravec.wordpress.com/2019/09/16/tricky-punctuation-etc-at-the-end-of-a-sentence/
=> simplified language in crowdin warnings section

src/content/developers/docs/nodes-and-clients/index.md
This PR adds information to the light node section of `/developers/docs/nodes-and-clients/index.md`.
This is part of the wiki migration. I initially expected that this might have to be a page in its own right or at least a new, expanded section in the existing landing page. However, on reflection the wiki information is execution layer specific (in fact, Geth specific), dated to 2018 and light clients have not really taken off on Ethereum yet anyway - they are something exciting for the near future. For these reasons I decided the intended outcome (overview of light clients) is best served by linking to Geth's LES protocol docs and maintaining just a short, forward looking description in the existing light nodes section on the landing page. 
#5690
=> expand light node section (wiki migration)

src/content/developers/docs/nodes-and-clients/index.md
Patches the syntax for a link recently added in #6223
=> Link patch

src/content/developers/docs/apis/json-rpc/index.md
This PR adds information from eth,wiki and ethdocs.org to ethereum.org/en/developers/docs/apis/json-rpc/.
Note that the key information is really the JSON-RPC API spec, which used to be included in full on the wiki but is not held externally - I have linked out to it. 
In the preservationist spirit, and because I thought it was useful information not available elsewhere, I incorporated the short RPC contract deployment tutorial from ethdocs.org into this page.
#5731 and #5690
=> Migrate json-rpc information from ethdocs/eth.wiki

src/content/glossary/index.md
Change glossary to direct to our new L2 page instead of developer doc
None
=> Update L2 glossary link

src/content/developers/tutorials/run-light-node-geth/index.md, src/content/translations/es/developers/docs/transactions/index.md, src/content/translations/fa/developers/docs/transactions/index.md, src/content/translations/id/developers/docs/transactions/index.md, src/content/translations/id/developers/tutorials/run-light-node-geth/index.md, src/content/translations/ro/developers/docs/transactions/index.md, src/content/translations/ro/developers/tutorials/run-light-node-geth/index.md, src/content/translations/zh/developers/tutorials/run-light-node-geth/index.md
In #6192, a contributor noted that a trailing slash breaks the URL id selector in glossary links. This builds on #6192 to remove all instances of this.
For example:
https://ethereum.org/en/glossary/#mainnet/ (with trailing slash) vs visiting https://ethereum.org/en/glossary/#mainnet (no slash)
#6192
=> Remove trailing slashes from glossary links

src/content/developers/tutorials/run-light-node-geth/index.md, src/content/smart-contracts/index.md, src/content/translations/id/developers/tutorials/run-light-node-geth/index.md, src/content/translations/ro/developers/tutorials/run-light-node-geth/index.md, src/content/translations/zh/developers/tutorials/run-light-node-geth/index.md
Follow on from: #6207.
I realised any trailing slash will break a header id. This removes broken occurences on the website.
#6207
=> Remove trailing slashes from urls with header-ids

src/components/Staking/StakingProductsCardGrid.js
- Updates the `id` prop to use `key`
- Pulls logic for creating the ranked product list into a `useEffect` hook. This will only load data once when component mounts, and prevents re-rendering of data after.
**Preview deploy:**
- https://ethereumorgwebsitedev01-stakingcardissue.gtsb.io/en/staking/pools/
- https://ethereumorgwebsitedev01-stakingcardissue.gtsb.io/en/staking/solo/
- https://ethereumorgwebsitedev01-stakingcardissue.gtsb.io/en/staking/saas/
[Fixes #6245]
=> Staking product card layout fix [Fixes #6245]

src/content/glossary/index.md
This PR collects together entries in the ethdocs.org and eth.wiki glossaries and merges them into the glossary on ethereum.org. There are quite a few new additions. There were also many entries in the glossaries of both ethdocs.org and eth.wiki that I decided NOT to merge into ethereum.org. These are listed below so the PR reviewers can challenge any that they think are actually useful to include (especially those from ethdocs relating to trust and identity - I excluded them as superfluous but think they might actually be quite nice to include).
```
**deposit**
Digital property placed into a contract involving another party such that if certain conditions are not satisfied that property is automatically forfeited and either credited to a counterparty as insurance against the conditions, …
```
=> sync glossaries between eth.org, ethdocs.org & eth.wiki

src/components/CardList.js, src/components/Staking/StakingGuides.js
Removes `margin-bottom` from `CardList.js`, and custom adds back a 1rem gap for the staking guides list specifically.
[Fixes #6228]
=> Layout patch [Fixes #6228]

src/pages/stablecoins.js
- update stablecoins filter to take out stablecoins not on Ethereum.
=> Filter out stablecoins not on Ethereum

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
not many typos to fix however, <br> are real nightmares for translators when using translation tools like Crowdin, or others. 
This way I removed unnecessary newlines so that it will be much more easier to translate.
=> Fix formatting in Uniswap V2 annotated code tutorial

src/content/developers/tutorials/run-light-node-geth/index.md
The testnet URL in the `run-light-node-geth` docs is no longer directing to the correct path of the document. Updating the url to point to the latest testnet section.
[Fixes #6148]
=> update testnet url for setting up light node docs

src/content/web3/index.md
The page *The early internet* incorrectly uses the term "internet" to mean "World Wide Web". This PR fixes that error.
This PR fixes issue #6058
=> 6058 Changed `internet` to ~`Web`.

src/pages/developers/index.js
Closing `</p>` tag recently accidentally removed causing build breaks.
=> Syntax bug patch

src/components/TranslationBanner.js
- Fixed the bug in the `View In English Button` (href).
- Changed `originalPagePath` to `/en/developers/`.  
- Related to [#6318].
=> 'View in English' Button Link Fixed [Solves #6318]

src/content/contributing/translation-program/index.md
The 2021 POAPs claim has been eliminated as it expired at the end of January 2022, and no more claimable💎
=> Fix POAPs claim on Translation Program page

gatsby-config.js
We are sending testing data from our preview deploys to Matomo because the plugin sends data when `NODE_ENV === 'production'`.
Ref. https://support.gatsbyjs.com/hc/en-us/articles/360052322954-Environment-Variables-Specific-to-Gatsby-Cloud.
Since we don't have control over these conditions in the plugin, we are not going to load the plugin when `GATSBY_CLOUD === 'true'`.
So, the end state of this is the following:
- In prod (Netlify), `NODE_ENV='production' & GATSBY_CLOUD=undefined` => will load Matomo normally
- In preview deploys, `NODE_ENV='production' & GATSBY_CLOUD='true'` => will NOT load Matomo
- In dev, `NODE_ENV='dev'` => will load Matomo but the plugin handles this case. It will not send any data in dev mode
#5998
=> Avoid loading matomo in preview deploys

src/content/community/grants/academic-grants-round/index.md, src/content/community/grants/index.md
This PR removes the Academic Grants Round link from `/community/grants/` page and updates the banner on `/community/grants/academic-grants-round/` as the round is currently closed.
=> Close Academic Grants round

redirects.json
This PR fixes the redirect loop from `/en/community/grants/`
=> fix: remove /*/grants/ redirect to avoid loop

src/intl/en/page-upgrades-get-involved-bug-bounty.json
Adjusts copy on bug bounty page to clarify the list of EL vs CL clients, as Nimbus also has EL infrastructure that is not currently in scope for rewards.
=> Bounty copy clarifier

src/data/community-meetups.json
This PR adds the [ETH SD](https://withkoji.com/@ethsd) meetup group to the list of meetups.
ETH SD is dedicated to creating a diverse community of web3 engineers, creatives, and builders in San Diego 🏄
=> Add ETH SD to list of meetups

src/content/whitepaper/index.md
Cleans up small layout bugs with the `/whitepaper` page in attempt to correct the transpiling bugs we're getting with Crowdin import/export
Changes do not affect content itself
=> Whitepaper Crowdin formatting patches

src/content/bridges/index.md
The current "Bridges" page uses ETH -> Luna as its asset bridging example. this no longer seems appropriate, so I have updated it to BTC/WBTC.
=> update LUNA -> WBTC in bridges example

src/content/developers/docs/standards/index.md, src/content/developers/docs/standards/tokens/erc-4626/index.md, src/content/developers/docs/standards/tokens/index.md, src/data/developer-docs-links.yaml, src/intl/bg/page-developers-docs.json, src/intl/ca/page-developers-docs.json, src/intl/en/page-developers-docs.json
In this pull request, I did the following:
- Edited the "Token standards" page by adding ERC-4626 to the list of token standards.
- I created a blog page in the `ERC-4626` folder as `index.md`
- And I wrote a blog post to summarize it.
This pull request is related to #6255
=> Included Erc-4626 in token standards- [Fixes #6255]

src/pages/wallets/find-wallet.js
Replace raw `<a />` tag with `<Link />`
#6423 Wrong i18n link for `page-find-wallet-new-to-wallets-link` in `/wallets/find-wallet/`
=> Fix i18n link in wallets/find-wallet [Fixes #6423]

src/content/developers/docs/standards/tokens/erc-20/index.md
Changed "of" to "as" in the original sentence "[...] each Token be exactly the same (in type and value) *of* another Token."
=> Fixed small typo in ERC20 docs

src/content/contributing/translation-program/translators-guide/index.md
Change 'backslash' to 'slash', as the example character in the translation style guide is a slash
=> Change backslash to slash in translators guide

src/pages/developers/learning-tools.js
The URL for questbook has changed.
The previous URL was questbook.app is now transferred to learn.questbook.xyz. Questbook has converted the questbook.app to crowdfunding dapp
=> Updating Learning-tools.js

src/intl/en/page-get-eth.json
- Changed `Try a Dex` to `Try a DEX`. 
- Related to [#6405]
=> Fixed common spelling of DEX [Fixes #6405]

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Changed "Ethereum Testnets" link on [this article](https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/) to reference `/developers/docs/networks/#ethereum-testnets` instead of `/developers/docs/networks/#testnets`.
Issue contains reproducibility steps - #6384
=> Updated link to testnet 'in node as a service article', fixes #6384

src/data/staking-products.json
StakeWise is no longer accepting new users/deposits for their "Solo" service, only for the "Pool" service.
This removes the StakeWise Solo option from the SaaS listings to avoid confusion for new users, and renames the existing pooled service to simply "StakeWise."
None filed
=> Remove StakeWise Solo from SaaS listings

src/components/FeedbackWidget.js
Limits displaying the new FeedbackWidget to English pages only, given internal limitations on ability to process and interpret non-English responses
None filed
=> FeedbackWidget on English pages only

src/data/community-events.json
Changed June ETH SF to Graph Day / Hack
Background:
**ETHSanFrancisco** is happening on November 4-6, 2022. https://sf.ethglobal.com/
**Graph Day** is happening on June 2, 2022 (plus **Graph Hack** June 3-5, 2022) in SF. https://thegraph.com/graph-day/2022/
**ETH SF** is currently listed as happening on June 2-5, 2022. https://ethereum.org/en/community/events/
I could not find evidence of ETH SF happening during June 2-5, 2022 on any official event sites(?)
=> Update ETH SF to Graph Day

src/components/Staking/StakingProductsCardGrid.js
`/staking/saas`
- Currently these are all listed with a ❌Trustless indicator
- All of these are considered "trusted" setups, since the service operates your validator for you, so this tag should not be present for this category
- Also, "Self custody" is listed in the "What to consider" section, but is not listed on the cards themselves.
`/staking/pools`
- The "What to consider" section mentioned "liquidity token" but this property never got added to the product cards themselves, leaving eight considerations defined, but only seven listed on the cards.
- Note, "liquidity token" takes the place of "self custody" for the pooled options.
- Removed the "Trustless" indicator from the SaaS cards
- Added "Self custody" indicator for "SaaS" cards 
- Added "Liquidity token" indicator for "Pool" …
=> Staking product attribute indicator bug fix

src/content/translations/ro/developers/docs/programming-languages/ruby/index.md, src/content/translations/ro/developers/tutorials/nft-minter/index.md, src/content/translations/ro/developers/tutorials/optimism-std-bridge-annotated-code/index.md
Fix incorrect Romanian lang paths.
Closes #6471
=> Fix lang:en -> lang:ro in Romanian docs

src/styles/layout.css
Before:
After:
When viewed on a small screen such as iPhone 8, the layout of a table may be broken for languages with long words such as German.
This can be solved by adding the setting `hyphens: auto;` to the `th` and `td` elements of the `table`.
#6268
=> Add `hyphens` settings to tables [Fixes #6268]

src/components/Card.tsx
- Migrates Card component to Typescript
- I was going to migrate all Cards that extend it but it looks like all of our cards are standalone components 🤔
#6392
=> Refactor Card component to TS

src/components/ActionCard.tsx
- Migrated `ActionCard` component to TypeScript. 
- Related to [#6392]
=> Migrated ActionCard.js to TS

src/components/YouTube.tsx
- I migrated the YouTube component to TypeScript
- There are very small changes to that.
[#6392](https://github.com/ethereum/ethereum-org-website/issues/6392)
=> migrate YouTube component to Typescript

src/components/BannerNotification.tsx
The boolean passed from docs template to banner notification component
has an issue when the variable passed is null. The interface of the
banner props has shouldShow declared as boolean or undefined. To prevent
each component to check against null to boolean, the check is made
internally inside the banner component and shouldShow is declared as
boolean or null or undefined.
Related to : #6392
=> fix(banner-notification): type check error on docs template

src/content/developers/docs/smart-contracts/testing/index.md
Removed OpenZeppelin Test Environment as this testing solution is no longer maintained and in archived status on Github.
[Issue 6551](https://github.com/ethereum/ethereum-org-website/issues/6551)
=> Remove OpenZeppelin Test Environment

src/content/developers/docs/intro-to-ethereum/index.md
Fixed a notation shaking in the documentation to be consistent with ETH.
https://ethereum.org/ja/developers/docs/intro-to-ethereum/
The chapter "What is ether?" has been excluded.
=> Fix notation shaking ether -> ETH

src/content/developers/docs/scaling/sidechains/index.md, src/content/developers/docs/scaling/validium/index.md
Remove UI banner from sidechains & validium pages:
> This page is incomplete and we'd love your help. Edit this page and add anything that you think might be useful to others.
Thanks to recent PRs from @emmanuel-awosika, we've recently added a good amount of info to both pages:
- https://github.com/ethereum/ethereum-org-website/pull/6508
- https://github.com/ethereum/ethereum-org-website/pull/6502
Doesn't mean we can't expand/edit further in the future, but I think they're to a point where they don't really need that flag anymore.
- https://github.com/ethereum/ethereum-org-website/pull/6508
- https://github.com/ethereum/ethereum-org-website/pull/6502
=> Remove incomplete frontmatter

src/data/developer-docs-links.yaml
https://ethereum.org/en/developers/docs/data-structures-and-encoding/
- Aligns the order of the dev docs within the `data-strctures-and-encoding` path to match the root markdown page
=> Fix ordering of data-strctures-and-encoding docs

src/content/developers/docs/consensus-mechanisms/index.md
deleted the word "has" in the phrase "has plans" on https://ethereum.org/en/developers/docs/consensus-mechanisms/
In general, substituting verbs for nouns makes sentences easier to parse; for more, see https://farewill.notion.site/Our-tone-of-voice-584b3a2390a14d2fbacfe387aa7dc6e1#7de9e3f6ef5e4845b3446b7ed8d751d6
=> Update index.md -- replace two words ("has plans") with one ("plans")

src/content/developers/docs/consensus-mechanisms/pos/index.md
* the intro paragraph/sentence should succinctly state the core idea rather than explaining the building blocks
* I don't think consensus mechanism needs to be both defined and linked to (I definitely might be wrong)
* The remainder of the article can explain the building blocks from the ground up
* ~40 fewer words
=> Update PoS overview to add a more on-point lede

src/content/translations/es/developers/docs/intro-to-ether/index.md
There was one paragraph that was not fully translated into English.
There was one paragraph that was not fully translated into English. I translate the outstanding part as specified below.
As you can see, there is a part of it still to be translated:
La quema de ether se produce en cada transacción en Ethereum. When users pay for their transactions, a base gas fee, set by the network according to transactional demand, gets destroyed. This, coupled with variable block sizes and a maximum gas fee, simplifies transaction fee estimation on Ethereum. When network demand is high, [blocks](https://etherscan.io/block/12965263) can burn more ether than they mint, effectively offsetting ether issuance.
Burning the base fee prevents various ways the miners could manipulate it otherwise. For example, …
=> Paragraph to be translated in into-to-ether (Spanish)

src/content/history/index.md
There seeems to be this misconception that eip-2 introduced the difficulty bomb.
> the client will calculate the difficulty based on a fake block number suggesting the client that the difficulty bomb is adjusting around 6 million blocks later than previously specified with the Homestead fork.
<https://github.com/ethereum/EIPs/pull/1234>
> Due to the "difficulty bomb" (also known as the "ice age"), introduced in EIP #2, an artificial exponential increase in difficulty until chain freeze,
<https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1227.md>
When looking into the homestead fork (specified in eip-2), it seems that the difficulty change has nothing to do with the difficulty bomb.  The difficulty bomb was introduced in the frontier-thawing fork.
> starting from block 200,000 (very …
=> Add difficulty bomb info to frontier-thawing

src/content/developers/docs/smart-contracts/compiling/index.md, src/content/translations/es/developers/docs/smart-contracts/compiling/index.md, src/content/translations/fr/developers/docs/smart-contracts/compiling/index.md, src/content/translations/hu/developers/docs/smart-contracts/compiling/index.md, src/content/translations/id/developers/docs/smart-contracts/compiling/index.md, src/content/translations/it/developers/docs/smart-contracts/compiling/index.md, src/content/translations/pl/developers/docs/smart-contracts/compiling/index.md, src/content/translations/pt-br/developers/docs/smart-contracts/compiling/index.md, src/content/translations/ro/developers/docs/smart-contracts/compiling/index.md, src/content/translations/tr/developers/docs/smart-contracts/compiling/index.md, src/content/translations/zh/developers/docs/smart-contracts/compiling/index.md
Fixes link to the Ethereum Virtual Machine page from compiling contracts
Fixes #6642
=> Fix links from compiling contracts -> evm across all translations

src/content/developers/docs/standards/tokens/index.md
existing text contained subject / verb number mismatch ("one standard focus on ...", rather than "one standard focuses on ...").
=> improve grammar / clarity in `Token Standards` doc

src/content/history/index.md
Putting the links on two separate lines.
=> fix frontier-thawing blog post links

src/content/developers/docs/evm/index.md
The link to information about Patricia Merkle Trees was broken. I fixed it.
None
=> Fix broken link on EVM docs page

src/pages/bug-bounty.js
This PR [fixes the total score leaderboard](https://github.com/ethereum/ethereum-org-website/issues/6328) on the bug bounty page by accumulating scores per user name.  We go off name as sometimes `username` is an empty string, so full name is our best accumulator.  Having some kind of UUID for users going forward would probably be ideal, but it's OOS for this PR.
This PR addresses [6328](https://github.com/ethereum/ethereum-org-website/issues/6328)
=> Fix bug bounty total leaderboard

src/content/developers/docs/apis/json-rpc/index.md
Adds JSON-RPC API endpoint examples from eth.wiki onto json-rpc page at ethereum.org.
Adds deprecation notices to `db_xxxxx` and `shh_xxxxx` endpoints.
Fixes some typos and adds some signposting for navigating the page.
#6760
=> Add JSON-RPC API endpoint examples

src/data/layer-2/layer-2.json
Key was missing, meaning the note wasn't being shown on the website.
=> Include Arbitrum key in layer-2.json

src/content/history/index.md, yarn.lock
- Adds Gray Glacier to /history with callout to node operators to update. 
Open question, should we add a banner callout for this anywhere? For Arrow Glacier I believe we added a banner to the homepage only, targeting node operators. We're already in the midst of calling out The Merge with #6710 on the homepage, so not sure if we want to do that or not this time.
=> Adds Gray Glacier to History page

src/assets/eth-home-icon.svg, src/components/Nav/index.js
- Upgrades home icon to SVG
- As a result the `svg:hover` selector in the `Link.tsx` component causes this to scale by 2% on hover (since it is now an SVG)... which I thought was a nice bonus, so I kept it in there
- Note, there is an existing SVG with a heavier stroke width that didn't quite match our existing home logo, hence the new file. If we feel it's too redundant, would suggest we remove the old one and replace it with this new one on the assets page. (This PR doesn't touch the assets page)
<-- old / new -->
=> Upgrade home icon to svg

src/intl/en/page-developers-learning-tools.json
* Made **four changes** on lines: `16, 30, 42 & 44`.
* Changed `Logo` to `logo`. 
* PR related to #6803
=> Ensured consistent spelling of 'logo' for alts [Fixes #6803]

src/intl/en/page-stablecoins.json
* Fixed a small typo, changed `USDc` to `USDC`.
* Not related to an open issue.
=> Fixed USDC Typo

src/data/execution-bounty-hunters.csv
Rendering is broken because of this:
=> Fix typo in execution-bounty-hunters.csv

src/content/community/grants/index.md
Adds missing closing `_` italics markdown tag on community grants page.
Causing issues with some language imports for the page.
=> Add missing closing tag to community grants page

src/content/translations/es/glossary/index.md
- Fixes a parsing error from recent import of `es/glossary`
None filed, currently breaking builds
- #6929 Culprit PR
=> Markdown syntax patch

src/content/translations/es/developers/docs/nodes-and-clients/index.md, src/content/translations/hu/developers/docs/nodes-and-clients/index.md
Remove inconsistencies in the spelling of the 'Go' programming language
=> Remove incorrect spellings of the 'Go' programming language

src/templates/use-cases.tsx
List items in the use cases template are currently showing as a different colour (#F2F2F2) compared to regular text (#CCCCCC) because the ListItem styles were not imported in the use cases template.
Before:
After:
None
=> Fix use-cases template list item styling bug

src/content/developers/docs/bridges/index.md, src/content/translations/de/developers/docs/transactions/index.md, src/content/translations/it/developers/docs/programming-languages/javascript/index.md, src/content/translations/it/developers/tutorials/secure-development-workflow/index.md, src/content/translations/pt-br/developers/docs/transactions/index.md, src/content/translations/pt-br/developers/tutorials/run-node-raspberry-pi/index.md
Get rid of /en/ tags in markdown links
#6903
=> Remove unwanted EN tags from markdown links

src/content/translations/hu/developers/docs/layer-2-scaling/index.md, src/content/translations/hu/history/index.md, src/content/translations/it/developers/docs/layer-2-scaling/index.md, src/content/translations/it/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md, src/content/translations/ro/developers/docs/layer-2-scaling/index.md
Broken links caused by escape characters / incorrect spacing
None
=> Fix broken markdown links

src/content/developers/tutorials/run-light-node-geth/index.md, src/content/translations/id/developers/tutorials/run-light-node-geth/index.md, src/content/translations/ro/developers/tutorials/run-light-node-geth/index.md, src/content/translations/tr/developers/tutorials/run-light-node-geth/index.md
The frontmatter prop is broken, causing the author's name to not render.
None
=> Fix broken 'author' frontmatter prop on run a light node tutorial

package.json
- Adds a package script `yarn build:10gb` that appends a 10gb limit to node option `max-old-space-size`
None filed, but was having memory heap issues on 16gb machine without this.
In testing, this works to build the entire site, all languages, on a 16gb machine.
=> Add 10GB node ram limit as optional build type

src/components/Link.tsx
@nloureiro pointed out that using the glossary icon on the navigation may be confusing or interpreted as a UI bug. This PR changes the GlossaryLink to only be used when we're linking to a glossary item (e.g. /glossary#pos) but not to the glossary page itself (/glossary/).
None
=> Only use glossary icon on glossary items

src/components/Link.tsx
- Patches recent update to remove glossary icon from menu glossary link.
- Only adds to links that include 'glossary' and '#' in the link string, no necessarily only `glossary#`
=> Glossary hash link patch

src/content/developers/docs/gas/index.md
Paragraphs about PoS in the "reduce gas costs" sections lead to confusion for people who aren't familiar with Ethereum's roadmap. For example: https://twitter.com/allenf32/status/1547205465267920896
I think we should aim for clarity, as we do elsewhere, e.g.: https://ethereum.org/en/upgrades/merge/#misconceptions
=> Remove paragraphs about PoS

src/components/FindWallet/WalletTable.tsx
- Track whether WalletMoreInfo event is opening or closing more information for a wallet
=> add more info to WalletMoreInfo about state for Matomo event

src/content/developers/docs/smart-contracts/upgrading-smart-contracts/index.md
This page provides a high-level introduction to smart contract upgrades for developers.
This is a review of various patterns for upgrading Ethereum smart contracts. It also contains information on the pros and cons of smart contract upgrades and recommendations for using upgrades safely. 
Closes #1511
=> Add page on smart contract upgradeability

src/content/developers/docs/smart-contracts/upgrading-smart-contracts/index.md
Adds missing `lang: en` frontmatter property
(Hot fix)
=> Upgrading-smart-contracts patch

docs/Event tracking guideline, docs/event-tracking.md
Event tracking guideline
For developers to see how to structure event tracking and what to measure when creating/redesigning a page.
=> Create Event tracking guideline

src/content/translations/it/developers/tutorials/deploying-your-first-smart-contract/index.md, src/content/translations/it/developers/tutorials/erc20-annotated-code/index.md, src/content/translations/it/developers/tutorials/how-to-implement-an-erc721-market/index.md, src/content/translations/it/developers/tutorials/interact-with-other-contracts-from-solidity/index.md, src/content/translations/it/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/it/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md, src/content/translations/it/developers/tutorials/run-light-node-geth/index.md, src/content/translations/it/developers/tutorials/send-token-etherjs/index.md, src/content/translations/it/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md, src/content/translations/it/developers/tutorials/uniswap-v2-annotated-code/index.md
Add Italian tutorials II bucket from Crowdin
None
=> Italian: add "Tutorials II" bucket from Crowdin

src/content/developers/docs/smart-contracts/upgrading/index.md
Noticed we had duplicate H1s here:
#7095
=> Remove extra H1 from upgrading smart contracts

src/content/developers/docs/scaling/optimistic-rollups/index.md
@corwintines suggested expanding the rollup docs to include details about other players in the system (validators, sequencers, etc.), which this edit does. I also added details I felt may be relevant to developers and users who want to interact with optimistic rollups.
Here is a high-level overview of some of the changes I suggested:
- A section explaining the relationship between optimistic rollups and Ethereum 
- A section describing types of fraud proving schemes 
- A section explaining how optimistic rollups work (transaction execution, state commitment, etc.)
- A section on rollup fees (felt this would be quite useful for would-be users)
- A section explaining how rollups scale Ethereum via `calldata` compression
=> Expand Optimistic Rollups docs

src/content/developers/docs/nodes-and-clients/index.md
looks like extra text for a header link that is no longer a header
removes {#full-sync}
=> delete header link markdown

gatsby-node.ts, redirects.json
1. For each `defaultLang` page we create, lets also create a redirect from the root paths. E.g. for `/en/nft` create a redirect from `/nft` to `/en/nft`.
2. Cleanup the `redirects.json` file. Leave only the custom redirects. The rest are dynamically generated by the previous logic.
Fixes: #6488 #7097
=> Redirect nested routes to default lang

gatsby-browser.tsx, gatsby-config.ts, gatsby-node.ts, redirects.json
**IMPORTANT**: this PR was branched from #7135. Merge that PR first.
---
Testing site: https://pettinarip-eth-org.netlify.app/
We are implementing the Netlify docs: https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling
Fix #5682 
Also cover #6356
=> Resolve 404 pages

src/components/Footer.tsx, src/components/Nav/index.tsx
Removes link to /wallets/ and replaces with link to /find-wallets/
None
=> Add find-wallets to Use Ethereum navigation dropdown

src/components/ActionCard.tsx, src/pages/upgrades/index.tsx, src/pages/upgrades/vision.tsx
MIgration of `upgrade/index` & `upgrade/vision` pages to TS.
#6392
=> Migrate `upgrade` pages to ts

src/content/developers/docs/nodes-and-clients/client-diversity/index.md
updates client diversity page for post-merge
#7075
=> post-merge update: client diversity page

src/content/decentralized-identity/index.md
Possibly typo: "utorial" -> "tutorial"
"utorial" -> "tutorial"
none
=> Fix typo in decentralized identity page

src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/ethash/index.md
Updates ethash page ready for post-merge
#7075
=> post-merge updates: ethash page

src/content/bridges/index.md
* Changed three cases of `euros` to `EUR`. I believe this looks better, because we are also using `USD` instead of `dollars` or `American dollars`. 
* Not related to an issue.
=> Changed 'euros' to 'EUR' [bridges]

src/content/developers/docs/nodes-and-clients/client-diversity/index.md
geth is by far the most used distribution of the codebase, and sending new users to another codebase, especially given all the changes with the merge can be misleading/dangerous.
=> Mention go-ethereum rather than core geth

src/content/social-networks/index.md
- Possibly typo:  Duplication of "NFTs" in the sentence
- Possibly typo: anyonymity -> anonymity
- Possibly typo:  Duplication of "NFTs" in the sentence
- Possibly typo: anyonymity -> anonymity
Deleted unnecessary "NFTs" word
none
=> Fix typos in social networks page

src/content/community/grants/index.md
The page is currently linking to an older version of the Balancer Grants application. This change has updated the link which now points to the Balancer Notion home page which has more background info and further details on how to apply.
=> Update Balancer Grants link

src/content/developers/docs/storage/index.md
swap "miner" for "validator" and remove ref to Etheruem being PoW
#7075
=> post-merge updates: storage page

src/content/developers/docs/apis/json-rpc/index.md
Subjective opinion but I think first linking to [the Ethereum RPC spec](https://github.com/ethereum/execution-apis) is more relevant to visitors than info on generic JSON RPC specs.
None 😄
=> Replace link with client spec

src/content/translations/de/developers/docs/ides/index.md, src/content/translations/es/developers/docs/ides/index.md, src/content/translations/fr/developers/docs/ides/index.md, src/content/translations/hu/developers/docs/ides/index.md, src/content/translations/id/developers/docs/ides/index.md, src/content/translations/it/developers/docs/ides/index.md, src/content/translations/pl/developers/docs/ides/index.md, src/content/translations/pt-br/developers/docs/ides/index.md, src/content/translations/ro/developers/docs/ides/index.md, src/content/translations/tr/developers/docs/ides/index.md, src/content/translations/zh/developers/docs/ides/index.md
Follows #7236, removes the same link in non-English languages.
#7236
=> Remove broken azure dev kit link on non-English pages

src/content/developers/docs/transactions/index.md
updates transactions page ready for post-merge
#7075
=> post-merge update: transactions page

src/content/developers/docs/data-availability/index.md
Fix the link in the document
Just a simple fix of the link.
=> Fix link to /glossary/#zk-proof

src/content/developers/docs/intro-to-ether/index.md
updates `developers/docs/intro-to-ether/index.md` ready for post-merge
#7075
=> post-merge updates: intro to ether page

src/content/developers/docs/smart-contracts/languages/index.md
- Community Discord
- Link to Ethereum for Python page that contains smart contract frameworks to developer on Vyper
- Added VyperPunk
- Added vyper-by-example.org
- Remove Gitter link (no longer active)
=> Update Vyper links on Vyper intro page

src/content/developers/docs/programming-languages/python/index.md
Vyper has new Discord.
Separate Discord links for Vyper and rest of Python.
Also bumped Vyper higher on the unordered lists as a lot of people are looking for it.
=> Added Vyper Discord link

src/content/developers/docs/smart-contracts/testing/index.md
Tweaked detail concerning formal verification to distinguish it from testing and added a link to the formal verification page (in progress).
=> Update formal verification information on the testing smart contracts page

src/content/developers/docs/bridges/index.md, src/data/layer-2/cex-layer-2-support.json, src/data/layer-2/layer-2.json, src/intl/en/page-layer-2.json
Optimism bridge should direct to https://app.optimism.io/bridge
Optimism description should read "Optimism is a fast, simple, and secure EVM-equivalent Optimistic Rollup. It scales Ethereum's tech while also scaling its values through retroactive public goods funding."
Crypto.com has withdraws / deposits for Optimism
OKX has withdraws for Optimism
N/A
=> A few small updates to L2 Page requested by the OP team

src/content/decentralized-identity/index.md
The invite link to the Veramo Labs community points to SpruceID community instead. I've edited it to have the correct URL
=> Update Veramo Labs URL

src/pages-conditional/wallets.tsx
Put wallet hero image below hero content on mobile screens
Before:
After:
None
=> Put wallet hero image below hero content on mobile screens

src/content/developers/docs/apis/json-rpc/index.md
adds a short paragraph linking out to consensus client and engine APIs. It is a bit weird to have the full execution layer JSON-RPC API spec on this page but only linking out to engine and beacon APIs, but there are legacy reasons for this (execution API doesn't have a better home atm). Migrating Beacon and Engine API spec here would make this page even more massive and also migrate a lot of repository tracking and maintenance responsibility.
#7075
=> post merge updates: json rpc apis

src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/index.md
updates mining-algorithms page for post-merge
#7075
=> post-merge updates: mining algorithms

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
The list items for "Rivet" and "SenseiNode" were mixed together, and their indentation was not in line with the other items of the list.
Considering this is a minor styling fix, I have not opened an issue for it. I hope that's ok.
=> Fix styling for node services list

src/content/developers/docs/standards/index.md
~~Moves the https://eips.ethereum.org/ link from the wrong section to a better section.~~ Deletes an unintentionally misleading reference to the EIPs website. It was presumably meant to only link to standards track EIPs, but no such page exists.
The EIPs website has already been linked to.
N.A.
=> Delete Contextually Incorrect Link to EIPs Website

src/components/Staking/StakingLaunchpadWidget.tsx, src/content/developers/docs/development-networks/index.md, src/content/developers/docs/nodes-and-clients/run-a-node/index.md, src/intl/en/page-staking.json
The Prater testnet URL is currently down. The plan is to redirect this to https://goerli.launchpad.ethereum.org/en/. 
- This PR fixes the broken URLs to use the Goerli launchpad
- Slight tweak to copy
None
=> Fix Goerli testnet link

src/content/glossary/index.md
* Small typo fix, changed `id` to `is`.
* Related to [#7388]
=> Fix typo in Ethereum glossary [Fixes #7388]

src/content/developers/tutorials/testing-erc-20-tokens-with-waffle/index.md
* Added a missing space between 'Waffle' and 'to deploy'. 
* PR related to #7391
=> Added missing space on Testing ERC-20 tokens with Waffle page [Fixes #7391]

src/content/community/get-involved/index.md
CC @poojaranjan
Adds the Ethereum Cat Herders Discord server to the Developers sub-heading of the "How can I get involved" page.
https://canary.discord.com/channels/714888181740339261/895003445436743752/1006953559713140826
=> Add ECH Discord to Get Involved page

src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md
* Small typo fix, removed one 'a' from sentence. 
* Related to #7390
=> Fixed typo on Create and deploy a DeFi app page [Fixes #7390]

src/content/developers/docs/consensus-mechanisms/pos/attestations/index.md
Fixed broken link to attestations on eth2book.info
=> Fix broken link on attestations developer doc

src/content/developers/docs/evm/index.md
Remove Hyperledger Burrow from the list of EVM implementations
As per their [Github](https://github.com/hyperledger/burrow), the project has reached End of Life
=> Remove Hyperledger Burrow from EVM implementations

src/content/translations/de/developers/docs/evm/index.md, src/content/translations/es/developers/docs/evm/index.md, src/content/translations/fa/developers/docs/evm/index.md, src/content/translations/fr/developers/docs/evm/index.md, src/content/translations/hu/developers/docs/evm/index.md, src/content/translations/id/developers/docs/evm/index.md, src/content/translations/it/developers/docs/evm/index.md, src/content/translations/pl/developers/docs/evm/index.md, src/content/translations/pt-br/developers/docs/evm/index.md, src/content/translations/ro/developers/docs/evm/index.md, src/content/translations/ru/developers/docs/evm/index.md, src/content/translations/tr/developers/docs/evm/index.md, src/content/translations/zh/developers/docs/evm/index.md
In #7408, it was highlighted that Hyperledger Burrow has been deprecated. This PR removes the non-English mentions of Hyperledger Burrow.
#7408 - Original issue
#7413 - Issue to add to deprecated software page
=> Remove Hyperledger Burrow from /evm/ developer doc in all languages

src/components/FindWallet/WalletPersonasSidebar.tsx, src/components/FindWallet/WalletTable.tsx, src/data/wallets/wallet-filters.ts
- Update label and description for `EIP-1559 support` to `Fee optimization`
=> Update EIP-1559 label to "Fee optimization" for find-wallet

src/content/decentralized-identity/index.md
There was a duplicate 'can' in the article, therefore removed one 'can'.
There is no related issue.
=> Fix typo, remove duplicate 'can'

src/components/Nav/index.tsx
When tab navigating, this was the resulting selection box. This zone was also all clickable, potentially interfering with other content.
Svg is missing a height property.
- Capped height of svg keeping ratio of original svg size.
=> Fix: height of homeIcon svg

docs/chakra-migration-guide.md
Add initial UI lib migration guide.
Fixes: #7369 
Epic #6374
=> UI lib - Migration guide doc

src/content/upgrades/merge/index.md
- Fix the tense from `upgraded` to `upgrades` when referring to Shanghai upgrade
=> Fix tense for withdraw misconception

src/components/FindWallet/WalletPersonasSidebar.tsx
We got a suggestion from "RomoPuma" (if you have a Github profile, please add it) on discord (https://discord.com/channels/714888181740339261/951053072258453574/999409307953143932)to change The checkboxes on the personas box to radio-style buttons.
Here are some screenshots of the change.
=> Change the checkbox to radio on the profile chooser box

src/content/upgrades/merge/index.md
Updates merge page, mostly deletions and swapping to past tense.
#7075
=> post-merge updates: merge page

src/content/developers/docs/nodes-and-clients/index.md
Previous link was wrong; fixed it to point at right page.
I didn't make one as it's so tiny.
=> Fix client diversity page link

src/content/deprecated-software/index.md
Adds section for deprecated "proof-of-work". Not included in main softyware list because no clients were actually deprecated as part of merge, only components. Added separately because it was deprecation of a concept, implemented as a set of software upgrades.
#7075
=> post merge updates: deprecated software

src/content/developers/docs/data-and-analytics/index.md
- Moved `Block explorers` section to be ahead of The Graph section because it is one of the prerequisites.
- Added a section for Dune Analytics, another representative approach to on-chain data analytics that is different from the Graph protocol
None
=> Moved up Block explorers section; added Dune section

src/content/developers/docs/standards/tokens/erc-4626/index.md
ERC4626 page incorrectly displays a function that didn't make the final cut
removed the function
issue #7468
=> remove function that does'nt exist [fixed #7468]

src/data/staking-products.json
DAppNode has recently introduced the addition of web3signer, which has enabled multi-client support for consensus clients. With this, **Teku, Lighthouse and Prysm** are now supported for Mainnet through DAppNode.
Also:
- Geth/Nethermind execution clients on Mainnet
- Nimbus/Lighthouse/Teku/Prysm consensus clients on Prater
- Geth execution client, and also SSV on Goerli (formerly Prater)
This PR updated the `multiClient` flag to `true` for DAppNode, to update their indicator on the http://localhost:8000/en/staking/solo/#node-and-client-tools page
None filed
=> Update DAppNode multi-client status

gatsby-config.ts, package.json, yarn.lock
This PR adds the generation of the `robots.txt` file inside the `gatsby-config.ts` file.
After the build the generated file looks like that:
```
User-agent: *
Allow: /
Sitemap: https://ethereum.org/sitemap/sitemap-index.xml
Host: https://ethereum.org
```
I didn't know what policy do you want to have so I kept the default one (`policy: [{ userAgent: "*", allow: "/" }]`), tell me if you want to change that.
Add feature requested in #7464
=> Feat/add robots.txt file

src/content/contributing/translation-program/blog-translations/index.md
Fix broken header on the Blog translations subpage
None
=> Fix broken header on Blog translation page

src/content/developers/docs/transactions/index.md
adding Nonce as it is also part of the transaction which gets validated along with the transaction
Nonce is added in the transaction information section.
[Issue link #7609](https://github.com/ethereum/ethereum-org-website/issues/7609#issue-1353469978)
=> nonce field is missing from transaction information in transactions page 

src/content/social-networks/index.md
The previous edit described Arbitrum Nova as a cross between a validium and an optimistic rollup, which is incorrect--the Arbitrum Nova chain only posts proofs of data availability to Ethereum, not proofs of validity (as validiums do). I've chosen to describe it as a cross between a sidechain and an optimistic rollup instead, as that feels more accurate.
=> Fixed error related to Arbitrum Nova description

src/content/developers/docs/blocks/index.md
updates `block` page for post-merge
#7075
=> post-merge update: block page

src/content/developers/docs/accounts/index.md, src/content/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit/index.md
updates comments re gas. AFAICT contract size limit still applies.
#7075
=> post-merge updates: contract size tutorial

src/components/Link.tsx
We were using the incorrect propname to apply the active link styles. It name is `partiallyActive`.
=> Fix partial active links

src/content/staking/saas/index.md
There was a typo 'much' intead of 'must', therefore fixed to 'must'.
There is no related issue.
=> Fix typo: much -> must

src/content/glossary/index.md
Fix broken links from Table of Contents to definition. The links and hashes for all other items are lowercase and the generated urls are all lowercase. `#DAG` and `#D-with-stroke` were the only exceptions.
The generated links in the Glossary's table of contents does not directly link you to the definition.
1. Đ (`#d-with-stroke` , the actual link is `#D-with-stroke`)
2. DAG (`#dag`, the actual link is `#DAG`)
Example:
1. Đ
2. The link in the TOC is: https://ethereum.org/en/glossary/#d-with-stroke
3. The current direct link is: https://ethereum.org/en/glossary/#D-with-stroke
5. DAG
6. The link in the TOC is: https://ethereum.org/en/glossary/#dag
7. The current direct link is: https://ethereum.org/en/glossary/#DAG
Proposing to change the `#<LINK_NAME>` to lowercase, matching all other short …
=> Convert glossary link tags for `Đ` and `DAG` to lowercase

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Adding some resources and removing references to Kiln testnet which will be deprecated with The Merge
=> Add resources, remove Kiln

src/content/glossary/index.md
updates glossary for post merge
#7075
#2277
=> post-merge update: glossary

src/content/developers/docs/scaling/validium/index.md
`Data availability committee` heading parenthesis was wrong (ended in **)** instead of **}** ) which resulted the anchor link appearing in the text.
=> chore: fixed anchor Data availability committee

src/components/YouTube.tsx
Migrate YouTube from styled-components to ChakraUI
#6374
=> Refactor YouTube component to use ChakraUI

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
--http-web3provider has been renamed to --execution-endpoint.
Reference release notes: https://github.com/prysmaticlabs/prysm/releases/tag/v3.0.0
=> Update prysm's --execution-endpoint.

src/components/Link.tsx, src/components/TranslationBanner.tsx
The English-only link in the Translation Banner was being built incorrectly. It was prepending `en` and the default lang that the user had selected, for example, `/en/es/path`.
Use the new `language` prop to specify the lang of the link.
**Bonus:** I've change the `Link` name from `LinkWrapper` to just `Link` to have a better autocomplete exp.
=> Fix English link in Translation Banner

src/content/community/online/index.md
The following external list item is broken - List of influential Ethereum twitter accounts (List of influential Ethereum twitter accounts) - https://hive.one/c/Ethereum?page=1
I removed as it points to a Server 500 error at destination page
Visit the link titled  List of influential Ethereum twitter accounts - https://hive.one/c/Ethereum?page=1
at https://ethereum.org/en/community/online/#youtube-and-twitter
=> Fix broken link on online community page

src/@chakra-ui/gatsby-plugin/components/Tag.ts, src/@chakra-ui/gatsby-plugin/components/index.ts, src/@chakra-ui/gatsby-plugin/foundations/shadows.ts, src/components/Tag.tsx, src/pages/developers/tutorials.tsx
Migrate Tag component from styled-components to ChakraUI
https://github.com/ethereum/ethereum-org-website/issues/6374
=> Refactor Tag component to use Chakra

src/content/developers/tutorials/all-you-can-cache/index.md
When using rollups the cost of a byte in the transaction is a lot more expensive than the cost of a storage slot. Therefore, it makes sense to cache as much information as possible on chain.
In this article the developer learns how to create and use a caching contract in such a way that any parameter value that is likely to be used multiple times will be cached and available for use (after the first time) with a much smaller number of bytes, and how to write off chain code that uses this cache.
Closing: #7283
=> Tutorial: All you can Cache

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
- Added VPN option to exposing RPC endpoint
- Added context to shutting down a node
=> Update index.md - Added additional detail to several sections

src/pages/staking/deposit-contract.tsx
Fixed the read address aloud issue in #7690
We were using the Web Speech API and setting the [SpeechSynthesisUtterance.text](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/text) to DEPOSIT_CONTRACT_ADDRESS.split("").join(" ")
When following a number the letter 'C' is read as 'degrees Celsius' and the letter 'F' as 'degrees Fahrenheit'.
I have added commas between the characters so that each character is read separately
=> Fix read address aloud functionality [#7690]

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
typo. be replaces to. 
update. replace openwhisk w/ openzep
=> Update index.md to fix typo and old reference to openwhisk that leads to doc for openzeppelin

src/content/smart-contracts/index.md
There is a plural/singular error in the page. 
They are computer programs stored on the blockchain that allow\*s\* us to convert traditional contracts into digital parallels.
I changed it to
They are computer programs stored on the blockchain that allow converting traditional contracts into digital parallels.
=> Fixed allows vs allow on Smart contracts page

src/content/whitepaper/index.md
Removed link on line 520 which was broken - http://sourceforge.net/p/bitcoin/mailman/message/31709140/.
Edited the url of the wikipedia to reflect the correct scroll to it for Simplified Payment Verification.
From https://en.bitcoin.it/wiki/Scalability#Simplifiedpaymentverification to https://en.bitcoin.it/wiki/Scalability#Simplified_payment_verification
1. Fixing a broken link to a resource which is no longer available. 
2. Editing the url of a link to make the id instantly accessible.
1. Visit the link titled Peter Todd on Merkle sum trees on point 21 of Further Reading: http://sourceforge.net/p/bitcoin/mailman/message/31709140/
It is no longer accessible.
2. Visit the link titled Simplified payment verification on point 13 of further reading: …
=> Removed broken link and fixed incorrect id in url

src/content/translations/pl/developers/docs/standards/tokens/erc-721/index.md
The sentence in line 18 has been mistranslated. The sentence will sound more natural in Polish upon the change.
1. The sentence in line 18 (more specifically, the phrase "That said,") was mistranslated. I've made it more readable in Polish.
2. Changed the typo in "każdeego" - it should be "każdego".
3. Changed "aplikacja zdecentralizowana" to "zdecentralizowana aplikacja" - sounds more natural.
=> Updated a mistranslated sentence in line 18 + typos.

src/content/upgrades/merge/index.md
Just a small typo fix - `it's` -> `its`
=> Fix small typo on merge page

src/content/developers/docs/networking-layer/index.md
Fixes the broken "nodes and clients" link on the [Networking layer page](https://ethereum.org/en/developers/docs/networking-layer/).
=> fix(content): use correct "nodes and clients" anchor url on "Networking layer" page

src/components/BannerNotification.tsx
The component has been migrated to chakra ui. 
The emotion styled component has been removed from the file
---
- There was a nested styling in the Banner component and it has been refactored in the `sx` attribute of chakra-ui.
- Using the useMediaQuery hook from chakra ui for the min-width media query used in pure css
**_Large screen_**
**_Small screen_**
---
**_Large screen_**
**_Small screen_**
Once the first migration is validated, I'll make all the missing PRs for the assigned components.
---
Refs: #6374
=> [UI] Banner Notification: migrate component to chakra ui

src/content/upgrades/merge/index.md
The link without the protocol is pointing to https://ethereum.org/enbordel.wtf which is the current address + the link. In order for it to be a standalone external link, the protocol can be added to it.
See it here at: https://ethereum.org/en/upgrades/merge/#wen-merge
=> fix(content): Fixes the link to bordel

.github/workflows/docsearchConfig.json, .github/workflows/docsearchConfigScript.js
- During the migration to Chakra, there were some new classes and pseudo elements that have been added to headers that we need to ignore now.
- https://docsearch.algolia.com/docs/legacy/config-file/#selectors_exclude-optional
=> add classes to selectors_exclude to ignore new chakra way of doing links

src/intl/de/common.json, src/intl/el/common.json, src/intl/es/common.json, src/intl/fr/common.json, src/intl/hi/common.json, src/intl/id/common.json, src/intl/it/common.json, src/intl/ja/common.json, src/intl/ko/common.json, src/intl/nl/common.json, src/intl/pl/common.json, src/intl/pt-br/common.json, src/intl/pt/common.json, src/intl/ru/common.json, src/intl/sw/common.json, src/intl/tr/common.json, src/intl/vi/common.json, src/intl/zh/common.json
Adds community translations for the 'merge-complete' string (i.e. `"merge-complete": "The Merge is complete! Welcome to a new greener Ethereum."`) for the following 18 languages:
- Swahili
- Chinese simplified
- Korean
- Greek
- Dutch
- Japanese
- Russian
- Portuguese Brazilian
- Turkish
- Portuguese
- Polish
- French
- German
- Italian
- Hindi
- Vietnamese
- Spanish
- Indonesian
=> Add 'merge-complete' community translations

src/data/community-meetups.json
We're a community running bi-weekly Cryptobars in the heart of Stockholm. Matos is the creators club where crypto natives, Ethereum enthusiasts and industrial figureheads go to hang out. Come build with us.
Added [Matos](https://matos.club/) to the Ethereum meetups list.
=> Added Matos to community-meetups.json

src/components/Layout.tsx
Confetti hook on the homepage is causing a glitch on Apple mobile devices. Removing from homepage.
(Not experiencing this bug on The Merge page `/upgrades/merge`; leaving the confetti on this page for the time being)
=> Patch: remove confetti from homepage

src/intl/pt-br/common.json
changed menu mobile light mode button string from "leve" to "claro"
=> pt-br: fixed mobile color mode button name

src/content/upgrades/beacon-chain/index.md
This simply replaces the `develoeprs` typo with `developers` across the codebase, but there only happens to be one case.
=> Fix "develoeprs" typo in `beacon-chain/index.md`

src/content/history/index.md
We included a link to Beacon Chain upgrade page. Figure it's relevant to include one for the Merge page as well 😄 
None
=> Add Merge link to Bellatrix upgrade

src/components/FeedbackWidget.tsx
* The button content of our feedback widget looked empty in light-mode (because the text color was also white). 
* I removed one line in ButtonContainer, this makes the text color the same as the theme color (blue in light-mode, orange in dark-mode). 
* Related to #7876
=> Fixed empty buttons in feedback widget [Fixes #7876]

src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md, src/content/translations/it/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md, src/content/translations/zh/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
Change broken link from `/fundamentals/rlp` to `/developers/docs/data-structures-and-encoding/rlp`
Fix #7944
=> Fix broken links in Particia Merkle Trie page

src/content/developers/docs/nodes-and-clients/index.md
Update NB on the https://ethereum.org/en/developers/docs/nodes-and-clients page to reflect that it is not possible to run an execution client without a consensus client.
https://github.com/ethereum/ethereum-org-website/issues/7700
https://github.com/ethereum/ethereum-org-website/issues/7401
=> minor edit in docs to correspond to post-Merge reality

src/components/BeaconChainActions.tsx, src/components/ShardChainsList.tsx, src/content/community/grants/staking-community-grants/index.md, src/content/developers/docs/consensus-mechanisms/pos/index.md
Use Internet Archive copy for the moment
=> Link beacon chain explainer to archive.org copy

src/content/developers/docs/storage/index.md
Like the issue(https://github.com/ethereum/ethereum-org-website/issues/2887) mentioned which Dean opened 1 year ago, Crust provide the dStorage platform on the top of IPFS and has already served multiple web3 projects including Uniswap, AAVE, Ceramic, Polkadot Apps, ... and Crust also have extended the dStorage function into multiple smart contract platforms, including Ethereum, Polygon, Solana, Near, Polkadot, Avalanche and Aptos.
So I'd love to open this PR to include Crust Network into Ethereum's documentation.  
- Add dStorage protocol Crust Network as new dStorage solution
- Add IPFS Scan, the IPFS storage explorer into `Additional Consideration`
- https://github.com/ethereum/ethereum-org-website/issues/2887
=> Add Crust Network into dStorage doc [Fixes #2887]

src/content/developers/docs/nodes-and-clients/index.md
This section previously only contained Infura, Alchemy, and Quicknode. Chainstack has been added to this paragraph as an additional third party API provider to increase visibility. Chainstack is included under the nodes-as-a-service page (https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/) but is excluded from this page and has thus been added to account for this.
=> Added Chainstack to Alternatives section.

src/content/community/research/index.md
updates info for post-merge
#7075
=> update research page for post-merge

src/pages/upgrades/vision.tsx
- Temporary patch to simply remove card that is no longer applicable post-merge
- Adds max width to limit size of remaining two cards
#7075
Preview link: https://ethereumorgwebsitedev01-cardremoval.gtsb.io/en/upgrades/vision
Can continue to discuss more options and plans for this page moving forward.
=> Patch: remove vision card

src/scripts/crowdin-import.ts
The crowdin-import script was not working for Swedish because we didn't have the Crowdin lang-code (`sv-SE`) mapped to the one we use (`se`). This PR fixes that.
=> Add Swedish mapping to crowdin-import script

src/content/upgrades/merge/index.md
There were duplicate 'items' word, therefore removed one of them.
There is no related issue
=> Fix typo: remove duplicate 'items' word

src/content/zero-knowledge-proofs.md
Adds a missing header ID on zk page, which was throwing a warning during builds
=> Add missing header ID on zk page

src/content/developers/docs/nodes-and-clients/index.md
Title was missing for Prysm section in consensus nodes. 
I've also added a link for Nimbus documentation.
=> Minor updates for nodes and clients page

i18n/config.json
Fixes #8016
Wrong hreflang code as per Google's web.dev
Correct code is fil as per [List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
=> Correct hreflang for Filipino

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Typos: Content and Link Prater testnet -> Goerli testnet 
Deletion: Obsolete contests regarding the Merge
*  Typos: Content and Link Prater testnet -> Goerli testnet  in Spin up your own Ethereum node page
Prater Testnet Launchpad page is no longer unavailable.
So, I changed Prater to Goerli in this page.
* Deletion: Obsolete contests regarding the Merge
none
=> Typo and Deletion in Run-a-Node Page

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Blog links to 404 not found in docs, this fixes the link
[https://github.com/ethereum/ethereum-org-website/issues/8010](https://github.com/ethereum/ethereum-org-website/issues/8010)
=> Fixed broken blog link on Running a node page

.github/ISSUE_TEMPLATE/bug_report.yaml
Replaced placeholder text with template text in bug issue template
Currently, the bug issue template uses placeholder text to describe a bug. Now, it has been updated to template text that can be edited.
(Replace placeholder text with template text) https://github.com/ethereum/ethereum-org-website/issues/8029
=> Update bug_report.yaml to use template text instead of placeholder

src/content/developers/docs/gas/index.md
Changed the ordering of this [line](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/gas/index.md#after-the-london-upgrade-post-london)
Currently the example is split in 2 parts and the title is breaking that example. i.e The position of title is not appropriate.
With this change the example would make sense with the context and with the title.
Documentation changes
#8034
=> Fix ordering of items in developer docs (gas) 

src/content/developers/docs/development-networks/index.md
Updates content of "development networks" dev docs page to remove Ropsten launchpad link, update "miner" terminology, and link out to the blog post about testnet deprecation.
#7075
=> Update development networks content

gatsby-config.ts, src/@chakra-ui/gatsby-plugin/components/Modal.ts, src/@chakra-ui/gatsby-plugin/components/index.ts, src/@chakra-ui/gatsby-plugin/theme.ts, src/components/CodeModal.tsx
Migrates `CodeModal` component from `emotion` to `chakra-ui`.
> To do this change, I had to use the `modal` component from chakra-ui and adjust the zIndex of portals to `1001`  (by default, it's `40`) because the modal overlay was behind the header of the website (`z-index: 1000`).
> 
> The result's pretty close to the original, but it has some little differences (really minimal) to preserve most of the default values of chakra.
https://github.com/ethereum/ethereum-org-website/issues/6374
=> refactor(code-modal): use chakra modal with custom variant

src/content/developers/docs/scaling/validium/index.md
Fix a typo in the `Batch submission` part.
Change the word `Lverifier` to `verifier` in the following sentence:
`
After executing a batch of transactions, the operator submits the associated validity proof to the Lverifier contract and proposes a new state root to the main contract.
`
=> ✏️ Fix typo in scaling/validium

src/pages/get-eth.tsx
on page https://ethereum.org/en/get-eth/ under Community posts on security there is a broken link to a coinbase.com article titled 'the keys to keeping your crypto safe':
https://blog.coinbase.com/the-keys-to-keeping-your-crypto-safe-96d497cce6cf
Blog.coinbase.com subdomain has been redirected to coinbase.com/blog subdirectory. However this post is no longer available and couldn't be found on waybackmachine. I found the medium post for Philip Martin and linked this instead.
Fixed broken coinbase.com link with the authors medium.com article.
=> Fix broken link on the get-eth page

src/pages/developers/tutorials.tsx, src/utils/tutorials.ts
Filtering tutorials on `/developers/tutorials` wasn't considering a current language option, but default `filteredTutorials` was considered well. So I copied the logic for filtering with the current language respect.
https://github.com/ethereum/ethereum-org-website/issues/7904
=> Fixed #7904, Respect current language for filtering tutorials

src/content/developers/docs/apis/json-rpc/index.md
Fixes the anchors which were swapped for `net_peerCount` and `net_listening`
This fixex:
https://github.com/ethereum/ethereum-org-website/issues/8116
=> Fix incorrect link anchors for net_listening and net_peercount rpc

src/pages/developers/learning-tools.tsx
on https://ethereum.org/en/developers/learning-tools/:
The link https://platzi.com/blockchain is no longer available, so I have replaced for the alternative link on the platzi domain.
Replaced broken link
=> Fix broken Platzi link (Spanish developer resource) 

src/components/BeaconChainActions.tsx, src/components/ShardChainsList.tsx, src/content/community/grants/staking-community-grants/index.md, src/content/developers/docs/consensus-mechanisms/pos/index.md
Beacon chain explainer is back and now on github pages.
Thus reverting the temporary usage of archive.org https://github.com/ethereum/ethereum-org-website/pull/7953
Reverting is done via "git revert" command.
=> Fix ethosdev links (reverts #7953)

src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/index.md, src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
fix: #7905 
- Fix link
- Add spacing above the callout
- The wording is also aligned
=> Fix markdown link display

src/content/defi/index.md
Adds https://defirate.com as a source of DeFi information, particularly lending data.
Closes #8065
=> Add DeFiRate.com as a resource for DeFi information

src/content/developers/tutorials/run-node-raspberry-pi/index.md
The existing tutorial was no longer fit for purpose because it was out of sync with the Ethereum-on-Arm docs, had dead download links and was configured for pre-merge Ethereum. This PR fixes those issues and brings the tutorial up to date.
=> update raspberry pi tutorial

src/intl/en/page-layer-2.json
Just a small grammar edit in the page-layer-2.json file.
Description
Line 17 added an "a" to "A layer 2 is "a" separate blockchain"
Related Issue
[Fixes ethereum#8177]
=> Update to page-layer-2.json - small grammar error

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Proposal for deletion of obsolete sentences after the Merge in the run-a-node page
* Deleted sentences regarding the Merge preparation for the clients
* Deleted to the Link  /developers/tutorials/run-light-node-geth/ because of the Geth light node under development after the Merge currently
* Light node PoS version (https://github.com/ethereum/go-ethereum/issues/25623)
=> Proposal for Deletion of Obsolete Sentences after the Merge in the run-a-node Page

src/content/energy-consumption/index.md
The proof-of-work link leads the user to the description of proof-of-stake which is incorrect.
The proof-of-work link now correctly leads to the proof-of-work docs instead of the proof-of-stake docs
=> Replaced proof of work linkwith correct link

src/content/developers/docs/consensus-mechanisms/pow/mining-algorithms/index.md, src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
Sorry for the repeated requests for review. I have been trying to fix the markdown links (https://github.com/ethereum/ethereum-org-website/pull/8130), but it seems that in some cases they do not work at the build, so the broken links in the production version have not been fixed. I have approached this in a different way, so please check it out.
https://github.com/ethereum/ethereum-org-website/pull/8130
=> Change markdown links to anchor links

src/content/developers/docs/consensus-mechanisms/pos/index.md
Adding video about PoS for visual learners just like on the PoW page (https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/)
Adding video ID regarding PoS before the Further Reading section in order to help visual learners understand about PoS
=> Adding a video about proof-of-stake

src/lambda/l2beat.ts, src/pages/layer-2.tsx
L2Beat changed its API URL and the response structure, so I modified the URL and adapted the calculations to work with the new structure of the response. They have 4 items on the JSON root; I assumed that what we need It's the data from `layers2s` key.
https://github.com/ethereum/ethereum-org-website/issues/8143
=> Change L2Beat API

src/pages/wallets/find-wallet.tsx
Now clicking outside wallet filter panel closes it on mobile.
Closes #8170
https://user-images.githubusercontent.com/41188167/195924788-278a3c11-0c24-4bea-b3fb-96b7a06202e9.mov
=> fix: Tap outside wallet filter panel to close on mobile

src/pages/get-eth.tsx
In page https://ethereum.org/en/get-eth/ we have an example public ETH address, where we mark this as an example address only. 
My PR adds 3 lines of simple css to the CodeBox class in this page which will disable the copying of text in the browser, to ensure the user cannot copy this ETH address by mistake.
=> Disable text selection of example ETH address

src/components/GitStars.tsx
Update Github icon, star Emoji, and GitStars component styling to use chakra-ui rather than emotion styling according to [chakra-migration-guide.md](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md).
Follow docs/api-keys.md step 1 to get a personal access token to add `GATSBY_GITHUB_TOKEN_READ_ONLY` to the .env file. You need this token to query [Github's graphql api](https://api.github.com/graphql) for github star counts. Then follow overall readme instructions to run the frontend locally.
hideStars: false
http://localhost:8000/en/developers/local-environment/
hideStars: true
http://localhost:8000/en/upgrades/get-involved/
https://github.com/ethereum/ethereum-org-website/issues/8049
=> migrate GitStars component to chakra-ui [Fixes #8049]

src/components/OrderedList.tsx
This migrates the [OrderedList](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/OrderedList.tsx)
For @pettinarip: In terms of completely replacing it with just using Chakra's `OrderedList`, I believe this component could be retained. Despite it being primitive in the logic, it is used in at least two places on the site with specific styling, unless there is interest in eventually creating styling variants.
There is an alternative approach that comes to mind, but I'll hear your feedback and thoughts first. 😃 
#6374
=> Migrate `OrderedList` to Chakra

src/components/Layer2ProductCard.tsx
Migrates `Layer2ProductCard` component from `emotion` to `chakra-ui`
#6374
=> Migrate Layer2ProductCard to Chakra 

src/components/CardList.tsx, src/components/Link.tsx, src/utils/url.ts
Migrate `CardList` component to Chakra.
It also includes a refactor on the URL util functions that used to live inside the `Link` component. I've moved all of those related functions to its own file (`src/utils/url.ts`).
#6374
=> UI migrate `CardList`

src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
Clarifies that missing head votes are not penalized in Ethereum's incentive layer.
#8297
=> fix info on head vote in rewards/penalties page

src/intl/en/page-upgrades-get-involved-bug-bounty.json
As stated in the bug bounty program, the EF Bug Bounty Program bases its impact on the effect a vulnerability has on the Network: "The severity is calculated according to the OWASP risk rating model based on Impact on the Ethereum Network and Likelihood. [View OWASP method](https://www.owasp.org/index.php/OWASP_Risk_Rating_Methodology)"
Below the above line, there is an example of what could be described as a "High" vulnerability which states "There is a consensus bug between two clients, but it is difficult or impractical for the attacker to trigger the event." - This could indeed be accurate from a network perspective - if the issue was in a client being used by a large part of the network (say 45%), while if the consensus bug was in a client being used by 0.1% of the network it would …
=> Updated Bug Bounty Example

src/components/EthVideo.tsx
Replace dark mode check from emotion with `useColorModeValue` hook from Chakra.
This provides a way to not use a nested ternary to determine what source to use, while returning a local video asset based on color mode if no `videoSrc` provided.
None
=> refactor(eth-video): apply `useColorModeValue` for video source

src/components/UpgradeTableOfContents.tsx
Migrate UpgradeTableOfContents from styled component to ChakraUI
#6374
=> Refactor UpgradeTableOfContents component to use ChakraUI

src/components/Staking/StakingProductsCardGrid.tsx
Fix the bullet point for <p/> tag misalignment in issue #7866
add `margin: 1rem auto 1rem 0` into p tag as suggested
#7866
=> Fix bullet points misalign in staking - saas providers

src/pages-conditional/what-is-ethereum.tsx
"Number of transactions today" was calculated from [the result of `/txs`](https://ethereum.org/.netlify/functions/txs) ([src/lambda/txs.ts](https://github.com/ethereum/ethereum-org-website/blob/dev/src/lambda/txs.ts))
After ecf1791bf5ffae6c3edf756617ab07b7f212ea22 commit (included in v5.0.0), `.result` was handled in `/txs` already.
So there are no need to handle `.result` in [`src/pages-conditional/what-is-ethereum.tsx`](https://github.com/minhoryang/ethereum-org-website/blob/dev/src/pages-conditional/what-is-ethereum.tsx).
FYI, [`src/components/StatsBoxGrid.tsx`](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/StatsBoxGrid.tsx) was also using `/txs` and already patched this in 13 Jul  (https://github.com/ethereum/ethereum-org-website/commit/214600eb509ffa228af16f …
=> Fixed #7817, Handle /txs response correctly for 'Number of transactions today'

src/content/developers/docs/apis/backend/index.md, src/content/developers/docs/apis/javascript/index.md
Fixed the broken link to the JSON-RPC page in the backend page.
The link on the public website is broken. See : https://ethereum.org/en/developers/docs/apis/backend/ 
I also renamed endpoints to methods to align the language.
The GRPC endpoint is litteraly the URI where you can send you JSON-RPC requests. That previous language was confusing.
This is a suggested addition tracked by Issue 
https://github.com/ethereum/ethereum-org-website/issues/8095
=> Fixing broken link and language on /backend page

src/components/MarkdownTable.tsx
Fixed table overflowing on https://ethereum.org/en/developers/docs/evm/opcodes/ page. 
Fixes #8320
=> fix table out of size issue

src/@chakra-ui/gatsby-plugin/components/Button.ts
Overrides the hover effect for the disabled buttons.
Demo:
https://user-images.githubusercontent.com/91947037/196906769-32e22466-445b-4e7a-92d6-933df436ffeb.mp4
Fixes #8295
=> fixes the hover style for disabled button

src/content/upgrades/merge/issuance/index.md
- Updates the "How The Merge impacted ETH supply" page located at [`/upgrades/merge/issuance`](https://ethereum.org/en/upgrades/merge/issuance)
- This copy update intentionally keeps the comparison to a pre-merge PoW world, so users have a comparison from what the issuance is now compared to what is was prior to The Merge. 
- Adds a section on "Calculating average gas price for deflation" which dives into some math surrounding how to calculate the average gas price needed to completely offset the issuance.
- [Closes #7873]
- #7075
Note, PR #7921 was also put up to address updated ETH issuance, but removes the comparison to pre-merge Ethereum. After some discussion and given this page is located at `/upgrades/merge/issuance`, recommending we table that PR for now and plan to create a …
=> Updates merge impact on ether issuance page [Closes #7873]

src/content/developers/docs/blocks/index.md
=> Correct typo

src/content/developers/docs/apis/backend/index.md
Added Coinbase Cloud as a node provider.
Coinbase Cloud now has a public offering as a Node Provider for Ethereum.
https://www.coinbase.com/blog/coinbase-cloud-launches-platform-for-web3-developers
This update is listing Coinbase Node as an alternative in the backend page : https://ethereum.org/en/developers/docs/apis/backend/
This is a suggested addition tracked by Issue 
https://github.com/ethereum/ethereum-org-website/issues/8098
=> Update backend doc with one addition node provider

src/components/ExpandableInfo.tsx, src/pages/run-a-node.tsx
This migrates the [ExpandableInfo](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/ExpandableInfo.tsx)
[Per discussion in Discord](https://discordapp.com/channels/714888181740339261/1003686202257449111/1027648992416383117), there was the question about using the `Accordion` prop for this component, but did not make sense to do so for accessibility because of it's current usage as only a forced-open iteration on a single page. So going by the existing functionality was considered the best course of action.
See comments below for explanation on certain Chakra additions.
#6374
=> Migrate `ExpandableInfo` to Chakra

src/content/glossary/index.md
Term name
DAG
Term definition
DAG stands for Directed Acyclic Graph. It is a data structure composed of nodes and links between them. Previous to The Merge, Ethereum used a DAG in its [proof-of-work](https://ethereum.org/en/glossary/#pow) algorithm, [Ethash](https://ethereum.org/en/glossary/#ethash).
Sources, if any (please do not submit copywrited content without appropriate approval)
No response
Ethereum.org links
No response
Additional context
As it stands today, it might cause confusion for new and existing users, given that it states in present form that Etherum "uses a DAG in its proof-of-work algorithm", which is no longer the case.
=> Update existing glossary term #8163

src/components/MergeInfographic.tsx
Hey @pettinarip, I've gone ahead and fixed the bugs that I encountered during the migration of the MergeInfographic component.
I wasn't sure about the best practices to fixing the bugs to a pull request so I closed the [previous pull request](https://github.com/ethereum/ethereum-org-website/pull/8209) and created a new one with my final version. (would love some insight on whether this was the right approach). 
_Related Issue #6374_
=> refactor: migrate the merge infographic component from emotion to chakraui #6374

src/components/CallToContribute.tsx
Refactor `CallToContribute` post Chakra migration.
- Create `ContentColumn` reusable component for the image and the content.
- Use the `Show` component to only show the image above the `lg` breakpoint (see additional information below).
- Create `DescriptionParagraph` reusable component for the content paragraphs.
N/A
As of this PR, the Chakra UI migration is not complete. If I were to do the following with `Show`:
```tsx
<Show above="lg">
```
The token value would not be recognized. This is due to the under the hood functionality of `Show` using the `useTheme` hook from Chakra. `useTheme` looks through the emotion package to retrieve theme values from the Context, and I believe it is receiving the old theme config instead of the Chakra config. Indeed there is no issue when applying …
=> Refactor `CallToContribute` component

src/content/developers/docs/nodes-and-clients/client-diversity/index.md
Fix inconsistent spelling of YouTube
The spelling of YouTube is inconsistent.
There is an instance of spelling as 'Youtube' on the website which should be correctly written as YouTube.
https://github.com/ethereum/ethereum-org-website/issues/8393
=> Fix incorrect spelling of 'YouTube' on client diversity developer doc

src/content/upgrades/merge/index.md
Fixing the typo on The Merge page
There is a typo in the following sentence: with all it's accounts, balances, smart contracts, and blockchain state
'it's' means 'it is', and is incorrect in this context.
https://github.com/ethereum/ethereum-org-website/issues/8392
=> Fix incorrect spelling on The Merge page

src/components/DocsNav.tsx
- fix breakpoint token value naming (`m` to `md`)
- add props to parent `Flex` for aria pagination pattern
- rename `Card` to `CardLink`
- apply `LinkOverlay` tandem to `CardLink`
- simplify `CardLink` so it's content is reusable
- update styling logic for doc data passed to `CardLink`
- replace empty `Flex` components with `Spacer`
None
When providing dynamic values to Chakra props, instead of something like...
```tsx
<Box textAlign={ isTrue ? 'right' : undefined } >
```
I usually do this
```tsx
// Clears typecheck by not returning 'false' (will return the prop or `undefined`)
<Box { ...( isTrue && { textAlign: 'right' } ) } >
```
This is my first time using the latter approach in this repo. If this is not preferred, I will gladly fix it! 😅
=> Refactor `DocsNav` with Chakra `LinkOverlay`, etc.

src/utils/url.ts
External links can also be IPFS hashes, noticeable through "ipfs://" for the base layer protocol itself or "ipfs" somewhere within a public gateway link. Since Ethereum and IPFS go hand in hand when it comes to decentralized storage, we should recognize IPFS hashes as valid links to prepare ethereum.org for years to come when IPFS adoption will inevitably increase.
=> Include IPFS hashes as external link possibility

src/content/contributing/translation-program/content-buckets/index.md, src/content/translations/it/developers/docs/consensus-mechanisms/pow/mining-algorithms/ethash/index.md, src/content/translations/it/developers/docs/consensus-mechanisms/pow/mining/index.md, src/content/translations/zh/developers/docs/consensus-mechanisms/pow/mining-algorithms/ethash/index.md, src/content/translations/zh/developers/docs/consensus-mechanisms/pow/mining/index.md, src/data/developer-docs-links.yaml, src/intl/en/page-developers-docs.json, src/intl/it/page-developers-docs.json, src/intl/zh/page-developers-docs.json
- Fixes any references of `Dagger Hashamoto` to `Dagger Hashimoto`
Fixes: https://github.com/ethereum/ethereum-org-website/issues/8421
=> change references to `Dagger Hashamoto` to `Dagger Hashimoto`

src/data/execution-bounty-hunters.csv
+2000 points for finding and reporting a vulnerability.
=> Increasing ChainSecurity's score on bug bounty leaderboard

src/content/developers/docs/networking-layer/index.md
My goal is to provide clarity to other developers working on the discovery of execution nodes. The current version of Geth doesn't use v5 but instead uses v4. As a new networking developer, I learned the hard way that v5 isn't used by Geth and so this change makes it easier for other devs to learn that v4 is what is currently in use.
#8310
=> Add discv4/v5 note to Execution Discovery section

src/content/developers/docs/accounts/index.md
The example on the accounts page uses Geth's `personal` namespace which is going to be deprecated very soon. This change swaps it out for `clef newaccount` which is more future-proof.
=> accounts: remove example using deprecated namespace

src/content/developers/docs/networks/index.md
Post-merge, there has been a shift in recommendations for how Sepolia and Goerli should be used by the community.
This update reflects these changes.
=> Update recommendations on Sepolia / Goerli usage

src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
`There is no penalty for missign the head vote` --> `There is no penalty for missing the head vote`
=> correct spelling on Proof of Stake rewards page

src/components/HorizontalCard.tsx
Refactored `HorizontalCard` component for Chakra UI.
=> Refactor HorizontalCard for Chakra UI

src/content/developers/docs/programming-languages/rust/index.md
It leads to a 404
Remove the bullet that links to Oasis SDK Getting Started guide. The content at that link is now gone. I tried to find a place it had moved, but the whole site's contents seem to have shifted.
=> Remove dead link to Oasis SDK

src/components/CardList.tsx
Due to CSS stacking context, the description text in the `Card` component of `CardList` is rendered on top of the pseudo element rendered by `LinkOverlay`, because the component for this text applies the `opacity` prop with a value less than 1 which puts it higher in the z-stack than the `zIndex={0}` rendered by the overlay.
This results in an area above the description text where you would not be able to access the anchor element to click.
This PR converts the `opacity` prop to the `color` prop.
In addition, adds `useColorModeValue` to ensure the color of this text in both light and dark mode meets the color contrast requirements for accessibility.
N/A
=> Fix link overlay in `CardList`

src/@chakra-ui/gatsby-plugin/styles.ts
Recover the [old global styles for the `a` tag](https://github.com/ethereum/ethereum-org-website/blob/v4.0.0/src/theme.ts#L416) to temporarily fix the unstyled links we have on the JSON files.
Note: these global styles are going to soon be removed on the #8406 PR by fixing the root problem which is using our chakra `Link` component on the translation files.
#8547
=> Fix unstyled links living in the JSON files [Fixes #8547]

src/content/developers/docs/smart-contracts/security/index.md
Moved smart contract auditing services and bug bounty platforms from the [testing page](https://ethereum.org/en/developers/docs/smart-contracts/testing/) to the smart contract security page. I gave some context on the proposal [here](https://github.com/ethereum/ethereum-org-website/pull/8362#issue-1422468870).
=> Add auditing services and bug bounty platforms to SC security page

src/components/Staking/StakingStatsBox.tsx, src/components/StatsBoxGrid.tsx
Beaconcha.in has offered the use of their API for the staking stats shown on https://ethereum.org/en/staking. We were already using one of their endpoints for Total ETH Staked and Total Validators, and recently added the use of another for Current APR, but we still do not have a link out to them as the source for the data like we do on the homepage for other data streams.
This adds the familiar feeling "info" icon Tooltip for the stats, pointing users to Beaconcha.in, similar to the StatsBoxGrid on the homepage.
https://ethereumorgwebsitedev01-sourceinfo.gtsb.io/en/staking
None filed
=> Adds source info for staking metrics

src/components/Quiz/QuizWidget.tsx
- Send "1" for correct answer, "0" for incorrect
None filed, request per @konopkja
=> Update Matomo tracking eventValue for QuizWidget

src/components/Layout.tsx, src/components/VisuallyHidden.tsx, src/components/ZenMode.tsx
Migrate VisuallyHidden from styled component to ChakraUI
#6374
=> Refactor VisuallyHidden component to use ChakraUI

src/components/Staking/StakingStatsBox.tsx
- Fixes the endpoint URL for pulling latest Beaconcha.in metric related to staking APR.
- "/650" was pulling data from 650 days after Beacon Chain genesis, not the latest
- Removes old endpoint for Total ETH Staked and Total Validators, using new endpoint for these as well to consolidate API calls into one.
- Specifies ETH.STORE as the source for the APR calculation.
Noted by @Buttaa offline 🙏
=> Use latest value from Beaconcha.in endpoint

src/intl/ar/page-run-a-node.json
This issue was found while I was testing the #8585 PR.
For the Arabic language, the closing tag for a link is in the incorrect place. This PR fixes that and lowercase the link text to match what we have in [the current English version](https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en/page-run-a-node.json#L112).
=> Fix closing link tag in Arabic translation file

src/content/translations/de/staking/pools/index.md, src/content/translations/de/staking/saas/index.md, src/content/translations/de/staking/solo/index.md
Fixes incorrect template name. `Staking` does not exist. It was replaced by `staking`.
=> Update template from `Staking` to `staking` in German md files

src/content/developers/docs/ides/index.md
Added the Hardhat VSCode extension. I normally would've added it last, but I think it makes sense to have the VSCode extensions grouped, otherwise the list is like "VSCode extension, formatter, VSCode extension".
No issue.
=> Add Hardhat+Solidity VSCode extension

src/data/quizzes/questionBank.ts
IMHO saying `always` here is wrong/not 100% precise - I have seen people giving away ETH (e.g. to test something out - especially in the early days)
=> Quiz: Make answer more precise

src/content/developers/docs/networks/index.md
Adding more context to choose which public testnet to use.
Also re-ordering so Sepolia comes first (as default for app devs)
=> Add context to testnets and re-order Goerli/Sepolia

src/components/TranslationChartImage.tsx
Current behavior of the `TranslationChartImage` is not responsive in mobile screens. Overflow scrolling is not applied.
New behavior...
- Remove the `layout` option in the query, so the value is set back to the default of `CONSTRAINT`
- Remove wrapper component, as it is no longer needed
The additional refactoring replaces `useColorMode` with `useColorModeValue` for retrieving the images asset paths.
N/A
=> Update `TranslationChartImage` (Post Chakra Migration)

src/pages-conditional/wallets.tsx
The respective article has been moved from coinbase blog to learn.
Changed the broken link from : https://blog.coinbase.com/the-keys-to-keeping-your-crypto-safe-96d497cce6cf 
to : https://www.coinbase.com/learn/crypto-basics/how-to-secure-crypto as it has been moved by coinbase.
Issue: https://github.com/ethereum/ethereum-org-website/issues/8559
=> Fix broken link on wallets page

src/components/FeedbackWidget.tsx
On the feedback widget we switch tenses, "Was this page helpful?" slides out, then the pop-up shows "Is this page helpful?". This PR fixes that so that 'Is this page helpful?' is used consistently on the feedback widget.
https://user-images.githubusercontent.com/62268199/202189898-75371f9c-77c8-4312-98a2-06ec3a528e9e.mov
=> Fix feedback widget copy

docs/deploy-and-review-process.md
This documentation outlines our current processes for how we deploy the latest changes to ethereum.org, and how we prioritize items in our review process.
None
=> Add deploy and review process

src/content/translations/zh/history/index.md, src/content/translations/zh/upgrades/merge/index.md
While reviewing translation imports, encountered some broken markdown link syntax on the `zh` translations. This patches them.
None filed
=> Patch `zh` markdown link syntax

src/@chakra-ui/gatsby-plugin/styles.ts, src/components/YouTube.tsx
Replaces `Box` component with a more robust `AspectRatio` component, which is primarily used for media elements. Adds enhanced sizing with aspect ratio equal, and equal existing sizing of the iframe in its current rendering.
It also creates a better render at mobile screen sizes.
This makes the `iframe` styling in the styles file unnecessary.
N/A
=> Refactor: Use `AspectRatio` in `Youtube` component

src/components/Footer.tsx
Migrate `Footer` component to Chakra
#6374
=> refactor(footer): migrate component to Chakra

src/components/DocLink.tsx
- Remove `Box` wrapping all components and send its props to `LinkBox`
- Remove `position='relative'` from a `Flex` component that preventing the whole component from being clickable.
- Apply `useToken` to use a theme token in the `boxShadow` prop instead of a CSS Variable
- Replace one prop value with a spacing token
- Remove `role="group"` as it is invalid to the accessibility of this component (it's a single item, not a group of items)
N/A
=> Update `DocLink` component (Post Chakra)

src/components/Staking/StakingProductsCardGrid.tsx
Migrate the `StakingProductsCardGrid` component to Chakra UI
>Side Note: This PR also fixes broken styling present in the current production.
#8632
=> Refactor: Migrate `StakingProductsCardGrid` to Chakra

src/components/Staking/StakingProductsCardGrid.tsx
Just removed py={2} from StakingProductCardGrid.tsx  line 309 to reduce spacing
#8696
=> modified StakingProductsCardGrid.tsx

src/@chakra-ui/gatsby-plugin/styles.ts, src/components/YouTube.tsx, src/content/developers/docs/consensus-mechanisms/pos/attack-and-defense/index.md
Adds Chakra's `AspectRatio` component to wrap the embedded iframe used in the PoS [Attack and Defense](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attack-and-defense/#reorgs) page (under the "reorgs" section).
N/A
=> Refactor: Apply `AspectRatio` to iframe in "Attack and Defense" page

package.json, src/components/FeedbackCard.tsx, src/components/Staking/StakingHierarchy.tsx, src/components/Staking/StakingHowSoloWorks.tsx, src/components/Translation.tsx, src/pages-conditional/what-is-ethereum.tsx, src/pages/layer-2.tsx, src/pages/run-a-node.tsx, src/pages/staking/index.tsx, src/pages/upgrades/vision.tsx, yarn.lock
This PR removes the usage of `dangerouslySetInnerHTML` (for security reasons) to insert html content from the translation files. Instead, it uses the [htmr](https://github.com/pveyes/htmr) lib where we can also use our own custom components (similar to what we do with markdown files).
- Revert the usage of `dangerouslySetInnerHTML`
- Use [`htmr`](https://github.com/pveyes/htmr) to parse the inner html that json files may have
- Use our own custom components in the parsing process
#8345
=> i18n lib change - use htmr to parse html inside json files #8585

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Fix broken link
The old link redirected to https://eth-docker.net/docs/About/Overview/ which does not exist anymore.  
Changed to https://eth-docker.net/
=> fix broken link to eth-docker.net

src/content/glossary/index.md
The glossary claims that the zero address is the correct recipient for a contract creation transaction. This is repeated in the entries for `zero address` and `contract creation transaction`.
This info is not correct. The recipient for a contract creation transaction should be `null` not `0x0`. The former triggers contract creation at an address deterministically generated from the senders address/nonce, latter is a normal EOA that can receive ETH.
This PR corrects the info.
=> fix incorrect info in glossary

src/intl/en/page-upgrades-index.json
Fix spelling of Ethereum on https://ethereum.org/en/upgrades/, under _How do I prepare for the upgrades?_
=> Fix spelling of Ethereum

src/@chakra-ui/gatsby-plugin/components/Tabs.ts, src/@chakra-ui/gatsby-plugin/components/index.ts, src/components/Tabs.tsx
Migrate the Tabs component from emotion to chakra
Closes #8639
=> Migrate Tabs to Chakra

src/components/Staking/StakingSurveyBanner.tsx, src/pages/staking/index.tsx, src/templates/staking.tsx
- Adds a banner linking out to the staking survey noted in issue #8654
- Banner added to /staking and all three subpages via the `staking` template
@Rodrigolvc Feel free to suggest alterations to the wording here
- [Closes #8654]
=> Adds staking survey banner to staking pages [Closes #8654]

src/components/ProductCard.tsx
Migrate the `ProductCard` component to Chakra.
#8632
=> Refactor: Migrate `ProductCard` to Chakra

src/content/developers/docs/consensus-mechanisms/pos/faqs/index.md, src/data/developer-docs-links.yaml, src/intl/en/page-developers-docs.json
Adds a page on proof-of-stake FAQs as part of post-merge gaps epic.
#8285
=> add page on proof-of-stake FAQs

src/content/nft/index.md
Kanye West has recently made many antisemitic comments and has [taken pro-nazi stances publicly](https://www.mediamatters.org/infowars/rapper-ye-goes-unhinged-antisemitic-rant-infowars). Earlier in his career the examples on this page were about Kanye the artist and the popular brand of shoes (Yeezys) that he created and marketed. Now Kanye is much more divisive and is a more dangerous name to use as an example. His brand of shoes has also been dropped by Adidas, so, while it is possible he takes his brand to Ethereum next, we can do better than to associate Ethereum with someone who spouts hate so openly.
When people search to learn about NFTs and land on ethereum.org, for many seeing Kanye's name and brand as examples might turn them off of the rest of the educational content that the …
=> Replace Kanye/Yeezy reference NFT with Nike/Jordans

src/components/Staking/StakingHomeTableOfContents.tsx
Migrate the `StakingHomeTableOfContents` component to Chakra UI
#8632
=> Refactor: Migrate `StakingHomeTableOfContents` to Chakra

src/components/Banners/PostMergeBanner.tsx
Migrates `PostMergeBanner` component from `emotion` to `chakra-ui`
#8632
=> refactor: postmergebanner to chakra

src/components/TableOfContents/TableOfContentsMobile.tsx
Fixes issue where the mobile version of `TableOfContents` was still appearing on larger screens because there was no media query check present.
NA
=> fix: apply dynamic visibility for mobile `TableOfContents`

src/components/TableOfContents/index.tsx
This removes an extra type export of `Item` from the main `TableOfContents` file, as it is already exported from [utils.ts](https://github.com/ethereum/ethereum-org-website/blob/efa2d964d6715db1e1b5700ae6a513ade0f54faf/src/components/TableOfContents/utils.ts#L27-L30)
=> Chore: remove extra `Item` type export in `TableOfContents`

src/content/developers/docs/programming-languages/rust/index.md
`SputnikVM` and `evm_rs` were pointing to the same repository. The bug was fixed by merging both under the name "SputnikVM", as indicated in the target github.
`evm_rs` was removed from the list.
`SputnikVM` link has been updated
Issue #8577
=> Rust projects and tools (link collision)

src/content/developers/docs/smart-contracts/security/index.md
Added Hacken (https://hacken.io/) to the Smart contract auditing services list;
Added HackenProof (https://hackenproof.com/) to the Bug bounty platforms list.
Description
Updating the Smart contract auditing services list; Updating the Bug bounty platforms list.
Related Issue
Related to issue https://github.com/ethereum/ethereum-org-website/issues/8543
=> Add Hacken and Hackenproof

package.json, src/components/Emoji.tsx, src/content/translations/it/developers/tutorials/how-to-view-nft-in-metamask/index.md, yarn.lock
Bump `react-emoji-render` to include [fix on cdn](https://github.com/tommoor/react-emoji-render/pull/107).
Fixes #9135
=> Fix twemoji cdn issue

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Add missing line continuation for lighthouse launch command. The multi-line command does not have line continuation for the first line and therefore would fail.
=> Add missing line continuation for lighthouse launch command

src/components/SideNav.tsx
Migrate the `SideNav` component to Chakra
#8632
=> Migrate the `SideNav` component to Chakra

src/content/developers/docs/intro-to-ethereum/index.md
Small typo/grammar error: " it is used to weight 'votes' for newly proposed blocks, ..." -> " it is used to weigh 'votes' for newly proposed blocks, ..."
https://github.com/ethereum/ethereum-org-website/issues/8898
=> fix: small grammar typo

src/pages-conditional/dapps.tsx
Updated the CryptoPunks link since, after the acquisition of Yuga Labs, the web app will soon be moving from "https://www.larvalabs.com/cryptopunks" to "https://cryptopunks.app/" (note for example that, by selecting a CryptoPunks, you will already be redirected to the new site) 🆕
=> Update a Dapp Link

src/components/BoxGrid.tsx
Migrate the `BoxGrid` component to Chakra
#8632
=> Migrate the `BoxGrid` component to Chakra

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
I think the fees are expressed as gwei and not wei in the send_transaction 'gas'
=> send_transaction

src/content/developers/docs/consensus-mechanisms/pos/keys/index.md
Small typo/grammar issue: "Ethereum secures user's assets using public-private key cryptography." -> "Ethereum secures user assets using public-private key cryptography."
https://github.com/ethereum/ethereum-org-website/issues/8898
=> fix: small typo/grammar issue

src/content/developers/docs/consensus-mechanisms/pos/block-proposal/index.md
"... equal to the `1/512 * effective balance` for each slashed validator." -> "...equal to `1/512 * effective balance` for each slashed validator."
https://github.com/ethereum/ethereum-org-website/issues/8898
=> fix: small grammar correction

src/content/developers/docs/consensus-mechanisms/pos/block-proposal/index.md
Currently the subheader does not render. 
`### Random selection {#random-selection}` gets displayed as paragraph text erroneously.
https://github.com/ethereum/ethereum-org-website/issues/8934
=> fix: incorrect formating of sub-header

src/content/glossary/index.md
=> Fix typo in the glossary causing broken link

src/content/contributing/index.md, src/content/desci/index.md
DeSci listing policy was previously added to the site but it wasn't obvious where it could be found. This PR adds some more prominent links in the `contributing` and `desci` pages.
=> adds more prominent links to desci listing policy

src/content/developers/docs/scaling/state-channels/index.md
Migrate EThHub data to ethereum.org and remove links to EthHub resource which is being sunset.
EthHub has additional details surrounding specific implementations. Concept-wise, ethereum.org is easier to follow and more comprehensive. 
- Propose to include Raiden as an external link as an example of a payment channel on Ethereum
- Propose migration of EthHub data not found on ethereum.org (additional details & benefits)
- Propose removal of the 2 EthHub links (state channel & payment channel)
- Minor language edits for improved readability
Fixes #8862
=> Migrate EthHub Info & Remove EthHub Links on the state channels developer docs

src/content/developers/docs/scaling/zk-rollups/index.md
Removed link to EthHub which is being sunset.
The ethereum.org zk-rollup page is more comprehensive and easier to reason with. EthHub's resource assumes knowledge of plasma chains but the industry has since moved towards a roll-up centric framework (i.e. newer users are more familiar with rollups instead of plasma). Propose to remove link
#8862
=> Remove EthHub Link from ZK-roll ups developer docs

src/content/developers/docs/scaling/sidechains/index.md
Remove EthHub link as resource is being sunset.
ethereum.org resource covers all the points raised on EthHub
#8862
=> Remove EthHub Link on sidechains developer docs

src/content/defi/index.md
Remove EthHUub link which is being sunset.
The EthHub DeFi resources are largely revolving around specific implementations rather than concepts. ethereum.org has greater details regarding the concepts. Propose to add EthHub examples to the ethereum.org dapps [page](https://ethereum.org/en/dapps/?category=finance) if still relevant. To be tracked under https://github.com/ethereum/ethereum-org-website/issues/9146 instead with regards to adding dapps.
#8862
=> Remove EthHub link on DeFi page

src/content/developers/docs/nodes-and-clients/index.md
Remove link to EthHub link which is being sunset. Etherem.org contains more updated information hence propose removal to avoid confusion
#8862
=> Remove EthHub link from nodes and clients developer docs

src/content/community/research/index.md
Remove external link to EthHub which is being sunset. As there is an existing link to ethereum.org scaling docs, propose to  conduct a review to integrate EthHub content with ethereum.org scaling [docs](https://ethereum.org/en/developers/docs/scaling/) instead.
#8862
=> Remove EthHub link on community research page

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Remove external link to EthHub which is being sunset. Ethereum.org [guides](https://ethereum.org/en/run-a-node) are more comprehensive and updated hence removing EthHub to avoid confusion (especially following the merge).
#8862
=> Remove EthHub external link from run-a-node developer docs

src/content/developers/docs/oracles/index.md
- Remove EthHub resource which is being sunset
- Integrated description about centralized oracles on EthHub into the ethereum.org page
- Added additional resource links 
#8862
=> Remove EthHub link and update resource links on oracles developer docs

src/content/developers/docs/gas/index.md
Removing EthHub further reading link as ethereum.org page on gas already addresses the concerns in greater detail. Please see linked issue for further details.
#8862
=> Remove reference to EthHub on gas developer docs

src/content/contributing/style-guide/index.md
Update sample link as EthHub resource is being sunset. Sample has been changed to a generic Consensys [article](https://consensys.net/blog/news/the-history-of-ethereum-testnets/) as this is another well-known resource for Ethereum related content.
#8862
=> Replace EthHub sample with ConsenSys on ethereum.org style guide

src/content/community/get-involved/index.md
Remove reference to EthHub resource which is being sunset. Propose to remove as it points users to update a resource which is going to be removed.
#8862
=> Remove EthHub reference from community get-involved page

src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
I'm changing "a user can trade Ethereum with our newly deployed ERC-20 token" to "a user can trade Ethereum _for_ our newly deployed ERC-20 token". It's a single, little word but it makes it much clearer.
In English we tend to say, "I'll trade my hat for that spade" and not "I'll trade my hat with that spade", which makes it sound like I'm using the spade to physically move the hat into someone else's possession. It's so subtle but when you're learning something completely new, you tend to analyse every word.
You could say, "a user can _buy_ Ethereum _with_ our newly deployed ERC-20 token" because you're buying it with ETH.
N/A
=> Change 'with' to 'for' for clarity

src/data/community-meetups.json
Just change the link for Ethereum Madrid meetup as asked by the organizers.
The organizers of the meetup prefer to use meetup.com link instead of the ethereum madrid website, it is also more consistent and therefore more intuitive for users visiting the link, as most of the meetup links on this page point to meetup.com
No additional relevant info to add
=> Fix the URL for Ethereum Madrid meetup

src/content/developers/docs/scaling/state-channels/index.md
fixed "multisig" link
"multisig" in https://ethereum.org/en/developers/docs/scaling/state-channels/ links to https://ethereum.org/endevelopers/docs/smart-contracts/#multisig but it should link to https://ethereum.org/en/developers/docs/smart-contracts/#multisig
changing the relative path from `developers/docs/smart-contracts/#multisig` to `/developers/docs/smart-contracts/#multisig` fixes the link
=> Fix broken link in scaling developer docs

src/components/StatsBoxGrid/GridItem.tsx
We have invalid DOM nesting here. I'm changing the wrapping `Text` to a `Box`.
=> Fix improper tag nesting - causing SSR hydration issue

src/templates/tutorial.tsx
Currently, there is both left and right overflow on tutorial pages, which use the `tutorial.tsx` template:
This issue points to the `div` element wrapping all the content in the `tutorial.tsx` template. The flexbox applied to `main` in the `Layout.tsx` is stretching this `div` past the browser window. Replacing this `div` with a React fragment resolves the global overflow issues for the tutorial pages, and retains the styling in `Layout` to prevent creating other bugs.
This seems to only impact the tutorial pages and no other templates.
N/A
=> Fix: Replace `div` with fragment in `tutorial` template

src/content/decentralized-identity/index.md
Noticed that we're missing a question mark from the "What is identity" header on the DID page; this PR corrects it to make it consistent with the remainder of the page.
None filed
=> Add missing question mark on DID header

redirects.json, src/content/about/community-lead/index.md
- Remove old redirect rule to /about page
- A couple tweaks, mainly updating ethereum.org from absolute to relative links
#9219
=> Community lead tweaks

src/content/glossary/index.md
Add CFI and EOF as entries in the glossary.
CFI for its relevance around EIP and network upgrade discussions, and EOF given it is under significant development and several related EIPs for EOF are CFI.
=> Add CFI and EOF to glossary

src/pages/run-a-node.tsx
Fixed a link for the installation of DAppNode on ARM📍
=> Fix a link on run-a-node page

src/content/developers/docs/consensus-mechanisms/index.md, src/content/developers/docs/mev/index.md
There were 2 " receive receive " on line 151 in the documentation section of last paragraph of Proposer-Builder Separation. I fixed the dual "receive" into 1 "receive". Kindly merge this PR. It will fix the grammar mistake, and the documentation will look good. Thank you!
I was reading about the MEV on ethereum.org. Then I stumbled upon this grammar mistake and I thought I should make a pull request and fix this issue as it creates a hurdle in my learning/reading experience.
Typo in the last paragraph of Proposer-Builder Separation Line 151. https://github.com/ethereum/ethereum-org-website/issues/9032
=>  Typo in the MEV Proposer-Builder Separation section Line 151.

src/content/developers/docs/consensus-mechanisms/index.md
It was a grammatical error. There were 2 "the" mentioned under block creation for the statement "The canonical chain is then determined by a fork-choice rule that selects the set of blocks that have had the most work done to mine them."
Removed one "the".
=>  ethereum-org-website

src/@chakra-ui/gatsby-plugin/foundations/shadows.ts, src/components/TranslationLeaderboard.tsx
Convert `TranslationLeaderboard.tsx` file to Chakra
Close: #8640
Epic: #8632
=> Convert `translationLeaderboard` to chakra

src/components/StatErrorMessage.tsx, src/components/StatLoadingMessage.tsx
Convert the StatLoadingMessage component to Chakra
Epic: #6374
=> chore: convert statLoadingMessage

src/content/developers/docs/data-structures-and-encoding/ssz/index.md
* `calcuator` -> `calculator` under [`Further reading` section](https://ethereum.org/en/developers/docs/data-structures-and-encoding/ssz/#further-reading)
=> Fix typo in SSZ documentation

src/content/developers/docs/apis/json-rpc/index.md
Adds note to the method description for `eth_protocolVersion` explaining that it is not available in Geth. This is in response to some user feedback. Currently geth.ethereum.org links to this page for the `eth` namespace definition rather than listing out the methods. However, this specific method is not actually available in geth, although
it is available in other clients.
=> add note to eth_protocolVersion in RPC-API

src/content/developers/docs/consensus-mechanisms/pos/block-proposal/index.md
Fixes the `Random selection` section title that was incorrectly displayed on the [website](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/block-proposal/#who-produces-blocks).
It seems that there was incorrect spacing in the markdown of the page which caused the incorrect display of the title for the section.
=> Fix the random selection title in block proposal page

src/components/ButtonLink.tsx, src/components/Link.tsx
The language which loads to should be `en` as we are requesting the user to see the latest `en` version and seeking their help to translate the page. It will fix the empty text in the button issue as well.
Please advice, we should not load the `en` version on `Translate Page` click. So that I can make changes accordingly.
#9312 #9313
=> fix the translate page button not showing the text

src/content/developers/tutorials/run-node-raspberry-pi/index.md
- Fixes sha256 hash for `ethonarm_22.04.00.img.zip` 
- https://ethereum-on-arm-documentation.readthedocs.io/en/latest/quick-guide/download-and-install.html#id2
https://www.notion.so/efdn/change-instructions-in-tutorial-d512f287a0794751bef574569c97c3a6
=> [Patch] ethonarm_22.04.00.img.zip sha256 checksum

src/content/developers/docs/nodes-and-clients/index.md
* Removed OpenEthereum from "Nodes and clients" page
There is a note added in this PR https://github.com/ethereum/ethereum-org-website/commit/2440b9e8d5a23415ea52d2368471fc413225db88 that OpenEthereum client is deprecated.
I've also removed it from the list of clients in  "SYNCHRONIZATION MODES" section.
Resolve ethereum/ethereum-org-website#6389
=> Remove OpenEthereum from "Nodes and clients" page

src/content/history/index.md
Adds the EIPs included in the Paris upgrade to the ethereum.org website's history section. 
Adds a card under the Paris upgrade section on the History page with links to EIP's 3675 and 4399 [included therein](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md).
=> Add EIPs included in Paris upgrade to History section

src/components/SimpleTable.tsx
- Removes LinkBox and LinkOverlay implementations as its causing issues on Safari (see issue for more info)
- Adds ButtonLink to get to external link instead
Fixes: https://github.com/ethereum/ethereum-org-website/issues/9386
=> Bug report: all links lead to gemini on safari - stablecoins page

gatsby-config.ts
Currently https://ethereum.org/sitemap/sitemap-index.xml gives a 404 error.
Fix sitemap output config to be aligned with the robots file (defined in `gatsby-plugin-robots-txt`).
=> Fix sitemap output

src/content/developers/docs/transactions/index.md
added the `from` key and its description as `the address of the sender, that will be signing the transaction. This will be an externally-owned account as contract accounts cannot send transactions.`
The `from` key in this sample transaction object has not been included in the descriptions.
=> Added `from` key to transaction information

src/content/developers/docs/scaling/zk-rollups/index.md
Polygon Hermez no longer exists and link is non-functional, should be renamed to Polygon zkEVM [Fixes #9263]
This PR resolves the link error and changes the description:
https://docs.hermez.io/zkEVM/architecture/introduction
https://polygon.technology/solutions/polygon-zkevm
Old version here:
https://github.com/0xPolygonHermez/zkevm-doc/blob/feature/merge-hermez-1.0-docs/mkdocs/docs/zkEVM/architecture/introduction.md or
https://docs.hermez.io/zkEVM/zkProver/Verifiable-Computations/Fibonacci
Updated similar version: https://wiki.polygon.technology/docs/zkEVM/zkProver/mfibonacci-example
Fixes #9263
=> Polygon Hermez no longer exists and link is non-functional, should be renamed to Polygon zkEVM 

src/content/enterprise/index.md
Epirus has been rebranded to Sirato and is now focussed on data and analytics for blockchains.
https://github.com/ethereum/ethereum-org-website/pull/9278
=> Update Epirus reference with Sirato

src/content/contributing/adding-staking-products/index.md
Current links lead to an empty issue template:
We want to link to the staking product template:
None
=> Fix link to staking issue template

src/components/Layout.tsx, src/pages/staking/index.tsx
Stake page hero banner is not showing fullwidth in xl screens
#9307
=> Fix stakes width issues on xl

src/components/Checkbox.tsx
Fix the checkbox button using static `white` colour for both dark/light theme. Converted the property to read from variable.
#9327 
**Dark** 
**Light**
=> fix the checbox static white color check on all themes

src/content/whitepaper/index.md
The Whitepaper page contains a link to a "Mike Hearn on Smart Property at Turing Festival" YouTube video which has since been removed. PR to remove this dead link
Fixes #9083
=> Whitepaper Page: Removed dead link [Fixes #9083]

src/components/ExpandableCard.tsx, src/components/Link.tsx, src/components/Staking/ShanghaiCapella.tsx, src/components/Staking/WithdrawalCredentials.tsx, src/components/Staking/WithdrawalsTabComparison.tsx, src/content/history/index.md, src/content/staking/withdrawals/index.md, src/templates/staking.tsx
- Few bug patches an fix-ups related to the new /staking/withdrawals page
- Enables matomo event tracking for internal hash links
- Adds matomo tracking to contents of withdrawals page, including custom hash link events taking advantage of the modification to the `Link` component.
https://ethereumorgwebsitedev01-withdrawalsv2.gatsbyjs.io/en/staking/withdrawals/
- #9101
- Fixes #9456
=> Withdrawals page updates

src/pages/developers/learning-tools.tsx
Bug fixed URL error mentioned in issue https://github.com/ethereum/ethereum-org-website/issues/9504
Fixed the URL from "alchemycom" to "alchemy.com".
=> Fix broken Alchemy link

src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
Edit page as EthHub is being sunset.
As Ethereum has switched to PoS, the included EthHub link still maintains its relevancy as a historical archive. As such, updated EthHub link to point to the [web archive snapshot on 17/09/22](https://web.archive.org/web/20220917012350/https://docs.ethhub.io/using-ethereum/mining/). Additionally, added a section on ommer blocks to give further context to readers that might have come across the "uncle" term when Ethereum was still under PoW.
Fixes #8862
=> Update Ommer Description & EthHub Link [Fixes #8862]

src/content/developers/docs/blocks/index.md
- Edited introductory paragraph to aid understanding of block segmentation and linking of blocks
- Added details to Ethereum's [average block time](https://etherscan.io/chart/blocktime) to provide greater context on Ethereum's transition to PoS
Fixes #9039
=> Docs: Update Blocks page language & description [Fixes #9039]

src/content/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit/index.md
I was surprised to see that custom errors are not mentioned in the [Downsizing contracts](https://ethereum.org/en/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit/) tutorial.
Here's a [related tweet](https://twitter.com/PaulRBerg/status/1616030271236628480).
=> Mention custom errors as a way to downsize contracts

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Existing DAppNode url is broken, change to "First steps with Dappnode" docs
The DappNode docs link [here](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#automatized-setup) links to a page that says: 
```
Oh oh... You probably weren't looking for this.
We've changed the documentation to serve you better and we might have broken this link.
```
The original URL mentions "custom hardware" but I couldn't find that page in the existing docs, so I pointed it to a general First steps doc. 
[Issue link](https://github.com/ethereum/ethereum-org-website/issues/9380)
=> Fix broken DAppNode url

src/pages/index.tsx, src/types.ts
Migrate the Home page to use Chakra UI
#9353
=> refactor(pages): migrate home page to Chakra

src/pages/layer-2.tsx
The URL to view the risk assessment of L2 chains is different. The old URL takes you to TVL tab.
=> chore: Update l2beat Risk assessment button URL

.github/workflows/chromatic.yml
This PR adds the Github action to automate Chromatic UI's visual regression testing in conjunction with StorybookJS. 
The workflow is customized for the specific usage of this project with the following expectations:
- Action to be triggered only if there are file changes within the `components`, `pages`, `pages-conditional`, and `templates` directories (subject to be altered later as needed)
- Testing only fails if errors exist in story files.
- Reliance on ensuring that the steps generated by this action in the PR checks are to be reviewed and accepted before merge, and that if any change is denied within the Chromatic dashboard by a reviewer, that it should fail the check and prevent the PR from being merged.
Along with comments given by me to note anything specific in the file or …
=> ci: Add Workflow for ChromaticUI Visual Regression Testing

src/content/developers/docs/nodes-and-clients/node-architecture/index.md
I found a typo in the Ethereum documentation.
This commit will resolve a typo issue in the documentation.
No related issue.
=> Resolved Typo in Documentation

.github/labeler.yml
To better organise PRs, this adds an event label to PRs that add to the community-events JSON file.
=> Add labels to any event PR

src/content/roadmap/scaling/index.md
"new network designs that enable efficiently confirm" -> "new network designs that enable the network to efficiently confirm"
I added some missing words.
=> Fix grammar error in scaling page

src/data/community-events.json
changing edcon.io to https://edcon.io/
=> Correcting wrong EDCON URL

package.json, src/@chakra-ui/gatsby-plugin/theme.ts, src/components/Breadcrumbs.tsx, src/components/CallToContribute.tsx, src/components/Staking/StakingHierarchy.tsx, src/components/TableOfContents/TableOfContentsMobile.tsx, src/components/Trilemma/index.tsx, yarn.lock
_NOTE: Recommend this PR for https://github.com/ethereum/ethereum-org-website/issues/9548 to not fall behind while implementing the DS. May need to consider timing in adding this while migrations are still ongoing_
This PR keeps Chakra up-to-date in preparation for the new DS
- Updates dependency to latest (v.2.5.1)
- Adds the Chakra CLI to generate typing for any custom tokens. This allow these tokens to be visible during auto-completion in the IDE with style props.
- Adds the package scripts `theme` and `theme:watch` to generate the typing and to generate the typing on watch when updating the theme config.
- Adds a `postinstall` package script to generate the typing when updating package deps or when a developer forks the project into their local environment for the first time.
- …
=> refactor: Bump Chakra-UI dep to latest

src/pages/studio.tsx
Refactored `src/pages/studio.tsx` to use native Chakra UI components instead of Styled Components.
[#9353](https://github.com/ethereum/ethereum-org-website/issues/9353)
=> refactor: replaced styled components w/ Chakra components in studio.tsx

src/components/Nav/Mobile.tsx
-When the search bar is opened in a small or medium device, the Glyph Button animation is Not visible nor it is clickable
when we open the website in the mobile form.
Open the search container the menu button turns into a cancel button which is not the requirement and hence a bug.
fixes:- https://github.com/ethereum/ethereum-org-website/issues/9275
=> Close button updated

src/content/developers/docs/apis/json-rpc/index.md
Changed expect to except in "See eth_call parameters, except that all properties are optional."
N/A
=> Fixed typo in index.md

src/content/developers/docs/networks/index.md
Hey there - adding Alchemy's newly launched Sepolia Faucet to offer devs resources like this as they build. Also given the unfortunate Goerli ETH shortage, I moved up Paradigm and Alchemy's faucets as they have consistently provided free testETH and we want to help developers find available supply.
=> Added Alchemy's new Sepolia Faucet

src/content/developers/docs/data-availability/index.md
This PR fixes a broken link in the [Data availability](https://ethereum.org/en/developers/docs/data-availability/) page. The broken link in question is https://celestia.org/learn/basics-of-modular-blockchains/ which was replaced with its updated link https://celestia.org/learn/basics-of-modular-blockchains/modular-and-monolithic-blockchains/
=> Fix broken link in 'Data availability' page in the docs

src/content/staking/withdrawals/index.md, src/intl/en/page-staking.json, src/intl/en/page-upgrades.json
- Moves dateKey to `page-staking.json` namespace to fix broken translation component
None filed
https://ethereum.org/en/staking/withdrawals
With patch:
=> Patch intl key-value namespace

src/components/Quiz/QuizWidget.tsx, src/components/Staking/WithdrawalCredentials.tsx, src/pages/staking/deposit-contract.tsx
When updating the Chakra UI dep, it introduced [a change in the `Button` component props](https://github.com/chakra-ui/chakra-ui/commit/0f376650efce9eb2d2cba3484ffe4e3a73364504) where `disabled` became `isDisabled`. This addresses that change.
=> fix: replace `disabled` with `isDisabled` for button components

src/pages/learn/index.tsx
- Replace `Blockchain in developing countries` link with a wayback machine link
Fixes https://github.com/ethereum/ethereum-org-website/issues/8704
=> Blockchain in developing countries link broken on learn page

src/data/layer-2/cex-layer-2-support.json
Kraken recently [enabled withdrawals and deposits for Arbitrum](https://blog.kraken.com/post/17590/eth-deposits-and-withdrawals-available-on-arbitrum/?utm_source=Social&utm_medium=Twitter&utm_campaign=Eth+on+Arb). Adds data for this to `cex-layer-2-support` for layer-2 page.
=> add kraken to cex-layer-2-support

src/data/community-events.json
ETHGlobal announced that Lisbon replaces Istanbul
https://ethglobal.medium.com/updates-to-the-2023-ethglobal-hackathon-season-1d2a9d418c91
ETHGlobal Istanbul is now expected later in the year.
replace ETHGlobal Istanbul with Lisbon as per ETHGlobal announcement
#9707
=> replace ETHGlobal Istanbul with Lisbon

src/content/developers/docs/transactions/index.md
Hyperlinks `RLP-encoded` to ethereum.org doc page on rlp in `TYPED TRANSACTION ENVELOPE` section of `Transactions` topic
=> Add RLP encoding link to `TYPED TRANSACTION ENVELOPE` section

src/content/developers/docs/apis/javascript/index.md
Adds [viem](https://viem.sh) to JavaScript libraries section.
=> docs: add viem to libraries

src/content/developers/docs/programming-languages/python/index.md
I am adding a link to The state of Python in the blockchain 2023 report. It includes an overview of Python developer opportunities in the Ethereum ecosystem and lists ~15 different Python-based projects for Ethereum developer and integrators.
As a disclaimer I am one of the authors of the report.
[Here is the direct link to the report](https://tradingstrategy.ai/blog/the-state-of-python-in-blockchain-in-2023).
Adding a new link to the Beginner articles section on Python documentation
=> Add The state fo Python in blockchain 2023 report to Python docs

redirects.json
- Adds default redirect for `/upgrades/shard-chains` so that it redirects to `/en/upgrades/sharding`
Fixes https://github.com/ethereum/ethereum-org-website/issues/9067
=> [Fix] Bad redirect from /upgrades/shard-chains/ 

src/content/developers/docs/oracles/index.md
The link to UMA's Optimistic Oracle page is dead. This updates the link and fixes a minor typo.
N/A
=> fix: fix dead link to UMA Optimistic Oracle

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/suggest_dapp.yaml, .github/ISSUE_TEMPLATE/suggest_dev_tool.yaml, .github/ISSUE_TEMPLATE/suggest_exchange.yaml, .github/ISSUE_TEMPLATE/suggest_glossary_term.yaml, .github/ISSUE_TEMPLATE/suggest_layer2.yaml, .github/ISSUE_TEMPLATE/suggest_staking_product.yaml, .github/ISSUE_TEMPLATE/suggest_tutorial.yaml, .github/ISSUE_TEMPLATE/suggest_wallet.yaml, .github/workflows/issue-triage-label.yml, docs/github-issue-triage-process.md
- adds documentation on issue process
- adds question for each issue template asking if the person who creates the issue wants to contribute
- adds workflow to label every issue opened with `needs-triage` label
- adds information that links out to process documentation in README
https://github.com/ethereum/ethereum-org-website/issues/9059
=> Create issue process

src/data/community-events.json
I'd like to propose adding BlockSplit to the list of Ethereum events. More than two-thirds of BlockSplit's content have historically been dedicated to Ethereum. Majority of our sponsors are Ethereum businesses. We have always held multiple full day Ethereum workshops for developers. Besides that, we are last year's grantees of Ethereum Foundation ESP.
=> Adding BlockSplit to the list of Ethereum events

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/suggest_dapp.yaml, .github/ISSUE_TEMPLATE/suggest_dev_tool.yaml, .github/ISSUE_TEMPLATE/suggest_exchange.yaml, .github/ISSUE_TEMPLATE/suggest_glossary_term.yaml, .github/ISSUE_TEMPLATE/suggest_layer2.yaml, .github/ISSUE_TEMPLATE/suggest_staking_product.yaml, .github/ISSUE_TEMPLATE/suggest_tutorial.yaml, .github/ISSUE_TEMPLATE/suggest_wallet.yaml
- Updates attribute option syntax for issue templates to use `label: <string>` and `required: <bool>` syntax
- Ensures all templates are using a unique ID for "Would you like to work on this issue?" question
- [Fixes #9760]
=> Fix GitHub issue template syntax [Fixes #9760]

src/components/Link.tsx
Moves the external link icon in the `Link` component from the after pseudo to a child element. This allows for the icon to be hidden from screen readers.
Also adds hidden indicator text that the link will open a new tab. This dissolves possible confusion for a blind user on where they are at in the browser. (Are they still on the website to be able to go back a page, or someplace else? It might not always be clear depending on the link text.)
#8877
=> a11y(link): update indicators for external links

src/data/staking-products.json
Updates StaFi `hasPermissionlessNodes` flag to `true`, in response to #9740
- Fixes #9740
=> Update StaFi permissionless flag [Fixes #9740]

src/content/developers/docs/smart-contracts/formal-verification/index.md
correction
Saying "but" for logical conjunction is confusing and should be avoided.
I suggest replacing "but" by "and also."
=> Clear wording for logical conjunction

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
The following links were throwing **Page Not Found** errors. On inspection, I noticed that they were pointing to outdated endpoint and hence the error. So, I have updated the links 
```
https://docs.uniswap.org/v2/smart-contracts/router01/
```
to 
```
https://docs.uniswap.org/contracts/v2/reference/smart-contracts/router-01
```
Same goes for the Router02.
=> style: Updated links to Router01 and Router02 docs

src/content/developers/docs/networks/index.md
Infura just released a Sepolia Testnet Faucet that lets you claim 0.5 Sepolia ETH per day, for free. It's super easy to use, just visit https://www.infura.io/faucet, sign in to your Infura account, enter your wallet address, and claim.
Sepolia Testnet is an important tool for testing your smart contracts before deploying them on mainnet environments. With our Testnet Faucet, you can easily catch bugs and reduce the cost of deploying tests on mainnet.
Add Infura Sepolia Testnet Faucet #9820
=> Add Infura Sepolia Faucet #9820

src/content/history/index.md
- Updates Shanghai EIP list with EIP-6049
Ref: https://blog.ethereum.org/2023/03/28/shapella-mainnet-announcement
None filed
=> Add EIP-6049 to Shanghai EIPs

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
- Many client pairs require more than 1TB today (e.g. Teku + Besu require +1.1GB)
- EthStaker has been recommending 2TB since before the merge: https://www.reddit.com/r/ethstaker/comments/rizos9/hardware_for_staking_2022_edition/
- eth.org itself recommends 2TB here: https://ethereum.org/en/run-a-node/#build-your-own
- As of right now the verkle trie migration will require ELs to temporarily store a copy of both the merkle patricia tree and verkle trie. Currently that would be just under 2TB, but depending on how soon the verkle trie upgrade is launched (unlikely before Q1 2024), it could pass 2TB in the meantime. (This could be mitigated if state expiry / EIP 4444 is launched in the interim.)
=> Update min. requirements for SSD from 1TB to 2TB

src/templates/roadmap.tsx
- Added margin to the wrapper containing header buttons 
- Added margin between header and main text in mobile view
[ Roadmap pages: UI bugs on mobile #9804 ](https://github.com/ethereum/ethereum-org-website/issues/9804)
=> Fix spacing in roadmap page [Fixes #9804]

gatsby-node.ts
Currently, we are trying to get the `isOutdated` flag from `node.fields` which is incorrect and for some reason that defaults to `true`. So, all pages that doesn't have `isOutdated` set, will be marked as outdated.
Here you can see an example where the page [is not set as outdated](https://github.com/ethereum/ethereum-org-website/blob/move-upgrades-pages/src/content/translations/es/web3/index.md) (is undefined) but the `isOutdated` is defaulting to `true`, https://ethereum.org/es/web3/
This PR query that flag from the frontmatter, where the `isOutdated` is declared.
Here is an example where we are setting that flag on the md files: https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/translations/hu/developers/docs/gas/index.md
=> Fix `isOutdated` flag

src/scripts/reorgIntlFiles.ts
Prettier will format the json files with a new line at the end of each file.
Currently the script doesn't add that new line automatically, so it will create a bunch of git differences every time you run the script. To avoid having that problem, we add that extra line to the script to do the same as prettier.
=> Intl reorg script - new line at the end of the files

src/components/Breadcrumbs.tsx
On smaller screen sizes, when breadcrumb text is big, the items are wrapped to next line instead of breaking each breadcrumb text in two
[ Mobile breadcrumb navigation wrong spacing #9805 ](https://github.com/ethereum/ethereum-org-website/issues/9805)
=> Fix breadcrumb spacing in mobile view

src/intl/de/page-about.json, src/intl/en/page-about.json
Fixes translations on the energy consumption chart: https://ethereum.org/en/energy-consumption/
Adding the translations in the `page-about` namespace as is the one used for the `static` template (the template used for this page).
#9843
=> Fix energy consumption chart translations

src/components/Nav/Mobile.tsx
Theme toggle button in sidebar navigation now shows expected label and icon. 
- Label "Dark" and moon icon when the theme is set to light
- Label "Light" and sun icon when the theme is set to dark
[Theme switch button issue on small screen sizes #9822](https://github.com/ethereum/ethereum-org-website/issues/9822)
=> Fix theme toggle button text in mobile [Fixes #9822]

src/templates/roadmap.tsx
The issue of horizontal scrolling caused by overflow on the x-axis in mobile view on the roadmap page has been resolved. The overflow is no longer visible and has been hidden.
[Ethereum roadmap page: Overflow along x-axis #9824 ](https://github.com/ethereum/ethereum-org-website/issues/9824)
Fixes #9824
=> Fix roadmap page overflow in mobile [Fixes #9824]

src/content/developers/docs/nodes-and-clients/index.md
This service was sunset on April 3, 2023.
Announcement tweet from DeFi Dude: https://twitter.com/defidude/status/1643014205442871304
Article: https://defidude.medium.com/sunsetting-archivenode-io-c72a78fe3653
=> Remove reference to ArchiveNode

src/data/community-events.json
Adding ETH Mobile to the calendar of communities around the world. We are the local Ethereum Miami chapter. Also, we have received funding from EF Ecosystem Support in the past as well as for Road To DevCon 2022. 
www.ethmiami.ooo
www.ethmobile.io
"title": "ETH Miami/ ETH Mobile",
"to": "https://www.ethmiami.ooo/",
"sponsor": null,
"location": "Hybrid",
"description": " We are Ethereum Miami. Joined the Road to DevCon and launched ETH Mobile.",
"startDate": "2023-09-15th",
"endDate": "2023-09-17th"
=> chore: add ETHMobile Miami to community-events.json

src/content/developers/docs/standards/tokens/erc-1155/index.md
This commit will fix a typo in a broken link.
- `#recieve_hook` => `#receive_hook`
=> Fix a typo in the "Hooks" section

src/intl/en/learn-quizzes.json
Fixes "page-assets-merge" translation in the learning quizzes.
=> Fix translation in learning quizzes

src/content/developers/docs/consensus-mechanisms/pos/attack-and-defense/index.md
added the missing developer slug to the 'incentive layer' and 'LMD-GHOST' links on the 'Consensus Mechanisms - Proof of Stake: Attack and Defense' [page](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/attack-and-defense/#prerequisites).
Invalid link 'incentive layer' and 'LMD-GHOST' #9866
=> fix: invalid link 'incentive layer' and 'LMD-GHOST' [ #9866]

src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
Fix according to [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718#receipts)
`Receipt` contains `ReceiptPayload`, not `TransactionPayload`.
=> Fix Receipts Trie description

src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
Change Ethereum to ether because that's how it's supposed to be!
Also, this tutorial uses both terms simultaneously right now and that's just wrong lol.
=> Change Ethereum to ether in tutorial

src/components/Staking/StakingProductsCardGrid.tsx
- Patches the key name for ethpool icon
https://ethereumorgwebsitedev01-patchethpoolicon.gatsbyjs.io/en/staking/saas/#saas-providers
=> [patch] ethpool icon key name

src/content/staking/withdrawals/index.md
Resolves typo on Staking Withdrawals page described in [#9927](https://github.com/ethereum/ethereum-org-website/issues/9927)
I changed the word 'with' to 'will' in the following sentence to help it make sense:
`At this time the account with be marked as fully “withdrawable”.`
[#9927](https://github.com/ethereum/ethereum-org-website/issues/9927)
=> fix nonsensical wording [Fixes #9927]

src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
This pull request fixes a small typo in the how-to-use-tellor-as-your-oracle guide. In the BTC/USD Example section, on line 65, _queryID is used instead of _queryId.
=> Fix typo in how-to-use-tellor-as-your-oracle

src/content/developers/docs/smart-contracts/testing/index.md
Updated the [Dynamic Analysis Tools section of the Smart Contracts Testing page ](https://ethereum.org/en/developers/docs/smart-contracts/testing/#dynamic-analysis-tools) to update the entry for the Harvey fuzzing engine to reflect the updated Consensys Fuzzing project.
- Add links to docs for Scribble and Fuzzing for developers
- Updated description
- Replaced listing for Harvey with the updated projects
- Removed the camelcase "S" from ConsenSys to Consensys b/c of change in branding
https://github.com/ethereum/ethereum-org-website/issues/9917
=> Add Diligence Fuzzing to Dynamic analysis tools #9917

src/components/TableOfContents/index.tsx
This addresses type errors in template files where the `Item` type originally imported from the `TableOfContents` component was no longer recognized. This comes from the restructuring of the component into multiple files where the type now resides in a utils file.
This PR exports the type through the index file of the component to retain the imports in the templates.
N/A
=> fix(TableOfContents): export `Item` type-sig from index file

.storybook/main.js, .storybook/preview.js, src/@chakra-ui/gatsby-plugin/components/components.utils.ts
- Update Storybook config to do the following:
- Set the `stories` option in `.storybook/main.js` to only point to where the story files are located and not up global prefixed titles for the sidebar. Rely only on declaring the structure via the component stories for now.
- Disable autodocs so that docs should only be added on a component-by-component basis with custom markdown
- Disable the backgrounds toggle in `.storybook/preview.js`. This is a color mode toggle for the background of the component preview. However, the Chakra UI addon has it's own toggle that is connected to the Chakra provider and needs to be prioritized.
- Set the `layout` option in `.storybook/preview.js` to `centered` so each rendered preview is in the center of the window. Only override this as needed in the story …
=> refactor: update storybook config and theme util

src/content/developers/docs/nodes-and-clients/run-a-node/index.md
Copy paste doesn't work because there is an extra slash in the command.
=> Remove extra slash in command

src/content/nft/index.md
The link contained in the ERC1155 hyperlink previously sent out to the Enjin blog. Due to some sort of apparent redirect on their end, instead of going to a helpful article, it would just put you at the index of their blog. 
https://github.com/ethereum/ethereum-org-website/issues/9967
=> update ERC1155 link for NFT page

src/content/developers/docs/mev/index.md
Replaced the MEV and ME Link as the old link was linking to a snapshot of the [Internet Archive's Wayback Machine](https://archive.org/web/) by Cloudflare.
Replaced https://research.paradigm.xyz/MEV with https://www.paradigm.xyz/2021/02/mev-and-me
=> Updated MEV and Me Link

src/content/developers/tutorials/eip-1271-smart-contract-signatures/index.md
This PR adds a tutorial about the EIP-1271 (smart contract signature validation) standard to the developer docs, under the "Ethereum Development Tutorials" section.
I wrote this page based on some of my work as a contractor for a web3 startup; the founders of the company generously gave me permission to share some of that knowledge here after I removed company-specific information. I'm happy to share more context/proof of release over email (listed in profile) if necessary.
Let me know what you think!
This page was already written so I figured I'd open a PR right away rather than opening a preliminary issue; if this sort of content isn't a great fit for ethereum.org right now I'm happy to either (a) improve it to more closely align with site standards or (b) close this PR without merging.
=> Add EIP-1271 tutorial to developer docs

src/content/developers/docs/gas/index.md
Hi team,
I guess there is a typo in the example, following the table above it should be an increase of 12.5% and not 112.5%.
Have a nice day ! 👍🏻
=> ✏️ fix typo in base fee example

src/content/developers/docs/data-structures-and-encoding/rlp/index.md
Re-wrote some part of the python code on the page RLP encoding for a better understandinhg.
What I propose is to remove useless `else`; IDK if removing them is againts the **explicit is better than implicit** doctrine; I will let you judge.
Also, some `for` and `if` condition where wrote in one line, which is not really visible when you are know python and even other languages.
=> ♻️ Propose a 'clearer' python code for RLP encoding page

src/content/developers/docs/apis/json-rpc/index.md
Add a eth_chainId section in JSON rpc documentation
The JSON RPC documentation lacks the eth_chainId method from [EIP 695](https://eips.ethereum.org/EIPS/eip-695), so I added a section inside json_rpc index.md to show how to use it
None
=> update JSON rpc documentation to add eth_chainId (EIP 695)

src/components/Nav/useNav.ts
There is currently an error on `dev` when the menu is shown in mobile.
1. On mobile, visit the home page and scroll down a bit
2. Open the menu
3. ERROR: The close icon on the top-right corner is not visible
Removes manual overflow hide logic when the menu is shown.
=> Fix hidden close icon when menu is shown [mobile]

src/pages-conditional/dapps.tsx
Fixed the link to Tornado Cash to the one they use in their [twitter bio](https://twitter.com/TornadoCash) as the current one no longer works.
Just changed a URL on a component :)
Noticed it was broken so decided to fix it
=> Fix Broken Tornado Cash URL

src/intl/en/learn-quizzes.json
- Adds translation strings for `security` and `page-what-is-ethereum-what-is-ether` to `learn-quizzes.json`
=> add missing translation strings for quiz titles

src/content/guides/how-to-register-an-ethereum-account/index.md, src/content/guides/how-to-revoke-token-access/index.md, src/content/guides/how-to-swap-tokens/index.md, src/content/guides/how-to-use-a-bridge/index.md, src/content/guides/how-to-use-a-wallet/index.md, src/content/guides/index.md, src/pages-conditional/dapps.tsx
This PR continues work on updating copy across the e.org website. In this case, the focus is specifically the `Guides` section under the `Learn` tab. I have edited the copy, added just one link to Kernel, and generally tried to keep cutting away for clarity and brevity, while not sacrificing accuracy.
#9869 
It seems like a previous fix I made has been reverted on `dev`, so this corrects #9924 again.
=> Guides Pages Updates

redirects.json, src/components/Banners/Implementations/WritersCohortBanner.tsx, src/pages/community.tsx, src/templates/static.tsx
- Adds a DismissableBanner to promote the ethereum.org writing cohort
=> Writing cohort banner

src/content/security/index.md
Hi everyone! I think there might be a typo on the [Use a hardware wallet](https://ethereum.org/en/security/#use-hardware-wallet) section of the [Security](https://ethereum.org/en/security) page:
> They are considered the most secure wallet option for storing your private keys: your private key touches the internet and stays completely local on your device.
Should be:
> They are considered the most secure wallet option for storing your private keys: your private key **never** touches the internet and stays completely local on your device.
Unless I misunderstood this paragraph?
=> Fix typo in Security - #use-hardware-wallet

src/content/developers/docs/apis/json-rpc/index.md
Run this (with your own RPC URL or Infura ID):
```
curl -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method": "eth_getTransactionByHash", "params": [ "0xc088a442d8b412a48ba4a677b19d5b59bb1f8ebc1fbe66eb72fff1699f62f470" ],"id":1}' https://mainnet.infura.io/v3/<INFURA ID>
```
and it should return:
```
{"jsonrpc":"2.0","id":1,"result":{"accessList":[],"blockHash":"0x58b75e6c12d3b26c5a3c804f71a7118f458d4b5bcbf81eb08a0a1340fbd1318f","blockNumber":"0x10101cd","chainId":"0x1","from":"0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5","gas":"0x7530","gasPrice":"0x4e4f9efc6","hash":"0xc088a442d8b412a48ba4a677b19d5b59bb1f8ebc1fbe66eb72fff1699f62f470","input":"0x","maxFeePerGas":"0x4e4f9efc6","maxPriorityFeePerGas":"0x0","nonce":"0x29548","r":"0x7e460941cfcb2447f601cb99447be92aecddd7ef3d6b1 …
```
=> the `type` field in `eth_getTransactionReceipt` should return a QUANTITY

src/content/translations/de/decentralized-identity/index.md, src/content/translations/de/social-networks/index.md, src/content/translations/es/decentralized-identity/index.md, src/content/translations/es/social-networks/index.md, src/content/translations/it/dao/index.md, src/content/translations/it/decentralized-identity/index.md, src/content/translations/it/defi/index.md, src/content/translations/it/social-networks/index.md, src/content/translations/pt-br/decentralized-identity/index.md, src/content/translations/pt-br/defi/index.md, src/content/translations/pt-br/social-networks/index.md, src/content/translations/zh/decentralized-identity/index.md, src/content/translations/zh/social-networks/index.md
Some non-English pages were using the English path for their frontmatter image, causing the image to 404 and not show.
E.g. using `../../assets/use-cases/dao-2.png` (which only works for English files) instead of `../../../../assets/use-cases/dao-2.png` (which is required for all non-English languages)
This PR fixes these for use case pages.
=> Fix broken use case hero images in non-English languages

src/components/InfoBanner.tsx
We were overriding the default colors in the InfoBanner because we kept the background color blue in both themes, but this introduced a bug where the button colors were wrong :) 
This PR fixes that bug.
#9642
=> Make Buttons in InfoBanner inherit color from theme

src/data/community-events.json
Adding Protocol Berg (https://protocol.berlin/) to the community events lists!
I couldn't find a logic (alphabetical or by date) in the list so I added it to the bottom - let me know if that was incorrect.
=> Add Protocol Berg to Community Events List

src/components/Button/index.tsx
Prevents the custom inner `onClick` logic from being overridden by the consumer of the component.
```tsx
// This use case will scroll to the id and track an event
<Button toId="test" onClick={trackSomeEvent} />
```
Fixes #9972
=> Fix button on click scroll

src/components/EnvWarningBanner.tsx, src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md, src/intl/en/page-developers-tutorials.json, src/templates/tutorial.tsx
Proposing we remove individual warnings about `.env` safety in Tutorial files with a reusable component.
**Why?**
1. Reduces duplicate work for translators
2. More maintainable (allows us to refine component/message to increase effectiveness)
3. Can be dropped anywhere we're telling people to use `.env` files, increasing developer safety
4. Allows us to remove many HTML tags (`<code>` and `<a>` tags) across our tutorial markdown pages, improving maintenance during Crowdin import process
The current banner is used in many places, but really should be in more places to avoid people getting by poor env hygiene:
#10126
=> Add EnvWarningBanner PoC

src/content/developers/docs/scaling/sidechains/index.md
The link https://en.bitcoinwiki.org/wiki/DPoS just redirects to https://bitcoin.org/. Switching to https://en.bitcoin.it/wiki/Delegated_proof_of_stake
This is just a simple change to fix a broken link for DPoS which is going to the wrong page now.
=> DPoS Link Change

src/components/Footer.tsx, src/intl/en/common.json
Changed **community guide and resources** in footer to **Learn Hub**.
Changed **community guide and resources** in footer to **Learn Hub**, and removed community-guide-and-resources **label** from the **common.js** file.
Legacy link on the footer needs to change the label to "Learning hub" 
Fixes #10156
=> fix(community guide): learnhub

src/components/Footer.tsx
Changed the order of the links in the footer Section : **Learn**
Here is an sc preview after changes, **on left** final-website footer links order and **on right** header links order :
Feature request : Regarding the footer links order in Learn Section #10171
=> fix(learn-links): footer links order changed

src/content/developers/tutorials/all-you-can-cache/index.md
=> Fix typo in all you can cache tutorial

src/components/Link.tsx, src/components/MarkdownTable.tsx
Noticed in #10120: the energy consumption has a horizontal scroll under ~680px caused by the table ([also visible in prod](https://ethereum.org/en/energy-consumption/)).
- The `VisuallyHidden` component within the `Link` component is causing the issue.
- Looks like the 1px width of the `VisuallyHidden` component is causing the overflow scroll not to work correctly, causing a horizontal scroll. 
- When I delete it the `VisuallyHidden` component or add `width: 0px` to it, it does not overflow
Suspect this might be a bug in Chakra itself 🤔?
I tested the a11y of this with the width set to 0px, and it works as expected using VoiceOver/JAWs screen readers. However, I isolated this change to links within markdown tables incase there are unintended consequences I'm not aware of...
cc: …
=> Fix table overflow caused by VisuallyHidden width on external Links

src/content/developers/docs/data-structures-and-encoding/ssz/index.md
the calculation of the generalized index in ssz encoding was reported as 
"
Each element in the serialized list has a generalized index equal to 2* *depth + idx where idx is its zero-indexed position in the serialized object and the depth is the number of levels in the Merkle tree, which can be determined as the **square root of the number of elements (leaves)**.
"
whereas it should actually be:
"
Each element in the serialized list has a generalized index equal to 2* *depth + idx where idx is its zero-indexed position in the serialized object and the depth is the number of levels in the Merkle tree, which can be determined as the **base-two logarithm of the number of elements (leaves)**".)
"
updated here.
No issue, error pointed out by @gballet
=> fix description of merkle trie depth calc

src/components/TableOfContents/TableOfContentsMobile.tsx, src/components/TableOfContents/index.tsx, src/pages/staking/index.tsx, src/templates/staking.tsx, src/templates/use-cases.tsx
Migrate `staking` template to Chakra UI
#9353
=> refactor(staking-template): migrate to chakra

src/components/Layer2/Layer2Onboard.tsx
- Migrates the `Layer2Onboard` component to Chakra UI
- Restructures Grid with a more simplified and explicit approach
- Fixes a type issue where the `selectExchangeOnboard` param was a union type when it should be an intersection type
> 🚨 IMPORTANT: This component is affected by #9856 and the new `Input` component
Part of the 2nd wave of UI migrations, #8632
=> refactor(Layer2Onboard): migrate to Chakra UI

src/components/Staking/StakingConsiderations/index.tsx, src/components/Staking/StakingConsiderations/use-staking-considerations.tsx
Migrate `StakingConsiderations` component to Chakra.
- Splits all logic into a separate hook
- Create reusable child component for the indicator blocks
- Add comment to encourage improvements in a11y for future PR
Part of 2nd wave of the UI Migration #8632
=> refactor(StakingConsiderations): migrate to Chakra

src/components/Staking/StakingLaunchpadWidget.tsx
Migrates the `StakingLaunchpadWidget` component to Chakra UI
> 🚨Important: This component is (slightly) impacted by #9856 where the select component is converted from `react-select` to a custom component.
Part of the 2nd wave of the UI migration #8632
=> refactor(StakingLaunchpadWidget): migrate component to Chakra

src/content/developers/docs/design-and-ux/index.md
The Mirror Design System was linked at the bottom of the ENS Design System repo. I figured it would be awesome to include it as well.
Here's the link: [Mirror Design System](https://degen-xyz.vercel.app/), and here's the [github repo](https://github.com/mirror-xyz/degen/tree/main) for anyone who's curious.
=> Add link to Mirror Design System

src/utils/translations.ts
- Fixes the `isLangRightToLeft` function to use a languages config for lang direction instead of being hardcoded values for langauges.
Fixes https://github.com/ethereum/ethereum-org-website/issues/10258
=> isLangRightToLeft function not using language config setting

src/components/PageMetadata.tsx
- Adds a `meta` tag for `docsearch:description` to gain access to the current metadata description for each page via Algolia DocSearch
- About: https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags
=> Add docsearch:description meta tag

.github/workflows/chromatic.yml
Reverts ethereum/ethereum-org-website#10224
The `push` event change didn't work as expected. PRs coming from forked repos are not triggering the chromatic workflow. Its only being triggered by local branches.
=> Revert "Chromatic job - change event for the workflow"

src/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
The documentation link for the Subgraph manifest is broken. I believe I have changed it to the new correct URL.
=> Fix broken link for subgraph manifest

src/content/developers/docs/apis/json-rpc/index.md
Currently, [the `net_version` return example paragraph](https://ethereum.org/en/developers/docs/apis/json-rpc/#net_version) reads like this:
This PR makes 2 updates to this paragraph:
- Removes [deprecated testnets](https://blog.ethereum.org/2022/06/21/testnet-deprecation) and adds Sepolia as an example
- Updates the list into a bulleted list for easier readability
=> chore: update example network IDs

src/components/Staking/StakingHierarchy.tsx
- Remove boxSize causing overflow and offset bug on Safari
Fixes https://github.com/ethereum/ethereum-org-website/issues/10274
=> Staking page StakingHierarchy safari

src/components/BannerGrid/index.tsx
Fixed padding for smaller screens
Fixes #10217
=> fix: Fixed padding in What is Ethereum section

src/content/developers/docs/networks/index.md
- Remove deprecated faucets for layer 2 testnets
=> remove deprecated or non existent faucets for L2

src/content/nft/index.md
Hey!
Adding Alchemy's NFT APIs store as I’ve found it to be a useful web directory. It has information about respective NFT minting tools and their chains. Thought this would allow devs to play around and mint their own NFTs using the API directory, allowing them to better understand the rest of the article.
=> Added Link to Popular NFT APIs in Further Reading

src/content/enterprise/index.md
Hi there, 
I came across your enterprise developer resource listing for ethereum and found that Zeeve is not listed there. I take this opportunity to bring to your attention that Zeeve has been one of the most popular no code web3 platforms for enterprises and has been providing RPC node hosting services. Hereby, i request you to add Zeeve to your directory for Node as a Service.  Zeeve is a cloud-based platform for managing and deploying applications. It provides a comprehensive set of features for developers to quickly and easily deploy their applications to the cloud. Zeeve offers a range of features, including automated deployment of   applications to the cloud of your choice, monitoring of applications, automated security and compliance and so on.  We believe that Zeeve is an …
=> Request to add Zeeve in Enterprise resources

src/content/enterprise/private-ethereum/index.md
Hi there, 
I came across your private ethereum listing for ethereum and found that Zeeve is not listed there. I take this opportunity to bring to your attention that Zeeve has been one of the most popular no code web3 platforms for enterprises and has been providing RPC node hosting services. Hereby, i request you to add Zeeve to your directory for Node as a Service.  Zeeve is a cloud-based platform for managing and deploying applications. It provides a comprehensive set of features for developers to quickly and easily deploy their applications to the cloud. Zeeve offers a range of features, including automated deployment of   applications to the cloud of your choice, monitoring of applications, automated security and compliance and so on.  We believe that Zeeve is an excellent addition …
=> Request to add Zeeve in Private ethereum

src/content/developers/docs/consensus-mechanisms/pos/gasper/index.md
Fixes typo in `developers/docs/consensus-mechanisms/pos/gasper/`
=> Fix typo in gasper developer docs

gatsby-node.ts
English pages should never display the Translation Banner as they are always updated.
Fixes the logic inside the `checkIsPageOutdated` function to always return English paths as updated.
=> Fix Translation Banner appearing on English pages

src/components/Quiz/QuizSummary.tsx, src/intl/en/learn-quizzes.json, src/intl/pt-br/learn-quizzes.json, src/intl/zh/learn-quizzes.json
The current quiz summary is a little confusing, as it isn't entirely clear what 'Total' means.
- To make this clearer, we can switch 'Total' with 'Questions'.
- We already have a 'questions' string in the JSON file, so simply replaced the string and removed the unused JSON keys
#10320
=> Improve QuizSummary copy

src/data/community-events.json, src/data/community-meetups.json
Add ETHBrussels and the monthly Crypto Wednesdays (organized by DAO Brussels) to this page: https://ethereum.org/en/community/events/
=> Represent Brussels on ethereum.org

src/@chakra-ui/gatsby-plugin/components/Tag/index.ts
Increases line-height of the `Tag` component to account for multi-line text.
Also adds padding adjustments to accommodate the fix.
Screenshot from Storybook
Closes #10265
=> fix(theme/tag): increase label line-height for multi-line

src/components/Link.tsx, src/constants.ts, src/utils/url.ts
- Updates the link component to force links to `/discord/` to use the full `https://ethereum.org/discord/` path. The former is being treated as an internal link and not triggering the desired redirect until a user refreshes the page at that path. By using the full path, it triggers the proper redirect for the Discord invite link.
- I saw two options here, one where we require editors to use the full path when linking out to this path, or another where we just add logic to the `Link` component to check for this relative path (`/discord/`) and update accordingly.
- I went with the second option here and have added a check for this path in `Link`, and then adjusting the string to the full path if it matches.
Thank you to @megatheikal for reporting! And my apologies, this got brought up …
=> Force /discord/ invite path links to full url

src/data/staking-products.json
IIRC, the Lido "Trustless" indicator was marked false due to `0x00` withdrawal credentials that had not been updated. This has reportedly been completed now (cc: @isidorosp), with request to update field value. PR flips the `isTrustless` boolean for Lido to `true`
Note, ongoing discussion in #6452 regarding potentially redefining that category, but this PR does not address anything related to changing the definition.
Reported on Discord
=> Update Lido trustless indicator

src/components/Staking/StakingCommunityCallout.tsx
`StakingCommunityCallout` migration to Chakra UI.
https://github.com/ethereum/ethereum-org-website/issues/8632
=> Migrate `StakingCommunityCallout` component

src/content/developers/docs/nodes-and-clients/node-architecture/index.md
Fixed a typo: overs --> over.
N/A
=> Fix typo in node comparison table

src/content/developers/docs/standards/tokens/erc-721/index.md
The web3 python library API has been updated and these calls were not working:
- `to_checksum_address` instead of `toChecksumAddress`
- `get_logs` instead of `getLogs`
- `block_number` instead of `blockNumber`
- `w3.keccak` instead of `w3.sha3`
Also cryptokitties does not have many transactions anymore. Recommended to increase the number backward searching blocks up from 120 if no events are found.
Added condition `recent_tx` not empty, since `recent_tx[0]` is accessed and this does not always exists (if no event is found)
=> Update index.md (old web3 python API was being used)

src/components/ProductDisclaimer.tsx, src/content/staking/pools/index.md, src/content/staking/saas/index.md, src/content/staking/solo/index.md, src/intl/en/common.json, src/templates/staking.tsx
- Adds a basic disclaimer for product/service listings
- String added to `common.json` and component made for reusability where needed
=> Endorsement disclaimer

redirects.json
Currently, we have the following warning on the build:
```
warn There are routes that match both page and redirect. Pages take precedence over redirects so the redirect will not work:
- page: "/quizzes/" and redirect: "/quizzes" -> "/en/quizzes/"
```
Removes `/quizzes` => `/en/quizzes` redirect from `redirects.json` since that rule is already generated automatically by the code in `gatsby-node.ts`.
=> Fix quizzes extra redirect

src/content/contributing/translation-program/resources/index.md
https://ethereum.org/en/contributing/translation-program/resources/#office-hours affected page. 
For the changes, I generated a discord invite link that will not expire, redirecting to #office-hours-voice channel.
Expected behavior on clicking the invite link is to redirect to #office-hours-voice channel.
Code change is to replace the invalid discord invite link https://discord.gg/geKhWjtF with a valid one https://discord.gg/Sfz7jqpBWU
Closes #10530
=> fix discord invite link on translation program resources page

src/data/community-events.json
[ETHLisbon](https://twitter.com/ETHLisbon) is an Ethereum-focused hackathon bringing together the best Web 3.0 builders to the crypto capital of Europe.
Included ETHLisbon 2023 in the list of community events.
=> Added ETHLisbon 2023 Event to Community Meetups

src/data/community-meetups.json
The original Ethereum Hong Kong meetup group has been inactive for recent years. We want to propose adding another local developer meetup group 852dev.xyz, which focuses also on web3 technologies and often hosts blockchain-related seminars, onto the list.
=> Add Hong Kong community 852dev.xyz to Community Meetups

src/content/developers/docs/gas/index.md
Fix percentage calculations.
When we want to increase 100 by 10%, we should calculate `100 * 110%` not `100 * 10%` as in example :)
None
=> Fix math % multiplication typo

src/components/Staking/StakingConsiderations/index.tsx, src/components/Staking/StakingConsiderations/use-staking-considerations.tsx
This is part of the UI migration epic #6374
Removes the `styled` dependeny from the `StakingConsiderations` component.
=> `StakingConsiderations` refactor - remove `styled` dep

src/components/InfoBanner.tsx
Background colors for `InfoBanner` are customized and not color-mode responsive, while the text is. This causes a clash of white text in dark mode on a light background.
PR forces use of "light" color mode settings at all times for all elements of the component, using the `LightMode` Chakra-UI component. Intended to be a patch until proper design adjustments implemented.
None filed
=> Wrap InfoBanner in LightMode component

src/content/translations/de/developers/docs/gas/index.md
In the DE translation of the docs, at the "gas" page, the "gwei" value is missing one "0". You can see that if you compare it to the EN docs for example. Also, the value is there twice, one with the correct amount of "0", one with a missing "0".
=> Docs: Fix DE translation gwei value

src/components/ButtonLink.tsx
Due to [recent DS implementation changes on the Button component](https://github.com/ethereum/ethereum-org-website/pull/10315), we need to override the underlined text decoration inherited from the Link component.
Overrides the link text decoration styles.
Before (hovered):
Now (hovered):
=> Fix `ButtonLink` styles

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Updated `ethereum-org-website/src/content/developers/docs/nodes-and-clients/nodes-as-a-service
/index.md` with information pertaining to Lava Network.
N/A
=> Add Lava Network entry to Nodes-as-a-Service list

src/components/PageHero.tsx
Was messing around with @nloureiro in GH grooming and we made some small improvements to the PageHero's spacing on smaller screens, further changes will improve it on the DS implementation but this is a nice quick win.
None
=> Adjust hero spacing on smaller screens

src/components/Search/utils.ts
Fixes text color for highlighted search results where the semantic token used was not up-to-date, resulting in a typo.
=> fix(Search/utils): update semantic syntax for highlighted search results

src/content/developers/docs/gas/index.md
Replaces "miner" with "validator" in several places on gas page.
Fixes #10430 (although note that the copy identified in the issue refers to the London upgrade which happened before The Merge, so miner is correct. Added a note about pow->pos beneath instead of swapping terms.
=> replace "miner" with "validator" on gas page

src/content/developers/docs/smart-contracts/verifying/index.md
fix broken for [this](https://ethereum.org/en/developers/docs/smart-contracts/verifying/) page
=> Remove broken link in verifying smart contracts developer docs

src/content/community/code-of-conduct/index.md, src/content/community/get-involved/index.md, src/content/contributing/index.md
A new code of conduct for the ethereum.org project spaces was workshoppped by volunteers from the ethereum.org discord. This PR adds it to the website under `/community`.
=> + community code of conduct

src/content/developers/docs/transactions/index.md
This filed is called `input` when you fetch a transaction using `geth console`.  like this one:
```js
> eth.getTransaction("0xd0dcbe007569fcfa1902dae0ab8b4e078efe42e231786312289b1eee5590f6a1")
{
accessList: [],
blockHash: "0x3f9e857e0aeb6df6c82164d8e9d8dc6ce06e81670906d669271ef874d7e57d1d",
blockNumber: 14330693,
chainId: "0x1",
from: "0xbae7ebe87fc708426a193f49c4829cdc6221ac84",
gas: 84000,
gasPrice: 30475312837,
hash: "0xd0dcbe007569fcfa1902dae0ab8b4e078efe42e231786312289b1eee5590f6a1",
input: "0xa9059cbb0000000000000000000000004f6742badb049791cd9a37ea913f2bac38d01279000000000000000000000000000000000000000000000000000000003b0559f4",
maxFeePerGas: 39390000000,
maxPriorityFeePerGas: 100000000,
nonce: 0,
r: "0xfd53e1027288b8e1f5697ca42551c7c86511b3c8f5b08151da1879af661beb0d",
s: …
```
=> Update transactions developer doc

src/intl/en/page-index.json
The phrase 'bank run' appears on the homepage. Even though of form noun-verb, it could be misinterpreted as noun-noun with the negative connotations of a [bank run](https://en.wikipedia.org/wiki/Bank_run).
Replace 'You can build a bank run by logic you've programmed.' with 'You can build a bank powered by logic you've programmed.'
#10369
=> Fix possible negative connotation of 'bank run' in code example

src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
* Adds small grammar corrections
* Adds some additional context for the Merkle root concept
* Makes a small change around word choice. Using integrity instead of authentication to explain the integrity guarantee provided by Merkle tree representation of data.
=> Update PMT Grammar and Explanation

src/content/developers/docs/apis/json-rpc/index.md
=> fix formatting in eth_getTransaction output bullets

src/scripts/markdownChecker.ts
- Creates a warning if a file in the /translations/ path has an invalid frontmatter link (based on hardcoded relative path, should not be two or three levels)
#10402
=> Add check for broken frontmatter images in translated files to markdown checker

src/content/developers/tutorials/hello-world-smart-contract/index.md
Hello Ethereum team, I'm Opemipo and I work at Alchemy and because of the updating Goerli deprecation, you are adding Sepolia b/c we want to make sure that developers reading these tutorials (originally uploaded by Alchemy) have the latest, best tools to build with.
I added a Deprecation notice about Goerli and suggested Sepolia as the most recommended test network to work with. I did not change Goerli in the body of the guide, it's up to the developers to do that since I made a recommendation about using Sepolia.
=> Update Hello World Smart Contract tutorial to use Sepoila testnet

src/components/Quiz/QuizWidget.tsx
Margins on QuizWidget were collapsing causing the widget to not have proper vertical margins. 
- Removes top margin on H2 title
- Add vertical margins to the flex container
- Fixes #10693
=> Adjust QuizWidget block margins [Fixes #10693]

package.json, yarn.lock
`yarn build` is failing in Windows envs.
Adds `cross-env` as a dev dep to support setting env vars in Windows computers.
=> Support setting env vars in win envs

src/pages/wallets/find-wallet.tsx
- Adds a disclaimer banner to the top of the find wallets page with the same text as at the bottom. 
Reason: Users typically do not reach the bottom of the page to know that these are not endorsements. This will make it more apparent.
=> add disclaimer banner to find wallets

src/components/Button/index.tsx
Fix issue where the `onClick` prop was being called in a custom handler of the local `Button` component and being passed straight to the render, thereby overriding the custom handler.
N/A
=> fix(Button): fix onClick prop call override

package.json, yarn.lock
This PR bumps `@chakra-ui/react` from `2.6.4` to `2.8.0`, and `@chakra-ui/storybook-addon` from `5.0.0` to `5.0.1`.
This introduces the following changes/additions to the project:
- Exposes the `SkipNavLink`/`SkipNavContent` component tandem for a theme-aware component to help with skip navigation (This can replace the custom [SkipLink component](https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/SkipLink.tsx) for uniformity with other potential usage)
- `v2.7.0` introduced a function for compiling colors in the theme config (seen in the default theme for `Input` which is being used in this project), but created an unexpected `theme undefined` error at buildtime. `2.8.0` removes this function and reverts back to a previous function that handling this compiling.
- …
=> chore(deps): bump Chakra packges to latest (v2.8.0)

src/pages/learn/index.tsx, src/templates/use-cases.tsx
Right now in the [learn hub](https://ethereum.org/en/learn/) page we have a very narrow sidebar:
This PR reuses the same layout components that we are using in the use-cases template to have a consistent layout between these pages. The use-cases template can be seen for example on the [nft page](https://ethereum.org/en/nft/).
=> Fix learn hub layout

package.json
Running into errors on Netlify trying to build lambda functions. Removed the cross-env change, and made a new set of scripts with those in it.
=> Hotfix: remove cross-env from build:lambda and build:10gb

src/content/developers/docs/standards/tokens/index.md, src/data/developer-docs-links.yaml, src/intl/en/page-developers-docs.json
Recently a pull request that adds ERC-223 to token standards documentation was merged https://github.com/ethereum/ethereum-org-website/pull/9651
This is a follow up update.
This will display the ERC-223 standard with a short description at the Advanced Standards tab for better visibility since https://ethereum.org/en/developers/docs/standards/tokens/erc-223/ is not accessible from the main navigation menu
=> Add ERC-223 to token standards list at the Advanced Standards tab

src/content/developers/docs/networks/index.md
rm sentence that says "testnet ETH has no value and there are no markets" because unfortunately there was Goerli ETH
for sale.
Also removes Rinkeby.
=> minor updates to networks page

src/components/TableOfContents/index.tsx
Although #9959 was created to properly export the `Item` type signature from `TableOfContents` to be used throughout the project, the following warning still appeared in the console:
```
warn ./src/components/TableOfContents/index.tsx
export 'Item' (reexported as 'Item') was not found in './utils' (possible exports: customIdRegEx, emojiRegEx, getCustomId, outerListProps, slugify, trimmedTitle)
```
The warning throws because Gatsby is assuming that `Item` is some object or function, when it is actually a type signature. Declaring the import with `import type` gives a safe-guard to the warning and any future similar cases.
N/A
=> fix(TableOfContents): declare import type with `Item`

src/@chakra-ui/gatsby-plugin/components/Button.ts
With only the solid variant of the Button theme updates with the new DS, a border color still renders via the default `currentColor`, which does not match the background color. Make color `transparent` instead.
N/A
=> fix(theme/Button): remove border color for solid variant

src/content/contributing/translation-program/content-buckets/index.md
Broken links and misspellings in "Content buckets" page
=> Broken links and misspellings in "Content buckets" page

src/content/developers/docs/data-structures-and-encoding/web3-secret-storage/index.md
In Web3 Secret Storage format specification document, test vector and it's derived value with scrypt was invalid.
["n" parameter of Scrypt cannot be less than 2^(128 * r / 8)](https://datatracker.ietf.org/doc/html/rfc7914#section-6), which is 2^16, and in this test vector, we have n of 2^19. 
It seems "r" and "p" has been swapped by mistake. so I recalculated new Web3 Secret Storage based on correct Scrypt parameters.
I generated new Web3 Secret Storage with right Scrypt parameters, using provided private key and password. also, updated derived value in process of decryption, such as derived key from KDF (in this case, scrypt.), MAC body, cipher key. 
This resolves #10405.
=> Fix Wrong Scrypt Parameter In Web3 Secret Storage Test Vector.

src/content/governance/index.md
Removes a fact that isn't particularly relevant to the topic, and adds context for the "More on EIPs" link that follows it.
CC @dtedesco1 
*N.A.*
=> Contextualize the "More on EIPs" link in the Governance page

src/content/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/fr/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/id/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/it/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/ja/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/ro/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/tr/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/translations/zh/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/pages-conditional/dapps.tsx, src/pages-conditional/eth.tsx
Sablier can now be found at [sablier.com](https://sablier.com).
[Twitter reference](https://twitter.com/Sablier/status/1679567131569184768).
=> refactor: update sablier domain name

src/content/developers/docs/apis/backend/index.md
Tokenview Blockchain APIs provides on-chain data for Ethereum.  Using Tokenview Blockchain APIs to send transaction, to deploy contract is very easily conducted too.
=> Add Tokenview ETH Archive API to apis-backend-index

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Hi There,
Tokenview support Ethereum RPC Node service, and the Tokenview ETH Node Service is built on the strong load-balanced node cluster, which can provide high-performance and high-concurrency processing requests.  I take this opportunity to bring to your attention that Tokenview has been one of the most popular web3 platforms for millions of users.
=> Add Tokenview ETH Node Service to nodes-as-a-service

yarn.lock
Due to recent updates on `package.json` when you run `yarn install` there is a diff in the `yarn.lock` file.
Re run `yarn install` and add `yarn.lock` differences.
=> Re-generate yarn.lock
