ethereum/ethereum-org-website

docs/learn/index.md
Removed the link to the 2.0 wiki roadmap. Most of these phases are non-existent.
=> remove wiki eth2.0 roadmap as it is outdated

docs/build/index.md
There is a section labeled `UX/UX` but I think it might have been supposed to be `UI/UX`. Not sure if this is a typo.
=> Update possible typo `UX/UX` to `UI/UX`

docs/.vuepress/config.js
Addresses #6 
Adds basic OGP / Twitter metadata. Uses the image on the front page, which maybe doesn't read the best.
Probably should install this plugin and configure defaults https://github.com/lorisleiva/vuepress-plugin-seo
=> First pass at adding social headers

docs/build/index.md
In the *Build* page I see information on how to testnet and how to run your own node, but it doesn't mention any tool on how to run a local node for development and testing, and it's not obvious to a newcomer that they can run `geth` or `parity` in *single player mode* to just practice interacting with a real node.
I've added a link to [ethnode](https://github.com/vrde/ethnode), a simple tool to locally run **Geth** or **Parity** in development mode.
=> "Build" page doesn't list tools to run a dev client

docs/build/index.md
Added Whiteblock Genesis (open source software) under testing tools section.
=> Whiteblock Genesis Under Testing Tools

docs/build/index.md
fixes #78 
- Broken links fixed
- Removed Typo (Github -> Gitter)
- Vyper documentation link now redirect to latest version doc
=> broken links fixed

README.md, docs/.vuepress/config.js, docs/.vuepress/theme/components/Hero.vue, docs/beginners/index.md, docs/developers/index.md, docs/index.md, docs/learn/index.md
I've changed all the links and text manually, so there shouldn't be any unintended renaming/replacing. Doesn't seem to break anything either.
=> Replaced "Build" with "Developers" (fixes #72)

docs/.vuepress/theme/components/Footer.vue
Just a small (but quite common) typo 😄
=> Fix typo in footer (Github → GitHub)

docs/developers/index.md
The new resource was freshly created this week while most if not all of other resources are outdated.
@chriseth can you merge this?
=> Added reference to a page collecting numerous security recommendations

docs/developers/index.md
Fixes build file conflict in #70
=> Virgil patch 3

docs/learn/index.md
This will eventually be `eth.wiki`, but for now `ethereum.wiki` is preferred over the github (afaik).
=> Updated URL

docs/learn/index.md
Part of fix for https://github.com/ethereum/ethereum-org-website/issues/73
I did not remove the term in the opening paragraph where the text states "This page includes technical **and** non-technical articles". In that context, it is providing the reader useful information about the scope of information on this page and is not using the term in in a diminutive fashion.
=> Updating to remove "non-technical"

docs/developers/index.md
I especially want Manticore added.
=> Added Manticore and Oyente.

docs/use/index.md
As of July 11, the Veil product is being sunsetted - removing from list of "recommended" applications for new users. 
Reference: https://twitter.com/veil/status/1149443647965814784.
=> Remove Veil

docs/developers/index.md
Updated links -that changed after a rebranding- to OpenZeppelin products and blogposts.
=> Updated links

docs/developers/index.md
Adding back a link to Swarm, which seems to have been removed at some point.
=> Adding Swarm link

docs/developers/index.md
As the title suggests, fixed **platfrom** to **platform** and added alerting to the list of features.
=> Fixed typo for Tenderly in developers section.

docs/use/index.md
Which renders incorrectly as HTML
=> Fix miss-formatted markdown link

docs/developers/index.md
Link to the Github repo for web3-wrapper was returning status 404, updated to new link.
=> Fix broken link to web3-wrapper package repo

docs/developers/index.md
A growing number of projects (such as ENS, Moloch, Melon) is using The Graph in production. We feel it is a tool worth for any Ethereum contract/dApp developer to have in their toolbox. We'd love to have it included in the developer tools section.
Let me know if anything could be improved and I'll happily make changes.
=> Add The Graph to the developer tools section

docs/java/index.md
For technical reasons, Besu should at least contain one mention of Hyperledger Besu in it.
=> Quick fix, change "Besu" to "Hyperledger Besu"

docs/enterprise/index.md, docs/index.md, docs/learn/index.md
There are 3 main changes proposed in this PR:
- added an `/enterprise` page path with information on enterprise ethereum
- added a enterprise intro-block section to the homepage with links to /enterprise resources
- added an "Enterprise Ethereum" h2+section on the `/learn` page with a link to the /enterprise page
I decided not to change the styling on the homepage intro-section (ie. to center align the block), but this could be done if needed.
=> /enterprise url with enterprise ethereum information and resources

docs/.vuepress/theme/Layout.vue
Only display artwork announcement on homepage
https://github.com/ethereum/ethereum-org-website/issues/186
Locally
=> Only display artwork announcement on homepage [Fixes #186]

docs/developers/index.md, docs/python/index.md
Continuation of https://github.com/ethereum/ethereum-org-website/pull/246
I've added a /python path with resources to python-ethereum related information.
- updated the link to the /python page from the /developers page
- added py-eth articles, divided in 3 categories, beginner, intermediate and advanced use patterns
- list of projects and tools tht use python on eth today
- community links to gitters of some of those projects
https://github.com/ethereum/ethereum-org-website/issues/223
=> Added python landing page + link to it

docs/.vuepress/theme/components/DropdownLink.vue, docs/.vuepress/theme/components/SearchBox.vue, docs/.vuepress/theme/styles/config.styl
Removed the white background setting for larger than small screens, set to gray.
https://github.com/ethereum/ethereum-org-website/issues/252
Locally
Dark background looked a bit too dark:
So I went with the `$textColorDark = rgb(180,180,180)`:
No change needed on mobile:
=> Update dark mode menu color [Fixes #252]

docs/.vuepress/theme/components/SidebarLink.vue, docs/.vuepress/theme/index.js, package.json, yarn.lock
Boldens, colors & sets right boarder on scrollbar section to illuminate progress on the page.
No issue, found it while researching Vuepress plugins.
Locally
=> Add active state styles for sidebars

docs/.vuepress/theme/styles/config.styl, docs/.vuepress/theme/styles/theme.styl
Respects browsers' default font size as the body font size. In practice, this typically results in body font of 16px vs 14px.
https://github.com/ethereum/ethereum-org-website/issues/290
Now
Before
=> Update body font-size to 1rem [Fixes #290]

.github/workflows/label.yml
https://github.com/ethereum/ethereum-org-website/issues/344
=> Avoid running GH labeler on forks [Fixes #344]

docs/.vuepress/config.js, docs/.vuepress/theme/Layout.vue, docs/.vuepress/theme/components/Footer.vue, package.json, yarn.lock
This PR adds the current updated page date to the Layout and  the last updated page date to the Footer.
https://github.com/ethereum/ethereum-org-website/issues/49
=> Add "Last Updated" To The Website

docs/.vuepress/theme/Layout.vue
- Smooth scroll to anchor links.
- The smooth scroll is only honored if the URL contains a `#` symbol using 'window.location.hash' 'method.
- a11y compliant, for users who are prone to motion sickness. (can be disabled by OS, most browsers honor this setting, eg. on android the user can disable animations)
Fixes #294
=> Scroll to anchor links [Fixes: #294]

docs/golang/index.md
Added language-specific page for Golangfollowing https://ethereum.org/python/ page as a template
Resolves #265
=> Added language specific page for Golang [resolves #265]

docs/developers/index.md, docs/javascript/index.md
Adds [Ethereum Grid](https://grid.ethereum.org) to the list of developer tools and JavaScript tools.
Addresses #558. One remaining question about the `build` page.
=> Add Ethereum Grid to tools [Closes #558]

docs/.vuepress/components/HomePage.vue, docs/.vuepress/theme/utils/translations.js
Fixes the link (but not the translations of "Learn more")
#612
=> Fix homepage "Learn more" link for translations

yarn.lock
Bumped up version for `serialize-javascript` to 2.1.1
This prevents a moderate severity XSS cross-scripting attack vector, you can read more [here](https://github.com/advisories/GHSA-h9rv-jmmf-4pgx)
=> bump serialize dependency

docs/rust/index.md
Because [eth-utils](https://github.com/ethereum/eth-utils/) is not a Rust project but a Python project, I would suggest to remove it from the Rust projects list.
=> Remove eth-utils from the Rust projects list

docs/developers/index.md
QuikNode.io has been an active member of the Ethereum infrastructure group since 2017.
Its dedicated to blockchain education and supporting the Ethereum ecosystem.
More information on https://blog.quiknode.io and https://twitter.com/quiknode
=> Add QuikNode.io to Backend APIs in Developers

docs/cookie-policy/index.md
Update cookie policy to reflect usage of Matomo instead of Google Analytics.
Delete:
`Google Analytics | _ga | Used to distinguish users. Enables us to identify which pages are popular, estimate our audience size and usage pattern, and better understand how the web site is used.
-- | -- | --
Google Analytics GID | _gid | Used to distinguish users. Enables us to identify which pages are popular, estimate our audience size and usage pattern, and better understand how the web site is used.
Google Analytics Throttle | _gat | Used to throttle request rate. This cookie does not store any user information. It is used by Google limit the number of requests that have to be made to doubleclick.net (which will be zero in our case because we do not use any ads on our site).`
Add:
`Matomo | _pk_id | …
=> Update cookie policy page for Matomo [Fixes: #566]

docs/.vuepress/theme/components/Footer.vue, yarn.lock
Adds link to the official Ethereum YouTube to the footer.
#664
=> Add Ethereum Foundation YouTube to Footer

docs/developers/index.md
I've added the links for the Solidity & Vyper cheat sheet at [http://reference.auditless.com/cheatsheet](http://reference.auditless.com/cheatsheet). This cheat sheet is open source and already has contributions from Solidity/Vyper devs/core team.
I'm not happy with the placement since there is no joint section for Solidity/Vyper so proposing a separate link in both (but it's one side-by-side cheat sheet in reality).
=> Update index.md to include Solidity & Vyper cheat sheet

docs/developers/index.md, docs/javascript/index.md
Added links to eattheblocks tutorials in developers ressources
=> Add eattheblocks tutorials

docs/community/index.md
Added ETHDEVNL, a meetup group in the Netherlands, to the overview.
=> Add Netherlands Meetup group

docs/.vuepress/components/__tests__/__snapshots__/AssetItem.spec.js.snap, docs/.vuepress/components/__tests__/__snapshots__/DefaultList.spec.js.snap, docs/.vuepress/components/__tests__/__snapshots__/HomePage.spec.js.snap, docs/.vuepress/components/__tests__/__snapshots__/LanguagesPage.spec.js.snap, docs/.vuepress/theme/components/DropdownLink.vue, docs/.vuepress/theme/components/Header.vue, docs/.vuepress/theme/components/__tests__/DropdownLink.spec.js, docs/.vuepress/theme/components/__tests__/__snapshots__/DropdownLink.spec.js.snap, docs/.vuepress/theme/components/__tests__/__snapshots__/Footer.spec.js.snap, docs/.vuepress/theme/components/__tests__/__snapshots__/Header.spec.js.snap, docs/.vuepress/theme/components/__tests__/__snapshots__/NavLinks.spec.js.snap
Apart from fixing the a11y issues with the dropdown items, I also fixed the view mode toggle from being skipped when tabbing through and made it usable with `@keydown.enter`.
There were various snapshot tests failing, which are unrelated to my changes, I updated them anyways. 
Fixes #735.
=> fix: Tabbing across links skips dropdown items (#735)

docs/developers/index.md
#317 didn't follow the convention to add new tools to the bottom of lists ([as we now instruct in the README](https://github.com/ethereum/ethereum-org-website#notes-on-specific-kinds-of-contributions))
Noticed this in #730 (thanks for surfacing). I'm making this update while we wait for additional feedback from the team on that PR in the meantime
=> Move Studio to bottom of IDE list

docs/.vuepress/components/BuildPage.vue, docs/.vuepress/components/Button.vue, docs/.vuepress/components/HomePage.vue, docs/.vuepress/theme/styles/dark.styl
A new `Button` component which can be called
This doesn't perfectly match the colors outlined in Figma, however that is because it is leveraging *current* darkmode colors.
- `isA` boolean, creates `<a href=...`
- `isRouter` boolean, creates `<router-link`
- `to` string, used inside `href` or `to` props,
- `secondary`, boolean, used to show secondary button style. Default is `primary`.
- `newTab`, boolean, creates `target="_blank" rel="noopener noreferrer"` when `isA` is used
Resolves #757
=> Added new buttons [fixes #757]

docs/.vuepress/components/BuildPage.vue, docs/.vuepress/theme/components/Footer.vue, docs/.vuepress/theme/components/Header.vue, docs/.vuepress/theme/components/NavLink.vue, docs/.vuepress/theme/styles/theme.styl
Added a glyph to external links. Resolves #759
All external links (anchor tags) now show a north east glyph by default, which can be disabled with a `hide-icon` class. It has been disabled in navigation, and in the build-page cards.
It is shown under the following conditions via CSS
```
:not([href^="https://ethereum.org"])
:not([href^="http://ethereum.org"])
:not([href^="/"])
:not([href^="#"])
:not(.hide-icon)
```
It should be noted that this doesn't enforce complete parity with the Figma file (underlines), as the existing lists may become unwieldy.
#759
=> Link styling

docs/.vuepress/theme/styles/responsive.styl
This fixes the padding on large screens. Previously it was `vw` based with no max
=> fixed wrapper padding

docs/.vuepress/theme/styles/theme.styl
Removed `:target` css for anchor tags. I'm not 100% sure why it wasn't working, but this update is
Tested in:
- Chrome 80.0.3987.132
- Safari 13.0.5
- Brave 1.4.96
- iOS 13.0 Safari
Changed `:target:before` to a combination of padding & margin values applied to `:before`. Also moved this inside `.content__default`
#832
=> fix anchor scroll position [fixes #832]

docs/.vuepress/theme/components/Sidebar.vue, docs/.vuepress/theme/components/SidebarGroup.vue, docs/.vuepress/theme/components/SidebarLink.vue
Updated outline styles
This is a css update, altering the styles of the sidebar to match the styles in the Figma Style Guide.
=> updated outline styline styling [fixes #766]

docs/.vuepress/components/LanguagesPage.vue
Added hide icon class to language card
The nested `a` tags with external hrefs were causing two external link icons to be displayed. The `hide-icon` class has been added to the wrapper to hide the 2nd.
#844
=> Hide 2nd external link icon [fixes 844]

docs/.vuepress/components/ListCard.vue, docs/.vuepress/theme/components/Footer.vue, docs/.vuepress/theme/components/NavDropdown.vue, docs/.vuepress/theme/components/NavLinks.vue, docs/.vuepress/theme/components/SearchBox.vue, docs/.vuepress/theme/components/Sidebar.vue, docs/.vuepress/theme/components/SidebarGroup.vue, docs/.vuepress/theme/components/SidebarLink.vue, docs/.vuepress/theme/styles/lists.styl, docs/.vuepress/theme/styles/theme.styl, docs/.vuepress/theme/styles/utils.styl, docs/developers/index.md, docs/style-guide/index.md, docs/style-guide/lists/index.md
Added lists & documentation for them Implemented simple list on `/developers` page
Added multiple list variations based on the Figma Style Guide. These include lists with descriptions, and list cards in multiple layouts.
An array of objects should be passed to leverage the card format, and a class should be added to the standard lists to enable their modification.
=> Lists [fixes #767]

docs/.vuepress/components/CardInner.vue, docs/.vuepress/components/CardList.vue, docs/.vuepress/theme/components/NavDropdown.vue, docs/.vuepress/theme/components/SearchBox.vue
You can now use arrows to navigate through the menu drop downs and the search results
Added `up()` and `down()` functions to `SearchBox.vue` and `NavDropdown.vue` which ensure that keypresses & focus are only triggered when relevant.
=> added keyboard up + down arrow nav for navigation and search

docs/.vuepress/theme/components/NavLinks.vue
Adds `overflow: initial` to the nav wrapper above the $breakM breakpoint.
=> Disable overflow: scroll for desktop [fixes #857]

docs/.vuepress/theme/components/Footer.vue, docs/.vuepress/theme/styles/utils.styl
This adds icon fill classes and fixes the footer icon issue.
Added icon fill classes using text colors, across dark mode, including hover states.
=> Added icon fills [fixes #876]

docs/.vuepress/theme/styles/theme.styl
This disables the italicised external link icon
Resolves #852
=> Disable italicized external link icon [fixes #852]

docs/.vuepress/theme/styles/theme.styl
This removes the external link icon from netlify/relative links
adds the following `:not()` rules to the default anchor styles:
`:not([href^="."]):not([href^="https://deploy-preview-"]):not([href^="deploy-preview-"])`
Resolves #897
=> Remove external icon on netlify links [fixes #897]

docs/.vuepress/components/HomePage.vue, docs/.vuepress/theme/styles/lists.styl, docs/.vuepress/theme/styles/theme.styl
Prevents the highlight image from overflowing the container.
Constrained the image using `background-size: contain`
This works in the one location the highlight is being used. Also removed `.highlight-small`, which is redundant as a result of the change.
Resolves #895
=> List highlight adjustment [fixes #895]

docs/.vuepress/theme/styles/theme.styl
This adds `overflow-x: scroll` to `pre` tags, with some small style updates
Resolves #860
Desktop:
Mobile:
=> Fix pre tag overflow [fixes #860]

docs/.vuepress/theme/components/NavDropdown.vue, docs/.vuepress/theme/components/NavLinks.vue, docs/.vuepress/theme/components/Navigation.vue, docs/.vuepress/theme/components/SearchBox.vue, docs/.vuepress/theme/styles/utils.styl
This updates the way the nav is being handled, and simplifies things to a certain degree.
- Nav only opens on focus or on click
- Nav closes on a link click or enter keypress
- Title links have hover states
- Removes the `a` tag from nav dropdown wrappers to prevent event propagation issues
To prevent unwanted `focusin` `focusout` interference during a click event, `mouseup` is used for links. This allows the navigation event to fire.
`keydown.enter` is on the wrapper and toggles visibility when a child is focused & enter pressed. This closes the nav when navigating to a link.
=> Fix nav behaviour [fixes #868, fixes #908]

package.json, scripts/updateInternalLinks.js, yarn.lock
The script will change all the internal links as follows:
- If the link does not contain the language directory passed in, add it (/learn/ —> /__lang__/learn/)
- If the link does not have a trailing slash, add it (/__lang__/learn → /__lang__/learn/)
Example usage (in project root directory):
```
yarn update-internal-links de
```
~~There is room for improvement (in terms of string manipulation), but for now I think it can do the work.~~
__EDIT__ fixed a bug in last commit and improved string manipulation
It works like this:
- retrieve all the Markdown files
- find all occourrences of links and apply rules to them
- replace the old links with the new correct links in the file body
- write the file
#817
=> Script to update internal links of translated files

docs/community/index.md
Geneva DevChain is advanced blockchain community with main focus in Ethereum ecosystem. We have solid monthly meetups with hands on sessions.
=> Adding Geneva DevChain community to the meetup list

docs/community/index.md
Very small changes, just adding ETHGlobal as the org running HackMoney and a typo for "Catherders"
=> Add "(ETHGlobal)" and fix catherder typo

docs/.vuepress/config.js
Introducing the `vuepress-plugin-ipfs` appears to have created some havoc in our HTML builds when interacting with the Matomo tracking pixel.
Before adding it: 
`view-source:https://5e82199f98b4cc0007b721be--ethereumorg.netlify.app/`
```
<noscript><p><img src="//matomo.ethereum.org/piwik/matomo.php?idsite=4&amp;rec=1" style="border:0;" alt="" /></p></noscript>
```
After adding it:
`view-source:https://5e87b5c66f385800079a016c--ethereumorg.netlify.app/`
```
<noscript></noscript></head><body><p><img src="//matomo.ethereum.org/piwik/matomo.php?idsite=4&#x26;rec=1" style="border:0;" alt=""></p>
```
This resulted in the pixel (& other scripts) being injected into the `<body>` vs. the `<head>` of the HTML. Our reported site traffic basically doubled as a result (visits were being …
=> Remove Matomo tracking pixel

docs/developers/index.md
Reopening this PR :- https://github.com/ethereum/ethereum-org-website/pull/948 
Hi @samajammin & @CPSTL , Last week we have successfully launched our infrastructure on ethereum mainnet and have also added the projects building on top of biconomy section in our documentation.
Docs: https://docs.biconomy.io/examples/projects-building-on-biconomy
Mainnet launch relevant links :-
1). https://medium.com/biconomy/biconomy-beta-launch-d6ad979fffce
2). https://decrypt.co/27768/biconomy-brings-gasless-transactions-to-ethereum
I was bit occupied and about to update it here. Can you please proceed with review process now?
=> Biconomy added

docs/.vuepress/theme/Layout.vue, docs/.vuepress/theme/components/Footer.vue
Remove footer glyph
See [comment](https://github.com/ethereum/ethereum-org-website/pull/1017#issuecomment-627516981) in #1017
=> Remove footer glyph

docs/developers/index.md, docs/enterprise/index.md, docs/translations/ar/developers/index.md, docs/translations/bn/developers/index.md, docs/translations/de/developers/index.md, docs/translations/fa/developers/index.md, docs/translations/fr/developers/index.md, docs/translations/id/developers/index.md, docs/translations/ro/developers/index.md, docs/translations/se/developers/index.md, docs/translations/sk/developers/index.md, docs/translations/tr/developers/index.md
As the title suggests, Tenderly is moving to a new domain, and this PR reflects that change.
N / A
N / A
=> Changed the Tenderly domain from .dev to .co

docs/.vuepress/components/TranslationsBuild.vue, docs/translation-build/index.md, lambda/translation-build.js
As demonstrated in #1029, currently there's no way for volunteers to bulk download our translation files. The project must be "built" first & only admins can do that in the UI. The only other option is seemingly downloading the files in the UI one by one.
This creates a public page that anyone can hit to build our project files. This ensures we're using the latest versions of our translated content.
Any site translation issue, e.g. #1028
=> Add page to build translation files

docs/build/index.md
How to also update https://ethereum.org/build/
from:
Learn the basics of Ethereum with Ethereum Studio, our web-based IDE where you can create and test smart contracts, and build a front end for them.
to:
Learn the basics of Ethereum with the web-based Ethereum Studio where you can create and test smart contracts, and build a front end for them.
=> Sharpen description on Build page

docs/.vuepress/components/RandomList.vue
I moved the selectItems() call to beforeMount() instead of created(). This makes the links work the same in both dev and my test deployment. Seeing as RandomList is only reference on this page, this appears to fix the bug reported in [Fixes #1040] without affecting any other pages.
https://github.com/ethereum/ethereum-org-website/issues/1040
=> Fix links in RandomList component [Fixes #1040]

docs/community/index.md
Two commits, one adds the recently announced ETHOnline to the upcoming events in the community page, another removed past events that should no longer be in the upcoming events heading.
=> Remove old upcoming events, add ETHOnline to upcoming events

docs/community/index.md
Added a line [here](https://github.com/Solexplorer/ethereum-org-website/blob/dev/docs/community/index.md#upcoming-events-upcoming-events) to have the Gitcoin hackathon show up in the community website
#1077
=> Add protect privacy hackathon [Fixes #1077]

docs/.vuepress/components/BuildPage.vue, docs/.vuepress/components/HomePage.vue, docs/.vuepress/theme/components/AlgoliaSearchBox.vue, docs/.vuepress/theme/components/NavLinks.vue, docs/.vuepress/theme/utils/translations.js
Created a mixin which defines `translateString` to dedup the definition for the same in BuildPage, HomePage, AlgoliaSearchBox, NavLinks components and enables easy sharing of the method. 
Also enables to remove imports of the `translate` method as the above-defined method from the mixin can be used for the same.
Fixes #979 
https://github.com/ethereum/ethereum-org-website/issues/979
=> Add mixin to dedup definition of translateString [Fixes #979]

README.md
Title and bodycopy typos fixed in the translations section of the `README`.
Corrected some typos I spotted when reviewing the `README`
#1100
=> Correction of typos in translations readme [Fixes #1100]

docs/community/index.md
DAOS got added to the Online Communities section of the Community page
DAOs are a very Ethereum-esque way of discovering and interacting with the Ethereum community. In order to help people find them, a list of DAOs was added to the Online Communities section, using websites and Twitter handles.
=> Added DAOs to the Online Communties section

docs/.vuepress/theme/utils/translations.js
Bug was identified by @sorumfactory so have amended the expression.
_ I received a message from one of our  translators that the Chinese Traditional 「中國傳統的」 on the language support page is not correctly written. The common expressions are such as 「傳統中文」or「正體中文」. It's a good catch :open_mouth: 
Would you please change the 中國傳統的 to 傳統中文?_
N/A
Before:
After:
=> Corrected chinese traditional characters

src/components/Footer.js, src/components/Link.js, src/components/MeetupList.js
Fixed styling issues on the community meet-up card list to restore it to it's pre-Gatsby look-and-feel.
#1149
=> Fixed #1149

src/components/RandomAppList.js
Changing the logic of random numbers for correction or random reproduction
#1040
https://share.getcloudapp.com/2Nu5prrO
=> chore: fixed list shuffles on RandomAppList 

src/components/Search/index.js
Exclude empty search queries from Algolia's analytics
#1153
=> Exclude empty search queries from analytics [Fixes #1153]

.github/workflows/docsearchConfig.json
Following our conversation from DocSearch support, this PR should solve the issue you are struggling with when attempting to extract textual information from meta tags. By default, the crawler extract textual informations from HTML node [via the `textContent` method](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Differences_from_innerHTML). Since `<meta/>` tags do not wrap any textual informations, the crawler must know that the coveted text is in the `content` attribute of the node.
N/A
N/A
=> fix(search): use correct selector for meta tags

src/components/Link.js, src/utils/matomo.js
- Noticed certain outlinks are not being tracked correctly (e.g. Exchange clicks on /get-eth/), likely because those links aren't rendered on page load.
- Adds function for custom events & add to external link clicks
None
=> Add event tracking to external link clicks

src/pages/languages.js
The link to our translation discord was mistakenly a link to the fillipino translation page on Crowdin. This PR inserts the correct link instead.
=> Fix wrong link to site translation discord

src/content/community/index.md
I added the upcoming EDCON2020 event to the "Upcoming Events" section on the Community page.
=> Adding EDCON2020 to upcoming events

src/content/developers/index.md
Added a link to Alchemy's documentation. 
##https://github.com/ethereum/ethereum-org-website/issues/1306
=> Adding link to Alchemy's documentation for developer resources

src/pages/index.js
Add margin to Page to prevent Nav from overlapping hero image.
#1299
=> Prevent Nav overlap on Page [Fixes #1299]

src/content/developers/index.md, src/content/enterprise/index.md
This is a small change that adds references to the Epirus Platform by Web3 Labs to the Enterprise and Developer Resources page.
Epirus enhances the developer experience by simplifying the project creation and deployment process to live networks with Web3j. It also provides a widely used and battle tested blockchain expolorer.
#1294 
N/A
=> Add Epirus to Ethereum for Enterprise and Developer Resources pages

src/content/eth2/the-beacon-chain/index.md
There was a typo in explanation of staking ETH.
=> Fixed typo in beacon chain content

src/content/developers/docs/smart-contracts/languages/index.md
Updated the example since the older one uses syntax that is deprecated. The example is the same as the one here https://solidity.readthedocs.io/en/v0.7.1/introduction-to-smart-contracts.html#subcurrency-example
=> Update solidity example

gatsby-config.js
Hard-coded Github OAuth token (with [no scope](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes)) for read-only uses. This prevents the project from failing when contributors run it locally or Netlify builds when they submit PRs.
#1472
=> Add read-only GH token [Fixes #1472]

src/components/Search/index.js
Prevent sending search requests to Algolia if the query is empty.
#1505
=> Mock search requests if query is empty [Fixes #1505]

gatsby-config.js, package.json, src/templates/docs.js, src/templates/static.js, src/templates/tutorial.js, yarn.lock
This plugin is no longer necessary since we replace all `a` tags with our internal `<Link />` component.
None
=> Remove gatsby-plugin-catch-links

gatsby-node.js, src/components/Nav/index.js
Only display the SubNav component if contentVersion of the language is > 1.1
#1543
=> Display SubNav for contentVersion > 1.1 [Fixes #1543]

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
Quotation marks have been added around the package name in the installation instructions for the `A Python developer's introduction to Ethereum, part 1` tutorial.  This was previously not working in .zsh.
https://github.com/ethereum/ethereum-org-website/issues/1526
=> Fixed installation instructions in tutorial so it now works in .zsh [Fixes #1526]

src/components/SideNav.js, src/content/developers/docs/standards/index.md, src/content/developers/docs/standards/tokens/erc-20/index.md, src/content/developers/docs/standards/tokens/erc-721/index.md, src/content/developers/docs/standards/tokens/index.md
Fixing links to the `ERC-721` page and also using the same pattern of the `ERC-20`.
@samajammin the `ERC-721` page is still not a left menu item, does this PR fix that (the proper links on the "parent" pages)?
=> [ERC-20|721] Fixing links and using same pattern for both pages

src/content/developers/docs/smart-contracts/languages/index.md
Updates the smart contract languages page in the docs section. 
Overview of changes and rationale: 
-  Rewording the intro from "huge advantage" to "great aspect" which I personally find less opinionated (but feel free to change).
- Fixing some capitalisation and punctuation issues for consistency.
- Updating Solidity link for "Solidity by Example" (the chosen link did not support Solidity v.0.7.).
- Biggest changes in the "How to choose" section: I don't think the prior chosen table view makes sense since the elements of the table did not really compare to each other. Hence, I rewrote it to consist of two lists. We can further work on these two lists; happy to adjust the content further there. Btw, Solidity is not a "JavaScript-like language" :) 
And as I outlined before: I don't think …
=> Update smart contract languages page

src/components/MeetupList.js
The previous non-Ethereum link (replaced) was the product of a distinct shift away from the local Ethereum community.
=> Added Sydney's most active Ethereum dev community

netlify.toml
Redirect request URLs to add the English directory (`/en/`) if the requested URL doesn't exist.
#1374
=> Add fallback redirect to /en/ [Fixes #1374]

src/content/whitepaper/index.md
Hello,
I think there is a typo under Further Applications section of the white paper:
_2. Crop insurance. One can easily make a financial derivatives
contract **but**  using a data feed of the weather instead of any price
index. If a farmer in Iowa purchases a derivative that pays out_
should be **by**
=> fixed typo?

src/content/developers/docs/transactions/index.md
In the transactions page, the external link to external json-rpc document is incorrect. The rendered URL is '/https://eth.wiki/json-rpc/API' which navigates users to Page Not Found.
Remove leading typo '/' in the url
=> change json-rpc to be the correct external link

src/content/developers/docs/transactions/index.md
a signature for a transaction should be sender's PRIVATE key not PUBLIC key
=> change 'public key' to 'private key'

src/components/Nav/Mobile.js, src/components/Nav/index.js
Fixes layout of hamburger menu icon and Ethereum wire logo to lay vertically centered along the same horizontal axis as one another. 'X' close button on menu adjusted to align with hamburger icon for improved UX on mobile.
- Adjusted horizontal padding of `StyledNav` from `2rem` to `1.5rem`, which lays the hamburger menu with an even distribution between top/right/bottom container edges. 
- Added `align-items: center` to styling of `NavContent`, correcting vertical alignment of hamburger icon, and the `Link` component containing `HomeLogo` (note: `Link` is now centered vertically within `NavContent` but this leaves a small gap below the `HomeLogo` image component it holds due to default inline styling, corrected next).
- Added `vertical-align: bottom` to styling of `HomeLogo` to prevent …
=> Mobile nav bar layout adjustment [Fixes #1605]

src/components/PageMetadata.js, src/content/developers/tutorials/write-hello-world-contract/index.md, src/templates/tutorial.js
This update should eliminate any negative SEO consequences of hosting community tutorials on ethereum.org.
If a tutorial contains a `sourceUrl` frontmatter field (meaning it was originally published on a different site), we set the canonical tag to the `sourceUrl`.
More on canonical tags & duplicate content:
- https://moz.com/learn/seo/canonicalization
- https://support.google.com/webmasters/answer/139066?hl=en
None
=> Add canonical tag to tutorials that have sourceUrl

src/components/Nav/Mobile.js
Reversed nesting order of `<SectionItem>` (now child) and `<NavLink>` (now parent) within mobile menu links list in order to make entire `<SectionItem>` component tappable with proper subsequent routing. The `key` property was kept on parent component (now `<NavLink>`) to allow proper list indexing.
=> Mobile menu links: Tappable region fix [Fixes #1621]

src/components/Emoji.js
Per error in issue #1667, margin prop names for `<StyledEmoji>` made all lowercase. Continues to pass props appropriately, and eliminates console error messages. Emojis being used behaving appropriately.
=> Adjusted StyledEmoji margin prop names to lowercase [Fixes #1667]

src/content/developers/docs/gas/index.md
This PR adds a link to [Etherscan Gas Tracker](https://etherscan.io/gastracker) on the "Gas and fees" doc.
The rationale adding this is that during times of high congestion, I've noticed that [ETH Gas Station](https://ethgasstation.info)'s numbers were unreliable whereas Etherscan's were on point. Not only do I find this resource to be more accurate, I think it is quite user-friendly as well.
=> Added Link to Etherscan Gas Tracker

src/components/SideNavMobile.js, src/templates/docs.js
Gap was formed from merge commit 3858a39 after nav bar alignment reduced height by 7px. This adjusts the position of the fixed navbar and document content to compensate for previous changes.
Note: docs content `margin-top: 8.5rem` was reduced by 0.5rem (8px) off by 1px which I felt was negligible for the sake of `rem` readability, and still leaves no gap.
=> Adjusts mobile docs navbar and content position [Fixes #1677]

src/content/developers/docs/nodes-and-clients/index.md
This PR adds a link to DAppNode in the "Nodes and clients" doc.
I currently run all my nodes through the DAppNode OS and it's awesome. A great option if you want to run your node on a separate, dedicated machine.
=> Added Link to DAppNode to Nodes doc

src/content/developers/docs/transactions/index.md
In the simple transaction example, there appears to be a unit conversion error between GWEI <-> ETH.
```
21000 GAS * 200 GWEI/GAS = 4200000 GWEI
4200000 GWEI = 4200000000000000 WEI = 0.0042 ETH
```
=> Fix GWEI <-> ETH Unit Conversion

src/content/developers/docs/nodes-and-clients/index.md
Add recently-written, peer-audited tutorials for running both Geth and OpenEthereum (fka. Parity) nodes.
Add QuikNode.io to node provider list.
(previously https://github.com/ethereum/ethereum-org-website/pull/1669)
=> add geth & oe tutorials, add quiknode provider (2)

src/templates/static.js
Placed `<TableOfContents>` component within static template, styled for proper placement and functioning. Placed in same region as `docs.js` at the top of the content. Does not display on desktop, and desktop ToC does not display on mobile. (Links highlight after activated)
#1705
=> Added mobile ToC component to static template [Fixed #1705]

src/components/SideNav.js
Added `border-right: 1px solid ${(props) => props.theme.colors.border};` to `<Nav>` component within `SideNav.js`.
#1710
=> Added border-right to docs SideNav [Fixes #1710]

src/components/SharedStyledComponents.js, src/templates/docs.js, src/templates/static.js, src/templates/tutorial.js
Currently the `<li>` list items have no explicit styling and default to a color of `.text`, while body paragraph text is styled with a shaded text color, `.text300`. 
This adds a `styled.li` component `ListItem` to `SharedStyledComponents.js` with `color: ${(props) => props.theme.colors.text300};`
Styles list items with `.text300` color shading to match body paragraph text (instead of default `.text`).
Passed to `docs.js`, `static.js` and `tutorial.js` so all list items get styled appropriately. 
(@samajammin @ryancreatescopy sorry for extra PR, I didn't know how to add to #1715 with my own branch changes... feel free to ignore, but wanted to offer this as an alternative approach which I feel is more declarative, and in line with existing theming)
#1714
=> Adds list item styling [alternative fix to #1714]

src/components/SideNav.js, src/components/TableOfContents.js, src/pages/eth2/deposit-contract.js
Tweak `top` of sticky items to account for Nav.
Not sure what caused it but current overlap is too close:
None
=> Increase top to account for Nav

.github/ISSUE_TEMPLATE/suggest_glossary_term.md, src/content/contributing/adding-glossary-terms/index.md, src/content/contributing/index.md, src/content/glossary/index.md
- Adds glossary to list of ways to contribute on `/en/contributing/` with link to `/en/conributing/adding-glossary-terms/` where a new `.md` file provides layout and expectations for new glossary terms
- Link provided to GitHub, where new issue template `suggest_glossary_term.md` has been created and is referenced, to help organize future submissions
- Updated bottom of glossary page with 'Sources' and 'Contribute' section headers, with link to new contribution page
#1718 
Does not "fix" this issue, as it will be ongoing with future glossary term additions, but this aims to help clarify and streamline submission process for future contributors by giving clear guidelines, directions, and templating.
=> Adds glossary contribution page [Helps with #1718]

src/content/developers/docs/evm/index.md
EVMC is not an EVM implementation itself, it's an interface between EVM implementations and EVM users.
evmone is such EVM implementation.
=> Replace EVMC with evmone in EVM implementations list

src/content/developers/docs/smart-contracts/languages/index.md
adds link to the recently launched Solidity language portal (soliditylang.org). :)
=> Adding Solidity Language Portal to Solidity Links

src/content/eth2/docking/index.md, src/content/eth2/shard-chains/index.md, src/pages/eth2/staking.js, src/pages/eth2/vision.js, src/templates/eth2.js
Some fixes for some style bugs: 
#1768, #1772 and #1773
=> Eth2 style bugs

src/pages/eth2/get-involved/index.js, src/pages/eth2/index.js
When navigating to `/en/eth2/get-involved/` a console warning generates as a result of a `<ul>` tag being nested within a `<p>` tag. This is in `/pages/eth2/get-involved/index.js`. The `<p>` tag here is not needed and has been removed, eliminating the warning. 
Also added commit to update `marginLeft` prop for `<Emoji>` component to use new `ml` format
=> Eth2 bug fixes (nesting/margin)

src/components/Link.js
This is one possible fix to issue #1788. 
I may be missing something but when I remove the `color: ${(props) => props.theme.colors.primary}` styling that is placed on all external links, this allows all links to keep the color styling from its parent. I tried a few different pages, in light and dark mode, and they all seem to work just fine without that override. Not sure why we could want this, but again, still new so I may be missing something deeper.
=> Removes color styling override of external links [Fixes #1788]

src/content/about/index.md
`/about/` page missing custom header IDs causing console warnings. Added them, resolving warnings.
=> About page bug fix (Missing custom ID on header)

src/pages/eth2/staking.js
Fixed a typo that broke a link
At the staking page there was a link pointing to the "beaon-chain" instead of "beacon-chain"
issue at:
https://ethereum.org/en/eth2/staking/
steps to replicate:
At the "How much are you willing to stake?" section click "Less than 32 ETH"
Click at the "Beacon Chain upgrade" link
Get 404 error
=> Fixed broken link at staking page

src/content/eth2/beacon-chain/index.md, src/content/eth2/docking/index.md, src/content/eth2/shard-chains/index.md, src/pages/eth2/index.js, src/templates/eth2.js
Due to the extent of communication around phases through eth2 content in the community, we thought it best to at least reference the phases in our content, despite positioning it around outcomes/results rather than phases of work.
Have added an FAQ that explains relationship between upgrades and phases. Have added an additional summary point to eah upgrade page that references what users might know it as in terms of phases.
We might also include references to phases in an interactive Eth2 diagram being worked on separately from this PR.
=> Added reference to eth2 phases

src/content/developers/docs/consensus-mechanisms/pos/index.md
Correction for "The beacon chain receives state information from shards and makes it available for other shards so that the network an stay in sync." to "The beacon chain receives state information from shards and makes it available for other shards so that the network can stay in sync."
=> Correction for typo "an" to "can"

src/components/BannerNotification.js, src/components/Layout.js, src/templates/docs.js, src/templates/eth2.js
This should actually fix it this time 🤞 
- Update position to `relative` (vs `absolute`) to avoid complex Layout margin logic
- Add container divs (flex-direction: column) to wrap BannerNotification in Layout & Docs template
#1768
=> Refactor BannerNotification [Fixes #1768]

src/components/Nav/Mobile.js
Triggers menu close when tapping outside the menu area on larger mobile devices. Does not trigger by clicking between menu items.
https://share.getcloudapp.com/geuqnGRK
Short and sweet.
=> Mobile menu closes when tapping outside on larger devices [Fixes #1850]

gatsby-config.js, package.json, yarn.lock
Per Gatsby documentation, `gatsby-remark-images` does not support GIFs, and requires `gatsby-remark-copy-linked-files` plugin. This was added using `yarn add gatsby-remark-copy-linked-files` and updated in `gatsby-config.js` file.
=> Adds GIF support with gatsby-remark-copy-linked-files [Fixes #1845]

src/components/DocsNav.js
Make docs links full width on mobile
**Before:**
**After:**
None
=> Make docs links full width on mobile

src/content/developers/docs/dapps/index.md
I noticed that the new version of the site doesn't have the dapp tools list anymore (for example: https://github.com/ethereum/ethereum-org-website/blob/385a2334acd2410f1f02c31fced099b4c0fa7710/src/content/translations/de/developers/index.md#entwicklerwerkzeuge-developer-tools).
If this isn't the best place to put this, please let me know. 
Thanks yall!
=> Add tools to "Dapp Tools"

src/content/developers/docs/programming-languages/dot-net/index.md
The Nethereum project now has a Discord channel. See https://discord.gg/jQPrR58FxX
=> Add reference to Nethereum new Discord group

src/content/developers/tutorials/run-node-raspberry-pi/index.md
https://ethraspbian.com/downloads/ubuntu-20.04-preinstalled-server-arm64+raspi-eth1.img.zip
This file has a sha256 checksum of 7fa9370d13857dd6abcc8fde637c7a9a7e3a66b307d5c28b0c0d29a09c73c55c
@ryancreatescopy Just wanted to double check that there isn't a security issue with this before just changing this (if the file has been altered), or if this was more likely to be an accident.
=> Corrects raspi-eth1.img.zip sha256 checksum [Fixes #1901]

src/components/Link.js
Images parsed by mdx renderer are being passed through Link to be wrapped in anchor tag, but these links result in 404. These links all involve the directory "static" which as far as I can tell we never want to link to. This PR places a conditional within the `Link.js` component to look for links including "static" and returns `{children}` wrapped in a `span` instead of returning a `<Link>` component (intentionally didn't use `div` as this needs to be compatible within `<p>` tags.) 
This prevents images within EDN from being rendered as links, and are no longer clickable. Remaining link types continue to work appropriately.
=> Links to static image assets bypass intl and open in new tab [Closes #1807, Closes #1918]

src/components/SharedStyledComponents.js, src/styles/layout.css
- This adds a css selector to the `Header2` and `Header3` components within `SharedStyledComponents.js`, selecting for `<code>` children, and adjusts height to be relative to its parent.
- Changed the `a` sub-styling on these two components to `a.header-anchor` to select _only_ for the link being generator when parsing mdx (the chain-link to the left of the header). This leaves intentionally placed links within a header to render normally.
- Note this does not actually create nested anchor tags (as I previously expressed concern for), because the actual header text is not a link (only the side chain-link icon), and the ToC only strips the text, and does not apply a second link or additional styling (like `code` styling for example)
=> Fixes links within mdx h2/h3, adjusts `code` css [Fixes #1843]

src/components/SharedStyledComponents.js
This places one further condition for `grid-template-columns` so when the screen is below 280px the `min(100%, 280px)` function will result with 100%, which will then collapse properly with smaller screens.
This article explains this nicely for reference: https://ishadeed.com/article/css-grid-minmax/
Screen recording w/ fix: https://share.getcloudapp.com/4guObxDQ
=> CardGrid adjusted to prevent overflow/horiz scroll on small screen [Fixed #1953]

src/content/developers/docs/gas/index.md
I am new to Ethereum right now. While reading Gas documentation, I felt it would be easier for new users to remember Gwei-ETH relation if it was specified in scientific notation as well. So, I just added a 10<sup>-9</sup> in brackets.
=> add 0.000000001 in scientific notation as well

src/content/developers/docs/consensus-mechanisms/pos/index.md
I was reading through the Ethereum documentation and came across this sentence and felt that this is a mistake. I am not a blockchain expert so if I am wrong, an explanation would be appreciated.
=> changed from isn't to is as that makes more sense.

src/content/developers/docs/smart-contracts/languages/index.md
We moved most Solidity related resources (namely the blog and the documentation) to the soliditylang.org domain, so I'm updating all domains affected by it in the Smart Contract Languages page.
=> Updating Solidity links to soliditylang.org domain

src/components/DocLink.js
Adds the `className` prop to `DocLink` custom component to allow styling with styled-components. 
(Also a small clean up with `<Arrow />`)
#1869
=> Adds className prop to DocLink component [Fixes #1869]

src/pages-conditional/what-is-ethereum.js
Update component to string to make alt prop valid.
Console.error message:
```
index.js:2177 Warning: Failed prop type: Invalid prop `alt` of type `object` supplied to `Image`, expected `string`.
in Image (created by ActionCard__Image)
in ActionCard__Image (at ActionCard.js:67)
in div (created by ActionCard__ImageWrapper)
in ActionCard__ImageWrapper (at ActionCard.js:66)
in a (created by Context.Consumer)
in Location (created by Context.Consumer)
in Link (created by Context.Consumer)
in Location (created by GatsbyLink)
in GatsbyLink (created by ForwardRef)
in ForwardRef (created by Context.Consumer)
in Link (created by Link__InternalLink)
in Link__InternalLink (at Link.js:140)
in Link (created by ActionCard__Card)
in ActionCard__Card (at ActionCard.js:65)
in ActionCard (at …
```
=> Fix translated alt tags

src/components/CardList.js
Follow-up to #1958, only other component I found that was being styled with `styled-components` without the `className` prop being passed. This adds it to the component. 
https://github.com/ethereum/ethereum-org-website/blob/689d9d6ecc462a27d79d94eecbabd44548632a93/src/pages/eth2/get-involved/index.js#L132
=> Adds className prop to CardList component

src/content/eth2/get-involved/staking-community-grants/index.md
Markdown link syntax was incorrect for this video causing a dead internal link. This corrects the syntax.
=> Fixes link for EthStaker YT video on Grants page [Fixes #1996]

src/intl/en.json
Fixes discrepancy in DAI value for 10,000 point High Risk bug reward on eth2 bounties.
=> Fixes DAI reward for High Risk bug bounty [Fixes #2005]

src/data/eth2-bounty-hunters.csv
Initializes the bug bounty leaderboard with the winners of attacknet bounties (see https://github.com/ethereum/public-attacknets#trophies-).
=> Add eth2 attacknet winners to eth2 bug bounty leaderboard

src/components/Breadcrumbs.js, src/components/ButtonDropdown.js, src/components/Nav/Dropdown.js, src/components/Nav/Mobile.js, src/components/Nav/index.js, src/components/PageMetadata.js, src/components/Search/Input.js, src/pages-conditional/developers/index.js, src/pages-conditional/developers/local-environment.js, src/pages-conditional/developers/tutorials.js, src/pages-conditional/eth.js, src/pages-conditional/wallets/find-wallet.js, src/pages-conditional/what-is-ethereum.js, src/pages/build.js, src/pages/eth2/deposit-contract.js, src/pages/eth2/get-involved/index.js, src/pages/eth2/index.js, src/pages/eth2/staking.js, src/pages/eth2/vision.js, src/pages/get-eth.js, src/pages/index.js, src/pages/languages.js
Replaces `intl.formatMessage` instances with `translateMessageId` which does not require explicitly (and redundantly) declaring the id for `defaultMessage`.
=> Refactored codebase using `translateMessageId` [Fixes #2029]

src/components/PageMetadata.js
Use full URL for Twitter meta image
#1910
=> Use full URL for Twitter meta image [Fixes #1910]

.github/CODEOWNERS
Add @lsankar4033 @djrtwo as code owners for Eth2 bounties data
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners
Note: they need to be granted write permission on the repo in order for this to work:
https://github.com/ethereum/devops/issues/598
None
=> Add CODEOWNERS for Eth2 bounties

src/content/glossary/index.md
With the launch of the genesis block🚀, thought we should add some technical glossary terms for the eth2 stuff as they get used a lot!
=> New eth2 terms for the glossary

src/pages-conditional/developers/tutorials.js
Reduces `allTags` down to array of unique tags after sanitizing them with `.toLowerCase().trim()`. This array is then sorted by name, since the previously capitalized tags are at the top from the returned query data.
Now for example: If you list "JavaScript " when making a new tutorial markdown, it will lump with "javascript", sum up the totals for each, and display "JAVASCRIPT" with the proper sum on the UI. Clicking this will properly filter for all of them, as all tags are forced to lowercase and trimmed before being stored in the `allTutorials` constant.
Kept styling logic separate, leaving the CSS to style these as uppercase.
=> Sanitizes tutorial tags before grouping [Fixes #2020]

package.json, src/intl/en.json, src/pages-conditional/dapps.js
- Translate dapps metadata
- Add dapps page og image
#2006
=> Translate metadata

src/content/developers/docs/accounts/index.md
I'm not a native english speaker but I don't think the current version is correct:
> Ethereum has two types of account:
=> Typo in developers/docs/accounts

src/pages-conditional/developers/local-environment.js
At OpenZeppelin we've halted development of the SDK in order to focus on Contracts and plugins for Hardhat and Truffle. See [this post](https://forum.openzeppelin.com/t/building-for-interoperability-why-we-re-focusing-on-upgrades-plugins/4088) for more info.
=> Remove OpenZeppelin SDK from local environments

src/content/developers/docs/standards/tokens/erc-20/index.md
I don't believe the 1st sentence made grammatical sense. Updated & added context that standards enable interoperability.
None
=> Fix typo in ERC20 intro

src/components/Nav/Mobile.js
Mobile menu close button was accidentally removed during Mobile Search upgrade, while being placed only on the Search panel, with alterations to the styled component's layout.
This adds a second styled component, based on the other "close" button, which adds back in the absolute positioning that the original menu close button previously had, and places the component back in the menu render.
=> Re-adds mobile menu close button [Fixes #2071]

src/content/developers/docs/apis/backend/index.md
Adding BlockCypher, the web APIs seem like a good fit for this page. Going for alphabetical order. The other links should be reordered a bit if that's the intent.
=> Add BlockCypher to list of libraries and tools

src/pages/stablecoins.js
Per request on Discord, tried a re-deign of top of stablecoins page placing hero image below the intro hero content text
- Flips column layout of `<Hero>` and `<HeroContent>` on stablecoins page to avoid mobile devices landing a screen consumed entirely by the hero image
- Adjusts vertical margins to accommodate having text above image instead of below on mobile sizes < `breakpoint.l`
=> Moves layout of Hero image to below HeroContent on mobile

src/components/WalletCompare.js
- Changes wallet results `ResultsGrid` to `auto-fill` instead of `auto-fit` to prevent extra-wide cards when only 1 or 2 results result on desktop
- Adds slight adjustment to flexibility of cards on same style line with `min(100%, 280px)` as done in other "cards" on the site
Currently:
With fix:
=> Switch wallet results to grid `auto-fill`

src/components/FileContributors.js
Display author's name if no user object exists in FileContributors component
#2148
=> Account for if user is null [Fixes #2148]

netlify.toml
Add /build redirect --> /developers/learning-tools/
#2072 - this update removed the need for any Build translation pages to exist.
=> Add /build redirect for all langauges

gatsby-config.js
- Effort to speed up local development
- Attempt to prevent GH API rate limits by querying on demand vs. on app start
https://github.com/gatsbyjs/gatsby/discussions/28680
=> Add Gatsby flags to speed up local development

src/content/history/index.md
Expanded the explanation of the DAO fork to mention the WithdrawDAO contract and community vote.
=> Updated history page

src/data/translations.json
Use the correct word for Turkish language in Turkish.
Please see https://en.wikipedia.org/wiki/List_of_language_names or https://en.wikipedia.org/wiki/Turkish_language.
=> Use correct word for Turkish (language)

src/content/developers/docs/smart-contracts/anatomy/index.md
Fix the typo in the comment describing the `pizzaToOwner` variable
The comment describing the mapping was flipped. Rewrote comment to
reflect the actual mapping.
n/a
=> Fix comment for `pizzaToOwner` variable in CryptoPizza example

src/content/developers/docs/programming-languages/rust/index.md
Update link to one that works, for what appears to be the new project that replaced the old one.
wiki.parity.io redirects to openethereum.github.io/wiki but it's a 404. There is a project by that name, which is a Rust ethereum wallet, but the URL just needs fixing.
=> Fix broken link

src/content/developers/docs/intro-to-ethereum/index.md
`whose` should be used instead of `who's`:
> The Ethereum Virtual Machine is the global virtual computer **whose** state every participant on the Ethereum network stores and agrees on.
=> docs: fix typo in intro-to-ethereum

src/components/Link.js
Adds custom styles to Link component if it's a glossary link
Builds off #2130 - we need to pass the prop to the component for styling logic to work.
#1921
=> Pass isGlossary to InternalLink [Fixes #1921]

src/components/ExpandableCard.js, src/pages/eth2/index.js
`<ExpandableCard>` component has nested elements that are passed as `children` to this component, but `{children}` was being nested within a `styled.p` within `ExpandableCard.js` component which is not valid HTML. One `<ul>` was also nested within a `<p>` tag on the `/eth2/index.js` page.
- Changed to `styled.div`
- Removed unneeded wrapping `<p>` tag for the problematic `<ul>`
=> Fixed invalid DOM nesting [Fixes #2267]

src/content/developers/docs/nodes-and-clients/index.md, src/content/developers/docs/nodes-and-clients/run-a-node/index.md, src/content/glossary/index.md, src/data/developer-docs-links.yaml, src/intl/en/page-developers-docs.json
- Relocates new "Spin up your own Ethereum node" documentation to `developers/docs/nodes-and-clients/run-a-node/`
- Adds linking to documentation via EDN yaml (documents navigation)
- Updated translation json with this entry
- Added link from "node" glossary definition, a new link near top of "Nodes and Clients" from previous copy, and updated original link on "nodes and clients" page midway down the page to new path
Note, it may be beneficial to add a link to this somewhere in the Eth2/staking sections (since validators running their own nodes should be encouraged), but to limit translation issues I held this for now.
=> Adds "run a node" page to developer docs [Fixes #2270]

src/components/Link.js
- Switched `isGlossary` prop to a className
- Selected for `.isGlossary` className in CSS, and applied `whitespace: nowrap;` styling
Now rendering appropriately without DOM warnings
=> Fixes isGlossary console warnings [Fixes #2259]

src/content/developers/docs/index.md
Minor re-wording after the decision to not brand our docs as the "Ethereum developer network" due to potential confusion with development networks (i.e. https://ethereum.org/en/developers/docs/development-networks/)
None
=> Reword "Ethereum developer network"

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Added Chainstack managed blockchain service in the list of Ethereum node-as-a-service providers.
It feels natural to keep such lists in an alphabetic order, so I put BlockDaemon right after Alchemy.
=> Add Chainstack & alphabetize list

src/content/developers/docs/ides/index.md
- Adds section for VS Code extensions/plugins to the IDE dev docs page
- Includes [solidity](https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity) (245k downloads) and [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=SimonSiefke.prettier-vscode)
If anyone has more suggestions happy to add them
=> Added plugins to IDE docs [Fixes #1947]

src/pages-conditional/dapps.js
- Updated `dapps` page to track selected category (`finance`, `collectibles`, `gaming`, or `technology`) within query params of the URL
- Will load with selected category already filtered when included in link, ie: `https://ethereum.org/en/dapps?category=technology` pre-selects the technology section
- Edges: Defaults to finance if queryParam is either not included or an invalid category. Uses first if array passed.
- Maintains the scroll-navigation built into the mobile-only component at the bottom of this page (will bring user to top of #explore section)
=> Makes dapp categories linkable with URL

.github/workflows/stale.yml
Update our bot to label stale issues after 45 days & close after an additional 7 days.
=> Update stale bot timeline

src/content/contributing/index.md, src/templates/static.js
This PR includes a couple options for how we might want to advertise 2020 POAPS on our contributing page.
Option 1: page banner on contributing page
Option 2: InfoBanner on contributing page
I wonder whether we also include a tout on the new homepage that advertises this as I doubt past contributors would be checking the contributors page as it's largely instructions for people who haven't contribute before.
=> POAP contributors banner 

src/components/StatsBoxGrid.js, src/utils/cache.js
Store API data in browser local storage & on fetch data source if >1 hour stale.
None
=> Add simple caching for homepage queries

src/components/StatsBoxGrid.js, src/lambda/txs.js
- Added new lambda function for call to Etherscan API to pull transaction counts
- Created second lambda for Etherscan in the event one endpoint fails, this will not block the other from potentially displaying
- Pulling 30-days of data in anticipation of charting, but currently only displaying current
#2362
=> Switches tx count to etherscan API [Fixes #2362]

gatsby-browser.js, package.json, yarn.lock
- Adds FormatJS library to help standardize number formatting internationally.
- Imported into `gatsby-browser.js`
(Still buggy on Safari)
@samajammin If you wouldn't mind trying this on your end and see if it causes on glitchy behavior on Safari. 
#2358
=> Adds FormatJS yarn package for intl number formatting [Fixes #2358]

src/content/glossary/index.md
- Fixed typo in link syntax within "sidechain" glossary entry
- Lowercased "sidechain" for consistency
=> Sidechain glossary link bug fix

src/pages/index.js
- Fixes link for Community "tout" card on homepage. (was pointing to `/enterprise/`)
=> Community tout link patch [Fixes #2413]

src/content/developers/docs/storage/index.md
- Per Issue #2240 (thanks @adrien-be!), added Aleph.im to dev documentation under the decentralized storage page
- Trimmed the wording from issue post, feel free to offer changes
=> Adds Aleph.im to decentralized storage docs page [Fixes #2240]

src/components/Nav/index.js
The NavContainer width set to **100vw** causes a horizontal scroll bar to appear on a 13-inch laptop screen. In fact, the vertical scroll width is included using the *vw* viewport unit.
Setting width at **100%** solve this bug. Moreover I removed the useless max-width rule. It is already set on the `ContentContainer` component who is wrapping `Nav` (in *src/components/Layout.js*).
#2411
=> fix(Nav): NavContainer width fixed to avoid horizontal scroll #2411

src/content/developers/tutorials/run-light-node-geth/index.md
- Removes instances of `--testnet` flag:
```WARN [02-17|13:38:29.488] The generic --testnet flag is deprecated and will be removed in the future! ```
- Replaced with `--ropsten` throughout
- Added comments per issue #2408 regarding stopping and restarting geth from command line
#2408
=> Updates run-light-node-geth tutorial [Fixes #2408]

src/content/developers/docs/data-and-analytics/block-explorers/index.md
Add ethscan.org eth2 explorer with a free public API
Open-source eth2 beacon chain explorer based on the original eth2 explorer by bitfly, offering a free public API.
Maintained by [Redot.com](https://redot.com/)
#2292
=> Add ethscan.org eth2 explorer with a free public API

src/content/developers/docs/accounts/index.md, src/content/developers/docs/data-and-analytics/block-explorers/index.md, src/content/glossary/index.md
Changed "tree" to "trie" as discussed in https://github.com/ethereum/ethereum-org-website/pull/2397
=> Updated instances of "tree" to "trie" in docs.

src/pages-conditional/dapps.js
- If hash link provided, will navigate to it
- If "category" queryParam provided, this will be set before navigating to any hash link, and will automatically scroll to "explore" section to provide context for queryParam if no overriding hash link is provided
examples:
`/en/dapps` -> No pre-filtering (defaults to Finance), user stays at top of page
`/en/dapps#explore` -> No pre-filtering (defaults to Finance), user is taken to `explore` section
`/en/dapps?category=gaming` ->  Pre-filters to Gaming, user is taken to `explore` section
`/en/dapps?category=gaming#what-are-dapps` -> Pre-filters to Gaming, user is taken to `what-are-dapps` section
@ryancreatescopy I defaulted this to an automatic scroll (no animation), but this can be switched to a "smooth" scroll if you wanted to consider …
=> Allows hash linking alongside queryParams [Fixes #2465]

src/content/developers/docs/layer-2-scaling/index.md
Remove a point describing a non-existent attack vector for ORUs.
ORU block producers bonds are meant to refund fraud provers for gas costs and disincentivize producing bad blocks. They're not related to the TLV in the rollup at all, including as a potential attack vector.
=> Remove non-existent attack vector for ORUs

src/content/developers/docs/smart-contracts/languages/index.md
Every time I look at this page, I see "Solidity is inspired by C++, *Python* and JavaScript" and think to myself "where's the Python influence?"
Thinking about it further, it also seems kind of weird to have that there, and then mention another language that is also "Pythonic" (aka Vyper) right below it. It really just seems confusing to me. "Which language should I try if I really like Python?", the natural answer should be Vyper I would think.
Feel free to accept or reject this PR, but I just finally decided to do something about my cognitive dissonance.
=> Remove "inspired by Python" in Solidity's description

src/components/Footer.js, src/components/Nav/Dropdown.js
Removed of the partiallyActive behaviour on Navigation Dropdown & Footer links by setting `isPartiallyActive` props to false for those links.
#2515
=> fix: isPartiallyActive set to false for NavDropdown & FooterLink

src/content/history/index.md
This PR fixes the typo on the word `methods` and fixes the markdown for the link for `layer 2 scaling`.
#2543
=> Fix typo and broken markdown link in Byzantium history

src/content/developers/docs/evm/index.md
- Clarify that keccak isn't the singular reason for the 256-bit stack.
- Change SHA3 to KECCAK256 as the opcode was renamed.
- Add link to Jellopaper
=> Fixing some remarks about the EVM

src/components/Roadmap.js, src/components/SharedStyledComponents.js, src/components/TranslationsInProgress.js, src/pages/languages.js
Created a single shared component CardItem in SharedStyledComponents and replaced the cards on `/languages` and `/about` ( #2076 & #2195 ) with the new shared component. Doing this also unified card hover transition.
These card styles were outdated:
https://ethereum.org/en/contributing/translation-program/#in-progress so @samajammin I updated them to similar ones like on `/languages` and `/about`.
=> Card style updated, created a single shared component [Fixes #2251]

src/templates/use-cases.js
The NFT, DeFi and DAO pages were overflowing horizontally on mobile. The previous styles applied a margin to the hero image, which led to the bug. Added a media query to resolve the issue.
https://github.com/ethereum/ethereum-org-website/issues/2553
=> resolve width overflow on mobile [Fixes #2553]

src/templates/use-cases.js
- Hides "edit" banner for use-cases on mobile
- Centers hero image on mobile
cc: @samajammin @ryancreatescopy
=> Use-cases banner/hero mobile fixes

src/components/Layout.js
* When you access a page under ```/doc``` on **light mode**, mobile navigation is rendered in a broken way (see screenshot below)  _This only happens on light mode, (works fine on dark mode)_  
After some research into this issue, it appears to behave such due to rehydration - where ```shouldShowBanner``` is ```false``` in server side, but ```true``` on client side. 
https://github.com/ethereum/ethereum-org-website/blob/41744cc49ebc9b6be762f85912f9378fc4be1dd6/src/components/Layout.js#L93
I'm suggesting to hold off rendering of ```SideNavMobile``` component until we know the ```path``` of the page being rendered. I wrapped this logic using ```useEffect``` hook to check when ```path``` changes. 
* Turn on light mode
* Open up any page under /Docs 
* Refresh
#2301
=> Fix mobile side navigation rendering issue [Fixes #2301]

src/content/developers/docs/layer-2-scaling/index.md
Link had space and wasn't parsed correctly by markdown.
=> Fix link in #Further Reading section of L2 scaling

src/content/learn/index.md
After receiving an email pointing out we use the wrong link on the community resources page.
=> Updating broken link for eth2 news

src/content/developers/tutorials/how-to-use-slither-to-find-smart-contract-bugs/index.md, src/content/translations/ro/developers/docs/accounts/index.md, src/content/translations/ro/developers/docs/blocks/index.md, src/content/translations/ro/developers/docs/evm/index.md, src/content/translations/ro/developers/docs/gas/index.md, src/content/translations/ro/developers/docs/layer-2-scaling/index.md, src/content/translations/ro/developers/docs/nodes-and-clients/index.md, src/content/translations/ro/developers/docs/transactions/index.md, src/content/translations/ro/developers/tutorials/deploying-your-first-smart-contract/index.md, src/content/translations/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md, src/content/translations/ro/developers/tutorials/how-to-use-slither-to-find-smart-contract-bugs/index.md, src/content/translations/ro/developers/tutorials/interact-with-other-contracts-from-solidity/index.md, src/content/translations/ro/developers/tutorials/logging-events-smart-contracts/index.md, src/content/translations/ro/developers/tutorials/the-graph-fixing-web3-data-querying/index.md, src/content/translations/ro/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md, src/content/translations/ro/developers/tutorials/using-websockets/index.md, src/content/translations/ro/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md
Updates image references in new foreign language markdown to use appropriate relative link.
@samajammin This was a quick patch to fix the Romanian dev docs and tutorials so all the images weren't broken anymore. Will look into a better way to solve this as we move forward with more translations. Although this one was relatively quick, I agree this should be automated as much as possible. 
#2585
=> Fixes broken intl tutorial images [#2585]

src/content/developers/docs/accounts/index.md
Brought up by @seishun (thanks!) that the explanation of `codeHash` within the `accounts` dev docs page was confusing after information was commented out. 
Attempt at clarifying this statement.
#2443
=> codeHash explanation [Closes #2443]

src/content/developers/docs/layer-2-scaling/index.md
Clarify that ZK rollups don't need all transaction data on layer1 (because the layer 2 state is in the ZK rollup contract).
=> Explain ZK rollups further

src/content/developers/docs/standards/tokens/erc-721/index.md
Fix a simple typo on the ERC-721 page.
This commit fixes a plural/singular typo at the beginning of the ERC-721 page.
* #2620
=> Fix typo on ERC-721 page

src/content/developers/tutorials/erc20-annotated-code/index.md, src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md, src/data/translations.json, src/intl/en/page-developers-tutorials.json, src/pages/developers/tutorials.js, src/utils/time.js, src/utils/translations.js
- Filters `allTutorials` by lang locale when going to `/{lang}/developers/tutorials` 
- Added work-around to create `allTags` object from the above filtered tutorials list, as pulling via graphql did not allow differentiating tags coming from tutorials of foreign languages.
#2584
=> Tutorials filter by language [Fixes #2584]

netlify.toml
> EDIT: Having put this out I now realize Netlify asks for permission to build, so not sure it even is relevant anymore
Adds a shell script to ignore builds based on what files have been changed (rather than the author). 
The idea here is to provide the foundation for not running builds on certain commits that can of course be changed by the maintainers as you need.
Currently, it makes it so that Netlify will build if:
- Something changed in `/src` **OR**
- `.js` or `.json` files were changed elsewhere
Happy to update the pattern if anyone has suggestions. 
#1148 
The first part of the script: 
```
git diff --quiet --exit-code HEAD^ HEAD ./src
```
Will exit with code 1 if files changed in `/src`, triggering a build as per [Netlify's …
=> Limit Netlify builds to relevant diffs

src/content/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
Fix typo in https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/
Closes #2633
=> Fix typo - [Fixes #2633]

src/content/developers/docs/programming-languages/index.md
The link in the page led to a 404 error instead of https://ethereum.org/en/developers/docs/apis/json-rpc/
#2222
=> Fixed the link to the JSON RPC interface

src/content/developers/docs/smart-contracts/anatomy/index.md
There is a typo in official ethereum documentation. 
I currently learning ethereum and going through the docs and found this small typo
=> typo in docs, intenal -> internal

src/content/defi/index.md, src/templates/use-cases.js
- Added logic of `use-cases` template to show Defi hero nicely given that it has a top/right/bottom edge unlike the other. 
- Adjusted logic of smaller screens for all use-cases, @ryancreatescopy Lemme know what you think
- Cleaned up unused components
[defi](https://deploy-preview-2663--ethereumorg.netlify.app/en/defi/) | [nft](https://deploy-preview-2663--ethereumorg.netlify.app/en/nft/) | [dao](https://deploy-preview-2663--ethereumorg.netlify.app/en/dao/)
#2651
=> Adds new Defi hero image [Fixes #2651]

src/components/Nav/Mobile.js, src/components/Nav/index.js
The mobile navigation isn't hidden correctly and therefor is rendered in the accessibility tree. This means a keyboard user has to tab through all of these hidden nav items before reaching any content.
Issue #2648 
Related PR: #2649
=> improve keyboard accessibility (a11y)

src/components/DocLink.js, src/components/InfoBanner.js
- Headers in markdown have a false top margin so hash links load with the header nudged down (to prevent being buried by the nav bar)
- Custom components that precede these headers as a sibling element can be blocked from clicking on them because of this false margin
- Adding relative positioning with a z-index of 1 to the components will give them precedence.  (Tried just doing this to the header with z-index -1 but this didn't work)
- The two notable components that were encountering this bug were `DocLink.js` and `InfoBanner.js`, and this styling was added to these two components. 
Mousing-over these components will now behave appropriately, and the hash links correctly bring the header to just below the nav bar.
=> InfoBanner / DocLink bug fix [Fixes #2718]

src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md
The filepath for "@openzeppelin/contracts/token/ERC20/SafeERC20.sol"; was incorrect, I updated it to "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
I was working through the tutorial, and had a compile error. I checked the openzeppelin git repo, followed the file path, and noticed SafeERC20.sol was in file utils. I changed it in the tutorial, and it worked.
=> Update filepath for SafeERC20.sol in tutorial

src/content/developers/docs/data-and-analytics/index.md
The old link to Block explorers was returning a 404 error. I updated the link to the current Block explorer page.
- Old link for Block explorers : developers/docs/block-explorers/
- New link for block explorers: https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/
=> Update index.md - Block explorer link to the current page

src/content/developers/docs/security/index.md
The name of the mapping in the Victim contract is balances, but in the cycle description when the Attacker calls Victim.withdraw() the Victim should read balances[msg.sender] instead of balanceOf[msg.sender]
=> Fixing error in the re-entrancy section

gatsby-node.js
Attempted to address issue #2757 by doing some research and following @samajammin's suggestion on where to start looking. Added some conditional logic to the ```onCreatePage``` hook to auto set ```page.context.isContentEnglish``` to ```true``` for pages with a language content version < 2 that isn't /developers/index.js ... had some time to look into it and decided to give it a go, though commented on the issue first and made sure there was no other assignee before doing so. 
Did not test all languages pages, but did a few, and on the ones that the issue had flagged, the fix seems to work locally both on desktop and mobile screens. See attachments below. Comments and change requests welcome.
> Desktop screenshot
> Mobile screenshot
#2757
=> add conditional logic to onCreatePage hook to address TranslationBanner bug #2757

src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
Tutorial was missing a code snippet as the line above it suggested to refer the code written below
Add the code snippet as the same tutorial can be found on [alchemy website](https://docs.alchemyapi.io/alchemy/tutorials/sending-transactions-using-web3-and-alchemy)
=> missing code snippet in tutorial

src/content/developers/docs/smart-contracts/languages/index.md
As discussed in Discord, added link to https://ethereum.org/en/developers/docs/smart-contracts/languages/#solidity
for Turkish Documentation
=> Adds link to Turkish docs

src/components/Nav/Mobile.js
- Replaced hamburger menu icon with SVG that defaults to greek "Xi" shape when closed, and morphs into an ETH glyph when opened. 
- Adjusted z-index so same glyph acts as close button when menu opens, and existing close button was removed.
- Search panel will lay above all of this and function as it did. 
cc: @ryancreatescopy check it out, lemme know what you think
=> Animates hamburger menu into ETH glyph

package.json, yarn.lock
`"framer-motion": "^1.11.1"` -> `"framer-motion": "^4.1.3"`
Didn't see any errors after this, built successfully, and the animations all still work.
#2779
=> Updates framer-motion package [Closes #2779]

src/components/Link.js
Fixes an issue with lack of styling on footer links that have their language set explicity (#2815).
Wraps the GatsbyLink in a styled component. I couldn't find a similar use cases in the codebase so I hope the naming convention is okay 😃.
One thought -- the styling is the same as the InternalLink, this could maybe be refactored to be more DRY?
Closes #2815
=> Add styling to links where the language is explicitly stated

src/content/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md, src/content/translations/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md
There was a code snippet in this [guide](https://ethereum.org/en/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/) missing a whitespace, it was:
```
mkdir web3-examplecd web3-example
```
It should be:
```
mkdir web3-example
cd web3-example
```
or:
```
mkdir web3-example && cd web3-example
```
=> fix whitespace issue (missing newline) in code snippet

src/content/developers/docs/storage/index.md
The document spelled the Storj link label incorrectly, so this is the fix for it. 
Incorrect spelling fix. 
Previously -- "Stroj" 
Updated to -- "Storj"
=> Storj Spelling Mistake Fix

netlify.toml
URL used to be e.g. https://ethereum.org/en/eth2/the-docking/ but it's not https://ethereum.org/en/eth2/docking/
Add 301 redirect for all languages to the updated URL.
https://github.com/ethereum/eth2.0-deposit/pull/405
=> Add redirect for old docking URL

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
Remove deprecated camel case methods in web3.py and add the snake case methods. 
Fixes #2880
=> add snake cased method in python tutorial

src/content/glossary/index.md
Update Serenity glossary term to make it obvious that Eth2 and Serenity are the same thing.
Related Issue #2872
=> Update Serenity glossary term

src/intl/en/page-stablecoins.json
`suffficient` -> `sufficient`
Issue raised by user offline (thanks!)
=> Typo fix in english stablecoin copy

src/content/developers/docs/smart-contracts/languages/index.md
Right now the link on this page points to `https://ethereum.org/enen/developers/docs/evm` which is invalid. This corrects this invalid link.
You can view this bug here: https://ethereum.org/en/developers/docs/smart-contracts/languages/
=> Fixing EVM hyperlink

src/components/Footer.js, src/components/Link.js
Added an ariaLabel property to the Link component and supplied it with values in the Footer component to improve accessibility.
Couple of things to note:
- I haven't added translations for the aria labels as they are brand names and will be read out by a screen reader.
- To resolve the scenario mentioned in the linked issue I would only need to update the link where isExternal is true and hide arrow is true (line 123 Link.js). In this PR I've updated all links with the aria-label in case people need to use it elsewhere.
Let me know your thoughts
[Fixes #2770]
=> Added aria-labels to icon links in footer

src/content/eth2/docking/index.md, src/intl/en/page-eth2-index.json, src/pages/eth2/index.js, src/pages/eth2/vision.js, src/templates/eth2.js
Created a banner that addresses latest talk of the merge happening earlier than expected.
Also updated terminology from "docking" to "merge" on the merge upgrade page. **I haven't** updated links or updated any other content at this point. I want to confirm what our plan is here and wonder if there's an efficient way to update all this at once and inform translators etc.
=> Eth2 merge banner

src/intl/en/page-eth2-get-involved-bug-bounty.json
Per @JustinDrake changing copy of Critical bugs to read "high likelihood"
[Fixes #2895]
=> Updates critical bug bounty copy

src/content/developers/docs/storage/index.md
Updated to include new link to Storj DCS website and developer documentation
Added link to Storj DCS documentation for S3-compatible decentralized storage.
Related to issue #2929 – https://github.com/ethereum/ethereum-org-website/issues/2929
=> Update to include link to Storj DCS Documentation

src/content/community/index.md
broken link: ethereum grants link going to a 404 page 
Change: changing url to /community/grants because the url https://ethereum.org/en/community/grants/ works
=> Update index.md: Broken link for Ethereum Grants page

src/components/ExpandableCard.js
- Bug was causing causing collapsed/hidden text to only be invisible, but you could still interact with the items. 
- Adds `display: hidden` wrapper to animation.
=> Bug fix ExpandableCard.js

src/content/developers/docs/ethereum-stack/index.md, src/content/developers/docs/oracles/index.md, src/content/developers/docs/standards/tokens/erc-721/index.md, src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md, src/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md, src/content/glossary/index.md, src/content/history/index.md, src/content/nft/index.md
Hello,
This PR will fix : 
- 1 typo in `src/content/developers/docs/ethereum-stack/index.md`
- 1 typo in `src/content/developers/docs/oracles/index.md`
- 1 typo in `src/content/developers/docs/standards/tokens/erc-721/index.md`
- 1 typo in `src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md`
- 1 typo in `src/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md`
- 2 typos in `src/content/glossary/index.md`
- 1 typo in `src/content/history/index.md`
- 1 typo in `src/content/nft/index.md`
Bye! :robot:
=> docs: fix typos

src/intl/en/page-dapps.json
There is duplicated text in the description of the Index Coop on the dapps page: https://ethereum.org/en/dapps/?category=finance
This PR removes the duplicated "A crypto index fund that gives your portfolio exposure to top DeFi tokens." text
https://github.com/ethereum/ethereum-org-website/issues/2959
=> Remove Duplicated Index Coop Description Text [Fixes #2959]

src/content/developers/docs/blocks/index.md
https://www.coindesk.com/ethereum-gas-limit-eth-price-soars
Was reading up on this and realized the gas limit was outdated and right now is ~15M as oppose to ~8M back in 2018
=> doc: updating the gas limit to April 2021

src/components/FileContributors.js
`FileContributors` errors out when loading a page without commit history. Surfaced from PR #2785 where new page errors out on load, since this component is trying to fetch the commit history on something that is not included in the master branch yet.
This component already conditionally returns `null` while in a `loading` or `error` state. I added another guard clause to also return `null` if `lastCommit` is undefined.
This allows pages without commit history yet to still load remainder of page correctly.
=> Checks for "undefined" lastCommit

src/components/BannerNotification.js
Changes display styling for banner to "flex" instead of "block"
Fixes #2940
=> Switches banner to "flex" [Fixes #2940]

src/components/FeedbackCard.js
[Fixes #2974]
Deleted media-query in the FeedbackCard file to add top margin between the FeedbackCard element and the previous one.
=> Added margin between FeedbackCard and BackToTop sections. [Fixes #2974]

src/content/eth2/merge/index.md
Fixed typo.
```
preceed -> precede
```
=> Fix typo in merge/index.md

src/content/developers/docs/consensus-mechanisms/pow/index.md
Typo fix "succcessful" to "successful"
https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/#economics
Closes #3033
=> Typo Fix: Developer Docs under Proof-of-work economics

src/content/glossary/index.md
Changes the word 'changes' to 'chances' for the sentence to make sense.
Closes #3043
=> Change a word in definition of difficulty bomb

src/components/StablecoinAccordion.js
The DEX links on the stablecoin section contain wrong URLs. This change uses the correct URL for each DEX.
=> stablecoins: set the correct URLs for all DEXs

.github/ISSUE_TEMPLATE/suggest_wallet.md
The URL to be used for the "go" action - as far as I see this was missing in the template
=> Add URL to wallet issue template

src/content/developers/docs/apis/javascript/index.md, src/content/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/index.md, src/content/developers/tutorials/set-up-web3js-to-use-ethereum-in-javascript/index.md, src/content/translations/ar/javascript/index.md, src/content/translations/bn/javascript/index.md, src/content/translations/cs/javascript/index.md, src/content/translations/de/javascript/index.md, src/content/translations/es/javascript/index.md, src/content/translations/fi/javascript/index.md, src/content/translations/fr/javascript/index.md, src/content/translations/hu/javascript/index.md, src/content/translations/id/javascript/index.md, src/content/translations/it/javascript/index.md, src/content/translations/ja/javascript/index.md, src/content/translations/ko/javascript/index.md, src/content/translations/lt/javascript/index.md, src/content/translations/ml/javascript/index.md, src/content/translations/nb/javascript/index.md, src/content/translations/pt-br/javascript/index.md, src/content/translations/ro/developers/docs/apis/javascript/index.md, src/content/translations/ro/javascript/index.md, src/content/translations/se/javascript/index.md, src/content/translations/sk/javascript/index.md, src/content/translations/tr/javascript/index.md, src/content/translations/uk/javascript/index.md, src/content/translations/vi/javascript/index.md, src/content/translations/zh-tw/javascript/index.md, src/content/translations/zh/javascript/index.md
The current ethers documentation links go to an outdated page which gives the message: 'This link is out-of-date and has moved.'
This PR fixes those links to go to the correct documentation page.
=> Fix ethers documentation links

src/components/Search/Input.js
Hitting <kbd>Enter</kbd> whilst in the search box refreshed the page. Added onSubmit handler to override this behaviour. Now it simply does nothing.. I think this is probably the only thing that can be done for now unless there are plans to implement a search results page?
Open to ideas on this one because I don't think simply breaking the form submission is optimal.
Closes #3059
=> Stop refresh on 'Enter' key press while searching

src/content/developers/docs/accounts/index.md
Clarified the conversion from public key to ethereum address. The documentation stated that the address is the last 20 bytes of the public key, and missed that it was actually the last 20 bytes of the hash of the public key.
=> Update public key to Ethereum address explanation

src/content/community/index.md
Adds ethereum.org discord to list of chat rooms on community page. 
Possible answer to #3083, but would appreciate feedback before merging... @samajammin @ryancreatescopy Any thoughts on placing this here? Or should we consider waiting until our community role is expanded and re-address then? 
[Closes #3083]
=> Adds ethereum.org discord to community section [Closes #3083]

src/content/developers/docs/accounts/index.md, src/content/developers/docs/scaling/index.md
Two typos noted in Deploy 2.29.1 changes:
- "minimizies"
- Fixing statement about hashing your public key to get your public key.
=> Typo corrections

src/content/developers/docs/scaling/layer-2-rollups/index.md
Page `/developers/docs/scaling/layer-2-rollups/`
=> Removes use of "sidechain" for rollups

src/components/FileContributors.js
Add placeholder avatar to prevent layout jumping [Fixes #2809]
=> Add placeholder avatar to prevent layout jumping [Fixes #2809]

README.md
Added Instructions for setting up Etherscan and DeFiPulse API keys.
Should we preface these instructions as being optional/less important than the GitHub API token. I think having the instructions available is important but we don't really want people to be bogged down by configuration if it is unnecessary for the majority of PRs.
Closes #3123
=> Update local dev instructions

src/components/StatsBoxGrid.js
In development the StatBoxGrid component doesn't fetch from coingecko/etherscan/defipulse but the fallback figures were way off. I updated the fallbacks figures to reflect todays figures.
=> Update StatBoxGrid development fallback figures 

src/content/developers/tutorials/erc20-annotated-code/index.md
I believe the correct function name here is `_mint` and not `_emit`. I can't even find a definition of the function `_emit` anywhere.
=> fix a typo

src/content/developers/tutorials/waffle-say-hello-world-with-hardhat-and-ethers/index.md, src/content/translations/ro/developers/tutorials/waffle-say-hello-world-with-hardhat-and-ethers/index.md
- Restores the tutorial with title "Waffle say hello world tutorial with hardhat and ethers" 
- Retrieved from repo history per [comment](https://github.com/ethereum/ethereum-org-website/issues/2766#issuecomment-852435490).
- While here, updated path to replace "buidler" with "hardhat"
- Includes Romanian translation
[Fixes #2766]
=> Restores waffle say hello world tutorial

src/content/developers/docs/accounts/index.md
In line 70 where the public address is described, it states that "You get a public address for your account by taking the last 20 bytes of the SHA3 hash of the private key", this should perhaps be "You get a public address for your account by taking the last 20 bytes of the SHA3 hash of the public key"?
Currently it states the public address is derived from the private key, which is wrong. The Ethereum address is derived from the last 20 bytes of the Keccak-256 hash of the corresponding public key.
=> mistake in Ethereum address creation

src/content/developers/docs/blocks/index.md, src/content/developers/docs/gas/index.md, src/content/developers/docs/transactions/index.md
Fix unescaped asterisks as described in issue. Remove some gendered language. Remove some unnecessary asterisks.
Asterisks on the blocks page are unnecessary as they don't refer to any footnote. The italics aren't necessary either.
https://github.com/ethereum/ethereum-org-website/issues/3202
=> Fix asterisk escape

src/content/developers/docs/standards/tokens/erc-721/index.md
Fix typos in ERC721 Web3.py examples and update to use functions from latest stable version
(1) Some of the APIs in the Web3.py examples have changed as of latest stable version (5.19.0), specifically `get_event_data` function. This change updates the function calls to conform to new function signature.
(2) Some of the params in `w3.eth.getLogs` were incorrect (passing event ABIs instead of event signatures as `'topics'`) -- this change fixes that
=> Fix typos in ERC721 Web3.py examples and update to use functions from latest stable version

src/content/glossary/index.md
Added new glossary definition:
application binary interface (ABI)
The standard way to interact with contracts in the Ethereum ecosystem, both from outside the blockchain and for contract-to-contract interaction.
Related issue:
https://github.com/ethereum/ethereum-org-website/issues/3228
=> Glossary definition for ABI [Fixes #3228]

src/content/developers/docs/apis/json-rpc/index.md
JSON-RPC API METHODS section of https://ethereum.org/en/developers/docs/apis/json-rpc/ had some methods missing.
Added:
- eth_sign
- eth_signTransaction
- eth_sendTransaction
https://github.com/ethereum/ethereum-org-website/issues/3209
=> Added missing JSON-RPC API methods [Fixes #3209]

src/content/developers/docs/apis/json-rpc/index.md
removed extra divider after https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_estimategas section
https://github.com/ethereum/ethereum-org-website/issues/3264
=> removed extra divider [fixes #3264]

src/components/Codeblock.js
added the following css instructions to the codeblock pre tag styles:
overflow: visible;
min-width: 100%;
width: fit-content;
https://github.com/ethereum/ethereum-org-website/issues/3253
=> Fixed double scrollbar bug [fixes #3253]

src/content/developers/docs/programming-languages/python/index.md
Encountered typo in 'incredible' while translating page to Polish
While translating Python page to polish I encountered a typo in word 'incredible'
n/a
=> Fix for typo in Python language information tab

src/content/developers/docs/storage/index.md
0chain does not store the actual data within the blockchain itself.
Instead the concept of spreading data in allocations (contracts) across multiple 'blobbers' using user-configurable erasure-coding is used.
https://github.com/ethereum/ethereum-org-website/issues/3293
=> Moved 0chain from "blockchain based" to "contract based"

src/content/developers/docs/smart-contracts/index.md
Adding an additional link for further reading to the smart contracts section.
Clean Contracts - a guide on smart contract patterns & practices
=> Add link smart contracts section

src/content/community/grants/index.md
Description 
I have updated the link to the MakerDAO grants page, since the previous link is no longer valid.
Additional information
Ideally, I would have preferred to replace the link with a link to the grant form, similarly to the other listed grants, however there are currently no open grants on MakerDAO, therefore the form is not accessible.
Related issue
#3255
=> Update MakerDAO grants link [fixes #3255]

src/content/contributing/translation-program/index.md
Description
Added the Resource section to the Translation Program page, split up into 'Tools' and 'Communities'.
Related issue
#3266
=> Add Resources section to Translation Program page [fixes #3266 ]

src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md
While implementing the steps on this page, happened to know that Solidity 0.8.0 has an improvement [documented here](https://blog.soliditylang.org/2020/12/16/solidity-v0.8.0-release-announcement/).
The [documentation](https://ethereum.org/en/developers/tutorials/create-and-deploy-a-defi-app/) to create and deploy Dapps has the source codes with Solidity ^0.6.2. 
The developers who would use a later compiler might face an issue with the usage of SafeMath.
```
using SafeMath for uint256;
```
A comment about the new changes for Solidity 0.8.0 would help the developers to learn the improvement.
=> Updated comment for SafeMath usage

src/content/translations/ar/what-is-ethereum/index.md, src/content/translations/bn/what-is-ethereum/index.md, src/content/translations/fa/what-is-ethereum/index.md, src/content/translations/fr/what-is-ethereum/index.md, src/content/translations/id/what-is-ethereum/index.md, src/content/translations/ig/what-is-ethereum/index.md, src/content/translations/nl/what-is-ethereum/index.md, src/content/translations/pl/what-is-ethereum/index.md, src/content/translations/pt/what-is-ethereum/index.md, src/content/translations/ru/what-is-ethereum/index.md, src/content/translations/se/what-is-ethereum/index.md, src/content/translations/sk/what-is-ethereum/index.md, src/content/translations/sl/what-is-ethereum/index.md, src/content/translations/tr/what-is-ethereum/index.md
The YouTube embeds on certain translations of the "What is Ethereum" page break the mobile layout causing horizontal scrolling on small screens.
The issue is resolved by changing the embed widths to `100%` instead of `560px` which allows the videos to scale with the same behavior as the other videos on the website such as the [accounts](https://ethereum.org/en/developers/docs/accounts/) docs.
An additional enhancement to the videos on the website would be to apply a [padding hack](https://techstacker.com/how-to-responsive-youtube-videos/) to preserve the aspect ratio of the video as it scales down for mobile size screens, but that may be better addressed in a feature enhancement issue.
**Translated pages affected by this issue:**
- ar
- bn
- fa
- fr
- id
- ig
- nl
- pl
- pt
- ru
- se
- sk …
=> Fix translated What is Ethereum page mobile layouts [Fixes #3316]

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
Swaps the previously incorrect links in the related tutorials section of nodes as a service in the developer docs. 
Addresses issue #3340 [here](https://github.com/ethereum/ethereum-org-website/issues/3340).
=> Fixes related tutorials links

src/content/developers/docs/accounts/index.md
This PR fixes a very small grammatical error in the "A note on wallets" section of the "Ethereum accounts" documentation. See the extremely brief diff. 
There is no related issue to this PR. It seems silly to open an issue for such a small modification.
=> Fix small grammatical error in accounts docs

src/content/developers/docs/nodes-and-clients/index.md
Trinity is not production ready client and is not being developed anymore. Having it listed with other clients here confuses users and is inconsistent with statement above the table: 'All of them are actively worked on and pass client tests.'
Also added more info about other clients to balance it and fixed some typos.
Resolves #3358
=>  Remove Trinity, add more info 

gatsby-node.js, netlify.toml
- Adds fields exclusively used in `job.js` template to frontmatter schema. 
- Fixes build error caused by 1d7c5181 after removal of the only markdown file that populated these fields. Solution suggested within logs
```
It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Frontmatter":
```
- Leaves `job.js` template available for future use
- Adds Netlify redirect from old page to /about/#open-jobs
=> Explicitly types frontmatter schema

src/content/eth2/merge/index.md, src/intl/en/page-eth2-staking.json
- Adds some information regarding the nuance that there will be a post-merge cleanup fork. 
- Focused on the key point that withdraws will not be capable until then, not immediately after the merge.
- Couple spelling corrections
=> Update `/merge` with post-merge cleanup note

.github/CODEOWNERS
For context, Antonio (@asanso) is part of the EF Eth2 security team and is now actively involved in the management of the Eth2 bounty program :) cc @djrtwo
(Related PR: https://github.com/ethereum/ethereum-org-website/pull/3379.)
=> make Antonio code owner of eth2-bounty-hunters.csv

src/content/history/index.md
Updates /history page with latest list of EIP's to be included in London upgrade, as well as block number (with link to etherscan block countdown time estimate)
none filed (content out of date)
=> Updates London EIPs and schedule on /history

src/content/developers/tutorials/deploying-your-first-smart-contract/index.md
Fixes the deployment image reference in the 'Deploying your first smart contract' tutorial to use the correct ones.
Closes #3419
=> Fix deployment image reference [Fixes #3419]

src/intl/en/page-eth2-get-involved.json, src/pages/eth2/get-involved/index.js
Re-org Eth2 client list into 2 sections, "production-ready" & "experimental":
#3422
=> Distinguish production-ready Eth2 clients [Fixes #3422]

src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
Tutorial incorrectly displayed ./transfer-and-bought-events.png image twice rather than the correct ./transfer-and-sold-events.png image corresponding to the second sell() function tx data being described.
=> Fixed duplicate tutorial images

src/components/FileContributors.js
Contributors shows duplicate users in https://ethereum.org/en/developers/docs/ (every docs page)
The issue is previously the check to detect duplicates only worked when the _author.user_ is not null. Somehow one specific user shows up in contributors for all docs even though there are no contributions i.e with author.user null. 
example- https://ethereum.org/en/developers/docs/web2-vs-web3/ (Click see contributors)
Actual contributors- https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/web2-vs-web3/index.md
https://user-images.githubusercontent.com/55653617/126914133-613c270b-a01c-4428-aaa2-bba28a543318.mp4
I added a check to not add any such user in the contributors list. 
Fixes #3468 
cc @samajammin
=> contributors modal shows duplicates [Fixes #3468]

src/content/translations/bg/eth2/beacon-chain/index.md, src/content/translations/ca/eth2/beacon-chain/index.md, src/content/translations/de/eth2/beacon-chain/index.md, src/content/translations/el/eth2/beacon-chain/index.md, src/content/translations/fr/eth2/beacon-chain/index.md, src/content/translations/hi/eth2/beacon-chain/index.md, src/content/translations/hr/eth2/beacon-chain/index.md, src/content/translations/hu/eth2/beacon-chain/index.md, src/content/translations/it/eth2/beacon-chain/index.md, src/content/translations/ja/eth2/beacon-chain/index.md, src/content/translations/ro/eth2/beacon-chain/index.md, src/content/translations/ru/eth2/beacon-chain/index.md, src/content/translations/sl/eth2/beacon-chain/index.md, src/content/translations/tr/eth2/beacon-chain/index.md, src/content/translations/uk/eth2/beacon-chain/index.md
The string "Shipped!" is embedded as a prop within a component in the `/eth2/beacon-chain/` markdown pages, and has not been getting translated. This utilized Google Translate to quickly translate this single word for the current v2 pages
=> Translates missing string on eth2/beacon-chain

src/content/developers/docs/consensus-mechanisms/index.md
Proof of work and proof of stake are technically not consensus protocols in themselves, but just a piece of what makes a consensus protocol. This clarifies that the Nakamoto Consensus is the actual consensus mechanism. 
https://github.com/ethereum/ethereum-org-website/issues/3198
=> added nakamoto consensus to the consensus page

src/components/TableOfContents.js, src/hooks/useActiveHash.js
Highlight the link in table of content that is currently in viewport.
https://user-images.githubusercontent.com/4337699/126549847-ab397df6-41aa-4ff1-98c3-1c14682bb7ab.mp4
Created an useActiveHash hook. It changes the state to the id of the element that scrolled into the viewport.
Resolves #3235
=> feat: highlight table of content on scroll

src/content/developers/docs/apis/backend/index.md
The link to JSON-RPC endpoints is broken, this fix replaces it with a link to the JSON-RPC API methods
=> Fix link to JSON-RPC endpoints

src/content/history/index.md
Add link to EF blog post
#3521
=> Add London blog post

src/content/learn/index.md
Added a section entitled "Books and podcasts" to the learning resources page. Six books and six podcasts were listed with links.
Books reference the author(s) along with the publish date. Podcasts contain a brief description paraphrased from source websites.
https://github.com/ethereum/ethereum-org-website/issues/3181
=> Appended Books and Podcasts section to end of Resources page [Fixes #3181]

src/content/developers/docs/blocks/index.md, src/content/developers/docs/gas/index.md, src/content/developers/docs/transactions/index.md
Changes to pages to include changes introduced in London update
- Gas and Fees page - [Preview](https://deploy-preview-3509--ethereumorg.netlify.app/en/developers/docs/gas/)
- Blocks page - [Preview](https://deploy-preview-3509--ethereumorg.netlify.app/en/developers/docs/transactions/)
- Transactions page - [Preview](https://deploy-preview-3509--ethereumorg.netlify.app/en/developers/docs/blocks/)
=> Update Gas and Fees, Blocks and Transactions pages

src/content/eips/index.md
=> Update EIPs page

src/content/history/index.md
Updated the history page for London update
=> Update History page for London

src/content/developers/docs/apis/json-rpc/index.md
Add some more context & resources for this page.
https://github.com/ethereum/ethereum-org-website/issues/3520
=> Add more info to JSON RPC page

src/content/enterprise/index.md
Added chainstack.com as an infrastructure provider of Enterprise Ethereum nodes.
=> Add Chainstack in the range of Enterprise infrastructure providers

src/content/developers/docs/gas/index.md
London upgrade text should be in past tense.
=> EIP-1559 intro to past tense

src/content/translations/fr/whitepaper/index.md, src/content/translations/hu/whitepaper/index.md, src/content/translations/ro/whitepaper/index.md
The `/whitepaper` page has a markdown table in it that required the syntax to be corrected on the English page, and this carried over into the translated pages.
This fixes the instances outstanding (`fr`, `hu`, `ro`)
None filed, noticed issue while preparing #3592
=> Markdown syntax fix for whitepaper tables

.github/workflows/stale.yml
Stops stale GitHub issues from closing automatically
- Removed option to close stale PRs after 7 days
- Updated stale message to reflect changes
- Stale bot will still mark issues as stale which receive no activity.
=> Stop stale issues closing

src/content/contributing/adding-developer-tools/index.md, src/content/contributing/adding-products/index.md
The previous instructions that new product entries on the site should be added to the bottom are no longer visible on the site. This re-adds those instructions to avoid confusion or perceived favouritism between products.
=> Add product ordering instructions to adding products page

src/content/developers/docs/gas/index.md
This makes it consistently "London Upgrade".
This makes it consistently "London Upgrade" (in "src/content/developers/docs/gas/index.md") headings.
none
=> Make London Upgrade capitalization consistent in "src/content/developers/docs/gas/index.md" headings

src/content/developers/docs/apis/json-rpc/index.md
This fixes the direct to link to the ethereum specification, not directly to playground.open-rpc.org (this would bring up an example OpenRPC spec by default, or your last open spec)
=> Update Ethereum JSON-RPC Specification direct link

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Update version of tutorial 0.7.3 to 0.8.0 and update functions for the updated openzeppelin library
Changed the code in the tutorial, and in paragraphs to reflect the updated openzeppelin library. Tutorial should now work out of the box for new users.
Resolves issue #3691
=> Add up-to-date imports to the NFT tutorial

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Added a missing 'e' to the the word "openzeppelin".
=> chore: fix a spelling mistake

src/content/developers/docs/scaling/plasma/index.md
The Matic Network page has been changed (https://matic.network/) to re-direct to Polygon's homepage so we had two adjacent links landing on the same page. This PR removes the second link. 
Not opposed to removing reference to Matic altogether (Polygon have now removed reference to Matic on their homepage) if anyone has any opinions on that.
=> Remove Matic Network link

src/content/eth2/merge/index.md
Updates the merge date on [eth/merge](https://ethereum.org/en/eth2/merge) to more accurately reflect the current roadmap
=> Update merge date in eth/merge

src/components/Layout.js
Removes the London Release Banner
Fixes: https://github.com/ethereum/ethereum-org-website/issues/3541#issuecomment-892815821
=> Remove/comment out ReleaseBanner in Layout after London Release

src/content/developers/docs/gas/index.md
Gas and fees page states that for the ninth block:
```202.8 gwei * 112.5% = 256.8 gwei```
But this is the cost of the tenth block.
The actual value to the listed calculation is 228.15 gwei. I rounded down to 228.1 as ```100×(1+0,125)^7``` is 228,069734573.
=> Fix incorrect gas calculation

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Reverted changes from last push on this page, while incorporating the new ERC721URIStorage library as mentioned in https://github.com/ethereum/ethereum-org-website/issues/3691#issuecomment-904716587
=> Update OpenZeppelin Library in NFT tutorial

src/content/eth2/shard-chains/index.md
There is a typo in the page that I fixed. I just happened to notice this as I was actually reading the page to learn about shard chains and Ethereum 2.0 in general.
The word "revisited" was misspelled, but it is no longer with this PR.
=> Fix typo in shard chains page

src/content/developers/tutorials/how-to-mint-an-nft/index.md
##Two grammatical nitpicks
1. Added a missing action word 'do'
2.  Changed the indefinite article 'a' to match the phonetics of NFT (the first sound in 'en eff tee' is a vowel).
=> Fix typo in 'How to mint an NFT' tutorial

src/content/community/index.md
[Blocktribe's](https://blocktribe.com/) URL was not working for the last few days....I removed it from the Jobs section as it was directing to Job Board is Unavailable page.
Fixes #3720
=> Temporarily remove Blocktribe.com from Ethereum jobs section

src/components/Trilemma.js
In Brave Browser on Linux, some text in the Trilemma diagram is cut off (see #3434).
This PR increases the width of the viewBox for the Trilemma diagram SVG, so that the text does not get cut off, as seen in these screenshots:
Fixes: #3434. 
I'll need a hand with testing on Mac and Windows (and perhaps other browsers) to ensure that it still looks reasonable on those platforms/browsers :slightly_smiling_face:
=> Increase Trilemma viewBox width to fit text on Linux

src/content/developers/docs/dapps/index.md
Changed old broken link from "https://rimble.consensys.design" to "https://consensys.github.io/rimble-app-demo/"
Related [#3734](https://github.com/ethereum/ethereum-org-website/issues/3734)
=> Fix broken link to RimbleUI in dapps docs page

src/content/developers/docs/dapps/index.md, src/content/translations/es/developers/docs/dapps/index.md, src/content/translations/fr/developers/docs/dapps/index.md, src/content/translations/hu/developers/docs/dapps/index.md, src/content/translations/it/developers/docs/dapps/index.md, src/content/translations/pl/developers/docs/dapps/index.md, src/content/translations/ro/developers/docs/dapps/index.md, src/content/translations/zh/developers/docs/dapps/index.md
Remove the RimbleUI from the dapp-tools sections in all pages(including the translations).
#3734 
#3740
=> Remove RimbleUI from dapp tools section [Fixes #3734]

src/data/translations.json
Changed the capitalization for 'čeština' and 'norsk' to ensure consistency with the capitalization throughout the language list.
Changed 'Slovenija' to 'Slovenščina', since all the remaining languages include the language name (Slovenščina), instead of the country name (Slovenija).
#3788
=> Update language names

src/content/developers/docs/dapps/index.md
Added resources in dapp-tool section.
Adding below resources and example dapps-
1. [scaffold-eth](https://github.com/austintgriffith/scaffold-eth) & [Example Dapp](https://punkwallet.io/)
2. [Create Eth App](https://github.com/paulrberg/create-eth-app) & Example Dapp is not available.
#3782
=> Added dapp-tool resources -  scaffold-eth, create-eth-app [Fixes #3782]

src/content/developers/docs/gas/index.md
Since it said many different tools, I put the gas trackers right next to Etherscan and added GasNow. Pulled ETH Gas Station up to that list as well. Kept the related tools for analytics and apis.
=> Rearrange order of gas page links

src/content/developers/docs/blocks/index.md
fix spelling of milion -> million on Foundational topics blocks page
Fixed spelling of million on Foundational topics blocks page.
=> Fix typo on blocks developer doc

src/content/whitepaper/index.md
Update value of btc mining reward from 12.5 BTC to 6.25 BTC in whitepaper document.
=> Update BTC block reward value in WP

src/content/developers/docs/accounts/index.md
The key differences mentions that externally-owned can only send ETH between them. But they can send tokens as well, of course.
=> Correction to externally-owned accounts section in developer docs

src/content/developers/tutorials/how-to-mint-an-nft/index.md
The link to `getTransactionCount` was broken and the `replay attack` was linked to the definition of nonce, which didn't discuss replay attacks in the context. This PR takes the links from another blog which discusses the same concepts [here](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md#7-create-sendtxjs-file-create-sendtx-js) and updates them for this tutorial.
Since this file was being updated, some fixes and enhancements were done to address minor issues.
None
=> fix: broken links in NFT minting tutorial

src/content/developers/docs/gas/index.md
Now that the London upgrade is live, we should make it clear that the `Prior to the London Upgrade` section is now describing the *past*, and the `After the London Upgrade` is now describing the *current* Gas and Fees method. I suggest making this clearer by adding the date that the london upgrade went live. Without the date, if you didn't know what the London upgrade was live or if/when it would go live, you'd be unsure which of those Gas and Fees methods is the *current* method, without researching more about the London upgrade.
Simple minor change, feel free to modify/reject if not ideal.
=> Add date of London upgrade to Gas and Fees page

src/pages/developers/index.js
Fixes the translation ID on the [developers resource](https://ethereum.org/en/developers/) page, so that the **Intro to Ether** description shows up properly.
Matching translation here: https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en/page-developers-index.json#L35
Closes #3826
=> Fix incorrect translation ID in intro to ether developer doc [Fixes #3826]

src/content/nft/index.md
Removes unnecessary full stops from a list of links on NFT page.
Noticed this whilst building out the governance page
None
=> Remove fullstops from link list on NFT page

src/content/developers/docs/intro-to-ether/index.md
Removes the word 'dapp' from intro to ether description. Users hitting a intro to ether page probably aren't dapp developers just yet :)
=> Remove the word 'dapp' from intro to ether description

src/content/contributing/design-principles/index.md
Refactored markdown file from using a regular emoji to the `Emoji` component. Using a regular emoji itself was causing spacing issues on this page.
=> Fix Emoji on design-principles page

src/content/developers/tutorials/waffle-say-hello-world-with-hardhat-and-ethers/index.md, src/content/translations/es/history/index.md, src/content/translations/fr/history/index.md, src/content/translations/hu/history/index.md, src/content/translations/it/history/index.md, src/content/translations/ro/developers/tutorials/waffle-say-hello-world-with-hardhat-and-ethers/index.md, src/content/translations/ro/history/index.md, src/content/translations/zh/history/index.md
`<Emoji>` component was being used with a lowercase e (i.e '<emoji>') causing emojis not to render on quite a few of the translated history pages.
`<emoji>` --> `<Emoji>`
None
=> Fix emoji rendering on history page for es, ro, hu and zh

src/components/MeetupList.js
Removed DC blockchain meetup as the group [no longer exists](https://www.meetup.com/DC-Blockchain-Developers/). Couldn't find the alternative (i.e. if they had renamed/hosted elsewhere).
=> Remove DC blockchain developers meetup

.github/workflows/on-pr-close.yml
Adds a GitHub action to add the `Status: Abandoned` label to PRs that have been closed without being merged. This stops these issues from appearing on the [Implemented section of our roadmap](https://ethereum.org/en/about/#roadmap). 
Seems [events received](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) is the only way to access the 'merged' property on a GitHub issue. 
Extends #3822
=> Add GitHub action to label unmerged PRs

src/content/developers/docs/gas/index.md
Adds a section explaining that wallets supporting the 1559 upgrade will automatically set fees for you to the EIP-1559 section
Closes #3588
=> Adds calculating fees section on Gas Page to explain wallet UX changes

netlify.toml
Removed the redirect from `ethereum.org/dao` to `ethereum.org/en/developers`. This was added to account for the missing DAO page from the original ethereum.org website (before we added the DAO learn page).
=> Update "use-case" page redirects

README.md
There was a punctuation error in the docs and I though of fixing it.
I really believe in solving and contributing in smallest of the issues so I saw the error and thought of fixing it.
=> Fixed Documentation Punctuation

src/content/contributing/translation-program/index.md
- Replace all mentions of the Eth2 Launchpad on the Translation Program page with ''Ethereum Staking Launchpad''
- Update link to the Launchpad project in Crowdin
- Update link to the Launchpad repo to request adding a language
- Add section about Translation Groups to Translation Program page
#3864
=> Rename Eth2 Launchpad on Translation Program page

src/content/glossary/index.md
removed repeated 'Nodes and Clients' link in the 'node' glossary definition. [Fixes #3846]
=> Remove duplicate link in 'node' glossary definition. [Fixes #3846]

src/components/Roadmap.js
Didn't have access to Netlify function to test but I think this works if we just use labels...
_Edit: this works._ Filters out any PRs that have been given the 'Status: Spam' label. 
On ethereum.org
On branch deploy preview
https://deploy-preview-3822--ethereumorg.netlify.app/en/about/#roadmap
We could generalise this to 'Not Merged' and automate it using GitHub actions. [Event received](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) contains info on whether the PR has been merged or not. 
#3047
#3808
=> Filter Spam/Abandoned issues from Implemented section of the Roadmap on About page

.all-contributorsrc, README.md
The all-contributors badge in our README wasn't updating automatically (it was showing 258 contributors when we've got 508 contributors).
- Added new dynamic badge (see [this issue for context](https://github.com/all-contributors/all-contributors/issues/406)) that will calculate number of contributors to the repo on shields.io rather being reliant on the script inside `.all-contributorsrc`
- I've removed the badge template in `.all-contributorsrc` as the above change made it redundant  
**Old badge**
**Actual contributors** 
**New badge**
[Related discord discussion](https://discord.com/channels/714888181740339261/727898649006309377/886219891290566686)
=> Fix all-contributors badge to autoupdate

src/content/developers/docs/scaling/validium/index.md
The link anchor did not exist in the scope of "validium" page. I changed the link to reference the L2 page that contains the "zk-rollup" section.
I was not sure whether I should use the relative path or the absolute path, but I saw an absolute example on one of the pages and did the same here.
N/A
=> fix: ZK-rollups link on validium page

src/content/developers/docs/scaling/state-channels/index.md
=> Fix typo in state channels developer doc

src/content/developers/docs/standards/tokens/erc-721/index.md
"Said that" doesn't make grammatical sense in English, it should be "That said", or "In saying that".
Fixed grammatical error.
N/A
=> Fix grammatical error in ERC-721 documentation

src/content/developers/docs/consensus-mechanisms/pow/index.md
Fixed inconsistencies with cycling back-and-forth between terms: Proof of work, proof-of-work, PoW, etc...
=> Fix inconsistencies on proof-of-work page

src/content/governance/index.md
Change absolute path of a link to relative path in governance page.
Resolves #3893
=> fix: change absolute path to relative in governance

src/content/developers/docs/transactions/index.md
Added 'Typed Transaction Envelope' on the transaction page
References used:-
- https://eips.ethereum.org/EIPS/eip-2718
- https://blog.mycrypto.com/new-transaction-types-on-ethereum/
https://deploy-preview-3836--ethereumorg.netlify.app/en/developers/docs/transactions/
Fixes #3807
=> feat: 'Typed Transaction Envelope' added to transaction page

.all-contributorsrc
Removes `projectManagement` and `question` accidentally assigned to a user by @all_contributors bot in #3909
=> Remove accidental contribution attributions

src/content/developers/docs/nodes-and-clients/index.md
Fixed a typo: relyable-> reliable
=> Fix typo in nodes-and-clients doc

src/templates/docs.js
Inherited `Header4` from `SharedStyledComponents` and copied styling for same headers from the tutorials template. Everything appears to work as intended.
This closes #3892.
=> Fix docs h4 anchor covered by navbar [Fixes #3892]

src/content/developers/docs/scaling/validium/index.md
From what I understand it's essential for the Validium to have the off-chain data available at all times. Otherwise the users cannot recreate the state, because the data posted on L1 is not sufficient.
If that's correct, then I believe this is a con that should be added to the list.
N/A
=> feat: add "data availiability" con to Validium page

src/content/developers/tutorials/run-node-raspberry-pi/index.md
Fix Typo
fix typo of raspberry pi 4 node tutorial at https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/#storage
#3924
=> fix typo of raspberry pi 4 node tutorial [Fixes #3924]

src/content/developers/docs/transactions/index.md
The example numbers are no consistent in the gas fee example on the _Transactions_ page of the _Fundament topics_ in the the Docs section of the website, making for a confusing experience to a reader new to gas or new to the EIP-1559 base fee.
This PR proposes a simple change to the explanation of the gas components in the gas fee example, which now reflects behavior after EIP-1559, but the numbers are not consistent.
#3951 _Docs / Transactions / improve gas fee accounting example_
=> improve example gas calculation in transactions topic

src/content/developers/docs/standards/tokens/erc-777/index.md
Changes `Hook allow sending tokens...` to `Hooks allow sending tokens...` on new ERC-777 page.
None filed
=> Fix grammar/typo on ERC-777 page

src/content/whitepaper/index.md
There are a few broken/deprecated links in the whitepaper, specifically the links for UTXO lack of state and the Patricia tree wiki are broken and outdated, respectively.
Updated the links to new hrefs per #3949
=> fix broken links #3949

src/content/developers/docs/gas/index.md
Fix typo of "Calculation" in Gas and fees page in doc.
No
=> Fix typo in Gas developer doc 

src/content/developers/docs/frameworks/index.md
Corrected Alchemy Website :: alchemyapi.io is redirecting to alchemy.com
=> Fix Alchemy website link

src/components/BugBountyPoints.js, src/components/CallToContribute.js, src/components/CodeModal.js, src/components/StatsBoxGrid.js, src/components/TutorialMetadata.js, src/pages/developers/index.js, src/pages/developers/learning-tools.js, src/pages/developers/local-environment.js, src/pages/developers/tutorials.js, src/pages/eth2/deposit-contract.js, src/styles/layout.css, src/templates/docs.js, src/templates/tutorial.js
We are not declaring explicit font families for most things using a monospace typeface unless the user has `SFMono-Regular` installed. Even on my iMac, the H2 was defaulting to `monospace` instead of `SFMono-Regular`
This was causing pages using monospace to 1. look a bit disconnected on most devices and 2. created issues with typographical hierarchy in some cases as H2s appeared to be smaller in height than H3s.
On this before screenshot notice how 'Development Modules' looks smaller than 'Foundational Topics' despite being the same font-size:
See after screenshot to see how this change fixes this.
Using BrowserStack I've tested this across windows and a few mobile devices and the change seems to be an improvement across all devices.
I re-used the monospace font-stack already used in our …
=> Add more explicit font families for monospace fonts

gatsby-node.js
- Adjusts logic to exclude homepage from being flagged as `isContentEnglish === true` for v1/v1.1 languages.
- This switches the banner that is being displayed on the v1/v1.1 homepages to the "content out-of-date" banner.
Did some checking and wasn't able to find any other pages that were affected this way, but please comment if you know of any. 
#3213
=> Translation banner patch [Fixes #3213]

src/pages/eth2/get-involved/index.js
URL used to point to Eth1 execution client...
The URL for the Nimbus eth2 client currently points to their eth1 client repo.
N/A
=> Fix repo URL for Nimbus on ETH2 page

src/content/developers/docs/gas/index.md
Some values in the Gas page of the Docs section of the website are not consistently rounded and formatted.
The change in numbers uses conventional rounding and rounds to the nearest 0.1 ETH, consistently.
#3964
=> Fix base fee rounding in gas developer doc

src/content/developers/docs/programming-languages/python/index.md
- Remove gitters in favor of the discord, where all the conversation takes place today.
- Add eth-tester to the projects list.
- Add archived list of projects that may still be interesting. Add Trinity to this list.
- Re-roganize list based on traffic / usage / foundation + somewhat alphabetically sorted after that.
- gitter channels are a space to have the same conversations that are present in the discord which is very active. Removing these channels will be an efficient way of directing all traffic to one spot (the python community discord)
- Added eth-tester to the projects list in case it is of interest to anyone perusing
- Separated active vs archived projects (not tied to how this was implemented but important to make the distinction for Trinity)
- Re-organized the list based on …
=> Update Python programming language developer doc

package.json, src/components/StatsBoxGrid.js, src/lambda/defipulse.js, src/lambda/etherscan.js, src/lambda/txs.js, yarn.lock
- Adds charts to homepage using `recharts@1.8.5` library
- Adjusts axios calls to fetch 90 days of history from each endpoint
- Adds `data` property to state for each metric which holds the results of the API calls, formatted for use with charts
- Can toggle between full 90 days, or a 30-day range
Note `recharts@>v2.0.0` was causing the error noted [here](https://github.com/ethereum/ethereum-org-website/pull/3354#issuecomment-924622049), possibly related to a TypeScript dependency. Downgraded to v1.8.5 which has resolved the issue. 
@Andrew-Sofos Thank you so much for the work you put in getting this started on the other branch! In a debugging attempt for #3354 we decided to try a fresh branch and manually pull over the lambda functions and `StatsBoxGrid.js` changes. I added you as a …
=> Homepage Charts [Fixes #2319]

src/content/developers/docs/security/index.md, src/content/translations/es/developers/docs/security/index.md, src/content/translations/fr/developers/docs/security/index.md, src/content/translations/hu/developers/docs/security/index.md, src/content/translations/it/developers/docs/security/index.md, src/content/translations/pl/developers/docs/security/index.md, src/content/translations/ro/developers/docs/security/index.md, src/content/translations/zh/developers/docs/security/index.md
Ethereum-play has rebranded as Playproject-io and this broke a few of the GitHub links in our docs. This PR fixes the links across all effected translated languages.
Closes #4013
=> Remove smartcontracts.code (broken app) from security page

src/content/developers/docs/programming-languages/python/index.md
- py-eth.com has been taken down so this PR removes the link to 
- Added some love to the discord description rather than just listing the link
- Some nit-pick changes for style consistency down the page:
- Inconsistent capitalization in section titles
- Small grammar blip in newly added section
Not necessarily tied to any of the nits, nor the wording on the discord description (though we should add _something_ there), but I spoke to the maintainer of py-eth.com and that link should definitely come down.
*Note: I did go through the page and made sure all the current links that are up after this PR are indeed working!*
adds to #4000 as part of #3908
=> remove py-eth.com link & add some description for discord link

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
I've added Pocket Network along with its docs, features, and links
Added Pocket Network to the list of Nodes as a Service
Highlighted features
Hyperlinked Website, Docs, Public Endpoints, and Pocket Portal (front-end for Pocket Network protocol that enables developers to mint RPC endpoints and view analytics)
[Add Pocket Network to our Nodes as a Service #4052](https://github.com/ethereum/ethereum-org-website/issues/4052)
=> Add Pocket Network to Node as a Service Documentation

src/components/GitStars.js, src/components/ProductCard.js, src/pages/eth2/get-involved/index.js
- Removes star count from eth2 client listings
- Randomizes order of these clients with each load (Went with this approach given how we fetch the star count on a component level, and the parent that is sorting it doesn't easily have this data.)
- Adjusted the `GitStars.js` component to accept hiding the stars with prop `hideStars`, which preserves the link to GitHub with a GH icon, but does not show star count. 
#4059
=> Eth2 client randomization and GH star removal [Fixes #4059]

src/pages/eth2/index.js, src/pages/eth2/vision.js, src/templates/eth2.js
- Removes announcement banner regarding prioritizing the merge from eth2 pages.
[Fixes #3806]
=> Remove Eth2 announcement banner [Fixes #3806]

src/components/MeetupList.js
I added Chainlink's SF Meetup group to this page: https://ethereum.org/en/community/#decentralized-autonomous-organizations-daos/community/#decentralized-autonomous-organizations-daos. Under #41
=> Added Chainlink SF Meetup to list of Meetup.com groups

src/components/Breadcrumbs.js, src/templates/docs.js, src/templates/eth2.js, src/templates/static.js, src/templates/tutorial.js, src/templates/use-cases.js
This merge will fix the issue with Fallback Language (English).
The issue existed for every page generated using the 5 templates.
Rather than basing the direction off the language selected by the user, now the direction will be based on the `lang` in which the document is written (The `lang` field inside the content markdowns is being used to detect the same).
- #4028
=> Fix Fallback Language Direction #4028

src/content/contributing/index.md
Updated Discord Link Explicitly For #poap channel.
I think It is good Idea To redirect the user to #poap channel rather than #ethereum-org-development channel of discord Server Because We are Talking About POAP
Note : The Link Attached is of the following type [The Link Will Never Expire, There is No Limit To the Number Of Users]
=> Update POAP section Discord link to go to #poaps channel

src/content/community/grants/index.md
Updated TheGraph Grants Apply Link As The Old Link is no longer valid.
How to check the authenticity of the updated link.
I recently checked their latest procedure for the grants in their official Discord Channel.
https://discord.gg/9fZZFn2f
And After that I Got The Link
https://www.notion.so/The-Graph-Foundation-e822e66d7b614fdd899a647f5db51a68
Then 
https://airtable.com/shrdfvnFvVch3IOVm
I have mentioned so much details because airtable link can be created by anybody so authenticity needs to be verified.
@minimalsm @corwintines 
Please Take A Look
=> Update ecosystem grants link for The Graph 

src/content/community/index.md
Ethereum Cat Herder Community Not Active
[Link](https://gitter.im/ethereum-cat-herders)
I have attached Discord Link Instead of Gitter.
@minimalsm Any Recommendation
=> Replace Ethereum Cat Herders Gitter with Discord link

src/content/contributing/adding-products/index.md
- Adds a note about requiring honest information to be provided for product listings, and content found to be falsified will be removed.
- Couple small cleanup tweaks
[Fixes #3150]
=> Adds note about falsified listing information to product guide [Fixes #3150]

gatsby-config.js, src/components/Search/index.js
Adds `noQueryString: true` to `gatsby-plugin-react-helmet-canonical-urls` with goal to eliminate duplicate Algolia search results for pages with query params. 
ie: `https://ethereum.org/en/dapps/?category=gaming` and `https://ethereum.org/en/dapps/?category=technology` would both have a canonical URL of `https://ethereum.org/en/dapps/`
Reached out to Algolia on how to test this, as I believe it should require the new pages to be indexed.
#2764
=> Ignore queryParams on canonical URLs

src/content/learn/index.md
Removed Kauri From The List of Community Built Resources.
All the Materials Provided By Them is almost already available in other list items other than Kauri.
Reason :  Last Updated Dec 2020, URL : https://github.com/kauri-io/archive
Community Report : Community is No Longer managing The WebSite. They have just hosted it.
@samajammin @minimalsm Take a look
=> Removed Kauri From The List

src/pages/eth2/get-involved/index.js
Moved Lodestar from experimental to production-ready ETH2 client 
Fixes #4098 
That is pretty much it 
under `src\pages\eth2\get-involved\index.js` 
from `randomizedClients`
I changed `isProductionReady` for Lodestar to `true`
=> Moved Lodestar from experimental to production-ready ETH2 client 

src/content/developers/docs/index.md, src/intl/en/page-developers-docs.json
Sam and I discussed changing the README title in the introduction doc to something more semantic. Currently, we're translating 'README' which seems very confusing to me.
I've proposed changing this to `Overview` (taking inspiration from [Gatsby documentation](https://www.gatsbyjs.com/docs/)). 
- If we agree on this I'll make this change consistent throughout the docs. 
- If we don't we can remove the change.
Deploy preview - https://deploy-preview-4095--ethereumorg.netlify.app/en/developers/docs/
=> Update README developer doc

src/content/developers/docs/scaling/layer-2-rollups/index.md
- adding more resources
- added videos explaining ZK-rollups and optimistic rollups
- improvements to readability
- updated out of date information
Deploy preview - https://deploy-preview-3996--ethereumorg.netlify.app/en/developers/docs/scaling/layer-2-rollups/
=> Update layer 2 rollups developer doc 

src/intl/en/page-eth2-get-involved-bug-bounty.json
"vulnerabilites" -> "vulnerabilities"
=> Fixed typo on eth2 bug bounty page

src/content/developers/docs/intro-to-ether/index.md
reword
computing services sounds inaccurate -> computing resources?
bold definitions as per style guide
removed link. it's a prerequisite
simplify network consumption explanation
reword gas fee explanation
move section 
remove link, add it as inline link above
sentence clarity
simplify language
explaining base fee too complicated at this stage in users journey
Ethereum or 'the network' not 'the Ethereum network'
incorrect the value field doesn't transfer ether, it specifies how much ether to transfer if the transaction is successful
added resource
removed yellowpaper
=> Update Intro to Ether developer doc

src/components/Nav/Mobile.js
The bottom bar was hidden under chrome address bar because of using viewport heights. Changed the height values to use percentage values as recommended in the chrome documentation.
This fixes issue #3329
=> Added mobile navbar fix [Fixes #3329]

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/suggest_dapp.md, .github/ISSUE_TEMPLATE/suggest_dev_tool.md, .github/ISSUE_TEMPLATE/suggest_exchange.md, .github/ISSUE_TEMPLATE/suggest_glossary_term.md, .github/ISSUE_TEMPLATE/suggest_tutorial.md, .github/ISSUE_TEMPLATE/suggest_wallet.md, .github/labeler.yml, .github/release-drafter.yml, .github/workflows/on-pr-close.yml
The [GitHub labels have been updated](https://github.com/ethereum/ethereum-org-website/labels/). These changes fix the code that interacts with labeling, aligning them with our new labels.
Will need to change the labels below at the time of a deploy or the [roadmap on the about page](https://ethereum.org/en/about/) will break:
- `Status: In Progress`
- `Status: Up Next`
- `Status: Abandoned`
- `Type: Spam`
None
=> Align labels in code logic with GitHub labels

src/content/glossary/index.md
A typo
Typo for a word on line number 218
=> Fix typo in glossary for 'ether' description

src/content/developers/docs/smart-contracts/index.md
Fixed punctuation 
Added space for the word 'cannot' on line number 12
=> Fix punctuation in smart contracts developer doc

src/content/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
Corrected a sentence
Removed letter 'a' to correct the sentence on line number 40
=> Fix typo in erc-20 tutorial

src/content/community/index.md
Quite a few people seem to come to the Eth R&D Discord asking support
questions, even though that is explicitly not allowed in that server
according to its #welcome message.
One possible reason this happens is that it is the first Discord/chat
entry they see on the "community" page. To redirect users to a more
appropriate chat room/server we:
- Elaborate that the Eth R&D Discord is _not_ for support questions, and
only for focused technical discussions.
- move it down on the list, such that it is not the first link people
see if they are looking for a chat room to ask for support in.
=> Add description/purpose to Eth R&D Discord link

src/content/developers/docs/consensus-mechanisms/pow/index.md
Tiny typo I found while cruising the documentation.
=> Fix typo in proof-of-work description in the consensus mechanisms developer docs

gatsby-node.js, src/components/Footer.js, src/components/Layout.js
- Removed isLegal check as we want to produce these pages for the lang in english
- removed the /en/ in the footer to keep user on their lang
Fixes: https://github.com/ethereum/ethereum-org-website/issues/4001
=> Non-english pages link to English pages in footer navigation

src/content/developers/tutorials/run-light-node-geth/index.md, src/content/translations/pl/developers/tutorials/run-light-node-geth/index.md, src/content/translations/ro/developers/tutorials/run-light-node-geth/index.md, src/content/translations/zh/developers/tutorials/run-light-node-geth/index.md
Updates link on "How to run a light node with Geth" tutorial to https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum from https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum. Avoids extra navigation step for users.
=> Update link to geth installation instructions

src/content/security/index.md
Fix typos in security doc
Corrected typos on line number 28, 94 and 98., however I am quite skeptical about it, because some of them might be used as 'CSS Selectors' for webpage, so these changes might affect
=> Fix typos in security learn page

src/components/MatomoOptOut.js, src/content/cookie-policy/index.md, src/content/privacy-policy/index.md, src/templates/static.js, src/utils/matomo.js
- Adds component that offers user the ability to opt-out of Matomo tracking. (`MatomoOptOut.js`)
- Uses `localStorage` to store this preference, and `utils/matomo.js` will check this before submitting an event, returning early if set to `true`
- Updated the cookie and privacy policies per legal team, adding the above component
=> Policy updates, adds Matomo opt-out option

src/content/nft/index.md
The NFT page was still saying the merge might happen in 2021. so removed 2021 from there.
This is PR is linked with: https://github.com/ethereum/ethereum-org-website/issues/4392
=> Fixes Timeline estimation date

src/content/nft/index.md
Removed the wrong year mentioned as per the information seen in discord's contribution channel.
Under the 'Timelines' heading, changed '2021/2022' to '2022'.
=> Corrections regarding timeline info in NFT doc

src/content/deprecated-software/index.md
Ethereum Studio was listed as being deprecated on https://ethereum.org/en/studio/ but not on the Deprecated Software page https://ethereum.org/en/deprecated-software/
Information about it has now been added to the Deprecated Software page.
The date for when it was deprecated was taken from https://blog.ethereum.org/2020/12/07/we-are-sunsetting-studio/
The information provided in this change follows the same format as other the other deprecated software that are listed on the page.
#4433
=> Added Ethereum Studio to Deprecated Software

src/content/deprecated-software/index.md
This adds Aleth to the deprecated software list. The date referenced for deprecation is not the earliest reference of deprecation I could find, but rather the date of pull request [5937](https://github.com/ethereum/aleth/pull/5937), where the change to archive was proposed.
If anyone has a logo/image for Aleth, that would be great. I could not find one.
[Add Aleth to deprecated software page #4432 ](https://github.com/ethereum/ethereum-org-website/issues/4432)
=> Add Aleth to deprecated software list

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Added single quotes to the package name in an instruction that didn't work on zsh/mac in order to make the command work correctly.
As currently written, the command returns `zsh: no matches found: ethers@^5.0.0`
This change is consistent with the instructions at https://hardhat.org/plugins/nomiclabs-hardhat-ethers.html , which is reference in this same page.
=> Update NFT tutorial: add quotes around NPM package `ethers.js`

src/content/contributing/translation-program/translation-guide/index.md
Add a section to the translation program guide page, explaining how we deal with reports about incorrect translations in Crowdin.
None
=> Add section about reported incorrect translations

src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md
The way the code for the `buy()` in this tutorial is written, 1 token is equal to 1 Wei, not 1 Ether. If I send one Ether (1000000000000000000 Wei) to the `buy()` method, I would recieve 1000000000000000000 tokens, not 1 token.
The wording of the sentence confused me and made me think there was a bug somewhere in the code or in my local development environment.
=> Fix tutorial: 1 token is equal to 1 Wei, not 1 Ether in the buy() method

src/content/glossary/index.md
Added the term "Oracle" to the Ethereum Glossary which was previously missing but was directly relevant to Ethereum.
The term was already extensively described here: https://ethereum.org/en/developers/docs/oracles/, but never actually added to the Glossary.
https://github.com/ethereum/ethereum-org-website/issues/4309
=> Add term Oracle to the Ethereum Glossary

src/components/Nav/index.js
Prevent the page to scroll when the screen is below 1025px wide and the navigation modal are open
Done by just stopping gatsby to force `overflow-y: scroll` when the hamburger menu or the search bar are open.
Done with @vluna
#https://github.com/ethereum/ethereum-org-website/issues/4194#event-5581859174
=> Prevent the page to scroll when modal search/menu is open [Fixes #4194]

src/content/developers/docs/transactions/index.md
I just simply fixed a misspelling on the Transaction signature receipt list item
=> Fixed misspelling in Transactions signature LI

src/content/developers/docs/intro-to-ethereum/index.md
Add a link to the "Intro to ether" doc page from the terminology section of "Intro to ethereum". Similar to other titles (blocks, transactions, accounts, etc.).
https://github.com/ethereum/ethereum-org-website/issues/4505
=> Link ETH terminology to "Intro to ether"

src/content/developers/docs/transactions/index.md
Fixed a couple more typos in the Transaction Section
=> Use American English on Transaction Lifecycle

src/components/Nav/Mobile.js
- Update the height for mobile nav and search to fit the screen when address bar on chrome shows/hides
- Extract BottomMenu out of MenuContainer to fix the position for BottomMenu. This will let the menu use the height of the screen rather than the parent container
- Update style for BottomMenu to show as part of MenuContainer for the user
[#4463](https://github.com/ethereum/ethereum-org-website/issues/4463)
=> Fix height for nav on chrome mobile when address bar shows/hides [Fix #4463]

src/content/history/index.md
Sorry for deleting the template, but this is a pretty self-explanatory change.
=> Use consistent format for block numbers in history

src/templates/job.js
This PR fixes the issue where the `<p>` and `<li>` tags have different colors.
The `ListItem` component needed to be imported into the `job.js` template and passed to the MDXProvider.
#4495
=> Fix list item color in markdown files [Fixes #4495]

src/content/community/index.md
The current MetaGame link is broken. Checking in their [twitter](https://twitter.com/MetaFam), they use the following link: https://wiki.metagame.wtf/
=> Update MetaGame website link

src/content/contributing/index.md
The name of the channel seems to be outdated.
=> Fix poaps channel name

src/templates/static.js
Since we arent editing the whitepaper moving forward, this PR removes the Edit Button for the whitepaper.
=> Remove Edit Button for Whitepaper

src/content/developers/docs/smart-contracts/libraries/index.md
There was a vocabulary related edit required. The word "designs" was used where the intended word is most likely "designated"
=> Update smart contract libraries - Changed "designs" to "designated"

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
Addressed some errors on grammatical, punctuations, duplications and typos
=> Fix typos in Uniswap v2 annotated code tutorial

src/components/SharedStyledComponents.js
#4491 fixed an issue where the chain for anchor links was not showing correctly on hover for the eth2, use-cases and jobs templates. 
This PR adds the same functionality to the SharedStyledComponents which the `static` and `docs` templates inherit from.
#4487
=> Show header ID chain on hover for docs/static templates

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
It should be `removeLiquidity` function in  remove liquidity flow instead of `addLiquidity`.
=> Fix typo in uniswap-v2-annotated-code

src/content/developers/docs/smart-contracts/libraries/index.md
Typo in the smart contracts library docs. Changed "kind" to "kinds"  since we are referring to multiple building blocks.
=> Smart contracts library doc typo: "kind" to "kinds"

src/content/translations/es/developers/docs/web2-vs-web3/index.md
Link missing in Web2 vs Web3 article in spanish version
A link from the section Further reading was missing on the spanish version of the article
=> Add article to web2 vs web3 developer doc (Spanish)

src/content/translations/it/enterprise/index.md
The link to the glossary was incorrect and consequently the page does not display the word with the link style, but the word with the .md syntax
" [rete principale](/glossary/#rete principale) "
=> Fix link to the glossary and corrected the translation

src/content/developers/tutorials/run-node-raspberry-pi/index.md
Fixes issue #4621 -- Small Typo in the run-node-rasberry-pi tutorial 
Hardware and Setup section had "- MicroSD Card (16 GB Class 10 minimun)"
Changed "minimun" to minimum
=> Fixes #4621 rasberry-pi tutorial typo

src/content/eth2/beacon-chain/index.md
The Beacon Chain shipped over a year ago! This adds the year so that it is clear which December 1 the Beacon Chain shipped on.
=> Add year to Beacon Chain ship date

src/content/developers/docs/programming-languages/rust/index.md, src/content/translations/fr/developers/docs/programming-languages/rust/index.md, src/content/translations/fr/rust/index.md, src/content/translations/it/developers/docs/programming-languages/rust/index.md, src/content/translations/sk/rust/index.md, src/content/translations/tr/rust/index.md
Removing link that is no longer active from docs pages.
Resolves issue #4609
=> Remove dead link from Rust developer docs

src/content/history/index.md
Fixed some typos to make everything universal with the site itself (e.g. , " - ")🪐
=> Fix typos on History page

src/content/developers/docs/standards/index.md
dead end ("not found") the link https://blog.bmannconsulting.com/ethereum-governance/ for more about Ethereum Governance
=> Update links in standards developer docs

src/intl/en/page-developers-index.json
Fixed a typo on the developers page where the word "opportunties" was spelt wrong. So it has now been corrected to "opportunities".
=> Fixed a typo on the developers page [fixes #4608]

src/pages/stablecoins.js
- Remove `min-width` for Image on desktop so it can resize with the card before changing layout to columns
- Add `flex: 1` to `Image` to keep even ratios for cards
- Update `align-items` to `stretch` in `Row` to keep the cards with the same height
#4598
=> Update stablecoins editors' choice cards to be responsive

src/pages/contributing/translation-program/acknowledgements.js
We had more than H1 on the acknowledgements page. Refactored to use H2s instead.
_Note: not sure if we want to increase the font size of any of these headings now? If not we can probably just scrap the styled component H2._
#4678
=> Remove duplicate H1s from acknowledgement page

src/components/StatsBoxGrid.js
When switching between 30 Days and 90 Days with specific data, the chart becomes unreadable.
https://github.com/ethereum/ethereum-org-website/issues/4651
=> fix: always convert nodes stats to Number

src/content/translations/it/eth2/merge/index.md
Fixes another instance of a broken, accidentally translated, link highlighted in #4589
I have checked CrowdIn and no issues found.
#4589
=> Fix broken glossary link (Italian)

gatsby-config.js, package.json, src/components/TutorialMetadata.js, src/pages/developers/tutorials.js, src/templates/tutorial.js, yarn.lock
Make the Chinese developer Tutorials Page use English TimeToRead till [this PR](https://github.com/gatsbyjs/gatsby/pull/25533) is merged.
Please, keep in mind that this is just a temporary fix.
- #4083 
- https://github.com/gatsbyjs/gatsby/issues/25532
=> English TimeToRead for Chinese Tutorials #4083

src/components/Layout.js, src/content/history/index.md
- Removes banner notice about Arrow Glacier network upgrade
- Updates history page entry
none filed
=> Remove Arrow Glacier banner and update history

src/content/developers/docs/accounts/index.md
Was a little confused about the purpose and value of codeHash in contract accounts versus externally-owned account after reading this for the first time, so i took a peek at the yellowpaper. the yellowpaper description was almost identical to these docs, but as someone totally unfamiliar with these concepts, the minor grammatical differences in the yellowpaper actually clarified a few things for me.
Minor grammatical changes
https://github.com/ethereum/ethereum-org-website/issues/3908
=> Adjust codeHash explanation

src/content/developers/docs/evm/index.md
Fixed typos in Ethereum Virtual Machine developer docs, in reference to " https://ethereum.org/en/contributing/style-guide/#proof-of "📌
=> Fix typos in EVM developer docs

gatsby-node.js
Relative path is being passed  with `src/app/www` at the beginning, when it previously did not prior to Gatsby Cloud migration.
- Changes `gatsby-node` logic to find _last_ instance of `src/` as starting point for relative path.
- Corrects `relativePath` and `editPath` for GitHub queries
Deploy preview: https://ethereumorgwebsitedev01-relativepath.gtsb.io/en/developers/docs/
Screenshot:
[Fixes #4710]
More comments on the issue here #4762
=> Adjust `relativePathStart` logic [Fixes #4710]

src/pages/contributing/translation-program/acknowledgements.js, src/pages/eth2/get-involved/index.js, src/pages/stablecoins.js
- Fixed broken images as a result of `gatsby-plugin-image` migration
None filed, but was causing Ethereum client logos to not display on `get-involved` page
=> Fix client images to use `gatsby-plugin-image` format

src/content/contributing/style-guide/index.md
Add styling guidance around citing article authors to the style guide
#4754
=> Add citing article authors guidance to style-guide

src/components/StatsBoxGrid.js
This PR renders the StatsBoxGrid result as a `span` as opposed to an `h3` element.
#4757
=> Render StatsBoxGrid as a span [Fixes #4757]

src/pages/stablecoins.js
Issue with buttons not stacking properly in `/stablecoins`, `Use you stablecoins` container.
- Remove `ButtonLinkRight` since it only adds `margin-right` to the button
- Add  `ButtonLinkContainer` to be a container around buttons to display flex in rows
- Update second button to be `ButtonLink`
#4598 
Changed PR #4667 to this one due to issues with code
=> Fix stacking button elements in container [Fixes #4598]

gatsby-config.js, package.json, yarn.lock
Recent builds have been presenting with a large variety of bugs. The errors received followed the theme of `TypeError: ___ is not a function`. A recent bug presented similarly where nav menus were broken, and was fixed by removing the use of `lodash` in that PR. Noted that we have both `lodash` and `gatsby-plugin-lodash` installed. 
Attempting to switch usage of `lodash` library in components, to using the gatby plugin resulted in a broken build.
Removing the gatsby plugin in lieu of the standard `lodash` library seems to fix the array of bugs we've been seeing.
- Removes `gatsby-plugin-lodash` package
=> Remove `gatsby-plugin-lodash`

src/content/translations/pl/developers/tutorials/run-node-raspberry-pi/index.md, src/content/translations/ro/developers/tutorials/run-node-raspberry-pi/index.md, src/content/translations/zh/developers/tutorials/run-node-raspberry-pi/index.md
Fixes outdated link in non-English tutorials that was highlighted in #4709
#4709
=> Update Ethereumonarm URL

src/pages/index.js
PR #4788 fixed bugs being caused by `gatsby-plugin-lodash` library. StatsBoxGrid component was removed temporarily from the homepage while debugging, but was not the root cause. This re-adds the metrics to the homepage.
=> Re-add StatsBoxGrid component

yarn.lock
Removes and regenerates the `yarn.lock` file
```sh
$ rm yarn.lock
$ yarn
```
Noted by @pettinarip to potentially help with recent bugs. These bugs were already noted to stop after merging #4788 which removed the `gatsby-plugin-lodash` plugin, but for house-cleaning still agree we should do this.
=> Regenerate `yarn.lock`

src/content/community/online/index.md
Removed the extra link for joining Ethereum Org Website team discord server
The same discord server link for Ethereum Org website team was given twice.
I have just removed the extra one .
https://github.com/ethereum/ethereum-org-website/issues/4804
=> Remove redundant link

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
Fixes typo in Range for unit112 in Tutorials/Uniswap V2
Fixes #4542
=> Fix  Typo: Incorrect range for uint112 in Tutorials/Uniswap V2

src/components/StatsBoxGrid.js
This PR updates the granularity of the ether price chart to daily so it visually matches the other charts on the stats box grid.
Examples below (both 90 day)
current site:
proposed update:
this will make the full grid look more uniform, instead of the price being less smooth than the other metrics:
=> Update eth price granularity

src/content/translations/es/glossary/index.md, src/content/translations/fr/glossary/index.md, src/content/translations/hu/glossary/index.md, src/content/translations/it/glossary/index.md, src/content/translations/zh/glossary/index.md
Fixes syntax for a markdown link on the intl glossary pages.
None filed.
Taken from https://ethereum.org/zh/glossary/#sidechain
=> Fix buggy markdown link syntax

gatsby-node.js, src/content/dao/index.md, src/content/defi/index.md, src/content/nft/index.md, src/templates/eth2.js, src/templates/use-cases.js, src/utils/getSummaryPoints.js
Similar to #4760, replaces `summaryPoints` (array of strings) frontmatter with separate `string` variables for each point.
Extracted helper util function `getSummaryPoints` to parse these into an array to use in components.
#4760
=> Refactor `summaryPoints` for use-cases

src/content/developers/docs/scaling/layer-2-rollups/index.md, src/content/enterprise/index.md, src/content/translations/es/developers/docs/layer-2-scaling/index.md, src/content/translations/es/enterprise/index.md, src/content/translations/fr/developers/docs/layer-2-scaling/index.md, src/content/translations/fr/enterprise/index.md, src/content/translations/hu/developers/docs/layer-2-scaling/index.md, src/content/translations/hu/enterprise/index.md, src/content/translations/it/developers/docs/layer-2-scaling/index.md, src/content/translations/it/enterprise/index.md, src/content/translations/pl/developers/docs/scaling/layer-2-rollups/index.md, src/content/translations/pl/enterprise/index.md, src/content/translations/ro/developers/docs/layer-2-scaling/index.md, src/content/translations/ro/enterprise/index.md, src/content/translations/zh/developers/docs/layer-2-scaling/index.md, src/content/translations/zh/enterprise/index.md
Removing "Offchain Labs Arbitrum SCSC" (SCSC is an abbreviation for "SideChains/StateChannels") from hybrid rollup solutions. 
**Reasons:**
- Offchain Labs Arbitrum is already correctly listed in the "optimistic rollup" section;
- Offchain Labs Arbitrum belongs to the optimistic rollup solution and not anymore hybrid;
- link [`https://offchainlabs.com/arbitrum.pdf`](https://offchainlabs.com/arbitrum.pdf) is deprecated;
=> remove 'Offchain Labs Arbitrum SCSC' from hybrid rollup solutions

src/components/DocLink.js, src/content/community/support/index.md, src/content/dao/index.md, src/content/glossary/index.md, src/content/history/index.md, src/content/security/index.md, src/content/translations/es/glossary/index.md, src/content/translations/es/history/index.md, src/content/translations/fr/glossary/index.md, src/content/translations/fr/history/index.md, src/content/translations/hu/glossary/index.md, src/content/translations/hu/history/index.md, src/content/translations/it/glossary/index.md, src/content/translations/it/history/index.md, src/content/translations/pl/glossary/index.md, src/content/translations/pl/history/index.md, src/content/translations/ro/history/index.md, src/content/translations/zh/glossary/index.md, src/content/translations/zh/history/index.md, src/intl/en/page-dapps.json, src/pages-conditional/dapps.js
- Change `DocLink` to take the title as a child to the component
- Allows using as `block` component within markdown by splitting syntax over three lines
- Updates all usage of this component with new syntax
=> Refactor `DocLink` component

src/content/developers/docs/accounts/index.md
This PR updates the definition of a wallet to more closely match terminology commonly used. The conflicting definitions of wallets on the Ethereum website are confusing for new users to Ethereum. This change creates consistency between the pages https://ethereum.org/en/wallets and https://ethereum.org/en/developers/docs/accounts/#a-note-on-wallets for wallet definitions.
Updates the definition at https://ethereum.org/en/developers/docs/accounts/#a-note-on-wallets from
> An account is not a wallet. A wallet is the keypair associated with a user-owned account, which allows a user to make transactions from or manage the account.
to
> An account is not a wallet. An account is the keypair for a user-owned Ethereum account. A wallet is an application that lets you interact with your Ethereum …
=> Update definition of wallet in developer docs for accounts

src/content/developers/docs/networks/index.md
On line 30 of index.md of the "Networks" page for the Ethereum docs, the last occurrence of "testnet" was spelled as "testnests". Therefore the extra 's' was deleted.
=> Fixing typo of "testnests" to "testnet"

src/intl/en/page-contributing-translation-program-contributors.json, src/pages/contributing/translation-program/contributors.js
Show total number of contributors on /contrubting/translation-program/contributors page
=> Show total translator amount on contributors page

src/components/Layout.js, src/pages-conditional/eth.js
- While debugging another PR, noticed the `eth.js` pages-conditional component was named/exported as `WhatIsEthereumPage`. Updated to just `EthPage`, since `WhatIsEthereumPage` is already used by `what-is-ethereum.js`.
- Also noticed boolean logic in `Layout.js` had `isTranslationBannerIgnored` being set to the opposite of what its name declared, then negated when determining `shouldShowTranslationBanner`. Updated to be more readable.
=> Syntax adjustments

src/content/translations/es/history/index.md, src/content/translations/fr/history/index.md, src/content/translations/it/history/index.md, src/content/translations/pl/foundation/index.md
- Corrects multiple instances of `ethereum. rg` to `ethereum.org`
- Reverts translating `ethereum.foundation` link
=> Broken link fixes

src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md
Typo fix in tutorial for `MyToken`
The text defines a simple fix to a migration not having gone through and references closing `Truffle` but should be close `Ganache`
N/A as this is a typo. If this is required, I can open one!
=> Updating a typo from `Truffle` -> `Ganache`

src/content/developers/tutorials/erc-721-vyper-annotated-code/index.md
There was a dead link in the [Vyper ERC-721 Contract Walkthrough](https://ethereum.org/en/developers/tutorials/erc-721-vyper-annotated-code/). This PR fixes it.
=> Fix dead link in Vyper tutorial

src/content/developers/tutorials/calling-a-smart-contract-from-javascript/index.md, src/content/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md, src/content/translations/pl/developers/tutorials/calling-a-smart-contract-from-javascript/index.md, src/content/translations/pl/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md, src/content/translations/ro/developers/tutorials/calling-a-smart-contract-from-javascript/index.md, src/content/translations/ro/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md, src/content/translations/zh/developers/tutorials/calling-a-smart-contract-from-javascript/index.md, src/content/translations/zh/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
- Fix 404 url in paragraph in tutorial `Calling a smart contract from JavaScript`
#4937
=> Update broken url in paragraph in blog post [Fixes #4937]

src/content/dao/index.md
The link for "Ethereum community DAOs" on https://ethereum.org/en/dao/ doesn't work as it points to a page that doesn't exist. Fixed the URL to point to the correct location.
https://github.com/ethereum/ethereum-org-website/issues/4922
=> Fix incorrect URL in DAO Doc

src/content/developers/docs/consensus-mechanisms/pos/index.md
Link to difficulty adjustment for Proof-of-stake (PoS).
The very first Ethereum protocol update codified the difficulty adjustment mechanism that helps the introduction of PoS.
=> Add link to PoS docs

src/intl/es/page-index.json
- Fix typo in `page-index.json` in Spanish translation
#4877
=> Fix typo in the Spanish homepage [Fixes #4877]

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
I removed the referrals from the alchemy signup
=> Remove referral links from tutorial

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Changes:
* add missing await which can cause deployment to fail
* move ` --network ropsten` argument to avoid confusion with scripts/deploy.js
=> Improve how-to-write-and-deploy-an-nft tutorial

src/components/BugBountyCards.js
Resolves [the todo at `src/components/BugBountyCards.js:111` on the `dev` branch](https://github.com/ethereum/ethereum-org-website/blob/653e3efe500d24796c86536fd9464e878ab86ef8/src/components/BugBountyCards.js#L111)
| Before | After |
|--------|-------|
|  <img width="1680" alt="138608761-015cde1b-3ab4-40eb-b653-e1dbc1e5d53d" src="https://user-images.githubusercontent.com/27740273/147427016-30c3bb3f-86b0-45fc-93a3-1524d32a0bf7.png"> |  <img width="1665" alt="Screen Shot 2021-12-27 at 4 58 50 AM" src="https://user-images.githubusercontent.com/27740273/147427044-9781050a-ae7c-4dca-ba59-4f3da23a9995.png">  |
It should be the same. I couldn't spot a difference. Comment below if you do.
Fixes #4303
=> Resolve 'BugBountyCards.js' todo. Fixes #4303

src/content/contributing/translation-program/index.md
Update translation program stats:
Update the number of languages live on the site. There are currently 39 languages live on the site, with a PR open for Marathi as well, so 40 will be the correct number after the next deploy.
Update the number of words, translated by our community in 2021.
=> Update translation program stats

src/templates/eth2.js, src/templates/use-cases.js
The h3 element following the ul containing the two list items under "Join a DAO" has a psudo ::before element (.gWTLmC::before) which has a negative margin and height of 120px which covers the list and seems to obstruct the mouse from interacting with the list. Removing the content:"" to remove the obstruction of the psudo element for h3 and h2 tag on line number 142 and 185
Fixing two issues: 
https://github.com/ethereum/ethereum-org-website/issues/4930
https://github.com/ethereum/ethereum-org-website/issues/4922
=> Remove pseudoelement from headers [Fixes #4922, Fixes #4930]

src/data/community-meetups.json
When reviewing #4999 (to add a Jakarta based meetup) I checked out our other Indonesian meetup group. It has been inactive since 2019 therefore we should probably remove it.
None
=> Remove inactive Indonesian meetup

src/pages/wallets/find-wallet.js
- Added a max-width of 45 characters to each Subtitle
- Use the same colour on both subtitles (amused this was a mistake? can revert otherwise)
- Use rem over px (a11y)
- Small refactor to remove redundancy 
Fixes #5010
=> Fix overflow of text on /find-wallet/ header

src/templates/use-cases.js
This merge will remove the second h1 tag (preserving the style) from the use-case template.
- The landing title remains an `<h1>`.
- The title on the left side of the article (inside `<aside>`) is now an `<h2>`.
#4648
=> Remove second h1 tag [Fixes #4648]

src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
Fixed typo in 'Sending transactions using Web3' tutorial 
'for signing' instead of 'for singing'
Issue https://github.com/ethereum/ethereum-org-website/issues/5042
=> Fixed typo in 'Sending transactions using Web3' tutorial

src/content/upgrades/beacon-chain/index.md, src/content/upgrades/merge/index.md, src/content/upgrades/shard-chains/index.md
`eth2-rebrand <- upgrade-template`
Updates the following pages removing eth2 terminology
- beacon-chain
- merge
- shard-chains
=> Update pages using `upgrade` template

src/content/glossary/index.md
`eth2-rebrand <- glossary`
Did a basic update to glossary terms for eth2 rebrand. Left one note about "Ethereum 2.0" and "Eth2" in the Serenity definition.
Did not add new terms due to scope, though separately we should consider adding some new terms here like "consensus layer", "execution layer", and "merge"
=> Update glossary for eth2 rebrand

src/content/developers/tutorials/hello-world-smart-contract/index.md, src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Update some links in the index.md files of 2 different tutorials
Links here are broken
https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/#connect-metamask-and-alchemy ("To learn more about sending transactions check out this tutorial")
https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/#deploy-contract ("To learn more about sending transactions, check out this tutorial on sending transactions using Web3")
https://ethereum.org/en/developers/tutorials/hello-world-smart-contract/#step-16-deploy-our-contract ("To learn more about sending transactions, check out this tutorial on sending transactions using Web3")
Was here: https://docs.alchemy.com/alchemy/tutorials/sending-transactions-using-web3-and-alchemy
Now here: …
=> Fix broken sending-transaction links in tutorials [Fixes #5069]

src/pages/index.js
- Removes a hardcoded /en/ path from the homepage
None
=> Remove hardcoded English path from homepage callout

src/content/developers/docs/scaling/layer-2-rollups/index.md
- Adding STARK (beside SNARK) as a type of ZK proof.
- Adding external link to explain STARKs vs SNARKs.
=> Adds STARK as a type of ZK proof on layer-2-rollups doc

src/content/developers/docs/data-and-analytics/block-explorers/index.md
Fixes #5101
This is a oneliner modifying the index.md to correct a typo from focusses to focuses with the only change been the extra "s" removed
=> Fix Issue #5101: fix typo on Block explorers page

src/content/developers/docs/nodes-and-clients/index.md, src/content/translations/es/developers/docs/nodes-and-clients/index.md, src/content/translations/fr/developers/docs/nodes-and-clients/index.md, src/content/translations/hu/developers/docs/nodes-and-clients/index.md, src/content/translations/it/developers/docs/nodes-and-clients/index.md, src/content/translations/pl/developers/docs/nodes-and-clients/index.md, src/content/translations/ro/developers/docs/nodes-and-clients/index.md, src/content/translations/zh/developers/docs/nodes-and-clients/index.md
`eth2-rebrand <- client-content`
- Updates terms on `nodes-and-clients` page to use "execution" and "consensus" clients.
- Drafted table for consensus layer clients
https://www.notion.so/efdn/Update-client-content-47575e2b6d6a41878457ed9f768d537c
=> Updates nodes-and-clients copy

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
npm install --save-dev @nomiclabs/hardhat-ethers 'ethers@^5.0.0'
doesn't work, gives error
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/%27ethers - Not found
npm ERR! 404
npm ERR! 404  ''ethers@5.0.0'' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain special characters ("~'!()*")
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm install --save-dev @nomiclabs/hardhat-ethers ethers@^5.0.0
does work
=> Fix npm install error in tutorial

src/content/eth2/shard-chains/index.md, src/content/translations/fr/developers/docs/programming-languages/delphi/index.md, src/content/translations/fr/glossary/index.md, src/content/translations/hu/glossary/index.md, src/content/translations/it/developers/docs/programming-languages/delphi/index.md, src/content/translations/it/glossary/index.md, src/intl/pt-br/page-developers-index.json, src/intl/tr/page-eth2-index.json
This fixes https://github.com/ethereum/ethereum-org-website/issues/4968
Using style guide at https://ethereum.org/en/contributing/style-guide/#mainnet
---
Also fixes all translations based on what is appropriate for that language.
=> Implement Ethereum.org style guide for Mainnet

src/content/community/language-resources/index.md
[ Related Issue #1](https://github.com/ethereum/ethereum-org-website/issues/5128)
[ Related Issue #2](https://github.com/ethereum/ethereum-org-website/issues/5126)
[ Related Issue #3](https://github.com/ethereum/ethereum-org-website/issues/5124)
=> Add spanish tutorials w/external links

src/components/WalletCard.js
Fixes glitch on WalletCard component when hovering over a flipped card. 
None filed. 
Can reproduce by going here on desktop: https://ethereum.org/en/wallets/find-wallet/
Then flipping any card over and hovering over that card.
=> Fix: svg hover bug on WalletCard

src/content/community/get-involved/index.md, src/content/community/online/index.md
Updated ECH invite link from `discord.io` page to original discord invite link
Users don't have to get redirected from `discord.io` the slash page
=> Updated ECH invite link 

src/pages/get-eth.js
Similar to #5011, fixes overflowing text on language with longer sentences.
- Added a max-width of 45 characters to each Subtitle
- Use the same colour on both subtitles (amused this was a mistake? can revert otherwise)
- Use rem over px (a11y)
- Small refactor to remove redundancy
#5010
=> Fix overflow of text on /get-eth/ header

src/content/deprecated-software/index.md, src/content/developers/docs/nodes-and-clients/index.md
Added same deprecation notice that we have on https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#getting-the-client
Also updated the OpenEthereum section on the deprecated software page. It seemed strange that we only mention Erigon as an alternative.
https://github.com/ethereum/ethereum-org-website/pull/4915#issuecomment-1018028898
=> Add OpenEthereum deprecation notice

src/content/glossary/index.md
Adds/fixes header ids for recently added glossary terms
None filed
=> Fix glossary term header ids

src/pages/upgrades/get-involved/index.js
Recently the `Callout` component was updated to accept `titleKey` and `descriptionKey`. 
The `StyledCalloutBanner` used on the upgrades/get-involved page is a `styled(CalloutBanner)` not a `styled(Callout)` and accidentally had it's props changed to the "key" arrangement.
Go to https://ethereum.org/en/upgrades/get-involved/ scroll down and see:
Reverted back to just `title` and `description`, passing the actual text and not just the look-up key.
=> Fix intl string bug

src/components/UpcomingEventsList.js, src/data/community-events.json, src/intl/en/page-community.json
- Add events from [the provided spreadsheet](https://docs.google.com/spreadsheets/d/1NEu_FCc1hnGAuRgPmbXXpf0h2lCrCOlMKbbFEqgkVDQ/htmlview)
- Update component to render 10 events at a time with "Load more" button
#5221
=> Add new upcoming events [Fixes #5221]

src/content/developers/docs/consensus-mechanisms/index.md
This pull request removes the additional closing bracket from the consensus-mechanisms page.
[Link to issue](https://github.com/ethereum/ethereum-org-website/issues/5270)
=> Removed additional closing bracket from the consensus-mechanisms page [Fixes #5270]

src/content/community/language-resources/index.md
One of our Turkish contributors has translated the 'The great renaming: what happened to Eth2?' blog post into Turkish. We should add this to the Language resources page.
https://blog.ethereum.org/2022/01/24/the-great-eth2-renaming/
=> Add Turkish translation of the 'What happened to Eth2' blog post

src/content/community/grants/index.md
I fixed the typo in the Grants Page via updating the index.md file.
Similar typos exist in the translation files, but I didn't want to 
update them, as I don't know if they're really typos or specific 
spelling rules in that language.
[👉 Issue](https://github.com/ethereum/ethereum-org-website/issues/5246)
=> Fixed the typo in the Grants Page [Fixes #5246]

src/data/developer-docs-links.yaml, src/intl/en/page-developers-docs.json
Included client-diversity developer doc https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/
in developer docs sidebar navigation under 'Nodes and clients' between between 'Run a node' and 'Nodes as a service'.
Files edited : `/src/data/developer-docs-links.yaml`
Issue Fix : Client-diversity developer doc not included in developer docs sidebar navigation #5275
=> Including client-diversity developer doc in developer docs sidebar navigation

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Visibility for constructors is not needed anymore, and hardhat throws a warning when public is used.
https://docs.soliditylang.org/en/v0.7.0/070-breaking-changes.html#functions-and-events
=> Remove public from solidity constructor

src/content/community/online/index.md
Adds chat links for ethereum-solidity.
Fixes #4753
=> content: add chat links (gitter/matrix) for ethereum-solidity

src/intl/en/page-run-a-node.json
Fixed typo on page-run-a-node.json, encountered during translation 📣
=> Fix typo on page-run-a-node.json

src/intl/en/page-run-a-node.json, src/pages/run-a-node.js
This is a proposal to make the section a bit simpler. Just felt redundant having the 2 same urls in the same space.
@wackerow let me know what do you think? perhaps you have some reason why we have done it that way and I'm not considering it
=> Simplify cpubenchmark link

src/content/glossary/index.md
Added term "sync committee" to glossary, with definition:
"Sync committees are randomly selected groups of [validators](#validator) on the [Beacon Chain](#beacon-chain) that refresh about every 27 hours. Their purpose is to add their signatures to valid block headers. This allows [light clients](#lightweight-client) to keep track of the head of the blockchain without having to access the entire validator set."
Closes #5365
=> add sync committee to glossary

src/content/developers/docs/data-and-analytics/index.md
The resource at the old URI on The Graph's documentation site is gone, causing a broken link on the [Data and analytics](https://ethereum.org/en/developers/docs/data-and-analytics/) page.
Replaced broken link to https://thegraph.com/docs/en/network#overview with https://thegraph.com/docs/en/about/network/
Just something I noticed while reading the docs.
=> Fix broken link to The Graph Network Overview page

src/content/developers/docs/networks/index.md
The Rinkeby Faucet has been unreliable/ not sending out test ETH for a few months now. Getting test ETH for Rinkeby from the Chainlink faucet is a better option until the Rinkeby issue is resolved.  I wrote  a note letting users know this in case they experience difficulty with the Rinkeby faucet.
=> Advise readers of Rinkeby faucet unreliability

src/pages/developers/tutorials.js
Issue: #5444 
On the `Tutorials` page
When more than one tag is selected and one of these tags is removed, the tutorials aren't filtered again
Steps to reproduce:
- Navigate to the tutorials page
- Select more than one tag
- See the filtered tutorials that match those tags
- Deselect only one of the selected filters
- See how the filtered tutorials haven't been recalculated
=> Fixes tutorial content filtering by tag [Fixes #5444]

src/components/Nav/Dropdown.js
- Add `tabInteractionHandler` function to handle when the last item in the submenu is reached and tab is pressed
- Update `onKeyDownHandler` function to close submenu when pressing Shift + Tab on main menu focus
- Update `DropdownItem` styled component to pass if the menu should close
#5412
=> Add tab handler action for submenus in main menu [Fixes #5412]

src/content/developers/tutorials/erc20-annotated-code/index.md
Fix a small typo in ERC-20 Contract Walk-Through
=> Fix typo in ERC-20 Contract Walk-Through

src/content/contributing/translation-program/index.md, src/content/contributing/translation-program/translators-guide/index.md
Add link to the Crowdin knowledge base (specifically the guide to using the Crowdin online editor) to the Resources section of the Translation Program page.
Add links to the Crowdin guide on the TP page and the Crowdin knowledge base to the translation style guide.
Change the capitalization of some segments for consistency.
=> Add link to Crowdin guide to translators guide and TP page

src/content/translations/zh/developers/docs/programming-languages/dot-net/index.md
Fixed typo.
```
Github -> GitHub
```
=> Fix typo (Github -> GitHub) in Chinese developer docs

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md
This PR adds details on the Ethereum node running and BaaS (blockchain as a service) capabilities offered by [Kaleido](https://kaleido.io).
=> Add Kaleido to Nodes as a Service list

src/content/glossary/index.md
Last pr from me in this bundle...!
adding "checkpoint" to glossary with definition:
"The [Beacon Chain](#beacon-chain) has a tempo divided into slots (12 seconds) and epochs (32 slots). The first slot in each epoch is a checkpoint. When a [supermajority](#supermajority) of validators attests to the link between two checkpoints, they can be [justified](#justification) and then when another checkpoint is justified on top, they can be [finalized](#finality)."
n/a
=> add "checkpoint" to glossary

src/content/glossary/index.md
Add "LMD_GHOST" to glossary with definition:
"The [fork-choice algorithm](fork-choice-algorithm) used by Ethereum's consensus clients to identify the head of the chain. LMD-GHOST is an acronym standing for "Latest Message Driven Greediest Heaviest Observed SubTree" which means that the head of the chain is the block with the greatest accumulation of [attestations](#attestation) in its history."
Clsoes #5392
=> add lmd-ghost to glossary

src/content/glossary/index.md
Adding fork-choice algorithm to glossary with definition:
"The algorithm used to identify the head of the blockchain. On the execution layer the head of the chain is identified as the one with the greatest total difficulty behind it. This means the true head of the chain is the one that required the most work to mine it. On the consensus layer the algorithm observes the accumulated attestations from validators ([LMD_GHOST](#lmd-ghost))."
Note that this contains a link to an entry that doesn't yet exist (lmd-ghost) but is added in separate PR (#5396).
Closes #5367
=> add "fork-choice algorithm" to glossary

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Cleaning up the link to Alchemy's NFT API since it previously went to a specific section that wasn't the top
=> Update Alchemy link in NFT tutorial

src/content/developers/docs/intro-to-ethereum/index.md
Changes terminology from "EVM storage" and "EVM memory" to "EVM state" to reflect a more accurate description of smart contracts' place in the EVM.
=> fix: Use correct terminology to refer to the EVM state

src/content/translations/es/developers/docs/programming-languages/python/index.md
updated ES version to be the same as the EN version because there were some dead links and some other useful links missing
=> Update Spanish Python developer doc 

gatsby-config.js, package.json, plugins/gatsby-remark-image-urls/index.js, plugins/gatsby-remark-image-urls/package.json, src/content/translations/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/index.md, yarn.lock
The following proposal tries to solve having different images urls between source and translated md files. With this, we won't need to adjust the images urls in translated files (we wil keep the same as in the source file).
By using a local gatsby plugin we can intercept the nodes created by `gatsby-plugin-mdx` and adjust the images urls. We can think about it as a "translator" for urls.
- If we are in a source file => the plugin will ignore it
- If we are in a translated file => the plugin will modify the url by pointing them to the source file folder (what we were doing manually)
Check working example https://ethereumorgwebsitedev01-mdximagespaths.gtsb.io/ro/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/
#2585
=> Local plugin to fix translated mdx images urls

src/content/bridges/index.md
Added the missing word 'lost' to line 101 in the Introduction to Blockchain Bridges page.
=> Added missing word to Smart Contact Risk line on Bridges page

src/content/community/language-resources/index.md
Fixed typos in line number 69 and 70 for cryptography and security channels description on 
Language Resources page
`acccount` to `account`
=> Update cryptography and security channels description on Language Resources page

src/content/glossary/index.md
Fixes header-id link for `fork-choice-algorithm` on glossary page
=> Fix header id syntax

plugins/gatsby-remark-image-urls/index.js
Adds support for langs with more than two letters. E.g. `pt-br`.
=> Fix urls plugin regex

src/content/translations/fr/dao/index.md, src/content/translations/fr/nft/index.md, src/content/translations/ru/dao/index.md, src/content/translations/ru/defi/index.md, src/content/translations/ru/nft/index.md
Image paths in frontmatter missing extra `../../` to move to proper directory. It was originally thought the recent plugin addition to handle relative paths for markdown files would fix this but does not appear to be. 
This PR reverts to the relative paths that still work to display these frontmatter images.
=> Frontmatter patch for relative image paths

src/content/translations/zh/developers/docs/apis/javascript/index.md
fix wrong spell when use web3.setProvider, change from web3。etProvider to web3.setProvider
=> Fix typo in javascript APIs developer docs (Chinese)

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md
Without the "gas" value in the transaction there will be an error:
```python TypeError: MockBackend.estimate_gas() takes 2 positional arguments but 3 were given```
=> Add gas to transaction example in Python Tutorial

src/content/developers/docs/networks/index.md, src/content/developers/tutorials/hello-world-smart-contract-fullstack/index.md, src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md, src/content/translations/es/developers/docs/networks/index.md, src/content/translations/fr/developers/docs/networks/index.md, src/content/translations/hu/developers/docs/networks/index.md, src/content/translations/id/developers/docs/networks/index.md, src/content/translations/it/developers/docs/networks/index.md, src/content/translations/pl/developers/docs/networks/index.md, src/content/translations/ro/developers/docs/networks/index.md, src/content/translations/zh/developers/docs/networks/index.md
Update legacy Ropsten testnet faucet to an available alternative in tutorials. Remove all references to end-of-life'd legacy Ropsten testnet faucet.
Update references and instructions for legacy Ropsten testnet faucet to faucETH https://fauceth.komputing.org, an available alternative in tutorials. Remove all references to end-of-life'd legacy Ropsten testnet faucet https://faucet.ropsten.be/
#5450
=> Update and remove references to end-of-life'd legacy Ropsten testnet faucet [Fixes #5450]

netlify.toml
From the ESP site, we need to access the Matomo script located in the eth.org domain. This will enable us to access it.
=> CORS esp domain

src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
Upgrade solidity version in Hardhat config code snippet shown in NFT minting tutorial to fix contract compilation error.
Upgrade from `0.8.0` to `0.8.1` to meet the requirement of `@openzeppelin/contracts/utils/Address.sol`.
#5389
=> Upgrade solidity version in Hardhat config [Fixes #5389]

src/content/contributing/translation-program/translators-guide/index.md
Remove sentence about adding the original English term in brackets when translating terms without established translations from the translators guide, due to the formatting issues this causes with terms that already have an abbreviation in brackets.
=> Remove sentence about adding English terms in brackets

src/content/translations/zh/developers/docs/smart-contracts/libraries/index.md
fix some typo in smart contract lib Chinese translator
=> Fix typo in smart contract developer docs(Chinese)

src/content/contributing/translation-program/translators-guide/index.md
Add section on translating page metadata to the translation style guide, with an emphasis on translating language codes.
=> Add section on translating metadata to translators guide

src/content/developers/docs/apis/javascript/index.md, src/content/nft/index.md
The current docs only include contract standards but no resources for interacting with NFT contracts post-deployment. I added one resource, the Alchemy NFT API, for interacting with, viewing, and integrating with NFTs.
Added information about the Alchemy NFT API for interacting with, viewing, and integrating with NFTs as part of the entire NFT build process.
=> Add nft resources for interacting with, viewing, and displaying nft contracts

src/content/developers/docs/intro-to-ether/index.md
While reading the documentation, I realized that ether burn was explained but it wasn't clarified as to why it is done.
I understood why minting is required but why to burn, I was clueless.
I have added a side-note under {#burning-ether} section regarding the same.
I'm hoping this will add more clarity to the documentation.
=> Add a side-note as to why ether is burnt

.env.example, package.json, src/api/coinmetrics.js, src/api/defipulse.js, src/api/etherscan.js, src/api/etherscanBlock.js, src/api/roadmap.js, src/api/translations.js, src/api/txs.js, src/components/ReleaseBanner.js, src/components/Roadmap.js, src/components/StatsBoxGrid.js, src/components/TranslationsInProgress.js, src/lambda/coinmetrics.js, src/lambda/defipulse.js, src/lambda/etherscan.js, src/lambda/etherscanBlock.js, src/lambda/roadmap.js, src/lambda/translations.js, src/lambda/txs.js, yarn.lock
Currently we have the Netlify functions working in the Netlify context/server. On the other hand, in our preview deploys context (Gatsby Cloud) they are not working. We need to integrate them. This PR addresses this issue.
- Added `api` folder to enable functions in gatsby cloud.
- New env var `GATSBY_FUNCTIONS_PATH` to determine the path of the functions in each environment.
- In Netlify: `/.netlify/functions`
- In GC: `/api`
**HOW TO TEST IT:**
1. Enter https://www.gatsbyjs.com/dashboard and use the site: `pettinarip-ethereum-org-website-dev`
2. Change `GATSBY_FUNCTIONS_PATH` env var to `/api` => wait the build to finish  => test the preview deploy
3. Change `GATSBY_FUNCTIONS_PATH` env var to `/.netlify/functions` => wait the build to finish => test the netlify deploy (netlify url …
=> Enable Gatsby functions in preview deploys

src/content/developers/docs/programming-languages/index.md
- Add new Ruby page (from #5387) to the list on the programming languages page.
- Sort links alphabetically
None
=> Add ruby to list

src/content/developers/docs/scaling/index.md
Noticed we don't link to the Validium page from the Scaling page - it's the only subpage we don't have a section on.
Separate question - is Validium considered an L2? In this PR I kept it separate, like Sidechains & Plasma. Not sure if that's correct. This relates a bit to #5576.
None
=> Add Validium section to scaling page

src/components/StatsBoxGrid.js
- Remove `outline: none` to `Button` component in network statistics graph on home page. This will allow to show focus when tabbing.
#4229
=> Add focus when tabbing through content to network statistic section [Fixes #4229]

src/content/developers/docs/gas/index.md
Simply adds one more resource to the article about gas fees.
Calculate gas fees in your local currency for different transaction types on Mainnet, Arbitrum, Binance Smart Chain, Avalanche, Polygon, Fantom and Harmony.
Launched on December 5, 2021: https://twitter.com/FelixVemmer/status/1467532744519565323
https://github.com/ethereum/ethereum-org-website/issues/5099
=> Add gas fees calculator resource [fixes #5099]

src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md, src/content/developers/tutorials/understand-the-erc-20-token-smart-contract/index.md
Noticed this issue has been hanging for a while so had a crack at it - hope that's ok.
Issue #5354 describes a declaration error thrown when the contract in tutorial in the developer docs [here](https://github.com/ethereum/ethereum-org-website/blob/864d77178dee04e80d5f983b3911cc351118fb26/src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md) is compiled using Solidity 0.8.0.
This is not really a huge problem since the tutorial is written with a clear `pragma Solidity ^0.6.0` statement. As long as the pragma statement remains unchanged at `^0.6.0` the contracts compile perfectly and behave as expected. Therefore, the mods might decide this PR is unnecessary and close it without merging. However, some users might want to use the …
=> update contracts in tutorial to work with Solidity 0.8.0

src/content/developers/tutorials/run-light-node-geth/index.md
- Remove references to running full sync - after all, this article is about `run-light-node-geth`.
- Switch to passive voice where possible.
- Change to beginner after significantly simplifying the page, to distil down to the very focussed task of running a geth light node
- Removed references to other syncmodes - this article is about light mode.
- Simplified section re: connecting to testnets, and added goerli
- Remove additional content about how to interact with geth. Aiming to keep this page as lightweight and focussed as possible, onto the basics of running a Geth light node
=> Simplify run-light-node-geth tutorial

redirects.json
- Redirects from https://ethereum.org/discord to discord invite link.
**Question**: do we also want this to work with language paths? (e.g. https://ethereum.org/en/discord)
None
=> Add Discord redirect

src/data/layer-2.json, src/intl/en/page-layer-2.json
Adds a disclaimer for Arbitrum. According to Arbitrum's documentation, Arbitrum's fraud proofs can currently only be used by [whitelisted addresses](https://developer.offchainlabs.com/docs/mainnet). This whitelist is currently not open to the general public, which has important effects on the security model of the system (only the Arbitrum team can currently use the fraud proof system). This is important to note (alongside the notes described for other L2s).
=> fix: add note for Arbitrum

src/data/community-events.json
Fixed an event date 📅
As reported by the website https://deficon.nyc/ , the DeFiCon event will take place on 7-8 May 2022.
Most likely, the date error was associated from here: https://www.eventbrite.com/e/deficon-2022-tickets-164176080075
=> Fix event date inconsistency

src/components/EthExchanges.js
Fixes a small bug where there was no space between two sentences of the final paragraph on the `EthExchanges` component.
None
=> Fix small typo on EthExchanges

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
In Solidity 0.5, `uint112(-1)` is `2^112 - 1`, not `2^111` and it is 5.19*10^33, not 2.5*10^33.
=> Fixed incorrectly referring uint112(-1) as 2^111

src/templates/docs.js
Removes conditional logic that stopped the `FeedbackCard` from showing on non-English developer doc pages
None
=> Add FeedbackCard to all langs (developer docs)

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md
The paragraph in the Uniswap-V2 Contract Walk Through document about gas saving by packing variables refers to three variables, `reserve0`, `reserve1`, and `blockTimestampLast`, and is moved up to be closer to the relevant code chunks. `kLast` is a regular uint256 and not packed in a single slot with other variables and its reference removed.
=> Moved up the gas expense paragraph; removed kLast reference

src/content/glossary/index.md
Under the entry for 'decentralized exchange', the button linking to the /get-eth/dex page contains a typo. Specifically, the incorrect spelling is 'Decentalized exchanges'
[Fixes #5762]
[https://github.com/ethereum/ethereum-org-website/issues/5762](url)
=> Fix typo in the Ethereum glossary
