src/content/translations/de/history/index.md
src/content/translations/fr/history/index.md
src/content/translations/it/history/index.md

Fix broken emoji components
#8710

Fix broken Emoji components on history page

---

src/data/community-meetups.json

Adding Ethereum Costa Rica

---

src/components/Emoji.tsx
src/components/TutorialMetadata.tsx
src/pages/developers/tutorials.tsx

Convert the `TutorialMetadata` component to ChakraUI
#8632 
Fix: #8718

Convert TutorialMetadata component to ChakraUI

---

src/components/UpcomingEventsList.tsx

This refactors `UpcomingEventsList` using chakra ui
#8632

refactor(UpcomingEventsList): update to chakra ui styling

---

src/content/desci/index.md

Adding desci.global - global desci events calendar

---

src/data/translation-reports/month/month-data.json

- Update `month-data.json` and `alltime-data.json` with November 2022 stats

update translation acknowledgement leaderboard with November 2022 stats

---

src/content/developers/docs/gas/index.md

Noticed two minor errors as I was reading the docs.
Should probs be **minimum base fee** and 202.7 to match the table.

Update base fee copy on Gas developer docs

---

src/components/Pill.tsx
src/components/TutorialTags.tsx

Migrate component to Chakra UI.
Includes update to `Pill` component to accept incoming Chakra props.
#6374

Refactor: Migrate `TutorialTags` to Chakra UI

---

src/content/developers/docs/consensus-mechanisms/index.md

"Block creation" sections for Proof-of-work and Proof-of-stake were mixed up. I put the right descriptions.

Fix descriptions for consensus mechanisms

---

src/components/BugBountyPoints.tsx

Migrate the `BugBountyPoints` component from emotion to ChakraUI
#8632

Migrate `BugBountyPoints.tsx` to Chakra

---

src/components/Staking/StakingHowSoloWorks.tsx

Migrates `StakingHowSoloWorks` component from `emotion` to `chakra-ui`
#8632

refactor: stakinghowsoloworks to chakra

---

src/components/Staking/StakingGuides.tsx

Migrates `StakingGuides` component from `emotion` to `chakra-ui`
#8632

refactor: stakingguides to chakra

---

src/components/Breadcrumbs.tsx

Implements Chakra's `Breadcrumb` multi-component in the custom `Breadcrumbs` component.
Closes #8772

refactor(breadcrumbs): implement Chakra's `Breadcrumb` component

---

src/content/translations/it/developers/docs/mev/index.md
src/content/translations/it/developers/docs/oracles/index.md
src/content/translations/it/developers/docs/scaling/index.md
src/content/translations/it/developers/docs/scaling/optimistic-rollups/index.md
src/content/translations/it/developers/docs/scaling/plasma/index.md
src/content/translations/it/developers/docs/scaling/sidechains/index.md
src/content/translations/it/developers/docs/scaling/state-channels/index.md
src/content/translations/it/developers/docs/scaling/validium/index.md
src/content/translations/it/developers/docs/scaling/zk-rollups/index.md
src/content/translations/it/developers/docs/standards/index.md
src/content/translations/it/developers/docs/standards/tokens/erc-1155/index.md
src/content/translations/it/developers/docs/standards/tokens/erc-20/index.md
src/content/translations/it/developers/docs/standards/tokens/erc-4626/index.md
src/content/translations/it/developers/docs/standards/tokens/erc-721/index.md
src/content/translations/it/developers/docs/standards/tokens/erc-777/index.md
src/content/translations/it/developers/docs/standards/tokens/index.md

Update Italian (it) Advanced developer docs bucket

Update Italian (it) Advanced developer docs bucket

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

- Lists Nodereal Meganode on nodes-as-a-service page
- [Closes #7400]

Add Nodereal to nodes-as-a-service page [Closes #7400]

---

src/intl/en/page-staking.json
src/pages/staking/index.tsx

- Adds EthStaker Knowledge Base link to the further reading section of `/staking` page
None filed

Add EthStaker knowledge base link

---

src/components/BannerGrid/index.tsx

Migrate the `BannerGrid` component to Chakra UI
#8632

Migrate `BannerGrid` to Chakra

---

src/components/StatsBoxGrid.tsx

Migrate the `StatsBoxGrid.tsx` component to Chakra.
#8632

Migrate `StatsBoxGrid.tsx` to Chakra

---

src/components/FeedbackWidget.tsx

Get current language from the intl context and not from the url to avoid having hydration conflicts.
Fixes #8996

Fix hydration issue on FeedbackWidget

---

src/content/developers/docs/smart-contracts/formal-verification/index.md

I edited the symbolic execution section to make the explanations easier to understand and more accurate. I also added some other tools for formal verification (Mythril and Certora Prover). Perhaps @leonardoalt could help with reviewing the additions?

Revamped symbolic execution section on formal verification page

---

src/components/PageHero.tsx

Migrate the `PageHero` component to Chakra UI
#8632

Migrate `PageHero` to Chakra

---

src/components/FindWallet/WalletPersonasSidebar.tsx

Migrate `WalletPersonasSidebar` to Chakra
#8632

Migrate `WalletPersonasSidebar` to Chakra

---

src/components/TranslationBannerLegal.tsx

Migrate the `TranslationBannerLegal` component from emotion to Chakra.
#8632

migrate `TranslationBannerLegal` to Chakra

---

src/content/developers/docs/scaling/index.md

Add a short section explaining why scaling solutions can't just be stacked on top of each other, inspired by https://vitalik.ca/general/2022/09/17/layer_3.html.

Add section on "layer 3" scaling

---

src/components/EthPriceCard.tsx
src/theme.ts

Migrate the `EthPriceCard` component from emotion to Chakra.
#8632

Migrate `EthPriceCard` component to Chakra

---

src/content/developers/docs/smart-contracts/deploying/index.md

Hey there - I added a new beginner smart contract tutorial as the other ones were made in 2020 and this is one of Alchemy's most popular beginner tutorials based on page views / completions. Also added in links to the node providers. Lmk of any questions, appreciate you reviewing :)

Added a beginner smart contract tutorial

---

src/content/developers/docs/apis/backend/index.md

Hello,
We are a node provider NOWNodes.io.
In our service we provide access to Ethereum node. 
May you list us as one more Ethereum node provider?

Update provider list

---

src/content/security/index.md

solves #8558 
removed "Explore wallets with limits protection" and its associated outdated link

removed outdated link to wallet filter

---

src/data/staking-products.json

[Fixes #8801]
added audit links and bug bounty existing for ankr liquid staking

updated ankr staking info

---

src/data/community-events.json

Eth Porto Update to the community-events.json

---

src/content/translations/nl/dao/index.md
src/intl/nl/page-developers-learning-tools.json
src/intl/nl/page-run-a-node.json

Update Dutch (nl) Use Ethereum bucket

Update Dutch (nl) Use Ethereum bucket

---

src/content/enterprise/index.md

Included Blast in the list of products.

Added Blast

---

src/content/community/get-involved/index.md

Added a new resource to help readers find a job in ethereum tagged projects. https://cryptojobster.com/tag/ethereum/

Added Cryptojobster to help find a job in ethereum

---

src/components/Staking/StakingStatsBox.tsx

migrate the `StakingStatsBox` component to Chakra UI
#8632

migrate the `StakingStatsBox` to Chakra UI

---

src/components/Staking/StakingComparison.tsx

Migrate the `StakingComparison` component to Chakra
#8632

migrate the `StakingComparison` component to Chakra

---

src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md

- superseeds #8727
I edited the text to make it more readable. I didn't make any changes to the actual content, just copyediting.

Copy editing Patricia Merkle Tries page

---

src/components/SideNavMobile.tsx

Migrate the `SideNavMobile` component to Chakra
#8632

Migrate the `SideNavMobile` component to Chakra

---

src/data/execution-bounty-hunters.csv

Adding iosiro to EL bounty hunter list for a vulnerability found

Adding iosiro to EL bounty hunter list

---

src/content/desci/index.md

Adding a great desci article to further reading

---

src/content/developers/docs/frameworks/index.md

Adding a new Ethereum Development Platform :Nodereal

Adding a new Ethereum Development:Nodereal

---

src/components/AdoptionChart.tsx

Migrate the `AdoptionChart` component to Chakra
#8632

Migrate the `AdoptionChart` component to Chakra

---

src/content/community/grants/index.md

Update the following links:
- Removes Layer 2 grants
- Adds new Academic grants

Update grant links

---

src/data/community-events.json

Adds ETH Malaysia event to community event list.

Add ETH Malaysia event

---

src/content/nft/index.md

* I believe this is a typo. Changed 'have' to 'has'. 
* Not related to an open issue.

Fix small typo in index.md [NFT]

---

README.md

Fixes #8867  https://github.com/MrJithil/ethereum-org-website/pull/new/clipboard-readme-file-issues-fix

fixes the extra $ prefix issues on copy #8867

---

src/content/developers/docs/scaling/sidechains/index.md
src/content/translations/fr/developers/docs/scaling/sidechains/index.md

Add Metis Andromeda

---

src/content/about/community-lead/index.md
src/content/about/index.md
src/templates/job.tsx

- Add link to community lead job posting on /about
- Add page for community lead job posting at /about/community-lead
- Add back job.tsx template for posting

Add community lead job posting

---

src/content/developers/docs/nodes-and-clients/index.md

solves #8773 
removed the ropsten and rinkeby and changed Gorli to Goerli

removed ropsten, rinkeby from Networks column

---

src/data/execution-bounty-hunters.csv

Updating Guido's EL score on bounty page

---

src/content/developers/docs/networks/index.md

Updating working faucet list

---

src/content/developers/docs/storage/index.md

Added Storj Github link to docs

Add Storj GitHub link to storage developer docs

---

src/data/community-events.json

Ethereum Züri.ch is a hackathon and a conference, organized by Paralelni Polis’ Institute of Cryptoanarchy, and hosted by University of Zürich and its Blockchain Center. Tracks: Ethereum community, VMs & blockchain execution, Data availability, ZKP, Cryptography & Cyber security.

Add Ethereum Zürich 2023 to the event list

---

src/content/developers/docs/scaling/plasma/index.md

Remove link to EthHub which is being sunset
- Minor edits to aid readability
- Remove EthHub link
#8862

Remove EthHub Link from Plasma developer docs

---

src/content/upgrades/merge/issuance/index.md

- Added details for improved clarity on "Post-merge consensus layer issuance"
- Minor language edits
Fixes #9096

Merge Issuance Page: Minor readability improvements [Fixes #9096]

---

src/content/developers/docs/intro-to-ether/index.md

Minor language changes to make the "Burning Ether" & "Denomination of Ether" sections easier to follow.
Changes in wording for improved clarity
Fixes #8986

Intro To Ether developer docs - Minor readability improvements

---

src/content/translations/de/glossary/index.md
src/content/translations/es/glossary/index.md
src/content/translations/fr/glossary/index.md
src/content/translations/hu/glossary/index.md
src/content/translations/id/glossary/index.md
src/content/translations/it/glossary/index.md
src/content/translations/pl/glossary/index.md
src/content/translations/ro/glossary/index.md
src/content/translations/tr/glossary/index.md
src/content/translations/zh/glossary/index.md

Fix broken link in glossary
#9214

Fix broken link in glossary

---

src/intl/en/page-learn.json
src/pages/learn/index.tsx

Updated podcast list: 
* dropped "into the ether" because podcast has been shut down
* added "The Daily Gwei"
fixes #9089

Updated podcast list: dropped "into the ether", added "The Daily Gwei"

---

src/content/security/index.md

edited for more clarity on hardware wallets

Update information about hardware wallets on security page

---

src/content/contributing/style-guide/index.md

Have followed the format of the others

Add smart contract to style-guide

---

src/content/translations/ja/developers/docs/data-and-analytics/block-explorers/index.md

Fix typo in block-explorers/index.md (ja)

---

src/content/social-networks/index.md

Details: https://github.com/ethereum/ethereum-org-website/issues/8941

Add Farcaster.xyz to the decentralized social networks list

---

src/content/developers/tutorials/uniswap-v2-annotated-code/index.md

Remove dangling code block
This code block seems to be outdated.

Remove dangling code block

---

src/content/social-networks/index.md

Added a great article by Coinbase Ventures explaining the Web3 social stack.

Add article on decentralized social networks

---

src/content/developers/docs/accounts/index.md

Fix broken link that isn't re-directing
None

Fix broken link on accounts developer docs page

---

src/content/bootnodes/index.md
src/content/developers/docs/nodes-and-clients/bootnodes/index.md
src/data/developer-docs-links.yaml
src/intl/en/page-developers-docs.json

Adds a page about bootnodes 
https://twitter.com/mysticryuujin/status/1605022656184561664?s=20&t=k9hoqPiFbileT9EXUiPuwA
cc @MysticRyuujin

src/content/bootnodes: add bootnodes page

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

BlockPI network is a distributed multi-chain acceleration layer solving the RPC requests congestion problem with infinite scalability. The node service from BlockPI is efficient and robust.
Add the node service from BlockPI Network

Update the node service from BlockPI Network

---

src/data/community-meetups.json

Add ETHVenice Meetup

---

src/content/security/index.md

Removing Lastpass due to recent security incidents.
They're also not open-source.

update password managers

---

src/components/MergeArticleList.tsx

Migrate `MergeArticleList.tsx` to Chakra
#8632

Migrate `MergeArticleList.tsx` to Chakra

---

src/components/ShardChainsList.tsx

Migrate `ShardChainsList.tsx` to Chakra
#8632

Migrate `ShardChainsList.tsx` to Chakra

---

src/content/developers/tutorials/deploying-your-first-smart-contract/index.md

For the Remix code explanation they said wrong line numbers to mean a different line. I also add and short explanation of what OOP was.
1. When one pastes the code that the author asks to paste, they explain what this means after, though the wrong lines where mentioned  
2. Generally speaking a person new to Ethereum, with this tutorial is geared towards, does not know that OOP Languages means Object-Oriented Languages so I explained that

Added correct numbers and clarification

---

docs/applying-storybook.md

Fix minor typo

---

docs/applying-storybook.md

Fix spelling error

---

docs/applying-storybook.md

Correct spelling

---

src/content/developers/docs/storage/index.md

I added more details about [Swarm](https://www.ethswarm.org/)

Added Swarm storage system Update index.md

---

src/data/execution-bounty-hunters.csv

Found a DoS vector in one of the clients

Bumping Martin's EL bounty score with 2000 points

---

src/content/developers/tutorials/run-node-raspberry-pi/index.md

Also make device naming more consistent with the above: >> sdxxx

update image name in flash command ethonarm

---

src/pages-conditional/wallets.tsx

Fixes #9210
Replaced the current robot hero image on the [wallets](https://ethereum.org/en/wallets) page with a new hero image from the [find wallets](https://ethereum.org/en/wallets/find-wallet) page.

Replaced hero image on the wallets page with hero image from find wallets page

---

src/data/community-meetups.json

Please link to the issue here: --> https://ethereum.org/en/community/events/

Hash House Medellín

---

src/content/energy-consumption/index.md

* Removed two blank spaces. 
* I noticed this while translating.

Remove blanks in paragraph - Energy Consumption

---

src/content/developers/docs/standards/tokens/erc-1155/index.md

Revise copy and formatting for clarity.
Revise copy and formatting for clarity.
N/A

Update ERC 1155 index.md

---

src/content/staking/withdrawals/index.md

Typo in withdrawals (principle -> principal)

Typo in withdrawals (principle -> principal)

---

src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Missing \ at EOL, otherwise command will error.

Fix missing syntax

---

src/content/developers/tutorials/set-up-web3js-to-use-ethereum-in-javascript/index.md

Hey there, 
I added Moralis and Alchemy as another free option for a hosted node. Also, web3.js is used along with ethers.js today so I clarified the language so that beginning developers would not read the bottom section and think that web3.js is the predominant JS library today as this isn't the case.

Additional free providers + JS library clarification

---

src/data/layer-2/layer-2.json

I do dev rel with aztec. Updating links to docs and the explorer
Updating aztec links

update aztec links

---

src/components/Banners/DismissableBanner.tsx
src/components/Layout.tsx

- Adds a dismissable banner calling out the KZG ceremony

Add a banner linking out to KZG ceremony

---

src/components/Banners/DismissableBanner.tsx

- switch default state of DismissableBanner to avoid render when dismissed

Fix DismissableBanner bug

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

Added the new open source beaconcha.in block explorer to the block explorers and services list.

Added beaconcha.in block explorer

---

src/content/translations/de/developers/docs/ethereum-stack/index.md

- Typo fix
- German translation fix

Ethereum-Stack documentation typo fix

---

src/content/developers/docs/ethereum-stack/index.md

I've added some information and corrected a few grammar mistakes.

Improve the Ethereum Stack Page

---

src/templates/staking.tsx

Remove undefined Roadmap component.

Remove undefined dependency

---

src/pages/contributing/translation-program/acknowledgements.tsx

Migrate the `acknowledgements` page from emotion to Chakra.
#9353

refactor(page): acknowledgements page to Chakra

---

README.md

How we work GitHub

---

src/data/consensus-bounty-hunters.csv

scio found a vulnerability that netted 10,000 points

Adding scio to CL bounty list

---

src/content/guides/how-to-revoke-token-access/index.md

Fix typo in how-to-revoke-token-access/index.md

---

src/content/developers/docs/apis/backend/index.md

GetBlock offers instant API access to more than 50 blockchains including Ethereum

Add GetBlock Node provider 

---

src/content/developers/docs/nodes-and-clients/run-a-node/index.md

fix 2 urls geth doc link

---

src/content/developers/docs/transactions/index.md

Added link to Recursive Length Prefix (RLP) to Ethereum explainer page - https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/

Add link to Recursive Length Prefix (RLP)

---

src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md

Simplify merkle radix tree pseudocode

---

src/pages/upgrades/get-involved/index.tsx

Migrate `upgrades/get-involved` page to Chakra
#9353

Migrate the `upgrades/get-involved` page to Chakra

---

src/content/developers/docs/smart-contracts/testing/index.md

Add missing word

---

src/content/enterprise/index.md

* Remove list of L2s, since we now have better content elsewhere 
* Removed some obsolete/dead enterprise projects and updated others

Update /enterprise content

---

src/content/developers/docs/transactions/index.md

fix typo word 'sequentially'

---

src/content/developers/docs/consensus-mechanisms/pos/index.md

fix typo word 'misbehavior'

---

src/content/developers/docs/smart-contracts/security/index.md

I added Nethermind as a service provider for Smart Contract Audits in Ethereum and Starknet

Update index.md - Adding Nethermind for smart contract services

---

src/data/community-events.json

Hi guys!
Am a Core-contributor for ETHSafari. I just updated the dates and description to the event that we are planning in Kenya for this year from 18 - 24 September.
Let me know if you have any questions.
Thanks!

updated ethsafari event to 2023

---

src/content/contributing/index.md

Fix typo in contributing page

---

src/components/Nav/index.tsx

NavItems visibility@1000px fixed.

---

src/components/InfoBanner.tsx

Fix color in the InfoBanner component.

Fix InfoBanner color

---

src/components/Search/Input.tsx
src/components/Search/index.tsx

Migrate the **Search** component from emotion to Chakra.
#8635

Migrate `Search` component to Chakra

---

src/content/translations/de/developers/docs/oracles/index.md

fix typo in oracles/index.md

---

src/content/developers/docs/networks/index.md

- Adds coinbase.com/faucets to resources for faucet networks

developers/networks - Add links to coinbase.com/faucets

---

src/data/community-events.json

Add ETH Beijing Hackathon
Details: https://github.com/WTFAcademy/ETHBeijing
Website (under construction): https://ethbeijing.com
Add events to https://ethereum.org/en/community/events/

Add ETH Beijing to community events

---

src/data/community-events.json

Add ETHVenice Event

---

src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Somer Esat guide was listed twice. Removed the duplicate.

Remove duplicated line

---

src/content/developers/docs/oracles/index.md

Add Pyth to available Blockchain Oracle List

Add Pyth to available Blockchain Oracle List

---

src/content/roadmap/index.md

Update button copy on roadmap page from 'updates' to 'upgrades'

Update button copy on roadmap page

---

src/content/staking/withdrawals/index.md

- Adds FAQ item on "re-activating" a validator (which cannot be done)
None filed, suggested separately

Add FAQ item to staking withdrawals

---

src/components/Translation.tsx

Pass `i18next` options to `Translation` component to be able to interpolate variables.
```tsx
// render
const variable = 2
<Translation id="test" options={{ variable }} />
// json file
"test": "Hello you have {{variable}} unread message."
```

Interpolate variables in Translation component

---

.github/CODEOWNERS

Add nhsz to CODEOWNERS

---

docs/stack.md

Adds Storybook & Chromatic to the tech stack.

Update tech stack docs

---

src/components/FindWallet/WalletTable.tsx

Came across this file (`WalletTable.tsx`) and noticed a handful of typos; this patches.

[Patch] typos on WalletTable.tsx

---

src/data/community-events.json

Added the ETHSamba Hack community event happening at the end of March 2023
No related issues.

Added ETHSamba Hack Event

---

src/intl/en/page-staking.json

- Made copy present tense to reflect post-Merge Ethereum

Fix energy consumption copy on staking homepage

---

redirects.json

- adds redirects for /upgrades/sharding -> /roadmap/danksharding

redirects old sharding content to roadmap sharding content

---

src/intl/en/page-staking.json

Typo patch

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

Hi there, 
I came across your repository for node as a service provider for ethereum and found that Zeeve is not listed there. I take this opportunity to bring to your attention that Zeeve has been one of the most popular no code web3 platforms for enterprises and has been providing RPC node hosting services. Hereby, i request you to add Zeeve to your directory for Node as a Service. 
 Zeeve is a cloud-based platform for managing and deploying applications. It provides a comprehensive set of features for developers to quickly and easily deploy their applications to the cloud. Zeeve offers a range of features, including automated deployment of   applications to the cloud of your choice, monitoring of applications, automated security and compliance and so on.  
We believe that Zeeve is an …

Request to add Zeeve in Ethereum node as a service repository

---

src/content/developers/tutorials/using-websockets/index.md

Corrected the eth_subscribe method link expire to the appropriate link
Corrected the eth_subscribe method link expire to the appropriate link
None

Corrected the eth_subscribe method link expire to the appropriate link

---

src/content/developers/docs/nodes-and-clients/archive-nodes/index.md
src/content/developers/docs/nodes-and-clients/client-diversity/index.md
src/content/developers/docs/nodes-and-clients/index.md
src/content/translations/it/developers/docs/nodes-and-clients/client-diversity/index.md
src/content/translations/it/developers/docs/nodes-and-clients/index.md
src/content/translations/ja/developers/docs/nodes-and-clients/client-diversity/index.md
src/content/translations/ja/developers/docs/nodes-and-clients/index.md
src/content/translations/pt-br/developers/docs/nodes-and-clients/client-diversity/index.md
src/content/translations/pt-br/developers/docs/nodes-and-clients/index.md
src/content/translations/zh/developers/docs/nodes-and-clients/client-diversity/index.md
src/content/translations/zh/developers/docs/nodes-and-clients/index.md

Akula has been deprecated see [README.md](https://github.com/akula-bft/akula)

Remove Akula from `client-diversity` section

---

docs/deploy-and-review-process.md

- Addresses suggested changes from https://github.com/ethereum/ethereum-org-website/issues/9059 for the deploy and review process
- https://github.com/ethereum/ethereum-org-website/issues/9059

Update deploy and review process

---

src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md

Looks like the sentence was chopped off. Added back '17' with a few grammar tokens.

patricia merkle trie: specify array length

---

src/components/Staking/StakingStatsBox.tsx

We just added ETHSTORE to beaconcha.in. This PR forwards the user to the correct subpage :)

Fix ETH.STORE URL

---

src/components/Banners/BugBountyBanner.tsx
src/pages/bug-bounty.tsx

Adding bug bounty banner for Shapella

Adding bug bounty banner

---

src/data/community-events.json

Include Ethereum Singapore 2023 Event details

update with Ethereum Singapore 2023 event details

---

src/intl/en/page-learn.json

Expanded stablecoins card description to include other forms of value
Fixes #9079

Update stablecoin card description

---

src/components/Nav/Mobile.tsx

- Adds z-index to GlyphIcon
Fixes https://github.com/ethereum/ethereum-org-website/issues/9709

[fix] Close button not working [bug report]

---

src/pages-conditional/what-is-ethereum.tsx

Update data source for `Projects built on Ethereum` in `what-is-ethereum.tsx`

---

src/content/developers/docs/nodes-and-clients/run-a-node/index.md

Add NodeReal as a node service provider. https://nodereal.io
N/A

add NodeReal as a node service provide [Fixes #9470]

---

src/content/glossary/index.md

fixed the Zero Address Term definition
closes #9514

fix zero address content on glossary

---

src/data/community-events.json

{
"title": "Ethereum Rio",
"to": "https://www.ethereumbrasil.com/ethereumrio",
"sponsor": null,
"location": "Museu de Arte do Rio, Rio de Janeiro, Brazil",
"description": "A convergence of creators, builders & thinkers in the most beautiful city in the world.",
"startDate": "2023-03-28",
"endDate": "2023-03-30"
}

Create Ethereum Rio 23

---

src/content/developers/docs/nodes-and-clients/node-architecture/index.md

This PR aims to remove duplicate information found on Validator components in the node comparison table.
None (simple documentation update).

[Documentation] Remove duplicates

---

src/data/community-events.json

Adding ETHDam, a conference and hackathon gathering the best DeFi and Privacy builders in Amsterdam in May 2023.
Add information following the json format.

Adding ETHDam to the community events.

---

src/data/community-events.json

With the success of ETHVN 22 in Ho Chi Minh, we continue to organize ETHVN 23 in Hanoi, Vietnam. We look forward to your support and adding our event to the event list. You can view event information via:
https://www.eth-vietnam.com/
https://docsend.com/view/2hmzyc897bnh9drc
All the best,
ETHVietnam Team.

Need review to add ETHVietnam 2023 event to the event list

---

src/data/community-events.json

This PR cleans the `community-events.json` file from past events
- Removes already finished events, prior to the current date
Fixes #9812

chore: clean up community-events.json file

---

src/data/staking-products.json

- Adds link to Kiln security audits to `staking-products.json`
- Closes #7628

Add Kiln audit documentation link

---

src/content/developers/docs/smart-contracts/testing/index.md

fix broken link source

---

src/pages-conditional/dapps.tsx

this PR removes the duplicate category section in the `Dapps.tsx` page.
Fixes #9772

fix: remove duplicate category selection in Dapps page

---

src/content/community/grants/index.md

Adding Decentraland DAO Grants Program details

Add Decentraland Grants Program

---

src/content/developers/docs/nodes-and-clients/index.md

This PR fixes an old link that currently gives a 404 error.

Fix broken link on "nodes and clients" page

---

src/content/developers/docs/networks/index.md

Added QuickNode faucet under Sepolia and Goerli faucet's list

Adding QuickNode Faucet links

---

src/pages-conditional/dapps.tsx

I feel bad for you looking at the issues tab in this repo :wink:
Fixes #9924

Fixes #9924

---

src/data/externalTutorials.json

- Add devpill.me info to externalTutorials.json
Fixes https://github.com/ethereum/ethereum-org-website/issues/9476

add devpill.me to externalTutorials.json

---

src/data/community-meetups.json

Update Ethereum bogota community meetup

---

src/data/community-events.json

added SpaghettETH II

---

src/data/community-events.json

added sponsors to SpaghettETH

---

src/data/community-events.json

adding ETHMilan to the list

---

src/content/roadmap/scaling/index.md

Fix typo in scaling page

---

src/content/translations/es/developers/docs/standards/tokens/erc-1155/index.md

Corrección de varios errores tipográficos (fixed a few typos).
Corrección de varios errores tipográficos (fixed a few typos).
Corrección de varios errores tipográficos (fixed a few typos).
No issue related

Corrección de varios errores tipográficos

---

src/content/translations/es/developers/docs/standards/tokens/erc-777/index.md

Corrección de dos errores tipográficos (Fixed two typos)
Corrección de dos errores tipográficos (Fixed two typos).
No issue related

Corrección de dos errores tipográficos

---

src/content/contributing/adding-layer-2s/index.md

- Adding mainnet criteria for layer 2 listings to bring in line with other product listings

update layer 2 listing criteria

---

.storybook/manager.js

Updated storybook favicon with Ethereum diamond icon (/src/assets/eth-home-icon.png).
Fixes #9754

Updated storybook favicon

---

src/content/developers/tutorials/yellow-paper-evm/index.md

Fix a typo.

---

src/components/BoxGrid.tsx

fix: inconsistent card background color on Dapps Page

---

src/components/Nav/index.tsx

Adds padding to the devs nav items.

Fix styles in the devs nav

---

src/data/community-meetups.json

Added Web3 Timisoara to community meetups section.
Added a new section to the `community-meetups.json`.

Added Web3 Timisoara to community meetups

---

src/content/desci/index.md

Replaced the main video I submitted a while ago by Juan Benet, with a better, newer one by Juan Benet about the desci movement, going into more depths..

Replaced the main video with a better one

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

- Provided link to Sirato home page and Goerli instance
- Add link to blockchain data concepts for less technical users
N/A

Add Sirato to the list of block explorers.

---

src/content/community/support/index.md

I added the following popular "how to learn web3 dev" resources and courses (all free) - Alchemy University, Chainlink (specifically Patrick Collins' famous 32 hour comprehensive course / video), and Nader Dabit. In full transparency, I work for Alchemy and am submitting this list because these resources consistently receive the most positive feedback from both the crypto community and our developers. Love what you guys do at Ethereum, thank you!

Added "how to build web3" developer resources

---

src/content/desci/index.md

1- Updating Cherubs DAO to Cerebrum DAO
2- Updating the hyperlink of Cherubs DAO to 21 Impact Labs 
3- Adding DeSci Collective project to the list - https://twitter.com/DeSciCollective
https://github.com/ethereum/ethereum-org-website/pull/7096

Updating Cherubs DAO and adding a new project to the list

---

src/content/translations/ja/developers/tutorials/secure-development-workflow/index.md
src/intl/zh/common.json

Fix misspellings of Ethereum in Chinese Simplified and Japanese

Fix misspellings of Ethereum in Chinese Simplified and Japanese

---

src/data/community-events.json

Ethereum Ecuador event, conference in Quito, 15-20 May!

Blockchain Conference in Quito

---

src/data/translation-reports/month/month-data.json

- Update month-data.json with April 2023 data
- Update alltime-data.json with April 2023 data

update translation leaderboard with April 2023 data

---

src/components/Staking/WithdrawalCredentials.tsx

fix: Input layout bug on staking withdrawals page

---

src/components/PageHero.tsx

Fixes the button css by adding overflow: hidden in PageHero.tsx
Fixes #9976

fix: overflow css bug in buttons

---

src/content/developers/docs/oracles/index.md

Fix unreachable link with generic link for chainlink

Fix chainlink reputation link

---

src/content/developers/tutorials/nft-minter/index.md

changed prev. 'Pintata' to 'Pinata'

Update spelling of 'Pinata'

---

src/content/roadmap/future-proofing/index.md

fix image path /roadmap/future-proofing

---

src/content/developers/docs/oracles/index.md

Remove protocols that aren't really active anymore. Websites/Twitter look dead. Code examples use an ancient Solidity version (0.4.x)

Remove inactive oracle protocols

---

src/content/guides/index.md

tweaking introductory text for the guides hub page.

updated guides hub text

---

src/content/developers/docs/scaling/zk-rollups/index.md

Adding Taiko to the list of ZK-rollups for community education and to help promote further contributions in the ZK-EVM space. Also, it is alphabetizing the list.
This is related to this @corwintines comment on this issue: https://github.com/ethereum/ethereum-org-website/issues/9919#issuecomment-1535475343

Add Taiko to list of ZK-rollups under scaling docs

---

src/content/zero-knowledge-proofs/index.md

Fix typo in zero knowledge proofs page

---

src/data/consensus-bounty-hunters.csv

Adding VulnerabilityX to Consensus Bounty Hunters

Adding VulnerabilityX to Consensus Bounty Hunters

---

src/content/developers/docs/consensus-mechanisms/pos/attestations/index.md

fix: remove redundant word

---

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md

Fixed typo, apostrophe & 1st letter of word capital

fix: typos in dev tutorial

---

src/content/developers/docs/scaling/optimistic-rollups/index.md

Hi team, just wanted to replace some outdated terms with new ones. Let me know if there's anything else to do here!

update outdated terms in "optimistic rollups" article

---

src/content/developers/tutorials/reverse-engineering-a-contract/index.md

Removed duplicate word from sentence.

fix redundant word.

---

src/content/developers/docs/design-and-ux/index.md

Update web3 UX page (more links)

---

src/content/roadmap/account-abstraction/index.md

- add erc4337.io to further reading on account abstraction page

add erc4337.io to further reading on account abstraction page

---

src/pages-conditional/dapps.tsx

Fixes an undefined translation function.

Fix undefined function

---

src/pages-conditional/dapps.tsx

Migrate the `src/pages-conditional/dapps.tsx` to Chakra
#9353

refactor (pages-conditional): migrate dapps page to Chakra

---

src/templates/tutorial.tsx

Refactored `src/templates/tutorial.tsx` to use native Chakra UI components instead of Styled Components.
#9353

refactor(templates/tutorials.tsx): replaced styled components w/ Chakra components

---

src/components/EthExchanges/index.tsx
src/components/EthExchanges/use-eth-exchanges.ts

Migrates the `EthExchanges` component to Chakra UI
> 🚨IMPORTANT: This component is impacted by PR #9856 as the select component is converted from react-select to the Chakra component
Part of the 2nd Wave of UI Migration #8632

refactor(EthExchanges): migrate component to Chakra

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

Adds EthVM as a block explorer option

chore: add ethvm to block explorrer link

---

src/content/roadmap/account-abstraction/index.md

hey there -- adding a few recent articles about various aspects of account abstraction. I work at Alchemy and we've gotten lots of views + tons of positive feedback about these articles. Thought this would be of help to EF readers too as web3 in general delves deeper in account abstraction Lmk of any questions, thanks!

Add additional resources about account abstraction

---

README.md
docs/deploy-process.md
docs/review-process.md

- Creates deploy process documentation
- Updates the deploy and review documentation to just be review documentation
- update readme with new documentation

create deploy process docs

---

src/content/guides/how-to-register-an-ethereum-account/index.md

I think "create" is a more appropriate word than "register", even if "register" is in quotation marks.
If we're putting "register" in quotation marks, this means that we don't really mean "register", so why use it at all?
Just my thoughts!

update title of "how to "register" an Ethereum account"

---

src/components/Staking/StakingCommunityCallout.tsx
src/pages/staking/index.tsx
src/templates/staking.tsx

- Adds a gap between sections.
- Migrates `h2`s to `Heading`s
- Removes inner margin from `StakingCommunityCallout` to be set by the parent

Fix spacing issue in the Staking page

---

src/content/decentralized-identity/index.md

Added EAS (Ethereum Attestation Service) to the list of identity projects. EAS has no token and is a public good on Ethereum. Developers can interact with EAS suing our SDK or directly with contracts deployed on Ethereum. Non technical users are able to make schemas and attestations on our attestation explorer https://easscan.org
See more info at https://attest.sh

+ EAS (Ethereum Attestation Service) to identity projects

---

src/pages-conditional/what-is-ethereum.tsx

- Update the link to point more directly to the source
- Change from measuring in T to measuring in B

Update TVS on What is Ethereum page

---

src/content/developers/docs/design-and-ux/index.md

adding more useful resources to the list

More resources to UX docs

---

src/data/community-events.json

adding ETH Montréal

---

src/components/Codeblock.tsx

Migrates `Codeblock.tsx` to Chakra UI.
#8632

Migrate `Codeblock.tsx` to Chakra UI

---

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md

- Add note on Python versions supported

Note on Python version for web3[tester]

---

src/content/developers/docs/gas/index.md

Adding another page from alchemy that focuses on gas cost reduction strategies and helping developers optimize their smart contract applications and reduce gas costs. The page includes code snippets and builds on the information provided in the rest of the Ethereum article but is not quite covered like minimization techniques for users.

Solidity Gas Optimization Techniques for Developers

---

src/content/developers/docs/dapps/index.md

Added Alchemy’s dApp store as I’ve found it to be a useful web directory. It has information about popular dApps and their respective chains. Thought this would help other devs directly view and play around with productionized dApps, enhancing their understanding of the rest of the article.

Link to Popular dApps

---

src/content/developers/docs/standards/tokens/erc-20/index.md

Hey!
I was trying to utilize the Solidity Methods and Events, however, there wasn't further documentation. I found the attached Alchemy link to be extremely useful as it directly enhanced my understanding of this article and understand the functionality of specific methods and events. The link also linked the methods to some useful deployment data structures in Solidity, allowing me to use the functions more easily.

Adding Link to Solidity ERC20 Standard Article

---

src/pages/404.tsx

Migrates the 404 page to Chakra UI.
#9353

Migrate `404.tsx` page to Chakra UI

---

src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

Add DRPC to Nodes as a Service list

---

src/content/translations/it/about/index.md
src/content/translations/it/enterprise/index.md
src/content/translations/it/glossary/index.md
src/content/translations/it/history/index.md
src/content/translations/it/nft/index.md

- Import latest from Crowdin for Italian

Import Italian updates

---

src/data/externalTutorials.json

I think fuzzing & invariant tests are the secret to the success of web3 in the future. So I made some tutorials! 
https://github.com/ethereum/ethereum-org-website/issues/9960
https://github.com/ethereum/ethereum-org-website/issues/9960

added fuzzing tutorial

---

src/data/community-events.json

Cleans up `community-events.json` removing events that have already completed.
None filed

Remove past events from community events

---

src/data/community-events.json

Added ETH Miami to community events

---

src/content/contributing/design/index.md

adding link to design in web3 page

update design contribution page

---

src/content/developers/docs/evm/index.md

add Ethereum Virtual Machine Opcodes Interactive Reference 

---

src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md

Hey there -- I'm updated 3 things to make it most helpful to developers as it's been a while since this tutorial has been edited. I'm from Alchemy and work with the original writer of this tutorial
(1) Rinkeby to Sepolia
(2) Added a link to sending transaction via ethers.js given that this library is increasingly popular
(3) Added in Transact APIs as an option to send more secure and gas-optimized transactions
Lmk of any questions, thanks!

Update to sepolia + add ethers.js option

---

src/templates/docs.tsx

Migrate the `template/docs.tsx` to ChakraUI.
#9353

refactor: template/docs.tsx to chakra

---

src/components/ActionCard.tsx
src/components/EthPriceCard.tsx
src/components/HorizontalCard.tsx
src/pages-conditional/eth.tsx

Migrates the `eth` page to use Chakra UI.
https://github.com/ethereum/ethereum-org-website/issues/9353

Migrate `eth` page

---

src/content/history/index.md

Updated Link Rot on the 2016 DAO Attack

---

src/content/roadmap/danksharding/index.md

This is a small spelling correction for the proto-danksharding explanation.

Fix spelling in proto-danksharding explanation

---

src/content/developers/docs/programming-languages/javascript/index.md

Updated repository link.
Updated information concerning the history of the repository - where it used to be housed, and that it was later merged into the ethereumjs monorepo.

Updated ethereumjs-client information

---

src/data/wallets/wallet-data.ts

Rainbow added hardware wallet support a few months ago, catching up our listing to reflect that
just adding rainbow's hardware wallet support
our learn article as proof: https://learn.rainbow.me/add-a-wallet-from-ledger-to-rainbow

add rainbow hardware wallet support

---

src/data/community-events.json

Ethereum Kuala Lumpur 2023 is a Conference & Hackathon aimed at the objective of promoting the understanding and adoption of Ethereum smart contracts and related technologies.

Add ETHKL to Community Events

---

src/content/translations/fr/desci/index.md
src/scripts/markdownChecker.ts

- Fixes broken Emoji: https://ethereum.org/fr/desci/
- Adds markdown check for valid emoji syntax
- Is there a better way to do this? This solution will still fail if an invalid emoji shortcode is used (e.g. `emoji: ':does-not-exist:'`
- Validating against [the list of emojis](https://github.com/tommoor/react-emoji-render/blob/HEAD/data/aliases.js) seems like overkill

Fix invalid emoji shortcode and add validation to MD checker

---

src/data/staking-products.json

- fixes social media links
- adds EL diversity data. Ethpool uses nethermind as posted [here](https://twitter.com/ethpool_staking/status/1647880237915488257)

Fix social media & EL data

---

src/content/contributing/design/adding-design-resources/index.md
src/content/contributing/design/index.md
src/content/contributing/index.md
src/content/developers/docs/design-and-ux/index.md

Creating listing policies for designer docs

Creating designer docs listing policy

---

src/data/staking-products.json

chore: add audit to eth-docker

---

src/content/developers/docs/smart-contracts/security/index.md

I moved Code4rena as we belong more in the "Smart contract auditing services" than "Bug bounty Platforms"

Change resources category for Code4rena

---

src/intl/cs/common.json

Update Czech (cs) homepage bucket

Update Czech (cs) homepage bucket

---

src/pages-conditional/what-is-ethereum.tsx
src/pages/run-a-node.tsx
src/templates/staking.tsx

Migrates the Run a node page to Chakra UI.
#9353

Migrate `run a node` page

---

src/content/translations/es/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md

"tab completion" reffers to the feature that completes a word by pressing the tab key, and the translation was about the literal translation of "tab" reffering to tabbed windows

Tab completion translation

---

src/pages/run-a-node.tsx

i have changed the style of buttons, the color to default and also the color on hover. 
please let me know if it is meeting your requirements.
Fixes: https://github.com/ethereum/ethereum-org-website/issues/10553#issuecomment-1610217271

Button style changed: Issue ethereum#10553

---

src/content/community/grants/index.md

Added SKALE to the grants page
Added urls for the grants program and SKALE website

Add SKALE Grants Program

---

src/content/developers/tutorials/all-you-can-cache/index.md

fix typo 
didn't open a new issue due to its minor change

Fix typo in all you can cache tutorial

---

src/content/developers/docs/ides/index.md

Added a link to Alchemy's web3 directory page with a list of Ethereum IDEs. As this list changes / gets refreshed almost daily (I work at Alchemy so I see the additions), thought this would be good to link to as a reference to developers looking for an IDE. Lmk of any questions, thanks :)

Updated the list of IDEs

---

src/content/contributing/adding-staking-products/index.md

Updates the product listing criteria to ensure that products/websites that ethereum.org link out to provide accurate and reliable information.

Update staking products listing criteria

---

src/content/developers/docs/accounts/index.md

Added an external link to Understanding Ethereum Accounts by etherscan in the further reading section.
The article on Understanding Ethereum Accounts by etherscan is an added resource to learning more about Ethereum accounts and so I am adding/recommending it here.

updated the further reading section

---

src/content/developers/docs/apis/backend/index.md
src/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

Add chainbase links

---

src/content/translations/fr/developers/docs/accounts/index.md

Little fix on french usage
Little fix on french usage
There's no real issue.

Fix typo in French accounts developer docs

---

src/content/desci/index.md

Added DeSci Nodes and DeSci Labs to the content on the DeSci Page
Changed the reproducibility section to provide tangible examples of reproducible research directly into the section. Additionally added a link to the DeSci Labs website into the list of projects below.

Add DeSci Labs to DeSci page

---

src/content/guides/index.md

changed intro text to better suite the goal of this page

updating guides intro text and removing kernel

---

src/content/guides/how-to-create-an-ethereum-account/index.md
src/content/guides/how-to-use-a-wallet/index.md

Made some changes in the guides folder.
Improved readability and fixed typos.

Content and terminology tweaks in guides

---

src/content/contributing/adding-staking-products/index.md

Made some small changes in the contributing folder to fix some typos.

content and terminology tweaks in contributing

---

src/components/EthExchanges/use-eth-exchanges.ts

Reverts alphabetical order on exchange/wallet listings on /get-eth page, using random sort

Randomize exchange and wallet listing order on /get-eth

---

src/pages/developers/local-environment.tsx

Removes a duplicate object that is not being used in the `developers/local-environment` page.
The object being used in prod should be the correct one (inside the component function block), as it contains converted translations for image alt text.

refactor(local-environment): remove duplicate object

---

src/data/crowdin/excluded-translators.json

- We mistakenly excluded the contributor Saturn Piece from the translators list
- This PR reverses that change

Remove Saturn Piece from excluded-translators.json

---

src/content/energy-consumption/index.md
src/content/enterprise/private-ethereum/index.md

Noted a few small markdown bugs when reviewing latest translation import PRs, patched in this PR.
None filed

Markdown patch

---

src/content/developers/docs/apis/backend/index.md
src/content/translations/zh/developers/docs/apis/backend/index.md

Add BlockPI RPC service in the 'BACKEND API LIBRARIES'
BlockPI network provides high performance and efficient API service for Ethereum developers with a decentralized architecture. Developers can not only  use the public endpoint supported by BlockPI Network, but also create private endpoints and use them for free with monthly free package.
None

Update index with Adding BlockPI RPC service in the 'BACKEND API LIBRARIES'

---

src/content/developers/docs/data-and-analytics/block-explorers/index.md

Added alternative block explorer 

---

src/content/defi/index.md

Made changes in the defi folder to fix some typos and improve readability.

Content and terminology tweaks in defi

---

src/intl/en/page-roadmap-vision.json

One json file is not valid and is breaking the build.
Adds a missing comma in a json file.

Fix translation json file

---

src/templates/use-cases.tsx

- Adds DeSci link to the dropdown navigation for the use case pages
- Fixes spelling typo in the matomo tracking event
None filed, surfaced offline

Add DeSci to use-case menu

---

yarn.lock

After running `yarn install` it creates a difference in the `yarn.lock`. This PR updates it.

Rerun yarn install

---

package.json
src/lambda/calendarEvents.ts
yarn.lock

- Switch from googleapis to googleapis/calendar to reduce bundle size

Hotfix: switch from googleapis to @googleapis/calendar

---

src/data/community-events.json

Fixed typos and specified our event a bit more.
Our event is near, so we adjusted the description to be a bit more precise and fixed typos.

Update text for ETHMunich

---

src/content/developers/docs/consensus-mechanisms/pos/pos-vs-pow/index.md

Edited the introductory index page of PoW vs PoS for easier reading and comprehension.
The introductory page which talked about the use of PoW before the move to PoS, provides some challenges in comprehension by the reader - me. This was due to the wording and so I did a light edit to the wording to make it easy to read.

Edited introduction section of pow vs pos index.md

---

src/content/developers/docs/accounts/index.md

Very small change to accounts page, just deleting introductory sentence that described accounts as a "beginner topic" but then linked out to another page as prerequisite.

minor changes to accounts page

---

src/data/community-events.json

added NAVH  event to community page

---

src/content/developers/docs/smart-contracts/index.md

make description of oracle a bit more clear. removed links to dappsys as they seem out of date. Update to more recent further reading.

minor updates to smart contract page

---

src/data/community-events.json

Add the TUM Blockchain Conference to the community event list. 
Closes #10705

Added TUM Blockchain Conference to community-events.json

---

src/components/Layout.tsx

Fixes [#10806] added condition to setShouldShowSideNav as false
not sure what caused the issue, but since it affects all pages, this works at least as workaround 
[#10806]

[Hotfix] Fixes [#10806] added condition to setShouldShowSideNav as false

---

src/components/Footer.tsx

added a nice little hover animation in the footer social icons 😀
https://github.com/ethereum/ethereum-org-website/assets/74294202/a3bcc94c-f5f3-4c0e-b6a9-827eeac5588b

added hover animation in footer social icons

---

src/content/community/get-involved/index.md

Adds EIP-related links to "Get Involved" page.
CC @dtedesco1 
*N.A.*

Add EIP information to "Get Involved" page

---

src/content/contributing/translation-program/translatathon/index.md

- bold machine translation warning in translatathon page

bold machine translation warning

---

src/components/PageHero.tsx
src/templates/roadmap.tsx

Reset the default margin of `ul` to 0.
Closes #10847

Align button container with text

---

src/content/contributing/translation-program/translatathon/index.md

- `translathon` > `translatathon`
none filed

Spelling typo fix

---

src/content/eips/index.md

Update eips index.md

---

src/content/developers/docs/consensus-mechanisms/pow/mining/index.md

Fixes some dead links to internal pages on `developers/docs/consensus-mechanisms/pow/mining`

fix dead links in mining page

---

src/content/developers/docs/networks/index.md

This PR adds the Chainstack Sepolia and Goerli faucets to the Networks page.

Adds Chainstack faucets to Networks page

---

src/content/developers/docs/apis/backend/index.md

Last examples of 'Available Libraries' section are not well formatted 
Things like asterisk were visible on website.

fix:formatting is broken for "Available libraries" in the last

---

src/content/nft/index.md

The NFT page was very long and repetitious. This update removes a lot of unnecessary content and refocuses the page on a straightforward description of how NFTs work.
Suggest further details about use-cases could be separate subpages in future.

update nft page

---

src/content/developers/docs/apis/json-rpc/index.md

removes long deprecated methods and clarifies some individual client differences.

update json-rpc page

---

src/content/contributing/translation-program/translatathon/index.md

- update translatathon timeline

Update translatathon timeline

---

src/pages-conditional/wallets.tsx

Fixed link redirect on wallet page.
Fixes #10919

Fix: Link to register an ethereum account

---

src/content/nft/index.md

Deleted misplaced dot in NFT site

Fix typo on NFT page

---

src/content/developers/tutorials/develop-and-test-dapps-with-a-multi-client-local-eth-testnet/index.md

Adds a Kurtosis tutorial geared towards helping users spin up and use a local testnet for dApp prototyping and development.
#9929

Add kurtosis tutorial [fixes #9929]

---

src/content/staking/pools/index.md

Not capitalized letter in pooled staking page

Not capitalized letter in pooled staking page

---

src/content/developers/tutorials/a-developers-guide-to-ethereum-part-one/index.md

'w3.isConnected()' through this error:
AttributeError: 'Web3' object has no attribute 'isConnected'
##Suggestion
auto fill/suggestion suggests this instead-
'w3.is_connected()'

code change

---

src/data/community-events.json

Add Ethereum Costa Rica Day

---

src/data/community-events.json

- Lists Devconnect Istanbul under events

Add Devconnect Istanbul event

---

src/content/developers/docs/networks/index.md

Add Testnet Faucet to the Sepolia faucet list.
I created this faucet a few years ago and I recently added Sepolia to it as a way to help give back to other developers who need some testnet Ethereum.

Add Testnet Faucet

---

src/components/TableOfContents/utils.ts
src/templates/static.tsx

Fixes "on this page" dropdown is not working, on mobile #10900

 Fixes "on this page" dropdown is not working, on mobile #10900 

---

src/content/developers/docs/design-and-ux/index.md

adding more useful resources to the designer docs

designer docs adding new research source

---

src/components/Footer.tsx
src/components/HorizontalCard.tsx
src/components/Nav/useNav.ts
src/pages/gas.tsx

Add Gas page

---

src/content/community/get-involved/index.md

fix: stale eip 1 link

---

src/content/community/get-involved/index.md

The earlier link was redirecting the users to a non-existent site. Added the correct link.
Resolves #11011

fix :changed the broken link in eip-1

---

docs/ds-implementation.md

Adds basic guide for the DS implementation epic.
#9546

DS implementation guide

---

src/content/security/index.md

Remove broken link: 4 Ways to Stay Safe in Crypto 
Remove broken link: 4 Ways to Stay Safe in Crypto ,it is in this directory: https://ethereum.org/en/security/#reading-crypto-security
Updated link for common media safety issues. it is necessary to educate users about common media security issues, by understanding these issues, users will know how to keep themselves safe.
https://www.coindesk.com/tech/2021/04/20/4-ways-to-stay-safe-in-crypto/

Remove broken link: 4 Ways to Stay Safe in Crypto

---

src/data/community-events.json

- Fix some location and event typos in community-events.json

Spelling fixes in community-events.json

---

src/content/zero-knowledge-proofs/index.md

The original link is invalid and has been updated to the correct link.
https://ethereum.org/zh/zero-knowledge-proofs/#how-maci-works-with-zk-proofs

Fix broken link: Learn more about MACI

---

src/data/translation-reports/month/month-data.json

- update alltime-data.json and month-data.json for crowdin translator report

September Crowdin report updates

---

src/content/roadmap/statelessness/index.md

Adds small detail about strong statelessness making contract interactions more difficult

minor change to strong statelessness info

---

src/data/community-events.json

Added Pragma New York to events calendar.

Add Pragma New York

---

src/@chakra-ui/gatsby-plugin/components/Table.ts

Removes the `minWidth` style from the base styles of the Table component.
#11145

[Hotfix] fix table style in mobile

---

src/data/community-meetups.json

Add ETHTbilisi

---

src/data/community-events.json

Updated Pragma New York and added Pragma Istanbul

Updated Pragma New York and added Pragma Istanbul

---

src/scripts/crowdin/reports/reportsHelpers.ts

Add tsignore to fix ts error

---

src/content/translations/es/developers/docs/data-and-analytics/block-explorers/index.md
src/content/translations/hu/developers/docs/data-and-analytics/block-explorers/index.md
src/content/translations/pl/developers/docs/data-and-analytics/block-explorers/index.md

- Remove dead links for medalla 
Fixes: https://github.com/ethereum/ethereum-org-website/issues/9763

remove medalla links

---

src/content/contributing/index.md

Added info on GitPOAP and it's procedure to claim. Source as per official discord server.

Updated info about GitPOAPs

---

README.md

An info regarding GitPOAP have been added., as sourced from official discord server.

Updated info about POAPs

---

src/content/decentralized-identity/index.md

Links to learning resources (White Papers), a community, a project (Opens-Source, working across ecosystems) and an explainer/demo video to help developers get started with building.

Update index.md - add link to resource in project, article, video and community section

---

src/content/developers/docs/oracles/index.md

**TL,DR** mostly stylistic edits, trying to make sentences punchier and easier to read. A few disambiguating header changes as well.
Nce page! Read through it today and I think we can do some work to get it more in line with the [Ethereum style guide](https://ethereum.org/en/contributing/style-guide/), e.g. "Use active voice and clear, concise sentences that are easy to follow." Tried to implement this to the best of my ability, feel free to discard changes you don't like. THanks!

Update oracles page

---

src/content/refi/index.md

Fixed missing letter in ReFi

---

src/content/staking/pools/index.md
src/content/staking/saas/index.md
src/content/staking/solo/index.md

- Lists [staking.directory](https://www.staking.directory) in further reading for each staking category page
- Provides additional independently curated third-party list of staking products for users to explore

Add staking.directory to staking category pages

---

src/@chakra-ui/gatsby-plugin/semanticTokens.ts

Fix on color to match the DS.
cc @nloureiro

Fix dark color for `primary.visited`

---

src/data/community-events.json

Update date Ethereum Costa Rica Day

---

src/content/translations/pt/decentralized-identity/index.md
src/content/translations/pt/defi/index.md
src/content/translations/pt/desci/index.md
src/content/translations/pt/refi/index.md
src/content/translations/pt/smart-contracts/index.md
src/content/translations/pt/social-networks/index.md

- Portuguese content buckets (Use cases)

Portuguese content buckets (Use cases)

---

src/data/community-events.json

I've included the ETHIndia 2023 event on the community events page.

Add ETHIndia 2023

---

src/content/developers/docs/scaling/plasma/index.md

The links are broken and removed.

Fixed broken links for example projects for plasma doc

---

src/@chakra-ui/gatsby-plugin/styles.ts

Set the `body` font size to `md`.

Fix default font size

---

src/content/translations/sl/nft/index.md

- Revert a Slovenian header on `/nft` that reverted to English

Patch reversion to English

---

src/components/Banners/Implementations/WritersCohortBanner.tsx

- Adds _visited={{}} to override visited style in WritersCohortBanner

remove visited style on Link in WritersCohortBanner

---

src/pages-conditional/wallets.tsx

- Remove unnecessary font size styles 
Fixes https://github.com/ethereum/ethereum-org-website/issues/11371

Font size issue on /wallets/#sim page

---

src/data/community-events.json

I've excluded the events that have already been completed from the community-events.json file.

Remove past events from community-events.json

---

src/content/developers/docs/design-and-ux/index.md

Fixed in-page navigation on Design and UX in web3 page.
Fixes #11402

Fixed in-page nav

---

src/content/community/language-resources/index.md

removed dead link in czech section

removing dead link

---

src/data/WalletSimulatorData.tsx

Fix typo in #11467
Close #11467

chore: account create text typo

---

src/@chakra-ui/gatsby-plugin/styles.ts

Updates fonts rendered for mono text, such as code blocks.
[Originally called out in discord chat](https://discord.com/channels/714888181740339261/727898649006309377/1159170613282340904)

style(theme): update font styling for mono text

---

src/content/contributing/adding-exchanges/index.md

Updates listing policy to require a dedicated page containing up-to-date information on the exchange's geographical restriction
None

Update adding exchanges listing policy

---

src/pages-conditional/dapps.tsx

Update Lido's link to point to the valid site.
Related issue: #11528

Fix Lido URL in "Explore dapps"

---

src/content/developers/docs/scaling/optimistic-rollups/index.md

fixed the broken link

---

src/content/community/code-of-conduct/index.md

Fix minor typo
minor typo found in index.md

fix: typo index.md

---

src/content/dao/index.md
src/content/decentralized-identity/index.md
src/content/deprecated-software/index.md
src/content/desci/index.md

This pull request includes minor copy edits to improve the wording and correct grammatical issues in various sections of the documentation. The changes aim to enhance readability and clarity for readers.
Four main corrections were made across the documentation:
1. **Refinement of Wording in Decentralized Science Section**
- **File:** src/content/desci/index.md
- **Change:** Simplified the language to remove redundancy in the description of data access within decentralized science.
2. **Article Correction in DeFi Insurance Protocol Description**
- **File:** src/content/deprecated-software/index.md
- **Change:** Fixed the use of the indefinite article 'an' to 'a' before 'DeFi insurance protocol.'
3. **Grammar Fix in Decentralized Identity Section**
- **File:** …

Improve Wording and Grammar in Docs

---

src/content/translations/id/roadmap/statelessness/index.md
src/content/translations/zh-tw/roadmap/statelessness/index.md
src/content/translations/zh/developers/docs/nodes-and-clients/archive-nodes/index.md

- Run `yarn markdown-checker` and fix any outstanding issues

Nov 6 markdown-checker

---

src/intl/en/glossary.json

Corrects link in re-entrancy attack term
Would resolve https://github.com/ethereum/ethereum-org-website/issues/11582 if merged

fix: Corrects Re-entrancy attack link error

---

src/intl/en/page-bug-bounty.json

Added c-kzg-4844 and go-kzg-4844 to be included in the bug bounty program
N/A

Add c-kzg-4844 and go-kzg-4844 to bug bounty program

---

src/content/community/research/index.md
src/content/translations/es/community/research/index.md
src/content/translations/tr/community/research/index.md
src/content/translations/zh-tw/community/research/index.md

hotfix out biastek

---

src/content/translations/id/glossary/index.md
src/content/translations/id/history/index.md
src/content/translations/id/roadmap/statelessness/index.md
src/content/translations/id/whitepaper/index.md
src/content/translations/zh-tw/roadmap/statelessness/index.md
src/content/translations/zh/developers/docs/nodes-and-clients/archive-nodes/index.md

- Nov 6 Indonesian (Whitepaper, Learn pages 2)

Nov 6 Indonesian (Whitepaper, Learn pages 2)

---

src/content/translations/id/roadmap/statelessness/index.md
src/content/translations/ms/whitepaper/index.md
src/content/translations/zh-tw/roadmap/statelessness/index.md
src/content/translations/zh/developers/docs/nodes-and-clients/archive-nodes/index.md

Nov 6 Malay (Whitepaper)

---

src/content/translations/id/roadmap/statelessness/index.md
src/content/translations/sr/decentralized-identity/index.md
src/content/translations/sr/defi/index.md
src/content/translations/sr/desci/index.md
src/content/translations/sr/refi/index.md
src/content/translations/sr/smart-contracts/index.md
src/content/translations/sr/social-networks/index.md
src/content/translations/zh-tw/roadmap/statelessness/index.md
src/content/translations/zh/developers/docs/nodes-and-clients/archive-nodes/index.md

Nov 6 Serbian (Use cases) 

---

src/content/translations/es/developers/docs/apis/backend/index.md
src/content/translations/es/developers/docs/apis/javascript/index.md
src/content/translations/es/developers/docs/apis/json-rpc/index.md
src/content/translations/es/developers/docs/data-and-analytics/block-explorers/index.md
src/content/translations/es/developers/docs/data-and-analytics/index.md
src/content/translations/es/developers/docs/development-networks/index.md
src/content/translations/es/developers/docs/ethereum-stack/index.md
src/content/translations/es/developers/docs/frameworks/index.md
src/content/translations/es/developers/docs/ides/index.md
src/content/translations/es/developers/docs/programming-languages/dart/index.md
src/content/translations/es/developers/docs/programming-languages/delphi/index.md
src/content/translations/es/developers/docs/programming-languages/dot-net/index.md
src/content/translations/es/developers/docs/programming-languages/golang/index.md
src/content/translations/es/developers/docs/programming-languages/index.md
src/content/translations/es/developers/docs/programming-languages/java/index.md
src/content/translations/es/developers/docs/programming-languages/javascript/index.md
src/content/translations/es/developers/docs/programming-languages/python/index.md
src/content/translations/es/developers/docs/programming-languages/ruby/index.md
src/content/translations/es/developers/docs/programming-languages/rust/index.md
src/content/translations/es/developers/docs/storage/index.md
src/content/translations/id/roadmap/statelessness/index.md
src/content/translations/zh-tw/roadmap/statelessness/index.md
src/content/translations/zh/developers/docs/nodes-and-clients/archive-nodes/index.md

- Nov 6 Spanish (Docs - tech stack pages)

Nov 6 Spanish (Docs - tech stack pages)

---

src/content/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit/index.md
src/content/developers/tutorials/erc20-with-safety-rails/index.md
src/content/developers/tutorials/guide-to-smart-contract-security-tools/index.md
src/content/developers/tutorials/hello-world-smart-contract-fullstack/index.md
src/content/developers/tutorials/hello-world-smart-contract/index.md
src/content/developers/tutorials/how-to-mint-an-nft/index.md

This pull request addresses a series of minor but important typographical and grammatical corrections across multiple tutorial documents. These changes are aimed at improving the readability and accuracy of the documentation, ensuring a more seamless and professional experience for users.
1. **Tutorial: How to Mint an NFT**
- Commit: 41bdfc79da05038e4c20085b4043db9df8fa2a74
- Corrected the possessive form of "NFTs" for grammatical accuracy.
2. **Tutorial: Hello World Smart Contract (Fullstack)**
- Commit: ce26b15cc63c2ac2e0bd3d9423b7aba03d50063a
- Fixed a typo in Step 4: Changed "Nopte" to "Note" in the "Add ether from a Faucet" section.
3. **Tutorial: Hello World Smart Contract**
- Commit: 1542cd1fbb8b4ae8d1cb2b8294036c079ceed161
- Corrected a typo in Step 4: Separated 'oursmart' into …

Documentation Fixes: Typographical and Grammatical Corrections in Tutorials

---

src/components/LeftNavBar/index.tsx
src/pages/learn/index.tsx
src/pages/staking/index.tsx
src/templates/event.tsx
src/templates/roadmap.tsx
src/templates/staking.tsx
src/templates/upgrade.tsx
src/templates/use-cases.tsx

Uses style props to hide the LeftNavBar instead of using `Show/Hide` components that completely mount or unmount the component.
This issue was mentioned on [Discord](https://discord.com/channels/714888181740339261/727898649006309377/1172227183100580040).

Fix LeftNavBar layout shift

---

src/content/developers/docs/apis/backend/index.md
src/content/developers/tutorials/erc20-with-safety-rails/index.md

fix typos:  
in src/content/developers/docs/apis/backend/index.md
in src/content/developers/tutorials/erc20-with-safety-rails/index.md

docs: fix typos

---

src/content/developers/tutorials/how-to-use-echidna-to-test-smart-contracts/index.md
src/content/developers/tutorials/how-to-view-nft-in-metamask/index.md
src/content/developers/tutorials/learn-foundational-ethereum-topics-with-sql/index.md
src/content/developers/tutorials/reverse-engineering-a-contract/index.md

This pull request aims to improve the clarity, grammar, and overall quality of the Ethereum tutorial documentation. It includes a series of minor yet impactful changes to various tutorials. The specific updates are as follows:
1. **Fix Typo in Reverse-Engineering Tutorial:** A typographical error has been corrected, changing 'up to data opcode table' to 'up to date opcode table'.
2. **Grammar Improvement in Foundational Ethereum Topics Tutorial:** Enhanced grammar, particularly in the section discussing resources for data analysts, making the content more accessible and professional.
3. **Typographical Correction in NFT Viewing Tutorial:** Fixed a typographical error in the tutorial's description field for better clarity.
4. **Clarity Enhancement in Smart Contract Testing Tutorial:** …

Documentation Improvements in Ethereum Tutorials

---

src/data/community-events.json

[data] fix typo: community events

---

src/intl/en/page-staking.json

Missing word
staking chosen -> staking is chosen

Fix grammar typo

---

src/components/TranslationLeaderboard.tsx

- Lowercased user data for case-insensitive checks
- Added 'Aco-' pattern recognition to filtering logic
- Streamlined data sorting and filtering into a unified function
#11711

Fix leaderboard filter (Fixes #11711)

---

src/content/developers/docs/design-and-ux/index.md

fixing broken link and adding few new links

Update designer docs

---

package.json
src/components/YouTube.tsx
yarn.lock

Implements [react-lite-youtube-embed](https://www.npmjs.com/package/react-lite-youtube-embed) as a privacy preserving means of loading YouTube embeds

Implement privacy-preserving react-lite-youtube-embed

---

src/templates/staking.tsx

Add translation in staking dropdown options. 
Fixes #11388

add translation in staking dropdown

---

.gitignore

Add .crowdin to .gitignore

---

src/data/community-events.json

Adding a community event organised by Gnosis

Updated community-events.json

---

docs/translation-program.md
public/content/contributing/translation-program/how-to-translate/index.md
public/content/contributing/translation-program/index.md
public/content/translations/de/contributing/translation-program/how-to-translate/index.md
public/content/translations/de/contributing/translation-program/index.md
public/content/translations/es/contributing/translation-program/index.md
public/content/translations/fr/contributing/translation-program/how-to-translate/index.md
public/content/translations/fr/contributing/translation-program/index.md
public/content/translations/id/contributing/translation-program/index.md
public/content/translations/it/contributing/translation-program/how-to-translate/index.md
public/content/translations/it/contributing/translation-program/index.md
public/content/translations/ja/contributing/translation-program/index.md
public/content/translations/pt-br/contributing/translation-program/how-to-translate/index.md
public/content/translations/pt-br/contributing/translation-program/index.md
public/content/translations/sl/contributing/translation-program/index.md
public/content/translations/tr/contributing/translation-program/how-to-translate/index.md
public/content/translations/tr/contributing/translation-program/index.md
public/content/translations/zh/contributing/translation-program/index.md

- Fixes translation program invite link

change translation program invite link

---

public/content/contributing/design/index.md

Update broken Discord link

---

public/.well-known/matrix/server
public/.well-known/security.txt

Adds missing files after the NextJS migration related to Matrix federation.

[HOTFIX] Add matrix federation files back

---

public/content/developers/docs/scaling/index.md

Added an article that explains how Ethereum rollups derive security from the base layer via on-chain data availability.

Add resource to further reading section of scaling page

---

public/content/developers/docs/data-availability/index.md

Added an article that explores the relationship between data availability and security/decentralization of rollups and other off-chain scaling solutions (among other things) to the further reading section.

Add article on data availability + rollups

---

src/data/community-events.json

Update community-events.json with Devcon 7 info

---

package.json
src/scripts/crowdin-import.ts
src/scripts/markdownChecker.ts

- Adds `crowdin-clean`, `crowdin-import`, and `markdown-checker` into package.json
- Adds crowdin-import.ts script modified to work in the NextJS repo
- Adds functionality to markdownChecker for links missing text (ex: [](link address)) brought up here https://discord.com/channels/714888181740339261/727898649006309377/1196408650269466694

Add and edit scripts for translation imports in NextJS repo

---

src/data/community-events.json

we announced recently - adding it to ethereum.org events calendar with this PR

Add ETHBerlin04

---

package.json
yarn.lock

Adds the `chromatic` dep + script that was deleted in the Next migration.

Add `chromatic` back to the project

---

src/intl/it/page-what-is-ethereum.json

fix: merge date on /it/what-is-ethereum

---

src/data/community-events.ts

This change adds EthCC to the Community Events page: https://ethereum.org/community/events
https://github.com/ethereum/ethereum-org-website/issues/12085

add ethcc to upcoming events

---

public/content/translations/fr/web3/index.md

Typo : "NTF" instead of "NFT"

---

src/pages/index.tsx

I believe this link is intended to go to the dev portal, not the dapps page
None 😄

fix: homepage link to developers page

---

src/lib/utils/translations.ts

- Add community namespace to gas page for broken translations

Add missing namespace for gas page translations

---

public/content/contributing/translation-program/index.md

Update year for the number of words translated from 2022 to 2023

Update year on Translation program page

---

public/content/developers/docs/design-and-ux/index.md

Safe Design system to the list on the Design docs

 Safe Design system to the list on the Design docs

---

public/content/contributing/adding-desci-projects/index.md

fixed punctuation errors and improved sentence structure for better clarity

---

src/pages/stablecoins.tsx

I changed the broken USDC link that routed to a 404 error to the correct link specified in the issue 
issue #12077: https://github.com/ethereum/ethereum-org-website/issues/12077

fixed the broken link to correct one stated in issue: Update USDC link on stablecoin.tsx #12077

---

src/components/FeedbackWidget.tsx
src/intl/en/common.json

- Fixes build-breaking error for missing `t` function

fix: initialize useTranslation

---

public/content/developers/docs/mev/index.md

Change miner to maximal in MEV

Change miner to maximal in MEV

---

src/intl/az/page-dapps.json
src/intl/en/page-dapps.json
src/intl/es/page-dapps.json
src/intl/fr/page-dapps.json
src/intl/hu/page-dapps.json
src/intl/tr/page-dapps.json
src/intl/zh/page-dapps.json

Removes unused JSON strings for an dapp that was removed in a different PR (#12143)
#12143

Remove Skiff i18n JSON strings

---

src/components/LanguagePicker/MenuItem.tsx

Adjusts MenuItem styling per design, cc: @nloureiro 
- https://deploy-preview-12136--ethereumorg.netlify.app/

LanguagePicker style adjustments

---

public/content/developers/docs/apis/json-rpc/index.md
public/content/translations/de/developers/docs/apis/json-rpc/index.md
public/content/translations/es/developers/docs/apis/json-rpc/index.md
public/content/translations/fr/developers/docs/apis/json-rpc/index.md
public/content/translations/hu/developers/docs/apis/json-rpc/index.md
public/content/translations/it/developers/docs/apis/json-rpc/index.md
public/content/translations/ja/developers/docs/apis/json-rpc/index.md
public/content/translations/pt-br/developers/docs/apis/json-rpc/index.md
public/content/translations/tr/developers/docs/apis/json-rpc/index.md
public/content/translations/zh/developers/docs/apis/json-rpc/index.md

Fix typo(keccack to keccak)

---

src/components/DevconGrantsBanner.tsx

- Remove direct usage of `react-emoji-render`; replace with internal `Emoji` component
- Update for latest repo code conventions

Devcon banner component update

---

public/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

Adding Amazon Managed Blockchain for Ethereum.
This simple PR adds AWS Ethereum nodes service.

Update Nodes-as-a-Service list

---

src/pages/dapps.tsx

- Removes potentially malicious site
Fixes #12220

[Hotfix] - Remove multichain

---

public/content/developers/tutorials/erc20-annotated-code/index.md

Fix markdown code format

---

public/content/developers/tutorials/erc20-annotated-code/index.md

Fixing typo

---

src/components/Breadcrumbs/index.tsx
src/components/FeedbackWidget.tsx
src/data/developer-docs-links.yaml
src/hooks/useSurvey.ts
src/layouts/RootLayout.tsx
src/lib/utils/i18n.ts
src/lib/utils/translations.ts
src/lib/utils/url.ts

**Target branch: default-locale-prefix (#12134)**
- Update paths for new `trailingSlash=true` rule
- Adds `addSlashes` util to `url.ts` which forces a leading and trailing slash.
- Updates `translations.ts` to have leading and trailing slashes on all paths. Runs the path through `addSlashes` first to ensure all paths match this pattern\*.
- \*Alternatively, we can update these in each `getStaticProps` to follow that pattern
- https://github.com/ethereum/ethereum-org-website/pull/12134#issuecomment-1948881490

Update paths for trailingSlash rule

---

public/content/developers/tutorials/erc20-with-safety-rails/index.md
public/content/translations/fr/developers/tutorials/erc20-with-safety-rails/index.md
public/content/translations/it/developers/tutorials/erc20-with-safety-rails/index.md
public/content/translations/pt-br/developers/tutorials/erc20-with-safety-rails/index.md
public/content/translations/tr/developers/tutorials/erc20-with-safety-rails/index.md

Fix dead link (OpenZeppelin Contracts Wizard)
Also fixing 2 minor typos

Fix dead link (OpenZeppelin Contracts Wizard)

---

public/content/web3/index.md

Explain ENS in full

---

docs/deploy-process.md

This PR adds more detaiils about the Community QA process we implement during our deploy process

docs: adds more community QA process details

---

public/content/developers/docs/apis/backend/index.md
public/content/developers/docs/frameworks/index.md

Fix discord links

---

src/components/PageMetadata.tsx

Sort inputs to fix build failures

chore: sort imports

---

public/content/translations/es/developers/tutorials/erc20-with-safety-rails/index.md

One of the earlier PRs missed this dead link, so updating to reflect the latest working link

fix: cleanup dead link

---

public/.well-known/security.txt

Updates expired security.txt which is causing PGP key links to 404
[Discord discussion](https://discord.com/channels/420394352083337236/420406791936147466/1210601520308166686)

Update outdated Security.txt

---

src/intl/ar/page-languages.json
src/intl/sl/common.json

Removes empty string translations that make the lang picker to fail.

Fix empty translations

---

src/components/PageMetadata.tsx

Adds x-default hreflang. Point it to the default locale path.

Add x-default hreflang

---

public/_redirects

Fix redirect loop for mining page

Fix mining redirects

---

src/data/NetworkUpgradeSummaryData.ts

- change dencun time from 1am to 1pm

[hotfix] change time for dencun from 1am to 1pm

---

public/content/developers/docs/scaling/zk-rollups/index.md

Updated the name of the project from "Applied ZKP" to it's current name "zkEVM".

Update name of zkEVM project

---

src/data/community-meetups.json

Added Eth·CO Eje Cafetero Meetup
Added Eth·CO Caribe Meetup
Added Eth·CO Medellin Meetup
Added Eth·CO Cali Meetup
Added Eth·CO Arauca Meetup

Added 5+ communities from Colombia on community-meetups.json

---

src/data/externalTutorials.json

Took a couple months to give new security researchers the exact path they need to get into web3, and EVERYONE has been asking me to make it easier to digest than 32 hours on YT, so we made this course! 
I'd love to add it to the Ethereum org website if you'll have it! It's on our new platform, which is going to be free and open sourced forever. 
I didn't make a related issue this time (again) I'm happy to do so if you'd like!
I made a tweet thread to explain the course. Happy to put more information here if this isn't enough! 
https://twitter.com/PatrickAlphaC/status/1735011515932012684

added security course

---

public/content/developers/docs/blocks/index.md

Fix typo in block document

---

public/content/translations/pl/staking/pools/index.md
src/intl/pl/page-staking.json

Fixed some weird Polish translations that were nowhere to be found on Crowdin.

Fix staking pools Polish translation

---

public/content/translations/fr/developers/docs/smart-contracts/languages/index.md

correct one word in fr/developers/docs/smart-contracts/languages/index.md

---

src/intl/en/page-layer-2.json

Fix Ethereum typo on layer 2 page

---

src/data/externalTutorials.json

I added "Learn EVM Opcodes Series"
- Closes #12250

Add opcode tutorials to externalTutorials.json [Closes #12250]

---

src/data/execution-bounty-hunters.json

Add BlockTrident to execution bounty hunters

Add BlockTrident to execution bounty hunters

---

public/content/developers/docs/nodes-and-clients/index.md

- Add information for EthereumJS to nodes-and-clients page
- Add `beta` tag
Fixes: https://github.com/ethereum/ethereum-org-website/issues/8698

Add EthereumJS client as an execution client

---

.github/workflows/issue-triage-label.yml
docs/github-issue-triage-process.md

Small refactor to update the `needs-triage` GitHub label to `needs triage 📥`

Refactor: update "needs triage 📥" GitHub label

---

public/content/developers/docs/smart-contracts/security/index.md

Adds:
- Useful related guides:  Fuzzing and oracles manipulation guide
- New resources: Cyfrin Updraft smart contract auditing and security course
- New security tool: Aderyn

Adds useful links/resources to dev docs smart-contract/security page

---

src/data/community-events.json

Add   Road to DEVCON: Zero-Knowledge Proofs Unveiled

Add:  Road to DEVCON: Zero-Knowledge Proofs Unveiled

---

public/content/developers/docs/programming-languages/rust/index.md
public/content/translations/de/developers/docs/programming-languages/rust/index.md
public/content/translations/es/developers/docs/programming-languages/rust/index.md
public/content/translations/fr/developers/docs/programming-languages/rust/index.md
public/content/translations/hu/developers/docs/programming-languages/rust/index.md
public/content/translations/id/developers/docs/programming-languages/rust/index.md
public/content/translations/it/developers/docs/programming-languages/rust/index.md
public/content/translations/ja/developers/docs/programming-languages/rust/index.md
public/content/translations/pl/developers/docs/programming-languages/rust/index.md
public/content/translations/pt-br/developers/docs/programming-languages/rust/index.md
public/content/translations/ro/developers/docs/programming-languages/rust/index.md
public/content/translations/tr/developers/docs/programming-languages/rust/index.md
public/content/translations/zh/developers/docs/programming-languages/rust/index.md

Reference to the latest OASIS API version.

Update oasis_std link to reference latest version on `/rust` page

---

public/content/developers/docs/smart-contracts/security/index.md

- Close italics
- Remove extra whitespace line

fix: markdown syntax

---

public/content/translations/az/decentralized-identity/index.md
public/content/translations/az/defi/index.md
public/content/translations/az/desci/index.md
public/content/translations/az/refi/index.md
public/content/translations/az/smart-contracts/index.md
public/content/translations/az/social-networks/index.md

Azerbaijani import

---

public/content/contributing/design/index.md

Corrected typos regarding capitalization on Design Contribution page
Corrected typos regarding capitalization on Design Contribution page
In addition to this PR https://github.com/ethereum/ethereum-org-website/pull/12626

Typo: Corrected typos regarding capitalization on Design Contribution page

---

src/data/community-meetups.json

added regular Prague web3 dev meetup

Update community-meetups.json added Prague meetup

---

public/content/developers/docs/nodes-and-clients/run-a-node/index.md

Under Docs - Run a node - Updating clients section, protocol announcement subscription link is updated.
#12627

Update protocol announcement subscription link [Fixes #12627]

---

src/data/externalTutorials.json

- Add external Alchemy tutorial
- Closes #8299

feat: add external alchemy tutorial [Closes #8299]

---

.github/labeler.yml

Updates labeler to match latest label changes on GitHub
- Uses emoji characters for labels
- Updates label for `needs review 👀`

refactor: use emojis for labels

---

src/pages/bug-bounty.tsx

Adjusting rendering of translation to let the href links render correctly, thanks to @wackerow for the guidance
- Fixes #12599

fix: Corrects rendering of links in bug-bounty page

---

public/content/decentralized-identity/index.md

Masca is an open source decentralized identity wallet that enables users and developers to leverage DIDs and VCs in the dapps that wants to utilize decentralized identity for identity management.

feat: add masca to decentralized identity

---

public/content/developers/docs/programming-languages/rust/index.md

Adds a list of projects written in Rust in the Ethereum ecosystem.

feat: add awesome ethereum rust list

---

src/components/UpgradeTableOfContents.tsx

Fixes an incorrect value used for the `mb` styleprop.

Fix ToC items space

---

public/content/developers/docs/dapps/index.md
public/content/developers/docs/frameworks/index.md
public/content/translations/de/developers/docs/dapps/index.md
public/content/translations/de/developers/docs/frameworks/index.md
public/content/translations/es/developers/docs/dapps/index.md
public/content/translations/es/developers/docs/frameworks/index.md
public/content/translations/fa/developers/docs/dapps/index.md
public/content/translations/fr/developers/docs/dapps/index.md
public/content/translations/fr/developers/docs/frameworks/index.md
public/content/translations/hu/developers/docs/dapps/index.md
public/content/translations/hu/developers/docs/frameworks/index.md
public/content/translations/id/developers/docs/dapps/index.md
public/content/translations/id/developers/docs/frameworks/index.md
public/content/translations/it/developers/docs/dapps/index.md
public/content/translations/it/developers/docs/frameworks/index.md
public/content/translations/ja/developers/docs/dapps/index.md
public/content/translations/ja/developers/docs/frameworks/index.md
public/content/translations/pl/developers/docs/frameworks/index.md
public/content/translations/pt-br/developers/docs/dapps/index.md
public/content/translations/pt-br/developers/docs/frameworks/index.md
public/content/translations/ro/developers/docs/dapps/index.md
public/content/translations/ro/developers/docs/frameworks/index.md
public/content/translations/ru/developers/docs/dapps/index.md
public/content/translations/tr/developers/docs/dapps/index.md
public/content/translations/tr/developers/docs/frameworks/index.md
public/content/translations/zh-tw/developers/docs/dapps/index.md
public/content/translations/zh/developers/docs/dapps/index.md
public/content/translations/zh/developers/docs/frameworks/index.md

fix: update Scaffold-ETH link

---

src/components/Nav/Menu/useNavMenu.ts
src/lib/utils/keyboard.ts

Checks for modifier keys before executing numerical keyboard shortcuts for menu items
Prevents hijacking other common keyboard shortcuts that use modifier keys such as Ctrl/Cmd/Shift etc

Keyboard shortcut fix

---

public/content/developers/docs/consensus-mechanisms/pos/keys/index.md
public/content/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/dagger-hashimoto/index.md
public/content/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/index.md
public/content/developers/tutorials/deploying-your-first-smart-contract/index.md
public/content/developers/tutorials/hello-world-smart-contract-fullstack/index.md
public/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md
public/content/roadmap/secret-leader-election/index.md
src/intl/en/glossary.json

This PR fixes some errors and typos across different files
No related issue, these errors were reported in Crowdin as mistakes in the source

Fix some errors and typos across files

---

public/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md

Make the sample code a bit simpler.
Simplified the redundant code
https://github.com/ethereum/ethereum-org-website/issues/12720

Update patricia merkle trie sample code

---

public/content/developers/docs/design-and-ux/index.md
public/content/translations/es/developers/docs/design-and-ux/index.md
public/content/translations/fr/developers/docs/design-and-ux/index.md
public/content/translations/hu/developers/docs/design-and-ux/index.md
public/content/translations/it/developers/docs/design-and-ux/index.md
public/content/translations/ja/developers/docs/design-and-ux/index.md
public/content/translations/tr/developers/docs/design-and-ux/index.md
public/content/translations/zh/developers/docs/design-and-ux/index.md

This article https://ethereum.org/ja/developers/docs/design-and-ux/
[Web3 needs more UX Researchers and Designers] (https://akasha.org/blog/2022/10/11/akasha-conversation-09-web3-ux-researchers-and-designers) is no longer available.
Changed to this link
https://blog.akasha.org/akasha-conversations-9-web3-needs-more-ux-researchers-and-designers
[#12711](https://github.com/ethereum/ethereum-org-website/issues/12711)

Fix broken link on UI and UX page

---

src/components/Footer.tsx

Update styles to match DS.
Close #10746

DS imp - Footer and Social icons

---

src/components/Glossary/GlossaryTooltip/index.tsx
src/components/Tooltip/index.tsx

Fixes invalid html around the GlossaryTooltip + use a Portal to display the tooltip content to avoid having nested divs inside inline text.

Fix hydration issue with tooltip and glossary tooltip

---

SECURITY.md

Adds initial security policy to repo
- Closes #12552

feat: Adds Security policy

---

public/content/developers/docs/consensus-mechanisms/pos/faqs/index.md

- Fixes dev docs `/consensus-mechanisms/pos/faqs` statement about validator selection
https://twitter.com/AcSunday294/status/1777928991338598839

fix: specification content detail

---

public/content/developers/tutorials/run-node-raspberry-pi/index.md

remove pre-merge comment & add airgapped option

---

public/content/enterprise/index.md
public/content/privacy-policy/index.md

chore: fix some typos in comments

---

public/content/social-networks/index.md

typo: Change unprecise date
The referring article was 2021, not last year, so it need to change this unprecise date
None

typo: Change unprecise date on a social network page

---

public/content/contributing/adding-wallets/index.md

Removes redundant copy (repeated from previous sentence)

chore: remove redundant copy

---

.github/ISSUE_TEMPLATE/suggest_wallet.yaml
public/content/contributing/adding-wallets/index.md

Updating wallet listing criteria

Updating wallet listing criteria

---

public/content/roadmap/statelessness/index.md

This should probably be "node" not "blocks".

Fix: wrong word in strong statelessness section

---

src/data/staking-products.json

Fix discord URL for Everstake Institutional
https://github.com/ethereum/ethereum-org-website/issues/10220#issuecomment-2061333727

fix: everstake institutional discord

---

public/content/community/get-involved/index.md
public/content/translations/ca/community/get-involved/index.md
public/content/translations/de/community/get-involved/index.md
public/content/translations/el/community/get-involved/index.md
public/content/translations/es/community/get-involved/index.md
public/content/translations/fa/community/get-involved/index.md
public/content/translations/fr/community/get-involved/index.md
public/content/translations/hu/community/get-involved/index.md
public/content/translations/id/community/get-involved/index.md
public/content/translations/it/community/get-involved/index.md
public/content/translations/ja/community/get-involved/index.md
public/content/translations/nl/community/get-involved/index.md
public/content/translations/pl/community/get-involved/index.md
public/content/translations/pt-br/community/get-involved/index.md
public/content/translations/ro/community/get-involved/index.md
public/content/translations/ru/community/get-involved/index.md
public/content/translations/sw/community/get-involved/index.md
public/content/translations/tr/community/get-involved/index.md
public/content/translations/uk/community/get-involved/index.md
public/content/translations/zh-tw/community/get-involved/index.md
public/content/translations/zh/community/get-involved/index.md

- Removes deprecated DAOs from /community/get-involved/
- Fixes the LexDAO link
- Updates the DAOSquare link
None filed

chore: remove deprecated DAOs from /community/get-involved/

---

src/components/CallToContribute.tsx

- Remove doge from CallToContribute component
- Update styling on H2 component in CallToContribute
Fixes: https://github.com/ethereum/ethereum-org-website/issues/7743

Remove doge from CallToContribute component

---

.github/ISSUE_TEMPLATE/suggest_wallet.yaml

Add a sentence about reaching out to wallet provider to fill out template

Add description for reaching out to wallet provider

---

public/content/dao/index.md

Update reputation example for DXdao on /daos

Update reputation example for DXdao on /daos

---

package.json
yarn.lock

Remove `focus-trap-react`, not longer needed.

Remove unused dep

---

public/content/developers/tutorials/deploying-your-first-smart-contract/index.md
public/content/developers/tutorials/guide-to-smart-contract-security-tools/index.md
public/content/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/index.md
public/content/developers/tutorials/nft-minter/index.md
public/content/developers/tutorials/optimism-std-bridge-annotated-code/index.md
public/content/developers/tutorials/the-graph-fixing-web3-data-querying/index.md

Fix some errors and typos in developer tutorials
No related issue, these errors were reported in Crowdin as mistakes in the source content

Fix errors in developer tutorials

---

public/content/developers/docs/smart-contracts/libraries/index.md

fix: resolve invalid `/audits` link in document

fix: resolve invalid`/audits` link

---

netlify.toml

Adds pages to be audited by the Netlify lighthouse plugin.

Netlify lighthouse plugin config

---

.github/workflows/build-crowdin.yml
.github/workflows/get-crowdin-contributors.yml
.github/workflows/get-leaderboard-reports.yml
.github/workflows/get-translation-progress.yml
.github/workflows/get-translations.yml
.github/workflows/import-community-events.yml

- Fix job name for `build-crowdin.yml`
- Update other job names to make them slightly more verbose

Patch workflow job names

---

public/content/dao/index.md

- Convert iframe to YouTube component to improve translations

convert iframe to YouTube component

---

public/content/developers/docs/programming-languages/dart/index.md

**The video “Integrating MetaMask into Flutter” has been made private and is no longer public.**
On the "**Ethereum for Dart Developers**" page, since the video “**Integrating MetaMask in Flutter application**” has been made **private** (the video is no longer public) and I thought the video was too old anyway, I added a new video tutorial instead, made by WalletConnect using **Web3Modal**.
Web3Modal is a open source library for integrating wallet to Flutter app, made it by WalletConnect.
Web3Modal: https://pub.dev/packages/web3modal_flutter
Also, about Web3Modal: https://docs.walletconnect.com/web3modal/about
The old video “Integrating MetaMask into Flutter”: https://youtu.be/8qzVDje3IWk
New video: https://www.youtube.com/watch?v=v_M2buHCpc4
Link to related page: …

fix: dead link in Dart language in index.md file

---

.storybook/preview.ts

Currently in storybook, existing stories tied to the DS are grouped by atomic design composition hierarchy. This PR updates the preview config to sort the hierarchy in the sidebar of the Storybook UI, from smallest to largest.

chore(.storybook): sort stories by atomic design composition

---

src/@chakra-ui/components/Tag/index.ts
src/@chakra-ui/components/Tag/utils.ts
src/components/FindWallet/WalletTable/index.tsx

Added a new variant for highContrast for the tag in the find Wallet Page. [Fixes #12647 ]

Added a HighContrast variant for tags

---

.github/workflows/stale.yml

Revert autoclosing stale issues

---

public/content/translations/de/staking/solo/index.md

- Href path was translated; reverts

fix: German resource link href

---

src/hooks/useSurvey.ts

- Adds `locale` to the path being logged with the useSurvey

fix: add locale to useSurvey URL being logged

---

public/content/enterprise/index.md

Added Moralis to enterprise products and services.

Added Moralis to enterprise products and services

---

public/content/community/language-resources/index.md

Added Modular Crypto as an educational resource in Brazilian Portuguese.
#12894

Added Modular Crypto Link under resources

---

src/layouts/RootLayout.tsx

Commenting out TranslationBanner components until logic for rendering right banner is resolved

Comment out TranslationBanner components until logic is fixed

---

public/content/developers/docs/intro-to-ether/index.md

Fix typo in intro to ether developer doc

---

public/content/nft/index.md

- Add NFTScan to /nft page
Fixes https://github.com/ethereum/ethereum-org-website/issues/9665

Add NFTScan to /nft

---

public/content/developers/docs/nodes-and-clients/client-diversity/index.md

Update client diversity developer doc - comma misplaced

---

src/data/layer-2/layer-2.ts

Added token list to zkSync L2 summary
Apologies @wackerow for not doing this in last PR

chore: add tokenlist to zksync

---

public/content/zero-knowledge-proofs/index.md

Resolves #11744
- Add new resource to the Further reading section

Update zero knowledge proofs index.md

---

src/components/Hero/HomeHero/index.tsx

Optimizes the max width for the home hero image.

Performance: optimize max width for home hero image

---

src/layouts/UseCases.tsx

Adds the missing `sizes` prop for the hero image in the use cases layout. This will create lighter images for smaller resolutions.
Example https://deploy-preview-13024--ethereumorg.netlify.app/en/nft/

Performance: optimize hero image for use cases layout

---

public/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

We would like to propose the updated information for public RPC endpoints powered by All That Node.

Update nodes as a service developer doc (all that node)

---

src/data/community-events.json

Adding ETHMilan 2024 to Community Events List

Adding ETHMilan 2024

---

src/intl/en/page-developers-index.json
src/intl/pl/page-developers-docs.json

Changed the Polish translation in page-developers-docs.json file and added a missing dot in the page-developers-index.json so that all the 4 texts end with a dot

Correct 2 things on page-developers

---

public/content/desci/index.md

CryoDAO is a DAO in the Molecule/bio.xyz ecosystem, similar to VitaDAO and ValleyDAO, but with the goal of funding high-impact research in cryopreservation (https://www.cryodao.org)
Along with its sister DAOs already listed (VitaDAO & ValleyDAO), CryoDAO meets the qualifications listed here: https://ethereum.org/en/contributing/adding-desci-projects/
CryoDAO has raised $3M+ to date to fund and advance cryopreservation research with a global community on Ethereum.
https://github.com/ethereum/ethereum-org-website/issues/13034

Add CryoDAO to DeSci project list

---

src/data/wallets/wallet-data.ts

Removed duplicated MyEtherWallet item from wallets listing

---

public/content/staking/saas/index.md

Corrects a typo.
- Fixes #13117

fix: typo [fixes #13117]

---

src/components/FindWallet/MobileFiltersMenu.tsx
src/components/FindWallet/WalletTable/SupportedLanguagesTooltip.tsx
src/components/FindWallet/WalletTable/index.tsx
src/hooks/useWalletTable.tsx
src/lib/types.ts
src/lib/utils/wallets.ts
src/pages/wallets/find-wallet.tsx

Fixes hydration issues by:
- sorting the wallets list at build time
- replacing the table/th/tr/td components with divs because it was throwing invalid html errors
- format the languages support for each wallet at build time
Main improvement in Task 2 (first render), nearly 1 second faster using CPU 4x slowdown + slow 4g connection.
Current dev
- Task 1: 500ms
- **Task 2: 3s**
- Task 3: 1.5s
Fixing hydration issue
- Task 1: 500ms
- **Task 2: 2s**
- Task 3: 1.2s
- https://deploy-preview-13066--ethereumorg.netlify.app/en/wallets/find-wallet

Performance: fix hydration issues on find wallets page

---

src/data/staking-products.json

Updates Stakewise permissionless nodes status to `true`
- Closes #13131

Update: Stakewise to permissionless nodes [Fixes #13131]

---

public/content/developers/docs/standards/index.md
public/content/developers/docs/standards/tokens/erc-20/index.md
public/content/developers/docs/standards/tokens/index.md
src/data/developer-docs-links.yaml

- Update information architecture of standards section

update IA of standards section

---

public/content/developers/docs/accounts/index.md

This looks good!  I made a few small changes related to readability and reducing word count

Update accounts developer docs

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/event_listing.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/suggest_dapp.yaml
.github/ISSUE_TEMPLATE/suggest_dev_tool.yaml
.github/ISSUE_TEMPLATE/suggest_exchange.yaml
.github/ISSUE_TEMPLATE/suggest_glossary_term.yaml
.github/ISSUE_TEMPLATE/suggest_layer2.yaml
.github/ISSUE_TEMPLATE/suggest_quiz.yaml
.github/ISSUE_TEMPLATE/suggest_staking_product.yaml
.github/ISSUE_TEMPLATE/suggest_tutorial.yaml
.github/ISSUE_TEMPLATE/suggest_wallet.yaml
.github/release-drafter.yml

- Updates labels associated with issue templates and release drafter
- Uses "product" label instead of "feature/content" for product listing requests
Ongoing GH management initiatives

chore: update issue template and release drafter labels

---

public/content/developers/docs/accounts/index.md

Minor update to clarify the meaning of an account in the context of a wallet, considering both EOAs as well as contract accounts.
- Closes #12061

Clarify account in the context of a wallet

---

src/@chakra-ui/components/Table.ts

- Changes textTransform from 'capitalized' to 'normal' for how we do capitalization on titles/headers
Fixes: https://github.com/ethereum/ethereum-org-website/issues/12045

Change textTransform from 'captialized' to 'normal' for Table component

---

public/content/developers/docs/smart-contracts/anatomy/index.md

Transactions are no longer mined but kind of validated and included in the block by the selected validator.

Transaction mined -> validated since we're no longer PoW

---

public/content/contributing/index.md

Galxe OAT URL fixed on [https://ethereum.org/en/contributing/#oat](https://ethereum.org/en/contributing/#oat)
- Fixes #13180

fixed issue 13180 - Galxe link

---

public/content/decentralized-identity/index.md

Adds Veramo to /decentralized-identity page
Fixes https://github.com/ethereum/ethereum-org-website/issues/7180

Add Veramo to /decentralized-identity

---

src/data/externalTutorials.json

- Adds external tutorial for Issuing and Verifying Ethereum DIDs with Metamask
Fixes: https://github.com/ethereum/ethereum-org-website/issues/9060

Add Suggest a tutorial: Issuing And Verifying Ethereum DIDs with Metamask

---

public/content/community/language-resources/index.md

added two more Russian language resources
https://github.com/ethereum/ethereum-org-website/issues/11701

Expanded the list of Russian-language resources

---

src/data/community-events.json

Add ETHKL 2024 event to upcoming events list

event: add ethkl 2024 to community events

---

src/components/MeetupList.tsx
src/data/community-meetups.json

- Fixes namespace bug causing "no results" strings to be broken
- Cleans up `emoji` fields inside `community-meetups.json` to remove uses of two-character region codes or emojis, and utilize full region names instead (which parse to the same flags that were already shown).
- Expanded the filtering/searching to take advantage of these region names, allowing a user to search by a country name
https://deploy-preview-13216--ethereumorg.netlify.app/en/community/events/#meetups
https://ethereum.org/en/community/events/

Meetup list improvements

---

yarn.lock

Regenerates the `yarn.lock` file as it is inconsistent when you install deps.

Regenerate yarn lock

---

src/data/quizzes/questionBank.ts

fix: correct quiz answer [Fixes #13248]

---

src/components/AssetDownload/index.tsx

Ignores the `locale` from the image generated links.

Fix assets download links

---

src/components/AssetDownload/index.tsx

Hotfix version of https://github.com/ethereum/ethereum-org-website/pull/13251

hotfix: Fix assets download links

---

public/content/community/language-resources/index.md

- Adds resources on the `/community/language-resources` page for Hebrew
- Closes: https://github.com/ethereum/ethereum-org-website/issues/9087

Add Hebrew resources

---

public/content/developers/docs/nodes-and-clients/nodes-as-a-service/index.md

As suggested in the issue, I made the following changes.
-  Fixed bulletpointing and indentation issues for Zeeve and Tokenview entries.
-  Sorted the entire list alphabetically for better readability.
-  Added bold formatting to highlight the DRPC name.
-  Corrected "API’s" to "APIs" for consistent grammar.
-  Capitalized "RPC" and "WSS" in the phrase "Both rpc and wss endpoints are open to use" for consistency and clarity.
Closes #12046

Documentation Formatting and Consistency [Fixes #12046]

---

public/content/about/index.md

Adds initial security policy to repo
- Closes #11586

feat: Adds License section to about page

---

README.md

- Update README image paths after updates from #13166
- Fixes #13308

fix: image paths for README embeds [Fixes #13308]

---

public/content/community/support/index.md
public/content/developers/docs/nodes-and-clients/index.md
public/content/developers/docs/nodes-and-clients/run-a-node/index.md
public/content/developers/docs/programming-languages/rust/index.md
public/content/governance/index.md

Reth is officially the fifth Ethereum execution client with a production level release.
- Adds Reth where existing execution clients are listed
- Some linting and cleanup as well
- None filed

Reth update

---

public/content/developers/docs/design-and-ux/index.md

- Dead links removed or fixed
- Added a link to [Web3 UX Design Handbook](https://web3ux.design/) as a useful resource, which includes 2 previously linked articles

Fixed or deleted dead links in docs/design-and-ux

---

public/content/translations/es/contributing/quizzes/index.md

- fix: mardown syntax from crowdin import

fix: mardown syntax from crowdin import

---

public/content/developers/docs/networking-layer/portal-network/index.md

Changed lowercase abbreviations to uppercase
Added space between numbers and units (it seems this is the usual style of the website)
Added "space" for disk 
- Fixes #13362

Change lowercase abbreviations to uppercase [Fixes #13362]

---

src/components/Footer.tsx
src/intl/en/common.json

- Set up "Go to top" button in Footer for translation

Setup "Go to top" button for translation

---

public/content/eips/index.md

Fix typo in EIPs learn page

---

public/content/about/index.md

Updated the Product Roadmap link to Q3 in the About Page
Updated the outdated Product Roadmap link from Q1 to Q3 in the About Page to solve issue #13402
#13402

Update index.md in About

---

src/data/wallets/wallet-data.ts

Update shapeshift to not new to crypto

---

.github/workflows/chromatic.yml

Add the tailwind config and `src/styles` directory as paths to trigger the Chromatic CI action on change

ci(workflows/chromatic): add tailwind paths for trigger

---

src/styles/global.css
tailwind.config.ts

Writes the semantic tokens for the complementary colors in the Tailwind config.
Forgot to be included in #13347

refactor(global.css): add complementary color semantics

---

src/lib/api/fetchGitHistory.ts

Removes console.log
Removes console log thats is logging looping in builds

Remove console log from fetchGitHistory.ts

---

src/styles/global.css

Correct CSS variables that are called in `global.css`, where they are currently written with dot notation when they should be kebab-case.

[Tailwind] fix(global.css): update variable annotations

---

tailwind.config.ts

- Simply token typo fix (token not implemented/used anywhere yet)

fix: name typo

---

public/content/enterprise/index.md

Removed most of the material about private chains, which have largely become obsolete and irrelevant

Update enterprise content

---

docs/review-process.md
public/content/community/research/index.md
public/content/contributing/adding-products/index.md
public/content/contributing/adding-wallets/index.md

Rectify typographical inaccuracies
This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.

fix: docs improvements

---

src/components/ActionCard.tsx
src/components/CardList.tsx
src/components/CodeModal.tsx
src/components/Codeblock.tsx
src/components/DataProductCard.tsx
src/components/EnergyConsumptionChart/index.tsx
src/components/EthVideo.tsx
src/components/Leaderboard.tsx
src/components/Logo.tsx
src/components/MeetupList.tsx
src/components/Nav/Desktop/index.tsx
src/components/Nav/Mobile/MenuFooter.tsx
src/components/Nav/useNav.ts
src/components/ProductList.tsx
src/components/Simulator/screens/ConnectWeb3/Web3App.tsx
src/components/Simulator/screens/CreateAccount/HomeScreen.tsx
src/components/Simulator/screens/SendReceive/ReceiveEther.tsx
src/components/StablecoinBoxGrid.tsx
src/components/Staking/StakingProductsCardGrid/useStakingProductsCardGrid.ts
src/components/TitleCardList.tsx
src/components/TranslationChartImage.tsx
src/components/TranslationLeaderboard.tsx
src/components/UpgradeStatus.tsx
src/pages/assets.tsx
src/pages/bug-bounty.tsx
src/pages/developers/index.tsx

Not an ideal solution but could serve as a workaround.
Manually syncs the chakra context color mode value in order to keep using the `useColorModeValue` hook from chakra.

Patch color mode sync

---

src/layouts/Translatathon.tsx

Fix links for translatathon pages in menu

Hotfix: Translatathon menu hotfix

---

.github/ISSUE_TEMPLATE/suggest_wallet.yaml

Change wording from `Does the wallet support Ethereum layer 2 networks?` -> `Which Ethereum Layer 2 networks does the wallet support?`

Update wording for layer-2 question on wallets template

---

public/content/roadmap/merge/index.md

fix grammar

---

public/content/roadmap/index.md

fix phrasing

---

public/content/defi/index.md

Corrected spelling (for a reference word)
**This typo is present across the translations.

fix: typo in custom heading id on /defi

---

src/data/community-events.json

Add ETH Shenzhen Event
Website: https://ethshenzhen.org
Update the src/data/community-events.json file
- Closes #13446

add ethshenzhen event [Fixes #13446]

---

src/data/quizzes/index.ts

I've updated the level of Scaling Quiz from `intermediate` to `advanced`
Closes #13500

Update: Quiz Metadata [Fixes #13500]

---

src/components/Nav/Menu/index.tsx
src/components/Nav/index.tsx

Desktop menu implementation using Tailwind classes.

Shadcn migration - desktop menu

---

public/content/community/get-involved/index.md

Eth R&D Discord was missing from the dev and researcher sections

Add link to Eth R&D Discord

---

src/intl/en/page-what-is-ethereum.json

Clearer what-is-ethereum-banking-card-desc

Clearer description for page-what-is-ethereum.json

---

src/components/Translatathon/LocalCommunitiesList.tsx

- Adds hubs from https://github.com/ethereum/ethereum-org-website/issues/13590
closes https://github.com/ethereum/ethereum-org-website/issues/13590

[hotfix] add new translatathon hubs

---

src/components/Translatathon/DatesAndTimeline.tsx

- Removes end date for results

Change end date for results

---

src/components/Search/index.tsx

- Repeat of #13604, but directly into `master` for high priority bug fix
- Fixes #13603

[Hotfix] docsearch transform

---

src/components/Translatathon/TranslatathonPrizes.tsx

- Adds Devcon ticket prize information for Translatathon

Add Devcon ticket prize info

---

public/content/developers/docs/nodes-and-clients/light-clients/index.md

fixed incorrect URL

---

public/content/nft/index.md

Typo in NFT page

---

public/content/roadmap/verkle-trees/index.md

Update verkle testnet number

---

src/components/BannerGrid/index.tsx
src/styles/global.css
tailwind.config.ts

Migrate BannerGrid to tailwind.

Shadcn migration - BannerGrid

---

public/content/developers/docs/gas/index.md

Adding another Gas tracking to the list of resources
https://www.ethgastracker.com/
It tracks gas prices on Ethereum mainnet and several L2s (Arbitrum, Optimism, Base) and provides an API to integrate

Add ethgastracker

---

src/pages/staking/index.tsx
tailwind.config.ts

Migrate page to use ShadCN/Tailwind and import the new UI components used.

[ShadCN] refactor(pages/staking): migrate page to ShadCN

---

src/components/ui/buttons/Button.tsx

fix: ButtonLink button props and cn merging
None filed

fix: ButtonLink button props and cn merging

---

public/content/bridges/index.md

I have added three resources that provide summary information about bridges. These resources aim to enhance the understanding of bridges in the context of the Ethereum ecosystem.
1. [L2BEAT](https://l2beat.com/) (as proposed)
2. [DefiLlama](https://defillama.com/)
3. [Alchemy's Ethereum Bridge Page](https://www.alchemy.com/list-of/web3-bridges-on-ethereum)
This pull request addresses issue [#12450](https://github.com/ethereum/ethereum-org-website/issues/12450).

add use bridge content [Fixes #12450]

---

.github/workflows/wallets-check.yml

Test wallets workflow

---

.github/workflows/wallets-check.yml
src/data/wallets/wallet-data.ts

Fix workflow [test]

---

.github/workflows/wallets-check.yml
src/data/wallets/wallet-data.ts

Update wallets check workflow

---

.github/workflows/wallets-check.yml
src/data/wallets/wallet-data.ts

Re-add rabby & update workflow

---

public/content/developers/docs/storage/index.md

Updated the information of 0chain storage solution.
Closes #13324

Updated: 0chain Info [Fixes #13324]

---

src/components/TranslationChartImage/TranslationChartImage.stories.tsx
src/components/TranslationChartImage/index.tsx

Create story tests for TranslationChartImage component [#13734]

---

public/content/developers/docs/design-and-ux/index.md

Adding direct links to the next pages in “Design Fundamentals/Intro to design and UX” for greater visibility

Add links to subitems in design and ux docs

---

public/content/developers/docs/design-and-ux/index.md

added 2 new research resources

updating resources design and ux

---

public/content/developers/docs/frameworks/index.md

Added veramo as framework inside `/en/developers/docs/frameworks/`
https://github.com/ethereum/ethereum-org-website/issues/11157

Added veramo as framework

---

.storybook/preview.tsx
src/components/Glossary/GlossaryTooltip/GlossaryTooltip.stories.tsx
src/components/Tooltip/Tooltip.stories.tsx

Adds the `TooltipProvider` to the SB preview to share it with all the stories.

Fix chromatic errors with tooltip stories

---

.storybook/preview.tsx
src/components/Glossary/GlossaryTooltip/GlossaryTooltip.stories.tsx
src/components/Tooltip/Tooltip.stories.tsx

[staging] Fix sb tooltip provider

---

src/components/EventCard.tsx
src/components/LanguagePicker/index.tsx
src/components/Search/SearchButton.tsx

Replaces `react-i18next` with `next-i18next` to fix hydration issues.

Fix i18n hydration issues

---

src/components/Tooltip/index.tsx

Adjusts the max width of the container to avoid dead space in content and sets the delay duration to 200ms.

Tooltip updates

---

src/pages/assets.tsx

Fix assets anchor links
Fixes #13805

fix: brand assets href links

---

src/components/Banners/BannerNotification.tsx
src/components/Banners/DismissableBanner/index.tsx
src/layouts/UseCases.tsx

- migrate BannerNotification to tw
- including `DismissableBnner`
Ongoing tw migration

feat: migrate BannerNotification to tw

---

src/components/Homepage/useHome.ts
src/hooks/useClipboard.ts
src/pages/index.tsx

Refactor the custom `useClipboard` hook to clean it up a bit.

refactor use clipboard

---

public/content/desci/index.md

- Adds article and youtube links to further reading/videos sections of the `/desci` page
- Closes #11091

feat: list desci article/video ref [Closes #11091]

---

public/content/about/index.md
public/content/community/support/index.md
public/content/security/index.md

we should include on 
/about
/security
/support
pages small paragraph that nobody with ethereum.org will ever email you asking for stuff

adding line about ethereum.org will never message you

---

public/content/developers/docs/gas/index.md
public/content/smart-contracts/index.md

Wraps frontmatter values in double quotes to escape special characters.

Fix md files

---

src/data/community-events.json

add ETHSydney hackathon, 25-27 October

add ETHSydney hackathon

---

src/components/Hero/HubHero/index.tsx
src/styles/global.css
tailwind.config.ts

Fixes the bg color in `HubHero` component. The necessary colors were not defined under the `colors` section in the tailwind config file.

Fix bg color in `HubHero` component

---

src/pages/index.tsx

Marks external images used in events and blog posts as lazy loaded.

Home page: lazy load images

---

src/data/staking-products.json

Updates Everstake details
- Fixes #13846

chore: update staking-products.json

---

src/components/Buttons/SvgButtonLink.tsx
src/components/Homepage/BentoCard.tsx
src/components/Homepage/useBentoBox.ts
src/components/Homepage/useHome.ts
src/components/ui/card.tsx
src/lib/interfaces.ts
src/pages/index.tsx

Sets up Matomo custom events for homepage elements
- #13528

Homepage: matomo events

---

src/pages/index.tsx

Currently we are experiencing a hydration issue that forces to render the entire node tree again.
Fixes duplicate key issue.

Hotfix hydration issue

---

public/content/history/index.md

The description of EIP-1052 was incorrect. This pull request updates the summary text to accurately describe what EIP-1052 did.

Update history/index.md: Fix description of EIP-1052

---

src/data/quizzes/index.ts

moving merge quiz from basics

---

public/content/guides/index.md

people seem to be searching how to connect wallet a lot, therefore adjusting the copy to mention this

updating guides hub to mention connect to projects (based on UXR)

---

public/content/developers/docs/nodes-and-clients/index.md

fix: markdown table syntax

---

src/layouts/Tutorial.tsx

Migrates the Tutorials layout to Tailwind.

Shadcn migration - tutorials layout

---

src/layouts/Docs.tsx

Migrates the Docs layout to Tailwind.

Shadcn migration - docs layout

---

CODE_OF_CONDUCT.md

- Adds `CODE_OF_CONDUCT.md` for GitHub repo
- Fixes #11504

feat: create CODE_OF_CONDUCT.md [Fixes #11504]

---

src/components/Banners/BugBountyBanner/index.tsx
src/components/Banners/UpgradeBannerNotification.tsx
src/components/CopyToClipboard.tsx
src/components/EnvWarningBanner.tsx
src/components/EthVideo.tsx
src/components/FeaturedText/index.tsx
src/components/Glossary/GlossaryDefinition/index.tsx
src/components/IdAnchor.tsx
src/components/LearningToolsCardGrid.tsx
src/components/MarkdownImage.tsx
src/components/MdComponents/index.tsx
src/components/MergeArticleList.tsx
src/components/StatErrorMessage.tsx
src/components/TranslationChartImage/index.tsx
src/components/YouTube.tsx
src/pages/what-is-ethereum.tsx

Migrate the following components to TW.
- Banners/UpgradeBannerNotification.tsx
- Banners/BugBountyBanner/index.tsx
- CopyToClipboard.tsx
- EnvWarningBanner.tsx
- EthVideo.tsx
- FeaturedText/index.tsx
- IdAnchor.tsx
- LearningToolsCardGrid.tsx
- MarkdownImage.tsx
- MergeArticleList.tsx
- StatErrorMessage.tsx
- TranslationChartImage/index.tsx
- YouTube.tsx

Shadcn migration - more components

---

src/pages/assets.tsx

Master -> staging

---

src/components/ui/tabs.tsx

Fixes the overflow allowing the text to wrap.

Fix tabs overflow

---

src/components/DevconGrantsBanner.tsx

Migrate `DevconGrantsBanner` to tailwind
#13946

Shadcn migrate - DevconGrantsBanner

---

public/content/developers/docs/networking-layer/portal-network/index.md

Fixes wrong shisui (portal network client) address

---

public/content/developers/docs/nodes-and-clients/bootnodes/index.md

chore(typo): build in => builtin

---

src/components/DeveloperDocsLinks.tsx

Migrate `DeveloperDocsLinks` to tailwind.
#13946

Shadcn migration - DeveloperDocsLinks

---

public/content/developers/docs/data-and-analytics/block-explorers/index.md

This pull request adds Ethseer, a beacon chain blockchain scanner developed by Migalabs, to the [Block Explorers](https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/#services) section of the Ethereum documentation. Ethseer provides in-depth insights into the beacon chain, helping users understand the blockchain’s performance and activity.
There is no related issue for this pull request, as this addition introduces a new tool to the block explorers documentation and does not resolve an open issue.

Add Ethseer to the Block Explorers section

---

src/components/History/NetworkUpgradeSummary.tsx

Migration of History/NetworkUpgradeSummary component to Tailwind

Migrate History/NetworkUpgradeSummary to tailwind

---

public/content/community/online/index.md

I've added a listing policy for the `Online Communities` page, outlining the eligibility criteria and content guidelines.
Closes #10790

chore: add listing policy for online communities [Fixes #10790]

---

src/scripts/crowdin/translations/getTranslations.ts
src/scripts/crowdin/translations/utils.ts

- Removes problematic portions of crowdin-ci workflow
- Checks if path exists before attempting to stage
- Fixes action failures

fix: crowdin-ci workflow

---

src/components/Staking/StakingProductsCardGrid/index.tsx

Migrate Staking/StakingProductsCardGrid component to Shadcn/tailwind

Migrate Staking/StakingProductsCardGrid component to Shadcn/tailwind

---

src/lib/constants.ts

- Updates ethstaker blog xml feed url
- #14171

fix: ethstaker blog xml feed

---

src/lib/constants.ts

Brings in #14171,  #14174, #14181.

Hotfix rss feed

---

README.md

Added info about OATs, updated and deleted some old info about POAPs
- Fixes #14169

Updated POAP section of README

---

CONTRIBUTING.md

Fixed the image source in CONTRIBUTING.md, so the image is now visible.

Fixed the image source in CONTRIBUTING.md

---

src/components/Translatathon/LocalCommunitiesList.tsx

Migrate `LocalCommunitiesList` component to tailwind  from Chakra

Migrate  `LocalCommunitiesList` to tailwind

---

src/data/wallets/wallet-data.ts

https://github.com/ethereum/ethereum-org-website/issues/14270

Update wallet-data.ts - BlockWallet

---

src/data/community-events.json

fix: remove broken image url

---

src/components/Footer.tsx

- Reduce padding on footer element by 4
- Move the 4 padding to internal divs
Found during QA testing

fix padding bug on footer

---

src/data/community-meetups.json

Added ETHCluj community
Updated the `community-meetups.json` with details of ETHCluj community.
#14483

ETHCluj community to community-meetups.json

---

src/data/community-events.json

Update community-events.json to add upcoming ETHLisbon event

---

src/components/Layer2NetworksTable/NetworksNoResults.tsx

fix empty state labels

---

public/content/developers/docs/nodes-and-clients/client-diversity/index.md

I added a link to the CL client Grandine.

Client Diversity Page Update

---

src/components/Stat/index.tsx

Migrated `Stat/index.tsx` to shadcn/tailwind
#13946

Migrated stat component to shadcn/tailwind

---

src/components/Translatathon/StepByStepInstructions.tsx

Changes:
- Replaced Chakra UI components (Flex, Text, Button) with Shadcn/Tailwind equivalents.
- Used Tailwind CSS for layout and styling.

Migrate StepByStepInstructions.tsx to Shadcn/tailwind

---

src/components/ProductList.tsx

migrate ProductList component to tailwind

---

public/content/staking/solo/index.md

added missing word for clarity

Update index.md - added missing word for clarity

---

src/data/consensus-bounty-hunters.json
src/data/execution-bounty-hunters.json

Adding alpharush to bug bounty

Adding alpharush to bug bounty

---

src/lib/constants.ts

Added ECH newsletter in the "Recent posts" section on [ethereum.org's main page](https://ethereum.org/en/), as well as a link to [ECH's Medium page](https://medium.com/ethereum-cat-herders) in the "Read more on these websites" section.
- Fixes #14607

add ECH newsletter

---

src/intl/en/page-index.json

fix the tooltip typo:
principal -> principle
https://github.com/ethereum/ethereum-org-website/issues/14610

Fix typos on homepage

---

public/content/contributing/index.md

Fixed broken link on [More On OATs]
Old broken link: https://help.galxe.com/en/articles/7067290-galxe-oats-reward-and-celebrate-achievements
New link: https://help.galxe.com/en/articles/9645630-create-quest-rewards#h_1c5d63ba03

Fixed broken link on Contributing Page

---

src/components/Layer2NetworksTable/NetworksSubComponent.tsx
src/components/Layer2NetworksTable/hooks/useNetworkColumns.tsx
src/components/StatsBoxGrid/useStatsBoxGrid.tsx
src/data/networks/networks.ts
src/lib/api/fetchGrowThePieMaster.ts
src/pages/layer-2/networks.tsx

lowercased growthepie (instead of Growthepie or GrowThePie)

---

src/crons/revalidate-layer-2-networks-page.ts
src/crons/revalidate-layer-2-page.ts

- Adds revalidation crons for /layer-2 and /layer-2/networks pages

add revalidation crons for layer-2 pages

---

public/content/developers/tutorials/uniswap-v2-annotated-code/index.md

Fixes a typo in the developer tutorial uniswap
N/A

docs: fix typo in uniswap

---

public/content/developers/docs/data-and-analytics/block-explorers/index.md

Correct a missing ')' in `public/content/developers/docs/data-and-analytics/block-explorers/index.md`
None

Correct a missing ')' in docs

---

src/components/Banners/BugBountyBanner/index.tsx

Minor update to bug bounty banner text

Update bug bounty banner text

---

public/content/translations/zh/defi/index.md

Hi, team!
Updated broken link to their current versions. https://aave.com/flash-loans/

Broken link index.md

---

src/pages/contributing/translation-program/contributors.tsx

Shadcn Migrate `contributing/translation-program/contributors.tsx`

Shadcn Migrate: contributing/translation-program/contributors.tsx

---

src/pages/contributing/translation-program/acknowledgements.tsx

Migrate acknowledgements page to Shadcn

Shadcn Migrate: Migrate acknowledgements page to Shadcn

---

src/pages/learn.tsx

Migrate src/learn.tsx to shadcn

Shadcn Migrate: Migrate learn page to shadcn

---

src/pages/staking/deposit-contract.tsx

Migrate staking/deposit-contract page to Shadcn

Shadcn Migrate: staking/deposit-contract.tsx

---

src/data/community-events.json

- Updates community events
- Removes duplicates
- Adds a few missing images
- Removes all 2024 events

Event cleanup

---

src/pages/developers/local-environment.tsx

Migrate `developers/local-environment.tsx`  to Shadcn

Shadcn Migrate: developers/local-environment.tsx 

---

src/pages/assets.tsx

Shadcn Migrate: assets.tsx 

---

src/pages/run-a-node.tsx

Migrate run-a-node page to Shadcn

Shadcn Migrate: run-a-node.tsx

---

src/components/CallToContribute/index.tsx

Migrate `CallToContribute/index.tsx` to Shadcn

Shadcn Migrate: CallToContribute/index.tsx

---

src/components/Roadmap/RoadmapActionCard/index.tsx

Migrate `Roadmap/RoadmapActionCard/index.tsx` to Shadcn

 Shadcn Migrate: Roadmap/RoadmapActionCard/index.tsx

---

src/data/community-events.json

Add ETHDubai 2025 conference and hackathon dates

Add ETHDubai 2025 conference and hackathon dates

---

src/pages/dapps.tsx

Migrate Dapps page to Tailwind/ShadCn
#13946

Migrate Dapps page to Tailwind/ShadCn

---

src/components/IssuesList/index.tsx

Migrate `IssuesList/index.tsx` to Shadcn

Shadcn Migrate: IssuesList/index.tsx

---

src/data/community-events.json

Adding EthDam III Hackathon in May '25

---

public/content/about/index.md

Update [ethereum.org product roadmap](https://ethereum.org/en/about/#roadmap)
N/A

Update ethereum.org roadmap

---

public/content/community/online/index.md

Small change since Peerhana is now Peera community forums

Update index.md Peera community forums has a new domain and name

---

src/components/FindWalletProductTable/hooks/useWalletFilters.tsx

Added event tracking for chain selection on find-wallet page 
https://github.com/ethereum/ethereum-org-website/issues/14778

Added event tracking for chain selection on find-wallet page 

---

public/content/translations/pt-br/developers/docs/dapps/index.md

Description
Corrected minor typos and formatting inconsistencies.
Fix: Corrected *Benefícios*(Benefits) to *Desvantagens*(Drawbacks)
Fix: Corrected *rápido*(quick) to *rapidamente* (Quickly)

Fix typos and grammar in index.md

---

src/data/wallets/wallet-data.ts

based on https://www.walletbeat.fyi/ data

Update wallet-data.ts - frame

---

src/data/community-meetups.json

Add ERC55 on Ethereum meetups
https://github.com/ethereum/ethereum-org-website/issues/14757

Add ERC55 on Ethereum meetups

---

src/data/wallets/wallet-data.ts

based on https://www.walletbeat.fyi/

Update wallet-data.ts - Aurox

---

src/data/wallets/wallet-data.ts

based on https://www.walletbeat.fyi/

Update wallet-data.ts - gem wallet

---

public/content/developers/docs/bridges/index.md

- Added a deep dive that focuses on newer designs that enable interoperability between Ethereum rollups (e.g., intent bridging and keystore rollups) to the further reading section
- Added an article analyzing security properties of different bridging designs
- Added L2Beat bridge risk framework

Add resources on rollup interoperability to bridges for developers page

---

src/pages/stablecoins.tsx

This PR fixes an invalid hyperlink
https://github.com/ethereum/ethereum-org-website/issues/14776#event-16127453112

Replace invalid hyperlink

---

public/content/governance/index.md

Added two articles that explain how Ethereum governance works and and describe various players involved in coordinating changes to the network in detail

Add resources to governance page

---

public/content/bridges/index.md

- Added an article on newer rollup interoperability protocols (including intent bridging and keystore rollups)
- Added an article analyzing security properties of different bridging designs

Add resources to bridges page

---

README.md

A typo was made in the documentation

Docs: Fix Typo

---

public/content/bridges/index.md

For issue https://github.com/ethereum/ethereum-org-website/issues/13872

Word choice

---

public/content/translations/ca/defi/index.md

docs: update ca/defi/index.md

---

src/data/consensus-bounty-hunters.json
src/data/execution-bounty-hunters.json

Bounty Hunter point updates

---

public/content/developers/docs/oracles/index.md

I added RedStone Oracles to the list of available blockchain oracles. No other changes more made. 
- Ari Kimelman

Updated index.md to include RedStone Oracles in the list of Oracles. 

---

src/data/networks/networks.ts
src/data/wallets/wallet-data.ts

Current dev branch is breaking due to a missmatch in one of the networks name.
- Updates "Taiko Mainnet" to "Taiko Alethia"

Fix taiko network name

---

src/components/Simulator/Explanation.tsx
src/data/WalletSimulatorData.tsx

Migrates component content from `walletOnboardingSimData` to ShadCN/Tailwind

[ShadCN]: migrate wallet simulator data object

---

public/content/developers/docs/scaling/optimistic-rollups/index.md

- Added a comprehensive article analyzing the different types of rollups (including newer designs like sovereign rollups)
- Added a research report on fraud proof systems used by Ethereum L2s

Update further reading section on optimistic rollups page

---

public/content/developers/docs/scaling/zk-rollups/index.md

- Added a comprehensive article analyzing the different types of rollups (including newer designs like sovereign rollups)
- Added a resource to help readers understand ZK-EVMs as a scaling solution for Ethereum

Update further reading section on ZK-rollups page

---

public/content/developers/docs/scaling/validium/index.md

- Added a comprehensive article analyzing the different types of rollups, including newer designs like sovereign rollups (validiums are similar to sovereign rollups with validity proofs and off-chain data availability)
- Added a Vitalik article on exit games for EVM validiums

Update further reading section of validiums page

---

public/content/developers/docs/gas/index.md

- Added an article that explains Ethereum's transaction fee mechanism design in detail and addresses common misconceptions about EIP-1559 
- Added an article on multidimensional gas pricing

Update further reading section on EIP-1559 page

---

src/components/Layer2NetworksTable/NetworkMaturityTooltip.tsx

Rearrange the color according to the maturity
https://github.com/ethereum/ethereum-org-website/issues/14759

switch tagging color on layer 2 networks page

---

src/pages/[locale]/stablecoins.tsx

fix: Fix wrong translation keys on stablecoins page

---

public/content/community/online/index.md

ethereum acc is no longer EF account

update X accounts after ethereum foundation split

---

src/data/consensus-bounty-hunters.json
src/data/execution-bounty-hunters.json

bounty leaderboard update

---

public/content/decentralized-identity/index.md

A grammatical mistake in the benefits section. The verb "facilitates" was used with "solutions," which is plural, so it should be "**facilitate**."
tnks!

docs: fix verb agreement in benefits section

---

src/pages/[locale]/stablecoins.tsx

This PR updates the TrueUSD website link as the former wasn't working again.
#15045

Fix: Updated TrueUSD link

---

public/content/developers/docs/design-and-ux/index.md

removing dead projects from the lists in designer docs

deleting deadlinks

---

src/data/community-events.json

- Adds EthAsia to community-events.json

Add EthAsia event

---

src/components/Footer.tsx

Changed a former name of Twitter to "X"
Also corrected a link

From twitter to x

---

src/data/wallets/wallet-data.ts

https://github.com/ethereum/ethereum-org-website/issues/15141

Update wallet-data.ts - mew

---

src/data/community-events.json

- Fixes ETH Seoul details, removes duplicate entry
- Removes duplicate ETHDubai entry
- Removes postponed Invisible Garden event

Event patches

---

app/[locale]/_components/home.tsx

- Adds human stories CTA banner to home page

human stories banner

---

src/i18n/routing.ts

Remove intl cookie

---

package.json
src/components/Footer.tsx
src/components/ui/breadcrumb.tsx
yarn.lock

- Adds link to new ethereum.org farcaster account on Warpcast
- Bumped react-icons version to utilize SiFarcaster icon

feat: add warpcast link to footer

---

public/content/developers/docs/standards/tokens/erc-1155/index.md

Update Openzeppelin docs link (version)

---

public/content/translations/fr/developers/docs/data-structures-and-encoding/rlp/index.md
public/content/translations/pt-br/developers/docs/data-structures-and-encoding/rlp/index.md

https://github.com/ethereum/ethereum-org-website/issues/15278

fix rlp example for fr and pt-br

---

src/lib/constants.ts

- Update rss `.xml` link for ethpandaops blog
Investigation of current broken production branch

hot-fix: update rss feed link for ethpandaops

---

src/data/NetworkUpgradeSummaryData.ts

Updates Pectra history with date/time, slot and epoch
https://blog.ethereum.org/2025/04/23/pectra-mainnet

Update pectra history timing values

---

src/lib/utils/translations.ts

- Fix namespace for /roadmap/vision page

fix /roadmap/vision namespace missing

---

README.md

fixing old year mention 2024 -> 2025

---

public/content/guides/how-to-swap-tokens/index.md

re-write the point to external article reference

doc: re-write the point to external article reference

---

src/data/consensus-bounty-hunters.json
src/data/execution-bounty-hunters.json

Update bounty hunters

---

.all-contributorsrc

I changed my github and linkedin handles and would like to update contributors list.

Update .all-contributorsrc with my correct details

---

src/intl/en/page-bug-bounty.json

describing the kyc process a bit more

Update page-bug-bounty.json language

---

src/lib/api/fetchGrowThePie.ts

- Removes caching growthepie fetch due to response size

no cache for fetchGrowThePie due to response size

---

app/[locale]/layer-2/page.tsx

Render page statically to mitigate potential errors from 3rd party data sources.

Hotfix render /layer-2 statically

---

src/components/TableOfContents/TableOfContentsLink.tsx

Fix some small bugs on the the inpage navigation:
- reduced the spacing on the eash link
- add primary color to active

In-page navigation spacing

---

app/[locale]/developers/page.tsx

https://deploy-preview-15477--ethereumorg.netlify.app/en/developers/
Closes: #15474

fix: missing page title

---

public/content/guides/index.md

The previous way the sentence is can be improved for more readability, which I have done.

Update index.md, break sentence and improve readability

---

README.md

docs(readme): added for ease of reading (Back to top)

---

middleware.ts

Hot fix to `master` including:
- #15518

[hot-fix] ignore matrix files from middleware

---

src/data/community-events.json

- Removes passed events
- Adds missing descriptions and imageUrls
- Updated a broken link

Events cleanup and update

---

public/content/community/grants/index.md

removal of broken links, dead projects and projects that are not aligned anymore with this page.

update grants page: removal of dead projects

---

app/[locale]/roadmap/_components/ReleaseCarousel.tsx
public/content/enterprise/use-cases/index.md
public/content/translations/ja/developers/docs/design-and-ux/heuristics-for-web3/index.md

***
This PR includes a few small updates across the repository:
- **Content Updates:**
- The URLs for "Visa Tokenized Asset Platform" and "QuarkID" have been corrected in the enterprise use cases document.
- **i18n:**
- A typo was fixed in the Japanese translation for the design and UX heuristics page (`.../ja/.../heuristics-for-web3/index.md`).
- **Chore:**
- A minor comment was updated in the `ReleaseCarousel.tsx` component.

chore: content updates and typo fixes

---

app/page.tsx

- Adds root `page.tsx` with next redirect to default locale
- Fixes local dev environment 500'ing on root path

fix: add root redirect default locale (devX)

---

app/[locale]/get-eth/page.tsx

patch: common string namespace

---

public/llms.txt

Adds a `llms.txt` file to provide structured context for LLM interactions.
The file is following the links found in:
- **Main Navigation** (`src/components/Nav/useNavigation.ts`)
- **Developer Docs** (`src/data/developer-docs-links.yaml`)
- **Footer Links** (`src/components/Footer.tsx`)
Note: it prioritize URLs pointing to the md files associated to the pages if they have one.
#15654, #15675

Initial `llms.txt` file

---

public/content/developers/docs/scaling/validium/index.md

Post 4844, blobs can also be used as DA. This PR updates the DA of validium post-4844.

fix: validium DA post-4844

---

app/[locale]/dapps/_components/dapps.tsx

previous domen is not working anymore

fix: change link to 1inch exchange

---

public/content/developers/docs/nodes-and-clients/run-a-node/index.md

Is this the wei?
Links and tool description added.
Closes https://github.com/ethereum/ethereum-org-website/issues/14209

run-a-node index.md - Update guide with prettier links and add EthPillar

---

src/intl/en/page-stablecoins.json

All other descriptions of stablecoin tools start with upper case.

Text consistency fix

---

src/data/NetworkUpgradeSummaryData.ts

Somes dates 12 hours off due to bad etherscan UI. Fixes these times

Fix history dates

---

src/lib/utils/matomo.ts

- Disabled Matomo for users with `doNotTrack` preference enabled

feat: respect doNotTrack preference for Matomo

---

app/[locale]/run-a-node/_components/run-a-node.tsx

URL of the dappnode shop was not reachable anymore. Modified link to homepage

Update run-a-node.tsx => dappnode url broken

---

app/[locale]/stablecoins/page.tsx

- Advanced the testKey being used from the development case to a production case

hot-patch: AB test restart

---

src/data/exchangesByCountry.ts
src/hooks/useCentralizedExchanges.ts
src/intl/en/common.json
src/lib/utils/intl.ts

https://deploy-preview-16014--ethereumorg.netlify.app/en/get-eth/
Closes #15995

feat: translate countries in get-eth dropdown

---

package.json
pnpm-lock.yaml

Upgrade sharp

---

app/[locale]/10years/_components/NFTMintCard/index.tsx
app/[locale]/10years/page.tsx
src/intl/en/page-10-year-anniversary.json

Finish setting up translations on /10year

/10year translations

---

src/data/audio/smart-contracts/script.md

Fix Typo in src/data/audio/smart-contracts/script.md

chore(docs): Fix Typo in src/data/audio/smart-contracts/script.md

---

instrumentation-client.ts
sentry.edge.config.ts
sentry.server.config.ts

- reduce `tracesSampleRate`
- only track `production` env

Sentry optimization

---

app/[locale]/apps/[application]/page.tsx
app/[locale]/apps/_components/AppCard.tsx
app/[locale]/apps/_components/AppsHighlight.tsx
app/[locale]/apps/_components/TopApps.tsx

Fixes prop on LinkOverlay components for matomo events

LinkOverlay customEventOptions -> matomoEvent

---

public/content/developers/tutorials/all-you-can-cache/index.md
public/content/developers/tutorials/creating-a-wagmi-ui-for-your-contract/index.md
public/content/developers/tutorials/erc-721-vyper-annotated-code/index.md
public/content/developers/tutorials/erc20-annotated-code/index.md
public/content/developers/tutorials/erc20-with-safety-rails/index.md
public/content/developers/tutorials/ethereum-for-web2-auth/index.md
public/content/developers/tutorials/ipfs-decentralized-ui/index.md
public/content/developers/tutorials/merkle-proofs-for-offline-data-integrity/index.md
public/content/developers/tutorials/optimism-std-bridge-annotated-code/index.md
public/content/developers/tutorials/reverse-engineering-a-contract/index.md
public/content/developers/tutorials/scam-token-tricks/index.md
public/content/developers/tutorials/secret-state/index.md
public/content/developers/tutorials/server-components/index.md
public/content/developers/tutorials/short-abi/index.md
public/content/developers/tutorials/uniswap-v2-annotated-code/index.md

Add a one-line link to my [personal site](https://cryptodocguy.pro/) to my tutorials.

Add links to my portfolio

---

app/[locale]/enterprise/page.tsx
src/intl/en/page-enterprise.json

- extract missing /enterprise strings

intl: extract missing /enterprise strings

---

app/[locale]/apps/categories/[catetgoryName]/page.tsx
src/intl/en/page-apps.json

- extract missing /apps/categories/[catetgoryName] string

intl: extract missing /apps/categories/[catetgoryName] string

---

.github/ISSUE_TEMPLATE/suggest_layer2.yaml
public/content/contributing/adding-layer-2s/index.md

- App portal no longer available—link removed

deprecate: optimism apps portal link

---

src/components/Banners/BugBountyBanner/index.tsx

Updated banner with relevant text

Update Bug Bounty Banner message

---

public/content/nft/index.md

[Text] Add missing space

---

public/content/zero-knowledge-proofs/index.md

- add zk game learning resource : zk-cards

Add resource to learn zk via game in index.md

---

src/components/FindWalletProductTable/index.tsx
src/components/ProductTable/List.tsx
tests/e2e/find-wallet.spec.ts
tests/e2e/pages/FindWalletPage.ts

Update tests to match new virtualize list items.

Fix findwallets e2e tests

---

src/components/DevconnectBanner/Variation1/index.tsx
src/components/DevconnectBanner/Variation2/index.tsx

Style adjustments for the devconnect banner.

Hotfix banner styles

---

public/content/security/index.md

This fixes a grammatical error in the security section. The phrase should be "given by a celebrity" to correctly use passive voice.

Fix grammar: add "by" after "given" in "given a celebrity"
